cheat_menu_texts:dc.w $A01
                dc.b $D
                dc.B "EARTHWORM JIM #"
                dc.b   1,$E4,  2,  4,  8,  1,  3
                dc.B "(C)1994 SHINY ENTERTAINMENT, INC."
                dc.b   1,$DC,  2,  1,  1, $A
                dc.B "ALL RIGHTS RESERVED"
                dc.b   1,$E3,  2,  1,  9,  1,  4
                dc.B "DAVID PERRY"
                dc.b $27
                dc.B "S PRIVATE CHEAT MODE"
                dc.b   1,$DC,  2,  1,  2,  1,  8
                dc.B "         RAM BYTES USED : 00000         "
                dc.b   1,$D8,  2,  1
                dc.B "         RAM BYTES FREE : 00000         "
                dc.b   1,$D8,  2,  1
                dc.B "         ROM BYTES USED : 0000000       "
                dc.b   1,$D8,  2,  1
                dc.B "         ROM BYTES FREE : 0000000       "
                dc.b   1,$D8,  2,  2
                dc.B "  MUSIC & SOUND FX USES : 000000        "
                dc.b   1,$D8,  2,  1
                dc.B "    WORD ADDRESSES LEFT : 00000         "
                dc.b   1,$D8,  2,  1
                dc.B "  ROOM FOR SPRTLIST.68K : 00000         "
                dc.b   1,$D8,  2,  1
                dc.B "  MAX TILES TO MAKE MAP : 0000          "
                dc.b   1,$D8,  2,  2
                dc.B "         CHEAT MODE :                   "
                dc.b   1,$D8,  2,  1
                dc.B "     START ON LEVEL :                   "
                dc.b   1,$D8,  2,  1
                dc.B "      FREEZEABILITY :                   "
                dc.b   1,$D8,  2,  1
                dc.B "      MAP VIEW MODE :                   "
                dc.b   1,$D8,  2,  2
                dc.B "        PRESS THE "
                dc.w $270B
                dc.B "START"
                dc.w $827
                dc.B " BUTTON        "
                dc.b   1,$D8,  2,$EB, $B
                dc.B "          TUE 2ND. AUGUST 1994",0
