cheat_levels:   dc.B "1-NEW JUNK CITY ",0 ; CheatMenu Level Select
                dc.B "2A-HELL OR HECK?",0
                dc.B "2B-SNOWMAN BOSS ",0
                dc.B "2C-EVIL BOSS    ",0
                dc.B "3A-BUNGEE 1     ",0
                dc.B "3B-BUNGEE 2     ",0
                dc.B "3C-BUNGEE 3     ",0
                dc.B "4- PETER PUPPY  ",0
                dc.B "5- SLUG FOR BUTT",0
                dc.B "5B-HELICOPTER   ",0
                dc.B "6A-PROF"
                dc.b $27
                dc.B "S LAB   ",0
                dc.B "6C-CHICKEN FLY  ",0
                dc.B "6D-NAKED WORM   ",0
                dc.B "7- INTESTINES   ",0
                dc.B "8A-SEA TUNNELS  ",0
                dc.B "8B-POD RACES    ",0
                dc.B "9A-ASTEROIDS 1  ",0
                dc.B "9B-ASTEROIDS 2  ",0
                dc.B "9C-ASTEROIDS 3  ",0
                dc.B "9D-ASTEROIDS 4  ",0
                dc.B "9E-ASTEROIDS 5  ",0
                dc.B "9F-ASTEROIDS 6  ",0
                dc.B "9G-ASTEROIDS 7  ",0
                dc.B "10A-DARKNESS 1  ",0
                dc.B "10B-DARKNESS 2  ",0
                dc.B "10C-DARKNESS 3  ",0
                dc.B "10D-DARKNESS 4  ",0
                dc.B "10E-DARKNESS 5  ",0
                dc.B "9P -PSYCROW!    ",0
                dc.b 0