end_titles:     dc.w $901
                dc.b $D
                dc.B "EARTHWORM JIM",0
                dc.w $103
                dc.B "(C) 1994 SHINY ENTERTAINMENT, INC.",0
                dc.w $10A
                dc.B "ALL RIGHTS RESERVED",0
                dc.b   7,  7,  7,  9,  1,$10
                dc.B "PROGRAM",0
                dc.b  $A,  1, $E
                dc.B "DAVID PERRY",0
                dc.b   7,  9,  1,  9
                dc.B "ADDITIONAL PROGRAMMING",0
                dc.b  $A,  1, $D
                dc.B "NICHOLAS JONES",0
                dc.b   1, $F
                dc.B "ANDY ASTOR",0
                dc.b   7,  9,  1, $C
                dc.B "ORIGINAL CONCEPT",0
                dc.b  $A,  1, $C
                dc.B "DOUGLAS TENNAPEL",0
                dc.b   7,  9,  1, $B
                dc.B "DIRECTING ANIMATOR",0
                dc.b  $A,  1, $F
                dc.B "MIKE DIETZ",0
                dc.b   7,  9,  1, $F
                dc.B "ANIMATORS",0
                dc.b  $A,  1, $C
                dc.B "DOUGLAS TENNAPEL",0
                dc.b   1, $C
                dc.B "EDWARD SCHOFIELD",0
                dc.b   7,  9,  1, $E
                dc.B "ART DIRECTOR",0
                dc.b  $A,  1, $F
                dc.B "NICK BRUTY",0
                dc.b   7,  9,  1, $E
                dc.B "LEAD ARTIST",0
                dc.b  $A,  1, $F
                dc.B "STEVE CROW",0
                dc.b   7,  9,  1, $D
                dc.B "LEVEL DESIGNER",0
                dc.b  $A,  1, $F
                dc.B "TOM TANAKA",0
                dc.b   7,  9,  1, $D
                dc.B "INK AND PAINT",0
                dc.b  $A,  1, $E
                dc.B "ERIC CICCONE",0
                dc.b   1, $E
                dc.B "MIKE PILOTTI",0
                dc.b   7,  9,  1,$10
                dc.B "CLEAN UP",0
                dc.b  $A,  1, $D
                dc.B "CLARK SORENSEN",0
                dc.b   7,  9,  1, $C
                dc.B "ASSISTANT ARTIST",0
                dc.b  $A,  1,$10
                dc.B "LIN SHEN",0
                dc.b   7,  9,  1, $F
                dc.B "MUSIC & FX",0
                dc.b  $A,  1, $E
                dc.B "MARK MILLER",0
                dc.b   7,  9,  1, $E
                dc.B "DESIGNED BY",0
                dc.b  $A,  1,  7
                dc.B "MANY, MANY SHINY MEETINGS",0
                dc.b   7,  9,  1, $E
                dc.B "PRODUCED BY",0
                dc.b  $A,  1, $D
                dc.B "DAVID LUEHMANN",0
                dc.b   7,  9,  1, $A
                dc.B "DEVELOPMENT TOOLS BY",0
                dc.b  $A,  1, $F
                dc.B "ANDY ASTOR",0
                dc.b   1, $F
                dc.B "DAN CHANG",0
                dc.b   1,$11
                dc.B "PSY-Q",0
                dc.b   1,  9
                dc.B "ROB NORTHERN COMPUTING",0
                dc.b   7,  9,  1, $D
                dc.B "SPECIAL THANKS",0
                dc.b  $A,  1, $D
                dc.B "PLAYMATES TOYS",0
                dc.b   1, $D
                dc.B "RICHARD SALLIS",0
                dc.b   1, $F
                dc.B "BECKY TRAN",0
                dc.b   7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,$FD
