fun_texts:      dc.l new_junk_city_txt  ; text_offset
                dc.w $B0                ; x_position ; New Junk City (Text)
                dc.w $108               ; y_position
                dc.l what_the_heck_txt  ; text_offset ; What the heck (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l what_the_heck_txt  ; text_offset ; What the heck (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l what_the_heck_txt  ; text_offset ; What the heck (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l snot_a_problem_r1_txt; text_offset ; Snot a problem! round 1 (text)
                dc.w $A6                ; x_position
                dc.w $108               ; y_position
                dc.l snot_a_problem_r2_txt; text_offset ; Snot a problem! round 2 (text)
                dc.w $A6                ; x_position
                dc.w $108               ; y_position
                dc.l snot_a_problem_r3_txt; text_offset ; Snot a problem! round 3 (text)
                dc.w $A6                ; x_position
                dc.w $108               ; y_position
                dc.l for_petes_sake_txt ; text_offset ; For Pete's sake! (text)
                dc.w $A0                ; x_position
                dc.w $108               ; y_position
                dc.l buttville_txt      ; text_offset ; Buttville (text)
                dc.w $DE                ; x_position
                dc.w $108               ; y_position
                dc.l buttville_txt      ; text_offset ; Buttville (text)
                dc.w $DE                ; x_position
                dc.w $108               ; y_position
                dc.l level_5_txt        ; text_offset ; Level 5 (text)
                dc.w $E4                ; x_position
                dc.w $108               ; y_position
                dc.l level_5_txt        ; text_offset ; Level 5 (text)
                dc.w $E4                ; x_position
                dc.w $108               ; y_position
                dc.l level_5_txt        ; text_offset ; Level 5 (text)
                dc.w $E4                ; x_position
                dc.w $108               ; y_position
                dc.l intestinal_distress_txt; text_offset ; Intestinal distress! (text)
                dc.w $DA                ; x_position
                dc.w $108               ; y_position
                dc.l down_the_tubes_txt ; text_offset ; Down the tubes (text)
                dc.w $B0                ; x_position
                dc.w $108               ; y_position
                dc.l down_the_tubes_txt ; text_offset ; Down the tubes (text)
                dc.w $B0                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l andy_asteroids_txt ; text_offset ; Andy asteroids? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l who_turned_out_txt ; text_offset ; Who turned out the light? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l who_turned_out_txt ; text_offset ; Who turned out the light? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l who_turned_out_txt ; text_offset ; Who turned out the light? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l who_turned_out_txt ; text_offset ; Who turned out the light? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l who_turned_out_txt ; text_offset ; Who turned out the light? (text)
                dc.w $A9                ; x_position
                dc.w $108               ; y_position
                dc.l psycrow_txt        ; text_offset ; Psycrow! (text)
                dc.w $DC                ; x_position
                dc.w $108               ; y_position
                dc.l press_start_txt    ; text_offset ; Press start (text)
                dc.w $C8                ; x_position
                dc.w $18A               ; y_position
                dc.l options_txt        ; text_offset ; Options (text)
                dc.w $E8                ; x_position
                dc.w $1B0               ; y_position
                dc.l practice_txt       ; text_offset ; Practice (text in options)
                dc.w $D2                ; x_position
                dc.w $1AE               ; y_position
                dc.l normal_txt         ; text_offset ; Normal (text in options)
                dc.w $E6                ; x_position
                dc.w $1AE               ; y_position
                dc.l difficult_txt      ; text_offset ; Difficult (text in options)
                dc.w $DC                ; x_position
                dc.w $1AE               ; y_position
                dc.l joypad_txt         ; text_offset ; Joypad (text in options)
                dc.w $E8                ; x_position
                dc.w $184               ; y_position
                dc.l very_cool_txt      ; text_offset ; Very cool (win boss-1 in new junk city)
                dc.w $E4                ; x_position
                dc.w $140               ; y_position
                dc.l warning_txt        ; text_offset ; Warning (boss 1 in new junk city)
                dc.w $E4                ; x_position
                dc.w $140               ; y_position
                dc.l cow_launched       ; text_offset ; Cow launched (in new junk city)
                dc.w $BA                ; x_position
                dc.w $140               ; y_position
                dc.l use_your_head_txt  ; text_offset ; Use your head (?)
                dc.w $B0                ; x_position
                dc.w $164               ; y_position
                dc.l finish_him_txt     ; text_offset ; Finish him (evil boss in what the heck)
                dc.w $CC                ; x_position
                dc.w $150               ; y_position
                dc.l won_the_race_txt   ; text_offset ; Psycrow won the race (text in level)
                dc.w $E4                ; x_position
                dc.w $148               ; y_position
new_junk_city_txt:dc.l $0C000000 ! (byte_1A348E) ; New Junk City (Text)
                dc.B "N"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "W "
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "J"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "N"
                dc.l $0C000000 + (byte_1A350E)
				dc.B "K "
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "C"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "Y",0
what_the_heck_txt:dc.l $0C000000 + (byte_1A356E)
                                        ; DATA XREF: ROM:001B6918   o
                                        ; ROM:001B6920   o ...
                                        ; What the heck (text)
                dc.B "W"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "H"
                dc.l $0C000000 + (byte_1A362E)
                dc.B "A"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "T "
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "T"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "H"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "E "
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "H"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "C"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "K"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "?",0
snot_a_problem_r1_txt:dc.l $0C000000 + (byte_1A35CE)
                                        ; DATA XREF: ROM:001B6930   o
                                        ; Snot a problem! round 1 (text)
                dc.B "S"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "T "
                dc.l $0C000000 + (byte_1A362E)
                dc.B "A "
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "P"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "B"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "L"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "M!"
                dc.w $186
                dc.w $1CE
                dc.w $228
                dc.l $0C000000 + (byte_1A353E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "D "
                dc.l $0C000000 + (byte_1A356E)
                dc.B "1",0
snot_a_problem_r2_txt:dc.l $0C000000 + (byte_1A35CE)
                                        ; DATA XREF: ROM:001B6938   o
                                        ; Snot a problem! round 2 (text)
                dc.B "S"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "T "
                dc.l $0C000000 + (byte_1A362E)
                dc.B "A "
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "P"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "B"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "L"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "M!"
                dc.w $186
                dc.w $1CE
                dc.w $228
                dc.l $0C000000 + (byte_1A353E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "D "
                dc.l $0C000000 + (byte_1A356E)
                dc.B "2",0
snot_a_problem_r3_txt:dc.l $0C000000 + (byte_1A35CE)
                                        ; DATA XREF: ROM:001B6940   o
                                        ; Snot a problem! round 3 (text)
                dc.B "S"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "T "
                dc.l $0C000000 + (byte_1A362E)
                dc.B "A "
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "P"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "B"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "L"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "M!"
                dc.w $186
                dc.w $1CE
                dc.w $228
                dc.l $0C000000 + (byte_1A353E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "D "
                dc.l $0C000000 + (byte_1A356E)
                dc.B "3",0
for_petes_sake_txt:dc.l $0C000000 + (byte_1A34DE)
                                        ; DATA XREF: ROM:001B6948   o
                                        ; For Pete's sake! (text)
                dc.B "F"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "R "
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "P"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "E",$27
                dc.l $0C000000 + (byte_1A353E)
                dc.B "S "
                dc.l $0C000000 + (byte_1A348E)
                dc.B "S"
                dc.l $0C000000 + (byte_1A362E)
                dc.B "A"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "K"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "!",0
buttville_txt:  dc.l $0C000000 + (byte_1A348E)
                                        ; DATA XREF: ROM:001B6950   o
                                        ; ROM:001B6958   o
                                        ; Buttville (text)
                dc.B "B"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "U"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "V"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "I"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "L"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "L"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "E",0
level_5_txt:    dc.l $0C000000 + (byte_1A348E)
                                        ; DATA XREF: ROM:001B6960   o
                                        ; ROM:001B6968   o ...
                                        ; Level 5 (text)
                dc.B "L"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "V"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "L "
                dc.l $0C000000 + (byte_1A362E)
                dc.B "5",0
intestinal_distress_txt:dc.l $0C000000 + (byte_1A34DE)
                                        ; DATA XREF: ROM:001B6978   o
                                        ; Intestinal distress! (text)
                dc.B "I"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "S"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "T"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "A"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "L"
                dc.w $188
                dc.w $1E8
                dc.w $228
                dc.l $0C000000 + (byte_1A348E)
                dc.B "D"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "S"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "T"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "E"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "S"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "S"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "!",0
down_the_tubes_txt:dc.l $0C000000 + (byte_1A35FE)
                                        ; DATA XREF: ROM:001B6980   o
                                        ; ROM:001B6988   o
                                        ; Down the tubes (text)
                dc.B "D"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "W"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "N "
                dc.l $0C000000 + (byte_1A356E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "H"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "E "
                dc.l $0C000000 + (byte_1A353E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "U"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "B"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "S",0
andy_asteroids_txt:dc.l $0C000000 + (byte_1A34DE)
                                        ; DATA XREF: ROM:001B6990   o
                                        ; ROM:001B6998   o ...
                                        ; Andy asteroids? (text)
                dc.B "A"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "D"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "Y "
                dc.l $0C000000 + (byte_1A353E)
                dc.B "A"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "S"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "T"
                dc.l $0C000000 + (byte_1A362E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "I"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "D"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "S"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "?",0
who_turned_out_txt:dc.l $0C000000 + (byte_1A34DE)
                                        ; DATA XREF: ROM:001B69C8   o
                                        ; ROM:001B69D0   o ...
                                        ; Who turned out the light? (text)
                dc.B "W"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "H"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "O "
                dc.l $0C000000 + (byte_1A350E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "U"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "R"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "N"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "D "
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "O"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "T"
                dc.w $194
                dc.w $1B4
                dc.w $228
                dc.l $0C000000 + (byte_1A350E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "H"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "E "
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "L"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "G"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "H"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "T"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "?",0
psycrow_txt:    dc.l $0C000000 + (byte_1A34DE)
                                        ; DATA XREF: ROM:001B69F0   o
                                        ; Psycrow! (text)
                dc.B "P"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "S"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "Y"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "C"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "R"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "O"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "W"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "!",0
press_start_txt:dc.l $0C000000 + (byte_1A353E)
                                        ; DATA XREF: ROM:001B69F8   o
                                        ; Press start (text)
                dc.B "P"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "E"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "S"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "S "
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "S"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "A"
                dc.l $0C000000 + (byte_1A362E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "T",0
options_txt:    dc.l $0C000000 + (byte_1A37BA)
                                        ; DATA XREF: ROM:001B6A00   o
                                        ; Options (text)
                dc.B "O"
                dc.l $0C000000 + (byte_1A372A)
                dc.B "P"
                dc.l $0C000000 + (byte_1A381A)
                dc.B "T"
                dc.l $0C000000 + (byte_1A375A)
                dc.B "I"
                dc.l $0C000000 + (byte_1A37EA)
                dc.B "O"
                dc.l $0C000000 + (byte_1A36FC)
                dc.B "N"
                dc.l $0C000000 + (byte_1A378A)
                dc.B "S",0
practice_txt:   dc.l $0C000000 + (byte_1A34B0)
                                        ; DATA XREF: ROM:001B6A08   o
                                        ; Practice (text in options)
                dc.B "P"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "R"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "A"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "C"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "T"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "C"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "E",0
normal_txt:     dc.l $0C000000 + (byte_1A353E)
                                        ; DATA XREF: ROM:001B6A10   o
                                        ; Normal (text in options)
                dc.B "N"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "O"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "R"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "M"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "A"
                dc.l $0C000000 + (byte_1A35CE)
                dc.B "L",0
difficult_txt:  dc.l $0C000000 + (byte_1A35CE)
                                        ; DATA XREF: ROM:001B6A18   o
                                        ; Difficult (text in options)
                dc.B "D"
                dc.l $0C000000 + (byte_1A348E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A35FE)
                dc.B "F"
                dc.l $0C000000 + (byte_1A34B0)
                dc.B "F"
                dc.l $0C000000 + (byte_1A350E)
                dc.B "I"
                dc.l $0C000000 + (byte_1A359E)
                dc.B "C"
                dc.l $0C000000 + (byte_1A353E)
                dc.B "U"
                dc.l $0C000000 + (byte_1A34DE)
                dc.B "L"
                dc.l $0C000000 + (byte_1A356E)
                dc.B "T",0
joypad_txt:     dc.l $0C000000 + (byte_1A37BA)
                                        ; DATA XREF: ROM:001B6A20   o
                                        ; Joypad (text in options)
                dc.B "J"
                dc.l $0C000000 + (byte_1A372A)
                dc.B "O"
                dc.l $0C000000 + (byte_1A381A)
                dc.B "Y"
                dc.l $0C000000 + (byte_1A375A)
                dc.B "P"
                dc.l $0C000000 + (byte_1A37EA)
                dc.B "A"
                dc.l $0C000000 + (byte_1A36FC)
                dc.B "D",0
very_cool_txt:  dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A28   o
                                        ; Very cool (win boss-1 in new junk city)
                dc.B "VERY COOL",0
                dc.b 0
warning_txt:    dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A30   o
                                        ; Warning (boss 1 in new junk city)
                dc.B "WARNING",0
cow_launched:   dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A38   o
                                        ; Cow launched (in new junk city)
                dc.B "COW LAUNCHED",0
use_your_head_txt:dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A40   o
                                        ; Use your head (?)
                dc.B "USE YOUR HEAD!",0
finish_him_txt: dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A48   o
                                        ; Finish him (evil boss in what the heck)
                dc.B "FINISH HIM!",0
won_the_race_txt:dc.l $0C000000 + (byte_1A3698)
                                        ; DATA XREF: ROM:001B6A50   o
                                        ; Psycrow won the race (text in level)
                dc.B "PSYCROW"
                dc.w $18B
                dc.w $1BA
                dc.w $228
                dc.B "WON THE RACE!",0
