license_text:   dc.b  $A,  1, $D
                dc.B "EARTHWORM JIM"
                dc.b   1,$E6,  2,  1,  2,  2,  1,  7
                dc.B "AND ALL RELATED CHARACTERS"
                dc.b   1,$DF,  2,  1,  1,  6
                dc.B "ARE REGISTERED TRADEMARKS OF"
                dc.b   1,$DE,  2,  1,  1,  7
                dc.B "SHINY ENTERTAINMENT, INC."
                dc.b   1,$E0,  2,  1,  2,  1,  1,  5
                dc.B "(C) 1994 - ALL RIGHTS RESERVED"
                dc.b   1,$DD,  2,  1,  1,  0
                dc.B "PLAYMATES INTERACTIVE ENTERTAINMENT, INC"
                dc.b   1,$D8,  2,  1,  2,  2,  1,  3
                dc.B "LICENSED BY SEGA ENTERPRISES, LTD."
                dc.b   1,$DB,  2,  1,  0