byte_2D2430:    dc.b   0,  4,$72,$A8,$8E,$B7,$88,$AD,$89,$AD
                                        ; DATA XREF: ROM:off_EC8   o
                dc.w sprite_32_8
                dc.w $70A2
                dc.w $9500 ! ((grp_97C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_97C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6EAA
                dc.w $9500 ! ((grp_C9E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $83AA
                dc.w $9500 ! ((grp_C9DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $89B2
                dc.w $9500 ! ((grp_B26C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B26C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B26C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6FB2
                dc.w $9500 ! ((grp_E4240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4240 / 2) >> 16)
                dc.w 1
