byte_2DCB34:    dc.b   0,  5,$6F,$55,$8E,$8F,$81,$67,$85,$58
                                        ; DATA XREF: ROM:off_1660   o
                dc.w sprite_32_24
                dc.w $6A58
                dc.w $9500 ! ((grp_12D540 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6A70
                dc.w $9500 ! ((grp_84E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7F70
                dc.w $9500 ! ((grp_84F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8A55
                dc.w $9500 ! ((grp_84F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7550
                dc.w $9500 ! ((grp_18A4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A4E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $625F
                dc.w $9500 ! ((grp_ED820 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED820 / 2) >> 16)
                dc.w 1
