byte_2DEAC8:    dc.b   0,  6,$80,$4D,$A1,$8A,$90,$6B,$91,$6B
                                        ; DATA XREF: ROM:off_17A0   o
                dc.w sprite_24_32
                dc.w $836A
                dc.w $9500 ! ((grp_1081C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1081C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1081C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8D48
                dc.w $9500 ! ((grp_176D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_176D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9B6B
                dc.w $9500 ! ((grp_1981C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1981C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1981C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $838A
                dc.w $9500 ! ((grp_D2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B70
                dc.w $9500 ! ((grp_B9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8554
                dc.w $9500 ! ((grp_EB3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB3E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D58
                dc.w $9500 ! ((grp_EB400 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB400 / 2) >> 16)
                dc.w 1
