byte_2F37CC:    dc.b   0,  6,$69,$5F,$96,$89,$78,$78,$79,$78
                                        ; DATA XREF: ROM:off_27D0   o
                dc.w sprite_24_32
                dc.w $7C5E
                dc.w $9500 ! ((grp_115240 / 2) & $00FF)
                dc.w $9600 ! (((grp_115240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7C7E
                dc.w $9500 ! ((grp_14F8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F8C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6C5D
                dc.w $9500 ! ((grp_17E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5C64
                dc.w $9500 ! ((grp_8D280 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $667F
                dc.w $9500 ! ((grp_DBEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6C7C
                dc.w $9500 ! ((grp_DBE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $946D
                dc.w $9500 ! ((grp_F3120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3120 / 2) >> 16)
                dc.w 1
