byte_2F4646:    dc.b   0,  1,$7A,$73,$88,$8D,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_299C   o
                dc.w sprite_16_32
                dc.w $7971
                dc.w $9500 ! ((grp_6D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8979
                dc.w $9500 ! ((grp_F3A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3A20 / 2) >> 16)
                dc.w 1
