byte_2D4F4E:    dc.b   0,  5,$6D,$61,$8A,$7A,$80,$6E,$76,$5F
                                        ; DATA XREF: ROM:off_1154   o
                dc.w sprite_32_32
                dc.w $6A5A
                dc.w $9500 ! ((grp_18800 / 2) & $00FF)
                dc.w $9600 ! (((grp_18800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6E7A
                dc.w $9500 ! ((grp_78400 / 2) & $00FF)
                dc.w $9600 ! (((grp_78400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7252
                dc.w $9500 ! ((grp_CB3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A6F
                dc.w $9500 ! ((grp_B37C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B37C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B37C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_E5E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9273
                dc.w $9500 ! ((grp_E5E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5E60 / 2) >> 16)
                dc.w 1
