byte_2DF094:    dc.b   0,  5,$61,$5F,$96,$8E,$75,$75,$5B,$6C
                                        ; DATA XREF: ROM:off_17D8   o
                dc.w sprite_32_32
                dc.w $6A5D
                dc.w $9500 ! ((grp_26800 / 2) & $00FF)
                dc.w $9600 ! (((grp_26800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $5268
                dc.w $9500 ! ((grp_1627C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1627C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1627C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $767D
                dc.w $9500 ! ((grp_162880 / 2) & $00FF)
                dc.w $9600 ! (((grp_162880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162880 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8A63
                dc.w $9500 ! ((grp_162940 / 2) & $00FF)
                dc.w $9600 ! (((grp_162940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $897C
                dc.w $9500 ! ((grp_D6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4A6C
                dc.w $9500 ! ((grp_EE080 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE080 / 2) >> 16)
                dc.w 1
