byte_2E15DE:    dc.b   0,  5,$71,$58,$93,$8F,$7F,$72,$80,$72
                                        ; DATA XREF: ROM:off_194C   o
                dc.w sprite_32_24
                dc.w $785A
                dc.w $9500 ! ((grp_12E440 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6856
                dc.w $9500 ! ((grp_85E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7266
                dc.w $9500 ! ((grp_A8E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7A69
                dc.w $9500 ! ((grp_A8F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8272
                dc.w $9500 ! ((grp_EE1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE1A0 / 2) >> 16)
                dc.w 1
