byte_2ED2C2:    dc.b   0,  5,$98,$79,$A3,$8F,$84,$84,$85,$84
                                        ; DATA XREF: ROM:off_2284   o
                dc.w sprite_24_16
                dc.w $6681
                dc.w $9500 ! ((grp_164D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_164D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7E81
                dc.w $9500 ! ((grp_164C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_164C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9679
                dc.w $9500 ! ((grp_17B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8679
                dc.w $9500 ! ((grp_D8940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9371
                dc.w $9500 ! ((grp_D8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E86
                dc.w $9500 ! ((grp_F0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0140 / 2) >> 16)
                dc.w 1
