byte_2D03CE:    dc.b   0,  1,$70,$71,$8A,$8F,$7D,$80,$7E,$80
                                        ; DATA XREF: ROM:off_D14   o
                dc.w sprite_24_24
                dc.w $777F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6F
                dc.w $9500 ! ((grp_46C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46C00 / 2) >> 16)
                dc.w 8
