byte_2E381E:    dc.b   0,  5,$6F,$64,$9B,$8E,$85,$79,$86,$79
                                        ; DATA XREF: ROM:off_1AD4   o
                dc.w sprite_24_16
                dc.w $7479
                dc.w $9500 ! ((grp_163240 / 2) & $00FF)
                dc.w $9600 ! (((grp_163240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7E6B
                dc.w $9500 ! ((grp_86A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_86A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D89
                dc.w $9500 ! ((grp_9BF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8E63
                dc.w $9500 ! ((grp_19ADA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ADA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ADA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9662
                dc.w $9500 ! ((grp_BD400 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C81
                dc.w $9500 ! ((grp_EE9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE9C0 / 2) >> 16)
                dc.w 1
