byte_2DF1DE:    dc.b   0,  5,$75,$59,$8E,$82,$80,$6D,$86,$60
                                        ; DATA XREF: ROM:off_17E4   o
                dc.w sprite_32_32
                dc.w $7164
                dc.w $9500 ! ((grp_1A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7954
                dc.w $9500 ! ((grp_7A780 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6967
                dc.w $9500 ! ((grp_1957C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1957C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1957C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8D77
                dc.w $9500 ! ((grp_B50C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B50C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B50C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $915F
                dc.w $9500 ! ((grp_B5080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $895C
                dc.w $9500 ! ((grp_E77A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E77A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E77A0 / 2) >> 16)
                dc.w 1
