byte_2F9B78:    dc.b   0,  8,$7A,$62,$91,$90,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_2DC8   o
                dc.w sprite_24_24
                dc.w $7863
                dc.w $9500 ! ((grp_152EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_152EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152EC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $787B
                dc.w $9500 ! ((grp_152FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_152FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152FE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $7071
                dc.w $9500 ! ((grp_AE700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6879
                dc.w $9500 ! ((grp_19F7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F7E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9069
                dc.w $9500 ! ((grp_19F840 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F840 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9873
                dc.w $9500 ! ((grp_19F8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F8A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6869
                dc.w $9500 ! ((grp_DEA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F5B
                dc.w $9500 ! ((grp_DEA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9081
                dc.w $9500 ! ((grp_C4680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4680 / 2) >> 16)
                dc.w 2
