byte_2FA516:    dc.b   0,  9,$7D,$54,$91,$8B,$7C,$6E,$7D,$6E
                                        ; DATA XREF: ROM:off_2E0C   o
                dc.w sprite_24_32
                dc.w $7574
                dc.w $9500 ! ((grp_11B240 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7E54
                dc.w $9500 ! ((grp_70000 / 2) & $00FF)
                dc.w $9600 ! (((grp_70000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9563
                dc.w $9500 ! ((grp_70100 / 2) & $00FF)
                dc.w $9600 ! (((grp_70100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6654
                dc.w $9500 ! ((grp_16ABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16ABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16ABC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $565B
                dc.w $9500 ! ((grp_91780 / 2) & $00FF)
                dc.w $9600 ! (((grp_91780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91780 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6E4C
                dc.w $9500 ! ((grp_A0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8D6C
                dc.w $9500 ! ((grp_AE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8E4C
                dc.w $9500 ! ((grp_AE880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $965B
                dc.w $9500 ! ((grp_DED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DED80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D7E
                dc.w $9500 ! ((grp_C4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4980 / 2) >> 16)
                dc.w 2
