byte_2D9028:    dc.b   0,  7,$69,$5B,$8F,$8E,$7C,$74,$74,$63
                                        ; DATA XREF: ROM:off_1400   o
                dc.w sprite_24_32
                dc.w $7470
                dc.w $9500 ! ((grp_103840 / 2) & $00FF)
                dc.w $9600 ! (((grp_103840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6458
                dc.w $9500 ! ((grp_7C880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $748F
                dc.w $9500 ! ((grp_99200 / 2) & $00FF)
                dc.w $9600 ! (((grp_99200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6C68
                dc.w $9500 ! ((grp_186D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_186D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6C70
                dc.w $9500 ! ((grp_1969C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1969C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1969C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7458
                dc.w $9500 ! ((grp_B6980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C7F
                dc.w $9500 ! ((grp_B6940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8468
                dc.w $9500 ! ((grp_E8D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D20 / 2) >> 16)
                dc.w 1
