byte_2E09C2:    dc.b   0,  5,$43,$40,$75,$6A,$5C,$55,$6C,$43
                                        ; DATA XREF: ROM:off_18F4   o
                dc.w sprite_32_32
                dc.w $503E
                dc.w $9500 ! ((grp_22C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_22C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $485E
                dc.w $9500 ! ((grp_4E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $4046
                dc.w $9500 ! ((grp_177280 / 2) & $00FF)
                dc.w $9600 ! (((grp_177280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177280 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $703E
                dc.w $9500 ! ((grp_B9AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $405E
                dc.w $9500 ! ((grp_EBCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBCE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $685E
                dc.w $9500 ! ((grp_EBD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD00 / 2) >> 16)
                dc.w 1
