byte_2F9510:    dc.b   0,  2,$7B,$6C,$87,$89,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_2D48   o
                dc.w sprite_16_32
                dc.w $796A
                dc.w $9500 ! ((grp_6FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $818A
                dc.w $9500 ! ((grp_F67C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F67C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F67C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $896B
                dc.w $9500 ! ((grp_F67E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F67E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F67E0 / 2) >> 16)
                dc.w 1
