byte_2EAF02:    dc.b   0,  3,$7D,$59,$99,$6C,$86,$63,$87,$63
                                        ; DATA XREF: ROM:off_1FC4   o
                dc.w sprite_32_24
                dc.w $6E5E
                dc.w $9500 ! ((grp_130FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_130FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_130FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8E5E
                dc.w $9500 ! ((grp_87300 / 2) & $00FF)
                dc.w $9600 ! (((grp_87300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8056
                dc.w $9500 ! ((grp_18BD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BD40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6E56
                dc.w $9500 ! ((grp_EF2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF2A0 / 2) >> 16)
                dc.w 1
