byte_2EE0B8:    dc.b   0,  1,$77,$80,$87,$8F,$7E,$86,$7F,$86
                                        ; DATA XREF: ROM:off_2360   o
                dc.w sprite_16_16
                dc.w $7981
                dc.w $9500 ! ((grp_89A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_89A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7185
                dc.w $9500 ! ((grp_F0680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0680 / 2) >> 16)
                dc.w 1
