byte_2FC41E:    dc.b   0,  1,$5E,$81,$6F,$87,$66,$84,$67,$84
                                        ; DATA XREF: ROM:off_310C   o
                dc.w sprite_16_16
                dc.w $627F
                dc.w $9500 ! ((grp_92F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_92F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5A82
                dc.w $9500 ! ((grp_F7E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7E20 / 2) >> 16)
                dc.w 1
