byte_2FF53E:    dc.b   0, $D,$3C,$53,$A8,$C4,$72,$8B,$73,$8B
                                        ; DATA XREF: ROM:off_358C   o
                dc.w sprite_24_16
                dc.w $3AB9
                dc.w $9500 ! ((grp_16E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4BA9
                dc.w $9500 ! ((grp_96680 / 2) & $00FF)
                dc.w $9600 ! (((grp_96680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8369
                dc.w $9500 ! ((grp_AF380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B60
                dc.w $9500 ! ((grp_AF400 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9358
                dc.w $9500 ! ((grp_AF480 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9B51
                dc.w $9500 ! ((grp_AF500 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5B98
                dc.w $9500 ! ((grp_1A0B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0B60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $638F
                dc.w $9500 ! ((grp_1A0BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0BC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B86
                dc.w $9500 ! ((grp_1A0C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $737D
                dc.w $9500 ! ((grp_1A0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7B73
                dc.w $9500 ! ((grp_1A0CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0CE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A351
                dc.w $9500 ! ((grp_1A0D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $43B1
                dc.w $9500 ! ((grp_F92E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F92E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F92E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $53A1
                dc.w $9500 ! ((grp_F9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9300 / 2) >> 16)
                dc.w 1
