byte_2DD8C4:    dc.b   0, $B,$56,$42,$A1,$87,$7B,$64,$89,$43
                                        ; DATA XREF: ROM:off_16E8   o
                dc.w sprite_32_16
                dc.w $5C43
                dc.w $9500 ! ((grp_4CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $696B
                dc.w $9500 ! ((grp_4CB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7C40
                dc.w $9500 ! ((grp_4CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $665B
                dc.w $9500 ! ((grp_15E680 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E680 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $717B
                dc.w $9500 ! ((grp_15E740 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $5443
                dc.w $9500 ! ((grp_B7D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8974
                dc.w $9500 ! ((grp_B7C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $916B
                dc.w $9500 ! ((grp_B7C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C40
                dc.w $9500 ! ((grp_B7CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $616D
                dc.w $9500 ! ((grp_EA020 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6553
                dc.w $9500 ! ((grp_EA040 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E63
                dc.w $9500 ! ((grp_EA060 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA060 / 2) >> 16)
                dc.w 1
