byte_2EA83A:    dc.b   0,  7,$66,$5A,$97,$8D,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_1F5C   o
                dc.w sprite_32_32
                dc.w $7258
                dc.w $9500 ! ((grp_2A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2A200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6A78
                dc.w $9500 ! ((grp_130B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_130B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_130B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_AA180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A58
                dc.w $9500 ! ((grp_AA200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9258
                dc.w $9500 ! ((grp_AA280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA280 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7850
                dc.w $9500 ! ((grp_18BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BC80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8A78
                dc.w $9500 ! ((grp_19B760 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B760 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9278
                dc.w $9500 ! ((grp_BDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDE80 / 2) >> 16)
                dc.w 2
