byte_2E6A42:    dc.b   0,  9,$70,$65,$8C,$8E,$78,$77,$7B,$68
                                        ; DATA XREF: ROM:off_1C74   o
                dc.w sprite_24_16
                dc.w $7367
                dc.w $9500 ! ((grp_161200 / 2) & $00FF)
                dc.w $9600 ! (((grp_161200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B77
                dc.w $9500 ! ((grp_1783C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1783C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1783C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B70
                dc.w $9500 ! ((grp_83700 / 2) & $00FF)
                dc.w $9600 ! (((grp_83700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B67
                dc.w $9500 ! ((grp_1992A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1992A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1992A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $737F
                dc.w $9500 ! ((grp_199300 / 2) & $00FF)
                dc.w $9600 ! (((grp_199300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199300 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8B6B
                dc.w $9500 ! ((grp_199360 / 2) & $00FF)
                dc.w $9600 ! (((grp_199360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199360 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $755F
                dc.w $9500 ! ((grp_D3E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838C
                dc.w $9500 ! ((grp_D3E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B8F
                dc.w $9500 ! ((grp_EC9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC9E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937A
                dc.w $9500 ! ((grp_ECA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECA00 / 2) >> 16)
                dc.w 1
