byte_2EBA24:    dc.b   0,  9,$84,$5B,$A1,$80,$81,$7B,$82,$7B
                                        ; DATA XREF: ROM:off_2060   o
                dc.w sprite_32_32
                dc.w $5B67
                dc.w $9500 ! ((grp_2EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2EA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7B67
                dc.w $9500 ! ((grp_2EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2EC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7B87
                dc.w $9500 ! ((grp_51700 / 2) & $00FF)
                dc.w $9600 ! (((grp_51700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9B6F
                dc.w $9500 ! ((grp_68600 / 2) & $00FF)
                dc.w $9600 ! (((grp_68600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $5B87
                dc.w $9500 ! ((grp_9D280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $536F
                dc.w $9500 ! ((grp_AA900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $AB77
                dc.w $9500 ! ((grp_19BEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BEE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4B7C
                dc.w $9500 ! ((grp_BE340 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $738F
                dc.w $9500 ! ((grp_EF820 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B8F
                dc.w $9500 ! ((grp_EF840 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF840 / 2) >> 16)
                dc.w 1
