byte_2D9B64:    dc.b   0,  8,$86,$67,$8F,$77,$80,$6C,$8B,$5D
                                        ; DATA XREF: ROM:off_1468   o
                dc.w sprite_24_16
                dc.w $7E5A
                dc.w $9500 ! ((grp_15ACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15ACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15ACC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7F7C
                dc.w $9500 ! ((grp_173680 / 2) & $00FF)
                dc.w $9600 ! (((grp_173680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173680 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7052
                dc.w $9500 ! ((grp_98800 / 2) & $00FF)
                dc.w $9600 ! (((grp_98800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6854
                dc.w $9500 ! ((grp_1950A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1950A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1950A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7E6A
                dc.w $9500 ! ((grp_CCA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $746E
                dc.w $9500 ! ((grp_E6F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8876
                dc.w $9500 ! ((grp_E6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $908B
                dc.w $9500 ! ((grp_E5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A40 / 2) >> 16)
                dc.w 1
