byte_2F58EA:    dc.b   0,  4,$66,$78,$9D,$8E,$81,$83,$82,$83
                                        ; DATA XREF: ROM:off_2AF4   o
                dc.w sprite_24_24
                dc.w $7079
                dc.w $9500 ! ((grp_150E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_150E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150E20 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8880
                dc.w $9500 ! ((grp_168F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_168F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6879
                dc.w $9500 ! ((grp_19E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E9A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D71
                dc.w $9500 ! ((grp_DCDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6089
                dc.w $9500 ! ((grp_F49A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F49A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F49A0 / 2) >> 16)
                dc.w 1
