byte_2D611C:    dc.b   0,  5,$6F,$66,$8E,$8F,$7F,$78,$80,$6A
                                        ; DATA XREF: ROM:off_1218   o
                dc.w sprite_24_32
                dc.w $7569
                dc.w $9500 ! ((grp_1069C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1069C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1069C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $5D6B
                dc.w $9500 ! ((grp_15F1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_15F280 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6E89
                dc.w $9500 ! ((grp_D1840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1840 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7961
                dc.w $9500 ! ((grp_D1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8689
                dc.w $9500 ! ((grp_D18C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D18C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D18C0 / 2) >> 16)
                dc.w 2
