byte_2D1B82:    dc.b   0,  5,$6D,$6B,$8E,$8F,$7D,$7D,$7E,$7D
                                        ; DATA XREF: ROM:off_E54   o
                dc.w sprite_32_32
                dc.w $7569
                dc.w $9500 ! ((grp_16400 / 2) & $00FF)
                dc.w $9600 ! (((grp_16400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $6571
                dc.w $9500 ! ((grp_5DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5DB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7589
                dc.w $9500 ! ((grp_97780 / 2) & $00FF)
                dc.w $9600 ! (((grp_97780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5D89
                dc.w $9500 ! ((grp_E3D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D69
                dc.w $9500 ! ((grp_E3CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9584
                dc.w $9500 ! ((grp_E3D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3D20 / 2) >> 16)
                dc.w 1
