byte_2F962E:    dc.b   0,  2,$74,$5D,$88,$6B,$7E,$64,$7F,$64
                                        ; DATA XREF: ROM:off_2D64   o
                dc.w sprite_24_8
                dc.w $725A
                dc.w $9500 ! ((grp_18FF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FF40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8062
                dc.w $9500 ! ((grp_F68E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F68E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F68E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $816C
                dc.w $9500 ! ((grp_F6900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6900 / 2) >> 16)
                dc.w 1
