byte_2CF1E8:    dc.b   0,  8,$71,$5C,$9B,$92,$84,$70,$85,$70
                                        ; DATA XREF: ROM:off_B48   o
                dc.w sprite_32_32
                dc.w $6E4D
                dc.w $9500 ! ((grp_13200 / 2) & $00FF)
                dc.w $9600 ! (((grp_13200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6E6D
                dc.w $9500 ! ((grp_13400 / 2) & $00FF)
                dc.w $9600 ! (((grp_13400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8E5E
                dc.w $9500 ! ((grp_FACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FACC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5E51
                dc.w $9500 ! ((grp_74A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_74A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E4E
                dc.w $9500 ! ((grp_74A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_74A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E7E
                dc.w $9500 ! ((grp_74B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_74B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $778D
                dc.w $9500 ! ((grp_C8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6683
                dc.w $9500 ! ((grp_E2AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E7E
                dc.w $9500 ! ((grp_E2AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2AE0 / 2) >> 16)
                dc.w 1
