byte_2E2768:    dc.b   0, $E,$66,$4D,$A6,$8E,$86,$6D,$87,$6D
                                        ; DATA XREF: ROM:off_1A38   o
                dc.w sprite_16_32
                dc.w $7572
                dc.w $9500 ! ((grp_64B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $955B
                dc.w $9500 ! ((grp_177940 / 2) & $00FF)
                dc.w $9600 ! (((grp_177940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177940 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7D52
                dc.w $9500 ! ((grp_A7980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8563
                dc.w $9500 ! ((grp_A7A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8D60
                dc.w $9500 ! ((grp_A7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9573
                dc.w $9500 ! ((grp_A7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $854B
                dc.w $9500 ! ((grp_198E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_198E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198E20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8D4B
                dc.w $9500 ! ((grp_B9D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D7C
                dc.w $9500 ! ((grp_B9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $648B
                dc.w $9500 ! ((grp_EC020 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6683
                dc.w $9500 ! ((grp_EC040 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D7D
                dc.w $9500 ! ((grp_EC060 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7559
                dc.w $9500 ! ((grp_EC080 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D80
                dc.w $9500 ! ((grp_EC0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC0A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A56C
                dc.w $9500 ! ((grp_EC0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC0C0 / 2) >> 16)
                dc.w 1
