byte_2FD942:    dc.b   0,  8,$76,$55,$A8,$8D,$8F,$71,$90,$71
                                        ; DATA XREF: ROM:off_331C   o
                dc.w sprite_32_16
                dc.w $8877
                dc.w $9500 ! ((grp_59800 / 2) & $00FF)
                dc.w $9600 ! (((grp_59800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7878
                dc.w $9500 ! ((grp_95400 / 2) & $00FF)
                dc.w $9600 ! (((grp_95400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7088
                dc.w $9500 ! ((grp_191140 / 2) & $00FF)
                dc.w $9600 ! (((grp_191140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191140 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8F6F
                dc.w $9500 ! ((grp_1911A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1911A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1911A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A664
                dc.w $9500 ! ((grp_1A0560 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0560 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7352
                dc.w $9500 ! ((grp_DFEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F56
                dc.w $9500 ! ((grp_DFF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8F5B
                dc.w $9500 ! ((grp_DFF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E5F
                dc.w $9500 ! ((grp_C5B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5B40 / 2) >> 16)
                dc.w 2
