byte_2F62EE:    dc.b   0,$15,$63,$4D,$84,$83,$76,$7B,$77,$7B
                                        ; DATA XREF: ROM:off_2B44   o
                dc.w sprite_32_32
                dc.w $5361
                dc.w $9500 ! ((grp_3D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $735E
                dc.w $9500 ! ((grp_117040 / 2) & $00FF)
                dc.w $9600 ! (((grp_117040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $733E
                dc.w $9500 ! ((grp_116EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_116EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5349
                dc.w $9500 ! ((grp_137440 / 2) & $00FF)
                dc.w $9600 ! (((grp_137440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $5B2E
                dc.w $9500 ! ((grp_169300 / 2) & $00FF)
                dc.w $9600 ! (((grp_169300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169300 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $732E
                dc.w $9500 ! ((grp_1693C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1693C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1693C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $3B67
                dc.w $9500 ! ((grp_17E9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E9C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $4B35
                dc.w $9500 ! ((grp_17EFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EFC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B39
                dc.w $9500 ! ((grp_8F380 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B38
                dc.w $9500 ! ((grp_8F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $3B47
                dc.w $9500 ! ((grp_AD780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4337
                dc.w $9500 ! ((grp_AD800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9B41
                dc.w $9500 ! ((grp_AD880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $737E
                dc.w $9500 ! ((grp_18EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4B64
                dc.w $9500 ! ((grp_19EA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EA60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4357
                dc.w $9500 ! ((grp_C2940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B72
                dc.w $9500 ! ((grp_C2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B48
                dc.w $9500 ! ((grp_C2380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9348
                dc.w $9500 ! ((grp_C2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A354
                dc.w $9500 ! ((grp_C29C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C29C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C29C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $335E
                dc.w $9500 ! ((grp_F4F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AD5E
                dc.w $9500 ! ((grp_F4F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4F60 / 2) >> 16)
                dc.w 1
