byte_2D458E:    dc.b   0,  3,$59,$62,$AB,$8C,$7C,$73,$7D,$73
                                        ; DATA XREF: ROM:off_10DC   o
                dc.w sprite_32_16
                dc.w $626B
                dc.w $9500 ! ((grp_49300 / 2) & $00FF)
                dc.w $9600 ! (((grp_49300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8A74
                dc.w $9500 ! ((grp_77A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_77A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8268
                dc.w $9500 ! ((grp_194320 / 2) & $00FF)
                dc.w $9600 ! (((grp_194320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194320 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5A74
                dc.w $9500 ! ((grp_B3340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3340 / 2) >> 16)
                dc.w 2
