byte_2D7374:    dc.b   0, $A,$77,$64,$88,$83,$82,$6C,$78,$5D
                                        ; DATA XREF: ROM:off_12D0   o
                dc.w sprite_16_24
                dc.w $7D73
                dc.w $9500 ! ((grp_1789C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1789C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1789C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7D5B
                dc.w $9500 ! ((grp_178A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_178A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7569
                dc.w $9500 ! ((grp_A7E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D6C
                dc.w $9500 ! ((grp_199720 / 2) & $00FF)
                dc.w $9600 ! (((grp_199720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199720 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D45
                dc.w $9500 ! ((grp_199780 / 2) & $00FF)
                dc.w $9600 ! (((grp_199780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199780 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7559
                dc.w $9500 ! ((grp_BB380 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $854B
                dc.w $9500 ! ((grp_BB3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9544
                dc.w $9500 ! ((grp_BB400 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D59
                dc.w $9500 ! ((grp_ECEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECEA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $818B
                dc.w $9500 ! ((grp_ECEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECEC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D74
                dc.w $9500 ! ((grp_ECEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECEE0 / 2) >> 16)
                dc.w 1
