byte_2D5E0A:    dc.b   0,  4,$75,$5D,$8C,$8C,$81,$74,$7C,$60
                                        ; DATA XREF: ROM:off_11F4   o
                dc.w sprite_32_16
                dc.w $7571
                dc.w $9500 ! ((grp_49A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8261
                dc.w $9500 ! ((grp_15A3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A3C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7259
                dc.w $9500 ! ((grp_1729C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1729C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1729C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6F81
                dc.w $9500 ! ((grp_78C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8C59
                dc.w $9500 ! ((grp_E6440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6440 / 2) >> 16)
                dc.w 1
