byte_2DC96A:    dc.b   0,  5,$77,$57,$90,$98,$89,$77,$83,$6C
                                        ; DATA XREF: ROM:off_164C   o
                dc.w sprite_32_24
                dc.w $7570
                dc.w $9500 ! ((grp_124FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_124FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7D88
                dc.w $9500 ! ((grp_15B140 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8350
                dc.w $9500 ! ((grp_173980 / 2) & $00FF)
                dc.w $9600 ! (((grp_173980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7668
                dc.w $9500 ! ((grp_185920 / 2) & $00FF)
                dc.w $9600 ! (((grp_185920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $958D
                dc.w $9500 ! ((grp_CCE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8298
                dc.w $9500 ! ((grp_E7280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7280 / 2) >> 16)
                dc.w 1
