byte_2CDD72:    dc.b   0,  3,$6D,$6D,$92,$8C,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_9BC   o
                dc.w sprite_32_32
                dc.w $736B
                dc.w $9500 ! ((grp_11600 / 2) & $00FF)
                dc.w $9600 ! (((grp_11600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $758B
                dc.w $9500 ! ((grp_183880 / 2) & $00FF)
                dc.w $9600 ! (((grp_183880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183880 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B71
                dc.w $9500 ! ((grp_192160 / 2) & $00FF)
                dc.w $9600 ! (((grp_192160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9374
                dc.w $9500 ! ((grp_B0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0C00 / 2) >> 16)
                dc.w 2
