byte_2DD4F2:    dc.b   0,  7,$80,$5B,$94,$98,$8B,$90,$87,$6D
                                        ; DATA XREF: ROM:off_16C4   o
                dc.w sprite_24_24
                dc.w $8887
                dc.w $9500 ! ((grp_142F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_142F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142F60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $8457
                dc.w $9500 ! ((grp_60600 / 2) & $00FF)
                dc.w $9600 ! (((grp_60600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7468
                dc.w $9500 ! ((grp_7A700 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8577
                dc.w $9500 ! ((grp_7A680 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7D78
                dc.w $9500 ! ((grp_E7700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $899F
                dc.w $9500 ! ((grp_E76A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E76A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E76A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $945B
                dc.w $9500 ! ((grp_E76E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E76E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E76E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $999F
                dc.w $9500 ! ((grp_E76C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E76C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E76C0 / 2) >> 16)
                dc.w 1
