byte_2EA6FC:    dc.b   0,  8,$66,$5A,$97,$8D,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_1F50   o
                dc.w sprite_24_32
                dc.w $7A70
                dc.w $9500 ! ((grp_10F6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7A50
                dc.w $9500 ! ((grp_10F840 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F840 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_A9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A5D
                dc.w $9500 ! ((grp_A9E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7256
                dc.w $9500 ! ((grp_A9E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $925D
                dc.w $9500 ! ((grp_A9F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7276
                dc.w $9500 ! ((grp_19B640 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B640 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6A7D
                dc.w $9500 ! ((grp_BDE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $927D
                dc.w $9500 ! ((grp_BDE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDE00 / 2) >> 16)
                dc.w 2
