byte_2EA170:    dc.b   0,  3,$66,$76,$91,$8A,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F10   o
                dc.w sprite_32_24
                dc.w $6C75
                dc.w $9500 ! ((grp_12FAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12FAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12FAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $647B
                dc.w $9500 ! ((grp_BDBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C7E
                dc.w $9500 ! ((grp_BDC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A6D
                dc.w $9500 ! ((grp_EEEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEEA0 / 2) >> 16)
                dc.w 1
