byte_2F4EC4:    dc.b   0,  6,$70,$62,$95,$8D,$90,$79,$91,$79
                                        ; DATA XREF: ROM:off_2A28   o
                dc.w sprite_32_32
                dc.w $7476
                dc.w $9500 ! ((grp_3BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3BA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7F5E
                dc.w $9500 ! ((grp_150880 / 2) & $00FF)
                dc.w $9600 ! (((grp_150880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150880 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6F66
                dc.w $9500 ! ((grp_8E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $976A
                dc.w $9500 ! ((grp_18EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EB00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6C7A
                dc.w $9500 ! ((grp_19E640 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E640 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $AE66
                dc.w $9500 ! ((grp_C1AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9772
                dc.w $9500 ! ((grp_F4320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4320 / 2) >> 16)
                dc.w 1
