byte_2E8CEE:    dc.b   0,  3,$74,$7F,$88,$8E,$80,$80,$7E,$82
                                        ; DATA XREF: ROM:off_1DCC   o
                dc.w sprite_24_16
                dc.w $727F
                dc.w $9500 ! ((grp_15CAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15CAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15CAC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $748F
                dc.w $9500 ! ((grp_CE940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B6F
                dc.w $9500 ! ((grp_B6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8888
                dc.w $9500 ! ((grp_E8A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8A60 / 2) >> 16)
                dc.w 1
