byte_2F3108:    dc.b   0,  5,$6C,$5F,$8B,$8E,$79,$76,$7A,$76
                                        ; DATA XREF: ROM:off_2790   o
                dc.w sprite_32_32
                dc.w $6B72
                dc.w $9500 ! ((grp_39A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_39A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $6E5A
                dc.w $9500 ! ((grp_14F440 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F440 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5E5D
                dc.w $9500 ! ((grp_8CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $637B
                dc.w $9500 ! ((grp_C0D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8662
                dc.w $9500 ! ((grp_C0D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E63
                dc.w $9500 ! ((grp_F2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2D00 / 2) >> 16)
                dc.w 1
