byte_2F845A:    dc.b   0, $B,$77,$57,$9D,$8C,$80,$67,$81,$67
                                        ; DATA XREF: ROM:off_2C7C   o
                dc.w sprite_24_24
                dc.w $785E
                dc.w $9500 ! ((grp_151DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_151DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151DE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $707B
                dc.w $9500 ! ((grp_169D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_169D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9056
                dc.w $9500 ! ((grp_90980 / 2) & $00FF)
                dc.w $9600 ! (((grp_90980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7673
                dc.w $9500 ! ((grp_DDF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8056
                dc.w $9500 ! ((grp_DDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9066
                dc.w $9500 ! ((grp_DDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6873
                dc.w $9500 ! ((grp_C3840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A04C
                dc.w $9500 ! ((grp_C3880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $758B
                dc.w $9500 ! ((grp_F5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $818B
                dc.w $9500 ! ((grp_F5FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906E
                dc.w $9500 ! ((grp_F6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A84C
                dc.w $9500 ! ((grp_F6020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6020 / 2) >> 16)
                dc.w 1
