byte_2D23B0:    dc.b   0,  3,$72,$A8,$8E,$B5,$89,$AF,$8A,$AF
                                        ; DATA XREF: ROM:off_EC0   o
                dc.w sprite_16_16
                dc.w $67AD
                dc.w $9500 ! ((grp_76B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $89AD
                dc.w $9500 ! ((grp_76C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $75A5
                dc.w $9500 ! ((grp_97B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_97B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6DA5
                dc.w $9500 ! ((grp_E4220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4220 / 2) >> 16)
                dc.w 1
