byte_2EAB1A:    dc.b   0,  2,$76,$6E,$89,$8F,$7E,$7E,$7F,$7E
                                        ; DATA XREF: ROM:off_1F84   o
                dc.w sprite_24_32
                dc.w $7473
                dc.w $9500 ! ((grp_10FB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10FB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10FB40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $796B
                dc.w $9500 ! ((grp_D74C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D74C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D74C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C7C
                dc.w $9500 ! ((grp_EF180 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF180 / 2) >> 16)
                dc.w 1
