byte_2D7FC2:    dc.b   0,  6,$73,$5E,$92,$8E,$8E,$79,$83,$68
                                        ; DATA XREF: ROM:off_1354   o
                dc.w sprite_32_16
                dc.w $8276
                dc.w $9500 ! ((grp_4B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7A66
                dc.w $9500 ! ((grp_7D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D100 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8886
                dc.w $9500 ! ((grp_99380 / 2) & $00FF)
                dc.w $9600 ! (((grp_99380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $938E
                dc.w $9500 ! ((grp_CF700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A76
                dc.w $9500 ! ((grp_B6E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E5E
                dc.w $9500 ! ((grp_E9340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A6E
                dc.w $9500 ! ((grp_E9360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9360 / 2) >> 16)
                dc.w 1
