byte_2FDD06:    dc.b   0,  4,$78,$53,$8F,$8D,$83,$70,$84,$70
                                        ; DATA XREF: ROM:off_3344   o
                dc.w sprite_24_32
                dc.w $7661
                dc.w $9500 ! ((grp_11CD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11CD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11CD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7651
                dc.w $9500 ! ((grp_16D740 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8E5F
                dc.w $9500 ! ((grp_AEE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_191440 / 2) & $00FF)
                dc.w $9600 ! (((grp_191440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7D81
                dc.w $9500 ! ((grp_F8660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8660 / 2) >> 16)
                dc.w 1
