byte_2EFC2C:    dc.b   0,  1,$77,$80,$87,$8D,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_2578   o
                dc.w sprite_24_16
                dc.w $757E
                dc.w $9500 ! ((grp_165A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_165A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7B8E
                dc.w $9500 ! ((grp_F1380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1380 / 2) >> 16)
                dc.w 1
