byte_2CD408:    dc.b   0,  2,$92,$72,$A2,$81,$89,$97,$8A,$97
                                        ; DATA XREF: ROM:off_8B0   o
                dc.w sprite_24_16
                dc.w $8C77
                dc.w $9500 ! ((grp_1564C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1564C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1564C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $8D6F
                dc.w $9500 ! ((grp_183280 / 2) & $00FF)
                dc.w $9600 ! (((grp_183280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183280 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8287
                dc.w $9500 ! ((grp_C7740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7740 / 2) >> 16)
                dc.w 2
