byte_2D616E:    dc.b   0,  9,$6F,$5F,$8E,$8F,$7F,$74,$7E,$64
                                        ; DATA XREF: ROM:off_121C   o
                dc.w sprite_16_32
                dc.w $7459
                dc.w $9500 ! ((grp_62B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_62B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $945A
                dc.w $9500 ! ((grp_176800 / 2) & $00FF)
                dc.w $9600 ! (((grp_176800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5C67
                dc.w $9500 ! ((grp_7FF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7479
                dc.w $9500 ! ((grp_80000 / 2) & $00FF)
                dc.w $9600 ! (((grp_80000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8469
                dc.w $9500 ! ((grp_197DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_D1900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8481
                dc.w $9500 ! ((grp_B8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C69
                dc.w $9500 ! ((grp_B8B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C6E
                dc.w $9500 ! ((grp_EACE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EACE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EACE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C89
                dc.w $9500 ! ((grp_EAD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAD00 / 2) >> 16)
                dc.w 1
