byte_2D5A6A:    dc.b   0,  6,$77,$5F,$8E,$93,$8C,$7C,$81,$6A
                                        ; DATA XREF: ROM:off_11CC   o
                dc.w sprite_24_32
                dc.w $766E
                dc.w $9500 ! ((grp_1042C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1042C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1042C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8E6E
                dc.w $9500 ! ((grp_7CF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $898B
                dc.w $9500 ! ((grp_CF580 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $946B
                dc.w $9500 ! ((grp_CF5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $778E
                dc.w $9500 ! ((grp_B6D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B5E
                dc.w $9500 ! ((grp_B6D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8365
                dc.w $9500 ! ((grp_E9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9200 / 2) >> 16)
                dc.w 1
