byte_2F7E32:    dc.b   0,  4,$7B,$7C,$9F,$A6,$8C,$91,$8D,$91
                                        ; DATA XREF: ROM:off_2BDC   o
                dc.w sprite_24_16
                dc.w $7A7C
                dc.w $9500 ! ((grp_169A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_169A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7A8C
                dc.w $9500 ! ((grp_DD880 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $889B
                dc.w $9500 ! ((grp_F5B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948F
                dc.w $9500 ! ((grp_F5B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9AA2
                dc.w $9500 ! ((grp_F5B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5B80 / 2) >> 16)
                dc.w 1
