byte_2CDA0A:    dc.b   0,  1,$85,$86,$97,$8C,$84,$8E,$85,$9D
                                        ; DATA XREF: ROM:off_954   o
                dc.w sprite_16_16
                dc.w $8A7D
                dc.w $9500 ! ((grp_73F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_73F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8288
                dc.w $9500 ! ((grp_E1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1F00 / 2) >> 16)
                dc.w 1
