byte_2D891E:    dc.b   0,  7,$6F,$5A,$8E,$90,$70,$71,$73,$62
                                        ; DATA XREF: ROM:off_13BC   o
                dc.w sprite_24_24
                dc.w $606B
                dc.w $9500 ! ((grp_147880 / 2) & $00FF)
                dc.w $9600 ! (((grp_147880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147880 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $695B
                dc.w $9500 ! ((grp_84500 / 2) & $00FF)
                dc.w $9600 ! (((grp_84500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $586E
                dc.w $9500 ! ((grp_1998A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1998A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1998A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7870
                dc.w $9500 ! ((grp_199900 / 2) & $00FF)
                dc.w $9600 ! (((grp_199900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199900 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $806B
                dc.w $9500 ! ((grp_199960 / 2) & $00FF)
                dc.w $9600 ! (((grp_199960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7788
                dc.w $9500 ! ((grp_D4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7253
                dc.w $9500 ! ((grp_BB540 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $887B
                dc.w $9500 ! ((grp_ED1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED1C0 / 2) >> 16)
                dc.w 1
