byte_2DEBEE:    dc.b   0,  7,$6F,$60,$8E,$8F,$82,$70,$83,$6B
                                        ; DATA XREF: ROM:off_17AC   o
                dc.w sprite_32_24
                dc.w $7264
                dc.w $9500 ! ((grp_12A3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $727C
                dc.w $9500 ! ((grp_188D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_188D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6A67
                dc.w $9500 ! ((grp_198280 / 2) & $00FF)
                dc.w $9600 ! (((grp_198280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198280 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8C
                dc.w $9500 ! ((grp_D2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7284
                dc.w $9500 ! ((grp_D26C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D26C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D26C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8484
                dc.w $9500 ! ((grp_B9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B5C
                dc.w $9500 ! ((grp_EB460 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
