byte_2EE9C2:    dc.b   0,  5,$6A,$6D,$98,$90,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_23F4   o
                dc.w sprite_32_32
                dc.w $6D6E
                dc.w $9500 ! ((grp_32A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_32A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8D72
                dc.w $9500 ! ((grp_17BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BF00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6D8E
                dc.w $9500 ! ((grp_9DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7566
                dc.w $9500 ! ((grp_18D420 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D420 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $657B
                dc.w $9500 ! ((grp_BF5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D82
                dc.w $9500 ! ((grp_F08C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F08C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F08C0 / 2) >> 16)
                dc.w 1
