byte_2FE258:    dc.b   0,  3,$74,$77,$89,$88,$7D,$7F,$7E,$7F
                                        ; DATA XREF: ROM:off_33B0   o
                dc.w sprite_24_16
                dc.w $7375
                dc.w $9500 ! ((grp_16DBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6179
                dc.w $9500 ! ((grp_E04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E04C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7985
                dc.w $9500 ! ((grp_E0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9781
                dc.w $9500 ! ((grp_F8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8980 / 2) >> 16)
                dc.w 1
