byte_2EDC50:    dc.b   0,  6,$6E,$68,$A0,$95,$89,$7B,$8A,$7B
                                        ; DATA XREF: ROM:off_2300   o
                dc.w sprite_32_16
                dc.w $6D7E
                dc.w $9500 ! ((grp_52100 / 2) & $00FF)
                dc.w $9600 ! (((grp_52100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52100 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $776E
                dc.w $9500 ! ((grp_52000 / 2) & $00FF)
                dc.w $9600 ! (((grp_52000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8F7A
                dc.w $9500 ! ((grp_164BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_164BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $8366
                dc.w $9500 ! ((grp_18CB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CB80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $808D
                dc.w $9500 ! ((grp_D88C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D88C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D88C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F6E
                dc.w $9500 ! ((grp_BEB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6773
                dc.w $9500 ! ((grp_F00A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F00A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F00A0 / 2) >> 16)
                dc.w 1
