byte_2E7DD0:    dc.b   0, $B,$72,$60,$89,$7F,$CF,$4A,$9B,$62
                                        ; DATA XREF: ROM:off_1D30   o
                dc.w sprite_32_16
                dc.w $6F5F
                dc.w $9500 ! ((grp_4D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6F6F
                dc.w $9500 ! ((grp_15ED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15ED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15ED40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9750
                dc.w $9500 ! ((grp_1762C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1762C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1762C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $BB4F
                dc.w $9500 ! ((grp_1883E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1883E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1883E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $AF57
                dc.w $9500 ! ((grp_D1040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $C847
                dc.w $9500 ! ((grp_D1080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $676A
                dc.w $9500 ! ((grp_EA6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA6E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $777F
                dc.w $9500 ! ((grp_EA700 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8057
                dc.w $9500 ! ((grp_EA6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA6A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F65
                dc.w $9500 ! ((grp_EA720 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A048
                dc.w $9500 ! ((grp_EA740 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A75B
                dc.w $9500 ! ((grp_EA6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA6C0 / 2) >> 16)
                dc.w 1
