byte_2E1574:    dc.b   0,  7,$71,$58,$93,$8F,$84,$72,$85,$72
                                        ; DATA XREF: ROM:off_1948   o
                dc.w sprite_16_24
                dc.w $7571
                dc.w $9500 ! ((grp_179800 / 2) & $00FF)
                dc.w $9600 ! (((grp_179800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7559
                dc.w $9500 ! ((grp_1798C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1798C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1798C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9B980 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $855E
                dc.w $9500 ! ((grp_19A4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A4A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D5B
                dc.w $9500 ! ((grp_19A500 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A500 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D52
                dc.w $9500 ! ((grp_BC740 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7551
                dc.w $9500 ! ((grp_EE160 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9565
                dc.w $9500 ! ((grp_EE180 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE180 / 2) >> 16)
                dc.w 1
