byte_2EC008:    dc.b   0,  1,$7E,$5F,$91,$89,$87,$74,$88,$74
                                        ; DATA XREF: ROM:off_2098   o
                dc.w sprite_24_32
                dc.w $7C6D
                dc.w $9500 ! ((grp_1111C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1111C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1111C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $805D
                dc.w $9500 ! ((grp_87C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_87C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87C00 / 2) >> 16)
                dc.w 4
