byte_2F4B72:    dc.b   0,  6,$6B,$65,$93,$8E,$82,$79,$83,$79
                                        ; DATA XREF: ROM:off_2A0C   o
                dc.w sprite_24_32
                dc.w $7E60
                dc.w $9500 ! ((grp_116140 / 2) & $00FF)
                dc.w $9600 ! (((grp_116140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6E68
                dc.w $9500 ! ((grp_6D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7E80
                dc.w $9500 ! ((grp_168280 / 2) & $00FF)
                dc.w $9600 ! (((grp_168280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168280 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6676
                dc.w $9500 ! ((grp_19E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E400 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $967E
                dc.w $9500 ! ((grp_19E460 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E460 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8690
                dc.w $9500 ! ((grp_DC580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E88
                dc.w $9500 ! ((grp_F4180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4180 / 2) >> 16)
                dc.w 1
