byte_2D0664:    dc.b   0,  2,$7D,$73,$8F,$86,$86,$7C,$87,$7C
                                        ; DATA XREF: ROM:off_D58   o
                dc.w sprite_16_16
                dc.w $7E71
                dc.w $9500 ! ((grp_75C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_75C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B81
                dc.w $9500 ! ((grp_C8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E75
                dc.w $9500 ! ((grp_E34E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E34E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E34E0 / 2) >> 16)
                dc.w 1
