byte_2DDE36:    dc.b   0,  6,$76,$5F,$8B,$8D,$7F,$72,$81,$60
                                        ; DATA XREF: ROM:off_172C   o
                dc.w sprite_32_32
                dc.w $7356
                dc.w $9500 ! ((grp_25800 / 2) & $00FF)
                dc.w $9600 ! (((grp_25800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $757E
                dc.w $9500 ! ((grp_161BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_161BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6B5E
                dc.w $9500 ! ((grp_199A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_199A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D89
                dc.w $9500 ! ((grp_D4D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B76
                dc.w $9500 ! ((grp_D4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8589
                dc.w $9500 ! ((grp_D4DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $935E
                dc.w $9500 ! ((grp_BB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB600 / 2) >> 16)
                dc.w 2
