byte_2FF79A:    dc.b   0, $B,$88,$30,$CD,$76,$AA,$53,$AB,$53
                                        ; DATA XREF: ROM:off_359C   o
                dc.w sprite_32_24
                dc.w $B22E
                dc.w $9500 ! ((grp_13C6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $B246
                dc.w $9500 ! ((grp_96700 / 2) & $00FF)
                dc.w $9600 ! (((grp_96700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9256
                dc.w $9500 ! ((grp_AF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9A50
                dc.w $9500 ! ((grp_AF900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A246
                dc.w $9500 ! ((grp_AF880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $AA3E
                dc.w $9500 ! ((grp_AF800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8A63
                dc.w $9500 ! ((grp_1A12E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A12E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A12E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $826B
                dc.w $9500 ! ((grp_F9420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A266
                dc.w $9500 ! ((grp_F9440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AA5E
                dc.w $9500 ! ((grp_F9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B256
                dc.w $9500 ! ((grp_F9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C246
                dc.w $9500 ! ((grp_F93E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F93E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F93E0 / 2) >> 16)
                dc.w 1
