byte_2D6D70:    dc.b   0,  4,$74,$55,$92,$A0,$81,$3C,$82,$62
                                        ; DATA XREF: ROM:off_1290   o
                dc.w sprite_24_32
                dc.w $7BA7
                dc.w $9500 ! ((grp_10D740 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D740 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7B87
                dc.w $9500 ! ((grp_10D8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $7F67
                dc.w $9500 ! ((grp_A9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F47
                dc.w $9500 ! ((grp_A9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7D3A
                dc.w $9500 ! ((grp_BCD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCD80 / 2) >> 16)
                dc.w 2
