byte_2ED6AE:    dc.b   0,  6,$6C,$69,$9C,$94,$86,$7C,$87,$7C
                                        ; DATA XREF: ROM:off_22BC   o
                dc.w sprite_32_24
                dc.w $7471
                dc.w $9500 ! ((grp_132040 / 2) & $00FF)
                dc.w $9600 ! (((grp_132040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132040 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $9470
                dc.w $9500 ! ((grp_19C8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C8A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_D8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E89
                dc.w $9500 ! ((grp_D8C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8169
                dc.w $9500 ! ((grp_D8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C71
                dc.w $9500 ! ((grp_BEE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C80
                dc.w $9500 ! ((grp_F02E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F02E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F02E0 / 2) >> 16)
                dc.w 1
