byte_2FBA2E:    dc.b   0,  6,$70,$6E,$95,$94,$82,$81,$83,$81
                                        ; DATA XREF: ROM:off_2FBC   o
                dc.w sprite_24_32
                dc.w $7674
                dc.w $9500 ! ((grp_11C140 / 2) & $00FF)
                dc.w $9600 ! (((grp_11C140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11C140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7194
                dc.w $9500 ! ((grp_190A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_190A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7E6C
                dc.w $9500 ! ((grp_190A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_190A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8E74
                dc.w $9500 ! ((grp_19FDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FDE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6E84
                dc.w $9500 ! ((grp_C4CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E6C
                dc.w $9500 ! ((grp_F78E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F78E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F78E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $967F
                dc.w $9500 ! ((grp_F7900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7900 / 2) >> 16)
                dc.w 1
