byte_2E150A:    dc.b   0,  7,$71,$58,$93,$8F,$83,$74,$84,$74
                                        ; DATA XREF: ROM:off_1944   o
                dc.w sprite_16_16
                dc.w $6759
                dc.w $9500 ! ((grp_85D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8F62
                dc.w $9500 ! ((grp_85D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6F89
                dc.w $9500 ! ((grp_9B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $775A
                dc.w $9500 ! ((grp_A8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F58
                dc.w $9500 ! ((grp_A8E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $875B
                dc.w $9500 ! ((grp_19A440 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7C79
                dc.w $9500 ! ((grp_BC700 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8478
                dc.w $9500 ! ((grp_EE140 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE140 / 2) >> 16)
                dc.w 1
