byte_2DA814:    dc.b   0,  3,$6F,$72,$8E,$8F,$84,$7A,$8A,$78
                                        ; DATA XREF: ROM:off_14B8   o
                dc.w sprite_32_32
                dc.w $6E70
                dc.w $9500 ! ((grp_1CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1CE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8E70
                dc.w $9500 ! ((grp_A5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $966C
                dc.w $9500 ! ((grp_196F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_196F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8060
                dc.w $9500 ! ((grp_B70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B70C0 / 2) >> 16)
                dc.w 2
