byte_2E91B0:    dc.b   0,  2,$69,$43,$73,$8E,$70,$5C,$6D,$4C
                                        ; DATA XREF: ROM:off_1E20   o
                dc.w sprite_8_32
                dc.w $6E4A
                dc.w $9500 ! ((grp_A6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $663C
                dc.w $9500 ! ((grp_197380 / 2) & $00FF)
                dc.w $9600 ! (((grp_197380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7469
                dc.w $9500 ! ((grp_1973E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1973E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1973E0 / 2) >> 16)
                dc.w 3
