byte_2D751C:    dc.b   0,  4,$78,$61,$8A,$77,$82,$6C,$84,$5A
                                        ; DATA XREF: ROM:off_12E0   o
                dc.w sprite_32_32
                dc.w $7056
                dc.w $9500 ! ((grp_25000 / 2) & $00FF)
                dc.w $9600 ! (((grp_25000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6F76
                dc.w $9500 ! ((grp_1618C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1618C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1618C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $604E
                dc.w $9500 ! ((grp_84380 / 2) & $00FF)
                dc.w $9600 ! (((grp_84380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7986
                dc.w $9500 ! ((grp_ECFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECFC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906C
                dc.w $9500 ! ((grp_ECFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECFE0 / 2) >> 16)
                dc.w 1
