byte_2CD55A:    dc.b   0,  1,$79,$7E,$88,$8D,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8DC   o
                dc.w sprite_24_16
                dc.w $7780
                dc.w $9500 ! ((grp_156280 / 2) & $00FF)
                dc.w $9600 ! (((grp_156280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7978
                dc.w $9500 ! ((grp_C7100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7100 / 2) >> 16)
                dc.w 2
