byte_2D2476:    dc.b   0,  2,$75,$9F,$8B,$B5,$88,$A9,$89,$A9
                                        ; DATA XREF: ROM:off_ECC   o
                dc.w sprite_16_16
                dc.w $779C
                dc.w $9500 ! ((grp_76C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $72A4
                dc.w $9500 ! ((grp_1935A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1935A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1935A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $86A4
                dc.w $9500 ! ((grp_193600 / 2) & $00FF)
                dc.w $9600 ! (((grp_193600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193600 / 2) >> 16)
                dc.w 3
