byte_2DC414:    dc.b   0,  3,$79,$5C,$A7,$90,$8E,$66,$8F,$66
                                        ; DATA XREF: ROM:off_1618   o
                dc.w sprite_32_24
                dc.w $7B59
                dc.w $9500 ! ((grp_12F1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $9B59
                dc.w $9500 ! ((grp_19ACE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ACE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ACE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7565
                dc.w $9500 ! ((grp_BD380 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A365
                dc.w $9500 ! ((grp_EE8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE8A0 / 2) >> 16)
                dc.w 1
