byte_2D665C:    dc.b   0,  4,$6D,$48,$9C,$6E,$81,$5B,$82,$5B
                                        ; DATA XREF: ROM:off_1248   o
                dc.w sprite_32_32
                dc.w $784E
                dc.w $9500 ! ((grp_24200 / 2) & $00FF)
                dc.w $9600 ! (((grp_24200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6463
                dc.w $9500 ! ((grp_161740 / 2) & $00FF)
                dc.w $9600 ! (((grp_161740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161740 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6D46
                dc.w $9500 ! ((grp_189F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_189F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189F40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $704E
                dc.w $9500 ! ((grp_ECD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECD20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9850
                dc.w $9500 ! ((grp_ECD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECD40 / 2) >> 16)
                dc.w 1
