byte_2EFCE2:    dc.b   0,  1,$76,$7D,$87,$8E,$7E,$85,$7F,$85
                                        ; DATA XREF: ROM:off_258C   o
                dc.w sprite_24_16
                dc.w $7481
                dc.w $9500 ! ((grp_165D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_165D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7B79
                dc.w $9500 ! ((grp_DA100 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA100 / 2) >> 16)
                dc.w 2
