byte_2ED4F4:    dc.b   0,  8,$6D,$60,$8C,$93,$78,$77,$79,$77
                                        ; DATA XREF: ROM:off_22A0   o
                dc.w sprite_16_32
                dc.w $7766
                dc.w $9500 ! ((grp_68F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $775E
                dc.w $9500 ! ((grp_18CE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CE20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6F6F
                dc.w $9500 ! ((grp_19C720 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C720 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8766
                dc.w $9500 ! ((grp_19C780 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C780 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7E86
                dc.w $9500 ! ((grp_BED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BED40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $636C
                dc.w $9500 ! ((grp_F0240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $676E
                dc.w $9500 ! ((grp_F0260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C85
                dc.w $9500 ! ((grp_F02A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F02A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F02A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8689
                dc.w $9500 ! ((grp_F0280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0280 / 2) >> 16)
                dc.w 1
