byte_2DCE34:    dc.b   0,  9,$6F,$51,$8E,$8F,$7D,$6B,$82,$56
                                        ; DATA XREF: ROM:off_1678   o
                dc.w sprite_24_24
                dc.w $6E4F
                dc.w $9500 ! ((grp_1483C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1483C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1483C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7867
                dc.w $9500 ! ((grp_1484E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1484E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1484E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $707F
                dc.w $9500 ! ((grp_85480 / 2) & $00FF)
                dc.w $9600 ! (((grp_85480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $864F
                dc.w $9500 ! ((grp_85500 / 2) & $00FF)
                dc.w $9600 ! (((grp_85500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6647
                dc.w $9500 ! ((grp_BBC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C3F
                dc.w $9500 ! ((grp_BBC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E3F
                dc.w $9500 ! ((grp_BBCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E47
                dc.w $9500 ! ((grp_ED9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED9C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $778F
                dc.w $9500 ! ((grp_ED9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED9E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $865F
                dc.w $9500 ! ((grp_EDA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDA00 / 2) >> 16)
                dc.w 1
