byte_2DEE82:    dc.b   0,  5,$6F,$5F,$95,$8E,$83,$72,$76,$74
                                        ; DATA XREF: ROM:off_17C4   o
                dc.w sprite_24_32
                dc.w $7774
                dc.w $9500 ! ((grp_10CFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10CFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10CFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6F5C
                dc.w $9500 ! ((grp_12E140 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6774
                dc.w $9500 ! ((grp_85980 / 2) & $00FF)
                dc.w $9600 ! (((grp_85980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $975C
                dc.w $9500 ! ((grp_A8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8754
                dc.w $9500 ! ((grp_18AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AC00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F72
                dc.w $9500 ! ((grp_BC540 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC540 / 2) >> 16)
                dc.w 2
