byte_2E82EE:    dc.b   0,  5,$6F,$74,$8E,$8F,$7C,$5F,$7B,$7D
                                        ; DATA XREF: ROM:off_1D5C   o
                dc.w sprite_32_24
                dc.w $7379
                dc.w $9500 ! ((grp_1267C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1267C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1267C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7B71
                dc.w $9500 ! ((grp_1867C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1867C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1867C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B79
                dc.w $9500 ! ((grp_196420 / 2) & $00FF)
                dc.w $9600 ! (((grp_196420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D69
                dc.w $9500 ! ((grp_CE0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A59
                dc.w $9500 ! ((grp_B6040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9372
                dc.w $9500 ! ((grp_B6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6080 / 2) >> 16)
                dc.w 2
