byte_2D7032:    dc.b   0,  7,$74,$55,$92,$7A,$80,$4E,$8D,$50
                                        ; DATA XREF: ROM:off_12AC   o
                dc.w sprite_24_24
                dc.w $7A4A
                dc.w $9500 ! ((grp_148DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_148DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148DE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7A62
                dc.w $9500 ! ((grp_66A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A52
                dc.w $9500 ! ((grp_86400 / 2) & $00FF)
                dc.w $9600 ! (((grp_86400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9259
                dc.w $9500 ! ((grp_19AAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AAA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $655A
                dc.w $9500 ! ((grp_BCF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A5F
                dc.w $9500 ! ((grp_BCFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B82
                dc.w $9500 ! ((grp_EE620 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A76
                dc.w $9500 ! ((grp_EE640 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE640 / 2) >> 16)
                dc.w 1
