byte_2D934A:    dc.b   0, $C,$53,$28,$A7,$69,$7D,$48,$7E,$48
                                        ; DATA XREF: ROM:off_141C   o
                dc.w sprite_32_32
                dc.w $594E
                dc.w $9500 ! ((grp_1C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1C600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5136
                dc.w $9500 ! ((grp_126F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_126F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $892E
                dc.w $9500 ! ((grp_1270C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1270C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1270C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $914E
                dc.w $9500 ! ((grp_1443A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1443A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1443A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7937
                dc.w $9500 ! ((grp_61900 / 2) & $00FF)
                dc.w $9600 ! (((grp_61900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8946
                dc.w $9500 ! ((grp_A5B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $592E
                dc.w $9500 ! ((grp_CF100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9946
                dc.w $9500 ! ((grp_CF140 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5155
                dc.w $9500 ! ((grp_B6A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7136
                dc.w $9500 ! ((grp_B6A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9366
                dc.w $9500 ! ((grp_E8EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9526
                dc.w $9500 ! ((grp_E8EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A951
                dc.w $9500 ! ((grp_E8F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F00 / 2) >> 16)
                dc.w 1
