byte_2D236A:    dc.b   0,  4,$72,$A4,$8E,$B5,$89,$AC,$8A,$AC
                                        ; DATA XREF: ROM:off_EBC   o
                dc.w sprite_24_8
                dc.w $79A3
                dc.w $9500 ! ((grp_1845A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1845A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1845A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $71A2
                dc.w $9500 ! ((grp_1934E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1934E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1934E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $86AB
                dc.w $9500 ! ((grp_C9D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $89B3
                dc.w $9500 ! ((grp_C9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $69A9
                dc.w $9500 ! ((grp_B25C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B25C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B25C0 / 2) >> 16)
                dc.w 2
