byte_2EFC70:    dc.b   0,  1,$77,$7C,$8D,$8D,$82,$84,$83,$84
                                        ; DATA XREF: ROM:off_2580   o
                dc.w sprite_24_24
                dc.w $757A
                dc.w $9500 ! ((grp_14D040 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D040 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $8D7F
                dc.w $9500 ! ((grp_F1360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1360 / 2) >> 16)
                dc.w 1
