byte_2CC8F6:    dc.b   0,  6,$6B,$5A,$95,$92,$80,$76,$81,$76
                                        ; DATA XREF: ROM:off_7DC   o
                dc.w sprite_32_24
                dc.w $6C7C
                dc.w $9500 ! ((grp_11E9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E9C0 / 2) >> 16)
                dc.w    $C
                dc.w sprite_24_24
                dc.w $735C
                dc.w $9500 ! ((grp_13DE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_13DE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13DE60 / 2) >> 16)
                dc.w     9
                dc.w sprite_8_24
                dc.w $8C7C
                dc.w $9500 ! ((grp_191BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_191BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191BC0 / 2) >> 16)
                dc.w     3
                dc.w sprite_8_8
                dc.w $647D
                dc.w $9500 ! ((grp_E1580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1580 / 2) >> 16)
                dc.w     1
                dc.w sprite_8_8
                dc.w $7C54
                dc.w $9500 ! ((grp_E15A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E15A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E15A0 / 2) >> 16)
                dc.w     1
                dc.w sprite_8_8
                dc.w $8B60
                dc.w $9500 ! ((grp_E15E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E15E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E15E0 / 2) >> 16)
                dc.w     1
                dc.w sprite_8_8
                dc.w $947C
                dc.w $9500 ! ((grp_E15C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E15C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E15C0 / 2) >> 16)
                dc.w     1
