byte_2EAA6C:    dc.b   0,  3,$70,$6D,$8E,$8B,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_1F78   o
                dc.w sprite_24_32
                dc.w $7973
                dc.w $9500 ! ((grp_10F9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $7173
                dc.w $9500 ! ((grp_19B8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B8E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $766B
                dc.w $9500 ! ((grp_D7400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6980
                dc.w $9500 ! ((grp_EF160 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF160 / 2) >> 16)
                dc.w 1
