byte_2CF8D6:    dc.b   0,  1,$77,$78,$88,$86,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_BAC   o
                dc.w sprite_24_16
                dc.w $7479
                dc.w $9500 ! ((grp_157300 / 2) & $00FF)
                dc.w $9600 ! (((grp_157300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157300 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7D71
                dc.w $9500 ! ((grp_E2E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2E20 / 2) >> 16)
                dc.w 1
