byte_2E8D62:    dc.b   0,  3,$79,$50,$80,$8B,$7B,$6D,$7F,$52
                                        ; DATA XREF: ROM:off_1DD4   o
                dc.w sprite_16_32
                dc.w $744E
                dc.w $9500 ! ((grp_61300 / 2) & $00FF)
                dc.w $9600 ! (((grp_61300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $786E
                dc.w $9500 ! ((grp_A5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7075
                dc.w $9500 ! ((grp_E8AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $806E
                dc.w $9500 ! ((grp_E8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8B00 / 2) >> 16)
                dc.w 1
