byte_2D0394:    dc.b   0,  3,$70,$70,$8A,$8F,$7D,$7F,$7E,$7F
                                        ; DATA XREF: ROM:off_D10   o
                dc.w sprite_24_24
                dc.w $777F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $766F
                dc.w $9500 ! ((grp_1576C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1576C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1576C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6E6E
                dc.w $9500 ! ((grp_B1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A67
                dc.w $9500 ! ((grp_E3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3280 / 2) >> 16)
                dc.w 1
