byte_2F55EE:    dc.b   0,  5,$6D,$56,$92,$8E,$7F,$72,$80,$72
                                        ; DATA XREF: ROM:off_2ABC   o
                dc.w sprite_32_32
                dc.w $7059
                dc.w $9500 ! ((grp_3D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7079
                dc.w $9500 ! ((grp_150D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_150D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150D00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7C51
                dc.w $9500 ! ((grp_DCCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8879
                dc.w $9500 ! ((grp_C2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9074
                dc.w $9500 ! ((grp_C21C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C21C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C21C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6867
                dc.w $9500 ! ((grp_F4900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4900 / 2) >> 16)
                dc.w 1
