byte_2F55A8:    dc.b   0,  4,$71,$54,$95,$8E,$83,$71,$84,$71
                                        ; DATA XREF: ROM:off_2AB8   o
                dc.w sprite_32_32
                dc.w $706A
                dc.w $9500 ! ((grp_3CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3CE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7152
                dc.w $9500 ! ((grp_150BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_150BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150BE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $798A
                dc.w $9500 ! ((grp_DCC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9071
                dc.w $9500 ! ((grp_C2140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6965
                dc.w $9500 ! ((grp_F48E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F48E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F48E0 / 2) >> 16)
                dc.w 1
