byte_2FF14A:    dc.b   0,  3,$79,$7F,$92,$94,$85,$89,$86,$89
                                        ; DATA XREF: ROM:off_354C   o
                dc.w sprite_16_24
                dc.w $7A7E
                dc.w $9500 ! ((grp_182E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_182E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8A7B
                dc.w $9500 ! ((grp_1A1460 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1460 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8573
                dc.w $9500 ! ((grp_E0EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7282
                dc.w $9500 ! ((grp_C6640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6640 / 2) >> 16)
                dc.w 2
