byte_2EDA28:    dc.b   0,  6,$69,$65,$98,$95,$7D,$7B,$7E,$7B
                                        ; DATA XREF: ROM:off_22E8   o
                dc.w sprite_32_32
                dc.w $6B6E
                dc.w $9500 ! ((grp_30C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_30C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8B66
                dc.w $9500 ! ((grp_68D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $838E
                dc.w $9500 ! ((grp_D8900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6372
                dc.w $9500 ! ((grp_BEBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $728E
                dc.w $9500 ! ((grp_F00E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F00E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F00E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8366
                dc.w $9500 ! ((grp_F0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B86
                dc.w $9500 ! ((grp_F0120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0120 / 2) >> 16)
                dc.w 1
