byte_2DDEE6:    dc.b   0,  5,$76,$5F,$8B,$8E,$80,$73,$82,$60
                                        ; DATA XREF: ROM:off_1734   o
                dc.w sprite_32_32
                dc.w $7356
                dc.w $9500 ! ((grp_25800 / 2) & $00FF)
                dc.w $9600 ! (((grp_25800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7782
                dc.w $9500 ! ((grp_4F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7B76
                dc.w $9500 ! ((grp_84680 / 2) & $00FF)
                dc.w $9600 ! (((grp_84680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B5E
                dc.w $9500 ! ((grp_199A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_199A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8A
                dc.w $9500 ! ((grp_D4E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $935E
                dc.w $9500 ! ((grp_BB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB600 / 2) >> 16)
                dc.w 2
