byte_2EA2F2:    dc.b   0,  5,$66,$66,$98,$89,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F24   o
                dc.w sprite_24_32
                dc.w $7C6C
                dc.w $9500 ! ((grp_10F240 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6C64
                dc.w $9500 ! ((grp_67500 / 2) & $00FF)
                dc.w $9600 ! (((grp_67500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67500 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7C64
                dc.w $9500 ! ((grp_9C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6484
                dc.w $9500 ! ((grp_18B8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B8C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $647C
                dc.w $9500 ! ((grp_EEF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEF60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9474
                dc.w $9500 ! ((grp_EEF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEF80 / 2) >> 16)
                dc.w 1
