byte_2EEAAC:    dc.b   0,  6,$6E,$4E,$89,$8E,$80,$73,$81,$73
                                        ; DATA XREF: ROM:off_2400   o
                dc.w sprite_32_32
                dc.w $5F59
                dc.w $9500 ! ((grp_33000 / 2) & $00FF)
                dc.w $9600 ! (((grp_33000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6179
                dc.w $9500 ! ((grp_132C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_132C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $817A
                dc.w $9500 ! ((grp_132DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_132DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7F6A
                dc.w $9500 ! ((grp_89E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_89E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5984
                dc.w $9500 ! ((grp_F0920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6151
                dc.w $9500 ! ((grp_F0940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A187
                dc.w $9500 ! ((grp_F0960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0960 / 2) >> 16)
                dc.w 1
