byte_2DF878:    dc.b   0,  7,$58,$54,$90,$8D,$74,$70,$7A,$64
                                        ; DATA XREF: ROM:off_1830   o
                dc.w sprite_24_32
                dc.w $7060
                dc.w $9500 ! ((grp_1087C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1087C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1087C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7780
                dc.w $9500 ! ((grp_15F580 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $606A
                dc.w $9500 ! ((grp_80D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8351
                dc.w $9500 ! ((grp_80D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B5C
                dc.w $9500 ! ((grp_188E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_188E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $506C
                dc.w $9500 ! ((grp_D2880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F88
                dc.w $9500 ! ((grp_EB560 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_EB580 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB580 / 2) >> 16)
                dc.w 1
