byte_2F956C:    dc.b   0,  3,$79,$63,$89,$7E,$81,$70,$82,$70
                                        ; DATA XREF: ROM:off_2D50   o
                dc.w sprite_16_16
                dc.w $7761
                dc.w $9500 ! ((grp_91080 / 2) & $00FF)
                dc.w $9600 ! (((grp_91080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A71
                dc.w $9500 ! ((grp_F6840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F79
                dc.w $9500 ! ((grp_F6860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8766
                dc.w $9500 ! ((grp_F6880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6880 / 2) >> 16)
                dc.w 1
