byte_2E96F4:    dc.b   0,  8,$54,$16,$9D,$80,$78,$28,$79,$28
                                        ; DATA XREF: ROM:off_1E78   o
                dc.w sprite_32_32
                dc.w $5117
                dc.w $9500 ! ((grp_27A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7116
                dc.w $9500 ! ((grp_66E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9118
                dc.w $9500 ! ((grp_66F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $5137
                dc.w $9500 ! ((grp_9C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $891D
                dc.w $9500 ! ((grp_A9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $570F
                dc.w $9500 ! ((grp_18B560 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8120
                dc.w $9500 ! ((grp_19AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7136
                dc.w $9500 ! ((grp_D6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9138
                dc.w $9500 ! ((grp_EEB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB20 / 2) >> 16)
                dc.w 1
