byte_2EB602:    dc.b   0,  5,$71,$55,$8F,$8D,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_2034   o
                dc.w sprite_32_32
                dc.w $6E6E
                dc.w $9500 ! ((grp_2B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2B000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8E76
                dc.w $9500 ! ((grp_17ADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17ADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17ADC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6E8E
                dc.w $9500 ! ((grp_9C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6676
                dc.w $9500 ! ((grp_19BB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BB80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8E6E
                dc.w $9500 ! ((grp_EF560 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E8E
                dc.w $9500 ! ((grp_EF580 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF580 / 2) >> 16)
                dc.w 1
