byte_2DB026:    dc.b   0, $D,$5B,$51,$96,$8E,$78,$6F,$79,$6F
                                        ; DATA XREF: ROM:off_152C   o
                dc.w sprite_24_24
                dc.w $7360
                dc.w $9500 ! ((grp_148840 / 2) & $00FF)
                dc.w $9600 ! (((grp_148840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148840 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5C57
                dc.w $9500 ! ((grp_85680 / 2) & $00FF)
                dc.w $9600 ! (((grp_85680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_D5A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A78
                dc.w $9500 ! ((grp_D5AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8380
                dc.w $9500 ! ((grp_D5B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8988
                dc.w $9500 ! ((grp_D5B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B63
                dc.w $9500 ! ((grp_BBFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8350
                dc.w $9500 ! ((grp_BC000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B4C
                dc.w $9500 ! ((grp_BC040 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $545C
                dc.w $9500 ! ((grp_EDBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDBC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6367
                dc.w $9500 ! ((grp_EDBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDBE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7386
                dc.w $9500 ! ((grp_EDC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDC00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7880
                dc.w $9500 ! ((grp_EDC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDC20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $934D
                dc.w $9500 ! ((grp_EDC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDC40 / 2) >> 16)
                dc.w 1
