byte_2FEE2C:    dc.b   0,  1,$7C,$70,$84,$87,$80,$7B,$81,$7B
                                        ; DATA XREF: ROM:off_34F8   o
                dc.w sprite_16_16
                dc.w $797E
                dc.w $9500 ! ((grp_96980 / 2) & $00FF)
                dc.w $9600 ! (((grp_96980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7E6E
                dc.w $9500 ! ((grp_C6840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6840 / 2) >> 16)
                dc.w 2
