byte_2F4C46:    dc.b   0, $A,$6C,$62,$91,$90,$8D,$75,$8E,$75
                                        ; DATA XREF: ROM:off_2A14   o
                dc.w sprite_32_32
                dc.w $7268
                dc.w $9500 ! ((grp_3B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3B600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $8888
                dc.w $9500 ! ((grp_168400 / 2) & $00FF)
                dc.w $9600 ! (((grp_168400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168400 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $9278
                dc.w $9500 ! ((grp_168340 / 2) & $00FF)
                dc.w $9600 ! (((grp_168340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6377
                dc.w $9500 ! ((grp_17E6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E6C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7A60
                dc.w $9500 ! ((grp_18EA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EA40 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $A16E
                dc.w $9500 ! ((grp_18EAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EAA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7888
                dc.w $9500 ! ((grp_DC5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9C60
                dc.w $9500 ! ((grp_DC600 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A6F
                dc.w $9500 ! ((grp_F4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9056
                dc.w $9500 ! ((grp_F4220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AA82
                dc.w $9500 ! ((grp_F4240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4240 / 2) >> 16)
                dc.w 1
