byte_2D35BA:    dc.b   0,  5,$75,$5B,$88,$95,$80,$79,$81,$79
                                        ; DATA XREF: ROM:00001014   o
                dc.w sprite_16_32
                dc.w $7859
                dc.w $9500 ! ((grp_5E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7A79
                dc.w $9500 ! ((grp_5E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $705A
                dc.w $9500 ! ((grp_193F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_193F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A7B
                dc.w $9500 ! ((grp_CA640 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A78
                dc.w $9500 ! ((grp_CA680 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E99
                dc.w $9500 ! ((grp_E4F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4F20 / 2) >> 16)
                dc.w 1
