byte_2EDDE6:    dc.b   0,  4,$77,$79,$99,$91,$88,$85,$89,$85
                                        ; DATA XREF: ROM:off_231C   o
                dc.w sprite_24_16
                dc.w $7584
                dc.w $9500 ! ((grp_164F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_164F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7D7C
                dc.w $9500 ! ((grp_D8F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $947B
                dc.w $9500 ! ((grp_BF040 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8274
                dc.w $9500 ! ((grp_F04E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F04E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F04E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D83
                dc.w $9500 ! ((grp_F0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0500 / 2) >> 16)
                dc.w 1
