byte_2E71FA:    dc.b   0,  6,$6F,$67,$8E,$8F,$A6,$73,$93,$63
                                        ; DATA XREF: ROM:off_1CC4   o
                dc.w sprite_24_32
                dc.w $7461
                dc.w $9500 ! ((grp_10B1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8C61
                dc.w $9500 ! ((grp_147400 / 2) & $00FF)
                dc.w $9600 ! (((grp_147400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147400 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6E81
                dc.w $9500 ! ((grp_83E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6467
                dc.w $9500 ! ((grp_D4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E81
                dc.w $9500 ! ((grp_D42C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D42C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D42C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8489
                dc.w $9500 ! ((grp_D4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C71
                dc.w $9500 ! ((grp_BB0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB0C0 / 2) >> 16)
                dc.w 2
