byte_2D555C:    dc.b   0,  5,$6F,$64,$8E,$8F,$7F,$77,$6E,$6A
                                        ; DATA XREF: ROM:off_1198   o
                dc.w sprite_24_32
                dc.w $6861
                dc.w $9500 ! ((grp_FED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FED40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7581
                dc.w $9500 ! ((grp_185260 / 2) & $00FF)
                dc.w $9600 ! (((grp_185260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185260 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CB940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8788
                dc.w $9500 ! ((grp_CB980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8069
                dc.w $9500 ! ((grp_B3A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7159
                dc.w $9500 ! ((grp_E6160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6160 / 2) >> 16)
                dc.w 1
