byte_2EC3FA:    dc.b   0,  1,$79,$7E,$85,$8D,$7F,$85,$80,$85
                                        ; DATA XREF: ROM:off_20DC   o
                dc.w sprite_24_16
                dc.w $747C
                dc.w $9500 ! ((grp_163C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_163C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $798C
                dc.w $9500 ! ((grp_EF9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF9E0 / 2) >> 16)
                dc.w 1
