byte_2CD18A:    dc.b   0,  2,$6E,$70,$8F,$8E,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_884   o
                dc.w sprite_32_32
                dc.w $7471
                dc.w $9500 ! ((grp_10E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $6C76
                dc.w $9500 ! ((grp_191EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_191EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A69
                dc.w $9500 ! ((grp_C80C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C80C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C80C0 / 2) >> 16)
                dc.w 2
