byte_2DD3B6:    dc.b   0,  5,$77,$68,$8E,$81,$7F,$74,$88,$67
                                        ; DATA XREF: ROM:off_16B4   o
                dc.w sprite_24_32
                dc.w $7971
                dc.w $9500 ! ((grp_1018C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1018C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1018C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7959
                dc.w $9500 ! ((grp_142D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_142D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142D20 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $915C
                dc.w $9500 ! ((grp_195640 / 2) & $00FF)
                dc.w $9600 ! (((grp_195640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195640 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6165
                dc.w $9500 ! ((grp_CD140 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7162
                dc.w $9500 ! ((grp_B4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7178
                dc.w $9500 ! ((grp_E7600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7600 / 2) >> 16)
                dc.w 1
