byte_2D84D8:    dc.b   0,  6,$78,$61,$8E,$7B,$82,$6F,$86,$62
                                        ; DATA XREF: ROM:off_1390   o
                dc.w sprite_24_24
                dc.w $745C
                dc.w $9500 ! ((grp_141FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_141FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141FA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7C74
                dc.w $9500 ! ((grp_173500 / 2) & $00FF)
                dc.w $9600 ! (((grp_173500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8C59
                dc.w $9500 ! ((grp_79600 / 2) & $00FF)
                dc.w $9600 ! (((grp_79600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7754
                dc.w $9500 ! ((grp_CC800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C5F
                dc.w $9500 ! ((grp_B44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B44C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7474
                dc.w $9500 ! ((grp_E6CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C77
                dc.w $9500 ! ((grp_E6CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6CC0 / 2) >> 16)
                dc.w 1
