byte_2F4624:    dc.b   0,  1,$79,$71,$89,$8F,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_2998   o
                dc.w sprite_24_24
                dc.w $776F
                dc.w $9500 ! ((grp_150520 / 2) & $00FF)
                dc.w $9600 ! (((grp_150520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150520 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7887
                dc.w $9500 ! ((grp_8DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8DD00 / 2) >> 16)
                dc.w 4
