byte_2F1F9E:    dc.b   0,  7,$6E,$74,$9F,$8E,$8F,$73,$90,$73
                                        ; DATA XREF: ROM:off_26DC   o
                dc.w sprite_24_32
                dc.w $7474
                dc.w $9500 ! ((grp_1135C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1135C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1135C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8C6D
                dc.w $9500 ! ((grp_14E360 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E360 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $9B55
                dc.w $9500 ! ((grp_17CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CE00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8F59
                dc.w $9500 ! ((grp_C0180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $935C
                dc.w $9500 ! ((grp_C0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A46D
                dc.w $9500 ! ((grp_C00C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C00C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C00C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB59
                dc.w $9500 ! ((grp_C0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C80
                dc.w $9500 ! ((grp_F1CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1CE0 / 2) >> 16)
                dc.w 1
