byte_2CFBA2:    dc.b   0,  2,$77,$73,$87,$8D,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_C14   o
                dc.w sprite_16_24
                dc.w $7671
                dc.w $9500 ! ((grp_170800 / 2) & $00FF)
                dc.w $9600 ! (((grp_170800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7689
                dc.w $9500 ! ((grp_C8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8672
                dc.w $9500 ! ((grp_E2FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2FC0 / 2) >> 16)
                dc.w 1
