byte_2E8FCA:    dc.b   0,  5,$7A,$6E,$8B,$8E,$81,$79,$8A,$7B
                                        ; DATA XREF: ROM:off_1DFC   o
                dc.w sprite_24_16
                dc.w $7979
                dc.w $9500 ! ((grp_15EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EF80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7389
                dc.w $9500 ! ((grp_188560 / 2) & $00FF)
                dc.w $9600 ! (((grp_188560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $717B
                dc.w $9500 ! ((grp_EA9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA9C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C61
                dc.w $9500 ! ((grp_EA980 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8069
                dc.w $9500 ! ((grp_EA9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA9E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8571
                dc.w $9500 ! ((grp_EA9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA9A0 / 2) >> 16)
                dc.w 1
