byte_2FE4D6:    dc.b   0,  4,$74,$76,$89,$8A,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_33DC   o
                dc.w sprite_16_24
                dc.w $7774
                dc.w $9500 ! ((grp_1828C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1828C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1828C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $677A
                dc.w $9500 ! ((grp_E0480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8778
                dc.w $9500 ! ((grp_C6180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $688B
                dc.w $9500 ! ((grp_F8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937E
                dc.w $9500 ! ((grp_F8BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8BA0 / 2) >> 16)
                dc.w 1
