byte_2E7258:    dc.b   0,  9,$6F,$6E,$8E,$8F,$B5,$76,$B8,$76
                                        ; DATA XREF: ROM:off_1CC8   o
                dc.w sprite_32_32
                dc.w $6E6C
                dc.w $9500 ! ((grp_23E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_23E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $8E70
                dc.w $9500 ! ((grp_9B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B200 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $BD75
                dc.w $9500 ! ((grp_9B280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5E7A
                dc.w $9500 ! ((grp_D4340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E8C
                dc.w $9500 ! ((grp_D4440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838C
                dc.w $9500 ! ((grp_D4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AD72
                dc.w $9500 ! ((grp_D43C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D43C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D43C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $C86D
                dc.w $9500 ! ((grp_D4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E78
                dc.w $9500 ! ((grp_ECC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECC40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A578
                dc.w $9500 ! ((grp_ECC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECC60 / 2) >> 16)
                dc.w 1
