byte_2FE644:    dc.b   0,  1,$73,$77,$8B,$8A,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_3400   o
                dc.w sprite_32_16
                dc.w $6E75
                dc.w $9500 ! ((grp_59C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_59C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7585
                dc.w $9500 ! ((grp_191740 / 2) & $00FF)
                dc.w $9600 ! (((grp_191740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191740 / 2) >> 16)
                dc.w 3
