byte_2D60CA:    dc.b   0,  5,$6F,$6A,$8E,$8F,$7E,$7B,$83,$6F
                                        ; DATA XREF: ROM:off_1214   o
                dc.w sprite_32_32
                dc.w $6D6F
                dc.w $9500 ! ((grp_1EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1EA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7467
                dc.w $9500 ! ((grp_188800 / 2) & $00FF)
                dc.w $9600 ! (((grp_188800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188800 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6571
                dc.w $9500 ! ((grp_197D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_197D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8F
                dc.w $9500 ! ((grp_D1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D70
                dc.w $9500 ! ((grp_B8AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C87
                dc.w $9500 ! ((grp_EACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EACC0 / 2) >> 16)
                dc.w 1
