byte_2D4A8E:    dc.b   0,  5,$29,$81,$69,$93,$49,$8A,$4A,$8A
                                        ; DATA XREF: ROM:off_1114   o
                dc.w sprite_32_16
                dc.w $2F85
                dc.w $9500 ! ((grp_4C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C600 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $4F83
                dc.w $9500 ! ((grp_187D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_187D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187D80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5F7F
                dc.w $9500 ! ((grp_D07C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D07C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D07C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $2785
                dc.w $9500 ! ((grp_B7B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $317D
                dc.w $9500 ! ((grp_E9E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4F8B
                dc.w $9500 ! ((grp_E9E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9E80 / 2) >> 16)
                dc.w 1
