byte_2F40FC:    dc.b   0,  1,$78,$76,$8A,$8B,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28D8   o
                dc.w sprite_24_16
                dc.w $7674
                dc.w $9500 ! ((grp_167EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_167EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7684
                dc.w $9500 ! ((grp_8D880 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D880 / 2) >> 16)
                dc.w 4
