byte_2F731C:    dc.b   0,  8,$6F,$5B,$9C,$83,$72,$90,$73,$90
                                        ; DATA XREF: ROM:off_2B88   o
                dc.w sprite_32_24
                dc.w $8561
                dc.w $9500 ! ((grp_137A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_137A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6D69
                dc.w $9500 ! ((grp_169900 / 2) & $00FF)
                dc.w $9600 ! (((grp_169900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169900 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7379
                dc.w $9500 ! ((grp_1699C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1699C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1699C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6561
                dc.w $9500 ! ((grp_9F780 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6959
                dc.w $9500 ! ((grp_18F2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F2E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8B79
                dc.w $9500 ! ((grp_DD500 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9559
                dc.w $9500 ! ((grp_DD540 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A563
                dc.w $9500 ! ((grp_C2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8959
                dc.w $9500 ! ((grp_F5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5600 / 2) >> 16)
                dc.w 1
