byte_2E6ED0:    dc.b   0,  6,$74,$53,$92,$78,$7D,$64,$78,$78
                                        ; DATA XREF: ROM:off_1CA0   o
                dc.w sprite_24_24
                dc.w $735C
                dc.w $9500 ! ((grp_144160 / 2) & $00FF)
                dc.w $9600 ! (((grp_144160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144160 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6D74
                dc.w $9500 ! ((grp_99080 / 2) & $00FF)
                dc.w $9600 ! (((grp_99080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7354
                dc.w $9500 ! ((grp_CEA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B4F
                dc.w $9500 ! ((grp_B6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B64
                dc.w $9500 ! ((grp_B66C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B66C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B66C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8756
                dc.w $9500 ! ((grp_B6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_E8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8C00 / 2) >> 16)
                dc.w 1
