byte_2EB97E:    dc.b   0, $C,$54,$68,$D2,$8F,$93,$7B,$94,$7B
                                        ; DATA XREF: ROM:off_205C   o
                dc.w sprite_32_32
                dc.w $6568
                dc.w $9500 ! ((grp_2C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8569
                dc.w $9500 ! ((grp_2C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $A56A
                dc.w $9500 ! ((grp_110740 / 2) & $00FF)
                dc.w $9600 ! (((grp_110740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $5570
                dc.w $9500 ! ((grp_68000 / 2) & $00FF)
                dc.w $9600 ! (((grp_68000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $BD70
                dc.w $9500 ! ((grp_68200 / 2) & $00FF)
                dc.w $9600 ! (((grp_68200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8488
                dc.w $9500 ! ((grp_87880 / 2) & $00FF)
                dc.w $9600 ! (((grp_87880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A588
                dc.w $9500 ! ((grp_87900 / 2) & $00FF)
                dc.w $9600 ! (((grp_87900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87900 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6588
                dc.w $9500 ! ((grp_9CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6260
                dc.w $9500 ! ((grp_18C0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C0A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4D70
                dc.w $9500 ! ((grp_19BCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BCA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5568
                dc.w $9500 ! ((grp_D7D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $CD78
                dc.w $9500 ! ((grp_BE140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6590
                dc.w $9500 ! ((grp_EF6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6E0 / 2) >> 16)
                dc.w 1
