byte_2EF7B4:    dc.b   0,  2,$7E,$4D,$96,$65,$8A,$59,$8B,$59
                                        ; DATA XREF: ROM:off_2520   o
                dc.w sprite_24_16
                dc.w $844B
                dc.w $9500 ! ((grp_165940 / 2) & $00FF)
                dc.w $9600 ! (((grp_165940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165940 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7C63
                dc.w $9500 ! ((grp_F10E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F10E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F10E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $875B
                dc.w $9500 ! ((grp_F1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1100 / 2) >> 16)
                dc.w 1
