byte_2DDBB6:    dc.b   0,  3,$78,$63,$8F,$90,$83,$79,$8E,$6D
                                        ; DATA XREF: ROM:off_1704   o
                dc.w sprite_24_32
                dc.w $7172
                dc.w $9500 ! ((grp_107D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_107D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7D6B
                dc.w $9500 ! ((grp_D2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8974
                dc.w $9500 ! ((grp_B9040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D92
                dc.w $9500 ! ((grp_EB220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB220 / 2) >> 16)
                dc.w 1
