byte_2D4238:    dc.b   0,  5,$79,$64,$9B,$90,$83,$79,$84,$79
                                        ; DATA XREF: ROM:off_10B0   o
                dc.w sprite_32_16
                dc.w $7B80
                dc.w $9500 ! ((grp_48E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8A60
                dc.w $9500 ! ((grp_5EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5EE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7A68
                dc.w $9500 ! ((grp_CAB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $737F
                dc.w $9500 ! ((grp_B2EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B7F
                dc.w $9500 ! ((grp_E52C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E52C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E52C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8278
                dc.w $9500 ! ((grp_E52E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E52E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E52E0 / 2) >> 16)
                dc.w 1
