byte_2EE05C:    dc.b   0,  2,$76,$6C,$8A,$78,$80,$72,$81,$72
                                        ; DATA XREF: ROM:off_2358   o
                dc.w sprite_16_16
                dc.w $7A6B
                dc.w $9500 ! ((grp_89980 / 2) & $00FF)
                dc.w $9600 ! (((grp_89980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $726F
                dc.w $9500 ! ((grp_F0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A6B
                dc.w $9500 ! ((grp_F0620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0620 / 2) >> 16)
                dc.w 1
