byte_2F1D38:    dc.b   0,  1,$79,$71,$8B,$8E,$82,$7F,$83,$7F
                                        ; DATA XREF: ROM:off_26C8   o
                dc.w sprite_24_32
                dc.w $7772
                dc.w $9500 ! ((grp_113440 / 2) & $00FF)
                dc.w $9600 ! (((grp_113440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113440 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $876F
                dc.w $9500 ! ((grp_F1BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1BE0 / 2) >> 16)
                dc.w 1
