byte_2E4298:    dc.b   0,  7,$61,$5F,$92,$8F,$79,$77,$7A,$77
                                        ; DATA XREF: ROM:off_1B28   o
                dc.w sprite_24_32
                dc.w $6762
                dc.w $9500 ! ((grp_1072C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1072C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1072C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6F82
                dc.w $9500 ! ((grp_80380 / 2) & $00FF)
                dc.w $9600 ! (((grp_80380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F71
                dc.w $9500 ! ((grp_A6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5F6B
                dc.w $9500 ! ((grp_197F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_197F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E5A
                dc.w $9500 ! ((grp_D1F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8773
                dc.w $9500 ! ((grp_D1FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $878B
                dc.w $9500 ! ((grp_D2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $877B
                dc.w $9500 ! ((grp_EAF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAF60 / 2) >> 16)
                dc.w 1
