byte_2F61D0:    dc.b   0,$16,$5F,$4E,$84,$83,$78,$7C,$79,$7C
                                        ; DATA XREF: ROM:off_2B40   o
                dc.w sprite_32_32
                dc.w $5361
                dc.w $9500 ! ((grp_3D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $733E
                dc.w $9500 ! ((grp_116EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_116EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $735E
                dc.w $9500 ! ((grp_117040 / 2) & $00FF)
                dc.w $9600 ! (((grp_117040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5349
                dc.w $9500 ! ((grp_137440 / 2) & $00FF)
                dc.w $9600 ! (((grp_137440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $732E
                dc.w $9500 ! ((grp_169240 / 2) & $00FF)
                dc.w $9600 ! (((grp_169240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $3B67
                dc.w $9500 ! ((grp_17E9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E9C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $5331
                dc.w $9500 ! ((grp_17EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EF00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6332
                dc.w $9500 ! ((grp_8F280 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B38
                dc.w $9500 ! ((grp_8F300 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A352
                dc.w $9500 ! ((grp_8F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $3B47
                dc.w $9500 ! ((grp_AD600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $433F
                dc.w $9500 ! ((grp_AD680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4B40
                dc.w $9500 ! ((grp_AD700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $737E
                dc.w $9500 ! ((grp_18EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4B64
                dc.w $9500 ! ((grp_19EA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EA60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9B45
                dc.w $9500 ! ((grp_19EC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EC40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B72
                dc.w $9500 ! ((grp_C2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B48
                dc.w $9500 ! ((grp_C2380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9348
                dc.w $9500 ! ((grp_C28C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C28C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C28C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B250
                dc.w $9500 ! ((grp_C2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $435F
                dc.w $9500 ! ((grp_F4F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4B38
                dc.w $9500 ! ((grp_F4F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A2A
                dc.w $9500 ! ((grp_F4F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4F40 / 2) >> 16)
                dc.w 1
