byte_2EDE8A:    dc.b   0,  6,$7C,$61,$A6,$92,$8E,$79,$8F,$79
                                        ; DATA XREF: ROM:off_2324   o
                dc.w sprite_24_24
                dc.w $797D
                dc.w $9500 ! ((grp_14C980 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C980 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $9174
                dc.w $9500 ! ((grp_19CA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CA80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C75
                dc.w $9500 ! ((grp_D8EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D62
                dc.w $9500 ! ((grp_BEF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7189
                dc.w $9500 ! ((grp_F03C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F03C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F03C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9972
                dc.w $9500 ! ((grp_F03E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F03E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F03E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A45D
                dc.w $9500 ! ((grp_F0400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0400 / 2) >> 16)
                dc.w 1
