byte_2E77B0:    dc.b   0, $A,$6F,$72,$8E,$8F,$CB,$BA,$B5,$8F
                                        ; DATA XREF: ROM:off_1CF8   o
                dc.w sprite_24_24
                dc.w $7B72
                dc.w $9500 ! ((grp_145480 / 2) & $00FF)
                dc.w $9600 ! (((grp_145480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145480 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $9373
                dc.w $9500 ! ((grp_7F380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $C3A2
                dc.w $9500 ! ((grp_197680 / 2) & $00FF)
                dc.w $9600 ! (((grp_197680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197680 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708A
                dc.w $9500 ! ((grp_D0A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838A
                dc.w $9500 ! ((grp_D0AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A379
                dc.w $9500 ! ((grp_B80C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B80C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B80C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB81
                dc.w $9500 ! ((grp_B8040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B38B
                dc.w $9500 ! ((grp_B8100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $BB97
                dc.w $9500 ! ((grp_B8080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7377
                dc.w $9500 ! ((grp_EA260 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $CBB7
                dc.w $9500 ! ((grp_EA280 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA280 / 2) >> 16)
                dc.w 1
