byte_2FDAD2:    dc.b   0,  7,$58,$5A,$90,$8D,$74,$73,$75,$73
                                        ; DATA XREF: ROM:off_332C   o
                dc.w sprite_16_32
                dc.w $7D59
                dc.w $9500 ! ((grp_71100 / 2) & $00FF)
                dc.w $9600 ! (((grp_71100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5660
                dc.w $9500 ! ((grp_95580 / 2) & $00FF)
                dc.w $9600 ! (((grp_95580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7478
                dc.w $9500 ! ((grp_95600 / 2) & $00FF)
                dc.w $9600 ! (((grp_95600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5758
                dc.w $9500 ! ((grp_A1180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E88
                dc.w $9500 ! ((grp_191200 / 2) & $00FF)
                dc.w $9600 ! (((grp_191200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7559
                dc.w $9500 ! ((grp_C5C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D62
                dc.w $9500 ! ((grp_C5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7570
                dc.w $9500 ! ((grp_F85A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F85A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F85A0 / 2) >> 16)
                dc.w 1
