byte_2E1384:    dc.b   0, $E,$72,$5A,$8E,$8E,$79,$4C,$76,$37
                                        ; DATA XREF: ROM:off_1938   o
                dc.w sprite_24_16
                dc.w $8D52
                dc.w $9500 ! ((grp_15BBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5346
                dc.w $9500 ! ((grp_7AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6D5D
                dc.w $9500 ! ((grp_7AE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7544
                dc.w $9500 ! ((grp_7AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9532
                dc.w $9500 ! ((grp_7AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $652C
                dc.w $9500 ! ((grp_98B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $853C
                dc.w $9500 ! ((grp_A5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6535
                dc.w $9500 ! ((grp_195B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_195B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195B20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6D35
                dc.w $9500 ! ((grp_1958E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1958E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1958E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $753C
                dc.w $9500 ! ((grp_CD5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D54
                dc.w $9500 ! ((grp_B5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D34
                dc.w $9500 ! ((grp_B5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6563
                dc.w $9500 ! ((grp_E7AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D34
                dc.w $9500 ! ((grp_E7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A62
                dc.w $9500 ! ((grp_E5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5860 / 2) >> 16)
                dc.w 1
