byte_2D8536:    dc.b   0,  7,$75,$5F,$8D,$7A,$80,$6E,$86,$62
                                        ; DATA XREF: ROM:off_1394   o
                dc.w sprite_32_24
                dc.w $7161
                dc.w $9500 ! ((grp_1249C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1249C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1249C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7E81
                dc.w $9500 ! ((grp_79680 / 2) & $00FF)
                dc.w $9600 ! (((grp_79680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E59
                dc.w $9500 ! ((grp_185500 / 2) & $00FF)
                dc.w $9600 ! (((grp_185500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7951
                dc.w $9500 ! ((grp_CC840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $695D
                dc.w $9500 ! ((grp_B4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C79
                dc.w $9500 ! ((grp_E6CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $916D
                dc.w $9500 ! ((grp_E6D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9157
                dc.w $9500 ! ((grp_E6D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6D20 / 2) >> 16)
                dc.w 1
