byte_2DCC8A:    dc.b   0, $B,$6F,$55,$8E,$8F,$7E,$6E,$83,$59
                                        ; DATA XREF: ROM:off_166C   o
                dc.w sprite_24_24
                dc.w $7950
                dc.w $9500 ! ((grp_1482A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1482A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1482A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $614D
                dc.w $9500 ! ((grp_85200 / 2) & $00FF)
                dc.w $9600 ! (((grp_85200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8572
                dc.w $9500 ! ((grp_85280 / 2) & $00FF)
                dc.w $9600 ! (((grp_85280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7768
                dc.w $9500 ! ((grp_A8480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7155
                dc.w $9500 ! ((grp_199DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199DE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7F68
                dc.w $9500 ! ((grp_199E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_199E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $914F
                dc.w $9500 ! ((grp_D5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F7E
                dc.w $9500 ! ((grp_BBB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $695D
                dc.w $9500 ! ((grp_ED900 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7788
                dc.w $9500 ! ((grp_ED920 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7848
                dc.w $9500 ! ((grp_ED940 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9157
                dc.w $9500 ! ((grp_ED960 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED960 / 2) >> 16)
                dc.w 1
