byte_2EFEB4:    dc.b   0,  8,$44,$2C,$BC,$83,$80,$85,$81,$85
                                        ; DATA XREF: ROM:off_25A8   o
                dc.w sprite_32_24
                dc.w $7974
                dc.w $9500 ! ((grp_133840 / 2) & $00FF)
                dc.w $9600 ! (((grp_133840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_133840 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $416C
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $996C
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $616C
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $858C
                dc.w $9500 ! ((grp_8B280 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B280 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $796C
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $716C
                dc.w $9500 ! ((grp_19D380 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $B96C
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C9C
                dc.w $9500 ! ((grp_F1520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1520 / 2) >> 16)
                dc.w 1
