byte_2D049C:    dc.b   0,  3,$76,$72,$8C,$87,$81,$7C,$82,$7C
                                        ; DATA XREF: ROM:off_D28   o
                dc.w sprite_16_24
                dc.w $7470
                dc.w $9500 ! ((grp_170C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_170C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8480
                dc.w $9500 ! ((grp_C8C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A88
                dc.w $9500 ! ((grp_E33C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E33C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E33C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8478
                dc.w $9500 ! ((grp_E33E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E33E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E33E0 / 2) >> 16)
                dc.w 1
