byte_2E17E4:    dc.b   0,  7,$71,$74,$95,$8D,$81,$80,$8C,$88
                                        ; DATA XREF: ROM:off_1960   o
                dc.w sprite_24_24
                dc.w $8174
                dc.w $9500 ! ((grp_1469E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1469E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1469E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7173
                dc.w $9500 ! ((grp_177700 / 2) & $00FF)
                dc.w $9600 ! (((grp_177700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177700 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $696F
                dc.w $9500 ! ((grp_B9C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6173
                dc.w $9500 ! ((grp_EBE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBE80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6983
                dc.w $9500 ! ((grp_EBEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBEA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718B
                dc.w $9500 ! ((grp_EBEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBEC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $888C
                dc.w $9500 ! ((grp_EBEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBEE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9975
                dc.w $9500 ! ((grp_EBF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBF00 / 2) >> 16)
                dc.w 1
