byte_2CE0FC:    dc.b   0,  1,$88,$7F,$A0,$8E,$94,$86,$95,$86
                                        ; DATA XREF: ROM:off_9F8   o
                dc.w sprite_32_16
                dc.w $8681
                dc.w $9500 ! ((grp_46600 / 2) & $00FF)
                dc.w $9600 ! (((grp_46600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $9B79
                dc.w $9500 ! ((grp_E1FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1FC0 / 2) >> 16)
                dc.w 1
