byte_2F41A8:    dc.b   0,  1,$7B,$7A,$86,$87,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28E8   o
                dc.w sprite_16_16
                dc.w $7978
                dc.w $9500 ! ((grp_8DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8DA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7B88
                dc.w $9500 ! ((grp_F35A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F35A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F35A0 / 2) >> 16)
                dc.w 1
