byte_2F1F10:    dc.b   0, $A,$75,$6F,$96,$8F,$93,$73,$94,$73
                                        ; DATA XREF: ROM:off_26D8   o
                dc.w sprite_32_32
                dc.w $8A5D
                dc.w $9500 ! ((grp_36800 / 2) & $00FF)
                dc.w $9600 ! (((grp_36800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $737B
                dc.w $9500 ! ((grp_14E240 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E240 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7373
                dc.w $9500 ! ((grp_DAAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A6B
                dc.w $9500 ! ((grp_DAA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B7D
                dc.w $9500 ! ((grp_DAA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9B55
                dc.w $9500 ! ((grp_DA900 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AA63
                dc.w $9500 ! ((grp_DA940 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7593
                dc.w $9500 ! ((grp_F1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8393
                dc.w $9500 ! ((grp_F1CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8373
                dc.w $9500 ! ((grp_F1C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B15B
                dc.w $9500 ! ((grp_F1C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1C00 / 2) >> 16)
                dc.w 1
