byte_2FD886:    dc.b   0,  5,$5F,$3D,$8F,$8D,$7F,$65,$80,$65
                                        ; DATA XREF: ROM:off_3314   o
                dc.w sprite_16_32
                dc.w $8268
                dc.w $9500 ! ((grp_70E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7A58
                dc.w $9500 ! ((grp_95380 / 2) & $00FF)
                dc.w $9600 ! (((grp_95380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95380 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7388
                dc.w $9500 ! ((grp_A0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6E3B
                dc.w $9500 ! ((grp_1A0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0500 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7351
                dc.w $9500 ! ((grp_C5B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A60
                dc.w $9500 ! ((grp_F84A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F84A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F84A0 / 2) >> 16)
                dc.w 1
