byte_2FE6EE:    dc.b   0,  1,$74,$77,$8A,$89,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_3414   o
                dc.w sprite_24_24
                dc.w $7775
                dc.w $9500 ! ((grp_1552C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1552C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1552C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $6F77
                dc.w $9500 ! ((grp_C6240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6240 / 2) >> 16)
                dc.w 2
