byte_2D3AD6:    dc.b   0,  2,$76,$61,$88,$84,$7D,$72,$7E,$72
                                        ; DATA XREF: ROM:off_105C   o
                dc.w sprite_24_16
                dc.w $715F
                dc.w $9500 ! ((grp_158F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_158F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B6F
                dc.w $9500 ! ((grp_171C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_171C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $736F
                dc.w $9500 ! ((grp_B2A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2A80 / 2) >> 16)
                dc.w 2
