byte_2F931C:    dc.b   0,  5,$65,$73,$90,$92,$7A,$82,$7B,$82
                                        ; DATA XREF: ROM:off_2D28   o
                dc.w sprite_16_24
                dc.w $7376
                dc.w $9500 ! ((grp_1801C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1801C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1801C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $637E
                dc.w $9500 ! ((grp_91000 / 2) & $00FF)
                dc.w $9600 ! (((grp_91000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8371
                dc.w $9500 ! ((grp_AE680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B8E
                dc.w $9500 ! ((grp_18FE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FE20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B75
                dc.w $9500 ! ((grp_C3FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B6E
                dc.w $9500 ! ((grp_F66A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F66A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F66A0 / 2) >> 16)
                dc.w 1
