byte_2CBFDC:    dc.b   0,  5,$67,$80,$8B,$89,$7C,$7F,$7D,$7F
                                        ; DATA XREF: ROM:off_6C0   o
                dc.w sprite_24_8
                dc.w $757C
                dc.w $9500 ! ((grp_182EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_182EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E84
                dc.w $9500 ! ((grp_C68C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C68C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C68C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D84
                dc.w $9500 ! ((grp_E1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $657C
                dc.w $9500 ! ((grp_E10C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E10C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E10C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D77
                dc.w $9500 ! ((grp_E1120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $957C
                dc.w $9500 ! ((grp_E10E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E10E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E10E0 / 2) >> 16)
                dc.w 1
