byte_2FE328:    dc.b   0,  2,$78,$76,$8A,$86,$82,$7A,$83,$7A
                                        ; DATA XREF: ROM:off_33C0   o
                dc.w sprite_24_24
                dc.w $7674
                dc.w $9500 ! ((grp_154F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_154F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154F60 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $786C
                dc.w $9500 ! ((grp_F8A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E76
                dc.w $9500 ! ((grp_F8A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8A00 / 2) >> 16)
                dc.w 1
