byte_2CE1D6:    dc.b   0,  2,$94,$78,$A6,$89,$9D,$80,$9E,$80
                                        ; DATA XREF: ROM:off_A0C   o
                dc.w sprite_8_8
                dc.w $9286
                dc.w $9500 ! ((grp_E2040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9C76
                dc.w $9500 ! ((grp_E2060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A384
                dc.w $9500 ! ((grp_E2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2080 / 2) >> 16)
                dc.w 1
