byte_2D2F4A:    dc.b   0,  6,$6D,$69,$9A,$8C,$82,$7A,$83,$7A
                                        ; DATA XREF: ROM:off_F44   o
                dc.w sprite_32_32
                dc.w $786D
                dc.w $9500 ! ((grp_17000 / 2) & $00FF)
                dc.w $9600 ! (((grp_17000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $8565
                dc.w $9500 ! ((grp_1849C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1849C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1849C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7071
                dc.w $9500 ! ((grp_193E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_193E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6881
                dc.w $9500 ! ((grp_E4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $798D
                dc.w $9500 ! ((grp_E4DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $865D
                dc.w $9500 ! ((grp_E4DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9882
                dc.w $9500 ! ((grp_E4DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4DE0 / 2) >> 16)
                dc.w 1
