byte_2DC29C:    dc.b   0,  6,$70,$5B,$9E,$90,$83,$62,$84,$62
                                        ; DATA XREF: ROM:off_1608   o
                dc.w sprite_24_24
                dc.w $885A
                dc.w $9500 ! ((grp_149140 / 2) & $00FF)
                dc.w $9600 ! (((grp_149140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149140 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $705C
                dc.w $9500 ! ((grp_1630C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1630C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1630C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $605C
                dc.w $9500 ! ((grp_D68C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D68C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D68C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6D55
                dc.w $9500 ! ((grp_D6900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8454
                dc.w $9500 ! ((grp_D6940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A05E
                dc.w $9500 ! ((grp_BD280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6064
                dc.w $9500 ! ((grp_EE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE800 / 2) >> 16)
                dc.w 1
