byte_2F17E2:    dc.b   0,  3,$71,$68,$8F,$81,$80,$74,$81,$74
                                        ; DATA XREF: ROM:off_267C   o
                dc.w sprite_32_16
                dc.w $7766
                dc.w $9500 ! ((grp_55200 / 2) & $00FF)
                dc.w $9600 ! (((grp_55200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7B76
                dc.w $9500 ! ((grp_8CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6F6C
                dc.w $9500 ! ((grp_F2940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7378
                dc.w $9500 ! ((grp_F2960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2960 / 2) >> 16)
                dc.w 1
