byte_2D51CA:    dc.b   0,  3,$6F,$6A,$8E,$8F,$7F,$7C,$7D,$71
                                        ; DATA XREF: ROM:off_116C   o
                dc.w sprite_24_32
                dc.w $6D66
                dc.w $9500 ! ((grp_103E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_103E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D86
                dc.w $9500 ! ((grp_4B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8D8C
                dc.w $9500 ! ((grp_CF400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6570
                dc.w $9500 ! ((grp_B6CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6CC0 / 2) >> 16)
                dc.w 2
