byte_2E757C:    dc.b   0,  4,$6F,$71,$8E,$8F,$7C,$7F,$81,$7D
                                        ; DATA XREF: ROM:off_1CE0   o
                dc.w sprite_32_32
                dc.w $7170
                dc.w $9500 ! ((grp_24000 / 2) & $00FF)
                dc.w $9600 ! (((grp_24000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24000 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_16
                dc.w $6976
                dc.w $9500 ! ((grp_BB180 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $617A
                dc.w $9500 ! ((grp_ECCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECCE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9170
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $918E
                dc.w $9500 ! ((grp_ECD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECD00 / 2) >> 16)
                dc.w 1
