byte_2F6506:    dc.b   0,$14,$5B,$59,$7D,$87,$6F,$7A,$70,$7A
                                        ; DATA XREF: ROM:off_2B4C   o
                dc.w sprite_32_32
                dc.w $585D
                dc.w $9500 ! ((grp_3DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $587D
                dc.w $9500 ! ((grp_56400 / 2) & $00FF)
                dc.w $9600 ! (((grp_56400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $786B
                dc.w $9500 ! ((grp_6E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4075
                dc.w $9500 ! ((grp_169000 / 2) & $00FF)
                dc.w $9600 ! (((grp_169000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $3065
                dc.w $9500 ! ((grp_17F080 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $344D
                dc.w $9500 ! ((grp_8F500 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $4C39
                dc.w $9500 ! ((grp_8F580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $562D
                dc.w $9500 ! ((grp_8F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $662D
                dc.w $9500 ! ((grp_18EFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EFE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4058
                dc.w $9500 ! ((grp_C2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E55
                dc.w $9500 ! ((grp_C2A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $286B
                dc.w $9500 ! ((grp_F5060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $444A
                dc.w $9500 ! ((grp_F5080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $443C
                dc.w $9500 ! ((grp_F50A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F50A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F50A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4860
                dc.w $9500 ! ((grp_F50C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F50C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F50C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5069
                dc.w $9500 ! ((grp_F4B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E55
                dc.w $9500 ! ((grp_F4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F55
                dc.w $9500 ! ((grp_F4AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F3B
                dc.w $9500 ! ((grp_F50E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F50E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F50E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8878
                dc.w $9500 ! ((grp_F4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D39
                dc.w $9500 ! ((grp_F5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5100 / 2) >> 16)
                dc.w 1
