byte_2F7D9C:    dc.b   0,  1,$7B,$7C,$8B,$89,$83,$82,$84,$82
                                        ; DATA XREF: ROM:off_2BD0   o
                dc.w sprite_16_16
                dc.w $7A7C
                dc.w $9500 ! ((grp_90100 / 2) & $00FF)
                dc.w $9600 ! (((grp_90100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8A84
                dc.w $9500 ! ((grp_F5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5860 / 2) >> 16)
                dc.w 1
