byte_2E8F84:    dc.b   0,  4,$79,$62,$85,$8E,$7B,$77,$82,$68
                                        ; DATA XREF: ROM:off_1DF8   o
                dc.w sprite_16_16
                dc.w $6F81
                dc.w $9500 ! ((grp_7F980 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7E6E
                dc.w $9500 ! ((grp_A6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $765E
                dc.w $9500 ! ((grp_D1340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E66
                dc.w $9500 ! ((grp_EA940 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8187
                dc.w $9500 ! ((grp_EA960 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA960 / 2) >> 16)
                dc.w 1
