byte_2D20C6:    dc.b   0,  3,$6D,$62,$92,$9F,$80,$80,$81,$80
                                        ; DATA XREF: ROM:off_E94   o
                dc.w sprite_24_32
                dc.w $7668
                dc.w $9500 ! ((grp_FD0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7688
                dc.w $9500 ! ((grp_140140 / 2) & $00FF)
                dc.w $9600 ! (((grp_140140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140140 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7660
                dc.w $9500 ! ((grp_C9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $76A0
                dc.w $9500 ! ((grp_E4100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4100 / 2) >> 16)
                dc.w 1
