byte_2D5290:    dc.b   0,  6,$6F,$4E,$8E,$8F,$7A,$6C,$6B,$53
                                        ; DATA XREF: ROM:off_1178   o
                dc.w sprite_24_32
                dc.w $6A4B
                dc.w $9500 ! ((grp_FE740 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $716B
                dc.w $9500 ! ((grp_5F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $624D
                dc.w $9500 ! ((grp_1946E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1946E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1946E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $836B
                dc.w $9500 ! ((grp_CB700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $865C
                dc.w $9500 ! ((grp_CB740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $824B
                dc.w $9500 ! ((grp_B3980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E87
                dc.w $9500 ! ((grp_E5FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5FA0 / 2) >> 16)
                dc.w 1
