byte_2F660C:    dc.b   0,$13,$59,$5B,$80,$87,$66,$7A,$67,$7A
                                        ; DATA XREF: ROM:off_2B50   o
                dc.w sprite_32_32
                dc.w $585D
                dc.w $9500 ! ((grp_3DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $587D
                dc.w $9500 ! ((grp_56400 / 2) & $00FF)
                dc.w $9600 ! (((grp_56400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $786B
                dc.w $9500 ! ((grp_6E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $286A
                dc.w $9500 ! ((grp_169540 / 2) & $00FF)
                dc.w $9600 ! (((grp_169540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169540 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $4075
                dc.w $9500 ! ((grp_169000 / 2) & $00FF)
                dc.w $9600 ! (((grp_169000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169000 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $3763
                dc.w $9500 ! ((grp_18F040 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F040 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $413D
                dc.w $9500 ! ((grp_18F0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F0A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $3057
                dc.w $9500 ! ((grp_DD100 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8937
                dc.w $9500 ! ((grp_DD140 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3C4F
                dc.w $9500 ! ((grp_F5120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $405B
                dc.w $9500 ! ((grp_F5140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4A45
                dc.w $9500 ! ((grp_F5160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5069
                dc.w $9500 ! ((grp_F4B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $542D
                dc.w $9500 ! ((grp_F5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E55
                dc.w $9500 ! ((grp_F4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $662C
                dc.w $9500 ! ((grp_F51A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F51A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F51A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F55
                dc.w $9500 ! ((grp_F4AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F3D
                dc.w $9500 ! ((grp_F51C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F51C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F51C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8878
                dc.w $9500 ! ((grp_F4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9448
                dc.w $9500 ! ((grp_F51E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F51E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F51E0 / 2) >> 16)
                dc.w 1
