byte_2EDCAE:    dc.b   0,  3,$73,$69,$9D,$95,$87,$7C,$88,$7C
                                        ; DATA XREF: ROM:off_2304   o
                dc.w sprite_32_32
                dc.w $7870
                dc.w $9500 ! ((grp_30A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_30A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $8268
                dc.w $9500 ! ((grp_18CBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CBE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7077
                dc.w $9500 ! ((grp_19C5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C5A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $987E
                dc.w $9500 ! ((grp_BEB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEB40 / 2) >> 16)
                dc.w 2
