byte_2E7CC0:    dc.b   0,  8,$71,$62,$89,$7F,$B1,$59,$AA,$54
                                        ; DATA XREF: ROM:off_1D28   o
                dc.w sprite_32_24
                dc.w $6768
                dc.w $9500 ! ((grp_129340 / 2) & $00FF)
                dc.w $9600 ! (((grp_129340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $9752
                dc.w $9500 ! ((grp_1456C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1456C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1456C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $AF50
                dc.w $9500 ! ((grp_7F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $875A
                dc.w $9500 ! ((grp_A6300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7760
                dc.w $9500 ! ((grp_D0FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F59
                dc.w $9500 ! ((grp_B8400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D80
                dc.w $9500 ! ((grp_EA5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA5C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AF60
                dc.w $9500 ! ((grp_E5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BF51
                dc.w $9500 ! ((grp_EA5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA5E0 / 2) >> 16)
                dc.w 1
