byte_2F0FF2:    dc.b   0, $B,$60,$47,$A8,$8D,$83,$69,$84,$69
                                        ; DATA XREF: ROM:off_2624   o
                dc.w sprite_32_32
                dc.w $5D69
                dc.w $9500 ! ((grp_37A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_37A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6549
                dc.w $9500 ! ((grp_37C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_37C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8550
                dc.w $9500 ! ((grp_37E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_37E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $A554
                dc.w $9500 ! ((grp_6BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $5E89
                dc.w $9500 ! ((grp_9EC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8570
                dc.w $9500 ! ((grp_9ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9ED00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6541
                dc.w $9500 ! ((grp_18DFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DFC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7D71
                dc.w $9500 ! ((grp_19D740 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D740 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8548
                dc.w $9500 ! ((grp_DB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5572
                dc.w $9500 ! ((grp_C0580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D69
                dc.w $9500 ! ((grp_F23A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F23A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F23A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9578
                dc.w $9500 ! ((grp_F23C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F23C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F23C0 / 2) >> 16)
                dc.w 1
