byte_2E903E:    dc.b   0,  2,$75,$80,$8B,$8E,$7F,$85,$83,$88
                                        ; DATA XREF: ROM:off_1E04   o
                dc.w sprite_24_16
                dc.w $7081
                dc.w $9500 ! ((grp_15F040 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F040 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7679
                dc.w $9500 ! ((grp_1885C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1885C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1885C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8880
                dc.w $9500 ! ((grp_B8800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8800 / 2) >> 16)
                dc.w 2
