byte_2E8B62:    dc.b   0,  4,$7C,$64,$87,$8D,$7F,$78,$88,$6A
                                        ; DATA XREF: ROM:off_1DB4   o
                dc.w sprite_16_16
                dc.w $7C62
                dc.w $9500 ! ((grp_7C380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7282
                dc.w $9500 ! ((grp_186B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_186B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $728A
                dc.w $9500 ! ((grp_CE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D7A
                dc.w $9500 ! ((grp_CE7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F72
                dc.w $9500 ! ((grp_E8920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8920 / 2) >> 16)
                dc.w 1
