byte_2D5A00:    dc.b   0,  7,$6E,$64,$8E,$8F,$7A,$71,$75,$68
                                        ; DATA XREF: ROM:off_11C8   o
                dc.w sprite_32_24
                dc.w $6F58
                dc.w $9500 ! ((grp_123AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_123AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6F70
                dc.w $9500 ! ((grp_141340 / 2) & $00FF)
                dc.w $9600 ! (((grp_141340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141340 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5F64
                dc.w $9500 ! ((grp_78800 / 2) & $00FF)
                dc.w $9600 ! (((grp_78800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CBC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A50
                dc.w $9500 ! ((grp_CBCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8780
                dc.w $9500 ! ((grp_B3B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6774
                dc.w $9500 ! ((grp_E6280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_E62A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E62A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E62A0 / 2) >> 16)
                dc.w 1
