byte_2DD178:    dc.b   0,  6,$74,$5D,$82,$84,$75,$6F,$76,$5E
                                        ; DATA XREF: ROM:off_1698   o
                dc.w sprite_24_32
                dc.w $6E59
                dc.w $9500 ! ((grp_101740 / 2) & $00FF)
                dc.w $9600 ! (((grp_101740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7479
                dc.w $9500 ! ((grp_7A480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7651
                dc.w $9500 ! ((grp_CCFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6659
                dc.w $9500 ! ((grp_B4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E5F
                dc.w $9500 ! ((grp_E74C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E74C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E74C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7489
                dc.w $9500 ! ((grp_E7480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8479
                dc.w $9500 ! ((grp_E74A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E74A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E74A0 / 2) >> 16)
                dc.w 1
