byte_2EEB0A:    dc.b   0,  8,$6E,$4E,$89,$8E,$7A,$6E,$7B,$6E
                                        ; DATA XREF: ROM:off_2404   o
                dc.w sprite_24_32
                dc.w $6071
                dc.w $9500 ! ((grp_112540 / 2) & $00FF)
                dc.w $9600 ! (((grp_112540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112540 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5249
                dc.w $9500 ! ((grp_132F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_132F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8877
                dc.w $9500 ! ((grp_14CCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14CCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14CCE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7861
                dc.w $9500 ! ((grp_6A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6A900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5861
                dc.w $9500 ! ((grp_1651C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1651C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1651C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7881
                dc.w $9500 ! ((grp_89F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7059
                dc.w $9500 ! ((grp_19D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $505D
                dc.w $9500 ! ((grp_F0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A087
                dc.w $9500 ! ((grp_F09A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F09A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F09A0 / 2) >> 16)
                dc.w 1
