byte_2DD256:    dc.b   0,  4,$77,$63,$91,$80,$82,$71,$86,$64
                                        ; DATA XREF: ROM:off_16A4   o
                dc.w sprite_32_24
                dc.w $7657
                dc.w $9500 ! ((grp_1252C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1252C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1252C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $786F
                dc.w $9500 ! ((grp_142AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_142AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142AE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $7067
                dc.w $9500 ! ((grp_195580 / 2) & $00FF)
                dc.w $9600 ! (((grp_195580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195580 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8087
                dc.w $9500 ! ((grp_CD080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9077
                dc.w $9500 ! ((grp_E7520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7520 / 2) >> 16)
                dc.w 1
