byte_2D3D36:    dc.b   0,  6,$6C,$5D,$8D,$8F,$79,$75,$7A,$75
                                        ; DATA XREF: ROM:off_107C   o
                dc.w sprite_32_24
                dc.w $6F78
                dc.w $9500 ! ((grp_122D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_122D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D60
                dc.w $9500 ! ((grp_48D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7058
                dc.w $9500 ! ((grp_CA9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D70
                dc.w $9500 ! ((grp_CAA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6780
                dc.w $9500 ! ((grp_B2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F82
                dc.w $9500 ! ((grp_E5140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6566
                dc.w $9500 ! ((grp_E5160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5160 / 2) >> 16)
                dc.w 1
