byte_2CDFC4:    dc.b   0,  5,$65,$55,$94,$7D,$7C,$69,$7D,$69
                                        ; DATA XREF: ROM:off_9E0   o
                dc.w sprite_24_32
                dc.w $7B50
                dc.w $9500 ! ((grp_FA6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6B5B
                dc.w $9500 ! ((grp_74300 / 2) & $00FF)
                dc.w $9600 ! (((grp_74300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74300 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6E78
                dc.w $9500 ! ((grp_97080 / 2) & $00FF)
                dc.w $9600 ! (((grp_97080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7C70
                dc.w $9500 ! ((grp_183940 / 2) & $00FF)
                dc.w $9600 ! (((grp_183940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $635E
                dc.w $9500 ! ((grp_E2440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9363
                dc.w $9500 ! ((grp_E2460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2460 / 2) >> 16)
                dc.w 1
