byte_2DC7AC:    dc.b   0,  6,$6F,$6A,$90,$8D,$7F,$75,$7F,$6F
                                        ; DATA XREF: ROM:00001638   o
                dc.w sprite_24_32
                dc.w $7568
                dc.w $9500 ! ((grp_104A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_104A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $835C
                dc.w $9500 ! ((grp_7DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D66
                dc.w $9500 ! ((grp_197080 / 2) & $00FF)
                dc.w $9600 ! (((grp_197080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197080 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_CFF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CFFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D74
                dc.w $9500 ! ((grp_E5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D6C
                dc.w $9500 ! ((grp_E9920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9920 / 2) >> 16)
                dc.w 1
