byte_2D9DB4:    dc.b   0,$12,$86,$67,$8F,$77,$7F,$6D,$7B,$60
                                        ; DATA XREF: ROM:off_1478   o
                dc.w sprite_16_32
                dc.w $7055
                dc.w $9500 ! ((grp_5FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5FF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7875
                dc.w $9500 ! ((grp_60000 / 2) & $00FF)
                dc.w $9600 ! (((grp_60000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60000 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $704D
                dc.w $9500 ! ((grp_98680 / 2) & $00FF)
                dc.w $9600 ! (((grp_98680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $688D
                dc.w $9500 ! ((grp_CC940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8885
                dc.w $9500 ! ((grp_CC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $888D
                dc.w $9500 ! ((grp_CAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6852
                dc.w $9500 ! ((grp_B4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8055
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8065
                dc.w $9500 ! ((grp_B4900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $885D
                dc.w $9500 ! ((grp_B4940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8875
                dc.w $9500 ! ((grp_B4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686E
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $707D
                dc.w $9500 ! ((grp_E58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7075
                dc.w $9500 ! ((grp_E7060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7085
                dc.w $9500 ! ((grp_E7080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8855
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $886D
                dc.w $9500 ! ((grp_E6E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9053
                dc.w $9500 ! ((grp_E5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A00 / 2) >> 16)
                dc.w 1
