byte_2EC736:    dc.b   0,  3,$70,$81,$87,$8E,$7B,$88,$7C,$88
                                        ; DATA XREF: ROM:off_2154   o
                dc.w sprite_16_16
                dc.w $7880
                dc.w $9500 ! ((grp_88880 / 2) & $00FF)
                dc.w $9600 ! (((grp_88880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7081
                dc.w $9500 ! ((grp_BE7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $688C
                dc.w $9500 ! ((grp_EFDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFDA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8888
                dc.w $9500 ! ((grp_EFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFDC0 / 2) >> 16)
                dc.w 1
