byte_2D3114:    dc.b   0,  7,$6D,$66,$9A,$8E,$83,$7A,$84,$7A
                                        ; DATA XREF: ROM:off_F58   o
                dc.w sprite_16_32
                dc.w $8964
                dc.w $9500 ! ((grp_5E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7966
                dc.w $9500 ! ((grp_172000 / 2) & $00FF)
                dc.w $9600 ! (((grp_172000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $696E
                dc.w $9500 ! ((grp_77600 / 2) & $00FF)
                dc.w $9600 ! (((grp_77600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B86
                dc.w $9500 ! ((grp_184A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_184A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $797E
                dc.w $9500 ! ((grp_CA540 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9970
                dc.w $9500 ! ((grp_B2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B8E
                dc.w $9500 ! ((grp_E4E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $717E
                dc.w $9500 ! ((grp_E4E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4E60 / 2) >> 16)
                dc.w 1
char_1:         dc.b   0,  0,$81,$83,$80,$85,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_F5C   o
                dc.w sprite_8_8
                dc.w $7B81
                dc.w $9500 ! ((grp_E4680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4680 / 2) >> 16)
                dc.w 1
