byte_2E081C:    dc.b   0,  4,$68,$4D,$94,$85,$7E,$69,$87,$54
                                        ; DATA XREF: ROM:off_18E0   o
                dc.w sprite_32_32
                dc.w $7768
                dc.w $9500 ! ((grp_22600 / 2) & $00FF)
                dc.w $9600 ! (((grp_22600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7258
                dc.w $9500 ! ((grp_4E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6768
                dc.w $9500 ! ((grp_64400 / 2) & $00FF)
                dc.w $9600 ! (((grp_64400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8048
                dc.w $9500 ! ((grp_81880 / 2) & $00FF)
                dc.w $9600 ! (((grp_81880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5F72
                dc.w $9500 ! ((grp_EBC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBC20 / 2) >> 16)
                dc.w 1
