byte_2EA1F0:    dc.b   0,  4,$62,$70,$92,$8C,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F18   o
                dc.w sprite_32_24
                dc.w $776E
                dc.w $9500 ! ((grp_12FDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12FDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12FDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6F77
                dc.w $9500 ! ((grp_19B280 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B280 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7786
                dc.w $9500 ! ((grp_D7140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $677E
                dc.w $9500 ! ((grp_BDCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F86
                dc.w $9500 ! ((grp_EEEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEEC0 / 2) >> 16)
                dc.w 1
