byte_2EC09E:    dc.b   0,  6,$69,$5A,$9B,$93,$82,$76,$83,$76
                                        ; DATA XREF: ROM:000020A4   o
                dc.w sprite_32_32
                dc.w $7460
                dc.w $9500 ! ((grp_2F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2F200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6C80
                dc.w $9500 ! ((grp_131440 / 2) & $00FF)
                dc.w $9600 ! (((grp_131440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_131440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8C80
                dc.w $9500 ! ((grp_87D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_87D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $946F
                dc.w $9500 ! ((grp_BE380 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6482
                dc.w $9500 ! ((grp_EF8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF8C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C6F
                dc.w $9500 ! ((grp_EF8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF8E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8258
                dc.w $9500 ! ((grp_EF900 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF900 / 2) >> 16)
                dc.w 1
