byte_2F81F6:    dc.b   0,  3,$71,$6A,$90,$A0,$80,$8E,$81,$8E
                                        ; DATA XREF: ROM:off_2C4C   o
                dc.w sprite_24_24
                dc.w $767F
                dc.w $9500 ! ((grp_151840 / 2) & $00FF)
                dc.w $9600 ! (((grp_151840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151840 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7A97
                dc.w $9500 ! ((grp_DDD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E7F
                dc.w $9500 ! ((grp_C3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E80
                dc.w $9500 ! ((grp_C35C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C35C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C35C0 / 2) >> 16)
                dc.w 2
