byte_2D61F0:    dc.b   0,  6,$6F,$5A,$8E,$8F,$7F,$71,$7E,$5B
                                        ; DATA XREF: ROM:off_1220   o
                dc.w sprite_32_32
                dc.w $7053
                dc.w $9500 ! ((grp_1EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1EC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $7B73
                dc.w $9500 ! ((grp_1768C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1768C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1768C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_D1940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $868B
                dc.w $9500 ! ((grp_D1980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6863
                dc.w $9500 ! ((grp_B8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $905D
                dc.w $9500 ! ((grp_B8BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7380
                dc.w $9500 ! ((grp_EAD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAD20 / 2) >> 16)
                dc.w 1
