byte_2EC770:    dc.b   0,  2,$77,$7C,$90,$8E,$7F,$84,$80,$84
                                        ; DATA XREF: ROM:off_2158   o
                dc.w sprite_24_16
                dc.w $7981
                dc.w $9500 ! ((grp_164200 / 2) & $00FF)
                dc.w $9600 ! (((grp_164200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6989
                dc.w $9500 ! ((grp_D8480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8479
                dc.w $9500 ! ((grp_D84C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D84C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D84C0 / 2) >> 16)
                dc.w 2
