byte_2FE816:    dc.b   0,  1,$79,$85,$86,$8F,$7F,$8A,$80,$8A
                                        ; DATA XREF: ROM:off_3434   o
                dc.w sprite_16_16
                dc.w $7983
                dc.w $9500 ! ((grp_95E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_95E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7186
                dc.w $9500 ! ((grp_F8D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8D20 / 2) >> 16)
                dc.w 1
