byte_2E932E:    dc.b   0,  2,$5F,$4E,$9F,$80,$7E,$53,$7F,$53
                                        ; DATA XREF: ROM:off_1E54   o
                dc.w sprite_32_8
                dc.w $5A4F
                dc.w $9500 ! ((grp_9C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7D51
                dc.w $9500 ! ((grp_18B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $984F
                dc.w $9500 ! ((grp_D6DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6DC0 / 2) >> 16)
                dc.w 2
