byte_2E1C78:    dc.b   0,  3,$56,$5C,$96,$7A,$76,$6B,$75,$6C
                                        ; DATA XREF: ROM:off_1998   o
                dc.w sprite_32_24
                dc.w $6C62
                dc.w $9500 ! ((grp_127FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_127FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $546F
                dc.w $9500 ! ((grp_7E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8956
                dc.w $9500 ! ((grp_7E280 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $646E
                dc.w $9500 ! ((grp_E9B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9B40 / 2) >> 16)
                dc.w 1
