byte_2E81F6:    dc.b   0,  9,$6F,$5B,$8E,$8F,$7F,$30,$7C,$3F
                                        ; DATA XREF: ROM:off_1D54   o
                dc.w sprite_32_32
                dc.w $6E60
                dc.w $9500 ! ((grp_1BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1BA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $7D48
                dc.w $9500 ! ((grp_174880 / 2) & $00FF)
                dc.w $9600 ! (((grp_174880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174880 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7580
                dc.w $9500 ! ((grp_186700 / 2) & $00FF)
                dc.w $9600 ! (((grp_186700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186700 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7B30
                dc.w $9500 ! ((grp_1962A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1962A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1962A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7D18
                dc.w $9500 ! ((grp_196300 / 2) & $00FF)
                dc.w $9600 ! (((grp_196300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196300 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CE000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A15
                dc.w $9500 ! ((grp_B6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6674
                dc.w $9500 ! ((grp_E8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7388
                dc.w $9500 ! ((grp_E8620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8340
                dc.w $9500 ! ((grp_E8640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8640 / 2) >> 16)
                dc.w 1
