byte_2E4A08:    dc.b   0,  6,$5E,$59,$84,$90,$39,$9F,$65,$73
                                        ; DATA XREF: ROM:off_1B60   o
                dc.w sprite_24_24
                dc.w $6F73
                dc.w $9500 ! ((grp_147F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_147F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147F40 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $5F57
                dc.w $9500 ! ((grp_65800 / 2) & $00FF)
                dc.w $9600 ! (((grp_65800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $5F77
                dc.w $9500 ! ((grp_D5240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $778B
                dc.w $9500 ! ((grp_D5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5767
                dc.w $9500 ! ((grp_BB940 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $677F
                dc.w $9500 ! ((grp_ED6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED6E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F5E
                dc.w $9500 ! ((grp_ED700 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED700 / 2) >> 16)
                dc.w 1
