byte_2F728E:    dc.b   0, $A,$7B,$4D,$A4,$83,$7E,$7E,$7F,$7E
                                        ; DATA XREF: ROM:off_2B84   o
                dc.w sprite_24_32
                dc.w $764B
                dc.w $9500 ! ((grp_117640 / 2) & $00FF)
                dc.w $9600 ! (((grp_117640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8E4B
                dc.w $9500 ! ((grp_6E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $866B
                dc.w $9500 ! ((grp_17EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EC00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9E51
                dc.w $9500 ! ((grp_17ECC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17ECC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17ECC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7776
                dc.w $9500 ! ((grp_8F080 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AC45
                dc.w $9500 ! ((grp_8F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B535
                dc.w $9500 ! ((grp_8F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $966B
                dc.w $9500 ! ((grp_C2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F7A
                dc.w $9500 ! ((grp_F4CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F43
                dc.w $9500 ! ((grp_F4CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4CE0 / 2) >> 16)
                dc.w 1
