byte_2CF52C:    dc.b   0, $C,$69,$65,$A0,$98,$8B,$78,$8C,$78
                                        ; DATA XREF: ROM:off_B68   o
                dc.w sprite_24_32
                dc.w $9062
                dc.w $9500 ! ((grp_FB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $707F
                dc.w $9500 ! ((grp_13E760 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E760 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $706F
                dc.w $9500 ! ((grp_156F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_156F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $785F
                dc.w $9500 ! ((grp_157000 / 2) & $00FF)
                dc.w $9600 ! (((grp_157000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6857
                dc.w $9500 ! ((grp_74C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_74C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6877
                dc.w $9500 ! ((grp_A3500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $886F
                dc.w $9500 ! ((grp_A3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $A85E
                dc.w $9500 ! ((grp_192A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_192A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7097
                dc.w $9500 ! ((grp_C86C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C86C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C86C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7857
                dc.w $9500 ! ((grp_C8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $607D
                dc.w $9500 ! ((grp_B15C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B15C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B15C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B067
                dc.w $9500 ! ((grp_B1600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A05A
                dc.w $9500 ! ((grp_E2C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2C20 / 2) >> 16)
                dc.w 1
