byte_2D7978:    dc.b   0,  5,$75,$5D,$8B,$A2,$86,$80,$81,$6B
                                        ; DATA XREF: ROM:off_1310   o
                dc.w sprite_32_24
                dc.w $6F6E
                dc.w $9500 ! ((grp_124240 / 2) & $00FF)
                dc.w $9600 ! (((grp_124240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7786
                dc.w $9500 ! ((grp_5F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $8F6E
                dc.w $9500 ! ((grp_194C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_194C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $976D
                dc.w $9500 ! ((grp_B4040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D66
                dc.w $9500 ! ((grp_E6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F5E
                dc.w $9500 ! ((grp_E9320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9320 / 2) >> 16)
                dc.w 1
