byte_2E0E6C:    dc.b   0, $C,$72,$5A,$8E,$8E,$83,$40,$77,$2A
                                        ; DATA XREF: ROM:off_1918   o
                dc.w sprite_24_16
                dc.w $6938
                dc.w $9500 ! ((grp_15BEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8946
                dc.w $9500 ! ((grp_15BD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BD40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8130
                dc.w $9500 ! ((grp_A5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6930
                dc.w $9500 ! ((grp_1860A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1860A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1860A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7948
                dc.w $9500 ! ((grp_195AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6128
                dc.w $9500 ! ((grp_CD680 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6958
                dc.w $9500 ! ((grp_CD440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E20
                dc.w $9500 ! ((grp_B5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8930
                dc.w $9500 ! ((grp_B53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B53C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $613D
                dc.w $9500 ! ((grp_E7B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7860
                dc.w $9500 ! ((grp_E5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9130
                dc.w $9500 ! ((grp_E7A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B56
                dc.w $9500 ! ((grp_E5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5860 / 2) >> 16)
                dc.w 1
