byte_2D72B8:    dc.b   0,  5,$77,$5F,$88,$79,$82,$6C,$7F,$59
                                        ; DATA XREF: ROM:off_12C8   o
                dc.w sprite_24_32
                dc.w $795B
                dc.w $9500 ! ((grp_10B940 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $797B
                dc.w $9500 ! ((grp_178900 / 2) & $00FF)
                dc.w $9600 ! (((grp_178900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $915B
                dc.w $9500 ! ((grp_84080 / 2) & $00FF)
                dc.w $9600 ! (((grp_84080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7853
                dc.w $9500 ! ((grp_D47C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D47C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D47C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7161
                dc.w $9500 ! ((grp_BB300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6963
                dc.w $9500 ! ((grp_ECE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECE60 / 2) >> 16)
                dc.w 1
