byte_2CF0CC:    dc.b   0, $B,$68,$5E,$97,$93,$80,$76,$81,$76
                                        ; DATA XREF: ROM:off_B40   o
                dc.w sprite_32_24
                dc.w $6A56
                dc.w $9500 ! ((grp_1204C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1204C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1204C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $727E
                dc.w $9500 ! ((grp_11FBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $627E
                dc.w $9500 ! ((grp_74780 / 2) & $00FF)
                dc.w $9600 ! (((grp_74780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $927F
                dc.w $9500 ! ((grp_74800 / 2) & $00FF)
                dc.w $9600 ! (((grp_74800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $826E
                dc.w $9500 ! ((grp_97200 / 2) & $00FF)
                dc.w $9600 ! (((grp_97200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A6E
                dc.w $9500 ! ((grp_183B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_183B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183B20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7A76
                dc.w $9500 ! ((grp_183B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_183B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6276
                dc.w $9500 ! ((grp_C83C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C83C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C83C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A66
                dc.w $9500 ! ((grp_C84C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C84C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C84C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7276
                dc.w $9500 ! ((grp_E2AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E96
                dc.w $9500 ! ((grp_E2960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A5E
                dc.w $9500 ! ((grp_E2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2980 / 2) >> 16)
                dc.w 1
