byte_2FBE20:    dc.b   0,  4,$6F,$6F,$93,$93,$81,$81,$82,$81
                                        ; DATA XREF: ROM:off_3030   o
                dc.w sprite_32_32
                dc.w $726D
                dc.w $9500 ! ((grp_44600 / 2) & $00FF)
                dc.w $9600 ! (((grp_44600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $728D
                dc.w $9500 ! ((grp_A0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A71
                dc.w $9500 ! ((grp_19FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FF00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A95
                dc.w $9500 ! ((grp_DF3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $928A
                dc.w $9500 ! ((grp_F7AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7AA0 / 2) >> 16)
                dc.w 1
