byte_2D2A40:    dc.b   0,  6,$6A,$73,$96,$8C,$7B,$7E,$7C,$7E
                                        ; DATA XREF: ROM:off_F08   o
                dc.w sprite_32_24
                dc.w $7576
                dc.w $9500 ! ((grp_1228C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1228C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1228C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7D6E
                dc.w $9500 ! ((grp_184840 / 2) & $00FF)
                dc.w $9600 ! (((grp_184840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184840 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6584
                dc.w $9500 ! ((grp_CA340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5D7C
                dc.w $9500 ! ((grp_B2B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7C
                dc.w $9500 ! ((grp_E4A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4A60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $908E
                dc.w $9500 ! ((grp_E4A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $957E
                dc.w $9500 ! ((grp_E4AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4AA0 / 2) >> 16)
                dc.w 1
