byte_2D8674:    dc.b   0,  8,$6E,$5F,$96,$85,$81,$7A,$85,$6E
                                        ; DATA XREF: ROM:off_13A0   o
                dc.w sprite_32_32
                dc.w $6865
                dc.w $9500 ! ((grp_19600 / 2) & $00FF)
                dc.w $9600 ! (((grp_19600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $728D
                dc.w $9500 ! ((grp_79700 / 2) & $00FF)
                dc.w $9600 ! (((grp_79700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D85
                dc.w $9500 ! ((grp_CC8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $606C
                dc.w $9500 ! ((grp_B4640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8872
                dc.w $9500 ! ((grp_B45C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B45C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B45C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9072
                dc.w $9500 ! ((grp_B4600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $976E
                dc.w $9500 ! ((grp_B4680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E5D
                dc.w $9500 ! ((grp_E6DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8868
                dc.w $9500 ! ((grp_E6D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6D80 / 2) >> 16)
                dc.w 1
