byte_2CE6D6:    dc.b   0,  1,$78,$79,$86,$88,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_AD4   o
                dc.w sprite_16_24
                dc.w $7677
                dc.w $9500 ! ((grp_16F840 / 2) & $00FF)
                dc.w $9600 ! (((grp_16F840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16F840 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8679
                dc.w $9500 ! ((grp_B0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0500 / 2) >> 16)
                dc.w 2
