byte_2D13A6:    dc.b   0,  7,$65,$60,$9E,$8E,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_E04   o
                dc.w sprite_32_32
                dc.w $8567
                dc.w $9500 ! ((grp_15400 / 2) & $00FF)
                dc.w $9600 ! (((grp_15400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $6D62
                dc.w $9500 ! ((grp_13F2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F2A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $5D67
                dc.w $9500 ! ((grp_5D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D600 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6D7A
                dc.w $9500 ! ((grp_158080 / 2) & $00FF)
                dc.w $9600 ! (((grp_158080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6F8A
                dc.w $9500 ! ((grp_C9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $845F
                dc.w $9500 ! ((grp_C9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9087
                dc.w $9500 ! ((grp_C9340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $655F
                dc.w $9500 ! ((grp_E3980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3980 / 2) >> 16)
                dc.w 1
