byte_2EF330:    dc.b   0,  4,$65,$68,$95,$9E,$7D,$80,$7E,$80
                                        ; DATA XREF: ROM:off_24C8   o
                dc.w sprite_32_8
                dc.w $637E
                dc.w $9500 ! ((grp_9E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $837F
                dc.w $9500 ! ((grp_18D6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D6C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6376
                dc.w $9500 ! ((grp_D9A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7977
                dc.w $9500 ! ((grp_D9A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9277
                dc.w $9500 ! ((grp_F0E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0E20 / 2) >> 16)
                dc.w 1
