byte_2D22A4:    dc.b   0,  3,$74,$A8,$8D,$B6,$8A,$AE,$8B,$AE
                                        ; DATA XREF: ROM:off_EB0   o
                dc.w sprite_16_16
                dc.w $86A6
                dc.w $9500 ! ((grp_76A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $76A6
                dc.w $9500 ! ((grp_C9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6EA7
                dc.w $9500 ! ((grp_B2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8BB6
                dc.w $9500 ! ((grp_E41C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E41C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E41C0 / 2) >> 16)
                dc.w 1
