byte_2FB2C0:    dc.b   0,  1,$6B,$74,$8B,$88,$7B,$7E,$7C,$7E
                                        ; DATA XREF: ROM:off_2F50   o
                dc.w sprite_32_24
                dc.w $6972
                dc.w $9500 ! ((grp_13AA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_13AA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13AA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $8982
                dc.w $9500 ! ((grp_F7840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7840 / 2) >> 16)
                dc.w 1
