byte_2F405A:    dc.b   0,  3,$73,$6F,$8F,$92,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28CC   o
                dc.w sprite_32_16
                dc.w $7275
                dc.w $9500 ! ((grp_55C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7685
                dc.w $9500 ! ((grp_8D780 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F6D
                dc.w $9500 ! ((grp_DC0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8685
                dc.w $9500 ! ((grp_F3500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3500 / 2) >> 16)
                dc.w 1
