byte_2F0F70:    dc.b   0,  9,$67,$48,$A6,$89,$89,$69,$8A,$69
                                        ; DATA XREF: ROM:off_2620   o
                dc.w sprite_32_32
                dc.w $724A
                dc.w $9500 ! ((grp_37800 / 2) & $00FF)
                dc.w $9600 ! (((grp_37800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $736A
                dc.w $9500 ! ((grp_37600 / 2) & $00FF)
                dc.w $9600 ! (((grp_37600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9251
                dc.w $9500 ! ((grp_113BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_113BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $624A
                dc.w $9500 ! ((grp_6BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $9741
                dc.w $9500 ! ((grp_166E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_166E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_9EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6371
                dc.w $9500 ! ((grp_AC280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6B6A
                dc.w $9500 ! ((grp_AC300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9371
                dc.w $9500 ! ((grp_DB000 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $937E
                dc.w $9500 ! ((grp_F2380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2380 / 2) >> 16)
                dc.w 1
