byte_2D6078:    dc.b   0,  5,$6F,$69,$8E,$8F,$81,$79,$83,$6E
                                        ; DATA XREF: ROM:off_1210   o
                dc.w sprite_24_32
                dc.w $746B
                dc.w $9500 ! ((grp_106840 / 2) & $00FF)
                dc.w $9600 ! (((grp_106840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106840 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $8C73
                dc.w $9500 ! ((grp_A6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6C8B
                dc.w $9500 ! ((grp_D1780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C63
                dc.w $9500 ! ((grp_D17C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D17C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D17C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C72
                dc.w $9500 ! ((grp_B8A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $848B
                dc.w $9500 ! ((grp_EACA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EACA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EACA0 / 2) >> 16)
                dc.w 1
