byte_2E3496:    dc.b   0,  7,$70,$64,$80,$6D,$7E,$6F,$7B,$75
                                        ; DATA XREF: ROM:off_1AAC   o
                dc.w sprite_24_16
                dc.w $6F86
                dc.w $9500 ! ((grp_15E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7076
                dc.w $9500 ! ((grp_15E440 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6966
                dc.w $9500 ! ((grp_7E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7966
                dc.w $9500 ! ((grp_7E580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A4E
                dc.w $9500 ! ((grp_197260 / 2) & $00FF)
                dc.w $9600 ! (((grp_197260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197260 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $878B
                dc.w $9500 ! ((grp_D04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D04C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $724E
                dc.w $9500 ! ((grp_B7800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $896C
                dc.w $9500 ! ((grp_E9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C40 / 2) >> 16)
                dc.w 1
