byte_2E70BC:    dc.b   0,  6,$6F,$63,$8E,$8F,$78,$59,$7D,$65
                                        ; DATA XREF: ROM:off_1CB8   o
                dc.w sprite_32_32
                dc.w $6E66
                dc.w $9500 ! ((grp_23C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_23C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6E56
                dc.w $9500 ! ((grp_83D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8186
                dc.w $9500 ! ((grp_83D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7286
                dc.w $9500 ! ((grp_BB000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E6E
                dc.w $9500 ! ((grp_BB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_ECBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECBE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E5E
                dc.w $9500 ! ((grp_ECC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECC00 / 2) >> 16)
                dc.w 1
