byte_2EC5FA:    dc.b   0,  1,$75,$7D,$8E,$90,$81,$86,$82,$86
                                        ; DATA XREF: ROM:off_212C   o
                dc.w sprite_24_24
                dc.w $737B
                dc.w $9500 ! ((grp_14B9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14B9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14B9C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $8B7B
                dc.w $9500 ! ((grp_BE600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE600 / 2) >> 16)
                dc.w 2
