byte_2EB6A6:    dc.b   0,  3,$71,$55,$8F,$8D,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_203C   o
                dc.w sprite_32_32
                dc.w $686D
                dc.w $9500 ! ((grp_2B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_2B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2B400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $886D
                dc.w $9500 ! ((grp_67800 / 2) & $00FF)
                dc.w $9600 ! (((grp_67800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67800 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $688D
                dc.w $9500 ! ((grp_9CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $888D
                dc.w $9500 ! ((grp_D7BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7BC0 / 2) >> 16)
                dc.w 2
