byte_2E0222:    dc.b   0,  3,$67,$50,$8F,$8A,$7B,$6D,$72,$58
                                        ; DATA XREF: ROM:off_18A4   o
                dc.w sprite_32_32
                dc.w $655C
                dc.w $9500 ! ((grp_21200 / 2) & $00FF)
                dc.w $9600 ! (((grp_21200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $657C
                dc.w $9500 ! ((grp_4E300 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $856B
                dc.w $9500 ! ((grp_63700 / 2) & $00FF)
                dc.w $9600 ! (((grp_63700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $654C
                dc.w $9500 ! ((grp_15FE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FE80 / 2) >> 16)
                dc.w 6
