byte_2E9D70:    dc.b   0,  6,$67,$53,$9B,$75,$81,$64,$82,$64
                                        ; DATA XREF: ROM:off_1ED0   o
                dc.w sprite_24_32
                dc.w $7C59
                dc.w $9500 ! ((grp_10EAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10EAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10EAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $7451
                dc.w $9500 ! ((grp_A9800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C53
                dc.w $9500 ! ((grp_19AFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AFE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C51
                dc.w $9500 ! ((grp_D6F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6459
                dc.w $9500 ! ((grp_BD780 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C74
                dc.w $9500 ! ((grp_EECE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EECE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EECE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9560
                dc.w $9500 ! ((grp_EECC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EECC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EECC0 / 2) >> 16)
                dc.w 1
