byte_2D435C:    dc.b   0,  5,$65,$68,$92,$90,$73,$74,$74,$74
                                        ; DATA XREF: ROM:off_10C0   o
                dc.w sprite_32_24
                dc.w $746A
                dc.w $9500 ! ((grp_123040 / 2) & $00FF)
                dc.w $9600 ! (((grp_123040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6468
                dc.w $9500 ! ((grp_172300 / 2) & $00FF)
                dc.w $9600 ! (((grp_172300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172300 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $5471
                dc.w $9500 ! ((grp_B2F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C71
                dc.w $9500 ! ((grp_E53E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E53E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E53E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7462
                dc.w $9500 ! ((grp_E53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E53C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F7F
                dc.w $9500 ! ((grp_E5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5400 / 2) >> 16)
                dc.w 1
