byte_2DF940:    dc.b   0,  5,$5D,$5D,$90,$8E,$76,$75,$7A,$62
                                        ; DATA XREF: ROM:off_1838   o
                dc.w sprite_24_32
                dc.w $6C63
                dc.w $9500 ! ((grp_108940 / 2) & $00FF)
                dc.w $9600 ! (((grp_108940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6C83
                dc.w $9500 ! ((grp_15F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5C71
                dc.w $9500 ! ((grp_80E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $846B
                dc.w $9500 ! ((grp_A6B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $685B
                dc.w $9500 ! ((grp_188E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_188E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $848B
                dc.w $9500 ! ((grp_D28C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D28C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D28C0 / 2) >> 16)
                dc.w 2
