byte_2E9E70:    dc.b   0,  5,$8D,$6A,$9A,$77,$8F,$75,$90,$75
                                        ; DATA XREF: ROM:off_1EE0   o
                dc.w sprite_24_32
                dc.w $8C5D
                dc.w $9500 ! ((grp_10EDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10EDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10EDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $846F
                dc.w $9500 ! ((grp_19B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B100 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8C7D
                dc.w $9500 ! ((grp_D7000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $767F
                dc.w $9500 ! ((grp_BD8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C79
                dc.w $9500 ! ((grp_BD880 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A45F
                dc.w $9500 ! ((grp_EED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EED40 / 2) >> 16)
                dc.w 1
