byte_2E22E2:    dc.b   0,  2,$74,$64,$8C,$84,$82,$72,$78,$59
                                        ; DATA XREF: ROM:off_19FC   o
                dc.w sprite_32_32
                dc.w $7258
                dc.w $9500 ! ((grp_1B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1B200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $8080
                dc.w $9500 ! ((grp_7B280 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B280 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7478
                dc.w $9500 ! ((grp_98C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98C80 / 2) >> 16)
                dc.w 4
