byte_2D54A0:    dc.b   0,  6,$6F,$64,$8E,$8F,$82,$78,$7D,$69
                                        ; DATA XREF: ROM:off_1190   o
                dc.w sprite_24_32
                dc.w $7669
                dc.w $9500 ! ((grp_FEBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FEBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FEBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C61
                dc.w $9500 ! ((grp_185200 / 2) & $00FF)
                dc.w $9600 ! (((grp_185200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6E6B
                dc.w $9500 ! ((grp_1947A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1947A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1947A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CB840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB840 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CB880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E68
                dc.w $9500 ! ((grp_B3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9668
                dc.w $9500 ! ((grp_E6120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6120 / 2) >> 16)
                dc.w 1
