byte_2CDDAC:    dc.b   0,  2,$6D,$6C,$90,$8B,$7E,$7B,$7F,$7B
                                        ; DATA XREF: ROM:off_9C0   o
                dc.w sprite_32_32
                dc.w $6B6A
                dc.w $9500 ! ((grp_11800 / 2) & $00FF)
                dc.w $9600 ! (((grp_11800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11800 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8B6B
                dc.w $9500 ! ((grp_A1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7D8A
                dc.w $9500 ! ((grp_E2380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2380 / 2) >> 16)
                dc.w 1
