byte_2E177A:    dc.b   0,  7,$71,$58,$93,$8F,$88,$6D,$89,$6D
                                        ; DATA XREF: ROM:off_195C   o
                dc.w sprite_24_16
                dc.w $7669
                dc.w $9500 ! ((grp_162A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_162A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7751
                dc.w $9500 ! ((grp_179BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_179BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8752
                dc.w $9500 ! ((grp_179C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_179C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7879
                dc.w $9500 ! ((grp_85F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6F4C
                dc.w $9500 ! ((grp_19A620 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $974F
                dc.w $9500 ! ((grp_BC880 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7749
                dc.w $9500 ! ((grp_EE240 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE240 / 2) >> 16)
                dc.w 1
