byte_2DB632:    dc.b   0,  5,$6A,$54,$92,$91,$7E,$72,$7F,$72
                                        ; DATA XREF: ROM:off_155C   o
                dc.w sprite_24_32
                dc.w $7061
                dc.w $9500 ! ((grp_10CE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10CE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10CE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7181
                dc.w $9500 ! ((grp_162700 / 2) & $00FF)
                dc.w $9600 ! (((grp_162700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8865
                dc.w $9500 ! ((grp_179500 / 2) & $00FF)
                dc.w $9600 ! (((grp_179500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7751
                dc.w $9500 ! ((grp_85900 / 2) & $00FF)
                dc.w $9600 ! (((grp_85900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6865
                dc.w $9500 ! ((grp_19A1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A1A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $808E
                dc.w $9500 ! ((grp_D6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6000 / 2) >> 16)
                dc.w 2
