byte_2D9B06:    dc.b   0,  6,$86,$67,$8F,$77,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_1464   o
                dc.w sprite_32_8
                dc.w $7453
                dc.w $9500 ! ((grp_98700 / 2) & $00FF)
                dc.w $9600 ! (((grp_98700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6C54
                dc.w $9500 ! ((grp_A4E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8B5B
                dc.w $9500 ! ((grp_194F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_194F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8C79
                dc.w $9500 ! ((grp_194FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $806E
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9456
                dc.w $9500 ! ((grp_E6E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E80 / 2) >> 16)
                dc.w 1
