byte_2CF34A:    dc.b   0,  8,$69,$69,$96,$94,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_B54   o
                dc.w sprite_32_32
                dc.w $7672
                dc.w $9500 ! ((grp_13800 / 2) & $00FF)
                dc.w $9600 ! (((grp_13800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $765A
                dc.w $9500 ! ((grp_1207C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1207C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1207C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6672
                dc.w $9500 ! ((grp_5C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $665A
                dc.w $9500 ! ((grp_170200 / 2) & $00FF)
                dc.w $9600 ! (((grp_170200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170200 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9665
                dc.w $9500 ! ((grp_192940 / 2) & $00FF)
                dc.w $9600 ! (((grp_192940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192940 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7192
                dc.w $9500 ! ((grp_C8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $967D
                dc.w $9500 ! ((grp_B1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E71
                dc.w $9500 ! ((grp_B1540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E60
                dc.w $9500 ! ((grp_E2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2B80 / 2) >> 16)
                dc.w 1
