byte_2FD0B6:    dc.b   0,  1,$78,$75,$88,$87,$80,$7E,$81,$7E
                                        ; DATA XREF: ROM:off_3294   o
                dc.w sprite_16_16
                dc.w $7C73
                dc.w $9500 ! ((grp_94C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_94C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_94C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7683
                dc.w $9500 ! ((grp_DF9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF9C0 / 2) >> 16)
                dc.w 2
