byte_2FE01A:    dc.b   0,  6,$70,$51,$9B,$8D,$85,$6F,$86,$6F
                                        ; DATA XREF: ROM:off_3364   o
                dc.w sprite_16_24
                dc.w $6E60
                dc.w $9500 ! ((grp_182440 / 2) & $00FF)
                dc.w $9600 ! (((grp_182440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6E78
                dc.w $9500 ! ((grp_95900 / 2) & $00FF)
                dc.w $9600 ! (((grp_95900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95900 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6888
                dc.w $9500 ! ((grp_A1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7258
                dc.w $9500 ! ((grp_E0180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0180 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7950
                dc.w $9500 ! ((grp_E01C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E01C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E01C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $894F
                dc.w $9500 ! ((grp_E0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9254
                dc.w $9500 ! ((grp_E0240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0240 / 2) >> 16)
                dc.w 2
