byte_2EEA5A:    dc.b   0,  5,$6E,$4E,$89,$8E,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_23FC   o
                dc.w sprite_32_32
                dc.w $6170
                dc.w $9500 ! ((grp_32E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_32E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8171
                dc.w $9500 ! ((grp_6A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6A800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9180
                dc.w $9500 ! ((grp_89E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6C69
                dc.w $9500 ! ((grp_9E080 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5974
                dc.w $9500 ! ((grp_F0900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9178
                dc.w $9500 ! ((grp_F08E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F08E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F08E0 / 2) >> 16)
                dc.w 1
