byte_2D47C2:    dc.b   0,  6,$68,$5F,$91,$91,$83,$7B,$7E,$6C
                                        ; DATA XREF: ROM:off_10F4   o
                dc.w sprite_32_32
                dc.w $7075
                dc.w $9500 ! ((grp_18000 / 2) & $00FF)
                dc.w $9600 ! (((grp_18000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $5872
                dc.w $9500 ! ((grp_159C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_159C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7665
                dc.w $9500 ! ((grp_78000 / 2) & $00FF)
                dc.w $9600 ! (((grp_78000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9074
                dc.w $9500 ! ((grp_78080 / 2) & $00FF)
                dc.w $9600 ! (((grp_78080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9084
                dc.w $9500 ! ((grp_B3600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E5D
                dc.w $9500 ! ((grp_E5C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A075
                dc.w $9500 ! ((grp_E5C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5C60 / 2) >> 16)
                dc.w 1
