byte_2E9C86:    dc.b   0,  6,$68,$53,$A1,$78,$84,$65,$85,$65
                                        ; DATA XREF: ROM:off_1EC4   o
                dc.w sprite_32_24
                dc.w $7558
                dc.w $9500 ! ((grp_12F4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $655E
                dc.w $9500 ! ((grp_86C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_86C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6D70
                dc.w $9500 ! ((grp_18B620 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B620 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7C50
                dc.w $9500 ! ((grp_18B680 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B680 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7578
                dc.w $9500 ! ((grp_D6EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9558
                dc.w $9500 ! ((grp_BD740 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9C69
                dc.w $9500 ! ((grp_EEC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEC40 / 2) >> 16)
                dc.w 1
