byte_2DFA36:    dc.b   0,  8,$6D,$55,$91,$8E,$7F,$71,$80,$5C
                                        ; DATA XREF: ROM:off_1844   o
                dc.w sprite_24_24
                dc.w $7260
                dc.w $9500 ! ((grp_146200 / 2) & $00FF)
                dc.w $9600 ! (((grp_146200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146200 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7278
                dc.w $9500 ! ((grp_15F7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F7C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6F88
                dc.w $9500 ! ((grp_9A580 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A6A
                dc.w $9500 ! ((grp_198520 / 2) & $00FF)
                dc.w $9600 ! (((grp_198520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8A64
                dc.w $9500 ! ((grp_198580 / 2) & $00FF)
                dc.w $9600 ! (((grp_198580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198580 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7658
                dc.w $9500 ! ((grp_D2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E50
                dc.w $9500 ! ((grp_EB620 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8A
                dc.w $9500 ! ((grp_EB640 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $926D
                dc.w $9500 ! ((grp_EB660 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB660 / 2) >> 16)
                dc.w 1
