byte_2E735C:    dc.b   0, $A,$6F,$63,$8E,$8F,$C4,$77,$80,$55
                                        ; DATA XREF: ROM:off_1CD0   o
                dc.w sprite_24_32
                dc.w $7059
                dc.w $9500 ! ((grp_10AEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10AEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10AEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7952
                dc.w $9500 ! ((grp_9B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7080
                dc.w $9500 ! ((grp_189D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_189D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7878
                dc.w $9500 ! ((grp_189D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_189D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_D4080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_D40C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D40C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D40C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9162
                dc.w $9500 ! ((grp_D4100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8868
                dc.w $9500 ! ((grp_BAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F5A
                dc.w $9500 ! ((grp_ECB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $946A
                dc.w $9500 ! ((grp_ECBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECBA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F5F
                dc.w $9500 ! ((grp_ECBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECBC0 / 2) >> 16)
                dc.w 1
