byte_2CFFE0:    dc.b   0,  1,$7B,$71,$89,$82,$82,$79,$83,$79
                                        ; DATA XREF: ROM:off_CB0   o
                dc.w sprite_16_24
                dc.w $7D6F
                dc.w $9500 ! ((grp_170B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_170B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7574
                dc.w $9500 ! ((grp_B17C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B17C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B17C0 / 2) >> 16)
                dc.w 2
