byte_2EC304:    dc.b   0,  5,$6D,$66,$92,$91,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_20D0   o
                dc.w sprite_32_32
                dc.w $6B6C
                dc.w $9500 ! ((grp_30000 / 2) & $00FF)
                dc.w $9600 ! (((grp_30000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8B74
                dc.w $9500 ! ((grp_17B0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B0C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $728C
                dc.w $9500 ! ((grp_9D580 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B64
                dc.w $9500 ! ((grp_D7EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B64
                dc.w $9500 ! ((grp_D7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_EF9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF9A0 / 2) >> 16)
                dc.w 1
