byte_2D0338:    dc.b   0,  2,$70,$6D,$8D,$8B,$7E,$7C,$7F,$7C
                                        ; DATA XREF: ROM:off_D08   o
                dc.w sprite_24_24
                dc.w $777B
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6B
                dc.w $9500 ! ((grp_46E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8E6B
                dc.w $9500 ! ((grp_E31A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E31A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E31A0 / 2) >> 16)
                dc.w 1
