byte_2E8278:    dc.b   0,  8,$6F,$62,$8E,$8F,$80,$19,$7F,$57
                                        ; DATA XREF: ROM:off_1D58   o
                dc.w sprite_16_16
                dc.w $7468
                dc.w $9500 ! ((grp_7BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6C78
                dc.w $9500 ! ((grp_98F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C48
                dc.w $9500 ! ((grp_A5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7E28
                dc.w $9500 ! ((grp_A5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_186760 / 2) & $00FF)
                dc.w $9600 ! (((grp_186760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186760 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7D10
                dc.w $9500 ! ((grp_1963C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1963C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1963C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8455
                dc.w $9500 ! ((grp_196360 / 2) & $00FF)
                dc.w $9600 ! (((grp_196360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196360 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_CE040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8288
                dc.w $9500 ! ((grp_CE080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE080 / 2) >> 16)
                dc.w 2
