byte_2CD730:    dc.b   0,  2,$69,$56,$82,$6D,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_908   o
                dc.w sprite_32_24
                dc.w $6552
                dc.w $9500 ! ((grp_11F140 / 2) & $00FF)
                dc.w $9600 ! (((grp_11F140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11F140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7C6A
                dc.w $9500 ! ((grp_73D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_73D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $696A
                dc.w $9500 ! ((grp_C7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7AC0 / 2) >> 16)
                dc.w 2
