byte_2F8582:    dc.b   0, $B,$76,$5E,$98,$8D,$81,$75,$82,$75
                                        ; DATA XREF: ROM:off_2C84   o
                dc.w sprite_24_24
                dc.w $7861
                dc.w $9500 ! ((grp_151DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_151DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151DE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $717B
                dc.w $9500 ! ((grp_169E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_169E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7573
                dc.w $9500 ! ((grp_DDF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8059
                dc.w $9500 ! ((grp_DDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9061
                dc.w $9500 ! ((grp_DDF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9069
                dc.w $9500 ! ((grp_DDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $677B
                dc.w $9500 ! ((grp_F6040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6980
                dc.w $9500 ! ((grp_F6060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $758B
                dc.w $9500 ! ((grp_F5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $818B
                dc.w $9500 ! ((grp_F5FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9071
                dc.w $9500 ! ((grp_F6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9059
                dc.w $9500 ! ((grp_F6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6080 / 2) >> 16)
                dc.w 1
