byte_2D75B4:    dc.b   0,  7,$77,$65,$8F,$99,$85,$74,$88,$67
                                        ; DATA XREF: ROM:off_12E8   o
                dc.w sprite_32_24
                dc.w $756E
                dc.w $9500 ! ((grp_127840 / 2) & $00FF)
                dc.w $9600 ! (((grp_127840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $655E
                dc.w $9500 ! ((grp_7D080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7566
                dc.w $9500 ! ((grp_187180 / 2) & $00FF)
                dc.w $9600 ! (((grp_187180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187180 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $957D
                dc.w $9500 ! ((grp_1871E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1871E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1871E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $845E
                dc.w $9500 ! ((grp_CF680 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E85
                dc.w $9500 ! ((grp_CF6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D6E
                dc.w $9500 ! ((grp_E92E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E92E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E92E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $956E
                dc.w $9500 ! ((grp_E9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9300 / 2) >> 16)
                dc.w 1
