byte_2FF67E:    dc.b   0, $A,$88,$30,$CC,$75,$AA,$52,$AB,$52
                                        ; DATA XREF: ROM:off_3594   o
                dc.w sprite_24_24
                dc.w $BA2E
                dc.w $9500 ! ((grp_155620 / 2) & $00FF)
                dc.w $9600 ! (((grp_155620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155620 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $9256
                dc.w $9500 ! ((grp_AF780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9A4E
                dc.w $9500 ! ((grp_AF700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A247
                dc.w $9500 ! ((grp_AF680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $AA3F
                dc.w $9500 ! ((grp_AF600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $B236
                dc.w $9500 ! ((grp_AF580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8A63
                dc.w $9500 ! ((grp_1A10A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A10A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A10A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $BA46
                dc.w $9500 ! ((grp_E0BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $826C
                dc.w $9500 ! ((grp_F9360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B256
                dc.w $9500 ! ((grp_F9340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BA4E
                dc.w $9500 ! ((grp_F9320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9320 / 2) >> 16)
                dc.w 1
