byte_2EFF2A:    dc.b   0, $A,$44,$31,$BC,$87,$80,$88,$81,$88
                                        ; DATA XREF: ROM:off_25AC   o
                dc.w sprite_32_16
                dc.w $4171
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9971
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8081
                dc.w $9500 ! ((grp_1660C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1660C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1660C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6171
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8691
                dc.w $9500 ! ((grp_8B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B300 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7971
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7179
                dc.w $9500 ! ((grp_18DAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DAE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8979
                dc.w $9500 ! ((grp_DA200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B971
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7171
                dc.w $9500 ! ((grp_F1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7881
                dc.w $9500 ! ((grp_F1540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1540 / 2) >> 16)
                dc.w 1
