byte_2F8AB6:    dc.b   0,  5,$77,$60,$88,$8D,$7F,$76,$80,$76
                                        ; DATA XREF: ROM:off_2CB4   o
                dc.w sprite_32_24
                dc.w $6F66
                dc.w $9500 ! ((grp_138940 / 2) & $00FF)
                dc.w $9600 ! (((grp_138940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_138940 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $707C
                dc.w $9500 ! ((grp_9FB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $748C
                dc.w $9500 ! ((grp_18FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FA00 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $765E
                dc.w $9500 ! ((grp_18F9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F9A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7884
                dc.w $9500 ! ((grp_DE040 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F76
                dc.w $9500 ! ((grp_F6240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6240 / 2) >> 16)
                dc.w 1
