byte_2EC284:    dc.b   0,  3,$6D,$66,$92,$91,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_20C8   o
                dc.w sprite_32_32
                dc.w $6B64
                dc.w $9500 ! ((grp_2FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2FC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7574
                dc.w $9500 ! ((grp_2FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2FA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_16
                dc.w $6D84
                dc.w $9500 ! ((grp_BE440 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B6D
                dc.w $9500 ! ((grp_EF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF980 / 2) >> 16)
                dc.w 1
