byte_2DAE44:    dc.b   0,  3,$6A,$85,$B2,$8F,$8E,$8A,$A5,$8A
                                        ; DATA XREF: ROM:off_1518   o
                dc.w sprite_24_16
                dc.w $9882
                dc.w $9500 ! ((grp_15E080 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6880
                dc.w $9500 ! ((grp_7DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $788A
                dc.w $9500 ! ((grp_99600 / 2) & $00FF)
                dc.w $9600 ! (((grp_99600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $B08A
                dc.w $9500 ! ((grp_E9A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9A80 / 2) >> 16)
                dc.w 1
