byte_2F8F86:    dc.b   0,  5,$6F,$71,$90,$85,$7F,$6D,$80,$6D
                                        ; DATA XREF: ROM:off_2CEC   o
                dc.w sprite_32_24
                dc.w $726F
                dc.w $9500 ! ((grp_139540 / 2) & $00FF)
                dc.w $9600 ! (((grp_139540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6273
                dc.w $9500 ! ((grp_90F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_90F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $765F
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9270
                dc.w $9500 ! ((grp_C3E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7567
                dc.w $9500 ! ((grp_F6460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A57
                dc.w $9500 ! ((grp_F63E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63E0 / 2) >> 16)
                dc.w 1
