byte_2E1CB2:    dc.b   0,  4,$5A,$61,$95,$7E,$77,$6F,$77,$7C
                                        ; DATA XREF: ROM:off_199C   o
                dc.w sprite_32_16
                dc.w $6A6B
                dc.w $9500 ! ((grp_4BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4BD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $865E
                dc.w $9500 ! ((grp_7E300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $526F
                dc.w $9500 ! ((grp_187A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_187A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F7B
                dc.w $9500 ! ((grp_D0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E65
                dc.w $9500 ! ((grp_E9B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9B60 / 2) >> 16)
                dc.w 1
