byte_2D4BE2:    dc.b   0,  3,$57,$78,$83,$8B,$6D,$81,$6E,$81
                                        ; DATA XREF: ROM:off_1124   o
                dc.w sprite_32_24
                dc.w $5676
                dc.w $9500 ! ((grp_129DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_129DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $767A
                dc.w $9500 ! ((grp_B8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4E7E
                dc.w $9500 ! ((grp_EB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E7E
                dc.w $9500 ! ((grp_EB060 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB060 / 2) >> 16)
                dc.w 1
