byte_2F5084:    dc.b   0,  6,$6D,$66,$8D,$92,$80,$7C,$81,$7C
                                        ; DATA XREF: ROM:off_2A38   o
                dc.w sprite_32_32
                dc.w $6A73
                dc.w $9500 ! ((grp_3BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3BE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $7363
                dc.w $9500 ! ((grp_168640 / 2) & $00FF)
                dc.w $9600 ! (((grp_168640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168640 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8A73
                dc.w $9500 ! ((grp_19E760 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E760 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $808F
                dc.w $9500 ! ((grp_DC880 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $927C
                dc.w $9500 ! ((grp_C1BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6289
                dc.w $9500 ! ((grp_F4460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B6B
                dc.w $9500 ! ((grp_F4440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4440 / 2) >> 16)
                dc.w 1
