byte_2D7402:    dc.b   0,  7,$77,$63,$88,$7D,$82,$6C,$73,$61
                                        ; DATA XREF: ROM:off_12D4   o
                dc.w sprite_32_32
                dc.w $6D57
                dc.w $9500 ! ((grp_24E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_24E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7D77
                dc.w $9500 ! ((grp_64F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6577
                dc.w $9500 ! ((grp_84200 / 2) & $00FF)
                dc.w $9600 ! (((grp_84200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6557
                dc.w $9500 ! ((grp_BB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D47
                dc.w $9500 ! ((grp_BB480 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $656F
                dc.w $9500 ! ((grp_ECF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECF00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7577
                dc.w $9500 ! ((grp_ECF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECF20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $754B
                dc.w $9500 ! ((grp_ECF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECF40 / 2) >> 16)
                dc.w 1
