byte_2CEDCC:    dc.b   0,  4,$71,$68,$8F,$82,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_B28   o
                dc.w sprite_32_32
                dc.w $6F6E
                dc.w $9500 ! ((grp_12600 / 2) & $00FF)
                dc.w $9600 ! (((grp_12600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_8
                dc.w $7666
                dc.w $9500 ! ((grp_C8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_E27C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E27C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E27C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $878E
                dc.w $9500 ! ((grp_E27E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E27E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E27E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F7A
                dc.w $9500 ! ((grp_E2800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2800 / 2) >> 16)
                dc.w 1
