byte_2F4094:    dc.b   0,  2,$75,$72,$8D,$8F,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28D0   o
                dc.w sprite_24_24
                dc.w $7870
                dc.w $9500 ! ((grp_150400 / 2) & $00FF)
                dc.w $9600 ! (((grp_150400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150400 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7788
                dc.w $9500 ! ((grp_8D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7080
                dc.w $9500 ! ((grp_F3520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3520 / 2) >> 16)
                dc.w 1
