byte_2F179C:    dc.b   0,  4,$72,$68,$89,$88,$7D,$78,$7E,$78
                                        ; DATA XREF: ROM:off_2678   o
                dc.w sprite_16_24
                dc.w $776E
                dc.w $9500 ! ((grp_17D880 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D880 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $876E
                dc.w $9500 ! ((grp_C0A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $707A
                dc.w $9500 ! ((grp_F28E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F28E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F28E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7685
                dc.w $9500 ! ((grp_F2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D66
                dc.w $9500 ! ((grp_F2920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2920 / 2) >> 16)
                dc.w 1
