byte_2D3DFE:    dc.b   0,  7,$71,$65,$92,$8F,$7C,$76,$7D,$76
                                        ; DATA XREF: ROM:off_1084   o
                dc.w sprite_24_24
                dc.w $7678
                dc.w $9500 ! ((grp_140B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_140B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140B60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7760
                dc.w $9500 ! ((grp_172600 / 2) & $00FF)
                dc.w $9600 ! (((grp_172600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6680
                dc.w $9500 ! ((grp_77900 / 2) & $00FF)
                dc.w $9600 ! (((grp_77900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8358
                dc.w $9500 ! ((grp_CADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CADC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8760
                dc.w $9500 ! ((grp_B3300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E80
                dc.w $9500 ! ((grp_E5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E79
                dc.w $9500 ! ((grp_E5760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F64
                dc.w $9500 ! ((grp_E5780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5780 / 2) >> 16)
                dc.w 1
