byte_2DD29C:    dc.b   0,  5,$75,$65,$8F,$83,$7F,$74,$87,$66
                                        ; DATA XREF: ROM:off_16A8   o
                dc.w sprite_32_24
                dc.w $7859
                dc.w $9500 ! ((grp_125440 / 2) & $00FF)
                dc.w $9600 ! (((grp_125440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7871
                dc.w $9500 ! ((grp_142C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_142C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142C00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $8089
                dc.w $9500 ! ((grp_CD0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6869
                dc.w $9500 ! ((grp_B4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7068
                dc.w $9500 ! ((grp_E7540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7078
                dc.w $9500 ! ((grp_E7560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7560 / 2) >> 16)
                dc.w 1
