byte_2F257C:    dc.b   0,  4,$71,$59,$88,$8D,$7C,$78,$7D,$78
                                        ; DATA XREF: ROM:off_2708   o
                dc.w sprite_16_24
                dc.w $7868
                dc.w $9500 ! ((grp_17CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7A80
                dc.w $9500 ! ((grp_8BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6877
                dc.w $9500 ! ((grp_DA680 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7860
                dc.w $9500 ! ((grp_DA6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8872
                dc.w $9500 ! ((grp_F18E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F18E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F18E0 / 2) >> 16)
                dc.w 1
