byte_2EE404:    dc.b   0,  3,$7F,$13,$80,$7E,$7F,$48,$80,$48
                                        ; DATA XREF: ROM:off_2388   o
                dc.w sprite_8_32
                dc.w $7D11
                dc.w $9500 ! ((grp_AB480 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7D31
                dc.w $9500 ! ((grp_AB500 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7D51
                dc.w $9500 ! ((grp_AB580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7D71
                dc.w $9500 ! ((grp_BF100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF100 / 2) >> 16)
                dc.w 2
