byte_2E52BC:    dc.b   0,  9,$6F,$61,$88,$8E,$3F,$97,$7E,$62
                                        ; DATA XREF: ROM:off_1BB0   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8A5E
                dc.w $9500 ! ((grp_177DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_177DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82780 / 2) & $00FF)
                dc.w $9600 ! (((grp_82780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_82800 / 2) & $00FF)
                dc.w $9600 ! (((grp_82800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $826D
                dc.w $9500 ! ((grp_BA500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F55
                dc.w $9500 ! ((grp_EC480 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A76
                dc.w $9500 ! ((grp_EC4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC4A0 / 2) >> 16)
                dc.w 1
