byte_2E5632:    dc.b   0,  8,$6F,$61,$88,$8E,$49,$98,$7C,$63
                                        ; DATA XREF: ROM:off_1BCC   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8262
                dc.w $9500 ! ((grp_177F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_177F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $625D
                dc.w $9500 ! ((grp_82980 / 2) & $00FF)
                dc.w $9600 ! (((grp_82980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $725D
                dc.w $9500 ! ((grp_82B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_82B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9261
                dc.w $9500 ! ((grp_82700 / 2) & $00FF)
                dc.w $9600 ! (((grp_82700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA680 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F55
                dc.w $9500 ! ((grp_EC520 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC520 / 2) >> 16)
                dc.w 1
