byte_2EA3F4:    dc.b   0,  6,$68,$69,$96,$8E,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F30   o
                dc.w sprite_32_32
                dc.w $6C6F
                dc.w $9500 ! ((grp_29000 / 2) & $00FF)
                dc.w $9600 ! (((grp_29000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_29000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6467
                dc.w $9500 ! ((grp_9C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C71
                dc.w $9500 ! ((grp_A9B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B8F
                dc.w $9500 ! ((grp_D7200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $647A
                dc.w $9500 ! ((grp_BDD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9474
                dc.w $9500 ! ((grp_EF000 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948A
                dc.w $9500 ! ((grp_EF020 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF020 / 2) >> 16)
                dc.w 1
