byte_2F9728:    dc.b   0,  2,$98,$7D,$AB,$8A,$A1,$83,$A2,$83
                                        ; DATA XREF: ROM:off_2D80   o
                dc.w sprite_24_8
                dc.w $967B
                dc.w $9500 ! ((grp_1900C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1900C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1900C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9C83
                dc.w $9500 ! ((grp_DE5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $958B
                dc.w $9500 ! ((grp_F69A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F69A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F69A0 / 2) >> 16)
                dc.w 1
