byte_2D1AA6:    dc.b   0,  1,$73,$7C,$8E,$8D,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_E44   o
                dc.w sprite_32_16
                dc.w $717A
                dc.w $9500 ! ((grp_48100 / 2) & $00FF)
                dc.w $9600 ! (((grp_48100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $728A
                dc.w $9500 ! ((grp_184420 / 2) & $00FF)
                dc.w $9600 ! (((grp_184420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184420 / 2) >> 16)
                dc.w 3
