byte_2F4578:    dc.b   0,  1,$75,$6A,$8E,$96,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_2988   o
                dc.w sprite_32_32
                dc.w $7178
                dc.w $9500 ! ((grp_3AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3AC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $7868
                dc.w $9500 ! ((grp_167F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_167F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167F80 / 2) >> 16)
                dc.w 6
