byte_2ECF44:    dc.b   0,  2,$72,$78,$8F,$91,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_2248   o
                dc.w sprite_24_32
                dc.w $7775
                dc.w $9500 ! ((grp_1117C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1117C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1117C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6F7A
                dc.w $9500 ! ((grp_19C0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C0C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F7C
                dc.w $9500 ! ((grp_BE6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE6C0 / 2) >> 16)
                dc.w 2
