byte_2F0300:    dc.b   0, $E,$5F,$57,$9A,$96,$7F,$74,$80,$74
                                        ; DATA XREF: ROM:000025E0   o
                dc.w sprite_32_32
                dc.w $656B
                dc.w $9500 ! ((grp_34400 / 2) & $00FF)
                dc.w $9600 ! (((grp_34400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $654B
                dc.w $9500 ! ((grp_34600 / 2) & $00FF)
                dc.w $9600 ! (((grp_34600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8553
                dc.w $9500 ! ((grp_34800 / 2) & $00FF)
                dc.w $9600 ! (((grp_34800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $8573
                dc.w $9500 ! ((grp_133CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_133CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_133CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $555B
                dc.w $9500 ! ((grp_6B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5D8B
                dc.w $9500 ! ((grp_1663C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1663C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1663C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8D8B
                dc.w $9500 ! ((grp_166300 / 2) & $00FF)
                dc.w $9600 ! (((grp_166300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166300 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $557B
                dc.w $9500 ! ((grp_DA3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $5583
                dc.w $9500 ! ((grp_DA400 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $854B
                dc.w $9500 ! ((grp_DA440 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A57B
                dc.w $9500 ! ((grp_DA480 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A563
                dc.w $9500 ! ((grp_BFD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFD00 / 2) >> 16)
                dc.w 2
