byte_2CEC46:    dc.b   0,$13,$6A,$7D,$9A,$CD,$81,$59,$82,$59
                                        ; DATA XREF: ROM:off_B1C   o
                dc.w sprite_32_32
                dc.w $6691
                dc.w $9500 ! ((grp_12E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6E71
                dc.w $9500 ! ((grp_13000 / 2) & $00FF)
                dc.w $9600 ! (((grp_13000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8E81
                dc.w $9500 ! ((grp_FA9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $86A1
                dc.w $9500 ! ((grp_156D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_156D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7761
                dc.w $9500 ! ((grp_74580 / 2) & $00FF)
                dc.w $9600 ! (((grp_74580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A41
                dc.w $9500 ! ((grp_74680 / 2) & $00FF)
                dc.w $9600 ! (((grp_74680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A11
                dc.w $9500 ! ((grp_74600 / 2) & $00FF)
                dc.w $9600 ! (((grp_74600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A01
                dc.w $9500 ! ((grp_74600 / 2) & $00FF)
                dc.w $9600 ! (((grp_74600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A21
                dc.w $9500 ! ((grp_74600 / 2) & $00FF)
                dc.w $9600 ! (((grp_74600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A31
                dc.w $9500 ! ((grp_74600 / 2) & $00FF)
                dc.w $9600 ! (((grp_74600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E71
                dc.w $9500 ! ((grp_74700 / 2) & $00FF)
                dc.w $9600 ! (((grp_74700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6671
                dc.w $9500 ! ((grp_A3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $76B1
                dc.w $9500 ! ((grp_183AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_183AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5E79
                dc.w $9500 ! ((grp_192760 / 2) & $00FF)
                dc.w $9600 ! (((grp_192760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192760 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5E91
                dc.w $9500 ! ((grp_1927C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1927C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1927C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7759
                dc.w $9500 ! ((grp_C8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8691
                dc.w $9500 ! ((grp_B1380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C51
                dc.w $9500 ! ((grp_E2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E79
                dc.w $9500 ! ((grp_E2920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9EA1
                dc.w $9500 ! ((grp_E2940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2940 / 2) >> 16)
                dc.w 1
