byte_2F205A:    dc.b   0,  7,$76,$67,$A8,$8D,$90,$78,$91,$78
                                        ; DATA XREF: ROM:off_26E4   o
                dc.w sprite_32_32
                dc.w $8E62
                dc.w $9500 ! ((grp_36A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_36A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7660
                dc.w $9500 ! ((grp_14E480 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E480 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7478
                dc.w $9500 ! ((grp_54700 / 2) & $00FF)
                dc.w $9600 ! (((grp_54700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7888
                dc.w $9500 ! ((grp_18DD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DD80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9482
                dc.w $9500 ! ((grp_DAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E64
                dc.w $9500 ! ((grp_C01C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C01C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C01C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AE67
                dc.w $9500 ! ((grp_C0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C7E
                dc.w $9500 ! ((grp_F1D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1D20 / 2) >> 16)
                dc.w 1
