byte_2FDE4E:    dc.b   0,  7,$77,$48,$92,$8D,$84,$6A,$85,$6A
                                        ; DATA XREF: ROM:off_3354   o
                dc.w sprite_16_32
                dc.w $7D49
                dc.w $9500 ! ((grp_71600 / 2) & $00FF)
                dc.w $9600 ! (((grp_71600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7D69
                dc.w $9500 ! ((grp_95780 / 2) & $00FF)
                dc.w $9600 ! (((grp_95780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7550
                dc.w $9500 ! ((grp_AF000 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_1915C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1915C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1915C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7570
                dc.w $9500 ! ((grp_1A0680 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0680 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7D78
                dc.w $9500 ! ((grp_C5E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D63
                dc.w $9500 ! ((grp_C5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8341
                dc.w $9500 ! ((grp_F86C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F86C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F86C0 / 2) >> 16)
                dc.w 1
