byte_2FECA0:    dc.b   0,  2,$7B,$7E,$86,$8D,$81,$82,$82,$82
                                        ; DATA XREF: ROM:off_34C8   o
                dc.w sprite_16_16
                dc.w $7986
                dc.w $9500 ! ((grp_96380 / 2) & $00FF)
                dc.w $9600 ! (((grp_96380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $797E
                dc.w $9500 ! ((grp_E0900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8176
                dc.w $9500 ! ((grp_E0940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0940 / 2) >> 16)
                dc.w 2
