byte_2FF834:    dc.b   0, $A,$41,$2F,$CE,$C0,$87,$77,$88,$77
                                        ; DATA XREF: ROM:off_35A0   o
                dc.w sprite_32_24
                dc.w $B32D
                dc.w $9500 ! ((grp_13C840 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $A53D
                dc.w $9500 ! ((grp_71C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_71C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8D5D
                dc.w $9500 ! ((grp_16E280 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8D6D
                dc.w $9500 ! ((grp_E0CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9555
                dc.w $9500 ! ((grp_E0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B545
                dc.w $9500 ! ((grp_E0C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3DBD
                dc.w $9500 ! ((grp_F94E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F94E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F94E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8565
                dc.w $9500 ! ((grp_F94C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F94C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F94C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D4D
                dc.w $9500 ! ((grp_F9460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A55D
                dc.w $9500 ! ((grp_F94A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F94A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F94A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B54D
                dc.w $9500 ! ((grp_F9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9480 / 2) >> 16)
                dc.w 1
