byte_2FDD4C:    dc.b   0,  5,$72,$50,$93,$8D,$82,$6E,$83,$6E
                                        ; DATA XREF: ROM:off_3348   o
                dc.w sprite_32_32
                dc.w $7460
                dc.w $9500 ! ((grp_44A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_44A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $7948
                dc.w $9500 ! ((grp_182380 / 2) & $00FF)
                dc.w $9600 ! (((grp_182380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_1914A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1914A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1914A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7880
                dc.w $9500 ! ((grp_E0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C6A
                dc.w $9500 ! ((grp_C5DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $946D
                dc.w $9500 ! ((grp_F8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8680 / 2) >> 16)
                dc.w 1
