byte_2DAB12:    dc.b   0,  7,$6C,$74,$88,$8C,$9F,$7F,$86,$82
                                        ; DATA XREF: ROM:off_14EC   o
                dc.w sprite_24_16
                dc.w $687E
                dc.w $9500 ! ((grp_15D780 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $695E
                dc.w $9500 ! ((grp_7D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6D6E
                dc.w $9500 ! ((grp_7D780 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $806E
                dc.w $9500 ! ((grp_A5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_CFC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $907D
                dc.w $9500 ! ((grp_CFBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6083
                dc.w $9500 ! ((grp_B7200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $887E
                dc.w $9500 ! ((grp_E9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9780 / 2) >> 16)
                dc.w 1
