byte_2F95C8:    dc.b   0,  1,$77,$5F,$8B,$76,$81,$6A,$82,$6A
                                        ; DATA XREF: ROM:off_2D58   o
                dc.w sprite_24_16
                dc.w $755D
                dc.w $9500 ! ((grp_16A2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7D6D
                dc.w $9500 ! ((grp_C4140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4140 / 2) >> 16)
                dc.w 2
