byte_2FB5E8:    dc.b   0,  2,$72,$61,$84,$8D,$7B,$77,$7C,$77
                                        ; DATA XREF: ROM:off_2F78   o
                dc.w sprite_16_32
                dc.w $776F
                dc.w $9500 ! ((grp_70700 / 2) & $00FF)
                dc.w $9600 ! (((grp_70700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $705F
                dc.w $9500 ! ((grp_16B880 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B880 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7E8F
                dc.w $9500 ! ((grp_F7CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7CA0 / 2) >> 16)
                dc.w 1
