byte_2D48D0:    dc.b   0,  6,$6C,$5F,$8F,$93,$83,$7B,$7F,$6E
                                        ; DATA XREF: ROM:off_1100   o
                dc.w sprite_32_32
                dc.w $7475
                dc.w $9500 ! ((grp_18600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $5C7C
                dc.w $9500 ! ((grp_159D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_159D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7665
                dc.w $9500 ! ((grp_78300 / 2) & $00FF)
                dc.w $9600 ! (((grp_78300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9076
                dc.w $9500 ! ((grp_185080 / 2) & $00FF)
                dc.w $9600 ! (((grp_185080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185080 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C74
                dc.w $9500 ! ((grp_E5D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5D20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_E5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E93
                dc.w $9500 ! ((grp_E5CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5CE0 / 2) >> 16)
                dc.w 1
