byte_2E7936:    dc.b   0,  8,$6F,$6C,$8E,$8F,$8C,$65,$68,$6F
                                        ; DATA XREF: ROM:off_1D04   o
                dc.w sprite_24_32
                dc.w $7771
                dc.w $9500 ! ((grp_105640 / 2) & $00FF)
                dc.w $9600 ! (((grp_105640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6664
                dc.w $9500 ! ((grp_15EBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8F72
                dc.w $9500 ! ((grp_7F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E64
                dc.w $9500 ! ((grp_188200 / 2) & $00FF)
                dc.w $9600 ! (((grp_188200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5E6B
                dc.w $9500 ! ((grp_EA2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA2C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F8A
                dc.w $9500 ! ((grp_EA2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA2E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F74
                dc.w $9500 ! ((grp_EA300 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8A
                dc.w $9500 ! ((grp_EA340 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F73
                dc.w $9500 ! ((grp_EA320 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA320 / 2) >> 16)
                dc.w 1
