byte_2D7A92:    dc.b   0,  5,$75,$5D,$8B,$A2,$84,$80,$80,$6A
                                        ; DATA XREF: ROM:off_131C   o
                dc.w sprite_32_24
                dc.w $6E6F
                dc.w $9500 ! ((grp_124540 / 2) & $00FF)
                dc.w $9600 ! (((grp_124540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7787
                dc.w $9500 ! ((grp_172D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_172D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8E6A
                dc.w $9500 ! ((grp_172FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_172FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $755F
                dc.w $9500 ! ((grp_79180 / 2) & $00FF)
                dc.w $9600 ! (((grp_79180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7C57
                dc.w $9500 ! ((grp_E6860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F9F
                dc.w $9500 ! ((grp_E6820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6820 / 2) >> 16)
                dc.w 1
