byte_2E8796:    dc.b   0,  8,$6F,$6D,$8E,$8F,$92,$5C,$6B,$6C
                                        ; DATA XREF: ROM:off_1D84   o
                dc.w sprite_24_24
                dc.w $6168
                dc.w $9500 ! ((grp_143E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_143E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143E00 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7968
                dc.w $9500 ! ((grp_143CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_143CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143CE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_186A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_186A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186A60 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7560
                dc.w $9500 ! ((grp_186AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_186AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8258
                dc.w $9500 ! ((grp_186B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_186B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186B20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_CE740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CE700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $596C
                dc.w $9500 ! ((grp_B6280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9170
                dc.w $9500 ! ((grp_B6240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6240 / 2) >> 16)
                dc.w 2
