byte_2D1B54:    dc.b   0,  2,$6C,$73,$93,$8F,$7A,$81,$7B,$81
                                        ; DATA XREF: ROM:off_E50   o
                dc.w sprite_32_32
                dc.w $6871
                dc.w $9500 ! ((grp_16200 / 2) & $00FF)
                dc.w $9600 ! (((grp_16200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8871
                dc.w $9500 ! ((grp_5DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5DA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $6087
                dc.w $9500 ! ((grp_E3CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3CC0 / 2) >> 16)
                dc.w 1
