byte_2F279C:    dc.b   0,  1,$79,$67,$89,$8E,$81,$80,$82,$80
                                        ; DATA XREF: ROM:00002730   o
                dc.w sprite_24_24
                dc.w $7571
                dc.w $9500 ! ((grp_14E120 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E120 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7789
                dc.w $9500 ! ((grp_DA8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA8C0 / 2) >> 16)
                dc.w 2
