byte_2ED288:    dc.b   0,  3,$96,$84,$A6,$8E,$86,$83,$87,$83
                                        ; DATA XREF: ROM:off_2280   o
                dc.w sprite_32_16
                dc.w $8981
                dc.w $9500 ! ((grp_52400 / 2) & $00FF)
                dc.w $9600 ! (((grp_52400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6276
                dc.w $9500 ! ((grp_164E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_164E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7181
                dc.w $9500 ! ((grp_164EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_164EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6986
                dc.w $9500 ! ((grp_F0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0200 / 2) >> 16)
                dc.w 1
