byte_2ED3F2:    dc.b   0,  4,$92,$72,$9B,$83,$85,$80,$86,$80
                                        ; DATA XREF: ROM:off_2294   o
                dc.w sprite_32_16
                dc.w $6E7A
                dc.w $9500 ! ((grp_52300 / 2) & $00FF)
                dc.w $9600 ! (((grp_52300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8E70
                dc.w $9500 ! ((grp_17B780 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_D8A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E72
                dc.w $9500 ! ((grp_D8A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $808A
                dc.w $9500 ! ((grp_D8A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8A80 / 2) >> 16)
                dc.w 2
