byte_2CC884:    dc.b   0,  2,$73,$7B,$98,$A1,$85,$8E,$86,$8E
                                        ; DATA XREF: ROM:off_7D0   o
                dc.w sprite_32_24
                dc.w $7079
                dc.w $9500 ! ((grp_11E6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E6C0 / 2) >> 16)
                dc.w    $C
                dc.w sprite_8_24
                dc.w $9186
                dc.w $9500 ! ((grp_191B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_191B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191B60 / 2) >> 16)
                dc.w     3
                dc.w sprite_8_8
                dc.w $7B9A
                dc.w $9500 ! ((grp_E1560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1560 / 2) >> 16)
                dc.w     1
