byte_2D4554:    dc.b   0,  3,$59,$62,$AB,$8C,$86,$77,$87,$77
                                        ; DATA XREF: ROM:off_10D8   o
                dc.w sprite_32_16
                dc.w $8078
                dc.w $9500 ! ((grp_49200 / 2) & $00FF)
                dc.w $9600 ! (((grp_49200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7072
                dc.w $9500 ! ((grp_77980 / 2) & $00FF)
                dc.w $9600 ! (((grp_77980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8070
                dc.w $9500 ! ((grp_184F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_184F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6876
                dc.w $9500 ! ((grp_E57A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E57A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E57A0 / 2) >> 16)
                dc.w 1
