byte_2FE356:    dc.b   0,  3,$79,$75,$89,$88,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_33C4   o
                dc.w sprite_16_24
                dc.w $7774
                dc.w $9500 ! ((grp_182740 / 2) & $00FF)
                dc.w $9600 ! (((grp_182740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8776
                dc.w $9500 ! ((grp_C6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7769
                dc.w $9500 ! ((grp_F8960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F71
                dc.w $9500 ! ((grp_F8940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8940 / 2) >> 16)
                dc.w 1
