byte_2EC186:    dc.b   0,  2,$72,$6D,$93,$8F,$82,$7E,$83,$7E
                                        ; DATA XREF: ROM:off_20B4   o
                dc.w sprite_32_32
                dc.w $706A
                dc.w $9500 ! ((grp_2F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_2F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2F400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $708A
                dc.w $9500 ! ((grp_9D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $906C
                dc.w $9500 ! ((grp_AAA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAA00 / 2) >> 16)
                dc.w 4
