byte_2DDD88:    dc.b   0,  3,$76,$66,$8F,$90,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:00001720   o
                dc.w sprite_24_32
                dc.w $746B
                dc.w $9500 ! ((grp_107440 / 2) & $00FF)
                dc.w $9600 ! (((grp_107440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7363
                dc.w $9500 ! ((grp_D2200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $788B
                dc.w $9500 ! ((grp_D2140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C6F
                dc.w $9500 ! ((grp_EB100 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB100 / 2) >> 16)
                dc.w 1
