byte_2FEC5C:    dc.b   0,  1,$7B,$7F,$86,$8D,$81,$81,$82,$81
                                        ; DATA XREF: ROM:off_34C0   o
                dc.w sprite_16_24
                dc.w $797C
                dc.w $9500 ! ((grp_182BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_182BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8374
                dc.w $9500 ! ((grp_F9080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9080 / 2) >> 16)
                dc.w 1
