byte_2EC7D8:    dc.b   0,  4,$70,$54,$8A,$65,$77,$64,$78,$64
                                        ; DATA XREF: ROM:off_2160   o
                dc.w sprite_16_16
                dc.w $7E54
                dc.w $9500 ! ((grp_88980 / 2) & $00FF)
                dc.w $9600 ! (((grp_88980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6664
                dc.w $9500 ! ((grp_BE840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E5C
                dc.w $9500 ! ((grp_BE880 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7655
                dc.w $9500 ! ((grp_BE8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E70
                dc.w $9500 ! ((grp_EFDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFDE0 / 2) >> 16)
                dc.w 1
