byte_2CD1B8:    dc.b   0,  3,$6C,$6E,$93,$90,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_888   o
                dc.w sprite_32_32
                dc.w $7172
                dc.w $9500 ! ((grp_11000 / 2) & $00FF)
                dc.w $9600 ! (((grp_11000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11000 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $6977
                dc.w $9500 ! ((grp_191F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_191F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9174
                dc.w $9500 ! ((grp_191F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_191F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B6A
                dc.w $9500 ! ((grp_C8100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8100 / 2) >> 16)
                dc.w 2
