byte_2EB832:    dc.b   0, $A,$4E,$5E,$C3,$8F,$88,$76,$89,$76
                                        ; DATA XREF: ROM:off_2054   o
                dc.w sprite_32_32
                dc.w $5C66
                dc.w $9500 ! ((grp_2C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7C66
                dc.w $9500 ! ((grp_2C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9C66
                dc.w $9500 ! ((grp_1108C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1108C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1108C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4C86
                dc.w $9500 ! ((grp_51200 / 2) & $00FF)
                dc.w $9600 ! (((grp_51200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $6C86
                dc.w $9500 ! ((grp_51400 / 2) & $00FF)
                dc.w $9600 ! (((grp_51400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $B45E
                dc.w $9500 ! ((grp_17AF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AF40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4C76
                dc.w $9500 ! ((grp_87780 / 2) & $00FF)
                dc.w $9600 ! (((grp_87780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8C86
                dc.w $9500 ! ((grp_87980 / 2) & $00FF)
                dc.w $9600 ! (((grp_87980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9C86
                dc.w $9500 ! ((grp_D7D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A45E
                dc.w $9500 ! ((grp_D7DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B73
                dc.w $9500 ! ((grp_EF6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6C0 / 2) >> 16)
                dc.w 1
