byte_2DC85C:    dc.b   0,  7,$7B,$57,$92,$94,$8B,$79,$83,$6A
                                        ; DATA XREF: ROM:off_1640   o
                dc.w sprite_24_24
                dc.w $7C65
                dc.w $9500 ! ((grp_144820 / 2) & $00FF)
                dc.w $9600 ! (((grp_144820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144820 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $837D
                dc.w $9500 ! ((grp_61C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8355
                dc.w $9500 ! ((grp_7D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9471
                dc.w $9500 ! ((grp_7D380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7467
                dc.w $9500 ! ((grp_B6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9385
                dc.w $9500 ! ((grp_B6FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $899D
                dc.w $9500 ! ((grp_E94E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E94E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E94E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B8D
                dc.w $9500 ! ((grp_E9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9500 / 2) >> 16)
                dc.w 1
