byte_2DE0D4:    dc.b   0,  7,$76,$63,$8F,$8E,$82,$77,$85,$6E
                                        ; DATA XREF: ROM:off_1748   o
                dc.w sprite_24_32
                dc.w $7666
                dc.w $9500 ! ((grp_10BC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10BC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10BC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7686
                dc.w $9500 ! ((grp_161C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_161C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7E5E
                dc.w $9500 ! ((grp_D4E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E6A
                dc.w $9500 ! ((grp_B8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E66
                dc.w $9500 ! ((grp_B8CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_ED2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED2C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E8A
                dc.w $9500 ! ((grp_ED2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED2E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $966A
                dc.w $9500 ! ((grp_EADA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EADA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EADA0 / 2) >> 16)
                dc.w 1
