byte_2D1F8A:    dc.b   0,  3,$6D,$5D,$8B,$8E,$7A,$73,$7B,$73
                                        ; DATA XREF: ROM:off_E84   o
                dc.w sprite_24_32
                dc.w $726F
                dc.w $9500 ! ((grp_FCDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FCDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FCDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6D57
                dc.w $9500 ! ((grp_13FDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13FDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13FDE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $8777
                dc.w $9500 ! ((grp_A3F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $655A
                dc.w $9500 ! ((grp_B2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2340 / 2) >> 16)
                dc.w 2
