byte_2EFA4A:    dc.b   0,  2,$79,$82,$85,$8C,$7F,$87,$80,$87
                                        ; DATA XREF: ROM:off_254C   o
                dc.w sprite_16_8
                dc.w $7785
                dc.w $9500 ! ((grp_D9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $797D
                dc.w $9500 ! ((grp_D9FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F8D
                dc.w $9500 ! ((grp_F0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0D00 / 2) >> 16)
                dc.w 1
