byte_2E8A90:    dc.b   0,  5,$7A,$64,$87,$8D,$7F,$77,$83,$6C
                                        ; DATA XREF: ROM:off_1DA8   o
                dc.w sprite_16_24
                dc.w $757F
                dc.w $9500 ! ((grp_174A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_174A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7D5F
                dc.w $9500 ! ((grp_A5800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $755F
                dc.w $9500 ! ((grp_B6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8567
                dc.w $9500 ! ((grp_B63C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B63C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B63C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8577
                dc.w $9500 ! ((grp_E8860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8587
                dc.w $9500 ! ((grp_E8880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8880 / 2) >> 16)
                dc.w 1
