byte_2EDD2E:    dc.b   0,  2,$6D,$66,$98,$96,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_230C   o
                dc.w sprite_24_32
                dc.w $7C6D
                dc.w $9500 ! ((grp_111940 / 2) & $00FF)
                dc.w $9600 ! (((grp_111940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6C70
                dc.w $9500 ! ((grp_68C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $8065
                dc.w $9500 ! ((grp_18CCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CCA0 / 2) >> 16)
                dc.w 3
