byte_2CC7C0:    dc.b   0,  3,$67,$7A,$8B,$8E,$79,$84,$7A,$84
                                        ; DATA XREF: ROM:off_7C0   o
                dc.w sprite_24_24
                dc.w $7378
                dc.w $9500 ! ((grp_13DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_13DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13DF80 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $6383
                dc.w $9500 ! ((grp_B01C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B01C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B01C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B81
                dc.w $9500 ! ((grp_B0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B7C
                dc.w $9500 ! ((grp_B0240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0240 / 2) >> 16)
                dc.w 2
