byte_2F3A82:    dc.b   0,  5,$6C,$5D,$8F,$8B,$73,$76,$74,$76
                                        ; DATA XREF: ROM:off_27EC   o
                dc.w sprite_32_32
                dc.w $776A
                dc.w $9500 ! ((grp_39800 / 2) & $00FF)
                dc.w $9600 ! (((grp_39800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $675B
                dc.w $9500 ! ((grp_55500 / 2) & $00FF)
                dc.w $9600 ! (((grp_55500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4F66
                dc.w $9500 ! ((grp_167740 / 2) & $00FF)
                dc.w $9600 ! (((grp_167740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167740 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $738A
                dc.w $9500 ! ((grp_18E320 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E320 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $676B
                dc.w $9500 ! ((grp_DB8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9062
                dc.w $9500 ! ((grp_F2C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2C00 / 2) >> 16)
                dc.w 1
