byte_2F861C:    dc.b   0, $D,$70,$3E,$90,$8A,$80,$64,$81,$64
                                        ; DATA XREF: ROM:off_2C88   o
                dc.w sprite_16_32
                dc.w $6E5C
                dc.w $9500 ! ((grp_6F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7E5C
                dc.w $9500 ! ((grp_6F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7E7C
                dc.w $9500 ! ((grp_17FD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FD40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6E4C
                dc.w $9500 ! ((grp_90B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E4C
                dc.w $9500 ! ((grp_90A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_90A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8E4C
                dc.w $9500 ! ((grp_AE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $763C
                dc.w $9500 ! ((grp_18F760 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F760 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7644
                dc.w $9500 ! ((grp_18F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F700 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8E7C
                dc.w $9500 ! ((grp_C3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E7C
                dc.w $9500 ! ((grp_F6160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7685
                dc.w $9500 ! ((grp_F6120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $767C
                dc.w $9500 ! ((grp_F6140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E3C
                dc.w $9500 ! ((grp_F60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E6C
                dc.w $9500 ! ((grp_F60E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60E0 / 2) >> 16)
                dc.w 1
