byte_2F9486:    dc.b   0,  4,$66,$70,$91,$92,$7B,$81,$7C,$81
                                        ; DATA XREF: ROM:off_2D3C   o
                dc.w sprite_16_32
                dc.w $7B6D
                dc.w $9500 ! ((grp_6FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6B77
                dc.w $9500 ! ((grp_180280 / 2) & $00FF)
                dc.w $9600 ! (((grp_180280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180280 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8B74
                dc.w $9500 ! ((grp_19F6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F6C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $648F
                dc.w $9500 ! ((grp_DE540 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6384
                dc.w $9500 ! ((grp_F6760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6760 / 2) >> 16)
                dc.w 1
