byte_2F6ACA:    dc.b   0,$16,$77,$53,$A8,$7E,$82,$88,$83,$88
                                        ; DATA XREF: ROM:off_2B64   o
                dc.w sprite_24_32
                dc.w $7860
                dc.w $9500 ! ((grp_1171C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1171C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1171C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $B049
                dc.w $9500 ! ((grp_151180 / 2) & $00FF)
                dc.w $9600 ! (((grp_151180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151180 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7880
                dc.w $9500 ! ((grp_56A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7850
                dc.w $9500 ! ((grp_56500 / 2) & $00FF)
                dc.w $9600 ! (((grp_56500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $987A
                dc.w $9500 ! ((grp_17F380 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F380 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $4089
                dc.w $9500 ! ((grp_9F680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7051
                dc.w $9500 ! ((grp_AD180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9852
                dc.w $9500 ! ((grp_AD280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD280 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $3B81
                dc.w $9500 ! ((grp_18F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F100 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6088
                dc.w $9500 ! ((grp_18F160 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F160 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7E48
                dc.w $9500 ! ((grp_18EEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EEC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9060
                dc.w $9500 ! ((grp_19EB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EB80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A869
                dc.w $9500 ! ((grp_19EDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EDC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7E90
                dc.w $9500 ! ((grp_DD300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B261
                dc.w $9500 ! ((grp_DD340 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A05A
                dc.w $9500 ! ((grp_C2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A06A
                dc.w $9500 ! ((grp_C2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A853
                dc.w $9500 ! ((grp_C2440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B069
                dc.w $9500 ! ((grp_C2BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $C849
                dc.w $9500 ! ((grp_C2C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B82
                dc.w $9500 ! ((grp_F5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7078
                dc.w $9500 ! ((grp_F4BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9872
                dc.w $9500 ! ((grp_F4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B80 / 2) >> 16)
                dc.w 1
