byte_2E7490:    dc.b   0,  8,$6F,$68,$8E,$8F,$7C,$71,$60,$68
                                        ; DATA XREF: ROM:off_1CD8   o
                dc.w sprite_24_32
                dc.w $6E68
                dc.w $9500 ! ((grp_10B4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $5E51
                dc.w $9500 ! ((grp_64D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8669
                dc.w $9500 ! ((grp_161500 / 2) & $00FF)
                dc.w $9600 ! (((grp_161500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161500 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6E51
                dc.w $9500 ! ((grp_189E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_189E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189E20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_D4600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8288
                dc.w $9500 ! ((grp_D45C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D45C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D45C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5659
                dc.w $9500 ! ((grp_BB100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9661
                dc.w $9500 ! ((grp_ECCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECCA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E62
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
