byte_2CC79E:    dc.b   0,  1,$79,$77,$95,$82,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_7BC   o
                dc.w sprite_24_16
                dc.w $7775
                dc.w $9500 ! ((grp_156040 / 2) & $00FF)
                dc.w $9600 ! (((grp_156040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156040 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8F76
                dc.w $9500 ! ((grp_E14E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E14E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E14E0 / 2) >> 16)
                dc.w 1
