byte_2D8782:    dc.b   0,  5,$6F,$5A,$8E,$90,$87,$74,$88,$60
                                        ; DATA XREF: ROM:off_13AC   o
                dc.w sprite_24_32
                dc.w $8B62
                dc.w $9500 ! ((grp_10BAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10BAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10BAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7B58
                dc.w $9500 ! ((grp_84600 / 2) & $00FF)
                dc.w $9600 ! (((grp_84600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7B70
                dc.w $9500 ! ((grp_A7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8368
                dc.w $9500 ! ((grp_A7F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B83
                dc.w $9500 ! ((grp_D4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $818C
                dc.w $9500 ! ((grp_ED280 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED280 / 2) >> 16)
                dc.w 1
