byte_2CEAD0:    dc.b   0, $A,$7D,  2,$91,$A9,$87,$55,$88,$55
                                        ; DATA XREF: ROM:off_B08   o
                dc.w sprite_16_24
                dc.w $7B94
                dc.w $9500 ! ((grp_16FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FF00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7F18
                dc.w $9500 ! ((grp_A2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B68
                dc.w $9500 ! ((grp_A2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B48
                dc.w $9500 ! ((grp_A2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7C7C
                dc.w $9500 ! ((grp_1922E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1922E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1922E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8A88
                dc.w $9500 ! ((grp_B0EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C00
                dc.w $9500 ! ((grp_B0F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8138
                dc.w $9500 ! ((grp_E2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8310
                dc.w $9500 ! ((grp_E25A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E25A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E25A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8408
                dc.w $9500 ! ((grp_E25C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E25C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E25C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8640
                dc.w $9500 ! ((grp_E25E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E25E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E25E0 / 2) >> 16)
                dc.w 1
