byte_2E02E8:    dc.b   0,  8,$5C,$49,$90,$81,$76,$65,$86,$59
                                        ; DATA XREF: ROM:off_18B0   o
                dc.w sprite_32_32
                dc.w $6864
                dc.w $9500 ! ((grp_21800 / 2) & $00FF)
                dc.w $9600 ! (((grp_21800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $6544
                dc.w $9500 ! ((grp_63900 / 2) & $00FF)
                dc.w $9600 ! (((grp_63900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8864
                dc.w $9500 ! ((grp_63A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $5548
                dc.w $9500 ! ((grp_A7080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5D4F
                dc.w $9500 ! ((grp_A7100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7D44
                dc.w $9500 ! ((grp_A7180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7547
                dc.w $9500 ! ((grp_1989A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1989A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1989A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $854D
                dc.w $9500 ! ((grp_B9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D47
                dc.w $9500 ! ((grp_EB9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB9C0 / 2) >> 16)
                dc.w 1
