byte_2F2508:    dc.b   0,  3,$72,$4F,$8C,$7A,$7F,$69,$80,$69
                                        ; DATA XREF: ROM:off_2700   o
                dc.w sprite_24_16
                dc.w $7456
                dc.w $9500 ! ((grp_1666C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1666C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1666C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7A66
                dc.w $9500 ! ((grp_17CB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6C5E
                dc.w $9500 ! ((grp_F1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C5E
                dc.w $9500 ! ((grp_F1860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1860 / 2) >> 16)
                dc.w 1
