byte_2CDF14:    dc.b   0,  5,$66,$5B,$93,$80,$7C,$6D,$7D,$6D
                                        ; DATA XREF: ROM:off_9D8   o
                dc.w sprite_32_32
                dc.w $6A61
                dc.w $9500 ! ((grp_12400 / 2) & $00FF)
                dc.w $9600 ! (((grp_12400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12400 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8A61
                dc.w $9500 ! ((grp_A2200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7859
                dc.w $9500 ! ((grp_1838E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1838E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1838E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6262
                dc.w $9500 ! ((grp_B0D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7281
                dc.w $9500 ! ((grp_E23C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E23C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E23C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9267
                dc.w $9500 ! ((grp_E23E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E23E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E23E0 / 2) >> 16)
                dc.w 1
