byte_2D5FBC:    dc.b   0,  7,$70,$60,$97,$8D,$89,$76,$83,$6C
                                        ; DATA XREF: ROM:off_1208   o
                dc.w sprite_32_24
                dc.w $716B
                dc.w $9500 ! ((grp_123F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_123F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $9B78
                dc.w $9500 ! ((grp_172A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_172A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8B7D
                dc.w $9500 ! ((grp_78D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7963
                dc.w $9500 ! ((grp_CBFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $696C
                dc.w $9500 ! ((grp_B3D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D5B
                dc.w $9500 ! ((grp_E64C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E64C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E64C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8383
                dc.w $9500 ! ((grp_E64E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E64E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E64E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A272
                dc.w $9500 ! ((grp_E6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6500 / 2) >> 16)
                dc.w 1
