byte_2CFF92:    dc.b   0,  1,$77,$60,$86,$71,$7E,$68,$7F,$68
                                        ; DATA XREF: ROM:off_CA4   o
                dc.w sprite_16_24
                dc.w $755E
                dc.w $9500 ! ((grp_170BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_170BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8563
                dc.w $9500 ! ((grp_B1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1880 / 2) >> 16)
                dc.w 2
