byte_2F1CB8:    dc.b   0,  4,$78,$66,$8D,$89,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_26C0   o
                dc.w sprite_16_24
                dc.w $787C
                dc.w $9500 ! ((grp_17CD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CD40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7E64
                dc.w $9500 ! ((grp_8BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7674
                dc.w $9500 ! ((grp_18DC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DC60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8886
                dc.w $9500 ! ((grp_F1B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B77
                dc.w $9500 ! ((grp_F1B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1B80 / 2) >> 16)
                dc.w 1
