byte_2F6400:    dc.b   0,$14,$5B,$58,$79,$87,$71,$7B,$72,$7B
                                        ; DATA XREF: ROM:off_2B48   o
                dc.w sprite_32_32
                dc.w $585D
                dc.w $9500 ! ((grp_3DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $587D
                dc.w $9500 ! ((grp_56400 / 2) & $00FF)
                dc.w $9600 ! (((grp_56400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $3C46
                dc.w $9500 ! ((grp_6E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $786B
                dc.w $9500 ! ((grp_6E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4075
                dc.w $9500 ! ((grp_169000 / 2) & $00FF)
                dc.w $9600 ! (((grp_169000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169000 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $542E
                dc.w $9500 ! ((grp_169480 / 2) & $00FF)
                dc.w $9600 ! (((grp_169480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169480 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $306E
                dc.w $9500 ! ((grp_8F480 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $344E
                dc.w $9500 ! ((grp_AD900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6C2E
                dc.w $9500 ! ((grp_18EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EF80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $4F3E
                dc.w $9500 ! ((grp_DD080 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8339
                dc.w $9500 ! ((grp_DD0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3C66
                dc.w $9500 ! ((grp_F4FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $443D
                dc.w $9500 ! ((grp_F4FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4C46
                dc.w $9500 ! ((grp_F4FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5069
                dc.w $9500 ! ((grp_F4B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E55
                dc.w $9500 ! ((grp_F4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F55
                dc.w $9500 ! ((grp_F4AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8878
                dc.w $9500 ! ((grp_F4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $903E
                dc.w $9500 ! ((grp_F5000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $984B
                dc.w $9500 ! ((grp_F5020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F5A
                dc.w $9500 ! ((grp_F5040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5040 / 2) >> 16)
                dc.w 1
