byte_2D3EBA:    dc.b   0,  5,$75,$65,$99,$8F,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_108C   o
                dc.w sprite_24_24
                dc.w $7968
                dc.w $9500 ! ((grp_140A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_140A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140A40 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7280
                dc.w $9500 ! ((grp_48F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $9173
                dc.w $9500 ! ((grp_B31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B31C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $627E
                dc.w $9500 ! ((grp_E5540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A80
                dc.w $9500 ! ((grp_E5560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $997B
                dc.w $9500 ! ((grp_E5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5580 / 2) >> 16)
                dc.w 1
