byte_2F828C:    dc.b   0,  4,$71,$6A,$90,$A0,$80,$8E,$81,$8E
                                        ; DATA XREF: ROM:off_2C58   o
                dc.w sprite_24_24
                dc.w $737F
                dc.w $9500 ! ((grp_151960 / 2) & $00FF)
                dc.w $9600 ! (((grp_151960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151960 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7877
                dc.w $9500 ! ((grp_DDD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B80
                dc.w $9500 ! ((grp_C3640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7897
                dc.w $9500 ! ((grp_C3680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B7F
                dc.w $9500 ! ((grp_C36C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C36C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C36C0 / 2) >> 16)
                dc.w 2
