byte_2CD118:    dc.b   0,  1,$73,$77,$8A,$88,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_878   o
                dc.w sprite_24_24
                dc.w $7575
                dc.w $9500 ! ((grp_13E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E400 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $6D7B
                dc.w $9500 ! ((grp_E2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2240 / 2) >> 16)
                dc.w 1
