byte_2E3C2A:    dc.b   0,  9,$5D,$69,$94,$7C,$C4,$48,$C2,$42
                                        ; DATA XREF: ROM:off_1AFC   o
                dc.w sprite_16_24
                dc.w $6966
                dc.w $9500 ! ((grp_1741C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1741C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1741C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8967
                dc.w $9500 ! ((grp_174100 / 2) & $00FF)
                dc.w $9600 ! (((grp_174100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5963
                dc.w $9500 ! ((grp_7B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7971
                dc.w $9500 ! ((grp_7B580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9963
                dc.w $9500 ! ((grp_7B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B93E
                dc.w $9500 ! ((grp_7B680 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $AD4F
                dc.w $9500 ! ((grp_B5800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A5E
                dc.w $9500 ! ((grp_E8040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A55B
                dc.w $9500 ! ((grp_E8060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B54E
                dc.w $9500 ! ((grp_E8080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8080 / 2) >> 16)
                dc.w 1
