byte_2EF2A8:    dc.b   0,  1,$79,$83,$8A,$8F,$81,$89,$82,$89
                                        ; DATA XREF: ROM:off_24B8   o
                dc.w sprite_24_16
                dc.w $7781
                dc.w $9500 ! ((grp_166000 / 2) & $00FF)
                dc.w $9600 ! (((grp_166000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166000 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7A91
                dc.w $9500 ! ((grp_F1460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1460 / 2) >> 16)
                dc.w 1
