byte_2EE526:    dc.b   0,  1,$7B,$54,$81,$7E,$7E,$69,$7F,$69
                                        ; DATA XREF: ROM:off_239C   o
                dc.w sprite_8_24
                dc.w $7953
                dc.w $9500 ! ((grp_19CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CC00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7F69
                dc.w $9500 ! ((grp_19CC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CC60 / 2) >> 16)
                dc.w 3
