byte_2CBF2C:    dc.b   0,  4,$66,$78,$94,$8C,$7C,$7C,$7D,$7C
                                        ; DATA XREF: ROM:off_6B8   o
                dc.w sprite_32_24
                dc.w $7073
                dc.w $9500 ! ((grp_11E0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $9073
                dc.w $9500 ! ((grp_16F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_16F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16F180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $607B
                dc.w $9500 ! ((grp_72B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_72B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6073
                dc.w $9500 ! ((grp_C6B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5882
                dc.w $9500 ! ((grp_E12C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E12C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E12C0 / 2) >> 16)
                dc.w 1
