byte_2FF3EC:    dc.b   0,  3,$1F,$70,$F3,$90,$87,$7B,$88,$7B
                                        ; DATA XREF: ROM:off_3578   o
                dc.w sprite_32_24
                dc.w $B273
                dc.w $9500 ! ((grp_13C3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $D271
                dc.w $9500 ! ((grp_13C240 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $9275
                dc.w $9500 ! ((grp_5AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5AC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $1D7D
                dc.w $9500 ! ((grp_F9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9200 / 2) >> 16)
                dc.w 1
