byte_2EE382:    dc.b   0,  9,$6A,$6B,$93,$93,$7E,$7E,$7F,$7E
                                        ; DATA XREF: ROM:off_2384   o
                dc.w sprite_32_32
                dc.w $7368
                dc.w $9500 ! ((grp_31C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_31C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $7388
                dc.w $9500 ! ((grp_9DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6B6D
                dc.w $9500 ! ((grp_AB780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7760
                dc.w $9500 ! ((grp_18D2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D2A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9372
                dc.w $9500 ! ((grp_19CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CF00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7090
                dc.w $9500 ! ((grp_D9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $878E
                dc.w $9500 ! ((grp_D93C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D93C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D93C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $637C
                dc.w $9500 ! ((grp_BF400 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B81
                dc.w $9500 ! ((grp_F07E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F07E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F07E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B7A
                dc.w $9500 ! ((grp_F0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0800 / 2) >> 16)
                dc.w 1
