byte_2F274C:    dc.b   0,  2,$77,$62,$8C,$8E,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_2728   o
                dc.w sprite_24_32
                dc.w $7771
                dc.w $9500 ! ((grp_1132C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1132C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1132C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7869
                dc.w $9500 ! ((grp_DA840 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F7C
                dc.w $9500 ! ((grp_F1A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1A40 / 2) >> 16)
                dc.w 1
