byte_2F56B6:    dc.b   0,  8,$6C,$55,$98,$8E,$82,$71,$83,$71
                                        ; DATA XREF: ROM:off_2AC4   o
                dc.w sprite_32_32
                dc.w $6A5B
                dc.w $9500 ! ((grp_3C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $727B
                dc.w $9500 ! ((grp_150AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_150AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150AC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $8A6B
                dc.w $9500 ! ((grp_8EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8253
                dc.w $9500 ! ((grp_DCC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A5B
                dc.w $9500 ! ((grp_DCC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9263
                dc.w $9500 ! ((grp_DCD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A7B
                dc.w $9500 ! ((grp_C1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A7B
                dc.w $9500 ! ((grp_C1F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A63
                dc.w $9500 ! ((grp_F4920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4920 / 2) >> 16)
                dc.w 1
