byte_2F411E:    dc.b   0,  2,$79,$77,$89,$8A,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28DC   o
                dc.w sprite_16_16
                dc.w $777D
                dc.w $9500 ! ((grp_8D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B75
                dc.w $9500 ! ((grp_DC180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $877D
                dc.w $9500 ! ((grp_F3560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3560 / 2) >> 16)
                dc.w 1
