byte_2DCFE8:    dc.b   0,  8,$6C,$62,$85,$85,$77,$73,$72,$60
                                        ; DATA XREF: ROM:off_1688   o
                dc.w sprite_16_32
                dc.w $7163
                dc.w $9500 ! ((grp_60300 / 2) & $00FF)
                dc.w $9600 ! (((grp_60300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5963
                dc.w $9500 ! ((grp_15B2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $615B
                dc.w $9500 ! ((grp_1859E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1859E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1859E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8181
                dc.w $9500 ! ((grp_185980 / 2) & $00FF)
                dc.w $9600 ! (((grp_185980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185980 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8169
                dc.w $9500 ! ((grp_195520 / 2) & $00FF)
                dc.w $9600 ! (((grp_195520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195520 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6583
                dc.w $9500 ! ((grp_CCF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697B
                dc.w $9500 ! ((grp_E7300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8789
                dc.w $9500 ! ((grp_E7340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8969
                dc.w $9500 ! ((grp_E7320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7320 / 2) >> 16)
                dc.w 1
