byte_2D69FA:    dc.b   0,  8,$74,$55,$92,$7A,$80,$4C,$85,$59
                                        ; DATA XREF: ROM:off_1274   o
                dc.w sprite_32_16
                dc.w $5E61
                dc.w $9500 ! ((grp_50700 / 2) & $00FF)
                dc.w $9600 ! (((grp_50700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7E51
                dc.w $9500 ! ((grp_66400 / 2) & $00FF)
                dc.w $9600 ! (((grp_66400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6651
                dc.w $9500 ! ((grp_162C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_162C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9659
                dc.w $9500 ! ((grp_86080 / 2) & $00FF)
                dc.w $9600 ! (((grp_86080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6271
                dc.w $9500 ! ((grp_18AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AF00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7E49
                dc.w $9500 ! ((grp_D6440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6249
                dc.w $9500 ! ((grp_BCA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5665
                dc.w $9500 ! ((grp_EE360 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E63
                dc.w $9500 ! ((grp_EE380 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE380 / 2) >> 16)
                dc.w 1
