byte_2DB246:    dc.b   0,  8,$66,$64,$A0,$8E,$83,$79,$84,$79
                                        ; DATA XREF: ROM:off_153C   o
                dc.w sprite_32_24
                dc.w $6C67
                dc.w $9500 ! ((grp_12D9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C5F
                dc.w $9500 ! ((grp_18A5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A5A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7E7F
                dc.w $9500 ! ((grp_18A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A600 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6466
                dc.w $9500 ! ((grp_19A0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A0E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_D56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D56C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7284
                dc.w $9500 ! ((grp_D5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A87
                dc.w $9500 ! ((grp_D5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9463
                dc.w $9500 ! ((grp_D5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C62
                dc.w $9500 ! ((grp_BC140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC140 / 2) >> 16)
                dc.w 2
