byte_2CD66E:    dc.b   0,  2,$72,$60,$85,$7C,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8F4   o
                dc.w sprite_24_32
                dc.w $6E5E
                dc.w $9500 ! ((grp_F9F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $747E
                dc.w $9500 ! ((grp_73D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_73D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8470
                dc.w $9500 ! ((grp_B0740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0740 / 2) >> 16)
                dc.w 2
