byte_2E3A50:    dc.b   0, $C,$66,$5B,$94,$7D,$CE,$47,$D2,$49
                                        ; DATA XREF: ROM:off_1AF0   o
                dc.w sprite_16_24
                dc.w $706A
                dc.w $9500 ! ((grp_1747C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1747C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1747C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $C83E
                dc.w $9500 ! ((grp_7BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6870
                dc.w $9500 ! ((grp_196120 / 2) & $00FF)
                dc.w $9600 ! (((grp_196120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196120 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $805E
                dc.w $9500 ! ((grp_196180 / 2) & $00FF)
                dc.w $9600 ! (((grp_196180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196180 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $A84E
                dc.w $9500 ! ((grp_CDDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B84A
                dc.w $9500 ! ((grp_CDE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $885D
                dc.w $9500 ! ((grp_B5EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9056
                dc.w $9500 ! ((grp_B5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $984E
                dc.w $9500 ! ((grp_B5F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $607C
                dc.w $9500 ! ((grp_E8480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7082
                dc.w $9500 ! ((grp_E84A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E84A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E84A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7862
                dc.w $9500 ! ((grp_E84C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E84C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E84C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A053
                dc.w $9500 ! ((grp_E84E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E84E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E84E0 / 2) >> 16)
                dc.w 1
