byte_2DF8E2:    dc.b   0,  6,$5F,$5D,$90,$8F,$77,$76,$72,$5F
                                        ; DATA XREF: ROM:off_1834   o
                dc.w sprite_24_24
                dc.w $6C5A
                dc.w $9500 ! ((grp_145FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_145FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145FC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7572
                dc.w $9500 ! ((grp_1460E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1460E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1460E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $5D72
                dc.w $9500 ! ((grp_15F640 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8462
                dc.w $9500 ! ((grp_80E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7389
                dc.w $9500 ! ((grp_9A500 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $645A
                dc.w $9500 ! ((grp_B9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6882
                dc.w $9500 ! ((grp_EB5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB5A0 / 2) >> 16)
                dc.w 1
