byte_2E8CB4:    dc.b   0,  3,$7B,$66,$84,$8E,$7F,$7A,$81,$6C
                                        ; DATA XREF: ROM:off_1DC8   o
                dc.w sprite_16_32
                dc.w $7B6C
                dc.w $9500 ! ((grp_61200 / 2) & $00FF)
                dc.w $9600 ! (((grp_61200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7364
                dc.w $9500 ! ((grp_186BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_186BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186BE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B8C
                dc.w $9500 ! ((grp_CE900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7387
                dc.w $9500 ! ((grp_E8A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8A00 / 2) >> 16)
                dc.w 1
