byte_2EBCD2:    dc.b   0,  9,$84,$5B,$A1,$80,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_2074   o
                dc.w sprite_32_32
                dc.w $6268
                dc.w $9500 ! ((grp_2D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_2D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2D400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8269
                dc.w $9500 ! ((grp_2D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2D600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $A273
                dc.w $9500 ! ((grp_17B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B000 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6388
                dc.w $9500 ! ((grp_9CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8389
                dc.w $9500 ! ((grp_9CF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5A68
                dc.w $9500 ! ((grp_AA780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5270
                dc.w $9500 ! ((grp_19BDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BDC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5388
                dc.w $9500 ! ((grp_D7E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4A73
                dc.w $9500 ! ((grp_BE200 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A26B
                dc.w $9500 ! ((grp_EF760 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF760 / 2) >> 16)
                dc.w 1
