byte_2E2130:    dc.b   0,  9,$75,$36,$8B,$B4,$80,$75,$81,$75
                                        ; DATA XREF: ROM:off_19E8   o
                dc.w sprite_24_32
                dc.w $757C
                dc.w $9500 ! ((grp_1027C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1027C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1027C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $759C
                dc.w $9500 ! ((grp_15C340 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7D44
                dc.w $9500 ! ((grp_173E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_173E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7334
                dc.w $9500 ! ((grp_195BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195BE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $735C
                dc.w $9500 ! ((grp_B5640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $766C
                dc.w $9500 ! ((grp_B5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $83AC
                dc.w $9500 ! ((grp_B56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B56C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $73AC
                dc.w $9500 ! ((grp_E7D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7D40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $815C
                dc.w $9500 ! ((grp_E7D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B3C
                dc.w $9500 ! ((grp_E7D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7D80 / 2) >> 16)
                dc.w 1
