byte_2D4322:    dc.b   0,  3,$68,$64,$87,$90,$79,$74,$7A,$74
                                        ; DATA XREF: ROM:off_10BC   o
                dc.w sprite_32_32
                dc.w $6869
                dc.w $9500 ! ((grp_17600 / 2) & $00FF)
                dc.w $9600 ! (((grp_17600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17600 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_8
                dc.w $6961
                dc.w $9500 ! ((grp_E5360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7761
                dc.w $9500 ! ((grp_E5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $887E
                dc.w $9500 ! ((grp_E53A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E53A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E53A0 / 2) >> 16)
                dc.w 1
