byte_2E951C:    dc.b   0,  8,$4F,$33,$97,$80,$73,$46,$74,$46
                                        ; DATA XREF: ROM:off_1E68   o
                dc.w sprite_32_32
                dc.w $4C35
                dc.w $9500 ! ((grp_27A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $6C34
                dc.w $9500 ! ((grp_66E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8C36
                dc.w $9500 ! ((grp_66F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $4C55
                dc.w $9500 ! ((grp_9C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $843B
                dc.w $9500 ! ((grp_A9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $522D
                dc.w $9500 ! ((grp_18B560 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C3E
                dc.w $9500 ! ((grp_19AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C54
                dc.w $9500 ! ((grp_D6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C56
                dc.w $9500 ! ((grp_EEB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB20 / 2) >> 16)
                dc.w 1
