byte_2E7F4A:    dc.b   0, $A,$76,$62,$8C,$83,$5F,$77,$6D,$44
                                        ; DATA XREF: ROM:off_1D3C   o
                dc.w sprite_24_24
                dc.w $7361
                dc.w $9500 ! ((grp_145900 / 2) & $00FF)
                dc.w $9600 ! (((grp_145900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145900 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7449
                dc.w $9500 ! ((grp_7F680 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E79
                dc.w $9500 ! ((grp_7F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6543
                dc.w $9500 ! ((grp_1884A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1884A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1884A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5F5B
                dc.w $9500 ! ((grp_197920 / 2) & $00FF)
                dc.w $9600 ! (((grp_197920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7359
                dc.w $9500 ! ((grp_D11C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D11C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D11C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B60
                dc.w $9500 ! ((grp_D1140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9363
                dc.w $9500 ! ((grp_D1180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6053
                dc.w $9500 ! ((grp_EA7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA7E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $624B
                dc.w $9500 ! ((grp_EA7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA7C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7679
                dc.w $9500 ! ((grp_EA800 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA800 / 2) >> 16)
                dc.w 1
