byte_2D4EF0:    dc.b   0,  6,$6C,$60,$8A,$7A,$7B,$74,$71,$5E
                                        ; DATA XREF: ROM:off_1150   o
                dc.w sprite_16_32
                dc.w $6C52
                dc.w $9500 ! ((grp_5F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7C72
                dc.w $9500 ! ((grp_5F300 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6455
                dc.w $9500 ! ((grp_1945C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1945C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1945C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C5A
                dc.w $9500 ! ((grp_194560 / 2) & $00FF)
                dc.w $9600 ! (((grp_194560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194560 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7390
                dc.w $9500 ! ((grp_CB380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7472
                dc.w $9500 ! ((grp_B3740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C84
                dc.w $9500 ! ((grp_B3780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3780 / 2) >> 16)
                dc.w 2
