byte_2FD71A:    dc.b   0,  6,$5F,$46,$8B,$8D,$83,$69,$84,$69
                                        ; DATA XREF: ROM:off_3304   o
                dc.w sprite_16_24
                dc.w $7E60
                dc.w $9500 ! ((grp_182500 / 2) & $00FF)
                dc.w $9600 ! (((grp_182500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7946
                dc.w $9500 ! ((grp_94E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_94E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_94E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E78
                dc.w $9500 ! ((grp_95C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_95C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7188
                dc.w $9500 ! ((grp_A1780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A56
                dc.w $9500 ! ((grp_F8760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F5B
                dc.w $9500 ! ((grp_F8780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $813E
                dc.w $9500 ! ((grp_F82A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F82A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F82A0 / 2) >> 16)
                dc.w 1
