byte_2D777E:    dc.b   0,  6,$77,$65,$8F,$99,$86,$76,$7E,$64
                                        ; DATA XREF: ROM:off_12FC   o
                dc.w sprite_32_32
                dc.w $7162
                dc.w $9500 ! ((grp_19200 / 2) & $00FF)
                dc.w $9600 ! (((grp_19200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7182
                dc.w $9500 ! ((grp_49C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7892
                dc.w $9500 ! ((grp_CC1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E5A
                dc.w $9500 ! ((grp_CC180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9162
                dc.w $9500 ! ((grp_B3F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $715A
                dc.w $9500 ! ((grp_E6660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9188
                dc.w $9500 ! ((grp_E6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6680 / 2) >> 16)
                dc.w 1
