byte_2EBB28:    dc.b   0, $A,$84,$5B,$A1,$80,$7E,$7A,$7F,$7A
                                        ; DATA XREF: ROM:off_2068   o
                dc.w sprite_32_32
                dc.w $9465
                dc.w $9500 ! ((grp_2CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2CC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5C65
                dc.w $9500 ! ((grp_110440 / 2) & $00FF)
                dc.w $9600 ! (((grp_110440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110440 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $8485
                dc.w $9500 ! ((grp_51600 / 2) & $00FF)
                dc.w $9600 ! (((grp_51600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $4C6D
                dc.w $9500 ! ((grp_67F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7465
                dc.w $9500 ! ((grp_68100 / 2) & $00FF)
                dc.w $9600 ! (((grp_68100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8465
                dc.w $9500 ! ((grp_68300 / 2) & $00FF)
                dc.w $9600 ! (((grp_68300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6485
                dc.w $9500 ! ((grp_9CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6A8D
                dc.w $9500 ! ((grp_D7D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B473
                dc.w $9500 ! ((grp_BE180 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4483
                dc.w $9500 ! ((grp_EF680 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5C85
                dc.w $9500 ! ((grp_EF6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6A0 / 2) >> 16)
                dc.w 1
