byte_2E7018:    dc.b   0,  5,$74,$53,$92,$78,$7D,$64,$7A,$51
                                        ; DATA XREF: ROM:off_1CB0   o
                dc.w sprite_24_24
                dc.w $694F
                dc.w $9500 ! ((grp_144280 / 2) & $00FF)
                dc.w $9600 ! (((grp_144280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144280 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $746F
                dc.w $9500 ! ((grp_15CB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15CB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15CB80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8157
                dc.w $9500 ! ((grp_15CC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15CC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15CC40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7967
                dc.w $9500 ! ((grp_CEB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $615D
                dc.w $9500 ! ((grp_B67C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B67C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B67C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C73
                dc.w $9500 ! ((grp_E8CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8CA0 / 2) >> 16)
                dc.w 1
