byte_2D8020:    dc.b   0,  5,$73,$5E,$92,$98,$8C,$80,$83,$6C
                                        ; DATA XREF: ROM:off_1358   o
                dc.w sprite_24_24
                dc.w $7A76
                dc.w $9500 ! ((grp_141C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_141C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141C40 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $828E
                dc.w $9500 ! ((grp_49D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8A9E
                dc.w $9500 ! ((grp_CC6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E66
                dc.w $9500 ! ((grp_B41C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B41C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B41C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A5E
                dc.w $9500 ! ((grp_E69C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E69C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E69C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9286
                dc.w $9500 ! ((grp_E69E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E69E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E69E0 / 2) >> 16)
                dc.w 1
