byte_2F31DC:    dc.b   0,  9,$6D,$5F,$8A,$91,$72,$78,$73,$78
                                        ; DATA XREF: ROM:off_2798   o
                dc.w sprite_24_16
                dc.w $7065
                dc.w $9500 ! ((grp_167800 / 2) & $00FF)
                dc.w $9600 ! (((grp_167800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167800 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $737C
                dc.w $9500 ! ((grp_1678C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1678C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1678C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $5865
                dc.w $9500 ! ((grp_18E4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E4A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6F5D
                dc.w $9500 ! ((grp_18E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708C
                dc.w $9500 ! ((grp_DBA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7774
                dc.w $9500 ! ((grp_DBA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $595D
                dc.w $9500 ! ((grp_F2DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $686D
                dc.w $9500 ! ((grp_F2DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B84
                dc.w $9500 ! ((grp_F2DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $886B
                dc.w $9500 ! ((grp_F2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2D80 / 2) >> 16)
                dc.w 1
