byte_2ED438:    dc.b   0,  4,$95,$77,$A0,$87,$87,$82,$88,$82
                                        ; DATA XREF: ROM:off_2298   o
                dc.w sprite_24_24
                dc.w $7B77
                dc.w $9500 ! ((grp_14C080 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C080 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $9374
                dc.w $9500 ! ((grp_17B840 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B840 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $737C
                dc.w $9500 ! ((grp_19C660 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C660 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $808F
                dc.w $9500 ! ((grp_D8AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B81
                dc.w $9500 ! ((grp_BEC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEC40 / 2) >> 16)
                dc.w 2
