byte_2EBDD6:    dc.b   0,  8,$84,$5B,$A1,$80,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:off_207C   o
                dc.w sprite_32_32
                dc.w $5B67
                dc.w $9500 ! ((grp_2DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2DC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7B67
                dc.w $9500 ! ((grp_2DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2DE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9B67
                dc.w $9500 ! ((grp_110BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_110BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $5B87
                dc.w $9500 ! ((grp_9D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7B87
                dc.w $9500 ! ((grp_9D080 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $536F
                dc.w $9500 ! ((grp_AA880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $B373
                dc.w $9500 ! ((grp_BE280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4B81
                dc.w $9500 ! ((grp_EF7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF7A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B87
                dc.w $9500 ! ((grp_EF7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF7C0 / 2) >> 16)
                dc.w 1
