byte_2F15B6:    dc.b   0,  6,$6F,$61,$89,$8E,$7C,$7B,$7D,$7B
                                        ; DATA XREF: ROM:off_2654   o
                dc.w sprite_24_16
                dc.w $7577
                dc.w $9500 ! ((grp_166B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_166B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7667
                dc.w $9500 ! ((grp_8BF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7587
                dc.w $9500 ! ((grp_DAD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $768D
                dc.w $9500 ! ((grp_DADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DADC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7A
                dc.w $9500 ! ((grp_F1F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E68
                dc.w $9500 ! ((grp_F1F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8667
                dc.w $9500 ! ((grp_F1F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1F80 / 2) >> 16)
                dc.w 1
