byte_2FE616:    dc.b   0,  2,$67,$7C,$94,$86,$7D,$81,$7E,$81
                                        ; DATA XREF: ROM:off_33FC   o
                dc.w sprite_24_16
                dc.w $6F7A
                dc.w $9500 ! ((grp_16DC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $877A
                dc.w $9500 ! ((grp_95D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_95D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5F7D
                dc.w $9500 ! ((grp_E05C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E05C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E05C0 / 2) >> 16)
                dc.w 2
