byte_2CC74E:    dc.b   0,  1,$6E,$76,$8A,$83,$80,$83,$81,$83
                                        ; DATA XREF: ROM:off_7B4   o
                dc.w sprite_32_16
                dc.w $6D76
                dc.w $9500 ! ((grp_45F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_45F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_45F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $856E
                dc.w $9500 ! ((grp_E1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1480 / 2) >> 16)
                dc.w 1
