byte_2D44BC:    dc.b   0,  7,$65,$68,$8F,$90,$7B,$7A,$7C,$7A
                                        ; DATA XREF: ROM:off_10D0   o
                dc.w sprite_24_32
                dc.w $7871
                dc.w $9500 ! ((grp_FDCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FDCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FDCC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $637A
                dc.w $9500 ! ((grp_CABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CABC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6882
                dc.w $9500 ! ((grp_CAC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7869
                dc.w $9500 ! ((grp_CAC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $706A
                dc.w $9500 ! ((grp_B3080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686A
                dc.w $9500 ! ((grp_E54E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E54E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E54E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7761
                dc.w $9500 ! ((grp_E5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $907D
                dc.w $9500 ! ((grp_E5520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5520 / 2) >> 16)
                dc.w 1
