byte_2D8D20:    dc.b   0,  5,$67,$5D,$99,$8E,$80,$75,$84,$62
                                        ; DATA XREF: ROM:off_13E0   o
                dc.w sprite_32_24
                dc.w $6D6B
                dc.w $9500 ! ((grp_127B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_127B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7183
                dc.w $9500 ! ((grp_4B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $765B
                dc.w $9500 ! ((grp_15D240 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8D79
                dc.w $9500 ! ((grp_CEBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $656F
                dc.w $9500 ! ((grp_B6900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D71
                dc.w $9500 ! ((grp_E8D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D00 / 2) >> 16)
                dc.w 1
