byte_2EA686:    dc.b   0,  8,$66,$5A,$97,$8D,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_1F4C   o
                dc.w sprite_24_32
                dc.w $7A70
                dc.w $9500 ! ((grp_10F3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7A50
                dc.w $9500 ! ((grp_10F540 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F540 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_A9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A5C
                dc.w $9500 ! ((grp_A9C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7256
                dc.w $9500 ! ((grp_A9C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $925D
                dc.w $9500 ! ((grp_A9D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7276
                dc.w $9500 ! ((grp_19B5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B5E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6A7C
                dc.w $9500 ! ((grp_BDDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $927D
                dc.w $9500 ! ((grp_BDD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDD80 / 2) >> 16)
                dc.w 2
