byte_2DDD4E:    dc.b   0,  3,$77,$6A,$8D,$90,$82,$7D,$85,$6E
                                        ; DATA XREF: ROM:off_171C   o
                dc.w sprite_24_32
                dc.w $7473
                dc.w $9500 ! ((grp_107740 / 2) & $00FF)
                dc.w $9600 ! (((grp_107740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $796B
                dc.w $9500 ! ((grp_D2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D64
                dc.w $9500 ! ((grp_D2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8971
                dc.w $9500 ! ((grp_EB120 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB120 / 2) >> 16)
                dc.w 1
