byte_2EF43A:    dc.b   0,  1,$65,$68,$95,$9E,$7C,$80,$7D,$80
                                        ; DATA XREF: ROM:off_24DC   o
                dc.w sprite_16_16
                dc.w $787E
                dc.w $9500 ! ((grp_8A580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7376
                dc.w $9500 ! ((grp_D99C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D99C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D99C0 / 2) >> 16)
                dc.w 2
