byte_2FC930:    dc.b   0,  1,$74,$7B,$8A,$82,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_3168   o
                dc.w sprite_24_16
                dc.w $7279
                dc.w $9500 ! ((grp_16C9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C9C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8A7D
                dc.w $9500 ! ((grp_F7FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7FC0 / 2) >> 16)
                dc.w 1
