byte_2E492A:    dc.b   0,  5,$6D,$6A,$8F,$99,$7E,$81,$7F,$81
                                        ; DATA XREF: ROM:off_1B54   o
                dc.w sprite_32_16
                dc.w $727C
                dc.w $9500 ! ((grp_4EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7A6C
                dc.w $9500 ! ((grp_160540 / 2) & $00FF)
                dc.w $9600 ! (((grp_160540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160540 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $728C
                dc.w $9500 ! ((grp_189880 / 2) & $00FF)
                dc.w $9600 ! (((grp_189880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189880 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A94
                dc.w $9500 ! ((grp_D3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A7E
                dc.w $9500 ! ((grp_B9EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8764
                dc.w $9500 ! ((grp_EC240 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC240 / 2) >> 16)
                dc.w 1
