byte_2D0A0E:    dc.b   0,  4,$71,$76,$97,$8D,$84,$81,$85,$81
                                        ; DATA XREF: ROM:off_DB4   o
                dc.w sprite_24_24
                dc.w $7678
                dc.w $9500 ! ((grp_13FBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13FBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13FBA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $8470
                dc.w $9500 ! ((grp_C9640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E7C
                dc.w $9500 ! ((grp_B1F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E78
                dc.w $9500 ! ((grp_B1FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9680
                dc.w $9500 ! ((grp_E3BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3BC0 / 2) >> 16)
                dc.w 1
