byte_2E18A0:    dc.b   0,  2,$7C,$61,$94,$8E,$86,$77,$8B,$64
                                        ; DATA XREF: ROM:off_1968   o
                dc.w sprite_32_32
                dc.w $786A
                dc.w $9500 ! ((grp_23400 / 2) & $00FF)
                dc.w $9600 ! (((grp_23400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $855A
                dc.w $9500 ! ((grp_81A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_81A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7089
                dc.w $9500 ! ((grp_9AA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AA80 / 2) >> 16)
                dc.w 4
