byte_2EC79E:    dc.b   0,  3,$73,$5F,$88,$74,$7A,$74,$7B,$74
                                        ; DATA XREF: ROM:off_215C   o
                dc.w sprite_16_16
                dc.w $6A7C
                dc.w $9500 ! ((grp_88900 / 2) & $00FF)
                dc.w $9600 ! (((grp_88900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7564
                dc.w $9500 ! ((grp_19C240 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C240 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7D5E
                dc.w $9500 ! ((grp_19C2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C2A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $855E
                dc.w $9500 ! ((grp_BE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE800 / 2) >> 16)
                dc.w 2
