byte_2D49B0:    dc.b   0,  5,$2C,$6E,$6B,$8E,$4B,$7E,$4C,$7E
                                        ; DATA XREF: ROM:off_1108   o
                dc.w sprite_32_16
                dc.w $2E80
                dc.w $9500 ! ((grp_4C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $4E89
                dc.w $9500 ! ((grp_99800 / 2) & $00FF)
                dc.w $9600 ! (((grp_99800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $3478
                dc.w $9500 ! ((grp_D0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $3870
                dc.w $9500 ! ((grp_D0740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $2978
                dc.w $9500 ! ((grp_B7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4068
                dc.w $9500 ! ((grp_E9DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9DC0 / 2) >> 16)
                dc.w 1
