byte_2CF8A8:    dc.b   0,  2,$78,$78,$86,$86,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_BA8   o
                dc.w sprite_16_16
                dc.w $7679
                dc.w $9500 ! ((grp_74D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_74D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A71
                dc.w $9500 ! ((grp_E2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $867E
                dc.w $9500 ! ((grp_E2DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2DE0 / 2) >> 16)
                dc.w 1
