byte_2D1AC8:    dc.b   0,  5,$70,$6F,$8F,$8F,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_E48   o
                dc.w sprite_16_32
                dc.w $6D6D
                dc.w $9500 ! ((grp_5DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5DC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8573
                dc.w $9500 ! ((grp_5DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5DD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7D6D
                dc.w $9500 ! ((grp_A3D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D8D
                dc.w $9500 ! ((grp_C9980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6586
                dc.w $9500 ! ((grp_E3EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9583
                dc.w $9500 ! ((grp_E3EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3EC0 / 2) >> 16)
                dc.w 1
