byte_2E913C:    dc.b   0,  2,$6A,$44,$74,$8E,$72,$5C,$6F,$4D
                                        ; DATA XREF: ROM:off_1E18   o
                dc.w sprite_8_32
                dc.w $704A
                dc.w $9500 ! ((grp_A6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $683C
                dc.w $9500 ! ((grp_197380 / 2) & $00FF)
                dc.w $9600 ! (((grp_197380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7669
                dc.w $9500 ! ((grp_1973E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1973E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1973E0 / 2) >> 16)
                dc.w 3
