byte_2EB726:    dc.b   0,  4,$71,$55,$8F,$8D,$82,$82,$83,$82
                                        ; DATA XREF: ROM:off_2044   o
                dc.w sprite_32_32
                dc.w $6A6E
                dc.w $9500 ! ((grp_2B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_2B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2B800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8A6E
                dc.w $9500 ! ((grp_67A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6A8E
                dc.w $9500 ! ((grp_9CA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8A8E
                dc.w $9500 ! ((grp_D7C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A76
                dc.w $9500 ! ((grp_EF600 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF600 / 2) >> 16)
                dc.w 1
