byte_2F7F90:    dc.b   0,  4,$7B,$7C,$99,$98,$8A,$8A,$8B,$8A
                                        ; DATA XREF: ROM:off_2BF0   o
                dc.w sprite_8_16
                dc.w $7A7C
                dc.w $9500 ! ((grp_C3140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $928C
                dc.w $9500 ! ((grp_C3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C90
                dc.w $9500 ! ((grp_F5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $827C
                dc.w $9500 ! ((grp_F5840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D8A
                dc.w $9500 ! ((grp_F5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5920 / 2) >> 16)
                dc.w 1
