byte_2F189C:    dc.b   0,  4,$78,$68,$8F,$87,$83,$77,$84,$77
                                        ; DATA XREF: ROM:off_2688   o
                dc.w sprite_24_16
                dc.w $766D
                dc.w $9500 ! ((grp_167380 / 2) & $00FF)
                dc.w $9600 ! (((grp_167380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $787D
                dc.w $9500 ! ((grp_DB740 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D66
                dc.w $9500 ! ((grp_DB780 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7885
                dc.w $9500 ! ((grp_F29E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F29E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F29E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E72
                dc.w $9500 ! ((grp_F2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2A00 / 2) >> 16)
                dc.w 1
