byte_2FE292:    dc.b   0,  3,$73,$77,$89,$8A,$77,$81,$78,$81
                                        ; DATA XREF: ROM:off_33B4   o
                dc.w sprite_16_24
                dc.w $7775
                dc.w $9500 ! ((grp_182800 / 2) & $00FF)
                dc.w $9600 ! (((grp_182800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182800 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8577
                dc.w $9500 ! ((grp_1A0920 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0920 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $637C
                dc.w $9500 ! ((grp_F89C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F89C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F89C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F7B
                dc.w $9500 ! ((grp_F89A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F89A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F89A0 / 2) >> 16)
                dc.w 1
