byte_2DCA26:    dc.b   0,  4,$6F,$4E,$8E,$8F,$7E,$6C,$7F,$4E
                                        ; DATA XREF: ROM:off_1654   o
                dc.w sprite_24_32
                dc.w $7049
                dc.w $9500 ! ((grp_10C540 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C540 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7069
                dc.w $9500 ! ((grp_162580 / 2) & $00FF)
                dc.w $9600 ! (((grp_162580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7979
                dc.w $9500 ! ((grp_178FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_178FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8856
                dc.w $9500 ! ((grp_A8280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6870
                dc.w $9500 ! ((grp_ED7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED7C0 / 2) >> 16)
                dc.w 1
