byte_2CC2DA:    dc.b   0,  1,$82,$82,$98,$98,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_724   o
                dc.w sprite_24_24
                dc.w $8182
                dc.w $9500 ! ((grp_13D440 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D440 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $847A
                dc.w $9500 ! ((grp_E1220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1220 / 2) >> 16)
                dc.w 1
