byte_2D38EA:    dc.b   0,  6,$7F,$5A,$99,$82,$8E,$6E,$8F,$6E
                                        ; DATA XREF: ROM:off_1044   o
                dc.w sprite_32_16
                dc.w $8258
                dc.w $9500 ! ((grp_48800 / 2) & $00FF)
                dc.w $9600 ! (((grp_48800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8768
                dc.w $9500 ! ((grp_76E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A7D
                dc.w $9500 ! ((grp_C9F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8276
                dc.w $9500 ! ((grp_C9F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_B29C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B29C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B29C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7265
                dc.w $9500 ! ((grp_E45A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E45A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E45A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A260
                dc.w $9500 ! ((grp_E45C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E45C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E45C0 / 2) >> 16)
                dc.w 1
