byte_2DA9A8:    dc.b   0,  1,$7D,$76,$84,$84,$80,$7D,$81,$7F
                                        ; DATA XREF: ROM:off_14D8   o
                dc.w sprite_16_16
                dc.w $7B74
                dc.w $9500 ! ((grp_79A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_79A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7D84
                dc.w $9500 ! ((grp_E7120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7120 / 2) >> 16)
                dc.w 1
