byte_2F5C40:    dc.b   0,  8,$75,$4A,$96,$83,$73,$86,$74,$86
                                        ; DATA XREF: ROM:off_2B20   o
                dc.w sprite_32_32
                dc.w $7346
                dc.w $9500 ! ((grp_3E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3E000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7566
                dc.w $9500 ! ((grp_3E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3E200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $644C
                dc.w $9500 ! ((grp_6E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9B48
                dc.w $9500 ! ((grp_17EE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EE40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $9360
                dc.w $9500 ! ((grp_18EF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EF20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D6C
                dc.w $9500 ! ((grp_C2540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB4F
                dc.w $9500 ! ((grp_C2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $713E
                dc.w $9500 ! ((grp_F4D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9358
                dc.w $9500 ! ((grp_F4D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D60 / 2) >> 16)
                dc.w 1
