byte_2CD436:    dc.b   0,  1,$93,$70,$A3,$7F,$8B,$96,$8C,$96
                                        ; DATA XREF: ROM:off_8B4   o
                dc.w sprite_24_16
                dc.w $8E72
                dc.w $9500 ! ((grp_156580 / 2) & $00FF)
                dc.w $9600 ! (((grp_156580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $956A
                dc.w $9500 ! ((grp_C7780 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7780 / 2) >> 16)
                dc.w 2
