byte_2D1348:    dc.b   0,  6,$69,$63,$A0,$8E,$83,$78,$84,$78
                                        ; DATA XREF: ROM:off_E00   o
                dc.w sprite_32_32
                dc.w $6C65
                dc.w $9500 ! ((grp_15200 / 2) & $00FF)
                dc.w $9600 ! (((grp_15200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8C65
                dc.w $9500 ! ((grp_5D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6C85
                dc.w $9500 ! ((grp_157FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_157FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $9C6A
                dc.w $9500 ! ((grp_A3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $646A
                dc.w $9500 ! ((grp_193120 / 2) & $00FF)
                dc.w $9600 ! (((grp_193120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193120 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8C85
                dc.w $9500 ! ((grp_C92C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C92C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C92C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $855D
                dc.w $9500 ! ((grp_E3960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3960 / 2) >> 16)
                dc.w 1
