byte_2FB538:    dc.b   0,  8,$6E,$5A,$95,$7D,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:00002F70   o
                dc.w sprite_24_24
                dc.w $6C60
                dc.w $9500 ! ((grp_154420 / 2) & $00FF)
                dc.w $9600 ! (((grp_154420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154420 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $8458
                dc.w $9500 ! ((grp_180D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_180D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6C78
                dc.w $9500 ! ((grp_190B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_190B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8478
                dc.w $9500 ! ((grp_190BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8470
                dc.w $9500 ! ((grp_190C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_190C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C58
                dc.w $9500 ! ((grp_DF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C58
                dc.w $9500 ! ((grp_F7BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9458
                dc.w $9500 ! ((grp_F7C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9468
                dc.w $9500 ! ((grp_F7BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7BE0 / 2) >> 16)
                dc.w 1
