byte_2E1F8C:    dc.b   0,  2,$74,$64,$8E,$86,$81,$75,$82,$75
                                        ; DATA XREF: ROM:off_19D0   o
                dc.w sprite_32_24
                dc.w $7269
                dc.w $9500 ! ((grp_126040 / 2) & $00FF)
                dc.w $9600 ! (((grp_126040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7581
                dc.w $9500 ! ((grp_186160 / 2) & $00FF)
                dc.w $9600 ! (((grp_186160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186160 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7561
                dc.w $9500 ! ((grp_1861C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1861C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1861C0 / 2) >> 16)
                dc.w 3
