byte_2DF282:    dc.b   0,  6,$6F,$59,$87,$88,$7D,$71,$7F,$63
                                        ; DATA XREF: ROM:off_17EC   o
                dc.w sprite_32_32
                dc.w $6A6C
                dc.w $9500 ! ((grp_1AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1AA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $765C
                dc.w $9500 ! ((grp_7A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8662
                dc.w $9500 ! ((grp_7A880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6664
                dc.w $9500 ! ((grp_CD280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $627F
                dc.w $9500 ! ((grp_E77E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E77E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E77E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C8C
                dc.w $9500 ! ((grp_E7800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E54
                dc.w $9500 ! ((grp_E7820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7820 / 2) >> 16)
                dc.w 1
