byte_2EDA86:    dc.b   0,  6,$64,$66,$99,$95,$7D,$7B,$7E,$7B
                                        ; DATA XREF: ROM:off_22EC   o
                dc.w sprite_32_32
                dc.w $6D6E
                dc.w $9500 ! ((grp_30600 / 2) & $00FF)
                dc.w $9600 ! (((grp_30600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $8566
                dc.w $9500 ! ((grp_18C9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C9A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $656F
                dc.w $9500 ! ((grp_19C480 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C480 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D6E
                dc.w $9500 ! ((grp_19C420 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $818C
                dc.w $9500 ! ((grp_D8780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D73
                dc.w $9500 ! ((grp_EFFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFFA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $957C
                dc.w $9500 ! ((grp_EFFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFFC0 / 2) >> 16)
                dc.w 1
