byte_2E226E:    dc.b   0,  4,$79,$64,$8B,$84,$83,$74,$8B,$58
                                        ; DATA XREF: ROM:off_19F4   o
                dc.w sprite_24_32
                dc.w $7756
                dc.w $9500 ! ((grp_102DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_102DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7276
                dc.w $9500 ! ((grp_15C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7086
                dc.w $9500 ! ((grp_7B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6F56
                dc.w $9500 ! ((grp_E7F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F56
                dc.w $9500 ! ((grp_E7FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7FA0 / 2) >> 16)
                dc.w 1
