byte_2F27BE:    dc.b   0,  3,$71,$5A,$8A,$83,$7D,$73,$7E,$73
                                        ; DATA XREF: ROM:00002734   o
                dc.w sprite_16_32
                dc.w $7762
                dc.w $9500 ! ((grp_6B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $6F6C
                dc.w $9500 ! ((grp_F1A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7782
                dc.w $9500 ! ((grp_F1AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8767
                dc.w $9500 ! ((grp_F1A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1A60 / 2) >> 16)
                dc.w 1
