byte_2EC708:    dc.b   0,  2,$70,$84,$8B,$8F,$7C,$89,$7D,$89
                                        ; DATA XREF: ROM:off_2150   o
                dc.w sprite_32_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_9D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7582
                dc.w $9500 ! ((grp_18C8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C8E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C8F
                dc.w $9500 ! ((grp_EFD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFD80 / 2) >> 16)
                dc.w 1
