byte_2F3A3C:    dc.b   0,  4,$6D,$5D,$93,$8B,$71,$76,$72,$76
                                        ; DATA XREF: ROM:off_27E8   o
                dc.w sprite_24_32
                dc.w $7773
                dc.w $9500 ! ((grp_114640 / 2) & $00FF)
                dc.w $9600 ! (((grp_114640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6E5B
                dc.w $9500 ! ((grp_1360C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1360C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1360C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $4E63
                dc.w $9500 ! ((grp_167680 / 2) & $00FF)
                dc.w $9600 ! (((grp_167680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167680 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $665B
                dc.w $9500 ! ((grp_19DC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DC20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8E6C
                dc.w $9500 ! ((grp_19DBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DBC0 / 2) >> 16)
                dc.w 3
