byte_2E23FA:    dc.b   0,  3,$86,$67,$9F,$7B,$92,$71,$93,$71
                                        ; DATA XREF: ROM:off_1A0C   o
                dc.w sprite_24_16
                dc.w $8A6B
                dc.w $9500 ! ((grp_160300 / 2) & $00FF)
                dc.w $9600 ! (((grp_160300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8D63
                dc.w $9500 ! ((grp_D3040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $826F
                dc.w $9500 ! ((grp_EBF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBF40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7B
                dc.w $9500 ! ((grp_EBF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBF60 / 2) >> 16)
                dc.w 1
