byte_2DAEB8:    dc.b   0,  6,$69,$69,$96,$8E,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_1520   o
                                        ; количество циклов, размер (в чем измеряем?)
                dc.w sprite_24_24
                dc.w $736F
                dc.w $9500 ! ((grp_148600 / 2) & $00FF)
                dc.w $9600 ! (((grp_148600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148600 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $636F
                dc.w $9500 ! ((grp_1792C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1792C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1792C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6B87
                dc.w $9500 ! ((grp_9B580 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B70
                dc.w $9500 ! ((grp_A8780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B8F
                dc.w $9500 ! ((grp_D58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D58C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A67
                dc.w $9500 ! ((grp_D5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9378
                dc.w $9500 ! ((grp_BBE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBE80 / 2) >> 16)
                dc.w 2
