byte_2FB7C2:    dc.b   0,  2,$7A,$62,$83,$8D,$7E,$77,$7F,$77
                                        ; DATA XREF: ROM:off_2F9C   o
                dc.w sprite_16_24
                dc.w $7560
                dc.w $9500 ! ((grp_181000 / 2) & $00FF)
                dc.w $9600 ! (((grp_181000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7A80
                dc.w $9500 ! ((grp_92800 / 2) & $00FF)
                dc.w $9600 ! (((grp_92800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7F78
                dc.w $9500 ! ((grp_F7C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7C40 / 2) >> 16)
                dc.w 1
