byte_2E461E:    dc.b   0,$11,$74,$62,$BD,$8E,$98,$78,$99,$78
                                        ; DATA XREF: ROM:off_1B3C   o
                dc.w sprite_16_24
                dc.w $AA5F
                dc.w $9500 ! ((grp_176BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_176BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8369
                dc.w $9500 ! ((grp_80280 / 2) & $00FF)
                dc.w $9600 ! (((grp_80280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9271
                dc.w $9500 ! ((grp_80480 / 2) & $00FF)
                dc.w $9600 ! (((grp_80480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80480 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $9B7F
                dc.w $9500 ! ((grp_9A100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $A087
                dc.w $9500 ! ((grp_1889E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1889E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1889E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7289
                dc.w $9500 ! ((grp_D1E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B81
                dc.w $9500 ! ((grp_D1EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_D1E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B81
                dc.w $9500 ! ((grp_D2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B63
                dc.w $9500 ! ((grp_B8E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A26F
                dc.w $9500 ! ((grp_B8F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $BA67
                dc.w $9500 ! ((grp_B8E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8279
                dc.w $9500 ! ((grp_EAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAF00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8361
                dc.w $9500 ! ((grp_EAEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAEE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A79
                dc.w $9500 ! ((grp_EAFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAFA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9369
                dc.w $9500 ! ((grp_EAEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAEC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A262
                dc.w $9500 ! ((grp_EAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAF40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AE77
                dc.w $9500 ! ((grp_EAEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAEA0 / 2) >> 16)
                dc.w 1
