byte_2D1274:    dc.b   0,  9,$62,$5E,$9F,$8F,$83,$76,$84,$76
                                        ; DATA XREF: ROM:off_DF8   o
                dc.w sprite_24_24
                dc.w $7061
                dc.w $9500 ! ((grp_13F060 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F060 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7079
                dc.w $9500 ! ((grp_13F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F180 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $6066
                dc.w $9500 ! ((grp_5D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $886A
                dc.w $9500 ! ((grp_171100 / 2) & $00FF)
                dc.w $9600 ! (((grp_171100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9873
                dc.w $9500 ! ((grp_76400 / 2) & $00FF)
                dc.w $9600 ! (((grp_76400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $815A
                dc.w $9500 ! ((grp_C9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8862
                dc.w $9500 ! ((grp_C9240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5876
                dc.w $9500 ! ((grp_B1C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_E3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A876
                dc.w $9500 ! ((grp_E3920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3920 / 2) >> 16)
                dc.w 1
