byte_2F94E2:    dc.b   0,  2,$7D,$79,$85,$8B,$81,$82,$82,$82
                                        ; DATA XREF: ROM:off_2D44   o
                dc.w sprite_8_16
                dc.w $8077
                dc.w $9500 ! ((grp_C40C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C40C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C40C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7879
                dc.w $9500 ! ((grp_F67A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F67A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F67A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F87
                dc.w $9500 ! ((grp_F6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6780 / 2) >> 16)
                dc.w 1
