byte_2D30B6:    dc.b   0,  6,$6A,$66,$9A,$8B,$82,$78,$83,$78
                                        ; DATA XREF: ROM:off_F54   o
                dc.w sprite_16_32
                dc.w $8964
                dc.w $9500 ! ((grp_5E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7966
                dc.w $9500 ! ((grp_172000 / 2) & $00FF)
                dc.w $9600 ! (((grp_172000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $696E
                dc.w $9500 ! ((grp_77600 / 2) & $00FF)
                dc.w $9600 ! (((grp_77600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6686
                dc.w $9500 ! ((grp_97E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $797E
                dc.w $9500 ! ((grp_CA580 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9970
                dc.w $9500 ! ((grp_B2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $717E
                dc.w $9500 ! ((grp_E4E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4E80 / 2) >> 16)
                dc.w 1
