byte_2E6956:    dc.b   0, $A,$6F,$62,$88,$8E,$84,$73,$78,$62
                                        ; DATA XREF: ROM:off_1C6C   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8261
                dc.w $9500 ! ((grp_161140 / 2) & $00FF)
                dc.w $9600 ! (((grp_161140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_83580 / 2) & $00FF)
                dc.w $9600 ! (((grp_83580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7755
                dc.w $9500 ! ((grp_D3D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8271
                dc.w $9500 ! ((grp_D3DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_BACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BACC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A66
                dc.w $9500 ! ((grp_EC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A5E
                dc.w $9500 ! ((grp_E59A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E59A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E59A0 / 2) >> 16)
                dc.w 1
