byte_2FD0EE:    dc.b   0,  2,$74,$78,$88,$87,$7E,$7F,$7F,$7F
                                        ; DATA XREF: ROM:off_329C   o
                dc.w sprite_24_8
                dc.w $7276
                dc.w $9500 ! ((grp_190E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_190E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $737E
                dc.w $9500 ! ((grp_190EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190EA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8286
                dc.w $9500 ! ((grp_F8120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8120 / 2) >> 16)
                dc.w 1
