byte_2DA33C:    dc.b   0,  5,$86,$67,$8F,$77,$7F,$6B,$80,$6B
                                        ; DATA XREF: ROM:off_1490   o
                dc.w sprite_16_16
                dc.w $8069
                dc.w $9500 ! ((grp_79880 / 2) & $00FF)
                dc.w $9600 ! (((grp_79880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7253
                dc.w $9500 ! ((grp_98780 / 2) & $00FF)
                dc.w $9600 ! (((grp_98780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A53
                dc.w $9500 ! ((grp_A4E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8C79
                dc.w $9500 ! ((grp_195040 / 2) & $00FF)
                dc.w $9600 ! (((grp_195040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195040 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B5B
                dc.w $9500 ! ((grp_B47C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B47C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B47C0 / 2) >> 16)
                dc.w 2
