byte_2E7722:    dc.b   0, $A,$6F,$72,$8E,$8F,$C2,$AE,$B9,$9D
                                        ; DATA XREF: ROM:off_1CF4   o
                dc.w sprite_24_32
                dc.w $7C72
                dc.w $9500 ! ((grp_1054C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1054C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1054C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6C72
                dc.w $9500 ! ((grp_7F300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9C7F
                dc.w $9500 ! ((grp_7F280 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $B491
                dc.w $9500 ! ((grp_197620 / 2) & $00FF)
                dc.w $9600 ! (((grp_197620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197620 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8A
                dc.w $9500 ! ((grp_D0A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $C4AF
                dc.w $9500 ! ((grp_D0A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $947B
                dc.w $9500 ! ((grp_B7FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AC8C
                dc.w $9500 ! ((grp_B7F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $BCA1
                dc.w $9500 ! ((grp_B8000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A48F
                dc.w $9500 ! ((grp_EA220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $CAA7
                dc.w $9500 ! ((grp_EA240 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA240 / 2) >> 16)
                dc.w 1
