byte_2ED8D4:    dc.b   0,  5,$68,$63,$91,$95,$7B,$7A,$7C,$7A
                                        ; DATA XREF: ROM:off_22D8   o
                dc.w sprite_32_24
                dc.w $656C
                dc.w $9500 ! ((grp_132340 / 2) & $00FF)
                dc.w $9600 ! (((grp_132340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6784
                dc.w $9500 ! ((grp_89580 / 2) & $00FF)
                dc.w $9600 ! (((grp_89580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7F84
                dc.w $9500 ! ((grp_89600 / 2) & $00FF)
                dc.w $9600 ! (((grp_89600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6B64
                dc.w $9500 ! ((grp_9DA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7784
                dc.w $9500 ! ((grp_F0320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F87
                dc.w $9500 ! ((grp_F0340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0340 / 2) >> 16)
                dc.w 1
