byte_2F19B2:    dc.b   0,  2,$75,$72,$8B,$8F,$80,$83,$81,$83
                                        ; DATA XREF: ROM:off_269C   o
                dc.w sprite_24_24
                dc.w $7679
                dc.w $9500 ! ((grp_14E5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E5A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $6E85
                dc.w $9500 ! ((grp_F1FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F71
                dc.w $9500 ! ((grp_F1FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1FE0 / 2) >> 16)
                dc.w 1
