byte_2FE73E:    dc.b   0,  2,$74,$84,$85,$91,$7C,$8B,$7D,$8B
                                        ; DATA XREF: ROM:off_341C   o
                dc.w sprite_16_8
                dc.w $7489
                dc.w $9500 ! ((grp_E0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B81
                dc.w $9500 ! ((grp_E0640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7091
                dc.w $9500 ! ((grp_F8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8C80 / 2) >> 16)
                dc.w 1
