byte_2E025C:    dc.b   0,  3,$68,$52,$8E,$87,$7B,$6C,$7A,$58
                                        ; DATA XREF: ROM:off_18A8   o
                dc.w sprite_32_32
                dc.w $6550
                dc.w $9500 ! ((grp_21400 / 2) & $00FF)
                dc.w $9600 ! (((grp_21400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6570
                dc.w $9500 ! ((grp_12AFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12AFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12AFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8568
                dc.w $9500 ! ((grp_63800 / 2) & $00FF)
                dc.w $9600 ! (((grp_63800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $6D88
                dc.w $9500 ! ((grp_EB980 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB980 / 2) >> 16)
                dc.w 1
