byte_2FE51C:    dc.b   0,  3,$97,$7F,$D1,$92,$8F,$88,$90,$88
                                        ; DATA XREF: ROM:off_33E0   o
                dc.w sprite_32_32
                dc.w $717A
                dc.w $9500 ! ((grp_44C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_44C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $997F
                dc.w $9500 ! ((grp_182680 / 2) & $00FF)
                dc.w $9600 ! (((grp_182680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182680 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $9181
                dc.w $9500 ! ((grp_C6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A980
                dc.w $9500 ! ((grp_C60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C60C0 / 2) >> 16)
                dc.w 2
