byte_2EAF8E:    dc.b   0,  5,$86,$61,$9F,$78,$86,$6B,$87,$6B
                                        ; DATA XREF: ROM:off_1FCC   o
                dc.w sprite_16_16
                dc.w $6E57
                dc.w $9500 ! ((grp_87000 / 2) & $00FF)
                dc.w $9600 ! (((grp_87000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D76
                dc.w $9500 ! ((grp_87080 / 2) & $00FF)
                dc.w $9600 ! (((grp_87080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E67
                dc.w $9500 ! ((grp_87180 / 2) & $00FF)
                dc.w $9600 ! (((grp_87180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7E5F
                dc.w $9500 ! ((grp_9C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7E67
                dc.w $9500 ! ((grp_D77C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D77C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D77C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9E69
                dc.w $9500 ! ((grp_EF260 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF260 / 2) >> 16)
                dc.w 1
