byte_2E04CC:    dc.b   0,  8,$4D,$50,$93,$85,$70,$6A,$83,$57
                                        ; DATA XREF: ROM:off_18C0   o
                dc.w sprite_32_32
                dc.w $664E
                dc.w $9500 ! ((grp_21E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_21E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $666E
                dc.w $9500 ! ((grp_12B740 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $864E
                dc.w $9500 ! ((grp_63D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $866E
                dc.w $9500 ! ((grp_1771C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1771C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1771C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4E4E
                dc.w $9500 ! ((grp_81500 / 2) & $00FF)
                dc.w $9600 ! (((grp_81500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5E56
                dc.w $9500 ! ((grp_198A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_198A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198A60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $4656
                dc.w $9500 ! ((grp_EBAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBAE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $565E
                dc.w $9500 ! ((grp_EBB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBB00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7286
                dc.w $9500 ! ((grp_EBB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBB20 / 2) >> 16)
                dc.w 1
