byte_2E9DCE:    dc.b   0,  3,$6A,$6F,$94,$8F,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_1ED4   o
                dc.w sprite_32_24
                dc.w $707A
                dc.w $9500 ! ((grp_12F640 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F640 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $9072
                dc.w $9500 ! ((grp_19B0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B0A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $687E
                dc.w $9500 ! ((grp_BD7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $886A
                dc.w $9500 ! ((grp_BD800 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD800 / 2) >> 16)
                dc.w 2
