byte_2DFE10:    dc.b   0,  6,$6D,$55,$9E,$8E,$85,$71,$8B,$61
                                        ; DATA XREF: ROM:off_1870   o
                dc.w sprite_32_32
                dc.w $7471
                dc.w $9500 ! ((grp_1FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1FC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7959
                dc.w $9500 ! ((grp_12A9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6C71
                dc.w $9500 ! ((grp_A6E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6969
                dc.w $9500 ! ((grp_D2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E51
                dc.w $9500 ! ((grp_D2A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $995B
                dc.w $9500 ! ((grp_B95C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B95C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B95C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7161
                dc.w $9500 ! ((grp_EB7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB7E0 / 2) >> 16)
                dc.w 1
