byte_2FB464:    dc.b   0,  6,$6E,$5A,$95,$7D,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_2F68   o
                dc.w sprite_24_32
                dc.w $6C60
                dc.w $9500 ! ((grp_11C8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11C8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11C8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8458
                dc.w $9500 ! ((grp_180DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_180DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $8470
                dc.w $9500 ! ((grp_190C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_190C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8478
                dc.w $9500 ! ((grp_190BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9458
                dc.w $9500 ! ((grp_19FF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FF60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C58
                dc.w $9500 ! ((grp_DF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C58
                dc.w $9500 ! ((grp_F7C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7C20 / 2) >> 16)
                dc.w 1
