byte_2F483A:    dc.b   0,  2,$6D,$73,$93,$87,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_29EC   o
                dc.w sprite_32_24
                dc.w $7071
                dc.w $9500 ! ((grp_136FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_136FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $9073
                dc.w $9500 ! ((grp_19E340 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E340 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6880
                dc.w $9500 ! ((grp_F3C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3C20 / 2) >> 16)
                dc.w 1
