byte_2E1442:    dc.b   0,  7,$71,$58,$93,$8F,$81,$72,$82,$72
                                        ; DATA XREF: ROM:off_193C   o
                dc.w sprite_32_24
                dc.w $785A
                dc.w $9500 ! ((grp_12E740 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7972
                dc.w $9500 ! ((grp_179D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_179D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $718A
                dc.w $9500 ! ((grp_9BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $605D
                dc.w $9500 ! ((grp_18ADE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18ADE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18ADE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6255
                dc.w $9500 ! ((grp_D6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9859
                dc.w $9500 ! ((grp_BC8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7065
                dc.w $9500 ! ((grp_EE260 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A05D
                dc.w $9500 ! ((grp_EE280 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE280 / 2) >> 16)
                dc.w 1
