byte_2CD6CA:    dc.b   0,  2,$6E,$5C,$84,$79,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8FC   o
                dc.w sprite_32_24
                dc.w $6A60
                dc.w $9500 ! ((grp_11EFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11EFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11EFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C58
                dc.w $9500 ! ((grp_1833A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1833A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1833A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7278
                dc.w $9500 ! ((grp_183400 / 2) & $00FF)
                dc.w $9600 ! (((grp_183400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183400 / 2) >> 16)
                dc.w 3
