byte_2E4302:    dc.b   0,  8,$67,$5F,$B1,$8E,$8C,$76,$8D,$76
                                        ; DATA XREF: ROM:off_1B2C   o
                dc.w sprite_32_24
                dc.w $7A75
                dc.w $9500 ! ((grp_129AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_129AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7A5D
                dc.w $9500 ! ((grp_129C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_129C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $9A7A
                dc.w $9500 ! ((grp_15F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6269
                dc.w $9500 ! ((grp_80300 / 2) & $00FF)
                dc.w $9600 ! (((grp_80300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7275
                dc.w $9500 ! ((grp_197F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_197F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D8D
                dc.w $9500 ! ((grp_D1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858D
                dc.w $9500 ! ((grp_D1F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7265
                dc.w $9500 ! ((grp_B8E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $B27A
                dc.w $9500 ! ((grp_EAF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAF20 / 2) >> 16)
                dc.w 1
