byte_2F277A:    dc.b   0,  1,$7A,$68,$8B,$8E,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_272C   o
                dc.w sprite_24_24
                dc.w $7779
                dc.w $9500 ! ((grp_14E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E000 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7871
                dc.w $9500 ! ((grp_DA880 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA880 / 2) >> 16)
                dc.w 2
