byte_2F4A10:    dc.b   0,  7,$6A,$6A,$9F,$93,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_2A00   o
                dc.w sprite_16_32
                dc.w $6D75
                dc.w $9500 ! ((grp_6D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7D70
                dc.w $9500 ! ((grp_1681C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1681C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1681C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7D80
                dc.w $9500 ! ((grp_17E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8068
                dc.w $9500 ! ((grp_DC380 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D88
                dc.w $9500 ! ((grp_DC340 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9578
                dc.w $9500 ! ((grp_C1840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6586
                dc.w $9500 ! ((grp_F3BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D90
                dc.w $9500 ! ((grp_F3C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3C00 / 2) >> 16)
                dc.w 1
psy_crow:       dc.b   0,  9,$66,$68,$90,$8D,$82,$7A,$83,$7A
                                        ; DATA XREF: ROM:off_2A04   o
                dc.w sprite_32_32
                dc.w $7163
                dc.w $9500 ! ((grp_3C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $6172
                dc.w $9500 ! ((grp_17E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7183
                dc.w $9500 ! ((grp_8E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9173
                dc.w $9500 ! ((grp_8E980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $597A
                dc.w $9500 ! ((grp_C1C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9163
                dc.w $9500 ! ((grp_C1C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A17E
                dc.w $9500 ! ((grp_C1C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $698A
                dc.w $9500 ! ((grp_F4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8183
                dc.w $9500 ! ((grp_F44A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F44A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F44A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A983
                dc.w $9500 ! ((grp_F44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F44C0 / 2) >> 16)
                dc.w 1
