byte_2D673A:    dc.b   0,  3,$72,$4B,$90,$81,$7B,$66,$7C,$66
                                        ; DATA XREF: ROM:off_1254   o
                dc.w sprite_32_32
                dc.w $7249
                dc.w $9500 ! ((grp_24600 / 2) & $00FF)
                dc.w $9600 ! (((grp_24600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7469
                dc.w $9500 ! ((grp_12CAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12CAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12CAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6460
                dc.w $9500 ! ((grp_83F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7881
                dc.w $9500 ! ((grp_D4680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4680 / 2) >> 16)
                dc.w 2
