byte_2CEE12:    dc.b   0,  4,$71,$68,$8F,$82,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_B2C   o
                dc.w sprite_32_32
                dc.w $6F6E
                dc.w $9500 ! ((grp_12800 / 2) & $00FF)
                dc.w $9600 ! (((grp_12800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7366
                dc.w $9500 ! ((grp_183A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_183A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F78
                dc.w $9500 ! ((grp_B1300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_E2820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $878E
                dc.w $9500 ! ((grp_E2840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2840 / 2) >> 16)
                dc.w 1
