byte_2E5F6A:    dc.b   0,  8,$6D,$67,$8B,$8F,$4D,$9C,$84,$6A
                                        ; DATA XREF: ROM:off_1C1C   o
                dc.w sprite_24_16
                dc.w $6F83
                dc.w $9500 ! ((grp_160D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_160D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8771
                dc.w $9500 ! ((grp_160E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_160E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6F63
                dc.w $9500 ! ((grp_178000 / 2) & $00FF)
                dc.w $9600 ! (((grp_178000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6F7B
                dc.w $9500 ! ((grp_D3AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $676B
                dc.w $9500 ! ((grp_BA840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F73
                dc.w $9500 ! ((grp_BA980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F63
                dc.w $9500 ! ((grp_BA9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $878B
                dc.w $9500 ! ((grp_EC760 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9581
                dc.w $9500 ! ((grp_EC780 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC780 / 2) >> 16)
                dc.w 1
