byte_2EE5A4:    dc.b   0,  2,$7A,$62,$84,$9D,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_23A8   o
                dc.w sprite_16_32
                dc.w $7878
                dc.w $9500 ! ((grp_69400 / 2) & $00FF)
                dc.w $9600 ! (((grp_69400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_69400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7860
                dc.w $9500 ! ((grp_17BFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BFC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7898
                dc.w $9500 ! ((grp_D9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9480 / 2) >> 16)
                dc.w 2
