byte_2DB820:    dc.b   0,  3,$6C,$6A,$86,$8D,$79,$7B,$78,$6B
                                        ; DATA XREF: ROM:off_1570   o
                dc.w sprite_24_24
                dc.w $767C
                dc.w $9500 ! ((grp_1428A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1428A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1428A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $776C
                dc.w $9500 ! ((grp_7D280 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6F6D
                dc.w $9500 ! ((grp_1953A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1953A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1953A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8774
                dc.w $9500 ! ((grp_E71A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E71A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E71A0 / 2) >> 16)
                dc.w 1
