byte_2DB7AA:    dc.b   0,  8,$70,$61,$8E,$8F,$7F,$78,$80,$78
                                        ; DATA XREF: ROM:off_156C   o
                dc.w sprite_32_16
                dc.w $6E6F
                dc.w $9500 ! ((grp_50100 / 2) & $00FF)
                dc.w $9600 ! (((grp_50100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $707F
                dc.w $9500 ! ((grp_18AAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AAE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $735F
                dc.w $9500 ! ((grp_18AB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AB40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7867
                dc.w $9500 ! ((grp_D6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7387
                dc.w $9500 ! ((grp_BC440 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8487
                dc.w $9500 ! ((grp_BC480 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_EDF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDF20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C8C
                dc.w $9500 ! ((grp_EDF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDF40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E74
                dc.w $9500 ! ((grp_EDF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDF60 / 2) >> 16)
                dc.w 1
