byte_2CC646:    dc.b   0,  2,$79,$68,$8D,$75,$83,$7D,$84,$7D
                                        ; DATA XREF: ROM:off_79C   o
                dc.w sprite_16_16
                dc.w $7867
                dc.w $9500 ! ((grp_72C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_72C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8868
                dc.w $9500 ! ((grp_AFFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $706E
                dc.w $9500 ! ((grp_E13A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E13A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E13A0 / 2) >> 16)
                dc.w 1
