byte_2E29F4:    dc.b   0, $B,$64,$62,$A3,$8D,$83,$77,$84,$77
                                        ; DATA XREF: ROM:off_1A48   o
                dc.w sprite_16_16
                dc.w $8170
                dc.w $9500 ! ((grp_81D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_81D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9170
                dc.w $9500 ! ((grp_81F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_81F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6580
                dc.w $9500 ! ((grp_189700 / 2) & $00FF)
                dc.w $9600 ! (((grp_189700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189700 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6978
                dc.w $9500 ! ((grp_189760 / 2) & $00FF)
                dc.w $9600 ! (((grp_189760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189760 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7B68
                dc.w $9500 ! ((grp_1897C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1897C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1897C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8E80
                dc.w $9500 ! ((grp_1896A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1896A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1896A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7170
                dc.w $9500 ! ((grp_D31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D31C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7588
                dc.w $9500 ! ((grp_D3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8260
                dc.w $9500 ! ((grp_D3240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9488
                dc.w $9500 ! ((grp_D3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6288
                dc.w $9500 ! ((grp_EC0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC0E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9768
                dc.w $9500 ! ((grp_EC000 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC000 / 2) >> 16)
                dc.w 1
