byte_2D4164:    dc.b   0,  5,$69,$68,$8F,$90,$7C,$7B,$7D,$7B
                                        ; DATA XREF: ROM:off_10A8   o
                dc.w sprite_32_24
                dc.w $6D72
                dc.w $9500 ! ((grp_122EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_122EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $666A
                dc.w $9500 ! ((grp_98100 / 2) & $00FF)
                dc.w $9600 ! (((grp_98100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $758A
                dc.w $9500 ! ((grp_184C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_184C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184C60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6578
                dc.w $9500 ! ((grp_E5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7262
                dc.w $9500 ! ((grp_E5220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7D
                dc.w $9500 ! ((grp_E5240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5240 / 2) >> 16)
                dc.w 1
