byte_2E8D9C:    dc.b   0,  4,$77,$5A,$83,$7F,$7D,$6A,$83,$5F
                                        ; DATA XREF: ROM:off_1DD8   o
                dc.w sprite_16_32
                dc.w $7855
                dc.w $9500 ! ((grp_61400 / 2) & $00FF)
                dc.w $9600 ! (((grp_61400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7575
                dc.w $9500 ! ((grp_CE980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7063
                dc.w $9500 ! ((grp_B65C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B65C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B65C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $777D
                dc.w $9500 ! ((grp_E8B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $794D
                dc.w $9500 ! ((grp_E8B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8B20 / 2) >> 16)
                dc.w 1
