byte_2E41B8:    dc.b   0,  7,$66,$3A,$90,$62,$B0,$46,$B3,$3C
                                        ; DATA XREF: ROM:off_1B20   o
                dc.w sprite_24_32
                dc.w $7333
                dc.w $9500 ! ((grp_1030C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1030C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1030C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8B41
                dc.w $9500 ! ((grp_60E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6B4D
                dc.w $9500 ! ((grp_174640 / 2) & $00FF)
                dc.w $9600 ! (((grp_174640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174640 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $AE31
                dc.w $9500 ! ((grp_A5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9B2B
                dc.w $9500 ! ((grp_186520 / 2) & $00FF)
                dc.w $9600 ! (((grp_186520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $634B
                dc.w $9500 ! ((grp_1960C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1960C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1960C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B2C
                dc.w $9500 ! ((grp_B5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $932D
                dc.w $9500 ! ((grp_E83C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E83C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E83C0 / 2) >> 16)
                dc.w 1
