byte_2EA3A2:    dc.b   0,  5,$67,$68,$96,$92,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F2C   o
                dc.w sprite_32_32
                dc.w $6669
                dc.w $9500 ! ((grp_28E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_28E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8669
                dc.w $9500 ! ((grp_67600 / 2) & $00FF)
                dc.w $9600 ! (((grp_67600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6589
                dc.w $9500 ! ((grp_9C480 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8589
                dc.w $9500 ! ((grp_18B920 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B920 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A61
                dc.w $9500 ! ((grp_EEFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEFC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7991
                dc.w $9500 ! ((grp_EEFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEFE0 / 2) >> 16)
                dc.w 1
