word_2DAF16:    dc.w    $A              ; DATA XREF: ROM:off_1524   o
                dc.w $6561
                dc.w $9F8E
                dc.w $8277
                dc.w $8377
                dc.w sprite_16_32
                dc.w $7361
                dc.w $9500 ! ((grp_65C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $636C
                dc.w $9500 ! ((grp_179380 / 2) & $00FF)
                dc.w $9600 ! (((grp_179380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179380 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8378
                dc.w $9500 ! ((grp_19A080 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A080 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A5E
                dc.w $9500 ! ((grp_D5940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_D5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7381
                dc.w $9500 ! ((grp_BBEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8368
                dc.w $9500 ! ((grp_BBF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A6F
                dc.w $9500 ! ((grp_BBF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBF40 / 2) >> 16)
                dc.b   0
                dc.b   2
                dc.w sprite_8_8
                dc.w $6B89
                dc.w $9500 ! ((grp_EDB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDB20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B81
                dc.w $9500 ! ((grp_EDB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDB40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B88
                dc.w $9500 ! ((grp_EDB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDB60 / 2) >> 16)
                dc.w 1
