byte_2FA736:    dc.b   0, $A,$74,$6D,$AD,$8F,$99,$75,$9A,$75
                                        ; DATA XREF: ROM:off_2E1C   o
                dc.w sprite_32_32
                dc.w $6D6B
                dc.w $9500 ! ((grp_41200 / 2) & $00FF)
                dc.w $9600 ! (((grp_41200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $9D5B
                dc.w $9500 ! ((grp_13A8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13A8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13A8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $8D73
                dc.w $9500 ! ((grp_57600 / 2) & $00FF)
                dc.w $9600 ! (((grp_57600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8D53
                dc.w $9500 ! ((grp_70300 / 2) & $00FF)
                dc.w $9600 ! (((grp_70300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6D8B
                dc.w $9500 ! ((grp_A0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D83
                dc.w $9500 ! ((grp_DE880 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A583
                dc.w $9500 ! ((grp_DE8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $855B
                dc.w $9500 ! ((grp_C46C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C46C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C46C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AD73
                dc.w $9500 ! ((grp_C4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D8B
                dc.w $9500 ! ((grp_F6DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BD6B
                dc.w $9500 ! ((grp_F7060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7060 / 2) >> 16)
                dc.w 1
