byte_2EA4B0:    dc.b   0,  6,$67,$5B,$98,$8D,$7F,$74,$80,$74
                                        ; DATA XREF: ROM:off_1F38   o
                dc.w sprite_32_32
                dc.w $6F58
                dc.w $9500 ! ((grp_29400 / 2) & $00FF)
                dc.w $9600 ! (((grp_29400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_29400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6278
                dc.w $9500 ! ((grp_130240 / 2) & $00FF)
                dc.w $9600 ! (((grp_130240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_130240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8278
                dc.w $9500 ! ((grp_149A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_149A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149A40 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $8F60
                dc.w $9500 ! ((grp_17A580 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A580 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7850
                dc.w $9500 ! ((grp_18B9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B9E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6760
                dc.w $9500 ! ((grp_19B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B400 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8F58
                dc.w $9500 ! ((grp_EF060 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF060 / 2) >> 16)
                dc.w 1
