byte_2D71CE:    dc.b   0,  5,$74,$55,$92,$7A,$83,$50,$8B,$57
                                        ; DATA XREF: ROM:off_12BC   o
                dc.w sprite_32_32
                dc.w $6F49
                dc.w $9500 ! ((grp_27600 / 2) & $00FF)
                dc.w $9600 ! (((grp_27600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $8F55
                dc.w $9500 ! ((grp_162F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_162F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6D69
                dc.w $9500 ! ((grp_9BE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5F66
                dc.w $9500 ! ((grp_D6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6749
                dc.w $9500 ! ((grp_BD100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5769
                dc.w $9500 ! ((grp_EE740 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE740 / 2) >> 16)
                dc.w 1
