byte_2D5204:    dc.b   0,  3,$6F,$6A,$8E,$8F,$7F,$7B,$7D,$72
                                        ; DATA XREF: ROM:off_1170   o
                dc.w sprite_24_32
                dc.w $6D66
                dc.w $9500 ! ((grp_FE440 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE440 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D86
                dc.w $9500 ! ((grp_49900 / 2) & $00FF)
                dc.w $9600 ! (((grp_49900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8D8C
                dc.w $9500 ! ((grp_CB640 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6570
                dc.w $9500 ! ((grp_B38C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B38C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B38C0 / 2) >> 16)
                dc.w 2
