byte_2EEE78:    dc.b   0,  7,$64,$76,$9D,$8C,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_2430   o
                dc.w sprite_24_16
                dc.w $5B82
                dc.w $9500 ! ((grp_165340 / 2) & $00FF)
                dc.w $9600 ! (((grp_165340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165340 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7382
                dc.w $9500 ! ((grp_165400 / 2) & $00FF)
                dc.w $9600 ! (((grp_165400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9B7E
                dc.w $9500 ! ((grp_17C2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8B7F
                dc.w $9500 ! ((grp_8A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5382
                dc.w $9500 ! ((grp_F0B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E67
                dc.w $9500 ! ((grp_F0BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E7A
                dc.w $9500 ! ((grp_F0B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AB84
                dc.w $9500 ! ((grp_F0B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0B40 / 2) >> 16)
                dc.w 1
