byte_2E2C20:    dc.b   0,  8,$6F,$47,$8E,$8F,$81,$66,$78,$47
                                        ; DATA XREF: ROM:off_1A58   o
                dc.w sprite_24_32
                dc.w $6F46
                dc.w $9500 ! ((grp_105F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_105F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7066
                dc.w $9500 ! ((grp_15F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7C76
                dc.w $9500 ! ((grp_7FB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8866
                dc.w $9500 ! ((grp_7FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7986
                dc.w $9500 ! ((grp_188680 / 2) & $00FF)
                dc.w $9600 ! (((grp_188680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188680 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A6F
                dc.w $9500 ! ((grp_EAA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAA60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7489
                dc.w $9500 ! ((grp_EAA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAA80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $875E
                dc.w $9500 ! ((grp_EAAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAAA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C8A
                dc.w $9500 ! ((grp_EAAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAAC0 / 2) >> 16)
                dc.w 1
