byte_2CC414:    dc.b   0,  1,$82,$82,$9F,$93,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_750   o
                dc.w sprite_24_24
                dc.w $8880
                dc.w $9500 ! ((grp_13D0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D0E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $8080
                dc.w $9500 ! ((grp_AFD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFD00 / 2) >> 16)
                dc.w 2
