byte_2F325E:    dc.b   0,  6,$6C,$5F,$8C,$92,$73,$78,$74,$78
                                        ; DATA XREF: ROM:off_279C   o
                dc.w sprite_24_32
                dc.w $7175
                dc.w $9500 ! ((grp_114C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_114C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6765
                dc.w $9500 ! ((grp_167980 / 2) & $00FF)
                dc.w $9600 ! (((grp_167980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7F65
                dc.w $9500 ! ((grp_8CE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $755D
                dc.w $9500 ! ((grp_18E560 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E560 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $576B
                dc.w $9500 ! ((grp_DBA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $685D
                dc.w $9500 ! ((grp_F2E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6980
                dc.w $9500 ! ((grp_F2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2E00 / 2) >> 16)
                dc.w 1
