byte_2D3A26:    dc.b   0,  5,$78,$66,$94,$84,$84,$73,$85,$73
                                        ; DATA XREF: ROM:off_1054   o
                dc.w sprite_16_24
                dc.w $8366
                dc.w $9500 ! ((grp_171AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_171AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7B7E
                dc.w $9500 ! ((grp_184720 / 2) & $00FF)
                dc.w $9600 ! (((grp_184720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184720 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7B67
                dc.w $9500 ! ((grp_B2A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7368
                dc.w $9500 ! ((grp_E47A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E47A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E47A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $835E
                dc.w $9500 ! ((grp_E47C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E47C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E47C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9372
                dc.w $9500 ! ((grp_E47E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E47E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E47E0 / 2) >> 16)
                dc.w 1
