byte_2D2B70:    dc.b   0,  1,$82,$7C,$95,$83,$8B,$7F,$8C,$7F
                                        ; DATA XREF: ROM:off_F18   o
                dc.w sprite_24_8
                dc.w $807E
                dc.w $9500 ! ((grp_184960 / 2) & $00FF)
                dc.w $9600 ! (((grp_184960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184960 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7F76
                dc.w $9500 ! ((grp_E4D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4D60 / 2) >> 16)
                dc.w 1
