byte_2D4026:    dc.b   0,  7,$6E,$65,$97,$8F,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_109C   o
                dc.w sprite_24_32
                dc.w $7770
                dc.w $9500 ! ((grp_FDFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FDFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FDFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7260
                dc.w $9500 ! ((grp_159880 / 2) & $00FF)
                dc.w $9600 ! (((grp_159880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159880 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6780
                dc.w $9500 ! ((grp_CAD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8F76
                dc.w $9500 ! ((grp_CAD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A63
                dc.w $9500 ! ((grp_B3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6778
                dc.w $9500 ! ((grp_E5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F88
                dc.w $9500 ! ((grp_E56A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E56A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E56A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A72
                dc.w $9500 ! ((grp_E56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E56C0 / 2) >> 16)
                dc.w 1
