byte_2D7220:    dc.b   0,  4,$78,$64,$8B,$7D,$82,$6C,$89,$63
                                        ; DATA XREF: ROM:off_12C0   o
                dc.w sprite_32_32
                dc.w $7861
                dc.w $9500 ! ((grp_25400 / 2) & $00FF)
                dc.w $9600 ! (((grp_25400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $7049
                dc.w $9500 ! ((grp_178B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_178B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7081
                dc.w $9500 ! ((grp_84400 / 2) & $00FF)
                dc.w $9600 ! (((grp_84400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8859
                dc.w $9500 ! ((grp_ED020 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D81
                dc.w $9500 ! ((grp_ED040 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED040 / 2) >> 16)
                dc.w 1
