byte_2D06E2:    dc.b   0,  1,$88,$73,$92,$8A,$8D,$7E,$8E,$7E
                                        ; DATA XREF: ROM:off_D64   o
                dc.w sprite_16_16
                dc.w $8671
                dc.w $9500 ! ((grp_75D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8D81
                dc.w $9500 ! ((grp_B1980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1980 / 2) >> 16)
                dc.w 2
