byte_2ED7C6:    dc.b   0,  4,$6A,$74,$A9,$95,$88,$82,$89,$82
                                        ; DATA XREF: ROM:off_22CC   o
                dc.w sprite_24_24
                dc.w $6778
                dc.w $9500 ! ((grp_14C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C500 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $8779
                dc.w $9500 ! ((grp_14C3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C3E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $9E74
                dc.w $9500 ! ((grp_89380 / 2) & $00FF)
                dc.w $9600 ! (((grp_89380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7F7A
                dc.w $9500 ! ((grp_19C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C900 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8E71
                dc.w $9500 ! ((grp_D8CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8CC0 / 2) >> 16)
                dc.w 2
