byte_2D399A:    dc.b   0,  5,$7E,$62,$97,$84,$8A,$73,$8B,$73
                                        ; DATA XREF: ROM:off_104C   o
                dc.w sprite_24_16
                dc.w $7C68
                dc.w $9500 ! ((grp_158C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_158C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8378
                dc.w $9500 ! ((grp_158D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_158D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8760
                dc.w $9500 ! ((grp_CA040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7765
                dc.w $9500 ! ((grp_E4600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B7D
                dc.w $9500 ! ((grp_E4620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $946E
                dc.w $9500 ! ((grp_E4640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4640 / 2) >> 16)
                dc.w 1
