byte_2FF224:    dc.b   0,  3,$17,$74,$6E,$90,$40,$7F,$41,$7F
                                        ; DATA XREF: ROM:off_3560   o
                dc.w sprite_24_24
                dc.w $1574
                dc.w $9500 ! ((grp_155500 / 2) & $00FF)
                dc.w $9600 ! (((grp_155500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155500 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $2D74
                dc.w $9500 ! ((grp_5A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5575
                dc.w $9500 ! ((grp_16DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DF80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $4D74
                dc.w $9500 ! ((grp_C6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6380 / 2) >> 16)
                dc.w 2
