byte_2E37D8:    dc.b   0,  4,$72,$64,$9B,$8D,$86,$78,$87,$78
                                        ; DATA XREF: ROM:off_1AD0   o
                dc.w sprite_24_32
                dc.w $7570
                dc.w $9500 ! ((grp_10E340 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8E60
                dc.w $9500 ! ((grp_86A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7668
                dc.w $9500 ! ((grp_18B2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B2C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6D88
                dc.w $9500 ! ((grp_EE980 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D88
                dc.w $9500 ! ((grp_EE9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE9A0 / 2) >> 16)
                dc.w 1
