byte_2D7F4C:    dc.b   0,  8,$75,$5D,$8B,$A2,$85,$80,$81,$6A
                                        ; DATA XREF: ROM:00001350   o
                dc.w sprite_16_32
                dc.w $777F
                dc.w $9500 ! ((grp_5FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5FA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $876F
                dc.w $9500 ! ((grp_173080 / 2) & $00FF)
                dc.w $9600 ! (((grp_173080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173080 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6F6F
                dc.w $9500 ! ((grp_194C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_194C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7777
                dc.w $9500 ! ((grp_CC480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $776F
                dc.w $9500 ! ((grp_CC440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D5F
                dc.w $9500 ! ((grp_B40C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B40C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B40C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $976D
                dc.w $9500 ! ((grp_B4100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D57
                dc.w $9500 ! ((grp_E6960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D9F
                dc.w $9500 ! ((grp_E67A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E67A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E67A0 / 2) >> 16)
                dc.w 1
