byte_2EF472:    dc.b   0,  4,$6C,$81,$93,$8D,$81,$7B,$82,$7B
                                        ; DATA XREF: ROM:off_24E4   o
                dc.w sprite_24_24
                dc.w $7879
                dc.w $9500 ! ((grp_14CF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_14CF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14CF20 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7369
                dc.w $9500 ! ((grp_18D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6884
                dc.w $9500 ! ((grp_D9A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7871
                dc.w $9500 ! ((grp_D9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9084
                dc.w $9500 ! ((grp_D9AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9AC0 / 2) >> 16)
                dc.w 2
