byte_2E84AE:    dc.b   0,  9,$6F,$6F,$8E,$8F,$68,$62,$5D,$72
                                        ; DATA XREF: ROM:off_1D6C   o
                dc.w sprite_32_16
                dc.w $6871
                dc.w $9500 ! ((grp_4AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5868
                dc.w $9500 ! ((grp_7BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8868
                dc.w $9500 ! ((grp_7BE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6C81
                dc.w $9500 ! ((grp_98F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5E60
                dc.w $9500 ! ((grp_CE280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6D89
                dc.w $9500 ! ((grp_CE2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7869
                dc.w $9500 ! ((grp_CE200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8389
                dc.w $9500 ! ((grp_CE240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6078
                dc.w $9500 ! ((grp_E8720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9869
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
