byte_2E65D4:    dc.b   0,  7,$6C,$5F,$88,$8E,$76,$74,$73,$61
                                        ; DATA XREF: ROM:off_1C50   o
                dc.w sprite_24_24
                dc.w $7969
                dc.w $9500 ! ((grp_1470A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1470A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1470A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5C71
                dc.w $9500 ! ((grp_83280 / 2) & $00FF)
                dc.w $9600 ! (((grp_83280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6969
                dc.w $9500 ! ((grp_83300 / 2) & $00FF)
                dc.w $9600 ! (((grp_83300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6C59
                dc.w $9500 ! ((grp_83380 / 2) & $00FF)
                dc.w $9600 ! (((grp_83380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83380 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6F89
                dc.w $9500 ! ((grp_9AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A81
                dc.w $9500 ! ((grp_D3CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C61
                dc.w $9500 ! ((grp_D3D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D51
                dc.w $9500 ! ((grp_EC8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC8E0 / 2) >> 16)
                dc.w 1
