byte_2DBA4E:    dc.b   0,  4,$69,$67,$83,$8E,$76,$7A,$73,$68
                                        ; DATA XREF: ROM:off_1594   o
                dc.w sprite_24_24
                dc.w $7379
                dc.w $9500 ! ((grp_142780 / 2) & $00FF)
                dc.w $9600 ! (((grp_142780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142780 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7369
                dc.w $9500 ! ((grp_7A080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B70
                dc.w $9500 ! ((grp_195400 / 2) & $00FF)
                dc.w $9600 ! (((grp_195400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195400 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7E91
                dc.w $9500 ! ((grp_E71E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E71E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E71E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8371
                dc.w $9500 ! ((grp_E7140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7140 / 2) >> 16)
                dc.w 1
