byte_2D4090:    dc.b   0,  6,$6F,$65,$8F,$8F,$7C,$74,$7D,$74
                                        ; DATA XREF: ROM:off_10A0   o
                dc.w sprite_32_16
                dc.w $6D80
                dc.w $9500 ! ((grp_49100 / 2) & $00FF)
                dc.w $9600 ! (((grp_49100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7460
                dc.w $9500 ! ((grp_172540 / 2) & $00FF)
                dc.w $9600 ! (((grp_172540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172540 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7578
                dc.w $9500 ! ((grp_184EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184EA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $845C
                dc.w $9500 ! ((grp_B32C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B32C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B32C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6580
                dc.w $9500 ! ((grp_E56E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E56E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E56E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7558
                dc.w $9500 ! ((grp_E5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7A
                dc.w $9500 ! ((grp_E5720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5720 / 2) >> 16)
                dc.w 1
