byte_2CF25E:    dc.b   0,  9,$6E,$74,$98,$9B,$84,$7B,$85,$7B
                                        ; DATA XREF: ROM:off_B4C   o
                dc.w sprite_24_32
                dc.w $7D7A
                dc.w $9500 ! ((grp_FAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FAE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6582
                dc.w $9500 ! ((grp_13E520 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E520 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6D5A
                dc.w $9500 ! ((grp_46800 / 2) & $00FF)
                dc.w $9600 ! (((grp_46800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9570
                dc.w $9500 ! ((grp_5C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C100 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7572
                dc.w $9500 ! ((grp_97280 / 2) & $00FF)
                dc.w $9600 ! (((grp_97280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D7A
                dc.w $9500 ! ((grp_C8540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $856A
                dc.w $9500 ! ((grp_C8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6562
                dc.w $9500 ! ((grp_B1440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B9A
                dc.w $9500 ! ((grp_E2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D62
                dc.w $9500 ! ((grp_E2B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2B20 / 2) >> 16)
                dc.w 1
