byte_2E1DA6:    dc.b   0,  3,$78,$6E,$95,$85,$86,$79,$87,$79
                                        ; DATA XREF: ROM:off_19AC   o
                dc.w sprite_32_16
                dc.w $7974
                dc.w $9500 ! ((grp_4C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7482
                dc.w $9500 ! ((grp_D0280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $786C
                dc.w $9500 ! ((grp_D02C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D02C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D02C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $906C
                dc.w $9500 ! ((grp_E9C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C00 / 2) >> 16)
                dc.w 1
