byte_2EA8F6:    dc.b   0,  5,$70,$6D,$93,$88,$83,$7A,$84,$7A
                                        ; DATA XREF: ROM:off_1F64   o
                dc.w sprite_32_24
                dc.w $6E6F
                dc.w $9500 ! ((grp_130CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_130CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_130CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8E6F
                dc.w $9500 ! ((grp_19B7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B7C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7667
                dc.w $9500 ! ((grp_D7280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E87
                dc.w $9500 ! ((grp_EF100 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8287
                dc.w $9500 ! ((grp_EF120 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9678
                dc.w $9500 ! ((grp_EF140 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF140 / 2) >> 16)
                dc.w 1
