byte_2DA8DA:    dc.b   0,  2,$6F,$74,$8E,$8F,$84,$7F,$8C,$77
                                        ; DATA XREF: ROM:off_14C4   o
                dc.w sprite_32_32
                dc.w $6D70
                dc.w $9500 ! ((grp_1D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1D400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8D70
                dc.w $9500 ! ((grp_175480 / 2) & $00FF)
                dc.w $9600 ! (((grp_175480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8D88
                dc.w $9500 ! ((grp_E9660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9660 / 2) >> 16)
                dc.w 1
