byte_2E8C7A:    dc.b   0,  3,$7A,$65,$84,$8E,$81,$79,$86,$6B
                                        ; DATA XREF: ROM:off_1DC4   o
                dc.w sprite_16_16
                dc.w $7883
                dc.w $9500 ! ((grp_7C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7963
                dc.w $9500 ! ((grp_7C480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7D73
                dc.w $9500 ! ((grp_B6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8580
                dc.w $9500 ! ((grp_E89E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E89E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E89E0 / 2) >> 16)
                dc.w 1
