byte_2E0296:    dc.b   0,  5,$5D,$4D,$8E,$82,$75,$67,$7D,$56
                                        ; DATA XREF: ROM:off_18AC   o
                dc.w sprite_32_32
                dc.w $6B65
                dc.w $9500 ! ((grp_21600 / 2) & $00FF)
                dc.w $9600 ! (((grp_21600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $634D
                dc.w $9500 ! ((grp_12B140 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B140 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6365
                dc.w $9500 ! ((grp_A7000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8B6B
                dc.w $9500 ! ((grp_198940 / 2) & $00FF)
                dc.w $9600 ! (((grp_198940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5B59
                dc.w $9500 ! ((grp_B9740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7745
                dc.w $9500 ! ((grp_EB9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB9A0 / 2) >> 16)
                dc.w 1
