byte_2EC356:    dc.b   0,  8,$6D,$66,$92,$91,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_20D4   o
                dc.w sprite_32_16
                dc.w $6B84
                dc.w $9500 ! ((grp_51A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_51A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $736C
                dc.w $9500 ! ((grp_163B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_163B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8B74
                dc.w $9500 ! ((grp_AAC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $737C
                dc.w $9500 ! ((grp_18C520 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B6C
                dc.w $9500 ! ((grp_19C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C000 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B64
                dc.w $9500 ! ((grp_D7F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B64
                dc.w $9500 ! ((grp_D7F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9377
                dc.w $9500 ! ((grp_BE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_EF9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF9C0 / 2) >> 16)
                dc.w 1
