byte_2E7B76:    dc.b   0, $B,$72,$67,$8B,$88,$71,$59,$59,$69
                                        ; DATA XREF: ROM:off_1D1C   o
                dc.w sprite_24_16
                dc.w $6E6F
                dc.w $9500 ! ((grp_15EC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6458
                dc.w $9500 ! ((grp_99D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7667
                dc.w $9500 ! ((grp_99C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_99C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B7F
                dc.w $9500 ! ((grp_1882C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1882C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1882C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $565C
                dc.w $9500 ! ((grp_1978C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1978C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1978C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7387
                dc.w $9500 ! ((grp_D0F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $815F
                dc.w $9500 ! ((grp_D0F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $936A
                dc.w $9500 ! ((grp_D0EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $666A
                dc.w $9500 ! ((grp_B8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E5B
                dc.w $9500 ! ((grp_EA520 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E6D
                dc.w $9500 ! ((grp_EA4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA4E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $866F
                dc.w $9500 ! ((grp_EA500 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA500 / 2) >> 16)
                dc.w 1
