byte_2E2080:    dc.b   0,  4,$77,$43,$8B,$A1,$81,$72,$82,$72
                                        ; DATA XREF: ROM:off_19E0   o
                dc.w sprite_24_32
                dc.w $756B
                dc.w $9500 ! ((grp_1021C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1021C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1021C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $754B
                dc.w $9500 ! ((grp_102340 / 2) & $00FF)
                dc.w $9600 ! (((grp_102340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_1433E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1433E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1433E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $7541
                dc.w $9500 ! ((grp_E7CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8543
                dc.w $9500 ! ((grp_E7CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7CE0 / 2) >> 16)
                dc.w 1
