byte_2E1E0E:    dc.b   0,  4,$69,$6B,$8B,$89,$7A,$7A,$7B,$7A
                                        ; DATA XREF: ROM:off_19B4   o
                dc.w sprite_16_24
                dc.w $7774
                dc.w $9500 ! ((grp_175A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_175A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6670
                dc.w $9500 ! ((grp_D0300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7171
                dc.w $9500 ! ((grp_B7580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F64
                dc.w $9500 ! ((grp_B75C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B75C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B75C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $876C
                dc.w $9500 ! ((grp_B7600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7600 / 2) >> 16)
                dc.w 2
