byte_2DB516:    dc.b   0,  8,$65,$50,$A0,$90,$82,$70,$83,$70
                                        ; DATA XREF: ROM:off_1554   o
                dc.w sprite_24_32
                dc.w $7352
                dc.w $9500 ! ((grp_10CCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10CCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10CCC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7872
                dc.w $9500 ! ((grp_85880 / 2) & $00FF)
                dc.w $9600 ! (((grp_85880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8B50
                dc.w $9500 ! ((grp_18AA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AA80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $634E
                dc.w $9500 ! ((grp_D5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7582
                dc.w $9500 ! ((grp_BC240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8482
                dc.w $9500 ! ((grp_BC280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B56
                dc.w $9500 ! ((grp_EDDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDDA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_EDDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDDC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B58
                dc.w $9500 ! ((grp_EDDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDDE0 / 2) >> 16)
                dc.w 1
