byte_2F184A:    dc.b   0,  5,$76,$69,$8B,$87,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_2684   o
                dc.w sprite_16_24
                dc.w $766F
                dc.w $9500 ! ((grp_17DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DA00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7667
                dc.w $9500 ! ((grp_DB700 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8669
                dc.w $9500 ! ((grp_C0B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E71
                dc.w $9500 ! ((grp_F2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E7F
                dc.w $9500 ! ((grp_F29A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F29A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F29A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B87
                dc.w $9500 ! ((grp_F29C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F29C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F29C0 / 2) >> 16)
                dc.w 1
