byte_2CD13A:    dc.b   0,  2,$6E,$71,$8F,$8D,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_87C   o
                dc.w sprite_32_24
                dc.w $6B72
                dc.w $9500 ! ((grp_11FA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $8B6E
                dc.w $9500 ! ((grp_A1E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $708A
                dc.w $9500 ! ((grp_C8080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8080 / 2) >> 16)
                dc.w 2
