byte_2F8B08:    dc.b   0,  8,$61,$82,$9D,$AE,$7F,$98,$80,$98
                                        ; DATA XREF: ROM:off_2CB8   o
                dc.w sprite_16_32
                dc.w $7791
                dc.w $9500 ! ((grp_6F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6F88
                dc.w $9500 ! ((grp_9FC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5FA8
                dc.w $9500 ! ((grp_18FB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FB80 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_18FBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FBE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $87A8
                dc.w $9500 ! ((grp_18FC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FC40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6794
                dc.w $9500 ! ((grp_DE140 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8794
                dc.w $9500 ! ((grp_DE180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5FA0
                dc.w $9500 ! ((grp_F63A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $98A0
                dc.w $9500 ! ((grp_F63C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63C0 / 2) >> 16)
                dc.w 1
