byte_2D730A:    dc.b   0,  7,$76,$5E,$8B,$78,$82,$6C,$7B,$5A
                                        ; DATA XREF: ROM:off_12CC   o
                dc.w sprite_16_32
                dc.w $7354
                dc.w $9500 ! ((grp_64E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7374
                dc.w $9500 ! ((grp_84100 / 2) & $00FF)
                dc.w $9600 ! (((grp_84100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $835A
                dc.w $9500 ! ((grp_84180 / 2) & $00FF)
                dc.w $9600 ! (((grp_84180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8C52
                dc.w $9500 ! ((grp_9B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $836A
                dc.w $9500 ! ((grp_A7D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8971
                dc.w $9500 ! ((grp_A7D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6B68
                dc.w $9500 ! ((grp_BB340 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $935A
                dc.w $9500 ! ((grp_ECE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECE80 / 2) >> 16)
                dc.w 1
