byte_2E4B2E:    dc.b   0,  3,$6A,$69,$8E,$90,$7C,$7C,$72,$7B
                                        ; DATA XREF: ROM:off_1B6C   o
                dc.w sprite_32_24
                dc.w $6877
                dc.w $9500 ! ((grp_12D240 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7967
                dc.w $9500 ! ((grp_162400 / 2) & $00FF)
                dc.w $9600 ! (((grp_162400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162400 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8877
                dc.w $9500 ! ((grp_A8100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $808F
                dc.w $9500 ! ((grp_ED760 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED760 / 2) >> 16)
                dc.w 1
