byte_2F8368:    dc.b   0,  1,$74,$7A,$8C,$98,$80,$89,$81,$89
                                        ; DATA XREF: ROM:off_2C68   o
                dc.w sprite_24_24
                dc.w $7288
                dc.w $9500 ! ((grp_151BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_151BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151BA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7178
                dc.w $9500 ! ((grp_57000 / 2) & $00FF)
                dc.w $9600 ! (((grp_57000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57000 / 2) >> 16)
                dc.w 8
