byte_2EC21C:    dc.b   0,  1,$7B,$78,$89,$85,$82,$7E,$83,$7E
                                        ; DATA XREF: ROM:off_20C0   o
                dc.w sprite_16_16
                dc.w $7578
                dc.w $9500 ! ((grp_87E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_87E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8476
                dc.w $9500 ! ((grp_BE400 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE400 / 2) >> 16)
                dc.w 2
