byte_2FB794:    dc.b   0,  2,$74,$62,$88,$8D,$7E,$77,$7F,$77
                                        ; DATA XREF: ROM:off_2F98   o
                dc.w sprite_16_24
                dc.w $6F64
                dc.w $9500 ! ((grp_180E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_180E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B78
                dc.w $9500 ! ((grp_180F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_180F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7960
                dc.w $9500 ! ((grp_DF500 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF500 / 2) >> 16)
                dc.w 2
