byte_2E3E86:    dc.b   0, $C,$6F,$7F,$8E,$BB,$7B,$46,$7A,$42
                                        ; DATA XREF: ROM:off_1B0C   o
                dc.w sprite_16_32
                dc.w $7975
                dc.w $9500 ! ((grp_60D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $79A5
                dc.w $9500 ! ((grp_174340 / 2) & $00FF)
                dc.w $9600 ! (((grp_174340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7995
                dc.w $9500 ! ((grp_7B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $71A6
                dc.w $9500 ! ((grp_A5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7855
                dc.w $9500 ! ((grp_A5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $763D
                dc.w $9500 ! ((grp_195EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195EE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $69B3
                dc.w $9500 ! ((grp_B59C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B59C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B59C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7177
                dc.w $9500 ! ((grp_B5A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $79BD
                dc.w $9500 ! ((grp_B5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E3E
                dc.w $9500 ! ((grp_B5AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $89A9
                dc.w $9500 ! ((grp_B5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $61B4
                dc.w $9500 ! ((grp_E8220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $91B1
                dc.w $9500 ! ((grp_E8200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8200 / 2) >> 16)
                dc.w 1
