byte_2DE810:    dc.b   0,  5,$70,$67,$8C,$8D,$7F,$76,$83,$67
                                        ; DATA XREF: ROM:off_1788   o
                dc.w sprite_24_32
                dc.w $735E
                dc.w $9500 ! ((grp_10C240 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $737E
                dc.w $9500 ! ((grp_1621C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1621C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1621C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6B66
                dc.w $9500 ! ((grp_199BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_D51C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D51C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D51C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858C
                dc.w $9500 ! ((grp_D5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B6A
                dc.w $9500 ! ((grp_BB900 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB900 / 2) >> 16)
                dc.w 2
