byte_2CF91A:    dc.b   0,  1,$79,$77,$86,$8C,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_BB4   o
                dc.w sprite_16_24
                dc.w $7875
                dc.w $9500 ! ((grp_170740 / 2) & $00FF)
                dc.w $9600 ! (((grp_170740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $798D
                dc.w $9500 ! ((grp_E2E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2E60 / 2) >> 16)
                dc.w 1
