byte_2EE828:    dc.b   0,  4,$6C,$6B,$99,$95,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_23E0   o
                dc.w sprite_32_32
                dc.w $6B79
                dc.w $9500 ! ((grp_32000 / 2) & $00FF)
                dc.w $9600 ! (((grp_32000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6B69
                dc.w $9500 ! ((grp_52800 / 2) & $00FF)
                dc.w $9600 ! (((grp_52800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8B79
                dc.w $9500 ! ((grp_AB800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9373
                dc.w $9500 ! ((grp_19D020 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D020 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B69
                dc.w $9500 ! ((grp_BF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF4C0 / 2) >> 16)
                dc.w 2
