byte_2EF854:    dc.b   0,  3,$6D,$1F,$85,$38,$79,$2B,$7A,$2B
                                        ; DATA XREF: ROM:off_2530   o
                dc.w sprite_32_8
                dc.w $6A33
                dc.w $9500 ! ((grp_9E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E400 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6B23
                dc.w $9500 ! ((grp_9E480 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E2B
                dc.w $9500 ! ((grp_18D7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D7E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6F1B
                dc.w $9500 ! ((grp_18D780 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D780 / 2) >> 16)
                dc.w 3
