byte_2D573E:    dc.b   0,  8,$6F,$6B,$8E,$8F,$74,$72,$6A,$76
                                        ; DATA XREF: ROM:off_11AC   o
                dc.w sprite_16_32
                dc.w $6C70
                dc.w $9500 ! ((grp_62400 / 2) & $00FF)
                dc.w $9600 ! (((grp_62400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8483
                dc.w $9500 ! ((grp_7DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6465
                dc.w $9500 ! ((grp_A5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C6F
                dc.w $9500 ! ((grp_A5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C58
                dc.w $9500 ! ((grp_1970E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1970E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1970E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7457
                dc.w $9500 ! ((grp_B7380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C6F
                dc.w $9500 ! ((grp_E9960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $648C
                dc.w $9500 ! ((grp_E9980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948C
                dc.w $9500 ! ((grp_E99A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E99A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E99A0 / 2) >> 16)
                dc.w 1
