byte_2FBB30:    dc.b   0,  5,$6A,$6E,$94,$8D,$7F,$7D,$80,$7D
                                        ; DATA XREF: ROM:off_2FC8   o
                dc.w sprite_24_16
                dc.w $687C
                dc.w $9500 ! ((grp_16B4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B4C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $806C
                dc.w $9500 ! ((grp_91F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_91F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9074
                dc.w $9500 ! ((grp_AE980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $706C
                dc.w $9500 ! ((grp_DF2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $788C
                dc.w $9500 ! ((grp_F79A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F79A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F79A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $887C
                dc.w $9500 ! ((grp_F79C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F79C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F79C0 / 2) >> 16)
                dc.w 1
