byte_2E7C10:    dc.b   0,  7,$70,$66,$8C,$88,$59,$68,$75,$74
                                        ; DATA XREF: ROM:off_1D20   o
                dc.w sprite_32_24
                dc.w $6B62
                dc.w $9500 ! ((grp_1291C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1291C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1291C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $5362
                dc.w $9500 ! ((grp_176200 / 2) & $00FF)
                dc.w $9600 ! (((grp_176200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8B67
                dc.w $9500 ! ((grp_7F580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6D7A
                dc.w $9500 ! ((grp_188320 / 2) & $00FF)
                dc.w $9600 ! (((grp_188320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188320 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5F5A
                dc.w $9500 ! ((grp_D0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6372
                dc.w $9500 ! ((grp_EA540 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D82
                dc.w $9500 ! ((grp_EA560 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A82
                dc.w $9500 ! ((grp_EA580 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA580 / 2) >> 16)
                dc.w 1
