byte_2DE748:    dc.b   0,  7,$67,$54,$88,$8D,$77,$6E,$77,$56
                                        ; DATA XREF: ROM:off_1780   o
                dc.w sprite_32_24
                dc.w $6953
                dc.w $9500 ! ((grp_12D0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7673
                dc.w $9500 ! ((grp_65700 / 2) & $00FF)
                dc.w $9600 ! (((grp_65700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5956
                dc.w $9500 ! ((grp_84C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A4B
                dc.w $9500 ! ((grp_18A420 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $698B
                dc.w $9500 ! ((grp_D5040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $736B
                dc.w $9500 ! ((grp_D5080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $868A
                dc.w $9500 ! ((grp_D50C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D50C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D50C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8956
                dc.w $9500 ! ((grp_ED6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED6C0 / 2) >> 16)
                dc.w 1
