byte_2F1670:    dc.b   0,  2,$71,$7C,$93,$8E,$82,$88,$83,$88
                                        ; DATA XREF: ROM:off_2660   o
                dc.w sprite_32_8
                dc.w $7789
                dc.w $9500 ! ((grp_9E980 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7C81
                dc.w $9500 ! ((grp_18DDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DDE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6F89
                dc.w $9500 ! ((grp_F1F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1F20 / 2) >> 16)
                dc.w 1
