byte_2FE78E:    dc.b   0,  2,$76,$80,$86,$91,$7B,$88,$7C,$88
                                        ; DATA XREF: ROM:00003424   o
                dc.w sprite_24_16
                dc.w $757E
                dc.w $9500 ! ((grp_16DD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DD40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6D8C
                dc.w $9500 ! ((grp_F8CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $808E
                dc.w $9500 ! ((grp_F8CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8CE0 / 2) >> 16)
                dc.w 1
