byte_2E6FAE:    dc.b   0,  7,$74,$53,$92,$78,$7D,$64,$74,$59
                                        ; DATA XREF: ROM:off_1CAC   o
                dc.w sprite_32_24
                dc.w $7062
                dc.w $9500 ! ((grp_126C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_126C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $9063
                dc.w $9500 ! ((grp_7C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $715A
                dc.w $9500 ! ((grp_99180 / 2) & $00FF)
                dc.w $9600 ! (((grp_99180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $717A
                dc.w $9500 ! ((grp_CEB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6957
                dc.w $9500 ! ((grp_B6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7152
                dc.w $9500 ! ((grp_E8C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8852
                dc.w $9500 ! ((grp_E8C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9073
                dc.w $9500 ! ((grp_E8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8C80 / 2) >> 16)
                dc.w 1
