byte_2E23B4:    dc.b   0,  4,$74,$65,$88,$89,$7E,$74,$79,$5A
                                        ; DATA XREF: ROM:off_1A08   o
                dc.w sprite_24_32
                dc.w $7561
                dc.w $9500 ! ((grp_102C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_102C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7281
                dc.w $9500 ! ((grp_7B380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B380 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7259
                dc.w $9500 ! ((grp_98D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6D6D
                dc.w $9500 ! ((grp_A5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6579
                dc.w $9500 ! ((grp_E7F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7F60 / 2) >> 16)
                dc.w 1
