byte_2DD0B0:    dc.b   0,  6,$6E,$5D,$81,$81,$6D,$71,$69,$68
                                        ; DATA XREF: ROM:off_1690   o
                dc.w sprite_24_32
                dc.w $6C65
                dc.w $9500 ! ((grp_1015C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1015C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1015C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7055
                dc.w $9500 ! ((grp_7A380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5465
                dc.w $9500 ! ((grp_185B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_185B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185B00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6479
                dc.w $9500 ! ((grp_E73E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E73E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E73E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6855
                dc.w $9500 ! ((grp_E7380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7685
                dc.w $9500 ! ((grp_E73A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E73A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E73A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A89
                dc.w $9500 ! ((grp_E73C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E73C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E73C0 / 2) >> 16)
                dc.w 1
