byte_2DF5C2:    dc.b   0,  5,$74,$63,$8A,$8A,$7E,$76,$89,$69
                                        ; DATA XREF: ROM:off_1814   o
                dc.w sprite_32_24
                dc.w $7269
                dc.w $9500 ! ((grp_125BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_125BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6B81
                dc.w $9500 ! ((grp_77B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_77B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7B61
                dc.w $9500 ! ((grp_185E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_185E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B81
                dc.w $9500 ! ((grp_CAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B59
                dc.w $9500 ! ((grp_E7A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $927A
                dc.w $9500 ! ((grp_E78E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E78E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E78E0 / 2) >> 16)
                dc.w 1
