byte_2F953E:    dc.b   0,  2,$7A,$68,$88,$84,$81,$76,$82,$76
                                        ; DATA XREF: ROM:off_2D4C   o
                dc.w sprite_16_24
                dc.w $7866
                dc.w $9500 ! ((grp_180340 / 2) & $00FF)
                dc.w $9600 ! (((grp_180340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180340 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7E7E
                dc.w $9500 ! ((grp_F6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8866
                dc.w $9500 ! ((grp_F6820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6820 / 2) >> 16)
                dc.w 1
