byte_2FD4DA:    dc.b   0,  6,$5F,$41,$8F,$8D,$7A,$67,$7B,$67
                                        ; DATA XREF: ROM:off_32EC   o
                dc.w sprite_16_24
                dc.w $8370
                dc.w $9500 ! ((grp_181D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_181D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6447
                dc.w $9500 ! ((grp_94F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_94F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_94F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7456
                dc.w $9500 ! ((grp_95000 / 2) & $00FF)
                dc.w $9600 ! (((grp_95000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7D64
                dc.w $9500 ! ((grp_95080 / 2) & $00FF)
                dc.w $9600 ! (((grp_95080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $663F
                dc.w $9500 ! ((grp_191020 / 2) & $00FF)
                dc.w $9600 ! (((grp_191020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191020 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7B88
                dc.w $9500 ! ((grp_191080 / 2) & $00FF)
                dc.w $9600 ! (((grp_191080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191080 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C57
                dc.w $9500 ! ((grp_F83A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F83A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F83A0 / 2) >> 16)
                dc.w 1
