byte_2F2686:    dc.b   0,  3,$71,$4F,$8E,$7B,$7F,$69,$80,$69
                                        ; DATA XREF: ROM:off_271C   o
                dc.w sprite_24_24
                dc.w $7556
                dc.w $9500 ! ((grp_14DDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14DDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14DDC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7A6E
                dc.w $9500 ! ((grp_18DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DC00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6D61
                dc.w $9500 ! ((grp_F1980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A76
                dc.w $9500 ! ((grp_F1960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1960 / 2) >> 16)
                dc.w 1
