byte_2EF6C2:    dc.b   0,  2,$75,$57,$95,$6B,$85,$61,$86,$61
                                        ; DATA XREF: ROM:off_250C   o
                dc.w sprite_24_16
                dc.w $735A
                dc.w $9500 ! ((grp_165880 / 2) & $00FF)
                dc.w $9600 ! (((grp_165880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165880 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7552
                dc.w $9500 ! ((grp_D9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $936D
                dc.w $9500 ! ((grp_F0CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0CE0 / 2) >> 16)
                dc.w 1
