byte_2EEEE2:    dc.b   0,  4,$63,$75,$9E,$8C,$80,$80,$81,$80
                                        ; DATA XREF: ROM:off_2434   o
                dc.w sprite_32_16
                dc.w $7783
                dc.w $9500 ! ((grp_52D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_52D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5F83
                dc.w $9500 ! ((grp_1654C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1654C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1654C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $9785
                dc.w $9500 ! ((grp_18D5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D5A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5786
                dc.w $9500 ! ((grp_F0BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E67
                dc.w $9500 ! ((grp_F0BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0BC0 / 2) >> 16)
                dc.w 1
