byte_2F2D96:    dc.b   0,  4,$74,$57,$92,$8A,$85,$73,$86,$73
                                        ; DATA XREF: ROM:off_276C   o
                dc.w sprite_32_24
                dc.w $7F55
                dc.w $9500 ! ((grp_1366C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1366C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1366C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7F6D
                dc.w $9500 ! ((grp_14FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14FB00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6F63
                dc.w $9500 ! ((grp_17E0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E0C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7685
                dc.w $9500 ! ((grp_18E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E800 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $768D
                dc.w $9500 ! ((grp_F3240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3240 / 2) >> 16)
                dc.w 1
