byte_2F3580:    dc.b   0,  6,$69,$5F,$96,$89,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_27B8   o
                dc.w sprite_24_32
                dc.w $7B5D
                dc.w $9500 ! ((grp_114F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_114F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $747D
                dc.w $9500 ! ((grp_14F680 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F680 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8C7D
                dc.w $9500 ! ((grp_167B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_167B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6B5D
                dc.w $9500 ! ((grp_17DDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DDC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $5B61
                dc.w $9500 ! ((grp_C0F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $635D
                dc.w $9500 ! ((grp_F2FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $636D
                dc.w $9500 ! ((grp_F2FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2FE0 / 2) >> 16)
                dc.w 1
