byte_2FE556:    dc.b   0,  1,$7E,$75,$86,$84,$82,$7C,$83,$7C
                                        ; DATA XREF: ROM:off_33E4   o
                dc.w sprite_8_24
                dc.w $8173
                dc.w $9500 ! ((grp_1A1400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1400 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7973
                dc.w $9500 ! ((grp_C6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6600 / 2) >> 16)
                dc.w 2
