byte_2FA488:    dc.b   0, $A,$73,$58,$8F,$8E,$77,$6F,$78,$6F
                                        ; DATA XREF: ROM:off_2E08   o
                dc.w sprite_24_32
                dc.w $8756
                dc.w $9500 ! ((grp_11A940 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7076
                dc.w $9500 ! ((grp_152B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_152B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152B60 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $674E
                dc.w $9500 ! ((grp_57500 / 2) & $00FF)
                dc.w $9600 ! (((grp_57500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $725E
                dc.w $9500 ! ((grp_16A680 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8876
                dc.w $9500 ! ((grp_1804C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1804C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1804C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $706E
                dc.w $9500 ! ((grp_190300 / 2) & $00FF)
                dc.w $9600 ! (((grp_190300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190300 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $748E
                dc.w $9500 ! ((grp_190360 / 2) & $00FF)
                dc.w $9600 ! (((grp_190360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190360 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $4A63
                dc.w $9500 ! ((grp_DED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DED00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $5A5E
                dc.w $9500 ! ((grp_DED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DED40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A5E
                dc.w $9500 ! ((grp_C4940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F56
                dc.w $9500 ! ((grp_C4540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4540 / 2) >> 16)
                dc.w 2
