byte_2DCB86:    dc.b   0,  9,$6F,$57,$8E,$8F,$80,$69,$86,$59
                                        ; DATA XREF: ROM:off_1664   o
                dc.w sprite_24_24
                dc.w $7151
                dc.w $9500 ! ((grp_148060 / 2) & $00FF)
                dc.w $9600 ! (((grp_148060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148060 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6C71
                dc.w $9500 ! ((grp_85000 / 2) & $00FF)
                dc.w $9600 ! (((grp_85000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8954
                dc.w $9500 ! ((grp_85080 / 2) & $00FF)
                dc.w $9600 ! (((grp_85080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $615A
                dc.w $9500 ! ((grp_D5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7769
                dc.w $9500 ! ((grp_D5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C6E
                dc.w $9500 ! ((grp_D5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8676
                dc.w $9500 ! ((grp_D54C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D54C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D54C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7081
                dc.w $9500 ! ((grp_ED840 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F6E
                dc.w $9500 ! ((grp_ED860 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9955
                dc.w $9500 ! ((grp_ED880 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED880 / 2) >> 16)
                dc.w 1
