byte_2D4D6C:    dc.b   0,  3,$79,$5F,$8E,$8E,$87,$7E,$80,$69
                                        ; DATA XREF: ROM:off_1140   o
                dc.w sprite_32_24
                dc.w $775D
                dc.w $9500 ! ((grp_123640 / 2) & $00FF)
                dc.w $9600 ! (((grp_123640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7984
                dc.w $9500 ! ((grp_49700 / 2) & $00FF)
                dc.w $9600 ! (((grp_49700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7774
                dc.w $9500 ! ((grp_159E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_159E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7894
                dc.w $9500 ! ((grp_B36C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B36C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B36C0 / 2) >> 16)
                dc.w 2
