byte_2FC87C:    dc.b   0,  1,$70,$73,$8C,$8B,$7E,$7F,$7F,$7F
                                        ; DATA XREF: ROM:off_3150   o
                dc.w sprite_32_16
                dc.w $6F71
                dc.w $9500 ! ((grp_58D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_58D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $6779
                dc.w $9500 ! ((grp_F7FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7FA0 / 2) >> 16)
                dc.w 1
