byte_2F230A:    dc.b   0, $D,$59,$57,$A8,$92,$7F,$76,$80,$76
                                        ; DATA XREF: ROM:off_26F4   o
                dc.w sprite_24_32
                dc.w $795B
                dc.w $9500 ! ((grp_113EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_113EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $797B
                dc.w $9500 ! ((grp_14EC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_14EC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14EC60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $615B
                dc.w $9500 ! ((grp_6C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4953
                dc.w $9500 ! ((grp_166FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_166FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9973
                dc.w $9500 ! ((grp_17D640 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5163
                dc.w $9500 ! ((grp_8C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7173
                dc.w $9500 ! ((grp_AC500 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7153
                dc.w $9500 ! ((grp_AC580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $916B
                dc.w $9500 ! ((grp_AC600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $A970
                dc.w $9500 ! ((grp_19D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D800 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7493
                dc.w $9500 ! ((grp_DB2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $697B
                dc.w $9500 ! ((grp_C0640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5973
                dc.w $9500 ! ((grp_F24A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F24A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F24A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B17B
                dc.w $9500 ! ((grp_F24C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F24C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F24C0 / 2) >> 16)
                dc.w 1
