byte_2F3092:    dc.b   0,  8,$6D,$5F,$8E,$90,$78,$77,$79,$77
                                        ; DATA XREF: ROM:off_278C   o
                dc.w sprite_24_32
                dc.w $775D
                dc.w $9500 ! ((grp_114AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_114AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D7D
                dc.w $9500 ! ((grp_55600 / 2) & $00FF)
                dc.w $9600 ! (((grp_55600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6F60
                dc.w $9500 ! ((grp_19DCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DCE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $798D
                dc.w $9500 ! ((grp_DB9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F65
                dc.w $9500 ! ((grp_C0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D7D
                dc.w $9500 ! ((grp_C0CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5769
                dc.w $9500 ! ((grp_F2CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6585
                dc.w $9500 ! ((grp_F2CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6766
                dc.w $9500 ! ((grp_F2CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2CC0 / 2) >> 16)
                dc.w 1
