byte_2EC696:    dc.b   0,  2,$72,$7D,$8F,$91,$80,$87,$81,$87
                                        ; DATA XREF: ROM:off_2144   o
                dc.w sprite_24_24
                dc.w $707B
                dc.w $9500 ! ((grp_14BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14BC00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $887B
                dc.w $9500 ! ((grp_D8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8883
                dc.w $9500 ! ((grp_EFC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFC40 / 2) >> 16)
                dc.w 1
