byte_2FE484:    dc.b   0,  5,$74,$78,$8A,$88,$7D,$84,$7E,$84
                                        ; DATA XREF: ROM:off_33D8   o
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_16DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7886
                dc.w $9500 ! ((grp_E0440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6986
                dc.w $9500 ! ((grp_F8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C7A
                dc.w $9500 ! ((grp_F8B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718E
                dc.w $9500 ! ((grp_F8B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7D
                dc.w $9500 ! ((grp_F8B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8B40 / 2) >> 16)
                dc.w 1
