byte_2E7E6A:    dc.b   0,  6,$70,$65,$88,$82,$A1,$61,$7C,$7C
                                        ; DATA XREF: ROM:off_1D34   o
                dc.w sprite_24_32
                dc.w $6E62
                dc.w $9500 ! ((grp_105C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_105C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7282
                dc.w $9500 ! ((grp_D10C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D10C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D10C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8662
                dc.w $9500 ! ((grp_B8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E68
                dc.w $9500 ! ((grp_B8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $965F
                dc.w $9500 ! ((grp_B8540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8674
                dc.w $9500 ! ((grp_EA780 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E5B
                dc.w $9500 ! ((grp_EA760 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA760 / 2) >> 16)
                dc.w 1
