byte_2E2434:    dc.b   0,  2,$88,$6E,$9A,$86,$91,$7A,$92,$7A
                                        ; DATA XREF: ROM:off_1A10   o
                dc.w sprite_16_24
                dc.w $8D71
                dc.w $9500 ! ((grp_1777C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1777C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1777C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8576
                dc.w $9500 ! ((grp_B9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9369
                dc.w $9500 ! ((grp_EBF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBF20 / 2) >> 16)
                dc.w 1
