byte_2ECC9C:    dc.b   0,  1,$78,$79,$85,$86,$7E,$7F,$7F,$7F
                                        ; DATA XREF: ROM:off_21F8   o
                dc.w sprite_24_16
                dc.w $7277
                dc.w $9500 ! ((grp_163CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_163CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7987
                dc.w $9500 ! ((grp_EFBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFBE0 / 2) >> 16)
                dc.w 1
