byte_2D4740:    dc.b   0,  9,$69,$5E,$93,$96,$83,$7B,$7E,$6B
                                        ; DATA XREF: ROM:off_10F0   o
                dc.w sprite_24_32
                dc.w $876D
                dc.w $9500 ! ((grp_FE140 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $775C
                dc.w $9500 ! ((grp_5EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5EF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $777C
                dc.w $9500 ! ((grp_1726C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1726C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1726C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $567B
                dc.w $9500 ! ((grp_77E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_77E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6774
                dc.w $9500 ! ((grp_77F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_77F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9F6C
                dc.w $9500 ! ((grp_77F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_77F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6789
                dc.w $9500 ! ((grp_B35C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B35C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B35C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4E81
                dc.w $9500 ! ((grp_E5C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_E5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A979
                dc.w $9500 ! ((grp_E5BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5BE0 / 2) >> 16)
                dc.w 1
