byte_2EF066:    dc.b   0,  2,$73,$7C,$8E,$8D,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_245C   o
                dc.w sprite_32_16
                dc.w $717A
                dc.w $9500 ! ((grp_53800 / 2) & $00FF)
                dc.w $9600 ! (((grp_53800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $758A
                dc.w $9500 ! ((grp_18DA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DA20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8172
                dc.w $9500 ! ((grp_DA180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA180 / 2) >> 16)
                dc.w 2
