byte_2F334A:    dc.b   0,  7,$70,$5F,$94,$8E,$7B,$76,$7C,$76
                                        ; DATA XREF: ROM:off_27A4   o
                dc.w sprite_32_32
                dc.w $7465
                dc.w $9500 ! ((grp_39C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_39C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $7585
                dc.w $9500 ! ((grp_9F080 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C61
                dc.w $9500 ! ((grp_19DDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DDA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5C71
                dc.w $9500 ! ((grp_DBB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $745D
                dc.w $9500 ! ((grp_DBB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $788D
                dc.w $9500 ! ((grp_DBC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B5D
                dc.w $9500 ! ((grp_DBBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D7D
                dc.w $9500 ! ((grp_C0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0E80 / 2) >> 16)
                dc.w 2
