byte_2FDCC0:    dc.b   0,  4,$66,$6D,$9F,$8D,$82,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_3340   o
                dc.w sprite_24_24
                dc.w $6A6B
                dc.w $9500 ! ((grp_154C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_154C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154C00 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $826B
                dc.w $9500 ! ((grp_154D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_154D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154D20 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7583
                dc.w $9500 ! ((grp_16D680 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D680 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6270
                dc.w $9500 ! ((grp_C5D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A72
                dc.w $9500 ! ((grp_C5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5D80 / 2) >> 16)
                dc.w 2
