byte_2EE970:    dc.b   0,  5,$62,$6C,$99,$8E,$7E,$79,$7F,$79
                                        ; DATA XREF: ROM:off_23F0   o
                dc.w sprite_32_32
                dc.w $6971
                dc.w $9500 ! ((grp_32800 / 2) & $00FF)
                dc.w $9600 ! (((grp_32800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $8973
                dc.w $9500 ! ((grp_14CBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14CBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14CBC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7863
                dc.w $9500 ! ((grp_18D3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D3C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6172
                dc.w $9500 ! ((grp_19D140 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D140 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $597F
                dc.w $9500 ! ((grp_F0880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $898B
                dc.w $9500 ! ((grp_F08A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F08A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F08A0 / 2) >> 16)
                dc.w 1
