byte_2D85A0:    dc.b   0,  7,$74,$5D,$88,$7A,$7E,$6E,$80,$60
                                        ; DATA XREF: ROM:off_1398   o
                dc.w sprite_24_24
                dc.w $7061
                dc.w $9500 ! ((grp_1420C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1420C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1420C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7B51
                dc.w $9500 ! ((grp_15AA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15AA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15AA80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7C79
                dc.w $9500 ! ((grp_194F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_194F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8487
                dc.w $9500 ! ((grp_CC880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6861
                dc.w $9500 ! ((grp_B4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $886C
                dc.w $9500 ! ((grp_B4540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B49
                dc.w $9500 ! ((grp_E6D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906F
                dc.w $9500 ! ((grp_E6D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6D40 / 2) >> 16)
                dc.w 1
