byte_2FB9A2:    dc.b   0,  4,$6A,$6E,$95,$94,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_2FB4   o
                dc.w sprite_24_32
                dc.w $686C
                dc.w $9500 ! ((grp_11BE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11BE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11BE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $708C
                dc.w $9500 ! ((grp_91C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_91C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8086
                dc.w $9500 ! ((grp_91C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_91C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9074
                dc.w $9500 ! ((grp_AE900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $806C
                dc.w $9500 ! ((grp_1909C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1909C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1909C0 / 2) >> 16)
                dc.w 3
