byte_2EE478:    dc.b   0,  4,$7D,$13,$81,$7E,$7F,$48,$80,$48
                                        ; DATA XREF: ROM:off_2390   o
                dc.w sprite_8_32
                dc.w $7B51
                dc.w $9500 ! ((grp_AB180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7B31
                dc.w $9500 ! ((grp_AB100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7B11
                dc.w $9500 ! ((grp_AB080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7B71
                dc.w $9500 ! ((grp_BF140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8311
                dc.w $9500 ! ((grp_F0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0700 / 2) >> 16)
                dc.w 1
