byte_2FCEDA:    dc.b   0,  1,$82,$65,$96,$72,$8C,$6B,$8D,$6B
                                        ; DATA XREF: ROM:off_325C   o
                dc.w sprite_24_24
                dc.w $8063
                dc.w $9500 ! ((grp_154780 / 2) & $00FF)
                dc.w $9600 ! (((grp_154780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154780 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $9863
                dc.w $9500 ! ((grp_C5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5900 / 2) >> 16)
                dc.w 2
