byte_2D717C:    dc.b   0,  5,$74,$55,$92,$7A,$82,$4E,$8F,$53
                                        ; DATA XREF: ROM:off_12B8   o
                dc.w sprite_32_24
                dc.w $754B
                dc.w $9500 ! ((grp_12EEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12EEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12EEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $666E
                dc.w $9500 ! ((grp_86580 / 2) & $00FF)
                dc.w $9600 ! (((grp_86580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7663
                dc.w $9500 ! ((grp_86600 / 2) & $00FF)
                dc.w $9600 ! (((grp_86600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $955B
                dc.w $9500 ! ((grp_86680 / 2) & $00FF)
                dc.w $9600 ! (((grp_86680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6551
                dc.w $9500 ! ((grp_D66C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D66C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D66C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7673
                dc.w $9500 ! ((grp_EE720 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE720 / 2) >> 16)
                dc.w 1
