byte_2D36F6:    dc.b   0,  4,$8F,$71,$C4,$88,$A9,$7C,$AA,$7C
                                        ; DATA XREF: ROM:off_1024   o
                dc.w sprite_24_24
                dc.w $AC74
                dc.w $9500 ! ((grp_1406E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1406E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1406E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $946B
                dc.w $9500 ! ((grp_5ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5ED00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $A46F
                dc.w $9500 ! ((grp_194080 / 2) & $00FF)
                dc.w $9600 ! (((grp_194080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194080 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8C7C
                dc.w $9500 ! ((grp_E50A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E50A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E50A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C479
                dc.w $9500 ! ((grp_E50C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E50C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E50C0 / 2) >> 16)
                dc.w 1
