byte_2EA772:    dc.b   0,  6,$66,$5A,$97,$8D,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_1F54   o
                dc.w sprite_32_32
                dc.w $6A70
                dc.w $9500 ! ((grp_29E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_29E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_29E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6A58
                dc.w $9500 ! ((grp_1309C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1309C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1309C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8A58
                dc.w $9500 ! ((grp_17A940 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A940 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_AA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A70
                dc.w $9500 ! ((grp_A9F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7850
                dc.w $9500 ! ((grp_18BBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BBC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9270
                dc.w $9500 ! ((grp_19B6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B6A0 / 2) >> 16)
                dc.w 3
