byte_2F1B64:    dc.b   0,  4,$6F,$48,$97,$72,$83,$5F,$84,$5F
                                        ; DATA XREF: ROM:off_26B0   o
                dc.w sprite_32_24
                dc.w $7154
                dc.w $9500 ! ((grp_1348C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1348C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1348C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $714C
                dc.w $9500 ! ((grp_18DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DF00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7E6C
                dc.w $9500 ! ((grp_DAE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $695F
                dc.w $9500 ! ((grp_F2220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9166
                dc.w $9500 ! ((grp_F2200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2200 / 2) >> 16)
                dc.w 1
