byte_2E22B4:    dc.b   0,  2,$76,$61,$8B,$8C,$84,$74,$8C,$5D
                                        ; DATA XREF: ROM:off_19F8   o
                dc.w sprite_24_32
                dc.w $755F
                dc.w $9500 ! ((grp_102940 / 2) & $00FF)
                dc.w $9600 ! (((grp_102940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7B7F
                dc.w $9500 ! ((grp_173F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_173F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7E57
                dc.w $9500 ! ((grp_186220 / 2) & $00FF)
                dc.w $9600 ! (((grp_186220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186220 / 2) >> 16)
                dc.w 3
