byte_2EEDBC:    dc.b   0,  5,$6F,$7D,$92,$8B,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_2428   o
                dc.w sprite_32_24
                dc.w $7C79
                dc.w $9500 ! ((grp_1333C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1333C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1333C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6C71
                dc.w $9500 ! ((grp_ABC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7479
                dc.w $9500 ! ((grp_19D260 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D260 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6479
                dc.w $9500 ! ((grp_BF780 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A78
                dc.w $9500 ! ((grp_BF740 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E71
                dc.w $9500 ! ((grp_F0B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0B00 / 2) >> 16)
                dc.w 1
