byte_2CDE88:    dc.b   0,  4,$68,$60,$92,$83,$7D,$71,$7E,$71
                                        ; DATA XREF: ROM:off_9D0   o
                dc.w sprite_32_32
                dc.w $7266
                dc.w $9500 ! ((grp_12000 / 2) & $00FF)
                dc.w $9600 ! (((grp_12000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $725E
                dc.w $9500 ! ((grp_96F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A63
                dc.w $9500 ! ((grp_A2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6265
                dc.w $9500 ! ((grp_B0CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $926B
                dc.w $9500 ! ((grp_B0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0C80 / 2) >> 16)
                dc.w 2
