byte_2DF332:    dc.b   0,  4,$73,$64,$8A,$8E,$7C,$77,$85,$6C
                                        ; DATA XREF: ROM:off_17F4   o
                dc.w sprite_24_32
                dc.w $7566
                dc.w $9500 ! ((grp_101D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_101D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6D81
                dc.w $9500 ! ((grp_7AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7D86
                dc.w $9500 ! ((grp_CD2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D75
                dc.w $9500 ! ((grp_E7880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $785E
                dc.w $9500 ! ((grp_E78A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E78A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E78A0 / 2) >> 16)
                dc.w 1
