byte_2EA072:    dc.b   0,  2,$73,$75,$91,$8E,$82,$81,$83,$81
                                        ; DATA XREF: ROM:off_1EFC   o
                dc.w sprite_32_24
                dc.w $7179
                dc.w $9500 ! ((grp_12F940 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F940 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $8371
                dc.w $9500 ! ((grp_EEE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEE40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9186
                dc.w $9500 ! ((grp_EEE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEE20 / 2) >> 16)
                dc.w 1
