byte_2FB6FE:    dc.b   0,  3,$72,$62,$8A,$8F,$7E,$78,$7F,$78
                                        ; DATA XREF: ROM:off_2F8C   o
                dc.w sprite_32_16
                dc.w $6E85
                dc.w $9500 ! ((grp_57A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $7968
                dc.w $9500 ! ((grp_1A01A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A01A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A01A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7C60
                dc.w $9500 ! ((grp_F7D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7D20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C7D
                dc.w $9500 ! ((grp_F7D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7D40 / 2) >> 16)
                dc.w 1
