byte_2F4CD4:    dc.b   0,  8,$6E,$64,$95,$8D,$8C,$79,$8D,$79
                                        ; DATA XREF: ROM:off_2A18   o
                dc.w sprite_24_32
                dc.w $7D5F
                dc.w $9500 ! ((grp_1162C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1162C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1162C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6D69
                dc.w $9500 ! ((grp_6DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7D7F
                dc.w $9500 ! ((grp_1684C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1684C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1684C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9D76
                dc.w $9500 ! ((grp_8E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6579
                dc.w $9500 ! ((grp_19E520 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E520 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $848F
                dc.w $9500 ! ((grp_DC640 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $956F
                dc.w $9500 ! ((grp_C1900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D89
                dc.w $9500 ! ((grp_F4260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A781
                dc.w $9500 ! ((grp_F4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4280 / 2) >> 16)
                dc.w 1
