byte_2E69E4:    dc.b   0,  6,$6C,$70,$8A,$8E,$7A,$7C,$7C,$77
                                        ; DATA XREF: ROM:off_1C70   o
                dc.w sprite_32_24
                dc.w $6869
                dc.w $9500 ! ((grp_12C7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $586A
                dc.w $9500 ! ((grp_83600 / 2) & $00FF)
                dc.w $9600 ! (((grp_83600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8869
                dc.w $9500 ! ((grp_83680 / 2) & $00FF)
                dc.w $9600 ! (((grp_83680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83680 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6F89
                dc.w $9500 ! ((grp_9B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7381
                dc.w $9500 ! ((grp_189BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189BE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8F89
                dc.w $9500 ! ((grp_EC9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC9A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $986A
                dc.w $9500 ! ((grp_EC9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC9C0 / 2) >> 16)
                dc.w 1
