byte_2EC3CC:    dc.b   0,  2,$77,$7B,$8A,$8D,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_20D8   o
                dc.w sprite_16_24
                dc.w $7B79
                dc.w $9500 ! ((grp_17B180 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B180 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7385
                dc.w $9500 ! ((grp_EFA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFA00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B79
                dc.w $9500 ! ((grp_EFA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFA20 / 2) >> 16)
                dc.w 1
