byte_2FB5AE:    dc.b   0,  3,$77,$62,$84,$8D,$7D,$77,$7E,$77
                                        ; DATA XREF: ROM:off_2F74   o
                dc.w sprite_16_16
                dc.w $7B68
                dc.w $9500 ! ((grp_92900 / 2) & $00FF)
                dc.w $9600 ! (((grp_92900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B78
                dc.w $9500 ! ((grp_1A00E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A00E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A00E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7560
                dc.w $9500 ! ((grp_DF580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7378
                dc.w $9500 ! ((grp_C5000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5000 / 2) >> 16)
                dc.w 2
