byte_2D52EE:    dc.b   0,  5,$6F,$4F,$8E,$8F,$76,$65,$7A,$54
                                        ; DATA XREF: ROM:off_117C   o
                dc.w sprite_24_32
                dc.w $6B52
                dc.w $9500 ! ((grp_FE8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $624A
                dc.w $9500 ! ((grp_98380 / 2) & $00FF)
                dc.w $9600 ! (((grp_98380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7272
                dc.w $9500 ! ((grp_CB780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $635F
                dc.w $9500 ! ((grp_E5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $717A
                dc.w $9500 ! ((grp_E5FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8271
                dc.w $9500 ! ((grp_E6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6000 / 2) >> 16)
                dc.w 1
