byte_2EE216:    dc.b   0,  7,$6A,$6B,$97,$92,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_2374   o
                dc.w sprite_32_24
                dc.w $7170
                dc.w $9500 ! ((grp_1327C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1327C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1327C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7568
                dc.w $9500 ! ((grp_18D120 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D120 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7688
                dc.w $9500 ! ((grp_18D180 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D180 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6973
                dc.w $9500 ! ((grp_19CDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CDE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9173
                dc.w $9500 ! ((grp_19CE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CE40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7790
                dc.w $9500 ! ((grp_D9240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $617B
                dc.w $9500 ! ((grp_BF300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $997B
                dc.w $9500 ! ((grp_BF340 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF340 / 2) >> 16)
                dc.w 2
