byte_2E2CF4:    dc.b   0,  9,$6F,$41,$8E,$8F,$82,$4A,$79,$4F
                                        ; DATA XREF: ROM:off_1A60   o
                dc.w sprite_32_32
                dc.w $7045
                dc.w $9500 ! ((grp_1E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1E800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6635
                dc.w $9500 ! ((grp_7FC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7564
                dc.w $9500 ! ((grp_99E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8C3F
                dc.w $9500 ! ((grp_1886E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1886E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1886E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6360
                dc.w $9500 ! ((grp_197BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197BC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B6C
                dc.w $9500 ! ((grp_D1400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $935E
                dc.w $9500 ! ((grp_D1440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6843
                dc.w $9500 ! ((grp_B8840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9047
                dc.w $9500 ! ((grp_EAB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAB60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9356
                dc.w $9500 ! ((grp_EAB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAB40 / 2) >> 16)
                dc.w 1
