byte_2D2DA2:    dc.b   0,  8,$79,$5E,$8A,$8E,$82,$76,$83,$76
                                        ; DATA XREF: ROM:off_F34   o
                dc.w sprite_16_16
                dc.w $7D69
                dc.w $9500 ! ((grp_77480 / 2) & $00FF)
                dc.w $9600 ! (((grp_77480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7D79
                dc.w $9500 ! ((grp_77380 / 2) & $00FF)
                dc.w $9600 ! (((grp_77380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7569
                dc.w $9500 ! ((grp_193DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193DE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7661
                dc.w $9500 ! ((grp_CA480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D6C
                dc.w $9500 ! ((grp_E4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7859
                dc.w $9500 ! ((grp_E4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8089
                dc.w $9500 ! ((grp_E4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7D
                dc.w $9500 ! ((grp_E4CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D6D
                dc.w $9500 ! ((grp_E4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C20 / 2) >> 16)
                dc.w 1
