byte_2F918E:    dc.b   0,  6,$72,$61,$97,$92,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_2D14   o
                dc.w sprite_24_32
                dc.w $7A75
                dc.w $9500 ! ((grp_11A340 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7A5D
                dc.w $9500 ! ((grp_152260 / 2) & $00FF)
                dc.w $9600 ! (((grp_152260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152260 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $7268
                dc.w $9500 ! ((grp_AE500 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $926C
                dc.w $9500 ! ((grp_AE580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6A6B
                dc.w $9500 ! ((grp_F65A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F65A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F65A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7288
                dc.w $9500 ! ((grp_F65C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F65C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F65C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9264
                dc.w $9500 ! ((grp_F6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6580 / 2) >> 16)
                dc.w 1
