byte_2D67C6:    dc.b   0,  7,$6F,$47,$9F,$7C,$87,$61,$88,$61
                                        ; DATA XREF: ROM:off_125C   o
                dc.w sprite_24_32
                dc.w $7A45
                dc.w $9500 ! ((grp_10B640 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7A65
                dc.w $9500 ! ((grp_161800 / 2) & $00FF)
                dc.w $9600 ! (((grp_161800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161800 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $9255
                dc.w $9500 ! ((grp_A7C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B5C
                dc.w $9500 ! ((grp_199540 / 2) & $00FF)
                dc.w $9600 ! (((grp_199540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199540 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7254
                dc.w $9500 ! ((grp_1995A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1995A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1995A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8875
                dc.w $9500 ! ((grp_D4700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A62
                dc.w $9500 ! ((grp_BB240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F7D
                dc.w $9500 ! ((grp_ECDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECDC0 / 2) >> 16)
                dc.w 1
