byte_2D08BE:    dc.b   0,  3,$55,$52,$AC,$8E,$7B,$81,$7C,$81
                                        ; DATA XREF: ROM:off_D9C   o
                dc.w sprite_32_16
                dc.w $717D
                dc.w $9500 ! ((grp_47F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $718D
                dc.w $9500 ! ((grp_C9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7975
                dc.w $9500 ! ((grp_C95C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C95C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C95C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697D
                dc.w $9500 ! ((grp_E3B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3B20 / 2) >> 16)
                dc.w 1
