byte_2F3442:    dc.b   0,  7,$5C,$5F,$9D,$8F,$7C,$77,$7D,$77
                                        ; DATA XREF: ROM:off_27AC   o
                dc.w sprite_32_24
                dc.w $707A
                dc.w $9500 ! ((grp_136CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_136CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7162
                dc.w $9500 ! ((grp_136B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_136B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $9164
                dc.w $9500 ! ((grp_8D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $745A
                dc.w $9500 ! ((grp_18E8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E8C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6965
                dc.w $9500 ! ((grp_19E040 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E040 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5970
                dc.w $9500 ! ((grp_DC000 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $907D
                dc.w $9500 ! ((grp_C1180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $987F
                dc.w $9500 ! ((grp_F3460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3460 / 2) >> 16)
                dc.w 1
