byte_2E6F2E:    dc.b   0,  4,$74,$53,$92,$78,$7D,$64,$75,$6B
                                        ; DATA XREF: ROM:off_1CA4   o
                dc.w sprite_32_24
                dc.w $7357
                dc.w $9500 ! ((grp_126AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_126AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6F4F
                dc.w $9500 ! ((grp_99100 / 2) & $00FF)
                dc.w $9600 ! (((grp_99100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F6F
                dc.w $9500 ! ((grp_186CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_186CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6B5F
                dc.w $9500 ! ((grp_B6740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7477
                dc.w $9500 ! ((grp_E8C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8C20 / 2) >> 16)
                dc.w 1
