byte_2CD57C:    dc.b   0,  1,$78,$79,$88,$8D,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8E0   o
                dc.w sprite_24_24
                dc.w $7678
                dc.w $9500 ! ((grp_13E0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E0A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7A70
                dc.w $9500 ! ((grp_C7140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7140 / 2) >> 16)
                dc.w 2
