byte_2EC928:    dc.b   0,  2,$79,$7F,$90,$8D,$84,$86,$85,$86
                                        ; DATA XREF: ROM:off_2178   o
                dc.w sprite_32_16
                dc.w $7781
                dc.w $9500 ! ((grp_51B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_51B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8479
                dc.w $9500 ! ((grp_D8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7779
                dc.w $9500 ! ((grp_EFEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFEA0 / 2) >> 16)
                dc.w 1
