byte_2E9F5A:    dc.b   0,  4,$92,$58,$B2,$67,$A3,$63,$A4,$63
                                        ; DATA XREF: ROM:off_1EEC   o
                dc.w sprite_32_32
                dc.w $9852
                dc.w $9500 ! ((grp_28400 / 2) & $00FF)
                dc.w $9600 ! (((grp_28400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8852
                dc.w $9500 ! ((grp_17A280 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A280 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8055
                dc.w $9500 ! ((grp_BD9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B860
                dc.w $9500 ! ((grp_BD980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A572
                dc.w $9500 ! ((grp_EEDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEDC0 / 2) >> 16)
                dc.w 1
