byte_2D825E:    dc.b   0,  3,$6D,$67,$87,$7E,$80,$60,$87,$67
                                        ; DATA XREF: ROM:off_1374   o
                dc.w sprite_32_32
                dc.w $6C66
                dc.w $9500 ! ((grp_19400 / 2) & $00FF)
                dc.w $9600 ! (((grp_19400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $735E
                dc.w $9500 ! ((grp_1854A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1854A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1854A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6477
                dc.w $9500 ! ((grp_E6B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E86
                dc.w $9500 ! ((grp_E6B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6B20 / 2) >> 16)
                dc.w 1
