byte_2D6AF2:    dc.b   0,  9,$74,$55,$92,$A0,$81,$44,$82,$59
                                        ; DATA XREF: ROM:off_127C   o
                dc.w sprite_24_24
                dc.w $7162
                dc.w $9500 ! ((grp_148A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_148A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148A80 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $577A
                dc.w $9500 ! ((grp_50800 / 2) & $00FF)
                dc.w $9600 ! (((grp_50800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8969
                dc.w $9500 ! ((grp_162D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_162D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $5967
                dc.w $9500 ! ((grp_18B020 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B020 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7842
                dc.w $9500 ! ((grp_D64C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D64C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D64C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $777A
                dc.w $9500 ! ((grp_BCAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E52
                dc.w $9500 ! ((grp_BCB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A5F
                dc.w $9500 ! ((grp_EE3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE3E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $668A
                dc.w $9500 ! ((grp_EE400 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $804A
                dc.w $9500 ! ((grp_EE420 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE420 / 2) >> 16)
                dc.w 1
