byte_2F9ECC:    dc.b   0, $E,$79,$5F,$90,$8E,$7B,$70,$7C,$70
                                        ; DATA XREF: ROM:off_2DE0   o
                dc.w sprite_24_32
                dc.w $6B67
                dc.w $9500 ! ((grp_11A7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8367
                dc.w $9500 ! ((grp_6FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $5A58
                dc.w $9500 ! ((grp_A0300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B87
                dc.w $9500 ! ((grp_1901E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1901E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1901E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $738F
                dc.w $9500 ! ((grp_190240 / 2) & $00FF)
                dc.w $9600 ! (((grp_190240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190240 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $815F
                dc.w $9500 ! ((grp_1902A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1902A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1902A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $715F
                dc.w $9500 ! ((grp_DE9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C4F
                dc.w $9500 ! ((grp_DE7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8257
                dc.w $9500 ! ((grp_DE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8387
                dc.w $9500 ! ((grp_DE840 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $636C
                dc.w $9500 ! ((grp_C44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C44C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9369
                dc.w $9500 ! ((grp_C4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B74
                dc.w $9500 ! ((grp_F6D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A57
                dc.w $9500 ! ((grp_F6E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $995F
                dc.w $9500 ! ((grp_F6D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D80 / 2) >> 16)
                dc.w 1
