byte_2E78B4:    dc.b   0,  9,$6F,$6A,$8E,$8F,$AF,$7D,$74,$68
                                        ; DATA XREF: ROM:off_1D00   o
                dc.w sprite_32_24
                dc.w $6B63
                dc.w $9500 ! ((grp_128D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_128D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $8962
                dc.w $9500 ! ((grp_99B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $727B
                dc.w $9500 ! ((grp_188140 / 2) & $00FF)
                dc.w $9600 ! (((grp_188140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188140 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7683
                dc.w $9500 ! ((grp_1881A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1881A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1881A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708A
                dc.w $9500 ! ((grp_D0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $848B
                dc.w $9500 ! ((grp_D0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B6E
                dc.w $9500 ! ((grp_D0BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9075
                dc.w $9500 ! ((grp_D0C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6367
                dc.w $9500 ! ((grp_B8200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A16A
                dc.w $9500 ! ((grp_EA2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA2A0 / 2) >> 16)
                dc.w 1
