byte_2EB8C0:    dc.b   0, $E,$49,$62,$CE,$90,$8B,$79,$8C,$79
                                        ; DATA XREF: ROM:off_2058   o
                dc.w sprite_32_32
                dc.w $8475
                dc.w $9500 ! ((grp_2C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5C65
                dc.w $9500 ! ((grp_110440 / 2) & $00FF)
                dc.w $9600 ! (((grp_110440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $A473
                dc.w $9500 ! ((grp_1105C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1105C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1105C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $8465
                dc.w $9500 ! ((grp_51300 / 2) & $00FF)
                dc.w $9600 ! (((grp_51300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $4C6D
                dc.w $9500 ! ((grp_67F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7465
                dc.w $9500 ! ((grp_68100 / 2) & $00FF)
                dc.w $9600 ! (((grp_68100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $A463
                dc.w $9500 ! ((grp_163900 / 2) & $00FF)
                dc.w $9600 ! (((grp_163900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $C465
                dc.w $9500 ! ((grp_87800 / 2) & $00FF)
                dc.w $9600 ! (((grp_87800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6485
                dc.w $9500 ! ((grp_9CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $BC62
                dc.w $9500 ! ((grp_19BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BD00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A8D
                dc.w $9500 ! ((grp_D7D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4483
                dc.w $9500 ! ((grp_EF680 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5C85
                dc.w $9500 ! ((grp_EF6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BC87
                dc.w $9500 ! ((grp_EF700 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C45D
                dc.w $9500 ! ((grp_EF720 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF720 / 2) >> 16)
                dc.w 1
