byte_2EFCC0:    dc.b   0,  1,$74,$7E,$88,$8D,$7E,$85,$7F,$85
                                        ; DATA XREF: ROM:off_2588   o
                dc.w sprite_24_16
                dc.w $7280
                dc.w $9500 ! ((grp_165AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_165AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7B78
                dc.w $9500 ! ((grp_DA040 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA040 / 2) >> 16)
                dc.w 2
