byte_2F8B7E:    dc.b   0,  6,$67,$81,$97,$A0,$7F,$90,$80,$90
                                        ; DATA XREF: ROM:off_2CBC   o
                dc.w sprite_24_24
                dc.w $757F
                dc.w $9500 ! ((grp_151F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_151F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151F00 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6D9F
                dc.w $9500 ! ((grp_9FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D99
                dc.w $9500 ! ((grp_DE080 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D85
                dc.w $9500 ! ((grp_C3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6597
                dc.w $9500 ! ((grp_F6260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D97
                dc.w $9500 ! ((grp_F6280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D8C
                dc.w $9500 ! ((grp_F62A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F62A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F62A0 / 2) >> 16)
                dc.w 1
