byte_2CD7AE:    dc.b   0,  3,$65,$4F,$75,$5B,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_914   o
                dc.w sprite_24_16
                dc.w $5E4A
                dc.w $9500 ! ((grp_156A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_156A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $744E
                dc.w $9500 ! ((grp_73E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_73E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5E5A
                dc.w $9500 ! ((grp_C7B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E6A
                dc.w $9500 ! ((grp_E1DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1DE0 / 2) >> 16)
                dc.w 1
