byte_2E4828:    dc.b   0,  4,$71,$58,$8D,$96,$7F,$77,$80,$77
                                        ; DATA XREF: ROM:off_1B48   o
                dc.w sprite_24_32
                dc.w $7266
                dc.w $9500 ! ((grp_109CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_109CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7086
                dc.w $9500 ! ((grp_4ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4ED00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7356
                dc.w $9500 ! ((grp_4EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $8A76
                dc.w $9500 ! ((grp_B9E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8396
                dc.w $9500 ! ((grp_EC1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC1A0 / 2) >> 16)
                dc.w 1
