byte_2CF2E0:    dc.b   0,  7,$65,$69,$91,$94,$81,$78,$82,$78
                                        ; DATA XREF: ROM:off_B50   o
                dc.w sprite_32_32
                dc.w $635A
                dc.w $9500 ! ((grp_13600 / 2) & $00FF)
                dc.w $9600 ! (((grp_13600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $637A
                dc.w $9500 ! ((grp_120640 / 2) & $00FF)
                dc.w $9600 ! (((grp_120640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $9372
                dc.w $9500 ! ((grp_74B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_74B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8374
                dc.w $9500 ! ((grp_A3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B62
                dc.w $9500 ! ((grp_A3300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $835C
                dc.w $9500 ! ((grp_1928E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1928E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1928E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6792
                dc.w $9500 ! ((grp_C85C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C85C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C85C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B82
                dc.w $9500 ! ((grp_B14C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B14C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B14C0 / 2) >> 16)
                dc.w 2
