byte_2D221A:    dc.b   0,  2,$76,$A8,$8B,$B7,$89,$B2,$8A,$B2
                                        ; DATA XREF: ROM:off_EA4   o
                dc.w sprite_24_8
                dc.w $75AA
                dc.w $9500 ! ((grp_184600 / 2) & $00FF)
                dc.w $9600 ! (((grp_184600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184600 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $73B2
                dc.w $9500 ! ((grp_B2740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8BB2
                dc.w $9500 ! ((grp_E4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4300 / 2) >> 16)
                dc.w 1
