byte_2EFBB8:    dc.b   0,  3,$74,$75,$8B,$89,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_2570   o
                dc.w sprite_16_24
                dc.w $7873
                dc.w $9500 ! ((grp_17C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C500 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $707C
                dc.w $9500 ! ((grp_F12E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F12E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F12E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F8B
                dc.w $9500 ! ((grp_F0F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $887C
                dc.w $9500 ! ((grp_F12C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F12C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F12C0 / 2) >> 16)
                dc.w 1
