byte_2F1A9C:    dc.b   0,  7,$72,$45,$9A,$71,$86,$5D,$87,$5D
                                        ; DATA XREF: ROM:off_26A8   o
                dc.w sprite_32_16
                dc.w $744B
                dc.w $9500 ! ((grp_54800 / 2) & $00FF)
                dc.w $9600 ! (((grp_54800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54800 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $705B
                dc.w $9500 ! ((grp_9EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8063
                dc.w $9500 ! ((grp_DAE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $905B
                dc.w $9500 ! ((grp_C04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C04C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C43
                dc.w $9500 ! ((grp_F2120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F6E
                dc.w $9500 ! ((grp_F2160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $816B
                dc.w $9500 ! ((grp_F2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $985E
                dc.w $9500 ! ((grp_F2140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2140 / 2) >> 16)
                dc.w 1
