byte_2E05AC:    dc.b   0,  9,$52,$4B,$94,$89,$73,$6A,$7B,$51
                                        ; DATA XREF: ROM:off_18C8   o
                dc.w sprite_16_32
                dc.w $7849
                dc.w $9500 ! ((grp_63E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7869
                dc.w $9500 ! ((grp_63F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $886A
                dc.w $9500 ! ((grp_64000 / 2) & $00FF)
                dc.w $9600 ! (((grp_64000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5071
                dc.w $9500 ! ((grp_81680 / 2) & $00FF)
                dc.w $9600 ! (((grp_81680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6869
                dc.w $9500 ! ((grp_A7280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $704C
                dc.w $9500 ! ((grp_A7300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $706C
                dc.w $9500 ! ((grp_A7380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7889
                dc.w $9500 ! ((grp_D2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6859
                dc.w $9500 ! ((grp_B9900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $606E
                dc.w $9500 ! ((grp_EBB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBB80 / 2) >> 16)
                dc.w 1
