byte_2D6F6A:    dc.b   0,  7,$74,$55,$92,$7A,$80,$4E,$8D,$50
                                        ; DATA XREF: ROM:off_12A4   o
                dc.w sprite_24_24
                dc.w $7A4A
                dc.w $9500 ! ((grp_148CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_148CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148CC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7A62
                dc.w $9500 ! ((grp_66900 / 2) & $00FF)
                dc.w $9600 ! (((grp_66900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6A53
                dc.w $9500 ! ((grp_17A040 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A040 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9259
                dc.w $9500 ! ((grp_19A9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A9E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $625B
                dc.w $9500 ! ((grp_BCEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A60
                dc.w $9500 ! ((grp_BCF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D82
                dc.w $9500 ! ((grp_EE5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE5C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A74
                dc.w $9500 ! ((grp_EE5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE5E0 / 2) >> 16)
                dc.w 1
