byte_2EB3C2:    dc.b   0,  4,$7F,$5B,$8F,$6C,$81,$64,$82,$64
                                        ; DATA XREF: ROM:off_2004   o
                dc.w sprite_16_24
                dc.w $7859
                dc.w $9500 ! ((grp_17AC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AC40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8857
                dc.w $9500 ! ((grp_AA400 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6D51
                dc.w $9500 ! ((grp_18BF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BF80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $905D
                dc.w $9500 ! ((grp_19BAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BAC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7871
                dc.w $9500 ! ((grp_EF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF4C0 / 2) >> 16)
                dc.w 1
