byte_2D5340:    dc.b   0,  4,$6F,$57,$8E,$8F,$7B,$6B,$7D,$5E
                                        ; DATA XREF: ROM:off_1180   o
                dc.w sprite_32_24
                dc.w $6C58
                dc.w $9500 ! ((grp_123940 / 2) & $00FF)
                dc.w $9600 ! (((grp_123940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6A70
                dc.w $9500 ! ((grp_15A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A000 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6F50
                dc.w $9500 ! ((grp_1851A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1851A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1851A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A80
                dc.w $9500 ! ((grp_CB7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8278
                dc.w $9500 ! ((grp_E6020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6020 / 2) >> 16)
                dc.w 1
