byte_2D39EC:    dc.b   0,  3,$77,$68,$90,$84,$81,$74,$82,$74
                                        ; DATA XREF: ROM:off_1050   o
                dc.w sprite_24_16
                dc.w $7C73
                dc.w $9500 ! ((grp_158E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_158E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7C63
                dc.w $9500 ! ((grp_76E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6C6C
                dc.w $9500 ! ((grp_CA080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D83
                dc.w $9500 ! ((grp_CA0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA0C0 / 2) >> 16)
                dc.w 2
