byte_2DE6D2:    dc.b   0,  8,$67,$51,$87,$8D,$75,$6D,$73,$52
                                        ; DATA XREF: ROM:off_177C   o
                dc.w sprite_32_32
                dc.w $6C4B
                dc.w $9500 ! ((grp_26000 / 2) & $00FF)
                dc.w $9600 ! (((grp_26000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7473
                dc.w $9500 ! ((grp_65600 / 2) & $00FF)
                dc.w $9600 ! (((grp_65600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5C4E
                dc.w $9500 ! ((grp_178E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_178E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6269
                dc.w $9500 ! ((grp_84B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8480
                dc.w $9500 ! ((grp_84B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $756B
                dc.w $9500 ! ((grp_D5000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C83
                dc.w $9500 ! ((grp_BB880 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5458
                dc.w $9500 ! ((grp_ED680 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $866F
                dc.w $9500 ! ((grp_ED6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED6A0 / 2) >> 16)
                dc.w 1
