byte_2D487E:    dc.b   0,  5,$6C,$5F,$96,$91,$83,$7B,$82,$6D
                                        ; DATA XREF: ROM:off_10FC   o
                dc.w sprite_32_32
                dc.w $7075
                dc.w $9500 ! ((grp_18400 / 2) & $00FF)
                dc.w $9600 ! (((grp_18400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6073
                dc.w $9500 ! ((grp_78280 / 2) & $00FF)
                dc.w $9600 ! (((grp_78280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7865
                dc.w $9500 ! ((grp_78200 / 2) & $00FF)
                dc.w $9600 ! (((grp_78200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $907B
                dc.w $9500 ! ((grp_1944A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1944A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1944A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9579
                dc.w $9500 ! ((grp_CB180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C5D
                dc.w $9500 ! ((grp_E5CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5CC0 / 2) >> 16)
                dc.w 1
