byte_2FFA36:    dc.b   0,  4,$77,$1C,$87,$82,$7F,$50,$80,$50
                                        ; DATA XREF: ROM:off_35BC   o
                dc.w sprite_16_32
                dc.w $791D
                dc.w $9500 ! ((grp_72200 / 2) & $00FF)
                dc.w $9600 ! (((grp_72200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7A3D
                dc.w $9500 ! ((grp_72300 / 2) & $00FF)
                dc.w $9600 ! (((grp_72300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7B7D
                dc.w $9500 ! ((grp_E0D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C5D
                dc.w $9500 ! ((grp_C65C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C65C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C65C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B75
                dc.w $9500 ! ((grp_F9600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9600 / 2) >> 16)
                dc.w 1
