byte_2DA6E2:    dc.b   0,  8,$56,$53,$78,$8C,$67,$6F,$68,$6F
                                        ; DATA XREF: ROM:off_14AC   o
                dc.w sprite_8_32
                dc.w $5452
                dc.w $9500 ! ((grp_A4F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7474
                dc.w $9500 ! ((grp_A4F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $744C
                dc.w $9500 ! ((grp_195220 / 2) & $00FF)
                dc.w $9600 ! (((grp_195220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6C54
                dc.w $9500 ! ((grp_B48C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B48C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B48C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7064
                dc.w $9500 ! ((grp_B4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C4C
                dc.w $9500 ! ((grp_E6FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $644C
                dc.w $9500 ! ((grp_E5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $686C
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C4C
                dc.w $9500 ! ((grp_E7000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7000 / 2) >> 16)
                dc.w 1
