byte_2E8E56:    dc.b   0,  4,$7C,$59,$84,$89,$81,$6F,$7C,$65
                                        ; DATA XREF: ROM:off_1DE4   o
                dc.w sprite_16_16
                dc.w $7B6C
                dc.w $9500 ! ((grp_7F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7C7C
                dc.w $9500 ! ((grp_7F880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7360
                dc.w $9500 ! ((grp_B8740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B5C
                dc.w $9500 ! ((grp_B8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F54
                dc.w $9500 ! ((grp_EA8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA8C0 / 2) >> 16)
                dc.w 1
