byte_2E2B28:    dc.b   0,  9,$55,$5F,$9D,$8C,$79,$75,$7A,$75
                                        ; DATA XREF: ROM:off_1A50   o
                dc.w sprite_32_32
                dc.w $5D5D
                dc.w $9500 ! ((grp_23800 / 2) & $00FF)
                dc.w $9600 ! (((grp_23800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7D65
                dc.w $9500 ! ((grp_109B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_109B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $5D7D
                dc.w $9500 ! ((grp_4EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $8685
                dc.w $9500 ! ((grp_189820 / 2) & $00FF)
                dc.w $9600 ! (((grp_189820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189820 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $956D
                dc.w $9500 ! ((grp_D3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5079
                dc.w $9500 ! ((grp_EC180 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $557D
                dc.w $9500 ! ((grp_EC100 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $638D
                dc.w $9500 ! ((grp_EC120 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_EC140 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $957D
                dc.w $9500 ! ((grp_EC160 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC160 / 2) >> 16)
                dc.w 1
