byte_2F6E18:    dc.b   0,$16,$7B,$4D,$A2,$82,$85,$7C,$86,$7C
                                        ; DATA XREF: ROM:off_2B70   o
                dc.w sprite_24_32
                dc.w $8659
                dc.w $9500 ! ((grp_117340 / 2) & $00FF)
                dc.w $9600 ! (((grp_117340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7649
                dc.w $9500 ! ((grp_6E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_169180 / 2) & $00FF)
                dc.w $9600 ! (((grp_169180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169180 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8649
                dc.w $9500 ! ((grp_1690C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1690C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1690C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $B631
                dc.w $9500 ! ((grp_169840 / 2) & $00FF)
                dc.w $9600 ! (((grp_169840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $AE41
                dc.w $9500 ! ((grp_17F440 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $C141
                dc.w $9500 ! ((grp_17F500 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9E50
                dc.w $9500 ! ((grp_8EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AF63
                dc.w $9500 ! ((grp_8FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $4781
                dc.w $9500 ! ((grp_DD3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6788
                dc.w $9500 ! ((grp_DD400 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7786
                dc.w $9500 ! ((grp_C2CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A7A
                dc.w $9500 ! ((grp_C2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A94
                dc.w $9500 ! ((grp_F5460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C79
                dc.w $9500 ! ((grp_F4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F41
                dc.w $9500 ! ((grp_F4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9282
                dc.w $9500 ! ((grp_F5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E60
                dc.w $9500 ! ((grp_F4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A648
                dc.w $9500 ! ((grp_F4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A660
                dc.w $9500 ! ((grp_F4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A771
                dc.w $9500 ! ((grp_F54A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F54A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F54A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $CD54
                dc.w $9500 ! ((grp_F54C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F54C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F54C0 / 2) >> 16)
                dc.w 1
