byte_2EC0FC:    dc.b   0,  1,$73,$74,$8E,$8D,$80,$80,$81,$80
                                        ; DATA XREF: ROM:off_20A8   o
                dc.w sprite_32_24
                dc.w $7178
                dc.w $9500 ! ((grp_1315C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1315C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1315C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7570
                dc.w $9500 ! ((grp_18C340 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C340 / 2) >> 16)
                dc.w 3
