byte_2DFB50:    dc.b   0,  5,$62,$68,$90,$8E,$79,$7B,$67,$6F
                                        ; DATA XREF: ROM:off_1850   o
                dc.w sprite_32_32
                dc.w $6871
                dc.w $9500 ! ((grp_1F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1F400 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8871
                dc.w $9500 ! ((grp_A6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6769
                dc.w $9500 ! ((grp_188F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_188F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $606D
                dc.w $9500 ! ((grp_1986A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1986A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1986A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6861
                dc.w $9500 ! ((grp_D2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $907D
                dc.w $9500 ! ((grp_EB6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB6A0 / 2) >> 16)
                dc.w 1
