byte_2EDCE8:    dc.b   0,  4,$72,$67,$98,$95,$84,$7B,$85,$7B
                                        ; DATA XREF: ROM:off_2308   o
                dc.w sprite_16_32
                dc.w $7F6F
                dc.w $9500 ! ((grp_68B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7770
                dc.w $9500 ! ((grp_AAD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8167
                dc.w $9500 ! ((grp_18CC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CC40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6F80
                dc.w $9500 ! ((grp_BEB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F6F
                dc.w $9500 ! ((grp_F00C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F00C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F00C0 / 2) >> 16)
                dc.w 1
