byte_2EB408:    dc.b   0,  2,$83,$51,$91,$62,$83,$59,$84,$59
                                        ; DATA XREF: ROM:off_2008   o
                dc.w sprite_24_16
                dc.w $7B4E
                dc.w $9500 ! ((grp_163780 / 2) & $00FF)
                dc.w $9600 ! (((grp_163780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163780 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $825E
                dc.w $9500 ! ((grp_18BFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BFE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B4E
                dc.w $9500 ! ((grp_D7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7A80 / 2) >> 16)
                dc.w 2
