byte_2F2EF6:    dc.b   0,  5,$71,$5E,$90,$95,$83,$7A,$84,$7A
                                        ; DATA XREF: ROM:off_277C   o
                dc.w sprite_24_32
                dc.w $7658
                dc.w $9500 ! ((grp_115540 / 2) & $00FF)
                dc.w $9600 ! (((grp_115540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7180
                dc.w $9500 ! ((grp_6D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8980
                dc.w $9500 ! ((grp_17E180 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E180 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7178
                dc.w $9500 ! ((grp_9F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6E5C
                dc.w $9500 ! ((grp_19DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DF80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8180
                dc.w $9500 ! ((grp_C1080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1080 / 2) >> 16)
                dc.w 2
