byte_2F10F6:    dc.b   0,  9,$6A,$50,$A9,$80,$8F,$68,$90,$68
                                        ; DATA XREF: ROM:off_262C   o
                dc.w sprite_32_32
                dc.w $7C4A
                dc.w $9500 ! ((grp_38400 / 2) & $00FF)
                dc.w $9600 ! (((grp_38400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $6462
                dc.w $9500 ! ((grp_113D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_113D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7C6A
                dc.w $9500 ! ((grp_134D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_134D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $9C52
                dc.w $9500 ! ((grp_166F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_166F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6C52
                dc.w $9500 ! ((grp_8C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6C82
                dc.w $9500 ! ((grp_DB100 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D7F
                dc.w $9500 ! ((grp_DB140 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9C4A
                dc.w $9500 ! ((grp_DB180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C62
                dc.w $9500 ! ((grp_C05C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C05C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C05C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $B45A
                dc.w $9500 ! ((grp_F2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2400 / 2) >> 16)
                dc.w 1
