byte_2E3F2C:    dc.b   0, $D,$65,$77,$98,$A9,$4F,$47,$4F,$42
                                        ; DATA XREF: ROM:off_1B10   o
                dc.w sprite_24_24
                dc.w $727D
                dc.w $9500 ! ((grp_143860 / 2) & $00FF)
                dc.w $9600 ! (((grp_143860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143860 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $8AA9
                dc.w $9500 ! ((grp_4A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8A91
                dc.w $9500 ! ((grp_174400 / 2) & $00FF)
                dc.w $9600 ! (((grp_174400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174400 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $5B75
                dc.w $9500 ! ((grp_98E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $4B45
                dc.w $9500 ! ((grp_CDAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $5C6D
                dc.w $9500 ! ((grp_CDB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A95
                dc.w $9500 ! ((grp_CDB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4E4D
                dc.w $9500 ! ((grp_B5BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5355
                dc.w $9500 ! ((grp_B5B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B5D
                dc.w $9500 ! ((grp_B5B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A7D
                dc.w $9500 ! ((grp_B5B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4B3D
                dc.w $9500 ! ((grp_E8240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5572
                dc.w $9500 ! ((grp_E8260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A95
                dc.w $9500 ! ((grp_E8280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8280 / 2) >> 16)
                dc.w 1
