byte_2E7EC8:    dc.b   0,  9,$77,$60,$8B,$80,$61,$79,$60,$6A
                                        ; DATA XREF: ROM:off_1D38   o
                dc.w sprite_32_16
                dc.w $765E
                dc.w $9500 ! ((grp_4D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $746E
                dc.w $9500 ! ((grp_176380 / 2) & $00FF)
                dc.w $9600 ! (((grp_176380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $5E5E
                dc.w $9500 ! ((grp_188440 / 2) & $00FF)
                dc.w $9600 ! (((grp_188440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188440 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5C66
                dc.w $9500 ! ((grp_D1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C6E
                dc.w $9500 ! ((grp_B85C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B85C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B85C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6476
                dc.w $9500 ! ((grp_B8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8476
                dc.w $9500 ! ((grp_B8640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C70
                dc.w $9500 ! ((grp_B8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9468
                dc.w $9500 ! ((grp_B86C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B86C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B86C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C7E
                dc.w $9500 ! ((grp_EA7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA7A0 / 2) >> 16)
                dc.w 1
