byte_2D4B90:    dc.b   0,  5,$5F,$54,$9C,$7F,$7D,$69,$7E,$69
                                        ; DATA XREF: ROM:off_1120   o
                dc.w sprite_32_16
                dc.w $6852
                dc.w $9500 ! ((grp_4C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8855
                dc.w $9500 ! ((grp_175FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_175FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $9662
                dc.w $9500 ! ((grp_A6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $585A
                dc.w $9500 ! ((grp_D0880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6262
                dc.w $9500 ! ((grp_D08C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D08C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D08C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7862
                dc.w $9500 ! ((grp_D0840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0840 / 2) >> 16)
                dc.w 2
