byte_2D0002:    dc.b   0,  1,$79,$6D,$88,$7E,$80,$75,$81,$75
                                        ; DATA XREF: ROM:off_CB4   o
                dc.w sprite_16_24
                dc.w $776B
                dc.w $9500 ! ((grp_170BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_170BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8770
                dc.w $9500 ! ((grp_B1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1880 / 2) >> 16)
                dc.w 2
