byte_2EC46C:    dc.b   0,  2,$75,$73,$88,$8D,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_20E8   o
                dc.w sprite_16_24
                dc.w $7A79
                dc.w $9500 ! ((grp_17B240 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B240 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $727F
                dc.w $9500 ! ((grp_BE500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8371
                dc.w $9500 ! ((grp_EFA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFA40 / 2) >> 16)
                dc.w 1
