byte_2D6B74:    dc.b   0,  9,$73,$55,$92,$A0,$81,$40,$80,$59
                                        ; DATA XREF: ROM:off_1280   o
                dc.w sprite_24_32
                dc.w $686E
                dc.w $9500 ! ((grp_10D5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5886
                dc.w $9500 ! ((grp_86100 / 2) & $00FF)
                dc.w $9600 ! (((grp_86100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $586E
                dc.w $9500 ! ((grp_86180 / 2) & $00FF)
                dc.w $9600 ! (((grp_86180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $784E
                dc.w $9500 ! ((grp_A9100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F3E
                dc.w $9500 ! ((grp_A9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $805E
                dc.w $9500 ! ((grp_A9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $678E
                dc.w $9500 ! ((grp_BCB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8871
                dc.w $9500 ! ((grp_BCB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9076
                dc.w $9500 ! ((grp_BCBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9875
                dc.w $9500 ! ((grp_BCC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCC00 / 2) >> 16)
                dc.w 2
