byte_2E002C:    dc.b   0,  3,$6A,$65,$93,$8E,$7E,$79,$7E,$6F
                                        ; DATA XREF: ROM:off_1888   o
                dc.w sprite_32_32
                dc.w $6873
                dc.w $9500 ! ((grp_20800 / 2) & $00FF)
                dc.w $9600 ! (((grp_20800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8873
                dc.w $9500 ! ((grp_63400 / 2) & $00FF)
                dc.w $9600 ! (((grp_63400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63400 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6B6B
                dc.w $9500 ! ((grp_9A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7363
                dc.w $9500 ! ((grp_1890A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1890A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1890A0 / 2) >> 16)
                dc.w 3
