byte_2FA30E:    dc.b   0,  6,$75,$52,$8C,$8E,$7F,$6D,$80,$6D
                                        ; DATA XREF: ROM:off_2DFC   o
                dc.w sprite_32_32
                dc.w $7152
                dc.w $9500 ! ((grp_41E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_41E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7172
                dc.w $9500 ! ((grp_42000 / 2) & $00FF)
                dc.w $9600 ! (((grp_42000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $595A
                dc.w $9500 ! ((grp_16A980 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $614A
                dc.w $9500 ! ((grp_91680 / 2) & $00FF)
                dc.w $9600 ! (((grp_91680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9952
                dc.w $9500 ! ((grp_91700 / 2) & $00FF)
                dc.w $9600 ! (((grp_91700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9153
                dc.w $9500 ! ((grp_AE780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $714A
                dc.w $9500 ! ((grp_190660 / 2) & $00FF)
                dc.w $9600 ! (((grp_190660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190660 / 2) >> 16)
                dc.w 3
