byte_2FF1F6:    dc.b   0,  2,$16,$71,$41,$8C,$2B,$7E,$2C,$7E
                                        ; DATA XREF: ROM:off_355C   o
                dc.w sprite_32_32
                dc.w $246F
                dc.w $9500 ! ((grp_45800 / 2) & $00FF)
                dc.w $9600 ! (((grp_45800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_45800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $1477
                dc.w $9500 ! ((grp_182D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_182D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $146F
                dc.w $9500 ! ((grp_F9140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9140 / 2) >> 16)
                dc.w 1
