byte_2F5188:    dc.b   0,  4,$6F,$60,$8D,$98,$7B,$7C,$7C,$7C
                                        ; DATA XREF: ROM:off_2A40   o
                dc.w sprite_32_32
                dc.w $7075
                dc.w $9500 ! ((grp_3C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $745D
                dc.w $9500 ! ((grp_168700 / 2) & $00FF)
                dc.w $9600 ! (((grp_168700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168700 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $706D
                dc.w $9500 ! ((grp_18EBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EBC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7695
                dc.w $9500 ! ((grp_18EC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EC20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $687E
                dc.w $9500 ! ((grp_C1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1CC0 / 2) >> 16)
                dc.w 2
