byte_2DA38E:    dc.b   0,  5,$56,$53,$76,$6D,$66,$60,$67,$60
                                        ; DATA XREF: ROM:off_1494   o
                dc.w sprite_32_8
                dc.w $594C
                dc.w $9500 ! ((grp_99480 / 2) & $00FF)
                dc.w $9600 ! (((grp_99480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $515C
                dc.w $9500 ! ((grp_196DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_196DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196DE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7154
                dc.w $9500 ! ((grp_196E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_196E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $514C
                dc.w $9500 ! ((grp_E9460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5254
                dc.w $9500 ! ((grp_E9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C6C
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
