byte_2E8E1C:    dc.b   0,  3,$78,$5C,$83,$7A,$7C,$66,$82,$61
                                        ; DATA XREF: ROM:off_1DE0   o
                dc.w sprite_16_32
                dc.w $775E
                dc.w $9500 ! ((grp_61500 / 2) & $00FF)
                dc.w $9600 ! (((grp_61500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61500 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6F63
                dc.w $9500 ! ((grp_196840 / 2) & $00FF)
                dc.w $9600 ! (((grp_196840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196840 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7C4E
                dc.w $9500 ! ((grp_B6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $797E
                dc.w $9500 ! ((grp_E8BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8BA0 / 2) >> 16)
                dc.w 1
