byte_2D3652:    dc.b   0,  4,$75,$5B,$88,$95,$81,$78,$82,$78
                                        ; DATA XREF: ROM:off_101C   o
                dc.w sprite_24_24
                dc.w $715A
                dc.w $9500 ! ((grp_1404A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1404A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1404A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7672
                dc.w $9500 ! ((grp_1405C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1405C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1405C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7B8A
                dc.w $9500 ! ((grp_77700 / 2) & $00FF)
                dc.w $9600 ! (((grp_77700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6E7A
                dc.w $9500 ! ((grp_E4F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E76
                dc.w $9500 ! ((grp_E4F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4F60 / 2) >> 16)
                dc.w 1
