byte_2D2AF0:    dc.b   0,  4,$71,$5B,$90,$81,$7F,$6E,$80,$6E
                                        ; DATA XREF: ROM:off_F10   o
                dc.w sprite_24_32
                dc.w $7561
                dc.w $9500 ! ((grp_FD3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6B59
                dc.w $9500 ! ((grp_97E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_97E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8D68
                dc.w $9500 ! ((grp_193CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193CC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8280
                dc.w $9500 ! ((grp_CA380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D6A
                dc.w $9500 ! ((grp_E4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4B00 / 2) >> 16)
                dc.w 1
