byte_2D1410:    dc.b   0,  7,$61,$61,$9E,$8D,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_E08   o
                dc.w sprite_32_32
                dc.w $6861
                dc.w $9500 ! ((grp_15600 / 2) & $00FF)
                dc.w $9600 ! (((grp_15600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $8868
                dc.w $9500 ! ((grp_13F3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F3C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6881
                dc.w $9500 ! ((grp_47B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6067
                dc.w $9500 ! ((grp_A3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8860
                dc.w $9500 ! ((grp_C93C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C93C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C93C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9480
                dc.w $9500 ! ((grp_C9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5873
                dc.w $9500 ! ((grp_B1C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A071
                dc.w $9500 ! ((grp_B1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1CC0 / 2) >> 16)
                dc.w 2
