byte_2D0FEA:    dc.b   0,  9,$45,$61,$78,$8F,$5E,$76,$5F,$76
                                        ; DATA XREF: ROM:off_DE4   o
                dc.w sprite_32_24
                dc.w $6779
                dc.w $9500 ! ((grp_1210C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1210C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1210C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $9F65
                dc.w $9500 ! ((grp_121240 / 2) & $00FF)
                dc.w $9600 ! (((grp_121240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6F61
                dc.w $9500 ! ((grp_13EF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_13EF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13EF40 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $8F5A
                dc.w $9500 ! ((grp_5D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9F55
                dc.w $9500 ! ((grp_76180 / 2) & $00FF)
                dc.w $9600 ! (((grp_76180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A07D
                dc.w $9500 ! ((grp_76200 / 2) & $00FF)
                dc.w $9600 ! (((grp_76200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8763
                dc.w $9500 ! ((grp_A3980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F5B
                dc.w $9500 ! ((grp_C9100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F7D
                dc.w $9500 ! ((grp_B1B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F7A
                dc.w $9500 ! ((grp_E37E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E37E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E37E0 / 2) >> 16)
                dc.w 1
