byte_2D269A:    dc.b   0, $A,$5D,$4A,$A3,$73,$79,$7B,$7A,$7B
                                        ; DATA XREF: ROM:off_EEC   o
                dc.w sprite_24_32
                dc.w $615C
                dc.w $9500 ! ((grp_FD240 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $795B
                dc.w $9500 ! ((grp_121FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_121FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $697B
                dc.w $9500 ! ((grp_97D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_97D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $596A
                dc.w $9500 ! ((grp_A4180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $617C
                dc.w $9500 ! ((grp_A4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6983
                dc.w $9500 ! ((grp_184660 / 2) & $00FF)
                dc.w $9600 ! (((grp_184660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184660 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7973
                dc.w $9500 ! ((grp_1846C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1846C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1846C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $698B
                dc.w $9500 ! ((grp_C9F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $598A
                dc.w $9500 ! ((grp_B27C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B27C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B27C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6993
                dc.w $9500 ! ((grp_E43E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E43E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E43E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9963
                dc.w $9500 ! ((grp_E4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4400 / 2) >> 16)
                dc.w 1
