byte_2D29CC:    dc.b   0,  2,$5D,$4A,$A3,$73,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_F00   o
                dc.w sprite_16_16
                dc.w $836F
                dc.w $9500 ! ((grp_76D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6B8E
                dc.w $9500 ! ((grp_E4560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7386
                dc.w $9500 ! ((grp_E4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4580 / 2) >> 16)
                dc.w 1
