byte_2F2A6C:    dc.b   0, $B,$5F,$78,$9C,$95,$81,$83,$82,$83
                                        ; DATA XREF: ROM:off_2748   o
                dc.w sprite_16_32
                dc.w $5B7D
                dc.w $9500 ! ((grp_6CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6B76
                dc.w $9500 ! ((grp_6CB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7B77
                dc.w $9500 ! ((grp_6CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8B74
                dc.w $9500 ! ((grp_6CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $9B6C
                dc.w $9500 ! ((grp_ACB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $A36C
                dc.w $9500 ! ((grp_19DB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DB60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C6F
                dc.w $9500 ! ((grp_DB6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $537E
                dc.w $9500 ! ((grp_C0940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB6C
                dc.w $9500 ! ((grp_C0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6275
                dc.w $9500 ! ((grp_F2820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $786D
                dc.w $9500 ! ((grp_F2840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C6C
                dc.w $9500 ! ((grp_F2860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2860 / 2) >> 16)
                dc.w 1
