byte_2CDECE:    dc.b   0,  4,$67,$5E,$93,$81,$7D,$6F,$7E,$6F
                                        ; DATA XREF: ROM:off_9D4   o
                dc.w sprite_32_32
                dc.w $7264
                dc.w $9500 ! ((grp_12200 / 2) & $00FF)
                dc.w $9600 ! (((grp_12200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $725C
                dc.w $9500 ! ((grp_97000 / 2) & $00FF)
                dc.w $9600 ! (((grp_97000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A63
                dc.w $9500 ! ((grp_A2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6265
                dc.w $9500 ! ((grp_B0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $926A
                dc.w $9500 ! ((grp_E23A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E23A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E23A0 / 2) >> 16)
                dc.w 1
