byte_2F1B06:    dc.b   0,  6,$6B,$45,$9A,$70,$82,$5D,$83,$5D
                                        ; DATA XREF: ROM:off_26AC   o
                dc.w sprite_24_24
                dc.w $6E4B
                dc.w $9500 ! ((grp_14E7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E7E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $865B
                dc.w $9500 ! ((grp_8C080 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $806B
                dc.w $9500 ! ((grp_DAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6656
                dc.w $9500 ! ((grp_F2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C43
                dc.w $9500 ! ((grp_F21E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F21E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F21E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C53
                dc.w $9500 ! ((grp_F21A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F21A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F21A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9661
                dc.w $9500 ! ((grp_F21C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F21C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F21C0 / 2) >> 16)
                dc.w 1
