byte_2FDDF0:    dc.b   0,  6,$75,$48,$91,$8D,$83,$6A,$84,$6A
                                        ; DATA XREF: ROM:off_3350   o
                dc.w sprite_16_32
                dc.w $7668
                dc.w $9500 ! ((grp_71500 / 2) & $00FF)
                dc.w $9600 ! (((grp_71500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7648
                dc.w $9500 ! ((grp_71400 / 2) & $00FF)
                dc.w $9600 ! (((grp_71400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $865D
                dc.w $9500 ! ((grp_AEF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_191560 / 2) & $00FF)
                dc.w $9600 ! (((grp_191560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6E67
                dc.w $9500 ! ((grp_1A05C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A05C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A05C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8E5E
                dc.w $9500 ! ((grp_1A0620 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7A40
                dc.w $9500 ! ((grp_F86A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F86A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F86A0 / 2) >> 16)
                dc.w 1
