byte_2FB864:    dc.b   0, $D,$82,$30,$EF,$7D,$B8,$56,$B9,$56
                                        ; DATA XREF: ROM:off_2FA8   o
                dc.w sprite_32_32
                dc.w $9046
                dc.w $9500 ! ((grp_43400 / 2) & $00FF)
                dc.w $9600 ! (((grp_43400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $9066
                dc.w $9500 ! ((grp_43600 / 2) & $00FF)
                dc.w $9600 ! (((grp_43600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $B046
                dc.w $9500 ! ((grp_43800 / 2) & $00FF)
                dc.w $9600 ! (((grp_43800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $B066
                dc.w $9500 ! ((grp_43A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_43A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $D066
                dc.w $9500 ! ((grp_43C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_43C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $902E
                dc.w $9500 ! ((grp_13ABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13ABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13ABC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $B02E
                dc.w $9500 ! ((grp_13AD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_13AD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13AD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $D04E
                dc.w $9500 ! ((grp_13AEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13AEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13AEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8046
                dc.w $9500 ! ((grp_70500 / 2) & $00FF)
                dc.w $9600 ! (((grp_70500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8066
                dc.w $9500 ! ((grp_70600 / 2) & $00FF)
                dc.w $9600 ! (((grp_70600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70600 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $D03E
                dc.w $9500 ! ((grp_16B280 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $802E
                dc.w $9500 ! ((grp_180B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_180B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $F063
                dc.w $9500 ! ((grp_19FD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FD20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $D036
                dc.w $9500 ! ((grp_F78C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F78C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F78C0 / 2) >> 16)
                dc.w 1
