byte_2F57A2:    dc.b   0,  3,$61,$91,$A0,$9E,$80,$96,$81,$96
                                        ; DATA XREF: ROM:off_2ACC   o
                dc.w sprite_32_16
                dc.w $5C8D
                dc.w $9500 ! ((grp_56200 / 2) & $00FF)
                dc.w $9600 ! (((grp_56200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7C8E
                dc.w $9500 ! ((grp_56300 / 2) & $00FF)
                dc.w $9600 ! (((grp_56300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9C8E
                dc.w $9500 ! ((grp_8EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $669D
                dc.w $9500 ! ((grp_DCE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCE00 / 2) >> 16)
                dc.w 2
