byte_2F00B0:    dc.b   0,  8,$44,$45,$BD,$94,$80,$8D,$81,$8D
                                        ; DATA XREF: ROM:off_25B8   o
                dc.w sprite_32_16
                dc.w $417C
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $997C
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8184
                dc.w $9500 ! ((grp_166180 / 2) & $00FF)
                dc.w $9600 ! (((grp_166180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $617C
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7184
                dc.w $9500 ! ((grp_8B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8694
                dc.w $9500 ! ((grp_8B480 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B480 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $797C
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $B97C
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $717C
                dc.w $9500 ! ((grp_F1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1480 / 2) >> 16)
                dc.w 1
