byte_2E53C0:    dc.b   0, $B,$6F,$63,$88,$8E,$3E,$97,$6D,$64
                                        ; DATA XREF: ROM:off_1BB8   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A160
                dc.w $9500 ! ((grp_82900 / 2) & $00FF)
                dc.w $9600 ! (((grp_82900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6965
                dc.w $9500 ! ((grp_1899A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1899A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1899A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8968
                dc.w $9500 ! ((grp_189A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_189A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5963
                dc.w $9500 ! ((grp_D3800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7653
                dc.w $9500 ! ((grp_D3840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA580 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8168
                dc.w $9500 ! ((grp_BA5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $695D
                dc.w $9500 ! ((grp_EC4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC4E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7257
                dc.w $9500 ! ((grp_EC500 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC500 / 2) >> 16)
                dc.w 1
