byte_2FD18E:    dc.b   0,  1,$78,$76,$8D,$81,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:off_32AC   o
                dc.w sprite_24_16
                dc.w $7674
                dc.w $9500 ! ((grp_16D080 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D080 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8E7C
                dc.w $9500 ! ((grp_F8180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8180 / 2) >> 16)
                dc.w 1
