byte_2FD7D6:    dc.b   0,  6,$5F,$49,$8B,$8D,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_330C   o
                dc.w sprite_16_24
                dc.w $7E71
                dc.w $9500 ! ((grp_181F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_181F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7547
                dc.w $9500 ! ((grp_95200 / 2) & $00FF)
                dc.w $9600 ! (((grp_95200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7C61
                dc.w $9500 ! ((grp_95280 / 2) & $00FF)
                dc.w $9600 ! (((grp_95280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95280 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7489
                dc.w $9500 ! ((grp_A0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7757
                dc.w $9500 ! ((grp_F8440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $795F
                dc.w $9500 ! ((grp_F8420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $854C
                dc.w $9500 ! ((grp_F8460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8460 / 2) >> 16)
                dc.w 1
