byte_2E7A72:    dc.b   0,  7,$75,$68,$8D,$89,$7F,$5F,$87,$69
                                        ; DATA XREF: ROM:off_1D14   o
                dc.w sprite_24_32
                dc.w $705E
                dc.w $9500 ! ((grp_105AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_105AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $737E
                dc.w $9500 ! ((grp_7F480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8865
                dc.w $9500 ! ((grp_197860 / 2) & $00FF)
                dc.w $9600 ! (((grp_197860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197860 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7656
                dc.w $9500 ! ((grp_D0D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $965F
                dc.w $9500 ! ((grp_B8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6860
                dc.w $9500 ! ((grp_EA420 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $877D
                dc.w $9500 ! ((grp_EA440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9068
                dc.w $9500 ! ((grp_EA460 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA460 / 2) >> 16)
                dc.w 1
