byte_2F8C46:    dc.b   0,  7,$65,$83,$9A,$A7,$7F,$95,$80,$95
                                        ; DATA XREF: ROM:off_2CC4   o
                dc.w sprite_24_32
                dc.w $7381
                dc.w $9500 ! ((grp_119BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_119BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $73A2
                dc.w $9500 ! ((grp_18FAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FAC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8BA1
                dc.w $9500 ! ((grp_18FB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FB20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8B91
                dc.w $9500 ! ((grp_DE100 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B89
                dc.w $9500 ! ((grp_C3A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $639E
                dc.w $9500 ! ((grp_F6340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6BA1
                dc.w $9500 ! ((grp_F6360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B89
                dc.w $9500 ! ((grp_F6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6380 / 2) >> 16)
                dc.w 1
