byte_2F97D4:    dc.b   0,  6,$6D,$6B,$96,$92,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_2D90   o
                dc.w sprite_32_16
                dc.w $6C79
                dc.w $9500 ! ((grp_57300 / 2) & $00FF)
                dc.w $9600 ! (((grp_57300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $7B69
                dc.w $9500 ! ((grp_C4240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7071
                dc.w $9500 ! ((grp_F6A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $748B
                dc.w $9500 ! ((grp_F6A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8491
                dc.w $9500 ! ((grp_F6A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8974
                dc.w $9500 ! ((grp_F6A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6A60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9088
                dc.w $9500 ! ((grp_F6A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6A00 / 2) >> 16)
                dc.w 1
