byte_2FD9B8:    dc.b   0,  4,$6E,$64,$AE,$8D,$8E,$78,$8F,$78
                                        ; DATA XREF: ROM:off_3320   o
                dc.w sprite_24_32
                dc.w $6A70
                dc.w $9500 ! ((grp_11CA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11CA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11CA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $8173
                dc.w $9500 ! ((grp_13B340 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $A162
                dc.w $9500 ! ((grp_71000 / 2) & $00FF)
                dc.w $9600 ! (((grp_71000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8288
                dc.w $9500 ! ((grp_F8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A182
                dc.w $9500 ! ((grp_F8520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8520 / 2) >> 16)
                dc.w 1
