byte_2CC7FA:    dc.b   0,  3,$5D,$7A,$8C,$99,$74,$89,$75,$89
                                        ; DATA XREF: ROM:off_7C4   o
                dc.w sprite_32_24
                dc.w $6F78
                dc.w $9500 ! ((grp_11E240 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5F85
                dc.w $9500 ! ((grp_72D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_72D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $578C
                dc.w $9500 ! ((grp_E1520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5D94
                dc.w $9500 ! ((grp_E1540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1540 / 2) >> 16)
                dc.w 1
