byte_2E842C:    dc.b   0,  9,$6F,$6B,$8E,$8F,$5E,$80,$62,$64
                                        ; DATA XREF: ROM:off_1D68   o
                dc.w sprite_32_24
                dc.w $6F6D
                dc.w $9500 ! ((grp_126940 / 2) & $00FF)
                dc.w $9600 ! (((grp_126940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $5F5D
                dc.w $9500 ! ((grp_15C880 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C880 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8F6C
                dc.w $9500 ! ((grp_7BD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5765
                dc.w $9500 ! ((grp_A5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F85
                dc.w $9500 ! ((grp_186880 / 2) & $00FF)
                dc.w $9600 ! (((grp_186880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186880 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B8D
                dc.w $9500 ! ((grp_CE180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE180 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838C
                dc.w $9500 ! ((grp_CE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F7D
                dc.w $9500 ! ((grp_E86E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E86E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E86E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $676D
                dc.w $9500 ! ((grp_E8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7765
                dc.w $9500 ! ((grp_E5940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5940 / 2) >> 16)
                dc.w 1
