byte_2FC202:    dc.b   0,  1,$6B,$8C,$76,$9B,$70,$93,$71,$93
                                        ; DATA XREF: ROM:off_30C4   o
                dc.w sprite_16_16
                dc.w $698A
                dc.w $9500 ! ((grp_92C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_92C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6A9A
                dc.w $9500 ! ((grp_F7DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7DA0 / 2) >> 16)
                dc.w 1
