byte_2E071A:    dc.b   0,  4,$6A,$5C,$94,$87,$7F,$71,$90,$6C
                                        ; DATA XREF: ROM:off_18D4   o
                dc.w sprite_24_32
                dc.w $686A
                dc.w $9500 ! ((grp_109240 / 2) & $00FF)
                dc.w $9600 ! (((grp_109240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $8068
                dc.w $9500 ! ((grp_1093C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1093C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1093C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $8058
                dc.w $9500 ! ((grp_15FF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FF40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6862
                dc.w $9500 ! ((grp_189100 / 2) & $00FF)
                dc.w $9600 ! (((grp_189100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189100 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $705A
                dc.w $9500 ! ((grp_D2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2C80 / 2) >> 16)
                dc.w 2
