byte_2ED978:    dc.b   0,  5,$6B,$63,$A6,$94,$87,$79,$88,$79
                                        ; DATA XREF: ROM:off_22E0   o
                dc.w sprite_32_32
                dc.w $8063
                dc.w $9500 ! ((grp_31000 / 2) & $00FF)
                dc.w $9600 ! (((grp_31000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6881
                dc.w $9500 ! ((grp_89700 / 2) & $00FF)
                dc.w $9600 ! (((grp_89700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $787F
                dc.w $9500 ! ((grp_89780 / 2) & $00FF)
                dc.w $9600 ! (((grp_89780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8583
                dc.w $9500 ! ((grp_89680 / 2) & $00FF)
                dc.w $9600 ! (((grp_89680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A063
                dc.w $9500 ! ((grp_AAF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $786B
                dc.w $9500 ! ((grp_F03A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F03A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F03A0 / 2) >> 16)
                dc.w 1
