byte_2F9A9A:    dc.b   0,  4,$6A,$7C,$97,$8F,$83,$85,$84,$85
                                        ; DATA XREF: ROM:off_2DBC   o
                dc.w sprite_32_24
                dc.w $667A
                dc.w $9500 ! ((grp_139FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_139FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $867A
                dc.w $9500 ! ((grp_152920 / 2) & $00FF)
                dc.w $9600 ! (((grp_152920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152920 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $9E8A
                dc.w $9500 ! ((grp_DE740 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E82
                dc.w $9500 ! ((grp_C4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9E82
                dc.w $9500 ! ((grp_F6D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D20 / 2) >> 16)
                dc.w 1
