byte_2CFB74:    dc.b   0,  2,$72,$77,$8D,$88,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_C10   o
                dc.w sprite_24_16
                dc.w $707B
                dc.w $9500 ! ((grp_1573C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1573C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1573C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7873
                dc.w $9500 ! ((grp_C8940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8875
                dc.w $9500 ! ((grp_B16C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B16C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B16C0 / 2) >> 16)
                dc.w 2
