byte_2ED9CA:    dc.b   0,  6,$71,$66,$B3,$94,$8F,$7A,$90,$7A
                                        ; DATA XREF: ROM:off_22E4   o
                dc.w sprite_32_24
                dc.w $966C
                dc.w $9500 ! ((grp_132640 / 2) & $00FF)
                dc.w $9600 ! (((grp_132640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6789
                dc.w $9500 ! ((grp_9DB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F81
                dc.w $9500 ! ((grp_18CFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CFA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $9E64
                dc.w $9500 ! ((grp_18D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $877C
                dc.w $9500 ! ((grp_19C9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C9C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8E6C
                dc.w $9500 ! ((grp_19CA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CA20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F84
                dc.w $9500 ! ((grp_BEEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEEC0 / 2) >> 16)
                dc.w 2
