byte_2D9690:    dc.b   0,  3,$6F,$5C,$8D,$8E,$7E,$75,$7F,$60
                                        ; DATA XREF: ROM:off_1438   o
                dc.w sprite_32_32
                dc.w $6D69
                dc.w $9500 ! ((grp_1C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1C200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7959
                dc.w $9500 ! ((grp_7CA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C71
                dc.w $9500 ! ((grp_A5A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7489
                dc.w $9500 ! ((grp_186E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_186E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186E20 / 2) >> 16)
                dc.w 3
