byte_2D2880:    dc.b   0, $C,$5D,$4A,$A3,$73,$79,$7B,$7A,$7B
                                        ; DATA XREF: ROM:off_EF8   o
                dc.w sprite_32_24
                dc.w $785A
                dc.w $9500 ! ((grp_1222C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1222C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1222C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $685A
                dc.w $9500 ! ((grp_5E300 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $5879
                dc.w $9500 ! ((grp_A4780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6060
                dc.w $9500 ! ((grp_A4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6080
                dc.w $9500 ! ((grp_A4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $687A
                dc.w $9500 ! ((grp_A4900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $707A
                dc.w $9500 ! ((grp_193A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_193A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7872
                dc.w $9500 ! ((grp_193A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_193A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5869
                dc.w $9500 ! ((grp_B2940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8072
                dc.w $9500 ! ((grp_B2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $507A
                dc.w $9500 ! ((grp_E44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E44C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8872
                dc.w $9500 ! ((grp_E4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9862
                dc.w $9500 ! ((grp_E44E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E44E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E44E0 / 2) >> 16)
                dc.w 1
