byte_2F417A:    dc.b   0,  2,$7A,$79,$87,$88,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28E4   o
                dc.w sprite_8_24
                dc.w $7B77
                dc.w $9500 ! ((grp_19E0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E0A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $737E
                dc.w $9500 ! ((grp_C1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8377
                dc.w $9500 ! ((grp_C12C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C12C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C12C0 / 2) >> 16)
                dc.w 2
