byte_2DB15A:    dc.b   0,  8,$6B,$61,$9F,$8E,$85,$77,$86,$77
                                        ; DATA XREF: ROM:off_1534   o
                dc.w sprite_32_16
                dc.w $6E6A
                dc.w $9500 ! ((grp_4FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8D63
                dc.w $9500 ! ((grp_85780 / 2) & $00FF)
                dc.w $9600 ! (((grp_85780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85780 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7582
                dc.w $9500 ! ((grp_9B680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6C62
                dc.w $9500 ! ((grp_18A7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A7E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $767A
                dc.w $9500 ! ((grp_18A840 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A840 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_D5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A8A
                dc.w $9500 ! ((grp_D5CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $666A
                dc.w $9500 ! ((grp_BC100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A5F
                dc.w $9500 ! ((grp_EDC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDC80 / 2) >> 16)
                dc.w 1
