byte_2CF9E2:    dc.b   0,  1,$78,$7F,$86,$85,$7F,$82,$80,$82
                                        ; DATA XREF: ROM:off_BD4   o
                dc.w sprite_16_16
                dc.w $767D
                dc.w $9500 ! ((grp_74E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_74E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8681
                dc.w $9500 ! ((grp_E2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2F00 / 2) >> 16)
                dc.w 1
