byte_2F3F58:    dc.b   0,  8,$6F,$6B,$93,$96,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28C0   o
                dc.w sprite_16_24
                dc.w $757D
                dc.w $9500 ! ((grp_17E480 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8575
                dc.w $9500 ! ((grp_ACD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7B6D
                dc.w $9500 ! ((grp_18E9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E9E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7093
                dc.w $9500 ! ((grp_DC240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7575
                dc.w $9500 ! ((grp_DC280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8265
                dc.w $9500 ! ((grp_DC2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D75
                dc.w $9500 ! ((grp_C11C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C11C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C11C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7F
                dc.w $9500 ! ((grp_F3A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3A60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9575
                dc.w $9500 ! ((grp_F3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3480 / 2) >> 16)
                dc.w 1
