byte_2DB58C:    dc.b   0, $C,$62,$53,$A2,$90,$82,$71,$83,$71
                                        ; DATA XREF: ROM:off_1558   o
                dc.w sprite_16_32
                dc.w $7361
                dc.w $9500 ! ((grp_65E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8353
                dc.w $9500 ! ((grp_A8900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8373
                dc.w $9500 ! ((grp_A8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6362
                dc.w $9500 ! ((grp_D5F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6D89
                dc.w $9500 ! ((grp_D5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9360
                dc.w $9500 ! ((grp_D5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B51
                dc.w $9500 ! ((grp_BC2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B5E
                dc.w $9500 ! ((grp_BC300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6066
                dc.w $9500 ! ((grp_EDE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDE00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7351
                dc.w $9500 ! ((grp_EDE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDE20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7581
                dc.w $9500 ! ((grp_EDE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDE40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B8B
                dc.w $9500 ! ((grp_EDE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDE60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D67
                dc.w $9500 ! ((grp_EDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDE80 / 2) >> 16)
                dc.w 1
