byte_2F7636:    dc.b   0, $C,$64,$42,$9E,$83,$89,$5F,$8A,$5F
                                        ; DATA XREF: ROM:off_2B9C   o
                dc.w sprite_32_32
                dc.w $6757
                dc.w $9500 ! ((grp_3EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3EE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6E38
                dc.w $9500 ! ((grp_3F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3F000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8758
                dc.w $9500 ! ((grp_118840 / 2) & $00FF)
                dc.w $9600 ! (((grp_118840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7777
                dc.w $9500 ! ((grp_90300 / 2) & $00FF)
                dc.w $9600 ! (((grp_90300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E48
                dc.w $9500 ! ((grp_90380 / 2) & $00FF)
                dc.w $9600 ! (((grp_90380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A649
                dc.w $9500 ! ((grp_90400 / 2) & $00FF)
                dc.w $9600 ! (((grp_90400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $5D59
                dc.w $9500 ! ((grp_C3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6647
                dc.w $9500 ! ((grp_C31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C31C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F51
                dc.w $9500 ! ((grp_F5BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F77
                dc.w $9500 ! ((grp_F5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8778
                dc.w $9500 ! ((grp_F5C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E40
                dc.w $9500 ! ((grp_F5C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E49
                dc.w $9500 ! ((grp_F5C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5C60 / 2) >> 16)
                dc.w 1
