byte_2E9F14:    dc.b   0,  4,$91,$5B,$B0,$69,$A0,$67,$A1,$67
                                        ; DATA XREF: ROM:off_1EE8   o
                dc.w sprite_32_32
                dc.w $8D55
                dc.w $9500 ! ((grp_28200 / 2) & $00FF)
                dc.w $9600 ! (((grp_28200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28200 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $AD55
                dc.w $9500 ! ((grp_A9880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $855D
                dc.w $9500 ! ((grp_BD900 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B55D
                dc.w $9500 ! ((grp_BD940 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9975
                dc.w $9500 ! ((grp_EEDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEDA0 / 2) >> 16)
                dc.w 1
