byte_2D3F6A:    dc.b   0,  6,$73,$65,$9B,$8F,$88,$7D,$89,$7D
                                        ; DATA XREF: ROM:off_1094   o
                dc.w sprite_32_24
                dc.w $7B69
                dc.w $9500 ! ((grp_123340 / 2) & $00FF)
                dc.w $9600 ! (((grp_123340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123340 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6F80
                dc.w $9500 ! ((grp_49000 / 2) & $00FF)
                dc.w $9600 ! (((grp_49000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $9B69
                dc.w $9500 ! ((grp_194260 / 2) & $00FF)
                dc.w $9600 ! (((grp_194260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194260 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $677E
                dc.w $9500 ! ((grp_E5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7372
                dc.w $9500 ! ((grp_E5620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F81
                dc.w $9500 ! ((grp_E55E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E55E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E55E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A36E
                dc.w $9500 ! ((grp_E5640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5640 / 2) >> 16)
                dc.w 1
