byte_2D9582:    dc.b   0,  8,$68,$58,$92,$8E,$7D,$73,$7E,$73
                                        ; DATA XREF: ROM:off_142C   o
                dc.w sprite_32_16
                dc.w $6D81
                dc.w $9500 ! ((grp_4B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7671
                dc.w $9500 ! ((grp_15CF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15CF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15CF40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8851
                dc.w $9500 ! ((grp_A5B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6E5E
                dc.w $9500 ! ((grp_196AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_196AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196AE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6656
                dc.w $9500 ! ((grp_B6B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6589
                dc.w $9500 ! ((grp_E8FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7669
                dc.w $9500 ! ((grp_E9000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8069
                dc.w $9500 ! ((grp_E9020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D89
                dc.w $9500 ! ((grp_E9040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9040 / 2) >> 16)
                dc.w 1
