byte_2D0B90:    dc.b   0, $A,$55,$60,$74,$8D,$71,$76,$72,$76
                                        ; DATA XREF: ROM:off_DC8   o
                dc.w sprite_32_24
                dc.w $605D
                dc.w $9500 ! ((grp_120DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_120DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $805E
                dc.w $9500 ! ((grp_47400 / 2) & $00FF)
                dc.w $9600 ! (((grp_47400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $505B
                dc.w $9500 ! ((grp_5CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5CF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6875
                dc.w $9500 ! ((grp_170E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_170E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $487B
                dc.w $9500 ! ((grp_1841E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1841E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1841E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $4A83
                dc.w $9500 ! ((grp_C8F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $628C
                dc.w $9500 ! ((grp_C8F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8083
                dc.w $9500 ! ((grp_C8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $486B
                dc.w $9500 ! ((grp_B1A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6075
                dc.w $9500 ! ((grp_B1A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $787B
                dc.w $9500 ! ((grp_B1A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1A80 / 2) >> 16)
                dc.w 2
