byte_2FE43E:    dc.b   0,  4,$73,$79,$8C,$88,$7E,$84,$7F,$84
                                        ; DATA XREF: ROM:off_33D4   o
                dc.w sprite_32_16
                dc.w $6D77
                dc.w $9500 ! ((grp_59A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_59A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7B87
                dc.w $9500 ! ((grp_E0400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A87
                dc.w $9500 ! ((grp_F8AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $738D
                dc.w $9500 ! ((grp_F8AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D7F
                dc.w $9500 ! ((grp_F8AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8AE0 / 2) >> 16)
                dc.w 1
