byte_2DC1E0:    dc.b   0,  7,$75,$5C,$A3,$90,$90,$64,$91,$64
                                        ; DATA XREF: ROM:off_1600   o
                dc.w sprite_24_16
                dc.w $8B5B
                dc.w $9500 ! ((grp_163000 / 2) & $00FF)
                dc.w $9600 ! (((grp_163000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $896B
                dc.w $9500 ! ((grp_86780 / 2) & $00FF)
                dc.w $9600 ! (((grp_86780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $735E
                dc.w $9500 ! ((grp_19ABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ABC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9253
                dc.w $9500 ! ((grp_D6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A461
                dc.w $9500 ! ((grp_D6840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B5B
                dc.w $9500 ! ((grp_BD200 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $835D
                dc.w $9500 ! ((grp_BD240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B60
                dc.w $9500 ! ((grp_EE7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE7A0 / 2) >> 16)
                dc.w 1
