byte_2D3CB6:    dc.b   0,  6,$6E,$69,$8C,$85,$7D,$76,$7E,$76
                                        ; DATA XREF: ROM:off_1074   o
                dc.w sprite_16_24
                dc.w $7A70
                dc.w $9500 ! ((grp_171D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_171D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A66
                dc.w $9500 ! ((grp_77100 / 2) & $00FF)
                dc.w $9600 ! (((grp_77100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6976
                dc.w $9500 ! ((grp_CA300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A68
                dc.w $9500 ! ((grp_CA2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A6D
                dc.w $9500 ! ((grp_B2AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8260
                dc.w $9500 ! ((grp_E4A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E7D
                dc.w $9500 ! ((grp_E4A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4A40 / 2) >> 16)
                dc.w 1
