byte_2FD596:    dc.b   0,  7,$5F,$44,$8C,$8D,$83,$68,$84,$68
                                        ; DATA XREF: ROM:off_32F4   o
                dc.w sprite_16_16
                dc.w $784A
                dc.w $9500 ! ((grp_95180 / 2) & $00FF)
                dc.w $9600 ! (((grp_95180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A0D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8758
                dc.w $9500 ! ((grp_AEC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A80
                dc.w $9500 ! ((grp_DFD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D78
                dc.w $9500 ! ((grp_DFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F68
                dc.w $9500 ! ((grp_C5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7842
                dc.w $9500 ! ((grp_F83E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F83E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F83E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F5A
                dc.w $9500 ! ((grp_F8400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8400 / 2) >> 16)
                dc.w 1
