byte_2EB2F0:    dc.b   0,  4,$71,$70,$8A,$8D,$7D,$74,$7E,$74
                                        ; DATA XREF: ROM:off_1FF8   o
                dc.w sprite_24_32
                dc.w $766A
                dc.w $9500 ! ((grp_110140 / 2) & $00FF)
                dc.w $9600 ! (((grp_110140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $6E5A
                dc.w $9500 ! ((grp_D79C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D79C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D79C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7562
                dc.w $9500 ! ((grp_D7A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $778A
                dc.w $9500 ! ((grp_D7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E7F
                dc.w $9500 ! ((grp_BE100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE100 / 2) >> 16)
                dc.w 2
