byte_2EBE4C:    dc.b   0,  6,$84,$5B,$A1,$80,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:off_2080   o
                dc.w sprite_32_32
                dc.w $5567
                dc.w $9500 ! ((grp_2E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2E000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7568
                dc.w $9500 ! ((grp_2E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2E200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $9569
                dc.w $9500 ! ((grp_2E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_2E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2E400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $5687
                dc.w $9500 ! ((grp_9D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7688
                dc.w $9500 ! ((grp_18C220 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C220 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $9989
                dc.w $9500 ! ((grp_18C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4D6F
                dc.w $9500 ! ((grp_BE2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE2C0 / 2) >> 16)
                dc.w 2
