byte_2DD34C:    dc.b   0,  7,$78,$67,$8F,$83,$80,$75,$88,$66
                                        ; DATA XREF: ROM:off_16B0   o
                dc.w sprite_32_24
                dc.w $795C
                dc.w $9500 ! ((grp_1255C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1255C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1255C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $797C
                dc.w $9500 ! ((grp_15B680 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $615C
                dc.w $9500 ! ((grp_7A500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7974
                dc.w $9500 ! ((grp_CD100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7164
                dc.w $9500 ! ((grp_B4CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7178
                dc.w $9500 ! ((grp_E75A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E75A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E75A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $858C
                dc.w $9500 ! ((grp_E75C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E75C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E75C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9964
                dc.w $9500 ! ((grp_E75E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E75E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E75E0 / 2) >> 16)
                dc.w 1
