byte_2DE3D4:    dc.b   0,  9,$73,$5A,$91,$8E,$7F,$6E,$95,$56
                                        ; DATA XREF: ROM:off_1760   o
                dc.w sprite_32_16
                dc.w $745D
                dc.w $9500 ! ((grp_4FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7D75
                dc.w $9500 ! ((grp_65300 / 2) & $00FF)
                dc.w $9600 ! (((grp_65300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5C60
                dc.w $9500 ! ((grp_161EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_161EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $894D
                dc.w $9500 ! ((grp_161F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_161F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9463
                dc.w $9500 ! ((grp_84900 / 2) & $00FF)
                dc.w $9600 ! (((grp_84900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $746D
                dc.w $9500 ! ((grp_18A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A300 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D89
                dc.w $9500 ! ((grp_D4F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7581
                dc.w $9500 ! ((grp_ED3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED3C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $814E
                dc.w $9500 ! ((grp_ED3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED3E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D8A
                dc.w $9500 ! ((grp_ED400 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED400 / 2) >> 16)
                dc.w 1
