byte_2FB944:    dc.b   0,  6,$6A,$6E,$93,$93,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_2FB0   o
                dc.w sprite_24_32
                dc.w $686C
                dc.w $9500 ! ((grp_11BCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11BCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11BCC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $8084
                dc.w $9500 ! ((grp_16B1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6C8C
                dc.w $9500 ! ((grp_DF180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7994
                dc.w $9500 ! ((grp_F7800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $807C
                dc.w $9500 ! ((grp_F77E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F77E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F77E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_F7820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9074
                dc.w $9500 ! ((grp_F77C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F77C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F77C0 / 2) >> 16)
                dc.w 1
