byte_2F003A:    dc.b   0,  8,$44,$3E,$BC,$8B,$80,$8C,$81,$8C
                                        ; DATA XREF: ROM:off_25B4   o
                dc.w sprite_32_16
                dc.w $4179
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7981
                dc.w $9500 ! ((grp_53B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9979
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6179
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7979
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E91
                dc.w $9500 ! ((grp_18DBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DBA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8999
                dc.w $9500 ! ((grp_DA240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $717B
                dc.w $9500 ! ((grp_BFA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B979
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
