byte_2D05FE:    dc.b   0,  1,$65,$78,$72,$8A,$6B,$81,$6C,$81
                                        ; DATA XREF: ROM:off_D4C   o
                dc.w sprite_16_16
                dc.w $6276
                dc.w $9500 ! ((grp_75B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6C86
                dc.w $9500 ! ((grp_E34A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E34A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E34A0 / 2) >> 16)
                dc.w 1
