byte_2E2E56:    dc.b   0,  6,$6F,$40,$8E,$8F,$7F,$53,$81,$3A
                                        ; DATA XREF: ROM:off_1A6C   o
                dc.w sprite_32_24
                dc.w $7148
                dc.w $9500 ! ((grp_1294C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1294C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1294C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7960
                dc.w $9500 ! ((grp_4D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6F6F
                dc.w $9500 ! ((grp_7FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7540
                dc.w $9500 ! ((grp_1887A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1887A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1887A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $694B
                dc.w $9500 ! ((grp_197C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_197C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $615B
                dc.w $9500 ! ((grp_EABA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EABA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EABA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9158
                dc.w $9500 ! ((grp_EABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EABC0 / 2) >> 16)
                dc.w 1
