byte_2F7DEC:    dc.b   0,  4,$7B,$7C,$9C,$9E,$8B,$8D,$8C,$8D
                                        ; DATA XREF: ROM:off_2BD8   o
                dc.w sprite_8_24
                dc.w $837C
                dc.w $9500 ! ((grp_19F0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F0C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7B7C
                dc.w $9500 ! ((grp_C3000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8794
                dc.w $9500 ! ((grp_F58A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F58A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F58A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B81
                dc.w $9500 ! ((grp_F58E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F58E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F58E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9497
                dc.w $9500 ! ((grp_F58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F58C0 / 2) >> 16)
                dc.w 1
