byte_2EC23E:    dc.b   0,  4,$6D,$66,$92,$91,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_20C4   o
                dc.w sprite_32_32
                dc.w $7274
                dc.w $9500 ! ((grp_2F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_2F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2F800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $726C
                dc.w $9500 ! ((grp_9D480 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A6C
                dc.w $9500 ! ((grp_AAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7064
                dc.w $9500 ! ((grp_18C460 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C460 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9274
                dc.w $9500 ! ((grp_19BF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BF40 / 2) >> 16)
                dc.w 3
