byte_2EEA14:    dc.b   0,  4,$6A,$70,$93,$92,$7E,$81,$7F,$81
                                        ; DATA XREF: ROM:off_23F8   o
                dc.w sprite_32_32
                dc.w $716D
                dc.w $9500 ! ((grp_32C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_32C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $718D
                dc.w $9500 ! ((grp_9E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9175
                dc.w $9500 ! ((grp_AB900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6974
                dc.w $9500 ! ((grp_19D1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D1A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $617A
                dc.w $9500 ! ((grp_BF600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF600 / 2) >> 16)
                dc.w 2
