byte_2E486E:    dc.b   0,  5,$71,$5A,$8E,$9A,$7F,$7A,$80,$7A
                                        ; DATA XREF: ROM:off_1B4C   o
                dc.w sprite_32_24
                dc.w $7075
                dc.w $9500 ! ((grp_12C040 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $705D
                dc.w $9500 ! ((grp_146B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_146B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146B00 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7A8D
                dc.w $9500 ! ((grp_160480 / 2) & $00FF)
                dc.w $9600 ! (((grp_160480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6D58
                dc.w $9500 ! ((grp_EC1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC1C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $728D
                dc.w $9500 ! ((grp_EC200 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $825C
                dc.w $9500 ! ((grp_EC1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC1E0 / 2) >> 16)
                dc.w 1
