byte_2E0066:    dc.b   0,  5,$6B,$60,$94,$8D,$7F,$76,$7B,$67
                                        ; DATA XREF: ROM:off_188C   o
                dc.w sprite_24_32
                dc.w $6C70
                dc.w $9500 ! ((grp_108C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_108C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8470
                dc.w $9500 ! ((grp_63500 / 2) & $00FF)
                dc.w $9600 ! (((grp_63500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6C60
                dc.w $9500 ! ((grp_15FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FD00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9474
                dc.w $9500 ! ((grp_198820 / 2) & $00FF)
                dc.w $9600 ! (((grp_198820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198820 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7058
                dc.w $9500 ! ((grp_D2B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $646C
                dc.w $9500 ! ((grp_B9600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9600 / 2) >> 16)
                dc.w 2
