byte_2DE4FC:    dc.b   0,  7,$74,$61,$8A,$8E,$7B,$73,$81,$62
                                        ; DATA XREF: ROM:off_1768   o
                dc.w sprite_24_32
                dc.w $716E
                dc.w $9500 ! ((grp_10BF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10BF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10BF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $735E
                dc.w $9500 ! ((grp_162040 / 2) & $00FF)
                dc.w $9600 ! (((grp_162040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162040 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $718E
                dc.w $9500 ! ((grp_18A360 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A360 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $897A
                dc.w $9500 ! ((grp_199AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199AE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $617E
                dc.w $9500 ! ((grp_D4FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $917A
                dc.w $9500 ! ((grp_BB7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6973
                dc.w $9500 ! ((grp_ED500 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E56
                dc.w $9500 ! ((grp_ED520 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED520 / 2) >> 16)
                dc.w 1
