byte_2DFD32:    dc.b   0,  7,$62,$70,$91,$8E,$79,$7F,$63,$77
                                        ; DATA XREF: ROM:off_1864   o
                dc.w sprite_32_16
                dc.w $706E
                dc.w $9500 ! ((grp_4DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $687C
                dc.w $9500 ! ((grp_176EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_176EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $606C
                dc.w $9500 ! ((grp_81280 / 2) & $00FF)
                dc.w $9600 ! (((grp_81280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $787E
                dc.w $9500 ! ((grp_81300 / 2) & $00FF)
                dc.w $9600 ! (((grp_81300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $788E
                dc.w $9500 ! ((grp_188FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_188FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $607C
                dc.w $9500 ! ((grp_EB760 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8886
                dc.w $9500 ! ((grp_EB780 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9073
                dc.w $9500 ! ((grp_EB7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB7A0 / 2) >> 16)
                dc.w 1
