byte_2F496C:    dc.b   0,  6,$6A,$61,$9E,$94,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_29F8   o
                dc.w sprite_32_32
                dc.w $7562
                dc.w $9500 ! ((grp_3B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3B000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6982
                dc.w $9500 ! ((grp_55D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $898A
                dc.w $9500 ! ((grp_8DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8DF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9564
                dc.w $9500 ! ((grp_19E280 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7192
                dc.w $9500 ! ((grp_F3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8982
                dc.w $9500 ! ((grp_F3AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $998A
                dc.w $9500 ! ((grp_F3AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3AC0 / 2) >> 16)
                dc.w 1
