byte_2FD646:    dc.b   0,  7,$5F,$49,$8D,$8D,$82,$6B,$83,$6B
                                        ; DATA XREF: ROM:off_32FC   o
                dc.w sprite_16_32
                dc.w $7F60
                dc.w $9500 ! ((grp_71900 / 2) & $00FF)
                dc.w $9600 ! (((grp_71900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7646
                dc.w $9500 ! ((grp_95980 / 2) & $00FF)
                dc.w $9600 ! (((grp_95980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95980 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7188
                dc.w $9500 ! ((grp_A1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F80
                dc.w $9500 ! ((grp_E0300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7856
                dc.w $9500 ! ((grp_F87E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F87E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F87E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E58
                dc.w $9500 ! ((grp_F8800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8649
                dc.w $9500 ! ((grp_F8220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C4F
                dc.w $9500 ! ((grp_F8240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8240 / 2) >> 16)
                dc.w 1
