byte_2FE666:    dc.b   0,  1,$74,$76,$8B,$8A,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_3404   o
                dc.w sprite_16_24
                dc.w $7075
                dc.w $9500 ! ((grp_182A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_182A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8074
                dc.w $9500 ! ((grp_182980 / 2) & $00FF)
                dc.w $9600 ! (((grp_182980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182980 / 2) >> 16)
                dc.w 6
