byte_2D07CE:    dc.b   0,  1,$77,$79,$88,$89,$80,$81,$2B,$34
                                        ; DATA XREF: ROM:off_D84   o
                dc.w sprite_24_16
                dc.w $757C
                dc.w $9500 ! ((grp_157840 / 2) & $00FF)
                dc.w $9600 ! (((grp_157840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157840 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7574
                dc.w $9500 ! ((grp_E3540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3540 / 2) >> 16)
                dc.w 1
