byte_2FC73C:    dc.b   0, $C,$43,$5A,$B6,$B4,$7C,$93,$7D,$93
                                        ; DATA XREF: ROM:off_3130   o
                dc.w sprite_16_16
                dc.w $44A4
                dc.w $9500 ! ((grp_93780 / 2) & $00FF)
                dc.w $9600 ! (((grp_93780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AC74
                dc.w $9500 ! ((grp_93800 / 2) & $00FF)
                dc.w $9600 ! (((grp_93800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $54A1
                dc.w $9500 ! ((grp_C5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C9C
                dc.w $9500 ! ((grp_C5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6499
                dc.w $9500 ! ((grp_C54C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C54C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C54C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C94
                dc.w $9500 ! ((grp_C5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7491
                dc.w $9500 ! ((grp_C5540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C8C
                dc.w $9500 ! ((grp_C5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8489
                dc.w $9500 ! ((grp_C55C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C55C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C55C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C84
                dc.w $9500 ! ((grp_C5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9481
                dc.w $9500 ! ((grp_C5640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C7C
                dc.w $9500 ! ((grp_C5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A479
                dc.w $9500 ! ((grp_C56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C56C0 / 2) >> 16)
                dc.w 2
