byte_2D80B8:    dc.b   0,  5,$73,$5E,$92,$9A,$88,$80,$80,$6A
                                        ; DATA XREF: ROM:off_1360   o
                dc.w sprite_24_24
                dc.w $7072
                dc.w $9500 ! ((grp_141E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_141E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141E80 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8872
                dc.w $9500 ! ((grp_15A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7A8A
                dc.w $9500 ! ((grp_1732C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1732C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1732C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7C5A
                dc.w $9500 ! ((grp_194E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_194E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7EA2
                dc.w $9500 ! ((grp_E6A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A06E
                dc.w $9500 ! ((grp_E6A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6A20 / 2) >> 16)
                dc.w 1
