byte_2EF6F0:    dc.b   0,  5,$74,$54,$95,$6F,$84,$61,$85,$61
                                        ; DATA XREF: ROM:off_2510   o
                dc.w sprite_16_16
                dc.w $825A
                dc.w $9500 ! ((grp_8A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $725F
                dc.w $9500 ! ((grp_F1040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7452
                dc.w $9500 ! ((grp_F0F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A62
                dc.w $9500 ! ((grp_F1060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8653
                dc.w $9500 ! ((grp_F0F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9771
                dc.w $9500 ! ((grp_F0F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F60 / 2) >> 16)
                dc.w 1
