byte_2CE19C:    dc.b   0,  3,$93,$79,$A6,$8B,$9C,$82,$9D,$82
                                        ; DATA XREF: ROM:off_A08   o
                dc.w sprite_8_24
                dc.w $9777
                dc.w $9500 ! ((grp_191CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_191CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191CE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_E20E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E20E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E20E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F77
                dc.w $9500 ! ((grp_E20A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E20A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E20A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A286
                dc.w $9500 ! ((grp_E20C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E20C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E20C0 / 2) >> 16)
                dc.w 1
