byte_2EF832:    dc.b   0,  1,$72,$26,$82,$35,$7A,$2D,$7B,$2D
                                        ; DATA XREF: ROM:off_252C   o
                dc.w sprite_16_16
                dc.w $7320
                dc.w $9500 ! ((grp_8A780 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F30
                dc.w $9500 ! ((grp_18D720 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D720 / 2) >> 16)
                dc.w 3
