byte_2F7E78:    dc.b   0,  4,$7B,$7C,$A0,$B1,$8D,$96,$8E,$96
                                        ; DATA XREF: ROM:off_2BE0   o
                dc.w sprite_24_16
                dc.w $7B7C
                dc.w $9500 ! ((grp_169B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_169B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $828C
                dc.w $9500 ! ((grp_90280 / 2) & $00FF)
                dc.w $9600 ! (((grp_90280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8AA4
                dc.w $9500 ! ((grp_F5BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9592
                dc.w $9500 ! ((grp_F5B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9AAB
                dc.w $9500 ! ((grp_F5BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5BC0 / 2) >> 16)
                dc.w 1
