byte_2F2462:    dc.b   0, $C,$59,$57,$A8,$92,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_26FC   o
                dc.w sprite_32_24
                dc.w $737A
                dc.w $9500 ! ((grp_135040 / 2) & $00FF)
                dc.w $9600 ! (((grp_135040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7362
                dc.w $9500 ! ((grp_1351C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1351C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1351C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $936A
                dc.w $9500 ! ((grp_14EB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_14EB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14EB40 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $5B5D
                dc.w $9500 ! ((grp_6C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $535A
                dc.w $9500 ! ((grp_AC400 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6B71
                dc.w $9500 ! ((grp_AC480 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7392
                dc.w $9500 ! ((grp_DB280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9B62
                dc.w $9500 ! ((grp_DB240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB68
                dc.w $9500 ! ((grp_C0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4B65
                dc.w $9500 ! ((grp_F2440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B69
                dc.w $9500 ! ((grp_F2420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $765A
                dc.w $9500 ! ((grp_F2460 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A92
                dc.w $9500 ! ((grp_F2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2480 / 2) >> 16)
                dc.w 1
