byte_2D55AE:    dc.b   0,  5,$6F,$64,$8E,$8F,$7C,$75,$78,$69
                                        ; DATA XREF: ROM:off_119C   o
                dc.w sprite_32_32
                dc.w $6A61
                dc.w $9500 ! ((grp_18E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7281
                dc.w $9500 ! ((grp_1852C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1852C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1852C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A89
                dc.w $9500 ! ((grp_CB9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6A59
                dc.w $9500 ! ((grp_CBA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CBA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $625A
                dc.w $9500 ! ((grp_B3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3A80 / 2) >> 16)
                dc.w 2
