byte_2D1DCE:    dc.b   0,  2,$6F,$7B,$93,$8E,$83,$84,$84,$84
                                        ; DATA XREF: ROM:off_E6C   o
                dc.w sprite_32_24
                dc.w $6C78
                dc.w $9500 ! ((grp_1219C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1219C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1219C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8C79
                dc.w $9500 ! ((grp_76980 / 2) & $00FF)
                dc.w $9600 ! (((grp_76980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8C89
                dc.w $9500 ! ((grp_E3EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3EE0 / 2) >> 16)
                dc.w 1
