byte_2E2FB8:    dc.b   0,  7,$6F,$5A,$8E,$8F,$7D,$6F,$81,$6A
                                        ; DATA XREF: ROM:off_1A78   o
                dc.w sprite_24_32
                dc.w $7471
                dc.w $9500 ! ((grp_1066C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1066C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1066C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7C61
                dc.w $9500 ! ((grp_7FE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C59
                dc.w $9500 ! ((grp_A6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6489
                dc.w $9500 ! ((grp_D1640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6860
                dc.w $9500 ! ((grp_B8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C68
                dc.w $9500 ! ((grp_B89C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B89C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B89C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C51
                dc.w $9500 ! ((grp_B8A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C89
                dc.w $9500 ! ((grp_EAC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAC60 / 2) >> 16)
                dc.w 1
