byte_2F4F22:    dc.b   0,  8,$6E,$61,$98,$8D,$90,$74,$91,$74
                                        ; DATA XREF: ROM:off_2A2C   o
                dc.w sprite_32_32
                dc.w $8D57
                dc.w $9500 ! ((grp_3BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3BC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7D5E
                dc.w $9500 ! ((grp_6DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6D7B
                dc.w $9500 ! ((grp_17E840 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6D6B
                dc.w $9500 ! ((grp_8E780 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7D7E
                dc.w $9500 ! ((grp_8E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C77
                dc.w $9500 ! ((grp_ACF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $AD66
                dc.w $9500 ! ((grp_C1B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $848E
                dc.w $9500 ! ((grp_F4340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948B
                dc.w $9500 ! ((grp_F4360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4360 / 2) >> 16)
                dc.w 1
