byte_2D2FA8:    dc.b   0,  5,$6D,$69,$9A,$8C,$80,$7B,$81,$7B
                                        ; DATA XREF: ROM:off_F48   o
                dc.w sprite_24_32
                dc.w $7A6A
                dc.w $9500 ! ((grp_FD540 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD540 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $7270
                dc.w $9500 ! ((grp_A4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5A88
                dc.w $9500 ! ((grp_184AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184AE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $926A
                dc.w $9500 ! ((grp_193F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_193F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A72
                dc.w $9500 ! ((grp_E4EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A80
                dc.w $9500 ! ((grp_E4EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4EE0 / 2) >> 16)
                dc.w 1
