byte_2F1288:    dc.b   0,  8,$64,$60,$9D,$9A,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_2638   o
                dc.w sprite_32_32
                dc.w $7E5E
                dc.w $9500 ! ((grp_38A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_38A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $605C
                dc.w $9500 ! ((grp_1354C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1354C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1354C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7A7E
                dc.w $9500 ! ((grp_135640 / 2) & $00FF)
                dc.w $9600 ! (((grp_135640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6A86
                dc.w $9500 ! ((grp_8C380 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5A91
                dc.w $9500 ! ((grp_DB300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E74
                dc.w $9500 ! ((grp_DB340 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7996
                dc.w $9500 ! ((grp_DB380 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A88
                dc.w $9500 ! ((grp_C0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9E70
                dc.w $9500 ! ((grp_F2540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2540 / 2) >> 16)
                dc.w 1
