byte_2EFE32:    dc.b   0,  9,$44,$24,$BC,$76,$80,$80,$81,$80
                                        ; DATA XREF: ROM:off_25A4   o
                dc.w sprite_32_32
                dc.w $796A
                dc.w $9500 ! ((grp_33800 / 2) & $00FF)
                dc.w $9600 ! (((grp_33800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $4162
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9962
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6162
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $868A
                dc.w $9500 ! ((grp_8B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B200 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7962
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7162
                dc.w $9500 ! ((grp_BF9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7172
                dc.w $9500 ! ((grp_BFA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B962
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C9A
                dc.w $9500 ! ((grp_F1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1500 / 2) >> 16)
                dc.w 1
