byte_2F3630:    dc.b   0,  5,$69,$5F,$96,$8C,$78,$77,$79,$77
                                        ; DATA XREF: ROM:off_27C0   o
                dc.w sprite_32_32
                dc.w $735B
                dc.w $9500 ! ((grp_3A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3A200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $737B
                dc.w $9500 ! ((grp_1363C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1363C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1363C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $5B62
                dc.w $9500 ! ((grp_18E680 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E680 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D6A
                dc.w $9500 ! ((grp_DBD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B76
                dc.w $9500 ! ((grp_C0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $637C
                dc.w $9500 ! ((grp_F3000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3000 / 2) >> 16)
                dc.w 1
