byte_2E9D1E:    dc.b   0,  5,$63,$53,$99,$75,$7E,$64,$7F,$64
                                        ; DATA XREF: ROM:off_1ECC   o
                dc.w sprite_32_32
                dc.w $7359
                dc.w $9500 ! ((grp_28000 / 2) & $00FF)
                dc.w $9600 ! (((grp_28000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6356
                dc.w $9500 ! ((grp_86D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7351
                dc.w $9500 ! ((grp_18B740 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $935E
                dc.w $9500 ! ((grp_19AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AF80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5B69
                dc.w $9500 ! ((grp_EEC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEC80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B71
                dc.w $9500 ! ((grp_EECA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EECA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EECA0 / 2) >> 16)
                dc.w 1
