byte_2CF3C0:    dc.b   0, $A,$6A,$69,$97,$94,$80,$77,$81,$77
                                        ; DATA XREF: ROM:off_B58   o
                dc.w sprite_24_32
                dc.w $8B72
                dc.w $9500 ! ((grp_FB140 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7B72
                dc.w $9500 ! ((grp_5C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8B62
                dc.w $9500 ! ((grp_156E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_156E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6B5A
                dc.w $9500 ! ((grp_1702C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1702C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1702C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6B72
                dc.w $9500 ! ((grp_170380 / 2) & $00FF)
                dc.w $9600 ! (((grp_170380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B5A
                dc.w $9500 ! ((grp_170440 / 2) & $00FF)
                dc.w $9600 ! (((grp_170440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170440 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $635D
                dc.w $9500 ! ((grp_A3380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_C8640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B65
                dc.w $9500 ! ((grp_B1580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D92
                dc.w $9500 ! ((grp_E2BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B5A
                dc.w $9500 ! ((grp_E2BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2BC0 / 2) >> 16)
                dc.w 1
