byte_2E89EC:    dc.b   0,  5,$77,$66,$82,$8E,$7D,$78,$78,$6D
                                        ; DATA XREF: ROM:off_1DA0   o
                dc.w sprite_24_16
                dc.w $7580
                dc.w $9500 ! ((grp_159AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_159AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7368
                dc.w $9500 ! ((grp_CE780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7570
                dc.w $9500 ! ((grp_E88C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E88C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E88C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7590
                dc.w $9500 ! ((grp_E5AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7978
                dc.w $9500 ! ((grp_E5AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7960
                dc.w $9500 ! ((grp_E88E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E88E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E88E0 / 2) >> 16)
                dc.w 1
