byte_2E73EA:    dc.b   0, $C,$6F,$63,$8E,$8F,$7B,$72,$64,$61
                                        ; DATA XREF: ROM:off_1CD4   o
                dc.w sprite_16_24
                dc.w $7373
                dc.w $9500 ! ((grp_178600 / 2) & $00FF)
                dc.w $9600 ! (((grp_178600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $635B
                dc.w $9500 ! ((grp_83C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $636B
                dc.w $9500 ! ((grp_83A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7B63
                dc.w $9500 ! ((grp_83A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B65
                dc.w $9500 ! ((grp_83B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6B53
                dc.w $9500 ! ((grp_9B180 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_D4140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B53
                dc.w $9500 ! ((grp_D4180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B60
                dc.w $9500 ! ((grp_BAF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7363
                dc.w $9500 ! ((grp_BAFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8380
                dc.w $9500 ! ((grp_BAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B8B
                dc.w $9500 ! ((grp_ECB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B6C
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
