byte_2D7CD2:    dc.b   0,  7,$75,$5D,$8B,$A2,$81,$81,$80,$6B
                                        ; DATA XREF: ROM:off_1334   o
                dc.w sprite_24_24
                dc.w $7376
                dc.w $9500 ! ((grp_141B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_141B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141B20 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $788E
                dc.w $9500 ! ((grp_173140 / 2) & $00FF)
                dc.w $9600 ! (((grp_173140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7B66
                dc.w $9500 ! ((grp_79300 / 2) & $00FF)
                dc.w $9600 ! (((grp_79300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B74
                dc.w $9500 ! ((grp_79200 / 2) & $00FF)
                dc.w $9600 ! (((grp_79200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B75
                dc.w $9500 ! ((grp_194CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194CE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $736E
                dc.w $9500 ! ((grp_E67E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E67E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E67E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B5E
                dc.w $9500 ! ((grp_E6840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F6C
                dc.w $9500 ! ((grp_E6940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6940 / 2) >> 16)
                dc.w 1
