byte_2DD5BA:    dc.b   0,  5,$80,$5B,$94,$98,$8B,$90,$83,$66
                                        ; DATA XREF: ROM:off_16CC   o
                dc.w sprite_16_32
                dc.w $8054
                dc.w $9500 ! ((grp_60700 / 2) & $00FF)
                dc.w $9600 ! (((grp_60700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $877C
                dc.w $9500 ! ((grp_60800 / 2) & $00FF)
                dc.w $9600 ! (((grp_60800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $8074
                dc.w $9500 ! ((grp_185C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_185C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $905C
                dc.w $9500 ! ((grp_195760 / 2) & $00FF)
                dc.w $9600 ! (((grp_195760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195760 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7864
                dc.w $9500 ! ((grp_B4DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $978C
                dc.w $9500 ! ((grp_B4E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4E00 / 2) >> 16)
                dc.w 2
