byte_2D8988:    dc.b   0,  7,$6F,$5A,$8E,$90,$6F,$71,$80,$62
                                        ; DATA XREF: ROM:off_13C0   o
                dc.w sprite_32_24
                dc.w $5765
                dc.w $9500 ! ((grp_12CDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12CDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12CDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $667D
                dc.w $9500 ! ((grp_18A120 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A120 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $715D
                dc.w $9500 ! ((grp_18A180 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A180 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_18A1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A1E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7765
                dc.w $9500 ! ((grp_1999C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1999C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1999C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6585
                dc.w $9500 ! ((grp_D4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B55
                dc.w $9500 ! ((grp_D4B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E7D
                dc.w $9500 ! ((grp_ED1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED1E0 / 2) >> 16)
                dc.w 1
