byte_2EE43E:    dc.b   0,  3,$7E,$13,$80,$7E,$7F,$48,$80,$48
                                        ; DATA XREF: ROM:off_238C   o
                dc.w sprite_8_32
                dc.w $7C11
                dc.w $9500 ! ((grp_AB200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C31
                dc.w $9500 ! ((grp_AB280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C51
                dc.w $9500 ! ((grp_AB300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7D71
                dc.w $9500 ! ((grp_BF100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF100 / 2) >> 16)
                dc.w 2
