byte_2CE11E:    dc.b   0,  2,$8B,$7F,$A1,$8F,$96,$87,$97,$87
                                        ; DATA XREF: ROM:off_9FC   o
                dc.w sprite_24_16
                dc.w $8F81
                dc.w $9500 ! ((grp_156AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_156AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8789
                dc.w $9500 ! ((grp_E1FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B79
                dc.w $9500 ! ((grp_E2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2000 / 2) >> 16)
                dc.w 1
