byte_2F25C2:    dc.b   0,  3,$76,$61,$8B,$8E,$80,$7C,$81,$7C
                                        ; DATA XREF: ROM:off_270C   o
                dc.w sprite_24_16
                dc.w $7380
                dc.w $9500 ! ((grp_166840 / 2) & $00FF)
                dc.w $9600 ! (((grp_166840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166840 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7670
                dc.w $9500 ! ((grp_166780 / 2) & $00FF)
                dc.w $9600 ! (((grp_166780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7868
                dc.w $9500 ! ((grp_DA700 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E78
                dc.w $9500 ! ((grp_F1900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1900 / 2) >> 16)
                dc.w 1
