byte_2F8DE0:    dc.b   0,  6,$6F,$71,$90,$85,$80,$6B,$81,$6B
                                        ; DATA XREF: ROM:off_2CD8   o
                dc.w sprite_24_32
                dc.w $7367
                dc.w $9500 ! ((grp_119D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_119D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8B6E
                dc.w $9500 ! ((grp_19F480 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F480 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $785F
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B6E
                dc.w $9500 ! ((grp_C3C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A4F
                dc.w $9500 ! ((grp_C3C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9371
                dc.w $9500 ! ((grp_C3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6371
                dc.w $9500 ! ((grp_F6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6400 / 2) >> 16)
                dc.w 1
