byte_2E1C26:    dc.b   0,  5,$5E,$59,$9D,$81,$7D,$6D,$76,$64
                                        ; DATA XREF: ROM:off_1994   o
                dc.w sprite_24_24
                dc.w $735F
                dc.w $9500 ! ((grp_145000 / 2) & $00FF)
                dc.w $9600 ! (((grp_145000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145000 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8B56
                dc.w $9500 ! ((grp_15E140 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B75
                dc.w $9500 ! ((grp_7E180 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B65
                dc.w $9500 ! ((grp_197200 / 2) & $00FF)
                dc.w $9600 ! (((grp_197200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7357
                dc.w $9500 ! ((grp_E9B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8579
                dc.w $9500 ! ((grp_E9B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9B20 / 2) >> 16)
                dc.w 1
