byte_2EF00C:    dc.b   0,  1,$77,$75,$88,$8D,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_2450   o
                dc.w sprite_16_32
                dc.w $7573
                dc.w $9500 ! ((grp_6AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $8575
                dc.w $9500 ! ((grp_19D320 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D320 / 2) >> 16)
                dc.w 3
