byte_2FF9F0:    dc.b   0,  4,$78,$1A,$86,$82,$80,$50,$81,$50
                                        ; DATA XREF: ROM:off_35B8   o
                dc.w sprite_16_32
                dc.w $791D
                dc.w $9500 ! ((grp_72100 / 2) & $00FF)
                dc.w $9600 ! (((grp_72100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7C3D
                dc.w $9500 ! ((grp_AFA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C5D
                dc.w $9500 ! ((grp_AFB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $797D
                dc.w $9500 ! ((grp_E0D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $743D
                dc.w $9500 ! ((grp_F95E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F95E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F95E0 / 2) >> 16)
                dc.w 1
