byte_2D4E04:    dc.b   0,  8,$74,$60,$8A,$89,$82,$7A,$81,$6E
                                        ; DATA XREF: ROM:off_1148   o
                dc.w sprite_24_24
                dc.w $746F
                dc.w $9500 ! ((grp_1444C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1444C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1444C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $8487
                dc.w $9500 ! ((grp_187060 / 2) & $00FF)
                dc.w $9600 ! (((grp_187060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187060 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A8F
                dc.w $9500 ! ((grp_CF2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7387
                dc.w $9500 ! ((grp_CF300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A67
                dc.w $9500 ! ((grp_CF340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C7F
                dc.w $9500 ! ((grp_CF380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A5F
                dc.w $9500 ! ((grp_E9100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $898F
                dc.w $9500 ! ((grp_E9120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C77
                dc.w $9500 ! ((grp_E9140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9140 / 2) >> 16)
                dc.w 1
