byte_2F2F48:    dc.b   0,  8,$6A,$5F,$91,$8D,$78,$76,$79,$76
                                        ; DATA XREF: ROM:off_2780   o
                dc.w sprite_32_32
                dc.w $7065
                dc.w $9500 ! ((grp_39E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_39E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7A85
                dc.w $9500 ! ((grp_8CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $606F
                dc.w $9500 ! ((grp_DBC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6681
                dc.w $9500 ! ((grp_DBC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6D5D
                dc.w $9500 ! ((grp_DBCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $855D
                dc.w $9500 ! ((grp_DBD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A85
                dc.w $9500 ! ((grp_DBD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $586F
                dc.w $9500 ! ((grp_C0EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $907B
                dc.w $9500 ! ((grp_F2EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2EC0 / 2) >> 16)
                dc.w 1
