byte_2D1EAC:    dc.b   0,  4,$70,$5C,$93,$8E,$7F,$66,$80,$66
                                        ; DATA XREF: ROM:off_E78   o
                dc.w sprite_32_24
                dc.w $6D59
                dc.w $9500 ! ((grp_121B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_121B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8D5F
                dc.w $9500 ! ((grp_193420 / 2) & $00FF)
                dc.w $9600 ! (((grp_193420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D71
                dc.w $9500 ! ((grp_C9A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6567
                dc.w $9500 ! ((grp_E3FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9565
                dc.w $9500 ! ((grp_E3FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3FC0 / 2) >> 16)
                dc.w 1
