byte_2D0954:    dc.b   0,  3,$55,$52,$AC,$8E,$86,$82,$87,$82
                                        ; DATA XREF: ROM:off_DA8   o
                dc.w sprite_24_24
                dc.w $7A76
                dc.w $9500 ! ((grp_13FA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_13FA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13FA80 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $9281
                dc.w $9500 ! ((grp_C9600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7283
                dc.w $9500 ! ((grp_E3B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F8E
                dc.w $9500 ! ((grp_E3B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3B80 / 2) >> 16)
                dc.w 1
