byte_2E9CE4:    dc.b   0,  3,$65,$53,$95,$77,$7D,$65,$7E,$65
                                        ; DATA XREF: ROM:off_1EC8   o
                dc.w sprite_32_32
                dc.w $7251
                dc.w $9500 ! ((grp_27E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7271
                dc.w $9500 ! ((grp_18B6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B6E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9258
                dc.w $9500 ! ((grp_19AF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AF20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6266
                dc.w $9500 ! ((grp_EEC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEC60 / 2) >> 16)
                dc.w 1
