byte_2ED1BA:    dc.b   0,  1,$6C,$7F,$96,$8E,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_226C   o
                dc.w sprite_16_32
                dc.w $7776
                dc.w $9500 ! ((grp_68700 / 2) & $00FF)
                dc.w $9600 ! (((grp_68700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $776E
                dc.w $9500 ! ((grp_D8640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8640 / 2) >> 16)
                dc.w 2
