byte_2DD44E:    dc.b   0,  5,$6F,$72,$8E,$90,$83,$7A,$86,$74
                                        ; DATA XREF: ROM:off_16BC   o
                dc.w sprite_32_32
                dc.w $7471
                dc.w $9500 ! ((grp_1A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $686A
                dc.w $9500 ! ((grp_7A580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8F66
                dc.w $9500 ! ((grp_7A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7F61
                dc.w $9500 ! ((grp_B4D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9488
                dc.w $9500 ! ((grp_E7640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9476
                dc.w $9500 ! ((grp_E7660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7660 / 2) >> 16)
                dc.w 1
