byte_2F892A:    dc.b   0,  4,$6D,$76,$9A,$8B,$83,$80,$84,$80
                                        ; DATA XREF: ROM:off_2C9C   o
                dc.w sprite_16_16
                dc.w $827E
                dc.w $9500 ! ((grp_90C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A86
                dc.w $9500 ! ((grp_18F820 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F820 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $876E
                dc.w $9500 ! ((grp_C39C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C39C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C39C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $927E
                dc.w $9500 ! ((grp_C3980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A86
                dc.w $9500 ! ((grp_F61E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F61E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F61E0 / 2) >> 16)
                dc.w 1
