byte_2E5DB6:    dc.b   0,  7,$6C,$60,$85,$8E,$48,$9B,$83,$65
                                        ; DATA XREF: ROM:off_1C0C   o
                dc.w sprite_32_24
                dc.w $656A
                dc.w $9500 ! ((grp_12C4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6F82
                dc.w $9500 ! ((grp_160CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_160CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7D5A
                dc.w $9500 ! ((grp_82F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_82F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_82E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_82E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5C5E
                dc.w $9500 ! ((grp_EC720 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $755D
                dc.w $9500 ! ((grp_EC6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC6E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $856A
                dc.w $9500 ! ((grp_EC700 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D76
                dc.w $9500 ! ((grp_E78E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E78E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E78E0 / 2) >> 16)
                dc.w 1
