byte_2D6616:    dc.b   0,  4,$6B,$47,$9A,$6E,$82,$5A,$83,$5A
                                        ; DATA XREF: ROM:off_1244   o
                dc.w sprite_24_32
                dc.w $7E4D
                dc.w $9500 ! ((grp_10B7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6E5B
                dc.w $9500 ! ((grp_178840 / 2) & $00FF)
                dc.w $9600 ! (((grp_178840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7045
                dc.w $9500 ! ((grp_83F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9652
                dc.w $9500 ! ((grp_BB280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6665
                dc.w $9500 ! ((grp_ECE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECE20 / 2) >> 16)
                dc.w 1
