byte_2EDBF2:    dc.b   0,  6,$6E,$64,$A0,$95,$87,$7A,$88,$7A
                                        ; DATA XREF: ROM:off_22FC   o
                dc.w sprite_32_32
                dc.w $736D
                dc.w $9500 ! ((grp_30800 / 2) & $00FF)
                dc.w $9600 ! (((grp_30800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $937C
                dc.w $9500 ! ((grp_88E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8465
                dc.w $9500 ! ((grp_18CB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CB20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B8D
                dc.w $9500 ! ((grp_D8880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B85
                dc.w $9500 ! ((grp_F0040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $858D
                dc.w $9500 ! ((grp_F0060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9374
                dc.w $9500 ! ((grp_F0080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0080 / 2) >> 16)
                dc.w 1
