byte_2DC2FA:    dc.b   0,  7,$71,$5A,$A5,$90,$84,$65,$85,$65
                                        ; DATA XREF: ROM:off_160C   o
                dc.w sprite_16_32
                dc.w $8853
                dc.w $9500 ! ((grp_66D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $705D
                dc.w $9500 ! ((grp_86800 / 2) & $00FF)
                dc.w $9600 ! (((grp_86800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9853
                dc.w $9500 ! ((grp_86880 / 2) & $00FF)
                dc.w $9600 ! (((grp_86880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9868
                dc.w $9500 ! ((grp_86900 / 2) & $00FF)
                dc.w $9600 ! (((grp_86900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8055
                dc.w $9500 ! ((grp_19AC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AC20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $605D
                dc.w $9500 ! ((grp_D6980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6B55
                dc.w $9500 ! ((grp_D69C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D69C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D69C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6865
                dc.w $9500 ! ((grp_EB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB040 / 2) >> 16)
                dc.w 1
