byte_2EE4EC:    dc.b   0,  3,$79,$53,$84,$7E,$7E,$68,$7F,$68
                                        ; DATA XREF: ROM:off_2398   o
                dc.w sprite_8_32
                dc.w $7959
                dc.w $9500 ! ((grp_AB380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7164
                dc.w $9500 ! ((grp_BF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B79
                dc.w $9500 ! ((grp_F0720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E51
                dc.w $9500 ! ((grp_F0740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0740 / 2) >> 16)
                dc.w 1
