byte_2F108C:    dc.b   0,  7,$5C,$54,$A5,$86,$84,$6E,$85,$6E
                                        ; DATA XREF: ROM:off_2628   o
                dc.w sprite_32_32
                dc.w $5665
                dc.w $9500 ! ((grp_38000 / 2) & $00FF)
                dc.w $9600 ! (((grp_38000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7650
                dc.w $9500 ! ((grp_38200 / 2) & $00FF)
                dc.w $9600 ! (((grp_38200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7670
                dc.w $9500 ! ((grp_54900 / 2) & $00FF)
                dc.w $9600 ! (((grp_54900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9650
                dc.w $9500 ! ((grp_17D4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D4C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9668
                dc.w $9500 ! ((grp_17D580 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6685
                dc.w $9500 ! ((grp_DB080 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A65A
                dc.w $9500 ! ((grp_DB0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E5D
                dc.w $9500 ! ((grp_F23E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F23E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F23E0 / 2) >> 16)
                dc.w 1
