byte_2D5386:    dc.b   0,  6,$6F,$63,$8E,$8F,$80,$73,$7C,$67
                                        ; DATA XREF: ROM:off_1184   o
                dc.w sprite_24_32
                dc.w $7571
                dc.w $9500 ! ((grp_FEA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FEA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FEA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7561
                dc.w $9500 ! ((grp_15A0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A0C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6D64
                dc.w $9500 ! ((grp_194740 / 2) & $00FF)
                dc.w $9600 ! (((grp_194740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D7F
                dc.w $9500 ! ((grp_B39C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B39C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B39C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7851
                dc.w $9500 ! ((grp_E6060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7959
                dc.w $9500 ! ((grp_E6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D89
                dc.w $9500 ! ((grp_E6040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6040 / 2) >> 16)
                dc.w 1
