byte_2DE65C:    dc.b   0,  8,$6E,$6E,$8C,$8F,$80,$78,$83,$6E
                                        ; DATA XREF: ROM:off_1778   o
                dc.w sprite_16_32
                dc.w $6972
                dc.w $9500 ! ((grp_65500 / 2) & $00FF)
                dc.w $9600 ! (((grp_65500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7962
                dc.w $9500 ! ((grp_178CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_178CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $797A
                dc.w $9500 ! ((grp_178D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_178D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8970
                dc.w $9500 ! ((grp_A8080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6187
                dc.w $9500 ! ((grp_ED5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED5E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $716A
                dc.w $9500 ! ((grp_ED600 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $785A
                dc.w $9500 ! ((grp_ED620 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9187
                dc.w $9500 ! ((grp_ED640 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937F
                dc.w $9500 ! ((grp_ED660 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED660 / 2) >> 16)
                dc.w 1
