byte_2CCA10:    dc.b   0,  8,$49,$71,$B0,$90,$7C,$80,$7D,$80
                                        ; DATA XREF: ROM:off_7E8   o
                dc.w sprite_32_16
                dc.w $5E87
                dc.w $9500 ! ((grp_46000 / 2) & $00FF)
                dc.w $9600 ! (((grp_46000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46000 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7E82
                dc.w $9500 ! ((grp_46100 / 2) & $00FF)
                dc.w $9600 ! (((grp_46100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $4687
                dc.w $9500 ! ((grp_183100 / 2) & $00FF)
                dc.w $9600 ! (((grp_183100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183100 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $566F
                dc.w $9500 ! ((grp_191C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_191C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A677
                dc.w $9500 ! ((grp_191C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_191C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5E6F
                dc.w $9500 ! ((grp_B0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E80
                dc.w $9500 ! ((grp_B0180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B6F
                dc.w $9500 ! ((grp_E1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AE7C
                dc.w $9500 ! ((grp_E16A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E16A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E16A0 / 2) >> 16)
                dc.w 1
