byte_2FEA46:    dc.b   0,  2,$73,$8D,$90,$8F,$81,$88,$82,$88
                                        ; DATA XREF: ROM:off_346C   o
                dc.w sprite_24_8
                dc.w $818A
                dc.w $9500 ! ((grp_191800 / 2) & $00FF)
                dc.w $9600 ! (((grp_191800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191800 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $718A
                dc.w $9500 ! ((grp_E07C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E07C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E07C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D7A
                dc.w $9500 ! ((grp_C62C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C62C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C62C0 / 2) >> 16)
                dc.w 2
