byte_2FE6CC:    dc.b   0,  1,$70,$77,$8B,$8A,$7D,$80,$7E,$80
                                        ; DATA XREF: ROM:off_3410   o
                dc.w sprite_24_24
                dc.w $7675
                dc.w $9500 ! ((grp_1551A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1551A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1551A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $6E77
                dc.w $9500 ! ((grp_C6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6200 / 2) >> 16)
                dc.w 2
