byte_2D66A2:    dc.b   0,  3,$6C,$47,$97,$6E,$7C,$5A,$7D,$5A
                                        ; DATA XREF: ROM:off_124C   o
                dc.w sprite_32_24
                dc.w $7A4D
                dc.w $9500 ! ((grp_12C940 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C940 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6065
                dc.w $9500 ! ((grp_4F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6A45
                dc.w $9500 ! ((grp_178780 / 2) & $00FF)
                dc.w $9600 ! (((grp_178780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178780 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8065
                dc.w $9500 ! ((grp_ECD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECD60 / 2) >> 16)
                dc.w 1
