byte_2D66DC:    dc.b   0,  6,$6C,$49,$9C,$70,$7D,$5C,$7E,$5C
                                        ; DATA XREF: ROM:off_1250   o
                dc.w sprite_32_32
                dc.w $704F
                dc.w $9500 ! ((grp_24400 / 2) & $00FF)
                dc.w $9600 ! (((grp_24400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $9055
                dc.w $9500 ! ((grp_83E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5867
                dc.w $9500 ! ((grp_189FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189FA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $686F
                dc.w $9500 ! ((grp_18A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6848
                dc.w $9500 ! ((grp_BB1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7047
                dc.w $9500 ! ((grp_ECD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECD80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $944D
                dc.w $9500 ! ((grp_ECDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECDA0 / 2) >> 16)
                dc.w 1
