byte_2DFE6E:    dc.b   0,  6,$6A,$53,$A0,$8F,$85,$71,$8A,$61
                                        ; DATA XREF: ROM:off_1874   o
                dc.w sprite_32_32
                dc.w $7B59
                dc.w $9500 ! ((grp_1FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1FE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7379
                dc.w $9500 ! ((grp_12AB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12AB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12AB40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6B69
                dc.w $9500 ! ((grp_81380 / 2) & $00FF)
                dc.w $9600 ! (((grp_81380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9B59
                dc.w $9500 ! ((grp_A6E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8B51
                dc.w $9500 ! ((grp_D2A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6371
                dc.w $9500 ! ((grp_EB800 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B89
                dc.w $9500 ! ((grp_EB820 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB820 / 2) >> 16)
                dc.w 1
