byte_2CED86:    dc.b   0,  4,$71,$68,$8F,$82,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_B24   o
                dc.w sprite_32_32
                dc.w $6F6C
                dc.w $9500 ! ((grp_12C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_8
                dc.w $7764
                dc.w $9500 ! ((grp_C8340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F8C
                dc.w $9500 ! ((grp_E28A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E28A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E28A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $878C
                dc.w $9500 ! ((grp_E28C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E28C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E28C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F7B
                dc.w $9500 ! ((grp_E28E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E28E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E28E0 / 2) >> 16)
                dc.w 1
