byte_2CC99A:    dc.b   0,  8,$51,$6D,$B1,$90,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_7E4   o
                dc.w sprite_32_24
                dc.w $5E7B
                dc.w $9500 ! ((grp_11ECC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11ECC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11ECC0 / 2) >> 16)
                dc.w    $C
                dc.w sprite_32_24
                dc.w $7E7B
                dc.w $9500 ! ((grp_11EE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11EE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11EE40 / 2) >> 16)
                dc.w    $C
                dc.w sprite_16_16
                dc.w $4E7E
                dc.w $9500 ! ((grp_72D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_72D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72D80 / 2) >> 16)
                dc.w     4
                dc.w sprite_16_16
                dc.w $616B
                dc.w $9500 ! ((grp_72E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_72E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72E00 / 2) >> 16)
                dc.w     4
                dc.w sprite_8_16
                dc.w $9E7F
                dc.w $9500 ! ((grp_B00C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B00C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B00C0 / 2) >> 16)
                dc.w     2
                dc.w sprite_8_16
                dc.w $A070
                dc.w $9500 ! ((grp_B0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $886B
                dc.w $9500 ! ((grp_E1620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9673
                dc.w $9500 ! ((grp_E1640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AC80
                dc.w $9500 ! ((grp_E1660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1660 / 2) >> 16)
                dc.w 1
