byte_2F16C0:    dc.b   0,  4,$77,$67,$90,$8C,$83,$79,$84,$79
                                        ; DATA XREF: ROM:off_2668   o
                dc.w sprite_24_24
                dc.w $7A6A
                dc.w $9500 ! ((grp_14F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F200 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7A82
                dc.w $9500 ! ((grp_8CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8A88
                dc.w $9500 ! ((grp_DB7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $727A
                dc.w $9500 ! ((grp_F2AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C62
                dc.w $9500 ! ((grp_F2AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2AC0 / 2) >> 16)
                dc.w 1
