byte_2E9BE2:    dc.b   0,  5,$68,$53,$9A,$74,$81,$63,$82,$63
                                        ; DATA XREF: ROM:off_1EBC   o
                dc.w sprite_24_32
                dc.w $7B51
                dc.w $9500 ! ((grp_10EC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10EC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10EC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6B56
                dc.w $9500 ! ((grp_86D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_86D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9358
                dc.w $9500 ! ((grp_19B040 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B040 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8371
                dc.w $9500 ! ((grp_D6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $635B
                dc.w $9500 ! ((grp_EED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EED00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B59
                dc.w $9500 ! ((grp_EED20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EED20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EED20 / 2) >> 16)
                dc.w 1
