byte_2CDD2C:    dc.b   0,  4,$6B,$6A,$97,$91,$81,$7D,$82,$7D
                                        ; DATA XREF: ROM:off_9B8   o
                dc.w sprite_32_32
                dc.w $7278
                dc.w $9500 ! ((grp_11400 / 2) & $00FF)
                dc.w $9600 ! (((grp_11400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $7270
                dc.w $9500 ! ((grp_96D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A75
                dc.w $9500 ! ((grp_1920A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1920A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1920A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9275
                dc.w $9500 ! ((grp_192100 / 2) & $00FF)
                dc.w $9600 ! (((grp_192100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192100 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7468
                dc.w $9500 ! ((grp_C81C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C81C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C81C0 / 2) >> 16)
                dc.w 2
