byte_2D873C:    dc.b   0,  4,$69,$5C,$93,$7A,$84,$71,$83,$6B
                                        ; DATA XREF: ROM:off_13A8   o
                dc.w sprite_32_32
                dc.w $665C
                dc.w $9500 ! ((grp_19A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $866C
                dc.w $9500 ! ((grp_15AB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15AB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15AB40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $667C
                dc.w $9500 ! ((grp_79780 / 2) & $00FF)
                dc.w $9600 ! (((grp_79780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8664
                dc.w $9500 ! ((grp_E6DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E70
                dc.w $9500 ! ((grp_E6E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E00 / 2) >> 16)
                dc.w 1
