byte_2F12FE:    dc.b   0, $C,$64,$61,$A2,$9C,$83,$7C,$84,$7C
                                        ; DATA XREF: ROM:off_263C   o
                dc.w sprite_24_32
                dc.w $8C5A
                dc.w $9500 ! ((grp_114040 / 2) & $00FF)
                dc.w $9600 ! (((grp_114040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5C5A
                dc.w $9500 ! ((grp_1357C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1357C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1357C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8C7A
                dc.w $9500 ! ((grp_14ED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_14ED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14ED80 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $747F
                dc.w $9500 ! ((grp_6C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $648C
                dc.w $9500 ! ((grp_8C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7C64
                dc.w $9500 ! ((grp_8C480 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $847D
                dc.w $9500 ! ((grp_AC880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6C72
                dc.w $9500 ! ((grp_DB3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A462
                dc.w $9500 ! ((grp_C0740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $545F
                dc.w $9500 ! ((grp_F25C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F25C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F25C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5C94
                dc.w $9500 ! ((grp_F2560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C5C
                dc.w $9500 ! ((grp_F2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C92
                dc.w $9500 ! ((grp_F25A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F25A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F25A0 / 2) >> 16)
                dc.w 1
