byte_2FE1F2:    dc.b   0,  1,$76,$72,$8B,$8D,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_33A4   o
                dc.w sprite_24_32
                dc.w $7670
                dc.w $9500 ! ((grp_11D1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $6E70
                dc.w $9500 ! ((grp_F8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8C00 / 2) >> 16)
                dc.w 1
funchar_8:      dc.b   0,  1,$75,$72,$8C,$8D,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_33A8   o
                dc.w sprite_32_24
                dc.w $7378
                dc.w $9500 ! ((grp_13B7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7470
                dc.w $9500 ! ((grp_1916E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1916E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1916E0 / 2) >> 16)
                dc.w 3
