byte_2D054A:    dc.b   0,  2,$76,$74,$93,$87,$84,$7D,$85,$7D
                                        ; DATA XREF: ROM:off_D34   o
                dc.w sprite_24_16
                dc.w $7D7A
                dc.w $9500 ! ((grp_157780 / 2) & $00FF)
                dc.w $9600 ! (((grp_157780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157780 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7572
                dc.w $9500 ! ((grp_192D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_192D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8572
                dc.w $9500 ! ((grp_C8D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8D40 / 2) >> 16)
                dc.w 2
