byte_2CD9DC:    dc.b   0,  2,$85,$88,$97,$8D,$84,$8E,$86,$9E
                                        ; DATA XREF: ROM:off_950   o
                dc.w sprite_16_8
                dc.w $8188
                dc.w $9500 ! ((grp_C7C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9086
                dc.w $9500 ! ((grp_E1EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $927E
                dc.w $9500 ! ((grp_E1EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1EE0 / 2) >> 16)
                dc.w 1
