byte_2FA1AC:    dc.b   0,  8,$7D,$55,$91,$8E,$7E,$6D,$7F,$6D
                                        ; DATA XREF: ROM:off_2DF0   o
                dc.w sprite_24_32
                dc.w $7E61
                dc.w $9500 ! ((grp_11AAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11AAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11AAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7D49
                dc.w $9500 ! ((grp_152C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_152C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152C80 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7181
                dc.w $9500 ! ((grp_57700 / 2) & $00FF)
                dc.w $9600 ! (((grp_57700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6E61
                dc.w $9500 ! ((grp_6FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $566D
                dc.w $9500 ! ((grp_91400 / 2) & $00FF)
                dc.w $9600 ! (((grp_91400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9670
                dc.w $9500 ! ((grp_91480 / 2) & $00FF)
                dc.w $9600 ! (((grp_91480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6665
                dc.w $9500 ! ((grp_19F780 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F780 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9552
                dc.w $9500 ! ((grp_C45C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C45C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C45C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9181
                dc.w $9500 ! ((grp_F6E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6E00 / 2) >> 16)
                dc.w 1
