byte_2CD0A6:    dc.b   0,  2,$7B,$7D,$90,$8D,$85,$85,$86,$85
                                        ; DATA XREF: ROM:off_86C   o
                dc.w sprite_16_8
                dc.w $798A
                dc.w $9500 ! ((grp_C70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C70C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B82
                dc.w $9500 ! ((grp_C76C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C76C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C76C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $837B
                dc.w $9500 ! ((grp_C7700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7700 / 2) >> 16)
                dc.w 2
