byte_2ED80C:    dc.b   0,  7,$75,$5F,$AB,$95,$8B,$76,$8C,$76
                                        ; DATA XREF: ROM:off_22D0   o
                dc.w sprite_24_24
                dc.w $8575
                dc.w $9500 ! ((grp_14C620 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C620 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $9C5E
                dc.w $9500 ! ((grp_14C740 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C740 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7582
                dc.w $9500 ! ((grp_89400 / 2) & $00FF)
                dc.w $9600 ! (((grp_89400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9D76
                dc.w $9500 ! ((grp_89480 / 2) & $00FF)
                dc.w $9600 ! (((grp_89480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8465
                dc.w $9500 ! ((grp_18CF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CF40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6588
                dc.w $9500 ! ((grp_D8D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858D
                dc.w $9500 ! ((grp_D8D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C6D
                dc.w $9500 ! ((grp_D8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8D80 / 2) >> 16)
                dc.w 2
