byte_2D43AE:    dc.b   0,  5,$6A,$65,$95,$90,$77,$75,$78,$75
                                        ; DATA XREF: ROM:off_10C4   o
                dc.w sprite_24_32
                dc.w $7065
                dc.w $9500 ! ((grp_FDB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FDB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FDB40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $586B
                dc.w $9500 ! ((grp_184D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_184D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184D80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $886D
                dc.w $9500 ! ((grp_1940E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1940E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1940E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9072
                dc.w $9500 ! ((grp_194140 / 2) & $00FF)
                dc.w $9600 ! (((grp_194140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194140 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6873
                dc.w $9500 ! ((grp_B2FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $775D
                dc.w $9500 ! ((grp_E5420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5420 / 2) >> 16)
                dc.w 1
