byte_2E8AE2:    dc.b   0,  4,$7A,$67,$85,$8E,$7D,$7A,$88,$6B
                                        ; DATA XREF: ROM:off_1DAC   o
                dc.w sprite_16_16
                dc.w $7F65
                dc.w $9500 ! ((grp_7C580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F75
                dc.w $9500 ! ((grp_A5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7783
                dc.w $9500 ! ((grp_B6540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F85
                dc.w $9500 ! ((grp_E8A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7765
                dc.w $9500 ! ((grp_E8A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8A40 / 2) >> 16)
                dc.w 1
