byte_2F6F36:    dc.b   0,$15,$79,$4E,$A0,$83,$85,$7B,$86,$7B
                                        ; DATA XREF: ROM:off_2B74   o
                dc.w sprite_24_32
                dc.w $8659
                dc.w $9500 ! ((grp_117340 / 2) & $00FF)
                dc.w $9600 ! (((grp_117340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117340 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $B62F
                dc.w $9500 ! ((grp_56B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7649
                dc.w $9500 ! ((grp_6E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_169180 / 2) & $00FF)
                dc.w $9600 ! (((grp_169180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169180 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8649
                dc.w $9500 ! ((grp_1690C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1690C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1690C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $AE3F
                dc.w $9500 ! ((grp_17F5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F5C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9E50
                dc.w $9500 ! ((grp_8EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B05F
                dc.w $9500 ! ((grp_8FC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $C63F
                dc.w $9500 ! ((grp_8FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D87
                dc.w $9500 ! ((grp_DD440 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C7B
                dc.w $9500 ! ((grp_C2D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $788F
                dc.w $9500 ! ((grp_F54E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F54E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F54E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C79
                dc.w $9500 ! ((grp_F4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F41
                dc.w $9500 ! ((grp_F4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9096
                dc.w $9500 ! ((grp_F5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E60
                dc.w $9500 ! ((grp_F4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A648
                dc.w $9500 ! ((grp_F4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A660
                dc.w $9500 ! ((grp_F4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AC6C
                dc.w $9500 ! ((grp_F5520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C84F
                dc.w $9500 ! ((grp_F5540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $CA57
                dc.w $9500 ! ((grp_F5560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5560 / 2) >> 16)
                dc.w 1
