byte_2EA99A:    dc.b   0,  4,$71,$6B,$91,$88,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_1F6C   o
                dc.w sprite_24_24
                dc.w $7671
                dc.w $9500 ! ((grp_149FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_149FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149FE0 / 2) >> 16)
                dc.w     9
                dc.w sprite_8_24
                dc.w $6E72
                dc.w $9500 ! ((grp_19B820 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B820 / 2) >> 16)
                dc.w     3
                dc.w sprite_8_24
                dc.w $8E72
                dc.w $9500 ! ((grp_19B880 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B880 / 2) >> 16)
                dc.w     3
                dc.w sprite_16_8
                dc.w $7769
                dc.w $9500 ! ((grp_D7300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7300 / 2) >> 16)
                dc.w     2
                dc.w sprite_16_8
                dc.w $7E89
                dc.w $9500 ! ((grp_D7340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7340 / 2) >> 16)
                dc.w     2
