byte_2EB336:    dc.b   0,  4,$71,$77,$8A,$8C,$7E,$75,$7F,$75
                                        ; DATA XREF: ROM:off_1FFC   o
                dc.w sprite_32_16
                dc.w $6B7A
                dc.w $9500 ! ((grp_51100 / 2) & $00FF)
                dc.w $9600 ! (((grp_51100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6D5A
                dc.w $9500 ! ((grp_17AB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AB80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6B72
                dc.w $9500 ! ((grp_18BEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BEC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_18BF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BF20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8B7F
                dc.w $9500 ! ((grp_EF440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF440 / 2) >> 16)
                dc.w 1
