byte_2F960C:    dc.b   0,  1,$75,$5D,$88,$6D,$7E,$65,$7F,$65
                                        ; DATA XREF: ROM:off_2D60   o
                dc.w sprite_24_16
                dc.w $735B
                dc.w $9500 ! ((grp_16A440 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A440 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7B6B
                dc.w $9500 ! ((grp_F68C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F68C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F68C0 / 2) >> 16)
                dc.w 1
