byte_2FD9FE:    dc.b   0,  6,$64,$5D,$A7,$8D,$85,$75,$86,$75
                                        ; DATA XREF: ROM:off_3324   o
                dc.w sprite_24_32
                dc.w $6658
                dc.w $9500 ! ((grp_11CBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11CBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11CBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6678
                dc.w $9500 ! ((grp_16D380 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8D7A
                dc.w $9500 ! ((grp_16D2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7E76
                dc.w $9500 ! ((grp_95480 / 2) & $00FF)
                dc.w $9600 ! (((grp_95480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95480 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6688
                dc.w $9500 ! ((grp_A1080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $5E61
                dc.w $9500 ! ((grp_C5B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A580
                dc.w $9500 ! ((grp_F8540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8540 / 2) >> 16)
                dc.w 1
