byte_2DA508:    dc.b   0, $C,$55,$51,$7A,$90,$67,$70,$6E,$5C
                                        ; DATA XREF: ROM:off_14A0   o
                dc.w sprite_24_32
                dc.w $606B
                dc.w $9500 ! ((grp_100E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_100E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6051
                dc.w $9500 ! ((grp_1421E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1421E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1421E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $508B
                dc.w $9500 ! ((grp_98880 / 2) & $00FF)
                dc.w $9600 ! (((grp_98880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $504B
                dc.w $9500 ! ((grp_1951C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1951C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1951C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708B
                dc.w $9500 ! ((grp_CAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5863
                dc.w $9500 ! ((grp_B4840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5853
                dc.w $9500 ! ((grp_B3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $506C
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5883
                dc.w $9500 ! ((grp_E6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $584B
                dc.w $9500 ! ((grp_E6FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $587B
                dc.w $9500 ! ((grp_E58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5873
                dc.w $9500 ! ((grp_E58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7851
                dc.w $9500 ! ((grp_E5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A00 / 2) >> 16)
                dc.w 1
