byte_2D3D94:    dc.b   0,  7,$6C,$5A,$8D,$8F,$79,$74,$7A,$74
                                        ; DATA XREF: ROM:00001080   o
                dc.w sprite_24_32
                dc.w $7870
                dc.w $9500 ! ((grp_FD840 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD840 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6E60
                dc.w $9500 ! ((grp_48C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $6874
                dc.w $9500 ! ((grp_CA940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7158
                dc.w $9500 ! ((grp_CA980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7082
                dc.w $9500 ! ((grp_B2D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6286
                dc.w $9500 ! ((grp_E50E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E50E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E50E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6661
                dc.w $9500 ! ((grp_E5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $688A
                dc.w $9500 ! ((grp_E5120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5120 / 2) >> 16)
                dc.w 1
