byte_2FD8D8:    dc.b   0,  7,$5F,$43,$95,$8D,$7B,$68,$7C,$68
                                        ; DATA XREF: ROM:off_3318   o
                dc.w sprite_16_32
                dc.w $8868
                dc.w $9500 ! ((grp_70F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7588
                dc.w $9500 ! ((grp_A1000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6950
                dc.w $9500 ! ((grp_1910E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1910E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1910E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6148
                dc.w $9500 ! ((grp_DFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A58
                dc.w $9500 ! ((grp_DFE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8260
                dc.w $9500 ! ((grp_DFE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F41
                dc.w $9500 ! ((grp_F84C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F84C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F84C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8080
                dc.w $9500 ! ((grp_F84E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F84E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F84E0 / 2) >> 16)
                dc.w 1
