byte_2E1CF8:    dc.b   0,  5,$62,$65,$8C,$8F,$77,$7A,$7C,$8D
                                        ; DATA XREF: ROM:off_19A0   o
                dc.w sprite_32_16
                dc.w $6274
                dc.w $9500 ! ((grp_4BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4BE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8063
                dc.w $9500 ! ((grp_62600 / 2) & $00FF)
                dc.w $9600 ! (((grp_62600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7184
                dc.w $9500 ! ((grp_7E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $606C
                dc.w $9500 ! ((grp_E9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $786C
                dc.w $9500 ! ((grp_E9BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8183
                dc.w $9500 ! ((grp_E9BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9BC0 / 2) >> 16)
                dc.w 1
