byte_2F926C:    dc.b   0,  5,$67,$71,$90,$92,$7B,$81,$7C,$81
                                        ; DATA XREF: ROM:off_2D20   o
                dc.w sprite_16_24
                dc.w $637F
                dc.w $9500 ! ((grp_180100 / 2) & $00FF)
                dc.w $9600 ! (((grp_180100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B6F
                dc.w $9500 ! ((grp_180040 / 2) & $00FF)
                dc.w $9600 ! (((grp_180040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180040 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $737A
                dc.w $9500 ! ((grp_19F5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F5A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B87
                dc.w $9500 ! ((grp_DE400 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B75
                dc.w $9500 ! ((grp_C3F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B8F
                dc.w $9500 ! ((grp_F6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6600 / 2) >> 16)
                dc.w 1
