byte_2D50EA:    dc.b   0,  5,$6E,$64,$8E,$8F,$78,$78,$70,$69
                                        ; DATA XREF: ROM:off_1164   o
                dc.w sprite_32_32
                dc.w $6360
                dc.w $9500 ! ((grp_18A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6B80
                dc.w $9500 ! ((grp_78500 / 2) & $00FF)
                dc.w $9600 ! (((grp_78500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CB500 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B61
                dc.w $9500 ! ((grp_E5F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B80
                dc.w $9500 ! ((grp_E5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8282
                dc.w $9500 ! ((grp_E5EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5EE0 / 2) >> 16)
                dc.w 1
