byte_2EBFE6:    dc.b   0,  1,$78,$5F,$8C,$88,$82,$73,$83,$73
                                        ; DATA XREF: ROM:off_2094   o
                dc.w sprite_24_32
                dc.w $776D
                dc.w $9500 ! ((grp_111040 / 2) & $00FF)
                dc.w $9600 ! (((grp_111040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $815D
                dc.w $9500 ! ((grp_87B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_87B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87B80 / 2) >> 16)
                dc.w 4
