byte_2D87D4:    dc.b   0,  7,$6F,$5A,$8E,$90,$89,$74,$79,$61
                                        ; DATA XREF: ROM:off_13B0   o
                dc.w sprite_24_24
                dc.w $7961
                dc.w $9500 ! ((grp_147760 / 2) & $00FF)
                dc.w $9600 ! (((grp_147760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147760 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8181
                dc.w $9500 ! ((grp_161B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_161B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7159
                dc.w $9500 ! ((grp_D4900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8779
                dc.w $9500 ! ((grp_D4940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9168
                dc.w $9500 ! ((grp_D4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7161
                dc.w $9500 ! ((grp_ED060 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B59
                dc.w $9500 ! ((grp_ED080 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9161
                dc.w $9500 ! ((grp_ED0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED0A0 / 2) >> 16)
                dc.w 1
