byte_2ED214:    dc.b   0,  1,$6C,$7F,$96,$8E,$7F,$87,$80,$87
                                        ; DATA XREF: ROM:off_2278   o
                dc.w sprite_24_16
                dc.w $757E
                dc.w $9500 ! ((grp_1645C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1645C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1645C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $758E
                dc.w $9500 ! ((grp_D8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8600 / 2) >> 16)
                dc.w 2
