byte_2E515A:    dc.b   0,  9,$6F,$62,$88,$8E,$4B,$95,$78,$62
                                        ; DATA XREF: ROM:off_1BA4   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8261
                dc.w $9500 ! ((grp_160900 / 2) & $00FF)
                dc.w $9600 ! (((grp_160900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82180 / 2) & $00FF)
                dc.w $9600 ! (((grp_82180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9247
                dc.w $9500 ! ((grp_82600 / 2) & $00FF)
                dc.w $9600 ! (((grp_82600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8271
                dc.w $9500 ! ((grp_D3740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_BA400 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A67
                dc.w $9500 ! ((grp_EC440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC440 / 2) >> 16)
                dc.w 1
