byte_2E12D2:    dc.b   0, $D,$72,$5A,$8E,$8E,$7A,$46,$77,$31
                                        ; DATA XREF: ROM:off_1934   o
                dc.w sprite_24_16
                dc.w $753F
                dc.w $9500 ! ((grp_15BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5440
                dc.w $9500 ! ((grp_7B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $832F
                dc.w $9500 ! ((grp_7AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $932C
                dc.w $9500 ! ((grp_7B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $632F
                dc.w $9500 ! ((grp_98B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6337
                dc.w $9500 ! ((grp_185EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $695E
                dc.w $9500 ! ((grp_185F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_185F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6F27
                dc.w $9500 ! ((grp_185FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7B4F
                dc.w $9500 ! ((grp_185E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_185E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6541
                dc.w $9500 ! ((grp_CD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9255
                dc.w $9500 ! ((grp_CD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7957
                dc.w $9500 ! ((grp_E7B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B37
                dc.w $9500 ! ((grp_E7AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A4D
                dc.w $9500 ! ((grp_E7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B00 / 2) >> 16)
                dc.w 1
