byte_2DA3E0:    dc.b   0, $B,$56,$52,$7A,$8E,$68,$70,$75,$58
                                        ; DATA XREF: ROM:off_1498   o
                dc.w sprite_16_32
                dc.w $685C
                dc.w $9500 ! ((grp_5FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5FC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $687C
                dc.w $9500 ! ((grp_173740 / 2) & $00FF)
                dc.w $9600 ! (((grp_173740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $604C
                dc.w $9500 ! ((grp_77B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_77B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $504C
                dc.w $9500 ! ((grp_A4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $586C
                dc.w $9500 ! ((grp_CB000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $704C
                dc.w $9500 ! ((grp_CB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $605C
                dc.w $9500 ! ((grp_B34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B34C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $584C
                dc.w $9500 ! ((grp_E5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6084
                dc.w $9500 ! ((grp_E58E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7054
                dc.w $9500 ! ((grp_E6F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7889
                dc.w $9500 ! ((grp_E5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7854
                dc.w $9500 ! ((grp_E5960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5960 / 2) >> 16)
                dc.w 1
