byte_2D5442:    dc.b   0,  6,$6F,$64,$8E,$8F,$82,$78,$7D,$68
                                        ; DATA XREF: ROM:off_118C   o
                dc.w sprite_24_32
                dc.w $7669
                dc.w $9500 ! ((grp_103FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_103FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C61
                dc.w $9500 ! ((grp_1870C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1870C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1870C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6E6B
                dc.w $9500 ! ((grp_196C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_196C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196C60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CF440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CF480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E68
                dc.w $9500 ! ((grp_B6D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9669
                dc.w $9500 ! ((grp_E91C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E91C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E91C0 / 2) >> 16)
                dc.w 1
