byte_2D030A:    dc.b   0,  2,$70,$6E,$8C,$8C,$7E,$7D,$7F,$7D
                                        ; DATA XREF: ROM:off_D04   o
                dc.w sprite_24_24
                dc.w $777C
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6C
                dc.w $9500 ! ((grp_46D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8E6C
                dc.w $9500 ! ((grp_E3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3180 / 2) >> 16)
                dc.w 1
