byte_2FB67E:    dc.b   0,  4,$66,$62,$92,$90,$7C,$79,$7D,$79
                                        ; DATA XREF: ROM:off_2F84   o
                dc.w sprite_24_16
                dc.w $6185
                dc.w $9500 ! ((grp_16B940 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B940 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8185
                dc.w $9500 ! ((grp_16BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16BA00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7978
                dc.w $9500 ! ((grp_AEB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B60
                dc.w $9500 ! ((grp_1A0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0140 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7360
                dc.w $9500 ! ((grp_F7CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7CE0 / 2) >> 16)
                dc.w 1
