byte_2CCF06:    dc.b   0,  2,$6E,$72,$8F,$8D,$7E,$7F,$7F,$7F
                                        ; DATA XREF: ROM:off_84C   o
                dc.w sprite_24_32
                dc.w $7470
                dc.w $9500 ! ((grp_FA3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $6C79
                dc.w $9500 ! ((grp_B09C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B09C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B09C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C78
                dc.w $9500 ! ((grp_B0A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0A00 / 2) >> 16)
                dc.w 2
