byte_2E8F3E:    dc.b   0,  4,$7B,$58,$83,$8F,$81,$72,$7D,$64
                                        ; DATA XREF: ROM:00001DF4   o
                dc.w sprite_8_32
                dc.w $7D74
                dc.w $9500 ! ((grp_A6480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7862
                dc.w $9500 ! ((grp_197B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_197B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197B00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7A53
                dc.w $9500 ! ((grp_197B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_197B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197B60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7583
                dc.w $9500 ! ((grp_B87C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B87C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B87C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $857A
                dc.w $9500 ! ((grp_EA920 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA920 / 2) >> 16)
                dc.w 1
