byte_2EA5CA:    dc.b   0,  6,$66,$5B,$98,$8D,$7F,$74,$80,$74
                                        ; DATA XREF: ROM:off_1F44   o
                dc.w sprite_32_32
                dc.w $6E58
                dc.w $9500 ! ((grp_29A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_29A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_29A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6278
                dc.w $9500 ! ((grp_1306C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1306C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1306C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8278
                dc.w $9500 ! ((grp_149DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_149DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149DA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $8E60
                dc.w $9500 ! ((grp_17A7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A7C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7850
                dc.w $9500 ! ((grp_18BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BB00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6660
                dc.w $9500 ! ((grp_19B520 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8E58
                dc.w $9500 ! ((grp_EF0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF0C0 / 2) >> 16)
                dc.w 1
