byte_2F1BAA:    dc.b   0,  7,$75,$48,$97,$71,$86,$5F,$87,$5F
                                        ; DATA XREF: ROM:off_26B4   o
                dc.w sprite_24_16
                dc.w $7656
                dc.w $9500 ! ((grp_166CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_166CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $764E
                dc.w $9500 ! ((grp_DAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8666
                dc.w $9500 ! ((grp_DAEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E52
                dc.w $9500 ! ((grp_F22A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F22A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F22A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B46
                dc.w $9500 ! ((grp_F2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $876E
                dc.w $9500 ! ((grp_F22C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F22C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F22C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E5E
                dc.w $9500 ! ((grp_F2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9268
                dc.w $9500 ! ((grp_F2260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2260 / 2) >> 16)
                dc.w 1
