byte_2D513C:    dc.b   0, $A,$6E,$64,$8E,$8F,$83,$79,$7D,$6D
                                        ; DATA XREF: ROM:off_1168   o
                dc.w sprite_32_24
                dc.w $6668
                dc.w $9500 ! ((grp_1237C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1237C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1237C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8E70
                dc.w $9500 ! ((grp_172840 / 2) & $00FF)
                dc.w $9600 ! (((grp_172840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7E80
                dc.w $9500 ! ((grp_78580 / 2) & $00FF)
                dc.w $9600 ! (((grp_78580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6660
                dc.w $9500 ! ((grp_185140 / 2) & $00FF)
                dc.w $9600 ! (((grp_185140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185140 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CB540 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E80
                dc.w $9500 ! ((grp_CB580 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E68
                dc.w $9500 ! ((grp_CB5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E88
                dc.w $9500 ! ((grp_CB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8363
                dc.w $9500 ! ((grp_E5F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8678
                dc.w $9500 ! ((grp_E5F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E76
                dc.w $9500 ! ((grp_E5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5F80 / 2) >> 16)
                dc.w 1
