byte_2F1508:    dc.b   0,  9,$66,$64,$A2,$9C,$85,$7A,$86,$7A
                                        ; DATA XREF: ROM:off_2648   o
                dc.w sprite_32_32
                dc.w $6657
                dc.w $9500 ! ((grp_38C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_38C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $8782
                dc.w $9500 ! ((grp_135AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_135AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $866A
                dc.w $9500 ! ((grp_14EFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14EFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14EFC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $5F8C
                dc.w $9500 ! ((grp_167080 / 2) & $00FF)
                dc.w $9600 ! (((grp_167080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7788
                dc.w $9500 ! ((grp_17D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7777
                dc.w $9500 ! ((grp_8C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $5E62
                dc.w $9500 ! ((grp_C0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E6E
                dc.w $9500 ! ((grp_C0840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A785
                dc.w $9500 ! ((grp_C0880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D4F
                dc.w $9500 ! ((grp_F2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2680 / 2) >> 16)
                dc.w 1
