byte_2F1706:    dc.b   0,  2,$73,$69,$8D,$88,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_266C   o
                dc.w sprite_24_24
                dc.w $7067
                dc.w $9500 ! ((grp_14F0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F0E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $7F7F
                dc.w $9500 ! ((grp_C09C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C09C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C09C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $886B
                dc.w $9500 ! ((grp_C0A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0A00 / 2) >> 16)
                dc.w 2
