byte_2D7112:    dc.b   0,  7,$74,$55,$92,$7A,$81,$4C,$8C,$50
                                        ; DATA XREF: ROM:off_12B4   o
                dc.w sprite_24_24
                dc.w $7B49
                dc.w $9500 ! ((grp_148F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_148F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148F00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7B61
                dc.w $9500 ! ((grp_66C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6B51
                dc.w $9500 ! ((grp_86480 / 2) & $00FF)
                dc.w $9600 ! (((grp_86480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9359
                dc.w $9500 ! ((grp_86500 / 2) & $00FF)
                dc.w $9600 ! (((grp_86500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6559
                dc.w $9500 ! ((grp_BD080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7674
                dc.w $9500 ! ((grp_BD0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B79
                dc.w $9500 ! ((grp_EE6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE6E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B69
                dc.w $9500 ! ((grp_EE700 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE700 / 2) >> 16)
                dc.w 1
