byte_2D4B3E:    dc.b   0,  5,$50,$5E,$87,$82,$6B,$70,$6C,$70
                                        ; DATA XREF: ROM:off_111C   o
                dc.w sprite_32_16
                dc.w $565C
                dc.w $9500 ! ((grp_4C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $566C
                dc.w $9500 ! ((grp_7ED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7ED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7ED80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4E65
                dc.w $9500 ! ((grp_A6180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $765D
                dc.w $9500 ! ((grp_D0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $567C
                dc.w $9500 ! ((grp_E9F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8264
                dc.w $9500 ! ((grp_E9EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9EE0 / 2) >> 16)
                dc.w 1
