byte_2DC8C6:    dc.b   0,  5,$77,$57,$90,$99,$89,$78,$83,$6D
                                        ; DATA XREF: ROM:off_1644   o
                dc.w sprite_32_24
                dc.w $7570
                dc.w $9500 ! ((grp_124CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_124CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7C86
                dc.w $9500 ! ((grp_4A100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8350
                dc.w $9500 ! ((grp_173980 / 2) & $00FF)
                dc.w $9600 ! (((grp_173980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7668
                dc.w $9500 ! ((grp_185920 / 2) & $00FF)
                dc.w $9600 ! (((grp_185920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D96
                dc.w $9500 ! ((grp_CCD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9C8C
                dc.w $9500 ! ((grp_E7240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7240 / 2) >> 16)
                dc.w 1
