byte_2E1D4A:    dc.b   0,  2,$7A,$7C,$96,$8E,$88,$85,$89,$85
                                        ; DATA XREF: ROM:off_19A4   o
                dc.w sprite_24_16
                dc.w $787A
                dc.w $9500 ! ((grp_15E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $788A
                dc.w $9500 ! ((grp_D0240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $907C
                dc.w $9500 ! ((grp_B74C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B74C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B74C0 / 2) >> 16)
                dc.w 2
