byte_2EB55E:    dc.b   0,  5,$71,$55,$8F,$8D,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_202C   o
                dc.w sprite_32_32
                dc.w $706C
                dc.w $9500 ! ((grp_2AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2AC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $788C
                dc.w $9500 ! ((grp_87600 / 2) & $00FF)
                dc.w $9600 ! (((grp_87600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6874
                dc.w $9500 ! ((grp_AA680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $906C
                dc.w $9500 ! ((grp_AA700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $888C
                dc.w $9500 ! ((grp_D7B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $708C
                dc.w $9500 ! ((grp_EF500 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF500 / 2) >> 16)
                dc.w 1
