byte_2F3034:    dc.b   0,  6,$6D,$5F,$8E,$91,$76,$78,$77,$78
                                        ; DATA XREF: ROM:off_2788   o
                dc.w sprite_24_32
                dc.w $756D
                dc.w $9500 ! ((grp_114940 / 2) & $00FF)
                dc.w $9600 ! (((grp_114940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114940 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6F8D
                dc.w $9500 ! ((grp_9F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5D6A
                dc.w $9500 ! ((grp_18E3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7565
                dc.w $9500 ! ((grp_18E440 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D6D
                dc.w $9500 ! ((grp_19DC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DC80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6572
                dc.w $9500 ! ((grp_DB940 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B5D
                dc.w $9500 ! ((grp_DB980 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB980 / 2) >> 16)
                dc.w 2
