byte_2E79AC:    dc.b   0,  4,$6F,$6C,$8E,$8F,$7D,$6D,$8A,$7D
                                        ; DATA XREF: ROM:off_1D08   o
                dc.w sprite_24_32
                dc.w $7671
                dc.w $9500 ! ((grp_1057C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1057C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1057C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8E79
                dc.w $9500 ! ((grp_1976E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1976E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1976E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A69
                dc.w $9500 ! ((grp_D0CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $967B
                dc.w $9500 ! ((grp_B8240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E89
                dc.w $9500 ! ((grp_EA360 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA360 / 2) >> 16)
                dc.w 1
