byte_2F7048:    dc.b   0,$12,$7B,$4F,$A2,$83,$85,$7A,$86,$7A
                                        ; DATA XREF: ROM:off_2B78   o
                dc.w sprite_24_32
                dc.w $8659
                dc.w $9500 ! ((grp_117340 / 2) & $00FF)
                dc.w $9600 ! (((grp_117340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117340 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $B12D
                dc.w $9500 ! ((grp_1378C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1378C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1378C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7649
                dc.w $9500 ! ((grp_6E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_169180 / 2) & $00FF)
                dc.w $9600 ! (((grp_169180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169180 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8649
                dc.w $9500 ! ((grp_1690C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1690C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1690C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9E50
                dc.w $9500 ! ((grp_8EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AE45
                dc.w $9500 ! ((grp_8FD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B25E
                dc.w $9500 ! ((grp_8FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F8D
                dc.w $9500 ! ((grp_18F280 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $C746
                dc.w $9500 ! ((grp_19EE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EE80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C79
                dc.w $9500 ! ((grp_F4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F41
                dc.w $9500 ! ((grp_F4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E60
                dc.w $9500 ! ((grp_F4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F80
                dc.w $9500 ! ((grp_F55A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F55A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F55A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A648
                dc.w $9500 ! ((grp_F4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A660
                dc.w $9500 ! ((grp_F4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AD6B
                dc.w $9500 ! ((grp_F55C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F55C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F55C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $CF41
                dc.w $9500 ! ((grp_F5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5580 / 2) >> 16)
                dc.w 1
