byte_2D4C56:    dc.b   0,  3,$60,$74,$93,$84,$79,$7C,$7A,$7C
                                        ; DATA XREF: ROM:off_112C   o
                dc.w sprite_32_16
                dc.w $5E72
                dc.w $9500 ! ((grp_4D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7E72
                dc.w $9500 ! ((grp_80700 / 2) & $00FF)
                dc.w $9600 ! (((grp_80700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6682
                dc.w $9500 ! ((grp_D2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E75
                dc.w $9500 ! ((grp_EB080 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB080 / 2) >> 16)
                dc.w 1
