byte_2ED314:    dc.b   0,  7,$96,$6F,$A1,$85,$84,$7F,$85,$7F
                                        ; DATA XREF: ROM:off_2288   o
                dc.w sprite_24_24
                dc.w $8C6D
                dc.w $9500 ! ((grp_14BE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_14BE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14BE40 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $7C72
                dc.w $9500 ! ((grp_AAE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8470
                dc.w $9500 ! ((grp_AAE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7479
                dc.w $9500 ! ((grp_19C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6489
                dc.w $9500 ! ((grp_D89C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D89C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D89C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C81
                dc.w $9500 ! ((grp_F0160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C85
                dc.w $9500 ! ((grp_F0180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9885
                dc.w $9500 ! ((grp_F01A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F01A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F01A0 / 2) >> 16)
                dc.w 1
