byte_2E0A14:    dc.b   0,  6,$42,$34,$76,$67,$5C,$4D,$6B,$3A
                                        ; DATA XREF: ROM:off_18F8   o
                dc.w sprite_32_24
                dc.w $4052
                dc.w $9500 ! ((grp_12B8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4142
                dc.w $9500 ! ((grp_4EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6049
                dc.w $9500 ! ((grp_177340 / 2) & $00FF)
                dc.w $9600 ! (((grp_177340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6131
                dc.w $9500 ! ((grp_177400 / 2) & $00FF)
                dc.w $9600 ! (((grp_177400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $513A
                dc.w $9500 ! ((grp_D2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6061
                dc.w $9500 ! ((grp_EBD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7132
                dc.w $9500 ! ((grp_EBD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD40 / 2) >> 16)
                dc.w 1
