byte_2D7E9C:    dc.b   0,  4,$75,$5D,$8B,$A2,$84,$7F,$82,$6A
                                        ; DATA XREF: ROM:off_1348   o
                dc.w sprite_32_24
                dc.w $6E6E
                dc.w $9500 ! ((grp_124540 / 2) & $00FF)
                dc.w $9600 ! (((grp_124540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7786
                dc.w $9500 ! ((grp_172D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_172D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8E69
                dc.w $9500 ! ((grp_172FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_172FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7D5E
                dc.w $9500 ! ((grp_B4080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F9E
                dc.w $9500 ! ((grp_E6820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6820 / 2) >> 16)
                dc.w 1
