byte_2D163A:    dc.b   0,  5,$63,$61,$9C,$8D,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_E1C   o
                dc.w sprite_32_32
                dc.w $7062
                dc.w $9500 ! ((grp_15A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8C69
                dc.w $9500 ! ((grp_FC340 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6069
                dc.w $9500 ! ((grp_5D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7082
                dc.w $9500 ! ((grp_76580 / 2) & $00FF)
                dc.w $9600 ! (((grp_76580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8C61
                dc.w $9500 ! ((grp_C94C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C94C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C94C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8082
                dc.w $9500 ! ((grp_E3A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3A40 / 2) >> 16)
                dc.w 1
