byte_2DFBA2:    dc.b   0,  8,$4F,$67,$8D,$8E,$6E,$7A,$65,$6E
                                        ; DATA XREF: ROM:off_1854   o
                dc.w sprite_24_32
                dc.w $6065
                dc.w $9500 ! ((grp_108AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_108AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6885
                dc.w $9500 ! ((grp_81000 / 2) & $00FF)
                dc.w $9600 ! (((grp_81000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7870
                dc.w $9500 ! ((grp_A6D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5075
                dc.w $9500 ! ((grp_198700 / 2) & $00FF)
                dc.w $9600 ! (((grp_198700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198700 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8078
                dc.w $9500 ! ((grp_198760 / 2) & $00FF)
                dc.w $9600 ! (((grp_198760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198760 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5879
                dc.w $9500 ! ((grp_B9540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4880
                dc.w $9500 ! ((grp_EB6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB6C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $586C
                dc.w $9500 ! ((grp_EB6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB6E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8888
                dc.w $9500 ! ((grp_EB700 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB700 / 2) >> 16)
                dc.w 1
