byte_2F5214:    dc.b   0,  5,$6F,$60,$8D,$98,$7B,$7C,$7C,$7C
                                        ; DATA XREF: ROM:off_2A48   o
                dc.w sprite_32_32
                dc.w $7075
                dc.w $9500 ! ((grp_3C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $775D
                dc.w $9500 ! ((grp_168880 / 2) & $00FF)
                dc.w $9600 ! (((grp_168880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168880 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $706D
                dc.w $9500 ! ((grp_18EBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EBC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7695
                dc.w $9500 ! ((grp_18EC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EC20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $687E
                dc.w $9500 ! ((grp_C1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F61
                dc.w $9500 ! ((grp_F44E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F44E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F44E0 / 2) >> 16)
                dc.w 1
