byte_2FC952:    dc.b   0,  2,$77,$78,$89,$86,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_316C   o
                dc.w sprite_16_16
                dc.w $7F76
                dc.w $9500 ! ((grp_93900 / 2) & $00FF)
                dc.w $9600 ! (((grp_93900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7779
                dc.w $9500 ! ((grp_C5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F83
                dc.w $9500 ! ((grp_F7FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7FE0 / 2) >> 16)
                dc.w 1
