byte_2F9232:    dc.b   0,  3,$71,$7B,$8D,$92,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_2D1C   o
                dc.w sprite_24_24
                dc.w $7079
                dc.w $9500 ! ((grp_152380 / 2) & $00FF)
                dc.w $9600 ! (((grp_152380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152380 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $887E
                dc.w $9500 ! ((grp_19F540 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7891
                dc.w $9500 ! ((grp_DE3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697F
                dc.w $9500 ! ((grp_F65E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F65E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F65E0 / 2) >> 16)
                dc.w 1
