byte_2E2DF8:    dc.b   0,  6,$6F,$3B,$8E,$8F,$7E,$4B,$84,$47
                                        ; DATA XREF: ROM:off_1A68   o
                dc.w sprite_24_32
                dc.w $7539
                dc.w $9500 ! ((grp_106240 / 2) & $00FF)
                dc.w $9600 ! (((grp_106240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7E59
                dc.w $9500 ! ((grp_4D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $6B67
                dc.w $9500 ! ((grp_188740 / 2) & $00FF)
                dc.w $9600 ! (((grp_188740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6D45
                dc.w $9500 ! ((grp_197C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_197C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D55
                dc.w $9500 ! ((grp_D1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6C6F
                dc.w $9500 ! ((grp_D14C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D14C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D14C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D3A
                dc.w $9500 ! ((grp_EAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAB80 / 2) >> 16)
                dc.w 1
