byte_2EA7D0:    dc.b   0,  7,$66,$5A,$97,$8D,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_1F58   o
                dc.w sprite_32_32
                dc.w $6A70
                dc.w $9500 ! ((grp_2A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2A000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6A60
                dc.w $9500 ! ((grp_51000 / 2) & $00FF)
                dc.w $9600 ! (((grp_51000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8A58
                dc.w $9500 ! ((grp_17AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AA00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6A58
                dc.w $9500 ! ((grp_9C580 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_AA100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A70
                dc.w $9500 ! ((grp_AA080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7850
                dc.w $9500 ! ((grp_18BC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BC20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9270
                dc.w $9500 ! ((grp_19B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B700 / 2) >> 16)
                dc.w 3
