byte_2D2728:    dc.b   0, $E,$5D,$4A,$A3,$73,$79,$7B,$7A,$7B
                                        ; DATA XREF: ROM:off_EF0   o
                dc.w sprite_16_32
                dc.w $5A62
                dc.w $9500 ! ((grp_5E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5A82
                dc.w $9500 ! ((grp_171940 / 2) & $00FF)
                dc.w $9600 ! (((grp_171940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171940 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6A5D
                dc.w $9500 ! ((grp_A4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A7D
                dc.w $9500 ! ((grp_A4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7272
                dc.w $9500 ! ((grp_A4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7A6A
                dc.w $9500 ! ((grp_A4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8262
                dc.w $9500 ! ((grp_A4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A5A
                dc.w $9500 ! ((grp_A4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5278
                dc.w $9500 ! ((grp_1938A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1938A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1938A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $725A
                dc.w $9500 ! ((grp_193900 / 2) & $00FF)
                dc.w $9600 ! (((grp_193900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193900 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A5A
                dc.w $9500 ! ((grp_B2800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $925F
                dc.w $9500 ! ((grp_B2840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $609A
                dc.w $9500 ! ((grp_E4460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $825A
                dc.w $9500 ! ((grp_E4420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A62
                dc.w $9500 ! ((grp_E4440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4440 / 2) >> 16)
                dc.w 1
