byte_2DC182:    dc.b   0,  6,$74,$5A,$A5,$90,$91,$67,$92,$67
                                        ; DATA XREF: ROM:off_15FC   o
                dc.w sprite_24_24
                dc.w $885A
                dc.w $9500 ! ((grp_149020 / 2) & $00FF)
                dc.w $9600 ! (((grp_149020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149020 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $785F
                dc.w $9500 ! ((grp_86700 / 2) & $00FF)
                dc.w $9600 ! (((grp_86700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9C68
                dc.w $9500 ! ((grp_18B140 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B140 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8872
                dc.w $9500 ! ((grp_D6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9352
                dc.w $9500 ! ((grp_D67C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D67C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D67C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7063
                dc.w $9500 ! ((grp_EE760 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A05A
                dc.w $9500 ! ((grp_EE780 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE780 / 2) >> 16)
                dc.w 1
