byte_2FC440:    dc.b   0, $C,$48,$5A,$BC,$B4,$82,$93,$83,$93
                                        ; DATA XREF: ROM:off_3110   o
                dc.w sprite_16_16
                dc.w $4375
                dc.w $9500 ! ((grp_93200 / 2) & $00FF)
                dc.w $9600 ! (((grp_93200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $537D
                dc.w $9500 ! ((grp_93180 / 2) & $00FF)
                dc.w $9600 ! (((grp_93180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6385
                dc.w $9500 ! ((grp_93100 / 2) & $00FF)
                dc.w $9600 ! (((grp_93100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $738D
                dc.w $9500 ! ((grp_93080 / 2) & $00FF)
                dc.w $9600 ! (((grp_93080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8395
                dc.w $9500 ! ((grp_93000 / 2) & $00FF)
                dc.w $9600 ! (((grp_93000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $9BA5
                dc.w $9500 ! ((grp_A0880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $A8AD
                dc.w $9500 ! ((grp_190D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_190D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9B9D
                dc.w $9500 ! ((grp_DF780 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9399
                dc.w $9500 ! ((grp_C5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5375
                dc.w $9500 ! ((grp_F7EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $637D
                dc.w $9500 ! ((grp_F7E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7385
                dc.w $9500 ! ((grp_F7E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $838D
                dc.w $9500 ! ((grp_F7E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7E40 / 2) >> 16)
                dc.w 1
