byte_2E7D36:    dc.b   0, $B,$72,$62,$8C,$7C,$BB,$4F,$A1,$51
                                        ; DATA XREF: ROM:off_1D2C   o
                dc.w sprite_24_24
                dc.w $6B67
                dc.w $9500 ! ((grp_1457E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1457E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1457E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $AB44
                dc.w $9500 ! ((grp_99D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_99D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $835C
                dc.w $9500 ! ((grp_A6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $CB44
                dc.w $9500 ! ((grp_D1000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9355
                dc.w $9500 ! ((grp_B8440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9B4E
                dc.w $9500 ! ((grp_B8480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A345
                dc.w $9500 ! ((grp_B84C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B84C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B84C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6369
                dc.w $9500 ! ((grp_EA640 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B5F
                dc.w $9500 ! ((grp_EA600 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B5F
                dc.w $9500 ! ((grp_EA620 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AB4C
                dc.w $9500 ! ((grp_EA660 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $D34C
                dc.w $9500 ! ((grp_EA680 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA680 / 2) >> 16)
                dc.w 1
