byte_2D0268:    dc.b   0,  3,$6E,$64,$86,$82,$7A,$73,$7B,$73
                                        ; DATA XREF: ROM:off_CF8   o
                dc.w sprite_24_24
                dc.w $716D
                dc.w $9500 ! ((grp_13EAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13EAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13EAC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7965
                dc.w $9500 ! ((grp_C8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $696A
                dc.w $9500 ! ((grp_E31E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E31E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E31E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $805D
                dc.w $9500 ! ((grp_E3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3200 / 2) >> 16)
                dc.w 1
