byte_2EE15A:    dc.b   0,  6,$6A,$6D,$97,$94,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_236C   o
                dc.w sprite_32_32
                dc.w $706B
                dc.w $9500 ! ((grp_31400 / 2) & $00FF)
                dc.w $9600 ! (((grp_31400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31400 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $9070
                dc.w $9500 ! ((grp_AB700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $748B
                dc.w $9500 ! ((grp_18D060 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D060 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6875
                dc.w $9500 ! ((grp_19CD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CD20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7793
                dc.w $9500 ! ((grp_D91C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D91C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D91C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6082
                dc.w $9500 ! ((grp_BF200 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9880
                dc.w $9500 ! ((grp_BF240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF240 / 2) >> 16)
                dc.w 2
