byte_2F2D38:    dc.b   0,  6,$72,$5C,$91,$93,$83,$79,$84,$79
                                        ; DATA XREF: ROM:off_2768   o
                dc.w sprite_32_24
                dc.w $7C5C
                dc.w $9500 ! ((grp_136540 / 2) & $00FF)
                dc.w $9600 ! (((grp_136540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136540 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7474
                dc.w $9500 ! ((grp_55900 / 2) & $00FF)
                dc.w $9600 ! (((grp_55900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6C64
                dc.w $9500 ! ((grp_8D480 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7584
                dc.w $9500 ! ((grp_8D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7294
                dc.w $9500 ! ((grp_F31E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F31E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F31E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8584
                dc.w $9500 ! ((grp_F3220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9455
                dc.w $9500 ! ((grp_F3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3200 / 2) >> 16)
                dc.w 1
