byte_2D0024:    dc.b   0,  1,$7A,$74,$87,$84,$80,$7C,$81,$7C
                                        ; DATA XREF: ROM:off_CB8   o
                dc.w sprite_24_24
                dc.w $7874
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $796C
                dc.w $9500 ! ((grp_C8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B00 / 2) >> 16)
                dc.w 2
