byte_2DD2EE:    dc.b   0,  6,$76,$63,$92,$82,$7E,$74,$88,$66
                                        ; DATA XREF: ROM:off_16AC   o
                dc.w sprite_16_32
                dc.w $8171
                dc.w $9500 ! ((grp_60400 / 2) & $00FF)
                dc.w $9600 ! (((grp_60400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6161
                dc.w $9500 ! ((grp_15B5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B5C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8159
                dc.w $9500 ! ((grp_173B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_173B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7969
                dc.w $9500 ! ((grp_A5080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $915E
                dc.w $9500 ! ((grp_1955E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1955E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1955E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7959
                dc.w $9500 ! ((grp_B4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7179
                dc.w $9500 ! ((grp_E7580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7580 / 2) >> 16)
                dc.w 1
