byte_2D5EAE:    dc.b   0,  5,$7D,$59,$97,$98,$82,$6A,$82,$69
                                        ; DATA XREF: ROM:off_11FC   o
                dc.w sprite_24_32
                dc.w $7B5A
                dc.w $9500 ! ((grp_104440 / 2) & $00FF)
                dc.w $9600 ! (((grp_104440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $827A
                dc.w $9500 ! ((grp_1445E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1445E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1445E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7B92
                dc.w $9500 ! ((grp_7D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A7A
                dc.w $9500 ! ((grp_E9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8252
                dc.w $9500 ! ((grp_E92A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E92A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E92A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A88
                dc.w $9500 ! ((grp_E92C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E92C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E92C0 / 2) >> 16)
                dc.w 1
