byte_2D6E66:    dc.b   0, $A,$74,$55,$92,$7A,$82,$48,$83,$58
                                        ; DATA XREF: ROM:off_129C   o
                dc.w sprite_24_32
                dc.w $7A64
                dc.w $9500 ! ((grp_10DD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10DD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10DD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7A84
                dc.w $9500 ! ((grp_179EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_179EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A64
                dc.w $9500 ! ((grp_86280 / 2) & $00FF)
                dc.w $9600 ! (((grp_86280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $824C
                dc.w $9500 ! ((grp_86300 / 2) & $00FF)
                dc.w $9600 ! (((grp_86300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A74
                dc.w $9500 ! ((grp_19A8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A8C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $926E
                dc.w $9500 ! ((grp_19A920 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7254
                dc.w $9500 ! ((grp_D6640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A44
                dc.w $9500 ! ((grp_D6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A8C
                dc.w $9500 ! ((grp_BCE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C9C
                dc.w $9500 ! ((grp_EE520 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $805C
                dc.w $9500 ! ((grp_EE540 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE540 / 2) >> 16)
                dc.w 1
