byte_2D1B1A:    dc.b   0,  3,$6E,$73,$90,$8F,$7C,$81,$7D,$81
                                        ; DATA XREF: ROM:off_E4C   o
                dc.w sprite_32_24
                dc.w $7879
                dc.w $9500 ! ((grp_1216C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1216C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1216C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6879
                dc.w $9500 ! ((grp_171400 / 2) & $00FF)
                dc.w $9600 ! (((grp_171400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171400 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6E71
                dc.w $9500 ! ((grp_97700 / 2) & $00FF)
                dc.w $9600 ! (((grp_97700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6080
                dc.w $9500 ! ((grp_E3CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3CA0 / 2) >> 16)
                dc.w 1
