byte_2D08F8:    dc.b   0,  1,$55,$52,$AC,$8E,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_DA0   o
                dc.w sprite_24_24
                dc.w $766F
                dc.w $9500 ! ((grp_13F960 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F960 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7387
                dc.w $9500 ! ((grp_184360 / 2) & $00FF)
                dc.w $9600 ! (((grp_184360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184360 / 2) >> 16)
                dc.w 3
