byte_2E783E:    dc.b   0,  8,$6F,$68,$8E,$8F,$B8,$93,$89,$60
                                        ; DATA XREF: ROM:off_1CFC   o
                dc.w sprite_16_32
                dc.w $745F
                dc.w $9500 ! ((grp_62800 / 2) & $00FF)
                dc.w $9600 ! (((grp_62800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8471
                dc.w $9500 ! ((grp_15EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7C79
                dc.w $9500 ! ((grp_176140 / 2) & $00FF)
                dc.w $9600 ! (((grp_176140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6C89
                dc.w $9500 ! ((grp_D0B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $845E
                dc.w $9500 ! ((grp_D0B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9C6B
                dc.w $9500 ! ((grp_D0B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C81
                dc.w $9500 ! ((grp_B8140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $945F
                dc.w $9500 ! ((grp_B8180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A771
                dc.w $9500 ! ((grp_B81C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B81C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B81C0 / 2) >> 16)
                dc.w 2
