byte_2CDC2A:    dc.b   0,  2,$89,$7B,$AE,$8E,$9B,$84,$9C,$84
                                        ; DATA XREF: ROM:off_994   o
                dc.w sprite_16_16
                dc.w $8581
                dc.w $9500 ! ((grp_74080 / 2) & $00FF)
                dc.w $9600 ! (((grp_74080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8C79
                dc.w $9500 ! ((grp_183580 / 2) & $00FF)
                dc.w $9600 ! (((grp_183580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183580 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $9983
                dc.w $9500 ! ((grp_1835E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1835E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1835E0 / 2) >> 16)
                dc.w 3
