byte_2DA7C2:    dc.b   0,  5,$6F,$63,$8E,$8F,$81,$75,$82,$6A
                                        ; DATA XREF: ROM:off_14B4   o
                dc.w sprite_32_24
                dc.w $756C
                dc.w $9500 ! ((grp_127E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_127E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $775C
                dc.w $9500 ! ((grp_7D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7484
                dc.w $9500 ! ((grp_187480 / 2) & $00FF)
                dc.w $9600 ! (((grp_187480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187480 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E8C
                dc.w $9500 ! ((grp_CF9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $848C
                dc.w $9500 ! ((grp_CFA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D70
                dc.w $9500 ! ((grp_B7080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7080 / 2) >> 16)
                dc.w 2
