byte_2FD778:    dc.b   0,  6,$5F,$4A,$8E,$8D,$84,$6B,$85,$6B
                                        ; DATA XREF: ROM:off_3308   o
                dc.w sprite_16_16
                dc.w $7A46
                dc.w $9500 ! ((grp_95A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_95A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E60
                dc.w $9500 ! ((grp_95B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_95B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8070
                dc.w $9500 ! ((grp_95B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_95B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A1700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F80
                dc.w $9500 ! ((grp_E0280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A56
                dc.w $9500 ! ((grp_C5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A49
                dc.w $9500 ! ((grp_F82C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F82C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F82C0 / 2) >> 16)
                dc.w 1
