byte_2F0B38:    dc.b   0,$12,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_2608   o
                dc.w sprite_32_32
                dc.w $5D63
                dc.w $9500 ! ((grp_35600 / 2) & $00FF)
                dc.w $9600 ! (((grp_35600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D7B
                dc.w $9500 ! ((grp_35400 / 2) & $00FF)
                dc.w $9600 ! (((grp_35400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $5D83
                dc.w $9500 ! ((grp_14D5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D5E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6553
                dc.w $9500 ! ((grp_54500 / 2) & $00FF)
                dc.w $9600 ! (((grp_54500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8A50
                dc.w $9500 ! ((grp_6B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $955B
                dc.w $9500 ! ((grp_17C740 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8570
                dc.w $9500 ! ((grp_8BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D4B
                dc.w $9500 ! ((grp_9E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9D7B
                dc.w $9500 ! ((grp_ABE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D63
                dc.w $9500 ! ((grp_DA540 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9573
                dc.w $9500 ! ((grp_DA580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D6B
                dc.w $9500 ! ((grp_BFE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8553
                dc.w $9500 ! ((grp_BFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D5B
                dc.w $9500 ! ((grp_F1720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1680 / 2) >> 16)
                dc.w 1
