byte_2DD74A:    dc.b   0,  8,$4F,$45,$A0,$91,$77,$6B,$70,$55
                                        ; DATA XREF: ROM:off_16DC   o
                dc.w sprite_24_32
                dc.w $735B
                dc.w $9500 ! ((grp_1051C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1051C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1051C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5344
                dc.w $9500 ! ((grp_128440 / 2) & $00FF)
                dc.w $9600 ! (((grp_128440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128440 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6F7B
                dc.w $9500 ! ((grp_1285C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1285C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1285C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7343
                dc.w $9500 ! ((grp_128740 / 2) & $00FF)
                dc.w $9600 ! (((grp_128740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $9343
                dc.w $9500 ! ((grp_7EE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7EE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7EE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B63
                dc.w $9500 ! ((grp_197500 / 2) & $00FF)
                dc.w $9600 ! (((grp_197500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197500 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B6F
                dc.w $9500 ! ((grp_B7BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4B4C
                dc.w $9500 ! ((grp_E9F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9353
                dc.w $9500 ! ((grp_E9F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9F60 / 2) >> 16)
                dc.w 1
