byte_2E8A3E:    dc.b   0,  5,$77,$66,$82,$8E,$7E,$78,$78,$6D
                                        ; DATA XREF: ROM:off_1DA4   o
                dc.w sprite_24_16
                dc.w $7580
                dc.w $9500 ! ((grp_159AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_159AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7560
                dc.w $9500 ! ((grp_196720 / 2) & $00FF)
                dc.w $9600 ! (((grp_196720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196720 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7590
                dc.w $9500 ! ((grp_E5AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7978
                dc.w $9500 ! ((grp_E5AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D60
                dc.w $9500 ! ((grp_E5AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D6B
                dc.w $9500 ! ((grp_E88A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E88A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E88A0 / 2) >> 16)
                dc.w 1
