byte_2E0F12:    dc.b   0, $D,$72,$5A,$8E,$8E,$76,$3E,$73,$28
                                        ; DATA XREF: ROM:off_191C   o
                dc.w sprite_24_16
                dc.w $7137
                dc.w $9500 ! ((grp_15BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5038
                dc.w $9500 ! ((grp_7B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6F27
                dc.w $9500 ! ((grp_7B180 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7F27
                dc.w $9500 ! ((grp_7AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8F24
                dc.w $9500 ! ((grp_7B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6556
                dc.w $9500 ! ((grp_185F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_185F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7747
                dc.w $9500 ! ((grp_185E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_185E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5F27
                dc.w $9500 ! ((grp_CD540 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $5F2F
                dc.w $9500 ! ((grp_CD580 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6139
                dc.w $9500 ! ((grp_CD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E4D
                dc.w $9500 ! ((grp_CD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $754F
                dc.w $9500 ! ((grp_E7B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C1F
                dc.w $9500 ! ((grp_E7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9645
                dc.w $9500 ! ((grp_E7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B00 / 2) >> 16)
                dc.w 1
