byte_2E8576:    dc.b   0,  7,$6F,$66,$8E,$8F,$A3,$58,$94,$65
                                        ; DATA XREF: ROM:off_1D74   o
                dc.w sprite_24_24
                dc.w $7C60
                dc.w $9500 ! ((grp_143AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_143AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143AA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7C78
                dc.w $9500 ! ((grp_7BF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7468
                dc.w $9500 ! ((grp_A5780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5C76
                dc.w $9500 ! ((grp_1868E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1868E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1868E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9456
                dc.w $9500 ! ((grp_196540 / 2) & $00FF)
                dc.w $9600 ! (((grp_196540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C88
                dc.w $9500 ! ((grp_CE340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CE380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C56
                dc.w $9500 ! ((grp_B6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6100 / 2) >> 16)
                dc.w 2
