byte_2D3C12:    dc.b   0,  5,$6A,$68,$8B,$82,$7A,$72,$7B,$72
                                        ; DATA XREF: ROM:off_106C   o
                dc.w sprite_32_24
                dc.w $6968
                dc.w $9500 ! ((grp_1225C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1225C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1225C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $895F
                dc.w $9500 ! ((grp_193C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_193C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193C60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7680
                dc.w $9500 ! ((grp_CA240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $616C
                dc.w $9500 ! ((grp_E4960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B80
                dc.w $9500 ! ((grp_E4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8160
                dc.w $9500 ! ((grp_E49A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E49A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E49A0 / 2) >> 16)
                dc.w 1
