byte_2DBDE4:    dc.b   0,  1,$6C,$70,$88,$88,$7A,$7C,$6F,$72
                                        ; DATA XREF: ROM:off_15D0   o
                dc.w sprite_32_24
                dc.w $6E79
                dc.w $9500 ! ((grp_124B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_124B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6E71
                dc.w $9500 ! ((grp_187720 / 2) & $00FF)
                dc.w $9600 ! (((grp_187720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187720 / 2) >> 16)
                dc.w 3
