byte_2E9224:    dc.b   0,  2,$6A,$47,$72,$8E,$71,$64,$6E,$54
                                        ; DATA XREF: ROM:off_1E28   o
                dc.w sprite_8_32
                dc.w $6F52
                dc.w $9500 ! ((grp_A6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6744
                dc.w $9500 ! ((grp_197380 / 2) & $00FF)
                dc.w $9600 ! (((grp_197380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7571
                dc.w $9500 ! ((grp_1973E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1973E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1973E0 / 2) >> 16)
                dc.w 3
