byte_2DD10E:    dc.b   0,  7,$6E,$64,$86,$80,$72,$6F,$70,$63
                                        ; DATA XREF: ROM:off_1694   o
                dc.w sprite_24_16
                dc.w $7176
                dc.w $9500 ! ((grp_15B380 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $745E
                dc.w $9500 ! ((grp_173A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_173A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $645E
                dc.w $9500 ! ((grp_7A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7156
                dc.w $9500 ! ((grp_CCF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C66
                dc.w $9500 ! ((grp_E7400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6980
                dc.w $9500 ! ((grp_E7440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C6E
                dc.w $9500 ! ((grp_E7420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7186
                dc.w $9500 ! ((grp_E7460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7460 / 2) >> 16)
                dc.w 1
