byte_2FD538:    dc.b   0,  6,$5F,$40,$8C,$8D,$7A,$66,$7B,$66
                                        ; DATA XREF: ROM:off_32F0   o
                dc.w sprite_16_32
                dc.w $7F60
                dc.w $9500 ! ((grp_70D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6645
                dc.w $9500 ! ((grp_95100 / 2) & $00FF)
                dc.w $9600 ! (((grp_95100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95100 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7388
                dc.w $9500 ! ((grp_A0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7150
                dc.w $9500 ! ((grp_DFCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7858
                dc.w $9500 ! ((grp_DFD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E80
                dc.w $9500 ! ((grp_DFD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $673D
                dc.w $9500 ! ((grp_F83C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F83C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F83C0 / 2) >> 16)
                dc.w 1
