byte_2E3AF6:    dc.b   0, $C,$68,$5C,$90,$7E,$CE,$47,$D0,$40
                                        ; DATA XREF: ROM:off_1AF4   o
                dc.w sprite_16_24
                dc.w $7D58
                dc.w $9500 ! ((grp_174700 / 2) & $00FF)
                dc.w $9600 ! (((grp_174700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6579
                dc.w $9500 ! ((grp_7BB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $C73D
                dc.w $9500 ! ((grp_7BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $755E
                dc.w $9500 ! ((grp_A5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5500 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9F50
                dc.w $9500 ! ((grp_186640 / 2) & $00FF)
                dc.w $9600 ! (((grp_186640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186640 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D78
                dc.w $9500 ! ((grp_CDD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9556
                dc.w $9500 ! ((grp_CDD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B74B
                dc.w $9500 ! ((grp_CDD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D69
                dc.w $9500 ! ((grp_B5E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $896A
                dc.w $9500 ! ((grp_B5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6571
                dc.w $9500 ! ((grp_E8420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D57
                dc.w $9500 ! ((grp_E8440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $925E
                dc.w $9500 ! ((grp_E8460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8460 / 2) >> 16)
                dc.w 1
