byte_2EE318:    dc.b   0,  7,$6A,$6A,$94,$93,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_2380   o
                dc.w sprite_32_32
                dc.w $726A
                dc.w $9500 ! ((grp_31A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_31A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $627C
                dc.w $9500 ! ((grp_89B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_89B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9276
                dc.w $9500 ! ((grp_89C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $768A
                dc.w $9500 ! ((grp_9DD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7462
                dc.w $9500 ! ((grp_18D240 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D240 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E91
                dc.w $9500 ! ((grp_D9340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A6C
                dc.w $9500 ! ((grp_BF3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B92
                dc.w $9500 ! ((grp_F07C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F07C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F07C0 / 2) >> 16)
                dc.w 1
