byte_2ED65C:    dc.b   0,  5,$6C,$62,$92,$95,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_22B8   o
                dc.w sprite_24_32
                dc.w $706B
                dc.w $9500 ! ((grp_111F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_111F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $886E
                dc.w $9500 ! ((grp_89300 / 2) & $00FF)
                dc.w $9600 ! (((grp_89300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $768B
                dc.w $9500 ! ((grp_D8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A63
                dc.w $9500 ! ((grp_D8BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $687E
                dc.w $9500 ! ((grp_BEDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9870
                dc.w $9500 ! ((grp_F02C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F02C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F02C0 / 2) >> 16)
                dc.w 1
