byte_2FF1BE:    dc.b   0,  1,$75,$76,$83,$94,$7C,$85,$7D,$85
                                        ; DATA XREF: ROM:off_3554   o
                dc.w sprite_24_32
                dc.w $6E6E
                dc.w $9500 ! ((grp_11D4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $7A8E
                dc.w $9500 ! ((grp_F9700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9700 / 2) >> 16)
                dc.w 1
