byte_2E706A:    dc.b   0,  5,$74,$53,$92,$78,$7D,$64,$86,$55
                                        ; DATA XREF: ROM:off_1CB4   o
                dc.w sprite_32_32
                dc.w $6D4F
                dc.w $9500 ! ((grp_1BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1BE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $626E
                dc.w $9500 ! ((grp_186C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_186C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186C40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D5A
                dc.w $9500 ! ((grp_1968A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1968A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1968A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6557
                dc.w $9500 ! ((grp_B6640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $856F
                dc.w $9500 ! ((grp_E8BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9566
                dc.w $9500 ! ((grp_E8BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8BE0 / 2) >> 16)
                dc.w 1
