byte_2E2510:    dc.b   0,  5,$5D,$64,$93,$8A,$78,$77,$79,$77
                                        ; DATA XREF: ROM:off_1A20   o
                dc.w sprite_32_32
                dc.w $665E
                dc.w $9500 ! ((grp_23A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_23A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $866A
                dc.w $9500 ! ((grp_64C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $667E
                dc.w $9500 ! ((grp_9AC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5B85
                dc.w $9500 ! ((grp_D32C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D32C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D32C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6F86
                dc.w $9500 ! ((grp_D3300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E75
                dc.w $9500 ! ((grp_B9E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9E00 / 2) >> 16)
                dc.w 2
