byte_2D15B8:    dc.b   0,  9,$63,$66,$9C,$8E,$82,$7A,$83,$7A
                                        ; DATA XREF: ROM:off_E18   o
                dc.w sprite_24_24
                dc.w $6B77
                dc.w $9500 ! ((grp_13F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F600 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6B67
                dc.w $9500 ! ((grp_1582C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1582C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1582C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8B75
                dc.w $9500 ! ((grp_1711C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1711C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1711C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8B65
                dc.w $9500 ! ((grp_76500 / 2) & $00FF)
                dc.w $9600 ! (((grp_76500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6369
                dc.w $9500 ! ((grp_A3B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8365
                dc.w $9500 ! ((grp_A3B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9B70
                dc.w $9500 ! ((grp_193240 / 2) & $00FF)
                dc.w $9600 ! (((grp_193240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193240 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D8F
                dc.w $9500 ! ((grp_C9480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B6D
                dc.w $9500 ! ((grp_B1E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A374
                dc.w $9500 ! ((grp_E3A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3A20 / 2) >> 16)
                dc.w 1
