byte_2FFAD6:    dc.b   0,  1,$7A,$70,$85,$96,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_35CC   o
                dc.w sprite_16_32
                dc.w $786E
                dc.w $9500 ! ((grp_72500 / 2) & $00FF)
                dc.w $9600 ! (((grp_72500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72500 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $7E8E
                dc.w $9500 ! ((grp_C6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6680 / 2) >> 16)
                dc.w     2
