byte_2DAE0A:    dc.b   0,  3,$67,$81,$8E,$8E,$7A,$87,$74,$8C
                                        ; DATA XREF: ROM:off_1514   o
                dc.w sprite_24_16
                dc.w $6D82
                dc.w $9500 ! ((grp_15DFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15DFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15DFC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $857D
                dc.w $9500 ! ((grp_7DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $657F
                dc.w $9500 ! ((grp_B7480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7A
                dc.w $9500 ! ((grp_E9A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9A60 / 2) >> 16)
                dc.w 1
