byte_2D4E7A:    dc.b   0,  8,$74,$60,$8A,$89,$82,$7A,$81,$6E
                                        ; DATA XREF: ROM:off_114C   o
                dc.w sprite_24_24
                dc.w $746F
                dc.w $9500 ! ((grp_140DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_140DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140DA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $8487
                dc.w $9500 ! ((grp_1850E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1850E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1850E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A8F
                dc.w $9500 ! ((grp_CB280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7387
                dc.w $9500 ! ((grp_CB2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A67
                dc.w $9500 ! ((grp_CB300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C7F
                dc.w $9500 ! ((grp_CB340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A5F
                dc.w $9500 ! ((grp_E5DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $888F
                dc.w $9500 ! ((grp_E5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C77
                dc.w $9500 ! ((grp_E5E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5E20 / 2) >> 16)
                dc.w 1
