byte_2D689A:    dc.b   0,  5,$74,$55,$92,$7A,$81,$51,$8A,$59
                                        ; DATA XREF: ROM:off_1264   o
                dc.w sprite_32_32
                dc.w $7250
                dc.w $9500 ! ((grp_26C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_26C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $9256
                dc.w $9500 ! ((grp_86000 / 2) & $00FF)
                dc.w $9600 ! (((grp_86000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A48
                dc.w $9500 ! ((grp_9BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5A64
                dc.w $9500 ! ((grp_18AE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AE40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A50
                dc.w $9500 ! ((grp_EE2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE2A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A6C
                dc.w $9500 ! ((grp_EE2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE2C0 / 2) >> 16)
                dc.w 1
