byte_2E3022:    dc.b   0,  4,$70,$64,$80,$6D,$7D,$7B,$7B,$75
                                        ; DATA XREF: ROM:off_1A7C   o
                dc.w sprite_32_24
                dc.w $6767
                dc.w $9500 ! ((grp_1282C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1282C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1282C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $737F
                dc.w $9500 ! ((grp_7E980 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6C8C
                dc.w $9500 ! ((grp_D05C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D05C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D05C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_D0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $876D
                dc.w $9500 ! ((grp_E9CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9CC0 / 2) >> 16)
                dc.w 1
