byte_2DE9DC:    dc.b   0,  7,$7A,$53,$A1,$8F,$8D,$71,$8E,$71
                                        ; DATA XREF: ROM:off_1798   o
                dc.w sprite_24_32
                dc.w $8768
                dc.w $9500 ! ((grp_108040 / 2) & $00FF)
                dc.w $9600 ! (((grp_108040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7E51
                dc.w $9500 ! ((grp_4DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7770
                dc.w $9500 ! ((grp_80B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8E60
                dc.w $9500 ! ((grp_D2540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9188
                dc.w $9500 ! ((grp_B9100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F68
                dc.w $9500 ! ((grp_EB340 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8688
                dc.w $9500 ! ((grp_EB360 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F7C
                dc.w $9500 ! ((grp_EB380 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB380 / 2) >> 16)
                dc.w 1
