byte_2FCEFC:    dc.b   0,  1,$82,$65,$96,$73,$8C,$6C,$8D,$6C
                                        ; DATA XREF: ROM:off_3260   o
                dc.w sprite_24_24
                dc.w $8063
                dc.w $9500 ! ((grp_1548A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1548A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1548A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $9863
                dc.w $9500 ! ((grp_C5940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5940 / 2) >> 16)
                dc.w 2
