byte_2DF3CA:    dc.b   0,  6,$72,$5E,$94,$8A,$7F,$76,$8D,$64
                                        ; DATA XREF: ROM:off_17FC   o
                dc.w sprite_32_24
                dc.w $7A64
                dc.w $9500 ! ((grp_125740 / 2) & $00FF)
                dc.w $9600 ! (((grp_125740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125740 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7A5C
                dc.w $9500 ! ((grp_185CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185CE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6881
                dc.w $9500 ! ((grp_CD300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7079
                dc.w $9500 ! ((grp_CD380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $867C
                dc.w $9500 ! ((grp_CD340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7266
                dc.w $9500 ! ((grp_B5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6689
                dc.w $9500 ! ((grp_E7900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7900 / 2) >> 16)
                dc.w 1
