byte_2D94F4:    dc.b   0, $A,$5A,$46,$93,$8C,$76,$69,$77,$69
                                        ; DATA XREF: ROM:off_1428   o
                dc.w sprite_24_32
                dc.w $705B
                dc.w $9500 ! ((grp_103CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_103CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6A7B
                dc.w $9500 ! ((grp_7CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8643
                dc.w $9500 ! ((grp_7CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5856
                dc.w $9500 ! ((grp_186D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_186D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $886C
                dc.w $9500 ! ((grp_196A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_196A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $584E
                dc.w $9500 ! ((grp_CEC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7056
                dc.w $9500 ! ((grp_CEC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8053
                dc.w $9500 ! ((grp_CF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $685E
                dc.w $9500 ! ((grp_E8D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718B
                dc.w $9500 ! ((grp_E8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $807B
                dc.w $9500 ! ((grp_E8FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8FC0 / 2) >> 16)
                dc.w 1
