byte_2CFB46:    dc.b   0,  2,$71,$7A,$8E,$89,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_C0C   o
                dc.w sprite_32_16
                dc.w $6F7C
                dc.w $9500 ! ((grp_46A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8474
                dc.w $9500 ! ((grp_E2F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F81
                dc.w $9500 ! ((grp_E2FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2FA0 / 2) >> 16)
                dc.w 1
