byte_2DF7B0:    dc.b   0,  6,$69,$65,$91,$8D,$7D,$79,$80,$72
                                        ; DATA XREF: ROM:off_1828   o
                dc.w sprite_24_32
                dc.w $6F68
                dc.w $9500 ! ((grp_108640 / 2) & $00FF)
                dc.w $9600 ! (((grp_108640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6F88
                dc.w $9500 ! ((grp_9A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8768
                dc.w $9500 ! ((grp_A6A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $676E
                dc.w $9500 ! ((grp_198460 / 2) & $00FF)
                dc.w $9600 ! (((grp_198460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198460 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F6E
                dc.w $9500 ! ((grp_B9440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7660
                dc.w $9500 ! ((grp_EB4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB4E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_EB500 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB500 / 2) >> 16)
                dc.w 1
