byte_2D7714:    dc.b   0,  7,$77,$65,$8F,$99,$84,$79,$7A,$64
                                        ; DATA XREF: ROM:off_12F8   o
                dc.w sprite_24_32
                dc.w $7767
                dc.w $9500 ! ((grp_FFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FFDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7A87
                dc.w $9500 ! ((grp_98480 / 2) & $00FF)
                dc.w $9600 ! (((grp_98480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8F7F
                dc.w $9500 ! ((grp_CC140 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F74
                dc.w $9500 ! ((grp_B3EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F5D
                dc.w $9500 ! ((grp_B3F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F63
                dc.w $9500 ! ((grp_B3F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $775F
                dc.w $9500 ! ((grp_E6640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $858F
                dc.w $9500 ! ((grp_E6620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6620 / 2) >> 16)
                dc.w 1
