byte_2D8330:    dc.b   0,  8,$72,$5D,$8C,$7E,$7B,$5E,$7A,$5F
                                        ; DATA XREF: ROM:off_1380   o
                dc.w sprite_24_24
                dc.w $705F
                dc.w $9500 ! ((grp_144700 / 2) & $00FF)
                dc.w $9600 ! (((grp_144700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144700 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7457
                dc.w $9500 ! ((grp_187240 / 2) & $00FF)
                dc.w $9600 ! (((grp_187240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187240 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $784F
                dc.w $9500 ! ((grp_1872A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1872A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1872A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C77
                dc.w $9500 ! ((grp_196D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_196D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8487
                dc.w $9500 ! ((grp_CF780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6861
                dc.w $9500 ! ((grp_B6EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $876F
                dc.w $9500 ! ((grp_B6F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7477
                dc.w $9500 ! ((grp_E93C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E93C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E93C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F74
                dc.w $9500 ! ((grp_E93E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E93E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E93E0 / 2) >> 16)
                dc.w 1
