byte_2D29FA:    dc.b   0,  4,$68,$82,$9B,$8F,$81,$83,$82,$83
                                        ; DATA XREF: ROM:off_F04   o
                dc.w sprite_32_16
                dc.w $6682
                dc.w $9500 ! ((grp_48900 / 2) & $00FF)
                dc.w $9600 ! (((grp_48900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8682
                dc.w $9500 ! ((grp_77200 / 2) & $00FF)
                dc.w $9600 ! (((grp_77200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6675
                dc.w $9500 ! ((grp_E4B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B7A
                dc.w $9500 ! ((grp_E4B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $968A
                dc.w $9500 ! ((grp_E4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4B80 / 2) >> 16)
                dc.w 1
