byte_2E20C6:    dc.b   0,  7,$77,$3B,$8A,$AC,$80,$73,$81,$73
                                        ; DATA XREF: ROM:off_19E4   o
                dc.w sprite_24_32
                dc.w $7581
                dc.w $9500 ! ((grp_1024C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1024C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1024C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7561
                dc.w $9500 ! ((grp_102640 / 2) & $00FF)
                dc.w $9600 ! (((grp_102640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7549
                dc.w $9500 ! ((grp_15C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7D59
                dc.w $9500 ! ((grp_CD7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7539
                dc.w $9500 ! ((grp_B55C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B55C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B55C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $85A1
                dc.w $9500 ! ((grp_B5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $75A1
                dc.w $9500 ! ((grp_E7D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8541
                dc.w $9500 ! ((grp_E7D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7D20 / 2) >> 16)
                dc.w 1
