byte_2FABBE:    dc.b   0,  9,$71,$63,$8E,$8F,$78,$73,$79,$73
                                        ; DATA XREF: ROM:off_2E3C   o
                dc.w sprite_24_32
                dc.w $7B72
                dc.w $9500 ! ((grp_11ADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11ADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11ADC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6361
                dc.w $9500 ! ((grp_153100 / 2) & $00FF)
                dc.w $9600 ! (((grp_153100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_153100 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7B5A
                dc.w $9500 ! ((grp_153220 / 2) & $00FF)
                dc.w $9600 ! (((grp_153220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_153220 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6379
                dc.w $9500 ! ((grp_16A740 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $5B6D
                dc.w $9500 ! ((grp_19F960 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6859
                dc.w $9500 ! ((grp_DEB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_DEAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E52
                dc.w $9500 ! ((grp_DEB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $936D
                dc.w $9500 ! ((grp_C4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5379
                dc.w $9500 ! ((grp_F6FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6FC0 / 2) >> 16)
                dc.w 1
