byte_2F2886:    dc.b   0, $A,$5B,$70,$A4,$93,$7E,$7E,$7F,$7E
                                        ; DATA XREF: ROM:off_273C   o
                dc.w sprite_32_24
                dc.w $757E
                dc.w $9500 ! ((grp_135DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_135DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $756E
                dc.w $9500 ! ((grp_54F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9572
                dc.w $9500 ! ((grp_6C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5D72
                dc.w $9500 ! ((grp_167140 / 2) & $00FF)
                dc.w $9600 ! (((grp_167140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167140 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $5D8A
                dc.w $9500 ! ((grp_167200 / 2) & $00FF)
                dc.w $9600 ! (((grp_167200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D76
                dc.w $9500 ! ((grp_8C880 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A57B
                dc.w $9500 ! ((grp_8C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8D6A
                dc.w $9500 ! ((grp_18E1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E1A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6582
                dc.w $9500 ! ((grp_DB540 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D62
                dc.w $9500 ! ((grp_DB580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5591
                dc.w $9500 ! ((grp_F2720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2720 / 2) >> 16)
                dc.w 1
