byte_2F8826:    dc.b   0, $C,$71,$3E,$90,$8A,$80,$64,$81,$64
                                        ; DATA XREF: ROM:off_2C94   o
                dc.w sprite_16_32
                dc.w $7E4C
                dc.w $9500 ! ((grp_6F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7F6C
                dc.w $9500 ! ((grp_6F300 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8E4C
                dc.w $9500 ! ((grp_AE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $763C
                dc.w $9500 ! ((grp_18F760 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F760 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7644
                dc.w $9500 ! ((grp_18F7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F7C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $764C
                dc.w $9500 ! ((grp_19F3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F3C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7777
                dc.w $9500 ! ((grp_19F420 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7F8C
                dc.w $9500 ! ((grp_DE000 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F7F
                dc.w $9500 ! ((grp_C3940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E7C
                dc.w $9500 ! ((grp_C3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E51
                dc.w $9500 ! ((grp_F6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E3C
                dc.w $9500 ! ((grp_F60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E6C
                dc.w $9500 ! ((grp_F60E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60E0 / 2) >> 16)
                dc.w 1
