byte_2F93B4:    dc.b   0,  4,$67,$72,$90,$94,$7B,$83,$7C,$83
                                        ; DATA XREF: ROM:off_2D30   o
                dc.w sprite_24_32
                dc.w $736F
                dc.w $9500 ! ((grp_11A640 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6A8F
                dc.w $9500 ! ((grp_18FE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FE80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6387
                dc.w $9500 ! ((grp_DE4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B75
                dc.w $9500 ! ((grp_C4000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B7F
                dc.w $9500 ! ((grp_F6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6700 / 2) >> 16)
                dc.w 1
