byte_2F7444:    dc.b   0, $C,$69,$34,$92,$83,$70,$7D,$71,$7D
                                        ; DATA XREF: ROM:off_2B90   o
                dc.w sprite_32_32
                dc.w $6232
                dc.w $9500 ! ((grp_3E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3E800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5E52
                dc.w $9500 ! ((grp_137BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_137BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $776A
                dc.w $9500 ! ((grp_6EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6EA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7E52
                dc.w $9500 ! ((grp_17F740 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8A3A
                dc.w $9500 ! ((grp_90080 / 2) & $00FF)
                dc.w $9600 ! (((grp_90080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9B32
                dc.w $9500 ! ((grp_90000 / 2) & $00FF)
                dc.w $9600 ! (((grp_90000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8232
                dc.w $9500 ! ((grp_ADB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6F72
                dc.w $9500 ! ((grp_C2E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8777
                dc.w $9500 ! ((grp_C2E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9B42
                dc.w $9500 ! ((grp_C2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A43
                dc.w $9500 ! ((grp_F56A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F56A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F56A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A4A
                dc.w $9500 ! ((grp_F56E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F56E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F56E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E61
                dc.w $9500 ! ((grp_F56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F56C0 / 2) >> 16)
                dc.w 1
