byte_2D4D04:    dc.b   0,  2,$5F,$7A,$8B,$8C,$75,$83,$76,$83
                                        ; DATA XREF: ROM:off_1138   o
                dc.w sprite_32_16
                dc.w $5E80
                dc.w $9500 ! ((grp_4DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7E7E
                dc.w $9500 ! ((grp_80880 / 2) & $00FF)
                dc.w $9600 ! (((grp_80880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5E78
                dc.w $9500 ! ((grp_9A280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A280 / 2) >> 16)
                dc.w 4
