byte_2E3988:    dc.b   0,  7,$70,$64,$9A,$93,$85,$7B,$86,$7B
                                        ; DATA XREF: ROM:off_1AE8   o
                dc.w sprite_24_24
                dc.w $7B68
                dc.w $9500 ! ((grp_1496E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1496E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1496E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6D86
                dc.w $9500 ! ((grp_86B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_86B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7D80
                dc.w $9500 ! ((grp_86C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D62
                dc.w $9500 ! ((grp_D6BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7477
                dc.w $9500 ! ((grp_BD440 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8060
                dc.w $9500 ! ((grp_EEA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEA40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D88
                dc.w $9500 ! ((grp_EEA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEA60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $936A
                dc.w $9500 ! ((grp_EEA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEA80 / 2) >> 16)
                dc.w 1
