byte_2F181C:    dc.b   0,  2,$77,$69,$87,$86,$7F,$77,$80,$77
                                        ; DATA XREF: ROM:off_2680   o
                dc.w sprite_16_24
                dc.w $7A67
                dc.w $9500 ! ((grp_17D940 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $777E
                dc.w $9500 ! ((grp_8CB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $726E
                dc.w $9500 ! ((grp_C0AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0AC0 / 2) >> 16)
                dc.w 2
