byte_2EF7E2:    dc.b   0,  1,$75,$2C,$83,$37,$7C,$31,$7D,$31
                                        ; DATA XREF: ROM:off_2524   o
                dc.w sprite_16_16
                dc.w $762A
                dc.w $9500 ! ((grp_8AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8AB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7128
                dc.w $9500 ! ((grp_BF900 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF900 / 2) >> 16)
                dc.w 2
