byte_2D469A:    dc.b   0, $C,$6A,$5E,$94,$98,$83,$7B,$7E,$6B
                                        ; DATA XREF: ROM:off_10EC   o
                dc.w sprite_16_24
                dc.w $7760
                dc.w $9500 ! ((grp_174D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_174D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7878
                dc.w $9500 ! ((grp_174DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_174DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $537C
                dc.w $9500 ! ((grp_7CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6874
                dc.w $9500 ! ((grp_7CD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9B6B
                dc.w $9500 ! ((grp_7CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A773
                dc.w $9500 ! ((grp_7CE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $887B
                dc.w $9500 ! ((grp_196C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_196C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8773
                dc.w $9500 ! ((grp_CF280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $628B
                dc.w $9500 ! ((grp_B6BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $997C
                dc.w $9500 ! ((grp_B6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4B84
                dc.w $9500 ! ((grp_E90A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E90A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E90A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718B
                dc.w $9500 ! ((grp_E90C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E90C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E90C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B58
                dc.w $9500 ! ((grp_E90E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E90E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E90E0 / 2) >> 16)
                dc.w 1
