byte_2D5BD6:    dc.b   0,  6,$77,$5E,$8F,$91,$7F,$7B,$84,$6C
                                        ; DATA XREF: ROM:off_11DC   o
                dc.w sprite_24_24
                dc.w $776D
                dc.w $9500 ! ((grp_141460 / 2) & $00FF)
                dc.w $9600 ! (((grp_141460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141460 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6A84
                dc.w $9500 ! ((grp_78900 / 2) & $00FF)
                dc.w $9600 ! (((grp_78900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E5D
                dc.w $9500 ! ((grp_78980 / 2) & $00FF)
                dc.w $9600 ! (((grp_78980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $838D
                dc.w $9500 ! ((grp_78A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8E65
                dc.w $9500 ! ((grp_194920 / 2) & $00FF)
                dc.w $9600 ! (((grp_194920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A85
                dc.w $9500 ! ((grp_CBD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $938E
                dc.w $9500 ! ((grp_E6300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6300 / 2) >> 16)
                dc.w 1
