byte_2F7F28:    dc.b   0,  3,$7B,$7C,$95,$A3,$88,$8F,$89,$8F
                                        ; DATA XREF: ROM:off_2BE8   o
                dc.w sprite_16_24
                dc.w $7B7C
                dc.w $9500 ! ((grp_17F8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8594
                dc.w $9500 ! ((grp_C30C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C30C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C30C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B7F
                dc.w $9500 ! ((grp_C3100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9387
                dc.w $9500 ! ((grp_F5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5980 / 2) >> 16)
                dc.w 1
