byte_2D376A:    dc.b   0,  4,$95,$64,$AC,$8D,$A0,$78,$A1,$78
                                        ; DATA XREF: ROM:off_102C   o
                dc.w sprite_24_32
                dc.w $9762
                dc.w $9500 ! ((grp_FD6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $9782
                dc.w $9500 ! ((grp_184BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9B8A
                dc.w $9500 ! ((grp_CA880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F66
                dc.w $9500 ! ((grp_E5000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F78
                dc.w $9500 ! ((grp_E5020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5020 / 2) >> 16)
                dc.w 1
