byte_2EAE5E:    dc.b   0,  5,$78,$63,$8C,$72,$80,$68,$81,$68
                                        ; DATA XREF: ROM:off_1FBC   o
                dc.w sprite_24_16
                dc.w $745E
                dc.w $9500 ! ((grp_163480 / 2) & $00FF)
                dc.w $9600 ! (((grp_163480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163480 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7B6E
                dc.w $9500 ! ((grp_18BCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BCE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F56
                dc.w $9500 ! ((grp_D7780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $736E
                dc.w $9500 ! ((grp_BDF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C5E
                dc.w $9500 ! ((grp_BDF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8976
                dc.w $9500 ! ((grp_EF240 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF240 / 2) >> 16)
                dc.w 1
