byte_2F19E0:    dc.b   0,  7,$77,$4E,$8D,$8F,$82,$71,$83,$71
                                        ; DATA XREF: ROM:off_26A0   o
                dc.w sprite_24_16
                dc.w $7D5C
                dc.w $9500 ! ((grp_166C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_166C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7552
                dc.w $9500 ! ((grp_19D680 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D680 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7884
                dc.w $9500 ! ((grp_C0440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D74
                dc.w $9500 ! ((grp_C0480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $708A
                dc.w $9500 ! ((grp_F2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D54
                dc.w $9500 ! ((grp_F2020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F6C
                dc.w $9500 ! ((grp_F2040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8574
                dc.w $9500 ! ((grp_F2060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2060 / 2) >> 16)
                dc.w 1
