byte_2FB7F0:    dc.b   0,  3,$79,$62,$84,$8D,$7E,$77,$7F,$77
                                        ; DATA XREF: ROM:off_2FA0   o
                dc.w sprite_16_16
                dc.w $7760
                dc.w $9500 ! ((grp_92880 / 2) & $00FF)
                dc.w $9600 ! (((grp_92880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7778
                dc.w $9500 ! ((grp_1A0020 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0020 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7F70
                dc.w $9500 ! ((grp_C4FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F88
                dc.w $9500 ! ((grp_F7C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7C60 / 2) >> 16)
                dc.w 1
