byte_2EA136:    dc.b   0,  3,$6B,$6C,$93,$88,$7F,$7A,$80,$7A
                                        ; DATA XREF: ROM:off_1F0C   o
                dc.w sprite_32_32
                dc.w $716A
                dc.w $9500 ! ((grp_27C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $9172
                dc.w $9500 ! ((grp_19AE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AE60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $697A
                dc.w $9500 ! ((grp_BD600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $798A
                dc.w $9500 ! ((grp_EEB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB40 / 2) >> 16)
                dc.w 1
