byte_2F1C14:    dc.b   0,  4,$77,$5B,$90,$8C,$83,$77,$84,$77
                                        ; DATA XREF: ROM:off_26B8   o
                dc.w sprite_24_16
                dc.w $7568
                dc.w $9500 ! ((grp_166D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_166D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7D80
                dc.w $9500 ! ((grp_8C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C60
                dc.w $9500 ! ((grp_DAF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F78
                dc.w $9500 ! ((grp_DAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D6F
                dc.w $9500 ! ((grp_C0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0500 / 2) >> 16)
                dc.w 2
