byte_2F5AA6:    dc.b   0,  5,$71,$54,$98,$8E,$84,$71,$85,$71
                                        ; DATA XREF: ROM:off_2B0C   o
                dc.w sprite_32_32
                dc.w $7762
                dc.w $9500 ! ((grp_3CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3CA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6F52
                dc.w $9500 ! ((grp_168C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_168C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7782
                dc.w $9500 ! ((grp_168D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_168D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168D00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6F62
                dc.w $9500 ! ((grp_C2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $976A
                dc.w $9500 ! ((grp_C20C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C20C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C20C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F82
                dc.w $9500 ! ((grp_F48A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F48A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F48A0 / 2) >> 16)
                dc.w 1
