byte_2EF286:    dc.b   0,  1,$76,$82,$89,$8F,$7F,$88,$80,$88
                                        ; DATA XREF: ROM:off_24B4   o
                dc.w sprite_24_16
                dc.w $7480
                dc.w $9500 ! ((grp_165F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_165F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7B90
                dc.w $9500 ! ((grp_F1440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1440 / 2) >> 16)
                dc.w 1
