byte_2F8EE2:    dc.b   0,  5,$6F,$71,$90,$85,$80,$6A,$81,$6A
                                        ; DATA XREF: ROM:off_2CE4   o
                dc.w sprite_32_24
                dc.w $6D6E
                dc.w $9500 ! ((grp_139240 / 2) & $00FF)
                dc.w $9600 ! (((grp_139240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $764E
                dc.w $9500 ! ((grp_90E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D72
                dc.w $9500 ! ((grp_90E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_90E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $785E
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A66
                dc.w $9500 ! ((grp_DE280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6571
                dc.w $9500 ! ((grp_C3DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3DC0 / 2) >> 16)
                dc.w 2
