byte_2FD24E:    dc.b   0,  3,$7A,$7B,$8F,$8D,$84,$84,$85,$84
                                        ; DATA XREF: ROM:off_32C4   o
                dc.w sprite_16_16
                dc.w $7878
                dc.w $9500 ! ((grp_95980 / 2) & $00FF)
                dc.w $9600 ! (((grp_95980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95980 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $887B
                dc.w $9500 ! ((grp_F8220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E81
                dc.w $9500 ! ((grp_F8240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8240 / 2) >> 16)
                dc.w 1
