byte_2E221C:    dc.b   0,  5,$77,$35,$8B,$B8,$81,$76,$82,$76
                                        ; DATA XREF: ROM:off_19F0   o
                dc.w sprite_8_16
                dc.w $85AB
                dc.w $9500 ! ((grp_B5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7435
                dc.w $9500 ! ((grp_E7DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7DA4
                dc.w $9500 ! ((grp_E7DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D43
                dc.w $9500 ! ((grp_E7DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D93
                dc.w $9500 ! ((grp_E7E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $868B
                dc.w $9500 ! ((grp_E7E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7E20 / 2) >> 16)
                dc.w 1
