byte_2DACD0:    dc.b   0,  7,$72,$75,$8E,$8F,$9E,$7F,$7C,$78
                                        ; DATA XREF: ROM:off_1500   o
                dc.w sprite_24_32
                dc.w $736F
                dc.w $9500 ! ((grp_1048C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1048C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1048C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8B7D
                dc.w $9500 ! ((grp_7D980 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7397
                dc.w $9500 ! ((grp_1876C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1876C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1876C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B9F
                dc.w $9500 ! ((grp_CFCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $768F
                dc.w $9500 ! ((grp_CFD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B7F
                dc.w $9500 ! ((grp_B7240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $829F
                dc.w $9500 ! ((grp_E98C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E98C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E98C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B7D
                dc.w $9500 ! ((grp_E98A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E98A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E98A0 / 2) >> 16)
                dc.w 1
