byte_2D0EF2:    dc.b   0,  9,$41,$62,$7B,$8F,$5D,$77,$5E,$77
                                        ; DATA XREF: ROM:off_DDC   o
                dc.w sprite_32_24
                dc.w $6078
                dc.w $9500 ! ((grp_120F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_120F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6160
                dc.w $9500 ! ((grp_13EE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_13EE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13EE20 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $2676
                dc.w $9500 ! ((grp_47600 / 2) & $00FF)
                dc.w $9600 ! (((grp_47600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $4170
                dc.w $9500 ! ((grp_47700 / 2) & $00FF)
                dc.w $9600 ! (((grp_47700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4960
                dc.w $9500 ! ((grp_157A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_157A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $815C
                dc.w $9500 ! ((grp_157B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_157B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $795D
                dc.w $9500 ! ((grp_192FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_192FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192FA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $2886
                dc.w $9500 ! ((grp_C90C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C90C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C90C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4168
                dc.w $9500 ! ((grp_E3760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4680
                dc.w $9500 ! ((grp_E3780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3780 / 2) >> 16)
                dc.w 1
