byte_2F79A4:    dc.b   0,$11,$64,$42,$9E,$83,$81,$61,$82,$61
                                        ; DATA XREF: ROM:off_2BB0   o
                dc.w sprite_32_32
                dc.w $6857
                dc.w $9500 ! ((grp_40200 / 2) & $00FF)
                dc.w $9600 ! (((grp_40200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $983F
                dc.w $9500 ! ((grp_1192C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1192C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1192C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $985F
                dc.w $9500 ! ((grp_137EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_137EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $884F
                dc.w $9500 ! ((grp_6ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6ED00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $B047
                dc.w $9500 ! ((grp_17FA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FA40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4076
                dc.w $9500 ! ((grp_90680 / 2) & $00FF)
                dc.w $9600 ! (((grp_90680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $886F
                dc.w $9500 ! ((grp_90600 / 2) & $00FF)
                dc.w $9600 ! (((grp_90600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6877
                dc.w $9500 ! ((grp_9F980 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5063
                dc.w $9500 ! ((grp_ADF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $584D
                dc.w $9500 ! ((grp_ADF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6067
                dc.w $9500 ! ((grp_AE000 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6047
                dc.w $9500 ! ((grp_AE080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $767F
                dc.w $9500 ! ((grp_18F580 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F580 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $9877
                dc.w $9500 ! ((grp_18F5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F5E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $586D
                dc.w $9500 ! ((grp_19F240 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F240 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $C05F
                dc.w $9500 ! ((grp_C3380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $387A
                dc.w $9500 ! ((grp_F5D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B867
                dc.w $9500 ! ((grp_F5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5D80 / 2) >> 16)
                dc.w 1
