byte_2D4AE0:    dc.b   0,  6,$38,$71,$73,$93,$55,$82,$56,$82
                                        ; DATA XREF: ROM:off_1118   o
                dc.w sprite_32_8
                dc.w $4186
                dc.w $9500 ! ((grp_99880 / 2) & $00FF)
                dc.w $9600 ! (((grp_99880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $3E8E
                dc.w $9500 ! ((grp_187DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_187DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187DE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $4D7E
                dc.w $9500 ! ((grp_187E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_187E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $5476
                dc.w $9500 ! ((grp_187EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_187EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187EA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $606E
                dc.w $9500 ! ((grp_187F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_187F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $368E
                dc.w $9500 ! ((grp_E9EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $3986
                dc.w $9500 ! ((grp_E9EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9EC0 / 2) >> 16)
                dc.w 1
