byte_2ED182:    dc.b   0,  1,$6C,$7F,$96,$8E,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_2264   o
                dc.w sprite_24_16
                dc.w $757D
                dc.w $9500 ! ((grp_164440 / 2) & $00FF)
                dc.w $9600 ! (((grp_164440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $758D
                dc.w $9500 ! ((grp_D85C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D85C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D85C0 / 2) >> 16)
                dc.w 2
