byte_2DD9E0:    dc.b   0, $C,$50,$49,$9E,$92,$77,$6D,$5C,$4B
                                        ; DATA XREF: ROM:off_16F0   o
                dc.w sprite_32_24
                dc.w $727D
                dc.w $9500 ! ((grp_1288C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1288C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1288C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7E47
                dc.w $9500 ! ((grp_4CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6647
                dc.w $9500 ! ((grp_15E980 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $726D
                dc.w $9500 ! ((grp_15E8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6A6C
                dc.w $9500 ! ((grp_A6280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $625F
                dc.w $9500 ! ((grp_1975C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1975C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1975C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5648
                dc.w $9500 ! ((grp_D09C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D09C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D09C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4E48
                dc.w $9500 ! ((grp_B7DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5250
                dc.w $9500 ! ((grp_B7D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5A55
                dc.w $9500 ! ((grp_B7D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A64
                dc.w $9500 ! ((grp_EA0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA0E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9283
                dc.w $9500 ! ((grp_EA100 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E4D
                dc.w $9500 ! ((grp_EA0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA0C0 / 2) >> 16)
                dc.w 1
