byte_2EB7F8:    dc.b   0,  3,$78,$3D,$87,$95,$7F,$4C,$80,$8B
                                        ; DATA XREF: ROM:off_2050   o
                dc.w sprite_24_32
                dc.w $7543
                dc.w $9500 ! ((grp_1102C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1102C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1102C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7A63
                dc.w $9500 ! ((grp_67E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7A83
                dc.w $9500 ! ((grp_87700 / 2) & $00FF)
                dc.w $9600 ! (((grp_87700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7263
                dc.w $9500 ! ((grp_19BC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BC40 / 2) >> 16)
                dc.w 3
