byte_2D88C0:    dc.b   0,  6,$6F,$5A,$8E,$90,$7A,$73,$65,$63
                                        ; DATA XREF: ROM:off_13B8   o
                dc.w sprite_32_32
                dc.w $6067
                dc.w $9500 ! ((grp_25600 / 2) & $00FF)
                dc.w $9600 ! (((grp_25600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $806F
                dc.w $9500 ! ((grp_84480 / 2) & $00FF)
                dc.w $9600 ! (((grp_84480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5D5F
                dc.w $9500 ! ((grp_D4A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7887
                dc.w $9500 ! ((grp_D4A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6057
                dc.w $9500 ! ((grp_ED160 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $867F
                dc.w $9500 ! ((grp_ED1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED1A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9076
                dc.w $9500 ! ((grp_ED180 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED180 / 2) >> 16)
                dc.w 1
