byte_2D587C:    dc.b   0,  6,$6E,$63,$8E,$8F,$7E,$74,$74,$68
                                        ; DATA XREF: ROM:off_11B8   o
                dc.w sprite_24_32
                dc.w $6F61
                dc.w $9500 ! ((grp_104140 / 2) & $00FF)
                dc.w $9600 ! (((grp_104140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7381
                dc.w $9500 ! ((grp_187120 / 2) & $00FF)
                dc.w $9600 ! (((grp_187120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187120 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6764
                dc.w $9500 ! ((grp_196CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_196CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196CC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A89
                dc.w $9500 ! ((grp_CF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7959
                dc.w $9500 ! ((grp_CF500 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CF540 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8761
                dc.w $9500 ! ((grp_E91E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E91E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E91E0 / 2) >> 16)
                dc.w 1
