byte_2EC41C:    dc.b   0,  1,$75,$76,$8B,$8D,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_20E0   o
                dc.w sprite_24_32
                dc.w $7374
                dc.w $9500 ! ((grp_111640 / 2) & $00FF)
                dc.w $9600 ! (((grp_111640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111640 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $8B7B
                dc.w $9500 ! ((grp_BE4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE4C0 / 2) >> 16)
                dc.w 2
