byte_2E3FDE:    dc.b   0, $D,$6F,$6E,$94,$87,$49,$47,$42,$45
                                        ; DATA XREF: ROM:off_1B14   o
                dc.w sprite_24_32
                dc.w $7967
                dc.w $9500 ! ((grp_102F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_102F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $596F
                dc.w $9500 ! ((grp_186460 / 2) & $00FF)
                dc.w $9600 ! (((grp_186460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186460 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $716E
                dc.w $9500 ! ((grp_195F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_195F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195F40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5B67
                dc.w $9500 ! ((grp_CDBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C87
                dc.w $9500 ! ((grp_CDB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9168
                dc.w $9500 ! ((grp_CDC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $3F40
                dc.w $9500 ! ((grp_B5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4743
                dc.w $9500 ! ((grp_B5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4E51
                dc.w $9500 ! ((grp_B5CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9170
                dc.w $9500 ! ((grp_B5C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A160
                dc.w $9500 ! ((grp_B5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5359
                dc.w $9500 ! ((grp_E82C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E82C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E82C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $595F
                dc.w $9500 ! ((grp_E82A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E82A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E82A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6977
                dc.w $9500 ! ((grp_E82E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E82E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E82E0 / 2) >> 16)
                dc.w 1
