byte_2EC886:    dc.b   0,  3,$79,$6A,$8D,$86,$79,$70,$7A,$70
                                        ; DATA XREF: ROM:off_216C   o
                dc.w sprite_16_24
                dc.w $7E6F
                dc.w $9500 ! ((grp_17B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B300 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7761
                dc.w $9500 ! ((grp_19C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C300 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $665B
                dc.w $9500 ! ((grp_D8540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F63
                dc.w $9500 ! ((grp_EFE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFE40 / 2) >> 16)
                dc.w 1
