byte_2E08A8:    dc.b   0,  4,$6B,$5B,$94,$84,$7F,$6F,$92,$60
                                        ; DATA XREF: ROM:off_18E8   o
                dc.w sprite_32_32
                dc.w $7759
                dc.w $9500 ! ((grp_22A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_22A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7779
                dc.w $9500 ! ((grp_4E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6766
                dc.w $9500 ! ((grp_A7680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6F61
                dc.w $9500 ! ((grp_A7700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6F81
                dc.w $9500 ! ((grp_EBC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBC60 / 2) >> 16)
                dc.w 1
