byte_2CDF66:    dc.b   0,  6,$66,$58,$93,$7F,$7C,$6B,$7D,$6B
                                        ; DATA XREF: ROM:off_9DC   o
                dc.w sprite_16_32
                dc.w $835F
                dc.w $9500 ! ((grp_5BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5BF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $736A
                dc.w $9500 ! ((grp_16FE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FE40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7356
                dc.w $9500 ! ((grp_74280 / 2) & $00FF)
                dc.w $9600 ! (((grp_74280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $635F
                dc.w $9500 ! ((grp_C8240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8357
                dc.w $9500 ! ((grp_C8280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B77
                dc.w $9500 ! ((grp_E2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9365
                dc.w $9500 ! ((grp_E2420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2420 / 2) >> 16)
                dc.w 1
