byte_2E19DC:    dc.b   0,  6,$78,$5F,$93,$8D,$83,$76,$81,$5F
                                        ; DATA XREF: ROM:off_1978   o
                dc.w sprite_32_24
                dc.w $6E71
                dc.w $9500 ! ((grp_12BD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12BD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12BD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $786A
                dc.w $9500 ! ((grp_9AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7262
                dc.w $9500 ! ((grp_189400 / 2) & $00FF)
                dc.w $9600 ! (((grp_189400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189400 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7489
                dc.w $9500 ! ((grp_189340 / 2) & $00FF)
                dc.w $9600 ! (((grp_189340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $755A
                dc.w $9500 ! ((grp_D2F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A62
                dc.w $9500 ! ((grp_D2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E72
                dc.w $9500 ! ((grp_B9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9B80 / 2) >> 16)
                dc.w 2
