byte_2EE0DA:    dc.b   0,  1,$72,$88,$8C,$8F,$7F,$8B,$80,$8B
                                        ; DATA XREF: ROM:off_2364   o
                dc.w sprite_32_8
                dc.w $7088
                dc.w $9500 ! ((grp_9DC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8880
                dc.w $9500 ! ((grp_F06A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F06A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F06A0 / 2) >> 16)
                dc.w 1
