byte_2CC5D4:    dc.b   0,  2,$75,$78,$8A,$8D,$7F,$82,$80,$82
                                        ; DATA XREF: ROM:off_790   o
                dc.w sprite_24_24
                dc.w $7576
                dc.w $9500 ! ((grp_13DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_13DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13DB00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $798E
                dc.w $9500 ! ((grp_C6BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D7D
                dc.w $9500 ! ((grp_AFF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFF00 / 2) >> 16)
                dc.w 2
