byte_2CCED8:    dc.b   0,  2,$6E,$74,$8C,$8D,$7D,$80,$7E,$80
                                        ; DATA XREF: ROM:off_848   o
                dc.w sprite_24_32
                dc.w $7272
                dc.w $9500 ! ((grp_FA240 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA240 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $6A7B
                dc.w $9500 ! ((grp_B0940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A77
                dc.w $9500 ! ((grp_B0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0980 / 2) >> 16)
                dc.w 2
