byte_2F4F98:    dc.b   0,  9,$71,$60,$A1,$87,$87,$6E,$88,$6E
                                        ; DATA XREF: ROM:off_2A30   o
                dc.w sprite_24_32
                dc.w $806F
                dc.w $9500 ! ((grp_116740 / 2) & $00FF)
                dc.w $9600 ! (((grp_116740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7E4F
                dc.w $9500 ! ((grp_6DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $686A
                dc.w $9500 ! ((grp_8E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $786A
                dc.w $9500 ! ((grp_ACF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9871
                dc.w $9500 ! ((grp_19E6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E6A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A068
                dc.w $9500 ! ((grp_19E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E700 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9251
                dc.w $9500 ! ((grp_C1B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6071
                dc.w $9500 ! ((grp_F43A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F43A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F43A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7662
                dc.w $9500 ! ((grp_F4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9C59
                dc.w $9500 ! ((grp_F43C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F43C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F43C0 / 2) >> 16)
                dc.w 1
