byte_2FE8CE:    dc.b   0,  2,$62,$89,$9A,$90,$7E,$88,$7F,$88
                                        ; DATA XREF: ROM:off_3444   o
                dc.w sprite_32_16
                dc.w $5D87
                dc.w $9500 ! ((grp_5A100 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A100 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7D87
                dc.w $9500 ! ((grp_5A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A200 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $847F
                dc.w $9500 ! ((grp_F8DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8DA0 / 2) >> 16)
                dc.w 1
