byte_2DFFDA:    dc.b   0,  5,$6A,$62,$94,$8E,$7F,$78,$7F,$6D
                                        ; DATA XREF: ROM:off_1884   o
                dc.w sprite_32_32
                dc.w $6868
                dc.w $9500 ! ((grp_20600 / 2) & $00FF)
                dc.w $9600 ! (((grp_20600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8870
                dc.w $9500 ! ((grp_63300 / 2) & $00FF)
                dc.w $9600 ! (((grp_63300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6888
                dc.w $9500 ! ((grp_9A780 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6860
                dc.w $9500 ! ((grp_189040 / 2) & $00FF)
                dc.w $9600 ! (((grp_189040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189040 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D90
                dc.w $9500 ! ((grp_D2AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8090
                dc.w $9500 ! ((grp_D2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2B00 / 2) >> 16)
                dc.w 2
