byte_2D5938:    dc.b   0,  8,$6E,$67,$8E,$8F,$76,$72,$70,$6F
                                        ; DATA XREF: ROM:off_11C0   o
                dc.w sprite_24_32
                dc.w $6870
                dc.w $9500 ! ((grp_FF040 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5563
                dc.w $9500 ! ((grp_78680 / 2) & $00FF)
                dc.w $9600 ! (((grp_78680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6560
                dc.w $9500 ! ((grp_78700 / 2) & $00FF)
                dc.w $9600 ! (((grp_78700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8081
                dc.w $9500 ! ((grp_CBBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CBC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B5B
                dc.w $9500 ! ((grp_E61E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E61E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E61E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6558
                dc.w $9500 ! ((grp_E6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7568
                dc.w $9500 ! ((grp_E6220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7757
                dc.w $9500 ! ((grp_E6240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6240 / 2) >> 16)
                dc.w 1
