byte_2CC834:    dc.b   0,  2,$5C,$7A,$8C,$96,$74,$88,$75,$88
                                        ; DATA XREF: ROM:off_7C8   o
                dc.w sprite_32_24
                dc.w $7078
                dc.w $9500 ! ((grp_11E3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E3C0 / 2) >> 16)
                dc.w    $C
                dc.w sprite_24_8
                dc.w $6E90
                dc.w $9500 ! ((grp_183040 / 2) & $00FF)
                dc.w $9600 ! (((grp_183040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183040 / 2) >> 16)
                dc.w     3
                dc.w sprite_16_8
                dc.w $5E89
                dc.w $9500 ! ((grp_C6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6C80 / 2) >> 16)
                dc.w     2
