byte_2DA84E:    dc.b   0,  4,$6F,$72,$8E,$8F,$8A,$7F,$96,$77
                                        ; DATA XREF: ROM:off_14BC   o
                dc.w sprite_32_32
                dc.w $7470
                dc.w $9500 ! ((grp_1D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1D000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $9470
                dc.w $9500 ! ((grp_175300 / 2) & $00FF)
                dc.w $9600 ! (((grp_175300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175300 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $A474
                dc.w $9500 ! ((grp_B7100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C7D
                dc.w $9500 ! ((grp_E9600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C88
                dc.w $9500 ! ((grp_E9620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9620 / 2) >> 16)
                dc.w 1
