byte_2CD75E:    dc.b   0,  2,$67,$53,$7F,$68,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_90C   o
                dc.w sprite_32_32
                dc.w $634F
                dc.w $9500 ! ((grp_10600 / 2) & $00FF)
                dc.w $9600 ! (((grp_10600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_8
                dc.w $7B6F
                dc.w $9500 ! ((grp_C7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8367
                dc.w $9500 ! ((grp_E1DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1DC0 / 2) >> 16)
                dc.w 1
