byte_2FDC1C:    dc.b   0,  6,$67,$5E,$94,$8D,$7D,$75,$7E,$75
                                        ; DATA XREF: ROM:off_3338   o
                dc.w sprite_32_24
                dc.w $6760
                dc.w $9500 ! ((grp_13B4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $875D
                dc.w $9500 ! ((grp_182200 / 2) & $00FF)
                dc.w $9600 ! (((grp_182200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6F78
                dc.w $9500 ! ((grp_95700 / 2) & $00FF)
                dc.w $9600 ! (((grp_95700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7258
                dc.w $9500 ! ((grp_191380 / 2) & $00FF)
                dc.w $9600 ! (((grp_191380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191380 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7288
                dc.w $9500 ! ((grp_191320 / 2) & $00FF)
                dc.w $9600 ! (((grp_191320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191320 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5F63
                dc.w $9500 ! ((grp_F8620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6778
                dc.w $9500 ! ((grp_F8640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8640 / 2) >> 16)
                dc.w 1
