byte_2CF8F8:    dc.b   0,  1,$76,$76,$88,$86,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_BB0   o
                dc.w sprite_16_24
                dc.w $7C74
                dc.w $9500 ! ((grp_170680 / 2) & $00FF)
                dc.w $9600 ! (((grp_170680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170680 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7484
                dc.w $9500 ! ((grp_E2E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2E40 / 2) >> 16)
                dc.w 1
