byte_2F4668:    dc.b   0,  1,$7B,$75,$87,$8B,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_29A0   o
                dc.w sprite_16_32
                dc.w $7973
                dc.w $9500 ! ((grp_6D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D700 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $897B
                dc.w $9500 ! ((grp_F3A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3A40 / 2) >> 16)
                dc.w 1
