byte_2ED5F4:    dc.b   0,  1,$77,$64,$89,$93,$7F,$7A,$80,$7A
                                        ; DATA XREF: ROM:off_22B0   o
                dc.w sprite_24_32
                dc.w $7462
                dc.w $9500 ! ((grp_111DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_111DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7982
                dc.w $9500 ! ((grp_89200 / 2) & $00FF)
                dc.w $9600 ! (((grp_89200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89200 / 2) >> 16)
                dc.w 4
