byte_2F21F8:    dc.b   0,$15,$56,$62,$B1,$99,$7E,$76,$7F,$76
                                        ; DATA XREF: ROM:off_26F0   o
                dc.w sprite_24_32
                dc.w $7E72
                dc.w $9500 ! ((grp_1138C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1138C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1138C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $A660
                dc.w $9500 ! ((grp_6BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $4E57
                dc.w $9500 ! ((grp_17CF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CF80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6E86
                dc.w $9500 ! ((grp_17D040 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D040 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6E6E
                dc.w $9500 ! ((grp_17D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $865A
                dc.w $9500 ! ((grp_17D1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $666D
                dc.w $9500 ! ((grp_AC100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $966A
                dc.w $9500 ! ((grp_AC180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9E72
                dc.w $9500 ! ((grp_AC200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $4652
                dc.w $9500 ! ((grp_19D5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D5C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7F52
                dc.w $9500 ! ((grp_DAD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8692
                dc.w $9500 ! ((grp_DAD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E66
                dc.w $9500 ! ((grp_C0400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $965A
                dc.w $9500 ! ((grp_C0340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E62
                dc.w $9500 ! ((grp_C0380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B666
                dc.w $9500 ! ((grp_C03C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C03C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C03C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3E52
                dc.w $9500 ! ((grp_F1E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $3E62
                dc.w $9500 ! ((grp_F1E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E59
                dc.w $9500 ! ((grp_F1E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $745E
                dc.w $9500 ! ((grp_F1E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6A
                dc.w $9500 ! ((grp_F1E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A680
                dc.w $9500 ! ((grp_F1EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1EA0 / 2) >> 16)
                dc.w 1
