byte_2F8D02:    dc.b   0,  5,$6F,$71,$90,$85,$80,$6B,$81,$6B
                                        ; DATA XREF: ROM:off_2CCC   o
                dc.w sprite_32_24
                dc.w $706D
                dc.w $9500 ! ((grp_138C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_138C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_138C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $6E67
                dc.w $9500 ! ((grp_DE200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE200 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $735F
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $686F
                dc.w $9500 ! ((grp_C3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $906E
                dc.w $9500 ! ((grp_C3AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7757
                dc.w $9500 ! ((grp_F63E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63E0 / 2) >> 16)
                dc.w 1
