byte_2CD976:    dc.b   0,  1,$85,$87,$93,$8C,$84,$8E,$83,$A1
                                        ; DATA XREF: ROM:off_944   o
                dc.w sprite_24_8
                dc.w $8187
                dc.w $9500 ! ((grp_1834C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1834C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1834C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8E7F
                dc.w $9500 ! ((grp_E1E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1E80 / 2) >> 16)
                dc.w 1
