byte_2F5A02:    dc.b   0,  5,$70,$54,$98,$8E,$84,$71,$85,$71
                                        ; DATA XREF: ROM:off_2B04   o
                dc.w sprite_32_32
                dc.w $7662
                dc.w $9500 ! ((grp_3C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6E52
                dc.w $9500 ! ((grp_168940 / 2) & $00FF)
                dc.w $9600 ! (((grp_168940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168940 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7682
                dc.w $9500 ! ((grp_168A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_168A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6E62
                dc.w $9500 ! ((grp_C1F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $966C
                dc.w $9500 ! ((grp_C1FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E82
                dc.w $9500 ! ((grp_F4860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4860 / 2) >> 16)
                dc.w 1
