byte_2D12F6:    dc.b   0,  5,$6C,$66,$9C,$8F,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_DFC   o
                dc.w sprite_24_32
                dc.w $6A72
                dc.w $9500 ! ((grp_FBBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FBBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FBBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $8262
                dc.w $9500 ! ((grp_FBD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FBD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FBD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $8282
                dc.w $9500 ! ((grp_157F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_157F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $626A
                dc.w $9500 ! ((grp_97680 / 2) & $00FF)
                dc.w $9600 ! (((grp_97680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6262
                dc.w $9500 ! ((grp_C9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A86
                dc.w $9500 ! ((grp_E3940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3940 / 2) >> 16)
                dc.w 1
