byte_2F967E:    dc.b   0,  1,$73,$5B,$8A,$68,$7E,$61,$7F,$61
                                        ; DATA XREF: ROM:off_2D6C   o
                dc.w sprite_32_8
                dc.w $7159
                dc.w $9500 ! ((grp_9FF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8169
                dc.w $9500 ! ((grp_F6940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6940 / 2) >> 16)
                dc.w 1
