byte_2FF936:    dc.b   0,  2,$71,$5E,$8C,$89,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_35AC   o
                dc.w sprite_32_32
                dc.w $6F5C
                dc.w $9500 ! ((grp_45C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_45C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_45C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $777C
                dc.w $9500 ! ((grp_16E340 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E340 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6F84
                dc.w $9500 ! ((grp_F9560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9560 / 2) >> 16)
                dc.w 1
