byte_2DD60C:    dc.b   0,  7,$80,$5B,$94,$98,$8B,$90,$84,$68
                                        ; DATA XREF: ROM:off_16D0   o
                dc.w sprite_16_32
                dc.w $8854
                dc.w $9500 ! ((grp_60500 / 2) & $00FF)
                dc.w $9600 ! (((grp_60500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $888C
                dc.w $9500 ! ((grp_15B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8774
                dc.w $9500 ! ((grp_173BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_173BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7866
                dc.w $9500 ! ((grp_B4E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F74
                dc.w $9500 ! ((grp_B4E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8054
                dc.w $9500 ! ((grp_B4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8064
                dc.w $9500 ! ((grp_B4EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D9C
                dc.w $9500 ! ((grp_E7680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7680 / 2) >> 16)
                dc.w 1
