byte_2E1FBA:    dc.b   0,  3,$76,$5D,$8C,$87,$81,$72,$82,$72
                                        ; DATA XREF: ROM:off_19D4   o
                dc.w sprite_32_24
                dc.w $7462
                dc.w $9500 ! ((grp_1261C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1261C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1261C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $747A
                dc.w $9500 ! ((grp_4A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $745A
                dc.w $9500 ! ((grp_E7C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $875A
                dc.w $9500 ! ((grp_E7C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7C40 / 2) >> 16)
                dc.w 1
