byte_2F68BE:    dc.b   0,$11,$6B,$54,$A0,$8D,$70,$83,$71,$83
                                        ; DATA XREF: ROM:off_2B5C   o
                dc.w sprite_32_32
                dc.w $7D59
                dc.w $9500 ! ((grp_3DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7579
                dc.w $9500 ! ((grp_137740 / 2) & $00FF)
                dc.w $9600 ! (((grp_137740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137740 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4D7F
                dc.w $9500 ! ((grp_56700 / 2) & $00FF)
                dc.w $9600 ! (((grp_56700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $655F
                dc.w $9500 ! ((grp_6E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $A562
                dc.w $9500 ! ((grp_17F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $3667
                dc.w $9500 ! ((grp_8F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $3D7B
                dc.w $9500 ! ((grp_8F780 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8251
                dc.w $9500 ! ((grp_18EE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EE60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7561
                dc.w $9500 ! ((grp_19EAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EAC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9D57
                dc.w $9500 ! ((grp_19EB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EB20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9D71
                dc.w $9500 ! ((grp_19ED60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ED60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ED60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $2D77
                dc.w $9500 ! ((grp_DD1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $2E5E
                dc.w $9500 ! ((grp_DD200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7551
                dc.w $9500 ! ((grp_C23C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C23C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C23C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9579
                dc.w $9500 ! ((grp_C2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D67
                dc.w $9500 ! ((grp_F4B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D88
                dc.w $9500 ! ((grp_F52C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F52C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F52C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8449
                dc.w $9500 ! ((grp_F4B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B60 / 2) >> 16)
                dc.w 1
