byte_2EC058:    dc.b   0,  4,$70,$5A,$97,$8C,$83,$73,$84,$73
                                        ; DATA XREF: ROM:000020A0   o
                dc.w sprite_32_32
                dc.w $7970
                dc.w $9500 ! ((grp_2F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2F000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7960
                dc.w $9500 ! ((grp_51800 / 2) & $00FF)
                dc.w $9600 ! (((grp_51800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $716B
                dc.w $9500 ! ((grp_AA980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $697C
                dc.w $9500 ! ((grp_EF880 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8658
                dc.w $9500 ! ((grp_EF8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF8A0 / 2) >> 16)
                dc.w 1
