byte_2EDD8A:    dc.b   0,  2,$76,$82,$89,$91,$7F,$89,$80,$89
                                        ; DATA XREF: ROM:off_2314   o
                dc.w sprite_16_24
                dc.w $7A7E
                dc.w $9500 ! ((grp_17BA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BA80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7288
                dc.w $9500 ! ((grp_F0480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A80
                dc.w $9500 ! ((grp_F04A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F04A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F04A0 / 2) >> 16)
                dc.w 1
