byte_2D3948:    dc.b   0,  5,$85,$5E,$9F,$82,$8E,$70,$8F,$70
                                        ; DATA XREF: ROM:off_1048   o
                dc.w sprite_16_32
                dc.w $8B64
                dc.w $9500 ! ((grp_5E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $9B64
                dc.w $9500 ! ((grp_193BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B61
                dc.w $9500 ! ((grp_C9FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B5C
                dc.w $9500 ! ((grp_CA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8375
                dc.w $9500 ! ((grp_B2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B7D
                dc.w $9500 ! ((grp_E45E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E45E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E45E0 / 2) >> 16)
                dc.w 1
