byte_2FF184:    dc.b   0,  3,$76,$82,$8F,$91,$83,$89,$84,$89
                                        ; DATA XREF: ROM:off_3550   o
                dc.w sprite_24_24
                dc.w $6C78
                dc.w $9500 ! ((grp_155980 / 2) & $00FF)
                dc.w $9600 ! (((grp_155980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155980 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $8488
                dc.w $9500 ! ((grp_E0F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7370
                dc.w $9500 ! ((grp_F96E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F96E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F96E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8880
                dc.w $9500 ! ((grp_F96C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F96C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F96C0 / 2) >> 16)
                dc.w 1
