byte_2D81BA:    dc.b   0,  6,$70,$5C,$84,$7E,$84,$60,$82,$63
                                        ; DATA XREF: ROM:off_136C   o
                dc.w sprite_24_32
                dc.w $715D
                dc.w $9500 ! ((grp_100540 / 2) & $00FF)
                dc.w $9600 ! (((grp_100540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100540 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $695E
                dc.w $9500 ! ((grp_194E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_194E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7355
                dc.w $9500 ! ((grp_CC740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A7D
                dc.w $9500 ! ((grp_B4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $727D
                dc.w $9500 ! ((grp_E6AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E8B
                dc.w $9500 ! ((grp_E6A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8968
                dc.w $9500 ! ((grp_E6AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6AC0 / 2) >> 16)
                dc.w 1
