byte_2F2B6E:    dc.b   0,  5,$72,$6B,$90,$82,$81,$76,$82,$76
                                        ; DATA XREF: ROM:off_2754   o
                dc.w sprite_8_24
                dc.w $7868
                dc.w $9500 ! ((grp_19D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7880
                dc.w $9500 ! ((grp_DA5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $886F
                dc.w $9500 ! ((grp_DA600 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $706D
                dc.w $9500 ! ((grp_BFF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8068
                dc.w $9500 ! ((grp_BFF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8078
                dc.w $9500 ! ((grp_F17E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F17E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F17E0 / 2) >> 16)
                dc.w 1
