byte_2EFA1C:    dc.b   0,  2,$66,$15,$92,$1D,$7C,$19,$7D,$19
                                        ; DATA XREF: ROM:off_2548   o
                dc.w sprite_16_8
                dc.w $6417
                dc.w $9500 ! ((grp_D9F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A17
                dc.w $9500 ! ((grp_D9F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C13
                dc.w $9500 ! ((grp_BF8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF8C0 / 2) >> 16)
                dc.w 2
