byte_2D633A:    dc.b   0,  5,$6F,$66,$8E,$8F,$80,$76,$84,$6D
                                        ; DATA XREF: ROM:off_122C   o
                dc.w sprite_24_32
                dc.w $7468
                dc.w $9500 ! ((grp_106B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_106B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7C58
                dc.w $9500 ! ((grp_80080 / 2) & $00FF)
                dc.w $9600 ! (((grp_80080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80080 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_99F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6C69
                dc.w $9500 ! ((grp_B8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C65
                dc.w $9500 ! ((grp_B8CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9469
                dc.w $9500 ! ((grp_EADA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EADA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EADA0 / 2) >> 16)
                dc.w 1
