byte_2F99CC:    dc.b   0,  1,$7B,$77,$85,$86,$80,$7E,$81,$7E
                                        ; DATA XREF: ROM:off_2DA8   o
                dc.w sprite_16_16
                dc.w $7979
                dc.w $9500 ! ((grp_91280 / 2) & $00FF)
                dc.w $9600 ! (((grp_91280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7B71
                dc.w $9500 ! ((grp_F6CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6CA0 / 2) >> 16)
                dc.w 1
