byte_2D0510:    dc.b   0,  3,$78,$72,$8F,$8C,$83,$7F,$84,$7F
                                        ; DATA XREF: ROM:off_D30   o
                dc.w sprite_8_24
                dc.w $7E78
                dc.w $9500 ! ((grp_192CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_192CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7670
                dc.w $9500 ! ((grp_B1900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $867E
                dc.w $9500 ! ((grp_E3460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D80
                dc.w $9500 ! ((grp_E3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3480 / 2) >> 16)
                dc.w 1
