byte_2D2050:    dc.b   0,  8,$5F,$66,$A2,$8D,$7E,$79,$7F,$79
                                        ; DATA XREF: ROM:off_E90   o
                dc.w sprite_24_32
                dc.w $8A6C
                dc.w $9500 ! ((grp_FCF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FCF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FCF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6A68
                dc.w $9500 ! ((grp_121E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_121E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6A80
                dc.w $9500 ! ((grp_48400 / 2) & $00FF)
                dc.w $9600 ! (((grp_48400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5A74
                dc.w $9500 ! ((grp_171580 / 2) & $00FF)
                dc.w $9600 ! (((grp_171580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171580 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $8A64
                dc.w $9500 ! ((grp_97980 / 2) & $00FF)
                dc.w $9600 ! (((grp_97980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D60
                dc.w $9500 ! ((grp_C9B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A278
                dc.w $9500 ! ((grp_B23C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B23C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B23C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $527C
                dc.w $9500 ! ((grp_E4080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $928C
                dc.w $9500 ! ((grp_E40A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E40A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E40A0 / 2) >> 16)
                dc.w 1
