byte_2FEEE2:    dc.b   0,  3,$70,$6C,$8E,$8D,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_350C   o
                dc.w sprite_24_32
                dc.w $746A
                dc.w $9500 ! ((grp_11DAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11DAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11DAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6D77
                dc.w $9500 ! ((grp_1A1700 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1700 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $758A
                dc.w $9500 ! ((grp_E0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C6A
                dc.w $9500 ! ((grp_C67C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C67C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C67C0 / 2) >> 16)
                dc.w 2
