byte_2DB0D8:    dc.b   0,  9,$6A,$53,$96,$8E,$80,$70,$81,$70
                                        ; DATA XREF: ROM:off_1530   o
                dc.w sprite_32_16
                dc.w $6863
                dc.w $9500 ! ((grp_4FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7873
                dc.w $9500 ! ((grp_85700 / 2) & $00FF)
                dc.w $9600 ! (((grp_85700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8858
                dc.w $9500 ! ((grp_A8800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $685B
                dc.w $9500 ! ((grp_D5B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6D8B
                dc.w $9500 ! ((grp_D5BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7283
                dc.w $9500 ! ((grp_D5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8988
                dc.w $9500 ! ((grp_D5C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8878
                dc.w $9500 ! ((grp_BC080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C51
                dc.w $9500 ! ((grp_BC0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7073
                dc.w $9500 ! ((grp_EDC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDC60 / 2) >> 16)
                dc.w 1
