byte_2F8F34:    dc.b   0,  5,$6F,$71,$90,$85,$7F,$6D,$80,$6D
                                        ; DATA XREF: ROM:off_2CE8   o
                dc.w sprite_32_24
                dc.w $746E
                dc.w $9500 ! ((grp_1393C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1393C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1393C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6472
                dc.w $9500 ! ((grp_90F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $775E
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A66
                dc.w $9500 ! ((grp_F6440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B56
                dc.w $9500 ! ((grp_F63E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9477
                dc.w $9500 ! ((grp_F6420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6420 / 2) >> 16)
                dc.w 1
