byte_2D0862:    dc.b   0,  2,$55,$52,$AC,$8E,$7A,$84,$7B,$84
                                        ; DATA XREF: ROM:off_D94   o
                dc.w sprite_24_24
                dc.w $6B7B
                dc.w $9500 ! ((grp_13F720 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F720 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $8380
                dc.w $9500 ! ((grp_B1EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7273
                dc.w $9500 ! ((grp_E3AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3AC0 / 2) >> 16)
                dc.w 1
