byte_2F7828:    dc.b   0, $C,$64,$42,$9E,$83,$84,$5D,$85,$5D
                                        ; DATA XREF: ROM:off_2BA8   o
                dc.w sprite_32_32
                dc.w $5756
                dc.w $9500 ! ((grp_3F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3F600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6636
                dc.w $9500 ! ((grp_3F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3F800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7756
                dc.w $9500 ! ((grp_3FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3FA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8636
                dc.w $9500 ! ((grp_3FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3FC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9756
                dc.w $9500 ! ((grp_118E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_118E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D76
                dc.w $9500 ! ((grp_56F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5646
                dc.w $9500 ! ((grp_90500 / 2) & $00FF)
                dc.w $9600 ! (((grp_90500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D76
                dc.w $9500 ! ((grp_90580 / 2) & $00FF)
                dc.w $9600 ! (((grp_90580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A636
                dc.w $9500 ! ((grp_ADD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $AE4E
                dc.w $9500 ! ((grp_19F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F180 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D76
                dc.w $9500 ! ((grp_DD9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E3E
                dc.w $9500 ! ((grp_F5D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5D20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D76
                dc.w $9500 ! ((grp_F5D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5D40 / 2) >> 16)
                dc.w 1
