byte_2FED6C:    dc.b   0,  1,$75,$76,$88,$85,$7E,$7D,$7F,$7D
                                        ; DATA XREF: ROM:off_34E0   o
                dc.w sprite_16_16
                dc.w $7B79
                dc.w $9500 ! ((grp_96B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7374
                dc.w $9500 ! ((grp_F97A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F97A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F97A0 / 2) >> 16)
                dc.w 1
