byte_2F45C8:    dc.b   0,  2,$76,$6D,$8C,$93,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_2990   o
                dc.w sprite_24_32
                dc.w $776B
                dc.w $9500 ! ((grp_1159C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1159C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1159C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $778B
                dc.w $9500 ! ((grp_168040 / 2) & $00FF)
                dc.w $9600 ! (((grp_168040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168040 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6F81
                dc.w $9500 ! ((grp_F3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3A00 / 2) >> 16)
                dc.w 1
