byte_2E411E:    dc.b   0, $B,$5F,$3C,$A8,$52,$92,$6F,$9C,$69
                                        ; DATA XREF: ROM:off_1B1C   o
                dc.w sprite_32_16
                dc.w $5D42
                dc.w $9500 ! ((grp_4AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $853A
                dc.w $9500 ! ((grp_4AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $854A
                dc.w $9500 ! ((grp_174580 / 2) & $00FF)
                dc.w $9600 ! (((grp_174580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174580 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $A53E
                dc.w $9500 ! ((grp_196060 / 2) & $00FF)
                dc.w $9600 ! (((grp_196060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196060 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D3A
                dc.w $9500 ! ((grp_CDC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D6A
                dc.w $9500 ! ((grp_CDC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D42
                dc.w $9500 ! ((grp_B5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A255
                dc.w $9500 ! ((grp_B5DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6452
                dc.w $9500 ! ((grp_E8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $753A
                dc.w $9500 ! ((grp_E83A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E83A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E83A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_E8340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A62
                dc.w $9500 ! ((grp_E8360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8360 / 2) >> 16)
                dc.w 1
