byte_2CC674:    dc.b   0,  2,$77,$5A,$8C,$6B,$81,$72,$82,$72
                                        ; DATA XREF: ROM:off_7A0   o
                dc.w sprite_24_16
                dc.w $785E
                dc.w $9500 ! ((grp_155E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_155E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7E56
                dc.w $9500 ! ((grp_C6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7063
                dc.w $9500 ! ((grp_E13C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E13C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E13C0 / 2) >> 16)
                dc.w 1
