byte_2E8B28:    dc.b   0,  3,$7B,$66,$87,$8D,$80,$79,$8A,$69
                                        ; DATA XREF: ROM:off_1DB0   o
                dc.w sprite_16_32
                dc.w $7B64
                dc.w $9500 ! ((grp_61100 / 2) & $00FF)
                dc.w $9600 ! (((grp_61100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $7380
                dc.w $9500 ! ((grp_B6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B84
                dc.w $9500 ! ((grp_B6440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B67
                dc.w $9500 ! ((grp_E8900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8900 / 2) >> 16)
                dc.w 1
