byte_2E0A72:    dc.b   0,  6,$42,$30,$6E,$66,$58,$4B,$6B,$39
                                        ; DATA XREF: ROM:off_18FC   o
                dc.w sprite_32_24
                dc.w $4051
                dc.w $9500 ! ((grp_12B8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4141
                dc.w $9500 ! ((grp_4EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6048
                dc.w $9500 ! ((grp_177340 / 2) & $00FF)
                dc.w $9600 ! (((grp_177340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6130
                dc.w $9500 ! ((grp_1774C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1774C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1774C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $5139
                dc.w $9500 ! ((grp_D2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6060
                dc.w $9500 ! ((grp_EBD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6628
                dc.w $9500 ! ((grp_EBD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD60 / 2) >> 16)
                dc.w 1
