byte_2D5DAC:    dc.b   0,  6,$73,$5E,$89,$83,$85,$67,$7B,$59
                                        ; DATA XREF: ROM:off_11F0   o
                dc.w sprite_32_24
                dc.w $6F53
                dc.w $9500 ! ((grp_123DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_123DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7473
                dc.w $9500 ! ((grp_78B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $716B
                dc.w $9500 ! ((grp_98400 / 2) & $00FF)
                dc.w $9600 ! (((grp_98400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $784B
                dc.w $9500 ! ((grp_CBF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B71
                dc.w $9500 ! ((grp_CBF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8F69
                dc.w $9500 ! ((grp_CBF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $727E
                dc.w $9500 ! ((grp_E6420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6420 / 2) >> 16)
                dc.w 1
