byte_2FD3FA:    dc.b   0,  7,$6A,$44,$8D,$8D,$7B,$68,$7C,$68
                                        ; DATA XREF: ROM:off_32E4   o
                dc.w sprite_32_16
                dc.w $6B41
                dc.w $9500 ! ((grp_59700 / 2) & $00FF)
                dc.w $9600 ! (((grp_59700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6850
                dc.w $9500 ! ((grp_70B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6B70
                dc.w $9500 ! ((grp_70C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8351
                dc.w $9500 ! ((grp_94F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_94F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_94F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B88
                dc.w $9500 ! ((grp_DFBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B80
                dc.w $9500 ! ((grp_F8320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B49
                dc.w $9500 ! ((grp_F8340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B61
                dc.w $9500 ! ((grp_F8360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8360 / 2) >> 16)
                dc.w 1
