byte_2F4D4A:    dc.b   0,  8,$6F,$63,$94,$8E,$8B,$78,$8C,$78
                                        ; DATA XREF: ROM:off_2A1C   o
                dc.w sprite_24_32
                dc.w $7D5E
                dc.w $9500 ! ((grp_116440 / 2) & $00FF)
                dc.w $9600 ! (((grp_116440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6D68
                dc.w $9500 ! ((grp_6DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7D7E
                dc.w $9500 ! ((grp_168580 / 2) & $00FF)
                dc.w $9600 ! (((grp_168580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168580 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6578
                dc.w $9500 ! ((grp_19E580 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E580 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_DC680 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $868E
                dc.w $9500 ! ((grp_DC6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $956E
                dc.w $9500 ! ((grp_C1940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D77
                dc.w $9500 ! ((grp_C1980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A57E
                dc.w $9500 ! ((grp_C19C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C19C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C19C0 / 2) >> 16)
                dc.w 2
