byte_2E3792:    dc.b   0,  4,$77,$64,$9A,$92,$88,$7B,$89,$7B
                                        ; DATA XREF: ROM:off_1ACC   o
                dc.w sprite_24_24
                dc.w $7972
                dc.w $9500 ! ((grp_149260 / 2) & $00FF)
                dc.w $9600 ! (((grp_149260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149260 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7E62
                dc.w $9500 ! ((grp_50C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $758A
                dc.w $9500 ! ((grp_18B260 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B260 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $766A
                dc.w $9500 ! ((grp_EE940 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8692
                dc.w $9500 ! ((grp_EE960 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE960 / 2) >> 16)
                dc.w 1
