byte_2CEB98:    dc.b   0,  3,$78,$45,$83,$7F,$7D,$62,$7E,$62
                                        ; DATA XREF: ROM:off_B10   o
                dc.w sprite_16_16
                dc.w $7643
                dc.w $9500 ! ((grp_74380 / 2) & $00FF)
                dc.w $9600 ! (((grp_74380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7653
                dc.w $9500 ! ((grp_A2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7673
                dc.w $9500 ! ((grp_E2620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $787B
                dc.w $9500 ! ((grp_E2640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2640 / 2) >> 16)
                dc.w 1
