byte_2DA130:    dc.b   0,$17,$86,$67,$8F,$77,$7F,$6D,$80,$6D
                                        ; DATA XREF: ROM:off_1488   o
                dc.w sprite_16_24
                dc.w $8055
                dc.w $9500 ! ((grp_1738C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1738C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1738C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $704D
                dc.w $9500 ! ((grp_98680 / 2) & $00FF)
                dc.w $9600 ! (((grp_98680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6A4D
                dc.w $9500 ! ((grp_195340 / 2) & $00FF)
                dc.w $9600 ! (((grp_195340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $686D
                dc.w $9500 ! ((grp_CCC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $688D
                dc.w $9500 ! ((grp_CC940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7085
                dc.w $9500 ! ((grp_CCA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $788D
                dc.w $9500 ! ((grp_CC9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $888D
                dc.w $9500 ! ((grp_CAF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8885
                dc.w $9500 ! ((grp_CC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7255
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7855
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $786D
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $806D
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $876D
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7065
                dc.w $9500 ! ((grp_E70E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E70E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E70E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $707D
                dc.w $9500 ! ((grp_E58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7075
                dc.w $9500 ! ((grp_E58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7865
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $787D
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8085
                dc.w $9500 ! ((grp_E6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $807D
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $877D
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9053
                dc.w $9500 ! ((grp_E5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A00 / 2) >> 16)
                dc.w 1
