byte_2F9CCE:    dc.b   0,  7,$71,$64,$93,$8E,$7C,$6F,$7D,$6F
                                        ; DATA XREF: ROM:off_2DD4   o
                dc.w sprite_32_32
                dc.w $655E
                dc.w $9500 ! ((grp_41400 / 2) & $00FF)
                dc.w $9600 ! (((grp_41400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $855E
                dc.w $9500 ! ((grp_11AC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11AC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11AC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6B7E
                dc.w $9500 ! ((grp_57800 / 2) & $00FF)
                dc.w $9600 ! (((grp_57800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7D4E
                dc.w $9500 ! ((grp_91500 / 2) & $00FF)
                dc.w $9600 ! (((grp_91500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B7E
                dc.w $9500 ! ((grp_91580 / 2) & $00FF)
                dc.w $9600 ! (((grp_91580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91580 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $718E
                dc.w $9500 ! ((grp_A0500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5D72
                dc.w $9500 ! ((grp_F6F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C56
                dc.w $9500 ! ((grp_F6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6F40 / 2) >> 16)
                dc.w 1
