byte_2F8BDC:    dc.b   0,  7,$66,$82,$99,$A4,$7F,$93,$80,$93
                                        ; DATA XREF: ROM:off_2CC0   o
                dc.w sprite_24_24
                dc.w $7480
                dc.w $9500 ! ((grp_152020 / 2) & $00FF)
                dc.w $9600 ! (((grp_152020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152020 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7C98
                dc.w $9500 ! ((grp_90C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_90C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $64A0
                dc.w $9500 ! ((grp_18FA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FA60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8CA0
                dc.w $9500 ! ((grp_DE0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6498
                dc.w $9500 ! ((grp_F6300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C90
                dc.w $9500 ! ((grp_F62C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F62C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F62C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C90
                dc.w $9500 ! ((grp_F62E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F62E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F62E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9498
                dc.w $9500 ! ((grp_F6320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6320 / 2) >> 16)
                dc.w 1
