byte_2E7A2C:    dc.b   0,  4,$6F,$77,$8E,$8F,$8E,$7C,$8E,$7E
                                        ; DATA XREF: ROM:off_1D10   o
                dc.w sprite_32_24
                dc.w $6D79
                dc.w $9500 ! ((grp_129040 / 2) & $00FF)
                dc.w $9600 ! (((grp_129040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7671
                dc.w $9500 ! ((grp_188260 / 2) & $00FF)
                dc.w $9600 ! (((grp_188260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188260 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D78
                dc.w $9500 ! ((grp_197740 / 2) & $00FF)
                dc.w $9600 ! (((grp_197740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $957B
                dc.w $9500 ! ((grp_B82C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B82C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B82C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9D7C
                dc.w $9500 ! ((grp_EA3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA3C0 / 2) >> 16)
                dc.w 1
