byte_2D0E4C:    dc.b   0, $C,$48,$62,$7B,$8D,$5F,$76,$60,$76
                                        ; DATA XREF: ROM:off_DD8   o
                dc.w sprite_32_32
                dc.w $515C
                dc.w $9500 ! ((grp_14600 / 2) & $00FF)
                dc.w $9600 ! (((grp_14600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $715B
                dc.w $9500 ! ((grp_47500 / 2) & $00FF)
                dc.w $9600 ! (((grp_47500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $3979
                dc.w $9500 ! ((grp_1579C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1579C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1579C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $2B82
                dc.w $9500 ! ((grp_76080 / 2) & $00FF)
                dc.w $9600 ! (((grp_76080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $4169
                dc.w $9500 ! ((grp_76000 / 2) & $00FF)
                dc.w $9600 ! (((grp_76000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $517C
                dc.w $9500 ! ((grp_97500 / 2) & $00FF)
                dc.w $9600 ! (((grp_97500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $3B89
                dc.w $9500 ! ((grp_C9000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $628B
                dc.w $9500 ! ((grp_C9040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $717C
                dc.w $9500 ! ((grp_C9080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4961
                dc.w $9500 ! ((grp_E3740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6784
                dc.w $9500 ! ((grp_E36E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E36E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E36E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $716B
                dc.w $9500 ! ((grp_E3700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7474
                dc.w $9500 ! ((grp_E3720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3720 / 2) >> 16)
                dc.w 1
