byte_2DE7B2:    dc.b   0,  6,$6E,$5B,$8D,$8D,$7D,$70,$7E,$5C
                                        ; DATA XREF: ROM:off_1784   o
                dc.w sprite_24_32
                dc.w $7359
                dc.w $9500 ! ((grp_10C0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7379
                dc.w $9500 ! ((grp_162100 / 2) & $00FF)
                dc.w $9600 ! (((grp_162100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6361
                dc.w $9500 ! ((grp_178F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_178F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_D5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7051
                dc.w $9500 ! ((grp_D5140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8489
                dc.w $9500 ! ((grp_D5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B65
                dc.w $9500 ! ((grp_BB8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB8C0 / 2) >> 16)
                dc.w 2
