byte_2E545A:    dc.b   0,  8,$6F,$61,$88,$8E,$3E,$97,$7A,$63
                                        ; DATA XREF: ROM:off_1BBC   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_160A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_160A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8261
                dc.w $9500 ! ((grp_177E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_177E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5A5F
                dc.w $9500 ! ((grp_D3880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7552
                dc.w $9500 ! ((grp_D38C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D38C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D38C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9261
                dc.w $9500 ! ((grp_BA640 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA640 / 2) >> 16)
                dc.w 2
