byte_2D7562:    dc.b   0,  5,$74,$60,$88,$7B,$82,$6C,$86,$5C
                                        ; DATA XREF: ROM:off_12E4   o
                dc.w sprite_32_32
                dc.w $725C
                dc.w $9500 ! ((grp_25200 / 2) & $00FF)
                dc.w $9600 ! (((grp_25200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6244
                dc.w $9500 ! ((grp_161980 / 2) & $00FF)
                dc.w $9600 ! (((grp_161980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $787C
                dc.w $9500 ! ((grp_161A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_161A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6A54
                dc.w $9500 ! ((grp_D4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8254
                dc.w $9500 ! ((grp_D48C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D48C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D48C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $788C
                dc.w $9500 ! ((grp_ED000 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED000 / 2) >> 16)
                dc.w 1
