byte_2CD816:    dc.b   0,  2,$5D,$4C,$67,$59,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_91C   o
                dc.w sprite_16_16
                dc.w $5B4D
                dc.w $9500 ! ((grp_73F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_73F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $774D
                dc.w $9500 ! ((grp_B0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C45
                dc.w $9500 ! ((grp_E1E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1E20 / 2) >> 16)
                dc.w 1
