byte_2DB9CE:    dc.b   0,  3,$6A,$69,$82,$8D,$76,$7B,$76,$6A
                                        ; DATA XREF: ROM:off_158C   o
                dc.w sprite_24_24
                dc.w $747B
                dc.w $9500 ! ((grp_142660 / 2) & $00FF)
                dc.w $9600 ! (((grp_142660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142660 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $746B
                dc.w $9500 ! ((grp_7A180 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6C73
                dc.w $9500 ! ((grp_B4A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8473
                dc.w $9500 ! ((grp_E7180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7180 / 2) >> 16)
                dc.w 1
