byte_2D37F6:    dc.b   0,  5,$8B,$70,$C9,$89,$AA,$7C,$AB,$7C
                                        ; DATA XREF: ROM:off_1034   o
                dc.w sprite_32_16
                dc.w $9076
                dc.w $9500 ! ((grp_48A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $B078
                dc.w $9500 ! ((grp_48B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_48B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $946E
                dc.w $9500 ! ((grp_184C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_184C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $B888
                dc.w $9500 ! ((grp_CA8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $887E
                dc.w $9500 ! ((grp_E5040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B86
                dc.w $9500 ! ((grp_E5060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5060 / 2) >> 16)
                dc.w 1
