byte_2FEF62:    dc.b   0,  4,$6D,$75,$9B,$8A,$84,$7F,$85,$7F
                                        ; DATA XREF: ROM:off_3514   o
                dc.w sprite_24_24
                dc.w $8073
                dc.w $9500 ! ((grp_155AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_155AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155AA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $7871
                dc.w $9500 ! ((grp_AFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7079
                dc.w $9500 ! ((grp_1A1580 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1580 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6879
                dc.w $9500 ! ((grp_C6740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9877
                dc.w $9500 ! ((grp_C6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6780 / 2) >> 16)
                dc.w 2
