byte_2DE8E4:    dc.b   0,  9,$78,$4F,$A3,$8F,$8D,$6F,$8E,$6F
                                        ; DATA XREF: ROM:off_1790   o
                dc.w sprite_24_32
                dc.w $8272
                dc.w $9500 ! ((grp_107EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_107EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $9973
                dc.w $9500 ! ((grp_80B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8055
                dc.w $9500 ! ((grp_9A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $816A
                dc.w $9500 ! ((grp_188C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_188C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188C20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $844D
                dc.w $9500 ! ((grp_188C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_188C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A71
                dc.w $9500 ! ((grp_B90C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B90C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B90C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7273
                dc.w $9500 ! ((grp_EB2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB2A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $875D
                dc.w $9500 ! ((grp_EB2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB2E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F62
                dc.w $9500 ! ((grp_EB2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB2C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $975D
                dc.w $9500 ! ((grp_EB300 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB300 / 2) >> 16)
                dc.w 1
