byte_2DF378:    dc.b   0,  5,$73,$63,$8E,$8C,$80,$77,$8A,$6C
                                        ; DATA XREF: ROM:off_17F8   o
                dc.w sprite_24_24
                dc.w $7C6F
                dc.w $9500 ! ((grp_1431A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1431A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1431A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6C81
                dc.w $9500 ! ((grp_7AA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E5F
                dc.w $9500 ! ((grp_7AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7471
                dc.w $9500 ! ((grp_B51C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B51C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B51C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B5E
                dc.w $9500 ! ((grp_E78C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E78C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E78C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $947D
                dc.w $9500 ! ((grp_E78E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E78E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E78E0 / 2) >> 16)
                dc.w 1
