byte_2EEF28:    dc.b   0,  4,$61,$79,$9E,$8D,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_2438   o
                dc.w sprite_32_16
                dc.w $8984
                dc.w $9500 ! ((grp_52E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_52E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7184
                dc.w $9500 ! ((grp_165580 / 2) & $00FF)
                dc.w $9600 ! (((grp_165580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165580 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $5187
                dc.w $9500 ! ((grp_9E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7F6C
                dc.w $9500 ! ((grp_F0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A984
                dc.w $9500 ! ((grp_F0C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0C20 / 2) >> 16)
                dc.w 1
