byte_2D2C4E:    dc.b   0,  6,$75,$6E,$91,$8C,$82,$7A,$83,$7A
                                        ; DATA XREF: ROM:off_F24   o
                dc.w sprite_24_16
                dc.w $7A7F
                dc.w $9500 ! ((grp_1591C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1591C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1591C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7A6F
                dc.w $9500 ! ((grp_159340 / 2) & $00FF)
                dc.w $9600 ! (((grp_159340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159340 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6A61
                dc.w $9500 ! ((grp_193D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_193D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $726C
                dc.w $9500 ! ((grp_B2BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $727C
                dc.w $9500 ! ((grp_E4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A8F
                dc.w $9500 ! ((grp_E4C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $927F
                dc.w $9500 ! ((grp_E4BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4BA0 / 2) >> 16)
                dc.w 1
