byte_2DDA86:    dc.b   0,  9,$4F,$47,$A1,$93,$78,$6D,$50,$50
                                        ; DATA XREF: ROM:off_16F4   o
                dc.w sprite_32_32
                dc.w $7376
                dc.w $9500 ! ((grp_1E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1E400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5C46
                dc.w $9500 ! ((grp_128A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_128A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7C45
                dc.w $9500 ! ((grp_128BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_128BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $4C45
                dc.w $9500 ! ((grp_7F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F200 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6B6E
                dc.w $9500 ! ((grp_99980 / 2) & $00FF)
                dc.w $9600 ! (((grp_99980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6B76
                dc.w $9500 ! ((grp_B7E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $705E
                dc.w $9500 ! ((grp_B7E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C45
                dc.w $9500 ! ((grp_B7E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $685E
                dc.w $9500 ! ((grp_EA140 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_EA120 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA120 / 2) >> 16)
                dc.w 1
