byte_2FC2B8:    dc.b   0,  1,$65,$88,$75,$95,$6D,$8E,$6E,$8E
                                        ; DATA XREF: ROM:off_30D8   o
                dc.w sprite_16_16
                dc.w $6886
                dc.w $9500 ! ((grp_92E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_92E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $628E
                dc.w $9500 ! ((grp_C52C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C52C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C52C0 / 2) >> 16)
                dc.w 2
