byte_2F588C:    dc.b   0,  6,$6F,$5F,$98,$8C,$83,$75,$84,$75
                                        ; DATA XREF: ROM:off_2AF0   o
                dc.w sprite_32_32
                dc.w $776A
                dc.w $9500 ! ((grp_3D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D200 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $6F6B
                dc.w $9500 ! ((grp_AD080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $795A
                dc.w $9500 ! ((grp_18ECE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18ECE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18ECE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7D62
                dc.w $9500 ! ((grp_18ED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18ED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18ED40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $838A
                dc.w $9500 ! ((grp_DCD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6780
                dc.w $9500 ! ((grp_F4960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $976A
                dc.w $9500 ! ((grp_F4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4980 / 2) >> 16)
                dc.w 1
