byte_2DD95E:    dc.b   0,  9,$57,$47,$A1,$91,$7C,$6C,$75,$49
                                        ; DATA XREF: ROM:off_16EC   o
                dc.w sprite_32_32
                dc.w $6A66
                dc.w $9500 ! ((grp_1E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1E200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7445
                dc.w $9500 ! ((grp_4CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7786
                dc.w $9500 ! ((grp_15E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5546
                dc.w $9500 ! ((grp_7F080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6256
                dc.w $9500 ! ((grp_7F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9445
                dc.w $9500 ! ((grp_7F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $857D
                dc.w $9500 ! ((grp_1880E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1880E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1880E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6546
                dc.w $9500 ! ((grp_D0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A75
                dc.w $9500 ! ((grp_EA080 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9475
                dc.w $9500 ! ((grp_EA0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA0A0 / 2) >> 16)
                dc.w 1
