byte_2E018A:    dc.b   0,  4,$6C,$67,$93,$8E,$7F,$7A,$85,$70
                                        ; DATA XREF: ROM:off_189C   o
                dc.w sprite_32_32
                dc.w $7A60
                dc.w $9500 ! ((grp_20E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_20E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7280
                dc.w $9500 ! ((grp_4E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6A69
                dc.w $9500 ! ((grp_198880 / 2) & $00FF)
                dc.w $9600 ! (((grp_198880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198880 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7268
                dc.w $9500 ! ((grp_1988E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1988E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1988E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A88
                dc.w $9500 ! ((grp_EB940 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB940 / 2) >> 16)
                dc.w 1
