byte_2D5F52:    dc.b   0,  7,$6E,$5F,$94,$97,$87,$7B,$7E,$73
                                        ; DATA XREF: ROM:off_1204   o
                dc.w sprite_24_24
                dc.w $7576
                dc.w $9500 ! ((grp_1418E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1418E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1418E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6571
                dc.w $9500 ! ((grp_78E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9B71
                dc.w $9500 ! ((grp_78E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8D7F
                dc.w $9500 ! ((grp_194A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_194A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $756E
                dc.w $9500 ! ((grp_CC000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $957F
                dc.w $9500 ! ((grp_CC040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5E
                dc.w $9500 ! ((grp_B3DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9292
                dc.w $9500 ! ((grp_E6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6580 / 2) >> 16)
                dc.w 1
