byte_2FF48E:    dc.b   0,  4,$35,$A7,$5A,$CE,$47,$BA,$48,$BA
                                        ; DATA XREF: ROM:off_3584   o
                dc.w sprite_32_32
                dc.w $3CA5
                dc.w $9500 ! ((grp_45A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_45A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_45A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_8
                dc.w $2CBD
                dc.w $9500 ! ((grp_E0540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $3CC5
                dc.w $9500 ! ((grp_E0580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $44CD
                dc.w $9500 ! ((grp_F8C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5CA5
                dc.w $9500 ! ((grp_F92A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F92A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F92A0 / 2) >> 16)
                dc.w 1
