byte_2DBD36:    dc.b   0,  3,$6B,$6E,$88,$8A,$79,$7C,$70,$6F
                                        ; DATA XREF: ROM:off_15C4   o
                dc.w sprite_24_24
                dc.w $7079
                dc.w $9500 ! ((grp_144DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_144DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144DC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6C69
                dc.w $9500 ! ((grp_15DB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15DB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15DB40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6879
                dc.w $9500 ! ((grp_B72C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B72C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B72C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8880
                dc.w $9500 ! ((grp_B7300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7300 / 2) >> 16)
                dc.w 2
