byte_2CD0F6:    dc.b   0,  1,$74,$76,$8B,$89,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_874   o
                dc.w sprite_24_24
                dc.w $7274
                dc.w $9500 ! ((grp_13E2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E2E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $8A79
                dc.w $9500 ! ((grp_B0AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0AC0 / 2) >> 16)
                dc.w 2
