byte_2ED78C:    dc.b   0,  3,$66,$70,$8F,$95,$78,$81,$79,$81
                                        ; DATA XREF: ROM:off_22C8   o
                dc.w sprite_24_32
                dc.w $6970
                dc.w $9500 ! ((grp_1120C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1120C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1120C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $6179
                dc.w $9500 ! ((grp_BEE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8181
                dc.w $9500 ! ((grp_BEE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8989
                dc.w $9500 ! ((grp_F0300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0300 / 2) >> 16)
                dc.w 1
