byte_2E90F6:    dc.b   0,  4,$6B,$43,$75,$8E,$6E,$5D,$6D,$4F
                                        ; DATA XREF: ROM:off_1E14   o
                dc.w sprite_16_16
                dc.w $6345
                dc.w $9500 ! ((grp_7ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7ED00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $736D
                dc.w $9500 ! ((grp_197440 / 2) & $00FF)
                dc.w $9600 ! (((grp_197440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6E5D
                dc.w $9500 ! ((grp_B7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $633D
                dc.w $9500 ! ((grp_E9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B55
                dc.w $9500 ! ((grp_E9DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9DA0 / 2) >> 16)
                dc.w 1
