byte_2F27F8:    dc.b   0, $A,$6E,$59,$9F,$A2,$82,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_2738   o
                dc.w sprite_32_32
                dc.w $8A55
                dc.w $9500 ! ((grp_39000 / 2) & $00FF)
                dc.w $9600 ! (((grp_39000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5A68
                dc.w $9500 ! ((grp_135C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_135C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $798D
                dc.w $9500 ! ((grp_54D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8A75
                dc.w $9500 ! ((grp_54E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $8085
                dc.w $9500 ! ((grp_9ED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9ED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9ED80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7A65
                dc.w $9500 ! ((grp_ACA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8255
                dc.w $9500 ! ((grp_ACA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $698C
                dc.w $9500 ! ((grp_19DAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DAA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $718E
                dc.w $9500 ! ((grp_19DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DB00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $799D
                dc.w $9500 ! ((grp_DB500 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8275
                dc.w $9500 ! ((grp_C08C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C08C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C08C0 / 2) >> 16)
                dc.w 2
