byte_2FC8D6:    dc.b   0,  1,$5B,$75,$8D,$87,$74,$7E,$75,$7E
                                        ; DATA XREF: ROM:off_315C   o
                dc.w sprite_32_16
                dc.w $7073
                dc.w $9500 ! ((grp_58E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_58E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $597A
                dc.w $9500 ! ((grp_190D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_190D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190D80 / 2) >> 16)
                dc.w 3
