byte_2ED10C:    dc.b   0,  8,$61,$45,$B0,$7E,$88,$61,$89,$61
                                        ; DATA XREF: ROM:off_2260   o
                dc.w sprite_16_24
                dc.w $704D
                dc.w $9500 ! ((grp_17B540 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B540 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6043
                dc.w $9500 ! ((grp_88C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_88C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8864
                dc.w $9500 ! ((grp_88C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9F69
                dc.w $9500 ! ((grp_88D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_88D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $805A
                dc.w $9500 ! ((grp_BEA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9769
                dc.w $9500 ! ((grp_BEA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6853
                dc.w $9500 ! ((grp_EFF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFF40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $885C
                dc.w $9500 ! ((grp_EFF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFF60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D79
                dc.w $9500 ! ((grp_EFF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFF80 / 2) >> 16)
                dc.w 1
