byte_2EF67C:    dc.b   0,  4,$78,$5A,$9C,$73,$8A,$66,$8B,$66
                                        ; DATA XREF: ROM:off_2508   o
                dc.w sprite_16_8
                dc.w $7662
                dc.w $9500 ! ((grp_D9D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7958
                dc.w $9500 ! ((grp_F1000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E60
                dc.w $9500 ! ((grp_F0FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $926C
                dc.w $9500 ! ((grp_F1020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9870
                dc.w $9500 ! ((grp_F0FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0FC0 / 2) >> 16)
                dc.w 1
