byte_2D883E:    dc.b   0,  9,$6F,$5A,$8E,$90,$89,$74,$76,$61
                                        ; DATA XREF: ROM:off_13B4   o
                dc.w sprite_16_32
                dc.w $8069
                dc.w $9500 ! ((grp_65100 / 2) & $00FF)
                dc.w $9600 ! (((grp_65100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7063
                dc.w $9500 ! ((grp_178C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_178C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6B5B
                dc.w $9500 ! ((grp_D49C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D49C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D49C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $987D
                dc.w $9500 ! ((grp_D4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $686B
                dc.w $9500 ! ((grp_BB500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F53
                dc.w $9500 ! ((grp_ED0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED0C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8061
                dc.w $9500 ! ((grp_ED0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED0E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8389
                dc.w $9500 ! ((grp_ED100 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9069
                dc.w $9500 ! ((grp_ED120 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9079
                dc.w $9500 ! ((grp_ED140 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED140 / 2) >> 16)
                dc.w 1
