byte_2D638C:    dc.b   0,  8,$6F,$51,$8E,$8F,$80,$6C,$81,$5B
                                        ; DATA XREF: ROM:off_1230   o
                dc.w sprite_24_32
                dc.w $8652
                dc.w $9500 ! ((grp_106CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_106CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7178
                dc.w $9500 ! ((grp_129940 / 2) & $00FF)
                dc.w $9600 ! (((grp_129940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7648
                dc.w $9500 ! ((grp_62C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_62C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5E5F
                dc.w $9500 ! ((grp_176980 / 2) & $00FF)
                dc.w $9600 ! (((grp_176980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7668
                dc.w $9500 ! ((grp_80100 / 2) & $00FF)
                dc.w $9600 ! (((grp_80100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6E58
                dc.w $9500 ! ((grp_A6780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8670
                dc.w $9500 ! ((grp_D1A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E5E
                dc.w $9500 ! ((grp_B8D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9188
                dc.w $9500 ! ((grp_EADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EADC0 / 2) >> 16)
                dc.w 1
