byte_2D6A70:    dc.b   0,  9,$74,$55,$92,$7A,$81,$48,$83,$5A
                                        ; DATA XREF: ROM:off_1278   o
                dc.w sprite_32_24
                dc.w $625E
                dc.w $9500 ! ((grp_12E8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $8256
                dc.w $9500 ! ((grp_A9080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6376
                dc.w $9500 ! ((grp_18AF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AF60 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8A65
                dc.w $9500 ! ((grp_18AFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AFC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7A46
                dc.w $9500 ! ((grp_19A6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A6E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $526B
                dc.w $9500 ! ((grp_D6480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5A56
                dc.w $9500 ! ((grp_BCA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8246
                dc.w $9500 ! ((grp_BCA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6256
                dc.w $9500 ! ((grp_EE3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE3A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $995E
                dc.w $9500 ! ((grp_EE3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE3C0 / 2) >> 16)
                dc.w 1
