byte_2DB1D0:    dc.b   0,  8,$6D,$67,$A1,$8E,$87,$7A,$88,$7A
                                        ; DATA XREF: ROM:off_1538   o
                dc.w sprite_24_24
                dc.w $6B66
                dc.w $9500 ! ((grp_148960 / 2) & $00FF)
                dc.w $9600 ! (((grp_148960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148960 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $737E
                dc.w $9500 ! ((grp_85800 / 2) & $00FF)
                dc.w $9600 ! (((grp_85800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8369
                dc.w $9500 ! ((grp_A8880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8B6C
                dc.w $9500 ! ((grp_18A8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A8A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6889
                dc.w $9500 ! ((grp_D5D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A89
                dc.w $9500 ! ((grp_D5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9464
                dc.w $9500 ! ((grp_D5DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $725E
                dc.w $9500 ! ((grp_EDCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDCA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B81
                dc.w $9500 ! ((grp_EDCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDCC0 / 2) >> 16)
                dc.w 1
