byte_2DC364:    dc.b   0,  5,$71,$59,$A3,$90,$87,$60,$88,$60
                                        ; DATA XREF: ROM:off_1610   o
                dc.w sprite_32_24
                dc.w $835D
                dc.w $9500 ! ((grp_12F040 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6B61
                dc.w $9500 ! ((grp_163180 / 2) & $00FF)
                dc.w $9600 ! (((grp_163180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $9355
                dc.w $9500 ! ((grp_D6A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6361
                dc.w $9500 ! ((grp_EE820 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $934D
                dc.w $9500 ! ((grp_EE840 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A36C
                dc.w $9500 ! ((grp_EE860 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE860 / 2) >> 16)
                dc.w 1
