byte_2DE5AC:    dc.b   0,  3,$72,$5E,$8A,$8D,$7F,$74,$81,$61
                                        ; DATA XREF: ROM:off_1770   o
                dc.w sprite_32_32
                dc.w $7061
                dc.w $9500 ! ((grp_25E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_25E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7181
                dc.w $9500 ! ((grp_4FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7059
                dc.w $9500 ! ((grp_18A3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A3C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $697F
                dc.w $9500 ! ((grp_ED560 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED560 / 2) >> 16)
                dc.w 1
