byte_2DB494:    dc.b   0,  9,$61,$55,$A1,$8F,$81,$72,$82,$72
                                        ; DATA XREF: ROM:off_1550   o
                dc.w sprite_32_16
                dc.w $6F56
                dc.w $9500 ! ((grp_50000 / 2) & $00FF)
                dc.w $9600 ! (((grp_50000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $796E
                dc.w $9500 ! ((grp_65D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7466
                dc.w $9500 ! ((grp_18A9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A9C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8F53
                dc.w $9500 ! ((grp_18AA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AA20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A89
                dc.w $9500 ! ((grp_D5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $848D
                dc.w $9500 ! ((grp_D5EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6755
                dc.w $9500 ! ((grp_BC200 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F55
                dc.w $9500 ! ((grp_EDD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDD40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7181
                dc.w $9500 ! ((grp_EDD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDD60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F5B
                dc.w $9500 ! ((grp_EDD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDD80 / 2) >> 16)
                dc.w 1
