byte_2E3764:    dc.b   0,  2,$7A,$68,$9C,$94,$8B,$7E,$8C,$7E
                                        ; DATA XREF: ROM:off_1AC8   o
                dc.w sprite_24_32
                dc.w $7968
                dc.w $9500 ! ((grp_10E1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7887
                dc.w $9500 ! ((grp_86980 / 2) & $00FF)
                dc.w $9600 ! (((grp_86980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9066
                dc.w $9500 ! ((grp_D6A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6A80 / 2) >> 16)
                dc.w 2
