byte_2D82DE:    dc.b   0,  5,$78,$69,$8D,$8E,$79,$60,$8A,$68
                                        ; DATA XREF: ROM:off_137C   o
                dc.w sprite_32_24
                dc.w $7672
                dc.w $9500 ! ((grp_124840 / 2) & $00FF)
                dc.w $9600 ! (((grp_124840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7862
                dc.w $9500 ! ((grp_15A780 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $768A
                dc.w $9500 ! ((grp_CC780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9672
                dc.w $9500 ! ((grp_B42C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B42C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B42C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $815A
                dc.w $9500 ! ((grp_E6BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906A
                dc.w $9500 ! ((grp_E6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6B80 / 2) >> 16)
                dc.w 1
