byte_2EE784:    dc.b   0,  5,$69,$66,$95,$93,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_23D8   o
                dc.w sprite_32_32
                dc.w $7366
                dc.w $9500 ! ((grp_32200 / 2) & $00FF)
                dc.w $9600 ! (((grp_32200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7386
                dc.w $9500 ! ((grp_52900 / 2) & $00FF)
                dc.w $9600 ! (((grp_52900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6B6C
                dc.w $9500 ! ((grp_AB880 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $936C
                dc.w $9500 ! ((grp_19D080 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D080 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6374
                dc.w $9500 ! ((grp_BF500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F5E
                dc.w $9500 ! ((grp_F0820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0820 / 2) >> 16)
                dc.w 1
