byte_2FE9BC:    dc.b   0,  2,$7B,$83,$87,$8E,$81,$87,$82,$87
                                        ; DATA XREF: ROM:off_3460   o
                dc.w sprite_16_16
                dc.w $797F
                dc.w $9500 ! ((grp_95F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_95F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7E8F
                dc.w $9500 ! ((grp_F8EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8987
                dc.w $9500 ! ((grp_F8EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8EC0 / 2) >> 16)
                dc.w 1
