byte_2E4BAE:    dc.b   0,  6,$71,$62,$89,$8E,$4D,$98,$7E,$63
                                        ; DATA XREF: ROM:off_1B74   o
                dc.w sprite_24_24
                dc.w $7179
                dc.w $9500 ! ((grp_146D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_146D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146D40 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7261
                dc.w $9500 ! ((grp_146E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_146E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146E60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $8A68
                dc.w $9500 ! ((grp_82100 / 2) & $00FF)
                dc.w $9600 ! (((grp_82100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7459
                dc.w $9500 ! ((grp_D3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8989
                dc.w $9500 ! ((grp_D34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D34C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A6B
                dc.w $9500 ! ((grp_B9FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9260
                dc.w $9500 ! ((grp_EC260 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC260 / 2) >> 16)
                dc.w 1
