byte_2CE88E:    dc.b   0,  5,$81,  2,$8D,$8F,$87,$48,$88,$48
                                        ; DATA XREF: ROM:off_AF4   o
                dc.w sprite_16_16
                dc.w $7F80
                dc.w $9500 ! ((grp_74500 / 2) & $00FF)
                dc.w $9600 ! (((grp_74500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8400
                dc.w $9500 ! ((grp_A2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8420
                dc.w $9500 ! ((grp_A2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8440
                dc.w $9500 ! ((grp_A2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8860
                dc.w $9500 ! ((grp_A2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8590
                dc.w $9500 ! ((grp_E27A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E27A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E27A0 / 2) >> 16)
                dc.w 1
