byte_2EF88E:    dc.b   0,  3,$68,$20,$8C,$3A,$7A,$2D,$7B,$2D
                                        ; DATA XREF: ROM:off_2534   o
                dc.w sprite_32_32
                dc.w $681D
                dc.w $9500 ! ((grp_33600 / 2) & $00FF)
                dc.w $9600 ! (((grp_33600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33600 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_8
                dc.w $6034
                dc.w $9500 ! ((grp_F1180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8834
                dc.w $9500 ! ((grp_F1140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8822
                dc.w $9500 ! ((grp_F1160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1160 / 2) >> 16)
                dc.w 1
