byte_2F26C0:    dc.b   0,  4,$73,$4D,$90,$7F,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_2720   o
                dc.w sprite_24_32
                dc.w $7355
                dc.w $9500 ! ((grp_113140 / 2) & $00FF)
                dc.w $9600 ! (((grp_113140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7B75
                dc.w $9500 ! ((grp_DA7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B65
                dc.w $9500 ! ((grp_F19E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F19E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F19E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $817D
                dc.w $9500 ! ((grp_F19C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F19C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F19C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B72
                dc.w $9500 ! ((grp_F19A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F19A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F19A0 / 2) >> 16)
                dc.w 1
