byte_2DA25A:    dc.b   0,$11,$86,$67,$8F,$77,$80,$6C,$81,$6C
                                        ; DATA XREF: ROM:off_148C   o
                dc.w sprite_24_16
                dc.w $704E
                dc.w $9500 ! ((grp_15AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15AC00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8086
                dc.w $9500 ! ((grp_79800 / 2) & $00FF)
                dc.w $9600 ! (((grp_79800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $684E
                dc.w $9500 ! ((grp_A4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $706E
                dc.w $9500 ! ((grp_CB000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $884E
                dc.w $9500 ! ((grp_CB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $785E
                dc.w $9500 ! ((grp_B34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B34C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $805E
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8076
                dc.w $9500 ! ((grp_B4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $885E
                dc.w $9500 ! ((grp_B4780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7886
                dc.w $9500 ! ((grp_E58E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $806E
                dc.w $9500 ! ((grp_E6EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8856
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $887E
                dc.w $9500 ! ((grp_E6E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8876
                dc.w $9500 ! ((grp_E6E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $886E
                dc.w $9500 ! ((grp_E6E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $908B
                dc.w $9500 ! ((grp_E5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9056
                dc.w $9500 ! ((grp_E5960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5960 / 2) >> 16)
                dc.w 1
