byte_2DBBAC:    dc.b   0,  4,$6A,$69,$86,$8E,$78,$7B,$72,$6A
                                        ; DATA XREF: ROM:off_15A8   o
                dc.w sprite_32_16
                dc.w $6D7B
                dc.w $9500 ! ((grp_49F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $756B
                dc.w $9500 ! ((grp_79B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_79B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $758B
                dc.w $9500 ! ((grp_185800 / 2) & $00FF)
                dc.w $9600 ! (((grp_185800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185800 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D6B
                dc.w $9500 ! ((grp_B4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8393
                dc.w $9500 ! ((grp_E7160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7160 / 2) >> 16)
                dc.w 1
