byte_2FECCE:    dc.b   0,  2,$7B,$7F,$85,$8D,$81,$82,$82,$82
                                        ; DATA XREF: ROM:off_34CC   o
                dc.w sprite_16_16
                dc.w $7986
                dc.w $9500 ! ((grp_96380 / 2) & $00FF)
                dc.w $9600 ! (((grp_96380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A7E
                dc.w $9500 ! ((grp_E0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8176
                dc.w $9500 ! ((grp_E09C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E09C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E09C0 / 2) >> 16)
                dc.w 2
