byte_2FFAF8:    dc.b   0,  1,$7B,$70,$86,$96,$80,$83,$81,$83
                                        ; DATA XREF: ROM:off_35D0   o
                dc.w sprite_16_32
                dc.w $796E
                dc.w $9500 ! ((grp_72600 / 2) & $00FF)
                dc.w $9600 ! (((grp_72600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72600 / 2) >> 16)
                dc.w     8
                dc.w sprite_8_16
                dc.w $7C8E
                dc.w $9500 ! ((grp_C66C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C66C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C66C0 / 2) >> 16)
                dc.w     2
