byte_2D709C:    dc.b   0,  8,$74,$55,$92,$7A,$81,$4E,$8D,$50
                                        ; DATA XREF: ROM:off_12B0   o
                dc.w sprite_32_24
                dc.w $7549
                dc.w $9500 ! ((grp_12ED40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12ED40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12ED40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7B61
                dc.w $9500 ! ((grp_66B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $9559
                dc.w $9500 ! ((grp_19AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AB00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6559
                dc.w $9500 ! ((grp_BD000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D56
                dc.w $9500 ! ((grp_BD040 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D61
                dc.w $9500 ! ((grp_EE660 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B81
                dc.w $9500 ! ((grp_EE680 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B77
                dc.w $9500 ! ((grp_EE6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE6A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D67
                dc.w $9500 ! ((grp_EE6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE6C0 / 2) >> 16)
                dc.w 1
