byte_2E0AD0:    dc.b   0,  6,$42,$33,$6F,$65,$58,$4C,$6B,$38
                                        ; DATA XREF: ROM:off_1900   o
                dc.w sprite_32_24
                dc.w $4050
                dc.w $9500 ! ((grp_12B8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4140
                dc.w $9500 ! ((grp_4EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6047
                dc.w $9500 ! ((grp_177340 / 2) & $00FF)
                dc.w $9600 ! (((grp_177340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $612F
                dc.w $9500 ! ((grp_177580 / 2) & $00FF)
                dc.w $9600 ! (((grp_177580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $5138
                dc.w $9500 ! ((grp_D2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $605F
                dc.w $9500 ! ((grp_EBD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7132
                dc.w $9500 ! ((grp_EBD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBD80 / 2) >> 16)
                dc.w 1
