byte_2F3FCE:    dc.b   0,  4,$71,$6C,$92,$95,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28C4   o
                dc.w sprite_24_32
                dc.w $7572
                dc.w $9500 ! ((grp_1156C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1156C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1156C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7592
                dc.w $9500 ! ((grp_DC040 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $836A
                dc.w $9500 ! ((grp_DC080 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D72
                dc.w $9500 ! ((grp_C1200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7E
                dc.w $9500 ! ((grp_F34A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F34A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F34A0 / 2) >> 16)
                dc.w 1
