byte_2E6E20:    dc.b   0,  8,$67,$5F,$9C,$8F,$81,$77,$82,$77
                                        ; DATA XREF: ROM:off_1C98   o
                dc.w sprite_24_32
                dc.w $7862
                dc.w $9500 ! ((grp_105040 / 2) & $00FF)
                dc.w $9600 ! (((grp_105040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $905C
                dc.w $9500 ! ((grp_62700 / 2) & $00FF)
                dc.w $9600 ! (((grp_62700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $907C
                dc.w $9500 ! ((grp_7EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7EE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7882
                dc.w $9500 ! ((grp_187F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_187F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $706E
                dc.w $9500 ! ((grp_1974A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1974A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1974A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708A
                dc.w $9500 ! ((grp_D0900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $888A
                dc.w $9500 ! ((grp_D0940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $687D
                dc.w $9500 ! ((grp_B7B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6082
                dc.w $9500 ! ((grp_E9F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9F20 / 2) >> 16)
                dc.w 1
