byte_2FC5F4:    dc.b   0,  3,$3F,$5A,$BF,$9B,$7F,$94,$80,$94
                                        ; DATA XREF: ROM:off_3120   o
                dc.w sprite_32_16
                dc.w $4090
                dc.w $9500 ! ((grp_58000 / 2) & $00FF)
                dc.w $9600 ! (((grp_58000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58000 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $6090
                dc.w $9500 ! ((grp_58100 / 2) & $00FF)
                dc.w $9600 ! (((grp_58100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58100 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8090
                dc.w $9500 ! ((grp_58200 / 2) & $00FF)
                dc.w $9600 ! (((grp_58200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $A090
                dc.w $9500 ! ((grp_58300 / 2) & $00FF)
                dc.w $9600 ! (((grp_58300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58300 / 2) >> 16)
                dc.w 8
