byte_2EF8C8:    dc.b   0,  4,$65,$1C,$8E,$38,$79,$2A,$7A,$2A
                                        ; DATA XREF: ROM:off_2538   o
                dc.w sprite_32_16
                dc.w $631A
                dc.w $9500 ! ((grp_53300 / 2) & $00FF)
                dc.w $9600 ! (((grp_53300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $762E
                dc.w $9500 ! ((grp_8A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $831A
                dc.w $9500 ! ((grp_8A880 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5E32
                dc.w $9500 ! ((grp_18D840 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D840 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8632
                dc.w $9500 ! ((grp_F11A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F11A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F11A0 / 2) >> 16)
                dc.w 1
