byte_2E5CEE:    dc.b   0,  6,$6B,$60,$84,$8E,$49,$94,$81,$63
                                        ; DATA XREF: ROM:off_1C04   o
                dc.w sprite_24_32
                dc.w $6C64
                dc.w $9500 ! ((grp_10A2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10A2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10A2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7084
                dc.w $9500 ! ((grp_160C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_160C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $635C
                dc.w $9500 ! ((grp_9AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $646D
                dc.w $9500 ! ((grp_199060 / 2) & $00FF)
                dc.w $9600 ! (((grp_199060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199060 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9470
                dc.w $9500 ! ((grp_D3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8465
                dc.w $9500 ! ((grp_BA780 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C66
                dc.w $9500 ! ((grp_BA7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA7C0 / 2) >> 16)
                dc.w 2
