byte_2FAB54:    dc.b   0,  7,$6E,$5C,$87,$8E,$83,$6F,$84,$6F
                                        ; DATA XREF: ROM:off_2E38   o
                dc.w sprite_32_32
                dc.w $6C71
                dc.w $9500 ! ((grp_42A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_42A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $6C53
                dc.w $9500 ! ((grp_11B840 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $8451
                dc.w $9500 ! ((grp_11B9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $8F71
                dc.w $9500 ! ((grp_190900 / 2) & $00FF)
                dc.w $9600 ! (((grp_190900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190900 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $645C
                dc.w $9500 ! ((grp_19FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FC00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9C51
                dc.w $9500 ! ((grp_19FBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FBA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $724B
                dc.w $9500 ! ((grp_DEE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9579
                dc.w $9500 ! ((grp_DEEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEEC0 / 2) >> 16)
                dc.w 2
