byte_2CF5D2:    dc.b   0, $A,$5E,$6E,$A8,$92,$87,$75,$88,$75
                                        ; DATA XREF: ROM:off_B6C   o
                dc.w sprite_24_32
                dc.w $7C6E
                dc.w $9500 ! ((grp_FB5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $946A
                dc.w $9500 ! ((grp_FB740 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB740 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5C77
                dc.w $9500 ! ((grp_120940 / 2) & $00FF)
                dc.w $9600 ! (((grp_120940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6F56
                dc.w $9500 ! ((grp_1570C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1570C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1570C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7C8E
                dc.w $9500 ! ((grp_183CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_183CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $948A
                dc.w $9500 ! ((grp_183D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_183D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $618F
                dc.w $9500 ! ((grp_E2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6760
                dc.w $9500 ! ((grp_E2C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F66
                dc.w $9500 ! ((grp_E2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A092
                dc.w $9500 ! ((grp_E2CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A75F
                dc.w $9500 ! ((grp_E2CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2CC0 / 2) >> 16)
                dc.w 1
