byte_2E1BE0:    dc.b   0,  4,$67,$5D,$9C,$85,$81,$71,$74,$60
                                        ; DATA XREF: ROM:off_1990   o
                dc.w sprite_32_32
                dc.w $6D5B
                dc.w $9500 ! ((grp_1D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1D800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $8C5F
                dc.w $9500 ! ((grp_187A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_187A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6573
                dc.w $9500 ! ((grp_1971A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1971A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1971A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6D80
                dc.w $9500 ! ((grp_E9AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $857B
                dc.w $9500 ! ((grp_E9AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9AE0 / 2) >> 16)
                dc.w 1
