byte_2F88CC:    dc.b   0,  6,$70,$3E,$90,$8A,$80,$64,$81,$64
                                        ; DATA XREF: ROM:off_2C98   o
                dc.w sprite_24_32
                dc.w $7D4C
                dc.w $9500 ! ((grp_119A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_119A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7684
                dc.w $9500 ! ((grp_16A080 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A080 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $763C
                dc.w $9500 ! ((grp_16A140 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7F6C
                dc.w $9500 ! ((grp_17FEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8E7C
                dc.w $9500 ! ((grp_C3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E87
                dc.w $9500 ! ((grp_F61C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F61C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F61C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E3C
                dc.w $9500 ! ((grp_F60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60C0 / 2) >> 16)
                dc.w 1
