byte_2D4FA0:    dc.b   0,  7,$6E,$64,$8E,$8F,$82,$79,$7D,$6C
                                        ; DATA XREF: ROM:off_1158   o
                dc.w sprite_16_32
                dc.w $7363
                dc.w $9500 ! ((grp_61A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8379
                dc.w $9500 ! ((grp_15D0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D0C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6B83
                dc.w $9500 ! ((grp_7CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8689
                dc.w $9500 ! ((grp_CF3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B71
                dc.w $9500 ! ((grp_B6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B63
                dc.w $9500 ! ((grp_E9160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B83
                dc.w $9500 ! ((grp_E9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8371
                dc.w $9500 ! ((grp_E91A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E91A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E91A0 / 2) >> 16)
                dc.w 1
