byte_2E3D3A:    dc.b   0, $D,$63,$78,$98,$8E,$BA,$47,$B8,$41
                                        ; DATA XREF: ROM:off_1B04   o
                dc.w sprite_32_16
                dc.w $7580
                dc.w $9500 ! ((grp_4A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $5D61
                dc.w $9500 ! ((grp_60C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $B13D
                dc.w $9500 ! ((grp_7B780 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D77
                dc.w $9500 ! ((grp_195E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_195E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195E80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9573
                dc.w $9500 ! ((grp_195E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_195E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195E20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9D72
                dc.w $9500 ! ((grp_B58C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B58C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B58C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A164
                dc.w $9500 ! ((grp_B5840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A85A
                dc.w $9500 ! ((grp_B5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5569
                dc.w $9500 ! ((grp_E8120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6581
                dc.w $9500 ! ((grp_E8140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D90
                dc.w $9500 ! ((grp_E8100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8878
                dc.w $9500 ! ((grp_E81A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E81A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E81A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AE55
                dc.w $9500 ! ((grp_E8160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B04D
                dc.w $9500 ! ((grp_E8180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8180 / 2) >> 16)
                dc.w 1
