byte_2E0B2E:    dc.b   0,  8,$3A,$3B,$7E,$7C,$5C,$5B,$67,$46
                                        ; DATA XREF: ROM:off_1904   o
                dc.w sprite_32_24
                dc.w $5761
                dc.w $9500 ! ((grp_12BA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12BA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12BA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $5749
                dc.w $9500 ! ((grp_12BBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12BBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12BBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7765
                dc.w $9500 ! ((grp_177640 / 2) & $00FF)
                dc.w $9600 ! (((grp_177640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $3F56
                dc.w $9500 ! ((grp_81980 / 2) & $00FF)
                dc.w $9600 ! (((grp_81980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $5B39
                dc.w $9500 ! ((grp_81A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_81A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4F51
                dc.w $9500 ! ((grp_A7800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6079
                dc.w $9500 ! ((grp_189220 / 2) & $00FF)
                dc.w $9600 ! (((grp_189220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $3759
                dc.w $9500 ! ((grp_EBDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBDA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $775D
                dc.w $9500 ! ((grp_EBDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBDC0 / 2) >> 16)
                dc.w 1
