byte_2E906C:    dc.b   0,  2,$74,$7F,$8F,$8E,$81,$81,$89,$8C
                                        ; DATA XREF: ROM:off_1E08   o
                dc.w sprite_32_16
                dc.w $7281
                dc.w $9500 ! ((grp_4C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7679
                dc.w $9500 ! ((grp_D06C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D06C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D06C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A71
                dc.w $9500 ! ((grp_B79C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B79C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B79C0 / 2) >> 16)
                dc.w 2
