byte_2E0144:    dc.b   0,  4,$6C,$60,$94,$8D,$80,$76,$8C,$80
                                        ; DATA XREF: ROM:off_1898   o
                dc.w sprite_32_32
                dc.w $6C70
                dc.w $9500 ! ((grp_20C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_20C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $775E
                dc.w $9500 ! ((grp_12AE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12AE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12AE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6760
                dc.w $9500 ! ((grp_81480 / 2) & $00FF)
                dc.w $9600 ! (((grp_81480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8C76
                dc.w $9500 ! ((grp_B96C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B96C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B96C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB920 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB920 / 2) >> 16)
                dc.w 1
