byte_2DD84E:    dc.b   0,  8,$57,$40,$A8,$83,$7F,$61,$A5,$45
                                        ; DATA XREF: ROM:off_16E4   o
                dc.w sprite_32_32
                dc.w $6D66
                dc.w $9500 ! ((grp_1E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1E000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $5546
                dc.w $9500 ! ((grp_4C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $853F
                dc.w $9500 ! ((grp_4CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4CA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $753E
                dc.w $9500 ! ((grp_176080 / 2) & $00FF)
                dc.w $9600 ! (((grp_176080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6D56
                dc.w $9500 ! ((grp_7F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8D6E
                dc.w $9500 ! ((grp_197560 / 2) & $00FF)
                dc.w $9600 ! (((grp_197560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6577
                dc.w $9500 ! ((grp_E9FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D5E
                dc.w $9500 ! ((grp_E9FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A542
                dc.w $9500 ! ((grp_EA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA000 / 2) >> 16)
                dc.w 1
