byte_2D168C:    dc.b   0,  5,$64,$5F,$A0,$8D,$86,$76,$87,$76
                                        ; DATA XREF: ROM:off_E20   o
                dc.w sprite_32_32
                dc.w $6A61
                dc.w $9500 ! ((grp_15C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9268
                dc.w $9500 ! ((grp_FC4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6A81
                dc.w $9500 ! ((grp_47D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6269
                dc.w $9500 ! ((grp_A3C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A60
                dc.w $9500 ! ((grp_A3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $9260
                dc.w $9500 ! ((grp_E3A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3A60 / 2) >> 16)
                dc.w 1
