byte_2F2B06:    dc.b   0,  1,$78,$79,$86,$82,$7F,$7D,$80,$7D
                                        ; DATA XREF: ROM:off_274C   o
                dc.w sprite_16_16
                dc.w $7977
                dc.w $9500 ! ((grp_8BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $717B
                dc.w $9500 ! ((grp_F1820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1820 / 2) >> 16)
                dc.w 1
