byte_2ECE6A:    dc.b   0,  2,$75,$74,$87,$89,$7E,$7E,$7F,$7E
                                        ; DATA XREF: ROM:off_2234   o
                dc.w sprite_24_16
                dc.w $727A
                dc.w $9500 ! ((grp_163FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_163FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7572
                dc.w $9500 ! ((grp_D8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $758A
                dc.w $9500 ! ((grp_D83C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D83C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D83C0 / 2) >> 16)
                dc.w 2
