byte_2FC274:    dc.b   0,  1,$67,$89,$76,$96,$6E,$8F,$6F,$8F
                                        ; DATA XREF: ROM:off_30D0   o
                dc.w sprite_16_16
                dc.w $6987
                dc.w $9500 ! ((grp_92D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_92D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $638F
                dc.w $9500 ! ((grp_C5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5280 / 2) >> 16)
                dc.w 2
