byte_2CF820:    dc.b   0,  1,$77,$76,$88,$8F,$7F,$82,$80,$82
                                        ; DATA XREF: ROM:off_B98   o
                dc.w sprite_16_32
                dc.w $7574
                dc.w $9500 ! ((grp_5CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5CC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $857C
                dc.w $9500 ! ((grp_E2DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2DA0 / 2) >> 16)
                dc.w 1
