byte_2E5E20:    dc.b   0,  6,$6F,$62,$89,$8E,$48,$9A,$80,$66
                                        ; DATA XREF: ROM:off_1C10   o
                dc.w sprite_32_24
                dc.w $7069
                dc.w $9500 ! ((grp_12C640 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $906A
                dc.w $9500 ! ((grp_82F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_82F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7089
                dc.w $9500 ! ((grp_9AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7081
                dc.w $9500 ! ((grp_189B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_189B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189B20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7061
                dc.w $9500 ! ((grp_189B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_189B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $686D
                dc.w $9500 ! ((grp_BA800 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7759
                dc.w $9500 ! ((grp_EC740 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC740 / 2) >> 16)
                dc.w 1
