byte_2CF732:    dc.b   0,  1,$6F,$7C,$90,$8A,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_B7C   o
                dc.w sprite_24_16
                dc.w $7D7D
                dc.w $9500 ! ((grp_157180 / 2) & $00FF)
                dc.w $9600 ! (((grp_157180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6D78
                dc.w $9500 ! ((grp_74D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_74D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74D00 / 2) >> 16)
                dc.w 4
