byte_2DEFB4:    dc.b   0,  9,$6D,$54,$8F,$8E,$79,$71,$64,$7B
                                        ; DATA XREF: ROM:off_17D0   o
                dc.w sprite_32_16
                dc.w $6383
                dc.w $9500 ! ((grp_50300 / 2) & $00FF)
                dc.w $9600 ! (((grp_50300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7363
                dc.w $9500 ! ((grp_65F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5B73
                dc.w $9500 ! ((grp_85A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7353
                dc.w $9500 ! ((grp_85A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6B53
                dc.w $9500 ! ((grp_A8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8353
                dc.w $9500 ! ((grp_A8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B6B
                dc.w $9500 ! ((grp_A8D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8376
                dc.w $9500 ! ((grp_19A2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A2C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $636B
                dc.w $9500 ! ((grp_EE000 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B63
                dc.w $9500 ! ((grp_EE020 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE020 / 2) >> 16)
                dc.w 1
