byte_2D1D88:    dc.b   0,  4,$6B,$7F,$93,$8E,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_E68   o
                dc.w sprite_24_24
                dc.w $7979
                dc.w $9500 ! ((grp_140020 / 2) & $00FF)
                dc.w $9600 ! (((grp_140020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140020 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6979
                dc.w $9500 ! ((grp_1714C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1714C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1714C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7171
                dc.w $9500 ! ((grp_E4020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9179
                dc.w $9500 ! ((grp_E4040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9183
                dc.w $9500 ! ((grp_E4060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4060 / 2) >> 16)
                dc.w 1
