byte_2CDE14:    dc.b   0,  3,$6A,$65,$91,$86,$7D,$75,$7E,$75
                                        ; DATA XREF: ROM:off_9C8   o
                dc.w sprite_32_32
                dc.w $6863
                dc.w $9500 ! ((grp_11C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_11C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6D83
                dc.w $9500 ! ((grp_96E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8864
                dc.w $9500 ! ((grp_A2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $906B
                dc.w $9500 ! ((grp_1921C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1921C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1921C0 / 2) >> 16)
                dc.w 3
