byte_2D3D14:    dc.b   0,  1,$7B,$73,$8B,$85,$85,$7A,$86,$7A
                                        ; DATA XREF: ROM:off_1078   o
                dc.w sprite_16_24
                dc.w $796F
                dc.w $9500 ! ((grp_171DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_171DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8976
                dc.w $9500 ! ((grp_B2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2B00 / 2) >> 16)
                dc.w 2
