byte_2F95A6:    dc.b   0,  1,$77,$61,$8A,$78,$80,$6C,$81,$6C
                                        ; DATA XREF: ROM:off_2D54   o
                dc.w sprite_24_16
                dc.w $755F
                dc.w $9500 ! ((grp_16A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A200 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7D6F
                dc.w $9500 ! ((grp_C4100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4100 / 2) >> 16)
                dc.w 2
