byte_2EC6E6:    dc.b   0,  1,$70,$83,$8C,$8F,$7C,$89,$7D,$89
                                        ; DATA XREF: ROM:off_214C   o
                dc.w sprite_24_16
                dc.w $7782
                dc.w $9500 ! ((grp_164140 / 2) & $00FF)
                dc.w $9600 ! (((grp_164140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $678A
                dc.w $9500 ! ((grp_D8440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8440 / 2) >> 16)
                dc.w 2
