byte_2EC11E:    dc.b   0,  2,$77,$6C,$8B,$91,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_20AC   o
                dc.w sprite_24_32
                dc.w $766B
                dc.w $9500 ! ((grp_1114C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1114C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1114C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $768B
                dc.w $9500 ! ((grp_18C3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C3A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6E7F
                dc.w $9500 ! ((grp_EF920 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF920 / 2) >> 16)
                dc.w 1
