byte_2E90C8:    dc.b   0,  2,$72,$45,$7B,$8E,$77,$62,$75,$54
                                        ; DATA XREF: ROM:off_1E10   o
                dc.w sprite_8_32
                dc.w $7550
                dc.w $9500 ! ((grp_A6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D42
                dc.w $9500 ! ((grp_197380 / 2) & $00FF)
                dc.w $9600 ! (((grp_197380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7B6F
                dc.w $9500 ! ((grp_1973E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1973E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1973E0 / 2) >> 16)
                dc.w 3
