byte_2FC4E6:    dc.b   0,  7,$46,$5A,$BD,$AF,$81,$94,$82,$94
                                        ; DATA XREF: ROM:off_3114   o
                dc.w sprite_24_16
                dc.w $5782
                dc.w $9500 ! ((grp_16C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C300 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7F92
                dc.w $9500 ! ((grp_16C240 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C240 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $A7A0
                dc.w $9500 ! ((grp_16C180 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $477A
                dc.w $9500 ! ((grp_93380 / 2) & $00FF)
                dc.w $9600 ! (((grp_93380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6F89
                dc.w $9500 ! ((grp_93300 / 2) & $00FF)
                dc.w $9600 ! (((grp_93300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9799
                dc.w $9500 ! ((grp_93280 / 2) & $00FF)
                dc.w $9600 ! (((grp_93280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $577A
                dc.w $9500 ! ((grp_F7EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F8A
                dc.w $9500 ! ((grp_F7EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7EC0 / 2) >> 16)
                dc.w 1
