byte_2CD03E:    dc.b   0,  3,$7B,$6B,$86,$8D,$80,$7C,$81,$7C
                                        ; DATA XREF: ROM:off_864   o
                dc.w sprite_16_16
                dc.w $796A
                dc.w $9500 ! ((grp_73A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_73A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $798A
                dc.w $9500 ! ((grp_C70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C70C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D7A
                dc.w $9500 ! ((grp_B0580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D62
                dc.w $9500 ! ((grp_E1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1CC0 / 2) >> 16)
                dc.w 1
