byte_2E1F5E:    dc.b   0,  2,$74,$61,$8E,$88,$81,$74,$80,$67
                                        ; DATA XREF: ROM:off_19CC   o
                dc.w sprite_32_24
                dc.w $7163
                dc.w $9500 ! ((grp_125EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_125EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $757B
                dc.w $9500 ! ((grp_15C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $795B
                dc.w $9500 ! ((grp_CD780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD780 / 2) >> 16)
                dc.w 2
