byte_2D1A24:    dc.b   0,  9,$74,$66,$97,$89,$97,$75,$98,$75
                                        ; DATA XREF: ROM:off_E40   o
                dc.w sprite_32_32
                dc.w $7162
                dc.w $9500 ! ((grp_16000 / 2) & $00FF)
                dc.w $9600 ! (((grp_16000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9162
                dc.w $9500 ! ((grp_FC7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7182
                dc.w $9500 ! ((grp_158500 / 2) & $00FF)
                dc.w $9600 ! (((grp_158500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9982
                dc.w $9500 ! ((grp_76680 / 2) & $00FF)
                dc.w $9600 ! (((grp_76680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $A962
                dc.w $9500 ! ((grp_193300 / 2) & $00FF)
                dc.w $9600 ! (((grp_193300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193300 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $A95A
                dc.w $9500 ! ((grp_C9840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B162
                dc.w $9500 ! ((grp_B2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A15A
                dc.w $9500 ! ((grp_E3C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A97A
                dc.w $9500 ! ((grp_E3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B95A
                dc.w $9500 ! ((grp_E3C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C60 / 2) >> 16)
                dc.w 1
