byte_2E3500:    dc.b   0,  8,$70,$64,$80,$6D,$79,$70,$7B,$75
                                        ; DATA XREF: ROM:off_1AB0   o
                dc.w sprite_24_16
                dc.w $6F86
                dc.w $9500 ! ((grp_15E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7076
                dc.w $9500 ! ((grp_15E440 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7966
                dc.w $9500 ! ((grp_7E580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6166
                dc.w $9500 ! ((grp_187C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_187C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187C60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $604E
                dc.w $9500 ! ((grp_197320 / 2) & $00FF)
                dc.w $9600 ! (((grp_197320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197320 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $696E
                dc.w $9500 ! ((grp_D0640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $878B
                dc.w $9500 ! ((grp_D04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D04C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6856
                dc.w $9500 ! ((grp_B7980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $896C
                dc.w $9500 ! ((grp_E9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C40 / 2) >> 16)
                dc.w 1
