byte_2EE2C6:    dc.b   0,  5,$6A,$6D,$96,$93,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_237C   o
                dc.w sprite_32_24
                dc.w $6B74
                dc.w $9500 ! ((grp_132940 / 2) & $00FF)
                dc.w $9600 ! (((grp_132940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8B75
                dc.w $9500 ! ((grp_17BCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BCC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $728C
                dc.w $9500 ! ((grp_18D1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D1E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $776C
                dc.w $9500 ! ((grp_D9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6377
                dc.w $9500 ! ((grp_BF380 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A8D
                dc.w $9500 ! ((grp_F07A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F07A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F07A0 / 2) >> 16)
                dc.w 1
