byte_2F9B32:    dc.b   0,  4,$7B,$68,$90,$8F,$81,$7B,$82,$7B
                                        ; DATA XREF: ROM:off_2DC4   o
                dc.w sprite_32_24
                dc.w $6679
                dc.w $9500 ! ((grp_13A140 / 2) & $00FF)
                dc.w $9600 ! (((grp_13A140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13A140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $867A
                dc.w $9500 ! ((grp_152A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_152A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152A40 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7A62
                dc.w $9500 ! ((grp_16A5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A5C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6F72
                dc.w $9500 ! ((grp_A0080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8F72
                dc.w $9500 ! ((grp_F6D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D40 / 2) >> 16)
                dc.w 1
