byte_2D01E8:    dc.b   0,  5,$5E,$64,$89,$87,$73,$75,$74,$75
                                        ; DATA XREF: ROM:off_CF0   o
                dc.w sprite_32_24
                dc.w $676A
                dc.w $9500 ! ((grp_120C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_120C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6B62
                dc.w $9500 ! ((grp_1840C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1840C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1840C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7882
                dc.w $9500 ! ((grp_C8BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F6F
                dc.w $9500 ! ((grp_B1840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $576F
                dc.w $9500 ! ((grp_E32A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E32A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E32A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8771
                dc.w $9500 ! ((grp_E32C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E32C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E32C0 / 2) >> 16)
                dc.w 1
