byte_2F9832:    dc.b   0,  8,$69,$67,$9A,$95,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_2D94   o
                dc.w sprite_24_24
                dc.w $7672
                dc.w $9500 ! ((grp_152800 / 2) & $00FF)
                dc.w $9600 ! (((grp_152800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152800 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $928A
                dc.w $9500 ! ((grp_DE680 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E76
                dc.w $9500 ! ((grp_C4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B62
                dc.w $9500 ! ((grp_C42C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C42C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C42C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6579
                dc.w $9500 ! ((grp_F6B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A86
                dc.w $9500 ! ((grp_F6AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7190
                dc.w $9500 ! ((grp_F6AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8990
                dc.w $9500 ! ((grp_F6AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $907B
                dc.w $9500 ! ((grp_F6B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6B20 / 2) >> 16)
                dc.w 1
