byte_2EFD3C:    dc.b   0,  2,$7A,$6E,$88,$8E,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_2598   o
                dc.w sprite_16_32
                dc.w $7A74
                dc.w $9500 ! ((grp_6AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7B6C
                dc.w $9500 ! ((grp_DA140 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7288
                dc.w $9500 ! ((grp_F13C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F13C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F13C0 / 2) >> 16)
                dc.w 1
