byte_2FEDF4:    dc.b   0,  1,$7E,$71,$85,$87,$81,$7C,$82,$7C
                                        ; DATA XREF: ROM:off_34F0   o
                dc.w sprite_16_16
                dc.w $787F
                dc.w $9500 ! ((grp_96900 / 2) & $00FF)
                dc.w $9600 ! (((grp_96900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7E6F
                dc.w $9500 ! ((grp_C6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6800 / 2) >> 16)
                dc.w 2
