byte_2D0834:    dc.b   0,  2,$55,$52,$AC,$8E,$7B,$83,$7C,$83
                                        ; DATA XREF: ROM:off_D90   o
                dc.w sprite_32_16
                dc.w $6E7E
                dc.w $9500 ! ((grp_47E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $6E8E
                dc.w $9500 ! ((grp_C9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7076
                dc.w $9500 ! ((grp_C9540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9540 / 2) >> 16)
                dc.w 2
