byte_2F965C:    dc.b   0,  1,$74,$5C,$89,$6A,$7E,$63,$7F,$63
                                        ; DATA XREF: ROM:off_2D68   o
                dc.w sprite_24_8
                dc.w $735A
                dc.w $9500 ! ((grp_18FFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FFA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7B6A
                dc.w $9500 ! ((grp_F6920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6920 / 2) >> 16)
                dc.w 1
