byte_2E1AF6:    dc.b   0,  6,$78,$5E,$93,$8D,$83,$74,$7C,$5B
                                        ; DATA XREF: ROM:off_1984   o
                dc.w sprite_32_24
                dc.w $6E71
                dc.w $9500 ! ((grp_12BD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12BD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12BD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $786A
                dc.w $9500 ! ((grp_9AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F5A
                dc.w $9500 ! ((grp_189580 / 2) & $00FF)
                dc.w $9600 ! (((grp_189580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189580 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7489
                dc.w $9500 ! ((grp_189340 / 2) & $00FF)
                dc.w $9600 ! (((grp_189340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A62
                dc.w $9500 ! ((grp_D3000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A62
                dc.w $9500 ! ((grp_D2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E72
                dc.w $9500 ! ((grp_B9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9B80 / 2) >> 16)
                dc.w 2
