byte_2F191C:    dc.b   0,  3,$7C,$68,$8D,$87,$84,$77,$85,$77
                                        ; DATA XREF: ROM:off_2690   o
                dc.w sprite_16_24
                dc.w $7A66
                dc.w $9500 ! ((grp_17DAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DAC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7E7E
                dc.w $9500 ! ((grp_C0B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A6A
                dc.w $9500 ! ((grp_C0BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7685
                dc.w $9500 ! ((grp_F2A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2A60 / 2) >> 16)
                dc.w 1
