byte_2F74EA:    dc.b   0, $C,$69,$37,$8E,$83,$70,$7E,$71,$7E
                                        ; DATA XREF: ROM:off_2B94   o
                dc.w sprite_32_32
                dc.w $6C3D
                dc.w $9500 ! ((grp_3EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3EA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $745D
                dc.w $9500 ! ((grp_118540 / 2) & $00FF)
                dc.w $9600 ! (((grp_118540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118540 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8C35
                dc.w $9500 ! ((grp_1513C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1513C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1513C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $5C3D
                dc.w $9500 ! ((grp_17F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F800 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6D7D
                dc.w $9500 ! ((grp_9F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8C4D
                dc.w $9500 ! ((grp_19EEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EEE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5452
                dc.w $9500 ! ((grp_C2EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A435
                dc.w $9500 ! ((grp_C2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C55
                dc.w $9500 ! ((grp_F5720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5D35
                dc.w $9500 ! ((grp_F5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C62
                dc.w $9500 ! ((grp_F5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7135
                dc.w $9500 ! ((grp_F5760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $954D
                dc.w $9500 ! ((grp_F5780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5780 / 2) >> 16)
                dc.w 1
