byte_2E9E08:    dc.b   0,  4,$65,$6A,$97,$8E,$7E,$7C,$7F,$7C
                                        ; DATA XREF: ROM:off_1ED8   o
                dc.w sprite_32_24
                dc.w $6B79
                dc.w $9500 ! ((grp_12F7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8B69
                dc.w $9500 ! ((grp_67000 / 2) & $00FF)
                dc.w $9600 ! (((grp_67000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7571
                dc.w $9500 ! ((grp_D6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B89
                dc.w $9500 ! ((grp_D6FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6380
                dc.w $9500 ! ((grp_BD840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD840 / 2) >> 16)
                dc.w 2
