byte_2D1D36:    dc.b   0,  5,$71,$70,$94,$8F,$84,$7F,$85,$7F
                                        ; DATA XREF: ROM:off_E64   o
                dc.w sprite_32_24
                dc.w $6E7B
                dc.w $9500 ! ((grp_121840 / 2) & $00FF)
                dc.w $9600 ! (((grp_121840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $766B
                dc.w $9500 ! ((grp_158800 / 2) & $00FF)
                dc.w $9600 ! (((grp_158800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158800 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8E80
                dc.w $9500 ! ((grp_B2200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $966D
                dc.w $9500 ! ((grp_B2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E6E
                dc.w $9500 ! ((grp_E3E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E75
                dc.w $9500 ! ((grp_E3E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3E80 / 2) >> 16)
                dc.w 1
