byte_2CFDA6:    dc.b   0,  1,$7B,$7C,$84,$89,$7F,$82,$80,$82
                                        ; DATA XREF: ROM:off_C5C   o
                dc.w sprite_16_16
                dc.w $797A
                dc.w $9500 ! ((grp_75680 / 2) & $00FF)
                dc.w $9600 ! (((grp_75680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7E8A
                dc.w $9500 ! ((grp_E30C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E30C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E30C0 / 2) >> 16)
                dc.w 1
