byte_2F5D74:    dc.b   0, $E,$75,$4A,$94,$83,$76,$7F,$77,$7F
                                        ; DATA XREF: ROM:off_2B28   o
                dc.w sprite_32_32
                dc.w $6C46
                dc.w $9500 ! ((grp_3D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7466
                dc.w $9500 ! ((grp_1168C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1168C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1168C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $9437
                dc.w $9500 ! ((grp_117AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_117AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $644E
                dc.w $9500 ! ((grp_AD100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C56
                dc.w $9500 ! ((grp_AD200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $945F
                dc.w $9500 ! ((grp_18EDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EDA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9C57
                dc.w $9500 ! ((grp_DCF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C66
                dc.w $9500 ! ((grp_C2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C3E
                dc.w $9500 ! ((grp_C2640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AC3A
                dc.w $9500 ! ((grp_C2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AC4F
                dc.w $9500 ! ((grp_C2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C4E
                dc.w $9500 ! ((grp_F4AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9457
                dc.w $9500 ! ((grp_F4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9470
                dc.w $9500 ! ((grp_F4A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B43E
                dc.w $9500 ! ((grp_F4DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4DE0 / 2) >> 16)
                dc.w 1
