byte_2CC2A2:    dc.b   0,  1,$82,$82,$96,$98,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_71C   o
                dc.w sprite_24_24
                dc.w $8083
                dc.w $9500 ! ((grp_13D320 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D320 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $867B
                dc.w $9500 ! ((grp_C6A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6A40 / 2) >> 16)
                dc.w 2
