byte_2FD362:    dc.b   0,  3,$76,$65,$8B,$8D,$80,$79,$81,$79
                                        ; DATA XREF: ROM:off_32DC   o
                dc.w sprite_32_24
                dc.w $6F68
                dc.w $9500 ! ((grp_13B1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7488
                dc.w $9500 ! ((grp_190F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_190F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7480
                dc.w $9500 ! ((grp_DFB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7960
                dc.w $9500 ! ((grp_DFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFB80 / 2) >> 16)
                dc.w 2
