byte_2DF4C0:    dc.b   0,  6,$71,$58,$8A,$8C,$7D,$70,$85,$63
                                        ; DATA XREF: ROM:off_1808   o
                dc.w sprite_24_32
                dc.w $7C59
                dc.w $9500 ! ((grp_101EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_101EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6C67
                dc.w $9500 ! ((grp_60A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $7C79
                dc.w $9500 ! ((grp_195820 / 2) & $00FF)
                dc.w $9600 ! (((grp_195820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195820 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $647C
                dc.w $9500 ! ((grp_E7960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7487
                dc.w $9500 ! ((grp_E7980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F51
                dc.w $9500 ! ((grp_E79A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E79A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E79A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9462
                dc.w $9500 ! ((grp_E5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5900 / 2) >> 16)
                dc.w 1
