byte_2DEED4:    dc.b   0,  7,$6F,$5A,$96,$8E,$89,$72,$76,$79
                                        ; DATA XREF: ROM:off_17C8   o
                dc.w sprite_32_32
                dc.w $6E56
                dc.w $9500 ! ((grp_26400 / 2) & $00FF)
                dc.w $9600 ! (((grp_26400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6E76
                dc.w $9500 ! ((grp_50200 / 2) & $00FF)
                dc.w $9600 ! (((grp_50200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7686
                dc.w $9500 ! ((grp_18AC60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AC60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AC60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8E6E
                dc.w $9500 ! ((grp_D6140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9E6C
                dc.w $9500 ! ((grp_D6180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $666E
                dc.w $9500 ! ((grp_BC580 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E76
                dc.w $9500 ! ((grp_EDFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDFA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A464
                dc.w $9500 ! ((grp_EDFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDFC0 / 2) >> 16)
                dc.w 1
