byte_2CD238:    dc.b   0,  3,$68,$6E,$95,$90,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_890   o
                dc.w sprite_32_32
                dc.w $6873
                dc.w $9500 ! ((grp_11200 / 2) & $00FF)
                dc.w $9600 ! (((grp_11200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8873
                dc.w $9500 ! ((grp_5BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5BD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7A6B
                dc.w $9500 ! ((grp_183820 / 2) & $00FF)
                dc.w $9600 ! (((grp_183820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183820 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6088
                dc.w $9500 ! ((grp_E2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2280 / 2) >> 16)
                dc.w 1
