byte_2EAC94:    dc.b   0,  4,$71,$70,$94,$8A,$81,$7C,$82,$7C
                                        ; DATA XREF: ROM:off_1FA8   o
                dc.w sprite_24_32
                dc.w $7067
                dc.w $9500 ! ((grp_10FE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10FE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10FE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8875
                dc.w $9500 ! ((grp_19B940 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B940 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $907C
                dc.w $9500 ! ((grp_D7740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8487
                dc.w $9500 ! ((grp_BDF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6869
                dc.w $9500 ! ((grp_EF220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF220 / 2) >> 16)
                dc.w 1
