byte_2D945A:    dc.b   0, $B,$5A,$30,$93,$76,$76,$53,$77,$53
                                        ; DATA XREF: ROM:off_1424   o
                dc.w sprite_24_32
                dc.w $7045
                dc.w $9500 ! ((grp_103CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_103CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6A65
                dc.w $9500 ! ((grp_7CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $862D
                dc.w $9500 ! ((grp_7CC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5840
                dc.w $9500 ! ((grp_186D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_186D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8856
                dc.w $9500 ! ((grp_196A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_196A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5838
                dc.w $9500 ! ((grp_CEC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7040
                dc.w $9500 ! ((grp_CEC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $803D
                dc.w $9500 ! ((grp_CF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6848
                dc.w $9500 ! ((grp_E8D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7175
                dc.w $9500 ! ((grp_E8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7638
                dc.w $9500 ! ((grp_E8FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8065
                dc.w $9500 ! ((grp_E8FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8FC0 / 2) >> 16)
                dc.w 1
