byte_2F8970:    dc.b   0,  4,$69,$7D,$9D,$8C,$83,$84,$84,$84
                                        ; DATA XREF: ROM:off_2CA0   o
                dc.w sprite_32_8
                dc.w $6A87
                dc.w $9500 ! ((grp_9FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7A7F
                dc.w $9500 ! ((grp_18F880 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F880 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8A87
                dc.w $9500 ! ((grp_18F8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F8E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $628C
                dc.w $9500 ! ((grp_F6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A77
                dc.w $9500 ! ((grp_F6220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6220 / 2) >> 16)
                dc.w 1
