byte_2EB1EE:    dc.b   0,  7,$75,$65,$93,$7F,$85,$71,$86,$71
                                        ; DATA XREF: ROM:off_1FEC   o
                dc.w sprite_32_24
                dc.w $705F
                dc.w $9500 ! ((grp_1312C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1312C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1312C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8A7F
                dc.w $9500 ! ((grp_87480 / 2) & $00FF)
                dc.w $9600 ! (((grp_87480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87480 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7077
                dc.w $9500 ! ((grp_9C680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $905F
                dc.w $9500 ! ((grp_AA300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9868
                dc.w $9500 ! ((grp_19BA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BA60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6C77
                dc.w $9500 ! ((grp_BE080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686A
                dc.w $9500 ! ((grp_EF3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF3E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7157
                dc.w $9500 ! ((grp_EF400 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF400 / 2) >> 16)
                dc.w 1
