byte_2EE7D6:    dc.b   0,  5,$66,$67,$96,$90,$7E,$7B,$7F,$7B
                                        ; DATA XREF: ROM:off_23DC   o
                dc.w sprite_32_32
                dc.w $7165
                dc.w $9500 ! ((grp_31E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_31E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_52700 / 2) & $00FF)
                dc.w $9600 ! (((grp_52700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52700 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6974
                dc.w $9500 ! ((grp_19CF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CF60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9167
                dc.w $9500 ! ((grp_19CFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CFC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6175
                dc.w $9500 ! ((grp_BF440 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $917F
                dc.w $9500 ! ((grp_BF480 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF480 / 2) >> 16)
                dc.w 2
