byte_2EB524:    dc.b   0,  3,$71,$55,$8F,$8D,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_2028   o
                dc.w sprite_32_32
                dc.w $716B
                dc.w $9500 ! ((grp_2AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2AA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $718B
                dc.w $9500 ! ((grp_9C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6973
                dc.w $9500 ! ((grp_AA580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9173
                dc.w $9500 ! ((grp_AA600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA600 / 2) >> 16)
                dc.w 4
