byte_2DABFC:    dc.b   0,  8,$6C,$76,$8E,$8B,$9E,$7F,$80,$85
                                        ; DATA XREF: ROM:off_14F8   o
                dc.w sprite_16_32
                dc.w $5A65
                dc.w $9500 ! ((grp_62000 / 2) & $00FF)
                dc.w $9600 ! (((grp_62000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6A69
                dc.w $9500 ! ((grp_61F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8A77
                dc.w $9500 ! ((grp_7D880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7A69
                dc.w $9500 ! ((grp_A5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6C89
                dc.w $9500 ! ((grp_187660 / 2) & $00FF)
                dc.w $9600 ! (((grp_187660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187660 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8276
                dc.w $9500 ! ((grp_197020 / 2) & $00FF)
                dc.w $9600 ! (((grp_197020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197020 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7261
                dc.w $9500 ! ((grp_CFC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7991
                dc.w $9500 ! ((grp_E9800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A7D
                dc.w $9500 ! ((grp_E9820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9820 / 2) >> 16)
                dc.w 1
