byte_2DAAA8:    dc.b   0,  7,$6D,$75,$88,$8A,$9E,$7E,$80,$7F
                                        ; DATA XREF: ROM:off_14E8   o
                dc.w sprite_24_24
                dc.w $6977
                dc.w $9500 ! ((grp_144A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_144A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144A60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $695F
                dc.w $9500 ! ((grp_175600 / 2) & $00FF)
                dc.w $9600 ! (((grp_175600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7E6F
                dc.w $9500 ! ((grp_CFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8177
                dc.w $9500 ! ((grp_B71C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B71C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B71C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9177
                dc.w $9500 ! ((grp_B7180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $698F
                dc.w $9500 ! ((grp_E9720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $897E
                dc.w $9500 ! ((grp_E9740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $997B
                dc.w $9500 ! ((grp_E9760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9760 / 2) >> 16)
                dc.w 1
