byte_2D8CC2:    dc.b   0,  6,$74,$55,$92,$7A,$82,$4D,$8C,$57
                                        ; DATA XREF: ROM:off_13DC   o
                dc.w sprite_32_24
                dc.w $7353
                dc.w $9500 ! ((grp_127CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_127CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7D6B
                dc.w $9500 ! ((grp_175240 / 2) & $00FF)
                dc.w $9600 ! (((grp_175240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6D70
                dc.w $9500 ! ((grp_7D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $804B
                dc.w $9500 ! ((grp_CF840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF840 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8283
                dc.w $9500 ! ((grp_CF880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B4D
                dc.w $9500 ! ((grp_B7040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $734B
                dc.w $9500 ! ((grp_E9540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9540 / 2) >> 16)
                dc.w 1
