byte_2E935C:    dc.b   0,  6,$59,$45,$A1,$80,$7C,$51,$7D,$51
                                        ; DATA XREF: ROM:off_1E58   o
                dc.w sprite_24_32
                dc.w $6442
                dc.w $9500 ! ((grp_10E7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $5C42
                dc.w $9500 ! ((grp_A9700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8452
                dc.w $9500 ! ((grp_D6E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5444
                dc.w $9500 ! ((grp_BD500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C4F
                dc.w $9500 ! ((grp_BD5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $944C
                dc.w $9500 ! ((grp_BD540 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C4B
                dc.w $9500 ! ((grp_BD580 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD580 / 2) >> 16)
                dc.w 2
