byte_2E1630:    dc.b   0,  7,$71,$58,$93,$8F,$7F,$72,$80,$72
                                        ; DATA XREF: ROM:off_1950   o
                dc.w sprite_16_32
                dc.w $7961
                dc.w $9500 ! ((grp_66300 / 2) & $00FF)
                dc.w $9600 ! (((grp_66300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $895B
                dc.w $9500 ! ((grp_179980 / 2) & $00FF)
                dc.w $9600 ! (((grp_179980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6155
                dc.w $9500 ! ((grp_85E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9BA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7155
                dc.w $9500 ! ((grp_A8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7959
                dc.w $9500 ! ((grp_D6300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $995A
                dc.w $9500 ! ((grp_BC780 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B81
                dc.w $9500 ! ((grp_EE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE1C0 / 2) >> 16)
                dc.w 1
