byte_2D6DB6:    dc.b   0,  5,$74,$55,$92,$A0,$81,$40,$82,$5F
                                        ; DATA XREF: ROM:off_1294   o
                dc.w sprite_24_32
                dc.w $7986
                dc.w $9500 ! ((grp_10DA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10DA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10DA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $80A6
                dc.w $9500 ! ((grp_66600 / 2) & $00FF)
                dc.w $9600 ! (((grp_66600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7E4E
                dc.w $9500 ! ((grp_A9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7F6E
                dc.w $9500 ! ((grp_19A7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A7A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7F3E
                dc.w $9500 ! ((grp_BCDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7FC0
                dc.w $9500 ! ((grp_EE4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE4E0 / 2) >> 16)
                dc.w 1
