byte_2F490E:    dc.b   0,  6,$6A,$63,$A4,$93,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_29F4   o
                dc.w sprite_32_32
                dc.w $6D73
                dc.w $9500 ! ((grp_3B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3B200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8D66
                dc.w $9500 ! ((grp_115CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_115CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6D63
                dc.w $9500 ! ((grp_55E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8986
                dc.w $9500 ! ((grp_8DF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8DF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8DF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6586
                dc.w $9500 ! ((grp_F3AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6573
                dc.w $9500 ! ((grp_F3B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $725B
                dc.w $9500 ! ((grp_F3B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3B20 / 2) >> 16)
                dc.w 1
