byte_2F8E90:    dc.b   0,  5,$6F,$71,$90,$85,$80,$6A,$81,$6A
                                        ; DATA XREF: ROM:off_2CE0   o
                dc.w sprite_32_24
                dc.w $706D
                dc.w $9500 ! ((grp_1390C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1390C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1390C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $774D
                dc.w $9500 ! ((grp_90D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_90D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $785D
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C65
                dc.w $9500 ! ((grp_DE240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6870
                dc.w $9500 ! ((grp_C3D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9073
                dc.w $9500 ! ((grp_C3D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3D40 / 2) >> 16)
                dc.w 2
