byte_2F1956:    dc.b   0,  2,$7A,$68,$8B,$86,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_2694   o
                dc.w sprite_16_32
                dc.w $7769
                dc.w $9500 ! ((grp_6CF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $876A
                dc.w $9500 ! ((grp_C0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B61
                dc.w $9500 ! ((grp_F2A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2A80 / 2) >> 16)
                dc.w 1
