byte_2F8CB0:    dc.b   0,  5,$6F,$71,$90,$85,$80,$6C,$81,$6C
                                        ; DATA XREF: ROM:off_2CC8   o
                dc.w sprite_32_24
                dc.w $716F
                dc.w $9500 ! ((grp_1396C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1396C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1396C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $745F
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6973
                dc.w $9500 ! ((grp_C3E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9170
                dc.w $9500 ! ((grp_C3E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7367
                dc.w $9500 ! ((grp_F64C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F64C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F64C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7857
                dc.w $9500 ! ((grp_F63E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63E0 / 2) >> 16)
                dc.w 1
