byte_2E36CC:    dc.b   0,  4,$6C,$69,$A1,$90,$86,$7C,$87,$7C
                                        ; DATA XREF: ROM:off_1AC0   o
                dc.w sprite_32_32
                dc.w $7668
                dc.w $9500 ! ((grp_27800 / 2) & $00FF)
                dc.w $9600 ! (((grp_27800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $7188
                dc.w $9500 ! ((grp_9C180 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9667
                dc.w $9500 ! ((grp_D6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A8B
                dc.w $9500 ! ((grp_EEAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEAE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $966F
                dc.w $9500 ! ((grp_EEB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB00 / 2) >> 16)
                dc.w 1
