byte_2E8E9C:    dc.b   0,  3,$7B,$58,$82,$8E,$7F,$71,$7D,$65
                                        ; DATA XREF: ROM:off_1DE8   o
                dc.w sprite_16_24
                dc.w $7879
                dc.w $9500 ! ((grp_176440 / 2) & $00FF)
                dc.w $9600 ! (((grp_176440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176440 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7B61
                dc.w $9500 ! ((grp_197980 / 2) & $00FF)
                dc.w $9600 ! (((grp_197980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197980 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7859
                dc.w $9500 ! ((grp_B8780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C51
                dc.w $9500 ! ((grp_EA8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA8E0 / 2) >> 16)
                dc.w 1
