byte_2CC376:    dc.b   0,  1,$82,$82,$96,$98,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_73C   o
                dc.w sprite_24_24
                dc.w $8081
                dc.w $9500 ! ((grp_13D7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D7A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $8499
                dc.w $9500 ! ((grp_C6AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6AC0 / 2) >> 16)
                dc.w 2
