byte_2DDC70:    dc.b   0,  3,$76,$6A,$8D,$90,$81,$7D,$7E,$6D
                                        ; DATA XREF: ROM:off_1710   o
                dc.w sprite_24_32
                dc.w $7673
                dc.w $9500 ! ((grp_107A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_107A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7A63
                dc.w $9500 ! ((grp_80980 / 2) & $00FF)
                dc.w $9600 ! (((grp_80980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8A66
                dc.w $9500 ! ((grp_197FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7C5B
                dc.w $9500 ! ((grp_EB1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB1E0 / 2) >> 16)
                dc.w 1
