byte_2E044A:    dc.b   0,  9,$52,$44,$92,$86,$72,$65,$86,$5E
                                        ; DATA XREF: ROM:off_18BC   o
                dc.w sprite_32_32
                dc.w $696A
                dc.w $9500 ! ((grp_21C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_21C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $714A
                dc.w $9500 ! ((grp_12B5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $514A
                dc.w $9500 ! ((grp_4E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $896A
                dc.w $9500 ! ((grp_63C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8642
                dc.w $9500 ! ((grp_D2C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4951
                dc.w $9500 ! ((grp_EBA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBA40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5442
                dc.w $9500 ! ((grp_EBA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBA60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5B5A
                dc.w $9500 ! ((grp_EBA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBA80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8262
                dc.w $9500 ! ((grp_EBAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBAA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $914A
                dc.w $9500 ! ((grp_EBAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBAC0 / 2) >> 16)
                dc.w 1
