byte_2FC5BA:    dc.b   0,  3,$41,$5A,$BF,$A2,$80,$94,$81,$94
                                        ; DATA XREF: ROM:0000311C   o
                dc.w sprite_32_16
                dc.w $4287
                dc.w $9500 ! ((grp_57C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $628C
                dc.w $9500 ! ((grp_57D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8290
                dc.w $9500 ! ((grp_57E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $A295
                dc.w $9500 ! ((grp_57F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57F00 / 2) >> 16)
                dc.w 8
