byte_2E062E:    dc.b   0,  7,$68,$4E,$94,$8C,$7E,$6D,$84,$57
                                        ; DATA XREF: ROM:off_18CC   o
                dc.w sprite_32_32
                dc.w $775C
                dc.w $9500 ! ((grp_22200 / 2) & $00FF)
                dc.w $9600 ! (((grp_22200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $677C
                dc.w $9500 ! ((grp_4E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $794C
                dc.w $9500 ! ((grp_81700 / 2) & $00FF)
                dc.w $9600 ! (((grp_81700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $877C
                dc.w $9500 ! ((grp_81780 / 2) & $00FF)
                dc.w $9600 ! (((grp_81780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81780 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6C8C
                dc.w $9500 ! ((grp_9A980 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6F64
                dc.w $9500 ! ((grp_198AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5F82
                dc.w $9500 ! ((grp_EBBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBBA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6774
                dc.w $9500 ! ((grp_EBBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBBC0 / 2) >> 16)
                dc.w 1
