byte_2E0FFE:    dc.b   0, $D,$72,$5A,$8E,$8E,$7A,$3D,$78,$28
                                        ; DATA XREF: ROM:off_1924   o
                dc.w sprite_24_16
                dc.w $6E25
                dc.w $9500 ! ((grp_15BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BE00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8E43
                dc.w $9500 ! ((grp_15BBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5437
                dc.w $9500 ! ((grp_7AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6E4E
                dc.w $9500 ! ((grp_7AE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7635
                dc.w $9500 ! ((grp_7AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9623
                dc.w $9500 ! ((grp_7AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $862D
                dc.w $9500 ! ((grp_A5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6626
                dc.w $9500 ! ((grp_195940 / 2) & $00FF)
                dc.w $9600 ! (((grp_195940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7E45
                dc.w $9500 ! ((grp_B5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E25
                dc.w $9500 ! ((grp_B5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6654
                dc.w $9500 ! ((grp_E7AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E38
                dc.w $9500 ! ((grp_E7B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E1D
                dc.w $9500 ! ((grp_E7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B53
                dc.w $9500 ! ((grp_E5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5860 / 2) >> 16)
                dc.w 1
