byte_2F23BC:    dc.b   0, $C,$59,$57,$A8,$92,$84,$7A,$85,$7A
                                        ; DATA XREF: ROM:off_26F8   o
                dc.w sprite_32_32
                dc.w $6F5E
                dc.w $9500 ! ((grp_38800 / 2) & $00FF)
                dc.w $9600 ! (((grp_38800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6F7E
                dc.w $9500 ! ((grp_135340 / 2) & $00FF)
                dc.w $9600 ! (((grp_135340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $5761
                dc.w $9500 ! ((grp_6C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C200 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6768
                dc.w $9500 ! ((grp_AC680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8F5E
                dc.w $9500 ! ((grp_AC700 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9767
                dc.w $9500 ! ((grp_AC780 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A766
                dc.w $9500 ! ((grp_AC800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9F6E
                dc.w $9500 ! ((grp_19D860 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4F66
                dc.w $9500 ! ((grp_C06C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C06C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C06C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AF6E
                dc.w $9500 ! ((grp_C0680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $678D
                dc.w $9500 ! ((grp_F24E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F24E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F24E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F7E
                dc.w $9500 ! ((grp_F2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8E
                dc.w $9500 ! ((grp_F2520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2520 / 2) >> 16)
                dc.w 1
