byte_2FD834:    dc.b   0,  5,$5F,$41,$8A,$8D,$80,$67,$81,$67
                                        ; DATA XREF: ROM:off_3310   o
                dc.w sprite_16_24
                dc.w $7D60
                dc.w $9500 ! ((grp_181FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_181FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181FC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7D78
                dc.w $9500 ! ((grp_95300 / 2) & $00FF)
                dc.w $9600 ! (((grp_95300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95300 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A0F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $723F
                dc.w $9500 ! ((grp_AED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AED80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7A50
                dc.w $9500 ! ((grp_C5AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A3F
                dc.w $9500 ! ((grp_F8480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8480 / 2) >> 16)
                dc.w 1
