byte_2FBE66:    dc.b   0,  1,$74,$72,$8C,$91,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_3034   o
                dc.w sprite_32_32
                dc.w $7270
                dc.w $9500 ! ((grp_44800 / 2) & $00FF)
                dc.w $9600 ! (((grp_44800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7990
                dc.w $9500 ! ((grp_190AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190AE0 / 2) >> 16)
                dc.w 3
