byte_2FBE88:    dc.b   0,  1,$75,$74,$8B,$8F,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_3038   o
                dc.w sprite_24_32
                dc.w $7672
                dc.w $9500 ! ((grp_11C5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11C5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11C5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $6E82
                dc.w $9500 ! ((grp_F7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7AC0 / 2) >> 16)
                dc.w 1
