byte_2DDB42:    dc.b   0,  3,$72,$6B,$8E,$91,$80,$7E,$8A,$70
                                        ; DATA XREF: ROM:off_16FC   o
                dc.w sprite_24_32
                dc.w $7172
                dc.w $9500 ! ((grp_107D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_107D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7D6B
                dc.w $9500 ! ((grp_D2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8974
                dc.w $9500 ! ((grp_B9040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D92
                dc.w $9500 ! ((grp_EB220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB220 / 2) >> 16)
                dc.w 1
