byte_2E7C7A:    dc.b   0,  4,$72,$64,$8A,$83,$A3,$60,$90,$6B
                                        ; DATA XREF: ROM:off_1D24   o
                dc.w sprite_32_32
                dc.w $695F
                dc.w $9500 ! ((grp_1E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1E600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $895F
                dc.w $9500 ! ((grp_4D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $697F
                dc.w $9500 ! ((grp_188380 / 2) & $00FF)
                dc.w $9600 ! (((grp_188380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5967
                dc.w $9500 ! ((grp_B83C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B83C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B83C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6171
                dc.w $9500 ! ((grp_EA5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA5A0 / 2) >> 16)
                dc.w 1
