byte_2F9C40:    dc.b   0, $A,$7A,$4D,$8E,$8E,$7F,$6B,$80,$6B
                                        ; DATA XREF: ROM:off_2DD0   o
                dc.w sprite_32_32
                dc.w $7269
                dc.w $9500 ! ((grp_41600 / 2) & $00FF)
                dc.w $9600 ! (((grp_41600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7E51
                dc.w $9500 ! ((grp_152DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_152DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152DA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6E51
                dc.w $9500 ! ((grp_180580 / 2) & $00FF)
                dc.w $9600 ! (((grp_180580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180580 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7589
                dc.w $9500 ! ((grp_1904E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1904E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1904E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7A49
                dc.w $9500 ! ((grp_190540 / 2) & $00FF)
                dc.w $9600 ! (((grp_190540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8041
                dc.w $9500 ! ((grp_DEA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A73
                dc.w $9500 ! ((grp_C4600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9269
                dc.w $9500 ! ((grp_C4640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6662
                dc.w $9500 ! ((grp_F6F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9666
                dc.w $9500 ! ((grp_F6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A6E
                dc.w $9500 ! ((grp_F6FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6FA0 / 2) >> 16)
                dc.w 1
