byte_2CDE4E:    dc.b   0,  3,$69,$63,$91,$84,$7D,$73,$7E,$73
                                        ; DATA XREF: ROM:off_9CC   o
                dc.w sprite_32_32
                dc.w $6C61
                dc.w $9500 ! ((grp_11E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6E81
                dc.w $9500 ! ((grp_96F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_96F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C61
                dc.w $9500 ! ((grp_A2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6467
                dc.w $9500 ! ((grp_192220 / 2) & $00FF)
                dc.w $9600 ! (((grp_192220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192220 / 2) >> 16)
                dc.w 3
