byte_2EC6C4:    dc.b   0,  1,$73,$7D,$8E,$91,$80,$87,$81,$87
                                        ; DATA XREF: ROM:off_2148   o
                dc.w sprite_24_24
                dc.w $717C
                dc.w $9500 ! ((grp_14B8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14B8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14B8A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $897B
                dc.w $9500 ! ((grp_BE5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE5C0 / 2) >> 16)
                dc.w 2
