byte_2DDF8A:    dc.b   0,  5,$76,$5F,$8B,$8E,$7F,$73,$82,$60
                                        ; DATA XREF: ROM:off_173C   o
                dc.w sprite_32_32
                dc.w $7356
                dc.w $9500 ! ((grp_25800 / 2) & $00FF)
                dc.w $9600 ! (((grp_25800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6F81
                dc.w $9500 ! ((grp_4F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7B76
                dc.w $9500 ! ((grp_84680 / 2) & $00FF)
                dc.w $9600 ! (((grp_84680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B5E
                dc.w $9500 ! ((grp_199A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_199A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $935E
                dc.w $9500 ! ((grp_BB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F89
                dc.w $9500 ! ((grp_ED2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED2A0 / 2) >> 16)
                dc.w 1
