byte_2D8072:    dc.b   0,  4,$73,$5E,$92,$9A,$88,$81,$80,$6B
                                        ; DATA XREF: ROM:off_135C   o
                dc.w sprite_24_24
                dc.w $7374
                dc.w $9500 ! ((grp_141D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_141D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141D60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7D8C
                dc.w $9500 ! ((grp_173200 / 2) & $00FF)
                dc.w $9600 ! (((grp_173200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8B7B
                dc.w $9500 ! ((grp_79380 / 2) & $00FF)
                dc.w $9600 ! (((grp_79380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7C5C
                dc.w $9500 ! ((grp_194DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $9B83
                dc.w $9500 ! ((grp_E6A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6A00 / 2) >> 16)
                dc.w 1
