byte_2EBF20:    dc.b   0,  9,$84,$5B,$A1,$80,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_2088   o
                dc.w sprite_32_32
                dc.w $5C66
                dc.w $9500 ! ((grp_2C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7C66
                dc.w $9500 ! ((grp_2CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2CA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $9C76
                dc.w $9500 ! ((grp_14A340 / 2) & $00FF)
                dc.w $9600 ! (((grp_14A340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14A340 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $4C86
                dc.w $9500 ! ((grp_51200 / 2) & $00FF)
                dc.w $9600 ! (((grp_51200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $6C86
                dc.w $9500 ! ((grp_51500 / 2) & $00FF)
                dc.w $9600 ! (((grp_51500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $9C66
                dc.w $9500 ! ((grp_1639C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1639C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1639C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4C76
                dc.w $9500 ! ((grp_87780 / 2) & $00FF)
                dc.w $9600 ! (((grp_87780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8C86
                dc.w $9500 ! ((grp_87A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_87A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5B73
                dc.w $9500 ! ((grp_EF6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B47F
                dc.w $9500 ! ((grp_EF800 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF800 / 2) >> 16)
                dc.w 1
