byte_2F6706:    dc.b   0,$10,$59,$5B,$80,$87,$64,$7A,$65,$7A
                                        ; DATA XREF: ROM:off_2B54   o
                dc.w sprite_32_32
                dc.w $585D
                dc.w $9500 ! ((grp_3DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $587D
                dc.w $9500 ! ((grp_56400 / 2) & $00FF)
                dc.w $9600 ! (((grp_56400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $786B
                dc.w $9500 ! ((grp_6E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $296D
                dc.w $9500 ! ((grp_169600 / 2) & $00FF)
                dc.w $9600 ! (((grp_169600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169600 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $4075
                dc.w $9500 ! ((grp_169000 / 2) & $00FF)
                dc.w $9600 ! (((grp_169000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169000 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $394D
                dc.w $9500 ! ((grp_AD980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $3155
                dc.w $9500 ! ((grp_19ECA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ECA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ECA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8936
                dc.w $9500 ! ((grp_DD180 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $415E
                dc.w $9500 ! ((grp_C2A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $413D
                dc.w $9500 ! ((grp_F5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4945
                dc.w $9500 ! ((grp_F5220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5069
                dc.w $9500 ! ((grp_F4B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $512D
                dc.w $9500 ! ((grp_F5240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5E55
                dc.w $9500 ! ((grp_F4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F55
                dc.w $9500 ! ((grp_F4AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $803D
                dc.w $9500 ! ((grp_F5260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8878
                dc.w $9500 ! ((grp_F4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B00 / 2) >> 16)
                dc.w 1
