byte_2CE962:    dc.b   0,  9,$79,  2,$90,$AB,$84,$56,$85,$56
                                        ; DATA XREF: ROM:off_AFC   o
                dc.w sprite_16_32
                dc.w $8281
                dc.w $9500 ! ((grp_5C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $779E
                dc.w $9500 ! ((grp_74400 / 2) & $00FF)
                dc.w $9600 ! (((grp_74400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8241
                dc.w $9500 ! ((grp_A2A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8A69
                dc.w $9500 ! ((grp_1925E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1925E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1925E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D10
                dc.w $9500 ! ((grp_192640 / 2) & $00FF)
                dc.w $9600 ! (((grp_192640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192640 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8231
                dc.w $9500 ! ((grp_B11C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B11C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B11C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8521
                dc.w $9500 ! ((grp_B1200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B00
                dc.w $9500 ! ((grp_B1240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D7E
                dc.w $9500 ! ((grp_E2720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8761
                dc.w $9500 ! ((grp_E2740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2740 / 2) >> 16)
                dc.w 1
