byte_2FE6AA:    dc.b   0,  1,$72,$76,$8C,$88,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_340C   o
                dc.w sprite_24_24
                dc.w $7874
                dc.w $9500 ! ((grp_155080 / 2) & $00FF)
                dc.w $9600 ! (((grp_155080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155080 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $7076
                dc.w $9500 ! ((grp_C61C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C61C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C61C0 / 2) >> 16)
                dc.w 2
