byte_2D624E:    dc.b   0,  8,$6F,$5D,$8E,$8F,$7F,$72,$81,$5F
                                        ; DATA XREF: ROM:off_1224   o
                dc.w sprite_32_24
                dc.w $7260
                dc.w $9500 ! ((grp_129640 / 2) & $00FF)
                dc.w $9600 ! (((grp_129640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7578
                dc.w $9500 ! ((grp_145B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_145B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145B40 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $6A5E
                dc.w $9500 ! ((grp_197E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_197E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7258
                dc.w $9500 ! ((grp_D1A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8258
                dc.w $9500 ! ((grp_D19C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D19C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D19C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $925D
                dc.w $9500 ! ((grp_B8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D88
                dc.w $9500 ! ((grp_EAD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAD40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A50
                dc.w $9500 ! ((grp_EAD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAD80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D88
                dc.w $9500 ! ((grp_EAD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAD60 / 2) >> 16)
                dc.w 1
