byte_2DAC72:    dc.b   0,  6,$6A,$7C,$8F,$92,$9C,$7F,$81,$74
                                        ; DATA XREF: ROM:off_14FC   o
                dc.w sprite_24_24
                dc.w $757A
                dc.w $9500 ! ((grp_144B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_144B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144B80 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $657A
                dc.w $9500 ! ((grp_62100 / 2) & $00FF)
                dc.w $9600 ! (((grp_62100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8D7C
                dc.w $9500 ! ((grp_7D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A72
                dc.w $9500 ! ((grp_CFC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D91
                dc.w $9500 ! ((grp_E9840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6499
                dc.w $9500 ! ((grp_E9860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7592
                dc.w $9500 ! ((grp_E9880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9880 / 2) >> 16)
                dc.w 1
