byte_2CF166:    dc.b   0,  9,$6D,$4D,$9C,$84,$87,$68,$88,$68
                                        ; DATA XREF: ROM:off_B44   o
                dc.w sprite_24_32
                dc.w $6E5B
                dc.w $9500 ! ((grp_FAFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FAFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FAFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $864B
                dc.w $9500 ! ((grp_5C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9663
                dc.w $9500 ! ((grp_5C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6E4B
                dc.w $9500 ! ((grp_156DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_156DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $866B
                dc.w $9500 ! ((grp_170140 / 2) & $00FF)
                dc.w $9600 ! (((grp_170140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170140 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6E7B
                dc.w $9500 ! ((grp_183C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_183C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183C40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6653
                dc.w $9500 ! ((grp_192880 / 2) & $00FF)
                dc.w $9600 ! (((grp_192880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192880 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9653
                dc.w $9500 ! ((grp_B1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E83
                dc.w $9500 ! ((grp_E2B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A666
                dc.w $9500 ! ((grp_E2B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2B60 / 2) >> 16)
                dc.w 1
