byte_2DEB26:    dc.b   0,  7,$6F,$60,$8E,$8F,$82,$70,$83,$66
                                        ; DATA XREF: ROM:off_17A4   o
                dc.w sprite_24_32
                dc.w $7665
                dc.w $9500 ! ((grp_108340 / 2) & $00FF)
                dc.w $9600 ! (((grp_108340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108340 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6E65
                dc.w $9500 ! ((grp_198220 / 2) & $00FF)
                dc.w $9600 ! (((grp_198220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198220 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $785D
                dc.w $9500 ! ((grp_D25C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D25C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D25C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7485
                dc.w $9500 ! ((grp_B91C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B91C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B91C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8485
                dc.w $9500 ! ((grp_B9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E69
                dc.w $9500 ! ((grp_B9240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C89
                dc.w $9500 ! ((grp_EB420 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
