byte_2D8404:    dc.b   0,  8,$72,$5D,$89,$7B,$7C,$6E,$7F,$61
                                        ; DATA XREF: ROM:off_1388   o
                dc.w sprite_24_16
                dc.w $7271
                dc.w $9500 ! ((grp_15A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7759
                dc.w $9500 ! ((grp_173440 / 2) & $00FF)
                dc.w $9600 ! (((grp_173440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6761
                dc.w $9500 ! ((grp_79500 / 2) & $00FF)
                dc.w $9600 ! (((grp_79500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7C81
                dc.w $9500 ! ((grp_79580 / 2) & $00FF)
                dc.w $9600 ! (((grp_79580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8754
                dc.w $9500 ! ((grp_B43C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B43C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B43C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D51
                dc.w $9500 ! ((grp_B4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D59
                dc.w $9500 ! ((grp_E6BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7751
                dc.w $9500 ! ((grp_E6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A79
                dc.w $9500 ! ((grp_E6C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6C20 / 2) >> 16)
                dc.w 1
