byte_2FC34A:    dc.b   0,  1,$63,$87,$71,$8F,$6A,$8B,$6B,$8B
                                        ; DATA XREF: ROM:off_30EC   o
                dc.w sprite_24_8
                dc.w $6385
                dc.w $9500 ! ((grp_190CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190CC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $618D
                dc.w $9500 ! ((grp_DF740 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF740 / 2) >> 16)
                dc.w 2
