byte_2DC3B6:    dc.b   0,  6,$76,$5C,$A4,$90,$8B,$66,$8C,$66
                                        ; DATA XREF: ROM:off_1614   o
                dc.w sprite_32_16
                dc.w $785D
                dc.w $9500 ! ((grp_50B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $8C6D
                dc.w $9500 ! ((grp_18B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9855
                dc.w $9500 ! ((grp_19AC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AC80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6F70
                dc.w $9500 ! ((grp_BD2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $924D
                dc.w $9500 ! ((grp_BD300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A061
                dc.w $9500 ! ((grp_BD340 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $776D
                dc.w $9500 ! ((grp_EE880 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE880 / 2) >> 16)
                dc.w 1
