byte_2CC862:    dc.b   0,  1,$73,$7A,$90,$96,$81,$88,$82,$88
                                        ; DATA XREF: ROM:off_7CC   o
                dc.w sprite_32_24
                dc.w $7178
                dc.w $9500 ! ((grp_11E540 / 2) & $00FF)
                dc.w $9600 ! (((grp_11E540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11E540 / 2) >> 16)
                dc.w    $C
                dc.w sprite_8_16
                dc.w $8B8A
                dc.w $9500 ! ((grp_B0040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0040 / 2) >> 16)
                dc.w     2
