byte_2DF9E4:    dc.b   0,  5,$65,$63,$8F,$8D,$7A,$78,$7F,$68
                                        ; DATA XREF: ROM:off_1840   o
                dc.w sprite_32_24
                dc.w $6B69
                dc.w $9500 ! ((grp_12A6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6B81
                dc.w $9500 ! ((grp_4DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $6369
                dc.w $9500 ! ((grp_A6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F61
                dc.w $9500 ! ((grp_188F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_188F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8B6F
                dc.w $9500 ! ((grp_B94C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B94C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B94C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8B89
                dc.w $9500 ! ((grp_EB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB600 / 2) >> 16)
                dc.w 1
