byte_2D5074:    dc.b   0,  8,$6E,$64,$8E,$8F,$80,$74,$6B,$68
                                        ; DATA XREF: ROM:off_1160   o
                dc.w sprite_16_32
                dc.w $6B59
                dc.w $9500 ! ((grp_5F500 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6D79
                dc.w $9500 ! ((grp_172780 / 2) & $00FF)
                dc.w $9600 ! (((grp_172780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172780 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6361
                dc.w $9500 ! ((grp_194620 / 2) & $00FF)
                dc.w $9600 ! (((grp_194620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7B59
                dc.w $9500 ! ((grp_194680 / 2) & $00FF)
                dc.w $9600 ! (((grp_194680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194680 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8389
                dc.w $9500 ! ((grp_CB4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D69
                dc.w $9500 ! ((grp_CB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E79
                dc.w $9500 ! ((grp_CB480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D7B
                dc.w $9500 ! ((grp_B3840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8659
                dc.w $9500 ! ((grp_B3880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3880 / 2) >> 16)
                dc.w 2
