byte_2CF4CE:    dc.b   0,  6,$61,$68,$9C,$98,$7E,$79,$7F,$79
                                        ; DATA XREF: ROM:off_B64   o
                dc.w sprite_32_32
                dc.w $5F79
                dc.w $9500 ! ((grp_13E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $5F59
                dc.w $9500 ! ((grp_14000 / 2) & $00FF)
                dc.w $9600 ! (((grp_14000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7F59
                dc.w $9500 ! ((grp_FB2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7F79
                dc.w $9500 ! ((grp_13E640 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E640 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $9766
                dc.w $9500 ! ((grp_A3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F91
                dc.w $9500 ! ((grp_C8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B99
                dc.w $9500 ! ((grp_E2C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2C00 / 2) >> 16)
                dc.w 1
