byte_2CD69C:    dc.b   0,  2,$70,$60,$84,$7B,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8F8   o
                dc.w sprite_24_32
                dc.w $6D63
                dc.w $9500 ! ((grp_FA0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6D5B
                dc.w $9500 ! ((grp_183340 / 2) & $00FF)
                dc.w $9600 ! (((grp_183340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183340 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8570
                dc.w $9500 ! ((grp_B0780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0780 / 2) >> 16)
                dc.w 2
