byte_2CD7E8:    dc.b   0,  2,$5F,$4B,$6C,$59,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_918   o
                dc.w sprite_16_24
                dc.w $5D49
                dc.w $9500 ! ((grp_16FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FC00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $784C
                dc.w $9500 ! ((grp_B07C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B07C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B07C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D69
                dc.w $9500 ! ((grp_E1E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1E00 / 2) >> 16)
                dc.w 1
