byte_2D693E:    dc.b   0,  5,$73,$55,$92,$7A,$82,$4E,$8B,$59
                                        ; DATA XREF: ROM:off_126C   o
                dc.w sprite_24_32
                dc.w $734A
                dc.w $9500 ! ((grp_10D2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $8B52
                dc.w $9500 ! ((grp_162AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_162AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6B6A
                dc.w $9500 ! ((grp_9BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5B62
                dc.w $9500 ! ((grp_18AEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AEA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8B62
                dc.w $9500 ! ((grp_D6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B4A
                dc.w $9500 ! ((grp_BC900 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC900 / 2) >> 16)
                dc.w 2
