byte_2F611E:    dc.b   0, $D,$77,$4C,$92,$83,$78,$7E,$79,$7E
                                        ; DATA XREF: ROM:off_2B3C   o
                dc.w sprite_32_32
                dc.w $6C46
                dc.w $9500 ! ((grp_3D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7466
                dc.w $9500 ! ((grp_1168C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1168C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1168C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $9437
                dc.w $9500 ! ((grp_118240 / 2) & $00FF)
                dc.w $9600 ! (((grp_118240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118240 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $644E
                dc.w $9500 ! ((grp_AD100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C56
                dc.w $9500 ! ((grp_AD200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $AC3E
                dc.w $9500 ! ((grp_AD580 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $945F
                dc.w $9500 ! ((grp_18EDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EDA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9C57
                dc.w $9500 ! ((grp_DD040 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C66
                dc.w $9500 ! ((grp_C2240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C3E
                dc.w $9500 ! ((grp_C2880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C4E
                dc.w $9500 ! ((grp_F4AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9470
                dc.w $9500 ! ((grp_F4A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9457
                dc.w $9500 ! ((grp_F4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AC36
                dc.w $9500 ! ((grp_F4EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4EE0 / 2) >> 16)
                dc.w 1
