byte_2F3968:    dc.b   0,  6,$6C,$5D,$95,$8E,$77,$77,$78,$77
                                        ; DATA XREF: ROM:off_27E0   o
                dc.w sprite_32_24
                dc.w $685B
                dc.w $9500 ! ((grp_135F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_135F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7873
                dc.w $9500 ! ((grp_6D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5067
                dc.w $9500 ! ((grp_167500 / 2) & $00FF)
                dc.w $9600 ! (((grp_167500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $886F
                dc.w $9500 ! ((grp_17DB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DB80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8887
                dc.w $9500 ! ((grp_C0C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8867
                dc.w $9500 ! ((grp_F2B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $987F
                dc.w $9500 ! ((grp_F2B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2B40 / 2) >> 16)
                dc.w 1
