byte_2DA758:    dc.b   0,  7,$6F,$5B,$8E,$8F,$80,$73,$7F,$5F
                                        ; DATA XREF: ROM:off_14B0   o
                dc.w sprite_24_24
                dc.w $6D60
                dc.w $9500 ! ((grp_144940 / 2) & $00FF)
                dc.w $9600 ! (((grp_144940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144940 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $8568
                dc.w $9500 ! ((grp_7D580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F78
                dc.w $9500 ! ((grp_1873C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1873C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1873C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_187420 / 2) & $00FF)
                dc.w $9600 ! (((grp_187420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F88
                dc.w $9500 ! ((grp_CF900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7458
                dc.w $9500 ! ((grp_CF940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8488
                dc.w $9500 ! ((grp_CF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8560
                dc.w $9500 ! ((grp_E95E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E95E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E95E0 / 2) >> 16)
                dc.w 1
