byte_2D044C:    dc.b   0,  2,$70,$70,$8B,$8F,$7D,$7F,$7E,$7F
                                        ; DATA XREF: ROM:off_D20   o
                dc.w sprite_24_24
                dc.w $777F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6F
                dc.w $9500 ! ((grp_46F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $7A67
                dc.w $9500 ! ((grp_E31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E31C0 / 2) >> 16)
                dc.w 1
