byte_2E3712:    dc.b   0,  5,$6E,$69,$A0,$8F,$87,$7C,$88,$7C
                                        ; DATA XREF: ROM:off_1AC4   o
                dc.w sprite_24_32
                dc.w $7A69
                dc.w $9500 ! ((grp_10E040 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6D88
                dc.w $9500 ! ((grp_9BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9267
                dc.w $9500 ! ((grp_D6A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C8D
                dc.w $9500 ! ((grp_EE8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE8E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $926F
                dc.w $9500 ! ((grp_EE900 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A16E
                dc.w $9500 ! ((grp_EE920 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE920 / 2) >> 16)
                dc.w 1
