byte_2D0134:    dc.b   0,  1,$7B,$7F,$88,$8F,$81,$87,$82,$87
                                        ; DATA XREF: ROM:off_CD8   o
                dc.w sprite_24_24
                dc.w $797F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7A77
                dc.w $9500 ! ((grp_C8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B00 / 2) >> 16)
                dc.w 2
