byte_2D6026:    dc.b   0,  5,$6F,$63,$8E,$8F,$80,$76,$82,$68
                                        ; DATA XREF: ROM:off_120C   o
                dc.w sprite_24_32
                dc.w $716D
                dc.w $9500 ! ((grp_106E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_106E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $785D
                dc.w $9500 ! ((grp_80180 / 2) & $00FF)
                dc.w $9600 ! (((grp_80180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_D1AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8688
                dc.w $9500 ! ((grp_D1B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $696E
                dc.w $9500 ! ((grp_B8D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $896D
                dc.w $9500 ! ((grp_B8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8D80 / 2) >> 16)
                dc.w 2
