byte_2D1CA8:    dc.b   0, $A,$75,$6A,$9B,$8F,$84,$7B,$85,$7B
                                        ; DATA XREF: ROM:off_E60   o
                dc.w sprite_32_16
                dc.w $7478
                dc.w $9500 ! ((grp_48200 / 2) & $00FF)
                dc.w $9600 ! (((grp_48200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7D68
                dc.w $9500 ! ((grp_158740 / 2) & $00FF)
                dc.w $9600 ! (((grp_158740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $AD63
                dc.w $9500 ! ((grp_76900 / 2) & $00FF)
                dc.w $9600 ! (((grp_76900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9D62
                dc.w $9500 ! ((grp_1933C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1933C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1933C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8588
                dc.w $9500 ! ((grp_C9900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9480
                dc.w $9500 ! ((grp_C9940 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C78
                dc.w $9500 ! ((grp_B2140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9567
                dc.w $9500 ! ((grp_B2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A562
                dc.w $9500 ! ((grp_B21C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B21C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B21C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9E85
                dc.w $9500 ! ((grp_E3E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BD6A
                dc.w $9500 ! ((grp_E3E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3E40 / 2) >> 16)
                dc.w 1
