byte_2E122C:    dc.b   0, $C,$72,$5A,$8E,$8E,$81,$41,$76,$2A
                                        ; DATA XREF: ROM:off_1930   o
                dc.w sprite_24_16
                dc.w $6739
                dc.w $9500 ! ((grp_15BEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $6729
                dc.w $9500 ! ((grp_15BF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BF80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8747
                dc.w $9500 ! ((grp_15BD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BD40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7F31
                dc.w $9500 ! ((grp_A5200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7749
                dc.w $9500 ! ((grp_195AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6759
                dc.w $9500 ! ((grp_CD440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E21
                dc.w $9500 ! ((grp_B5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8731
                dc.w $9500 ! ((grp_B53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B53C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F3E
                dc.w $9500 ! ((grp_E7B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5F29
                dc.w $9500 ! ((grp_E7BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7661
                dc.w $9500 ! ((grp_E5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F31
                dc.w $9500 ! ((grp_E7A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9957
                dc.w $9500 ! ((grp_E5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5860 / 2) >> 16)
                dc.w 1
