byte_2F4E5A:    dc.b   0,  7,$70,$63,$96,$8E,$91,$79,$92,$79
                                        ; DATA XREF: ROM:off_2A24   o
                dc.w sprite_32_32
                dc.w $7166
                dc.w $9500 ! ((grp_3B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3B800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7486
                dc.w $9500 ! ((grp_56000 / 2) & $00FF)
                dc.w $9600 ! (((grp_56000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6E7B
                dc.w $9500 ! ((grp_19E5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E5E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $805E
                dc.w $9500 ! ((grp_DC800 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $916B
                dc.w $9500 ! ((grp_DC7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9B69
                dc.w $9500 ! ((grp_DC840 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AB65
                dc.w $9500 ! ((grp_C1A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $B368
                dc.w $9500 ! ((grp_F4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4300 / 2) >> 16)
                dc.w 1
