byte_2D04D6:    dc.b   0,  3,$78,$6F,$8F,$8B,$83,$7D,$84,$7D
                                        ; DATA XREF: ROM:off_D2C   o
                dc.w sprite_16_16
                dc.w $766D
                dc.w $9500 ! ((grp_75A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C7D
                dc.w $9500 ! ((grp_C8C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C85
                dc.w $9500 ! ((grp_E3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C80
                dc.w $9500 ! ((grp_E3420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3420 / 2) >> 16)
                dc.w 1
