byte_2F76DC:    dc.b   0, $B,$64,$42,$9E,$83,$87,$60,$88,$60
                                        ; DATA XREF: ROM:off_2BA0   o
                dc.w sprite_24_32
                dc.w $6E4C
                dc.w $9500 ! ((grp_1189C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1189C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1189C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $864C
                dc.w $9500 ! ((grp_118B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_118B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $726C
                dc.w $9500 ! ((grp_137D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_137D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $723C
                dc.w $9500 ! ((grp_56D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $A149
                dc.w $9500 ! ((grp_18F4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F4C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5E4F
                dc.w $9500 ! ((grp_DD900 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7784
                dc.w $9500 ! ((grp_DD8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9247
                dc.w $9500 ! ((grp_DD980 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A651
                dc.w $9500 ! ((grp_DD940 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C57
                dc.w $9500 ! ((grp_C3240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $545D
                dc.w $9500 ! ((grp_F5CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A44
                dc.w $9500 ! ((grp_F5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5C80 / 2) >> 16)
                dc.w 1
