byte_2E329C:    dc.b   0,  7,$70,$64,$80,$6D,$7D,$72,$7B,$75
                                        ; DATA XREF: ROM:off_1A98   o
                dc.w sprite_24_16
                dc.w $6F86
                dc.w $9500 ! ((grp_15E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E380 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7076
                dc.w $9500 ! ((grp_15E440 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6656
                dc.w $9500 ! ((grp_7E680 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6966
                dc.w $9500 ! ((grp_7E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7966
                dc.w $9500 ! ((grp_7E580 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $878B
                dc.w $9500 ! ((grp_D04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D04C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $684E
                dc.w $9500 ! ((grp_E9C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $896C
                dc.w $9500 ! ((grp_E9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C40 / 2) >> 16)
                dc.w 1
