byte_2F2EA4:    dc.b   0,  5,$72,$59,$92,$8A,$85,$74,$86,$74
                                        ; DATA XREF: ROM:off_2778   o
                dc.w sprite_24_24
                dc.w $716A
                dc.w $9500 ! ((grp_1500A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1500A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1500A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $8972
                dc.w $9500 ! ((grp_1501C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1501C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1501C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6A5A
                dc.w $9500 ! ((grp_55A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7B82
                dc.w $9500 ! ((grp_8D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7282
                dc.w $9500 ! ((grp_F3340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8252
                dc.w $9500 ! ((grp_F3320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3320 / 2) >> 16)
                dc.w 1
