byte_2CC6C4:    dc.b   0,  2,$73,$61,$88,$72,$7B,$69,$7C,$69
                                        ; DATA XREF: ROM:off_7A8   o
                dc.w sprite_16_24
                dc.w $765D
                dc.w $9500 ! ((grp_16F480 / 2) & $00FF)
                dc.w $9600 ! (((grp_16F480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16F480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8662
                dc.w $9500 ! ((grp_B0000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E6C
                dc.w $9500 ! ((grp_E13E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E13E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E13E0 / 2) >> 16)
                dc.w 1
