byte_2D963E:    dc.b   0,  5,$67,$69,$99,$8E,$80,$7B,$81,$7B
                                        ; DATA XREF: ROM:off_1434   o
                dc.w sprite_32_24
                dc.w $6D6B
                dc.w $9500 ! ((grp_1273C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1273C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1273C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7183
                dc.w $9500 ! ((grp_4B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7563
                dc.w $9500 ! ((grp_187000 / 2) & $00FF)
                dc.w $9600 ! (((grp_187000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187000 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8D79
                dc.w $9500 ! ((grp_CEBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $656F
                dc.w $9500 ! ((grp_B6900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D71
                dc.w $9500 ! ((grp_E8D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D00 / 2) >> 16)
                dc.w 1
