byte_2E3B9C:    dc.b   0, $A,$62,$67,$9A,$7A,$CE,$47,$CF,$41
                                        ; DATA XREF: ROM:off_1AF8   o
                dc.w sprite_32_16
                dc.w $6466
                dc.w $9500 ! ((grp_4A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8465
                dc.w $9500 ! ((grp_174040 / 2) & $00FF)
                dc.w $9600 ! (((grp_174040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174040 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $C43E
                dc.w $9500 ! ((grp_7B480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9856
                dc.w $9500 ! ((grp_1863A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1863A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1863A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9466
                dc.w $9500 ! ((grp_195DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195DC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $945E
                dc.w $9500 ! ((grp_CD880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AC4F
                dc.w $9500 ! ((grp_CD8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C6C
                dc.w $9500 ! ((grp_B57C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B57C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B57C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6676
                dc.w $9500 ! ((grp_E7FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C5D
                dc.w $9500 ! ((grp_E8000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BC4A
                dc.w $9500 ! ((grp_E8020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8020 / 2) >> 16)
                dc.w 1
