byte_2D746C:    dc.b   0,  6,$74,$63,$85,$78,$82,$6C,$79,$5C
                                        ; DATA XREF: ROM:off_12D8   o
                dc.w sprite_16_32
                dc.w $744C
                dc.w $9500 ! ((grp_65000 / 2) & $00FF)
                dc.w $9600 ! (((grp_65000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $746C
                dc.w $9500 ! ((grp_84280 / 2) & $00FF)
                dc.w $9600 ! (((grp_84280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6C56
                dc.w $9500 ! ((grp_A7E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B7C
                dc.w $9500 ! ((grp_1997E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1997E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1997E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8457
                dc.w $9500 ! ((grp_199840 / 2) & $00FF)
                dc.w $9600 ! (((grp_199840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199840 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6467
                dc.w $9500 ! ((grp_BB4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $838A
                dc.w $9500 ! ((grp_ECF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECF60 / 2) >> 16)
                dc.w 1
