byte_2E75C2:    dc.b   0,  3,$6F,$63,$8E,$8F,$7F,$6A,$80,$76
                                        ; DATA XREF: ROM:off_1CE4   o
                dc.w sprite_24_32
                dc.w $7268
                dc.w $9500 ! ((grp_10B040 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B040 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6A6B
                dc.w $9500 ! ((grp_199420 / 2) & $00FF)
                dc.w $9600 ! (((grp_199420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199420 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_D41C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D41C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D41C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_D4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4200 / 2) >> 16)
                dc.w 2
