byte_2E76C4:    dc.b   0,  6,$6F,$6B,$8E,$8F,$B7,$92,$9E,$6D
                                        ; DATA XREF: ROM:off_1CF0   o
                dc.w sprite_24_32
                dc.w $7672
                dc.w $9500 ! ((grp_105340 / 2) & $00FF)
                dc.w $9600 ! (((grp_105340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8E68
                dc.w $9500 ! ((grp_145360 / 2) & $00FF)
                dc.w $9600 ! (((grp_145360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145360 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6E67
                dc.w $9500 ! ((grp_99A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_99A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8E80
                dc.w $9500 ! ((grp_B7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A66E
                dc.w $9500 ! ((grp_B7F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686C
                dc.w $9500 ! ((grp_EA1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA1E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_EA200 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA200 / 2) >> 16)
                dc.w 1
