byte_2CE7A4:    dc.b   0,  6,$75,  2,$82,$7F,$7B,$40,$7C,$40
                                        ; DATA XREF: ROM:off_AE8   o
                dc.w sprite_8_32
                dc.w $7556
                dc.w $9500 ! ((grp_A2800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C0F
                dc.w $9500 ! ((grp_A2880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7C2F
                dc.w $9500 ! ((grp_1924C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1924C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1924C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7403
                dc.w $9500 ! ((grp_B10C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B10C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B10C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7746
                dc.w $9500 ! ((grp_B1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7871
                dc.w $9500 ! ((grp_B1140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7200
                dc.w $9500 ! ((grp_E26E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E26E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E26E0 / 2) >> 16)
                dc.w 1
