byte_2FE838:    dc.b   0,  3,$6F,$83,$90,$8F,$7F,$87,$80,$87
                                        ; DATA XREF: ROM:off_3438   o
                dc.w sprite_32_16
                dc.w $6D82
                dc.w $9500 ! ((grp_59E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_59E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $6C7A
                dc.w $9500 ! ((grp_E06C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E06C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E06C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $857A
                dc.w $9500 ! ((grp_F8D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D85
                dc.w $9500 ! ((grp_F8D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8D40 / 2) >> 16)
                dc.w 1
