byte_2FF11C:    dc.b   0,  2,$80,$77,$90,$95,$87,$86,$88,$86
                                        ; DATA XREF: ROM:off_3548   o
                dc.w sprite_24_24
                dc.w $7A77
                dc.w $9500 ! ((grp_155860 / 2) & $00FF)
                dc.w $9600 ! (((grp_155860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155860 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $786F
                dc.w $9500 ! ((grp_191980 / 2) & $00FF)
                dc.w $9600 ! (((grp_191980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191980 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B8F
                dc.w $9500 ! ((grp_E0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0E80 / 2) >> 16)
                dc.w 2
