byte_2DE456:    dc.b   0, $C,$74,$60,$90,$8F,$85,$70,$87,$60
                                        ; DATA XREF: ROM:off_1764   o
                dc.w sprite_24_24
                dc.w $7878
                dc.w $9500 ! ((grp_147D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_147D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147D00 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $8058
                dc.w $9500 ! ((grp_65400 / 2) & $00FF)
                dc.w $9600 ! (((grp_65400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6870
                dc.w $9500 ! ((grp_84980 / 2) & $00FF)
                dc.w $9600 ! (((grp_84980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C90
                dc.w $9500 ! ((grp_D4F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9073
                dc.w $9500 ! ((grp_D4F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7868
                dc.w $9500 ! ((grp_BB780 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6073
                dc.w $9500 ! ((grp_ED420 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7068
                dc.w $9500 ! ((grp_ED440 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7088
                dc.w $9500 ! ((grp_ED460 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8550
                dc.w $9500 ! ((grp_ED480 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9058
                dc.w $9500 ! ((grp_ED4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED4A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9088
                dc.w $9500 ! ((grp_ED4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED4C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A070
                dc.w $9500 ! ((grp_ED4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED4E0 / 2) >> 16)
                dc.w 1
