byte_2FE9EA:    dc.b   0,  2,$75,$84,$8C,$8E,$80,$85,$81,$85
                                        ; DATA XREF: ROM:off_3464   o
                dc.w sprite_24_16
                dc.w $7981
                dc.w $9500 ! ((grp_16DEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7187
                dc.w $9500 ! ((grp_F8EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E79
                dc.w $9500 ! ((grp_F8F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8F00 / 2) >> 16)
                dc.w 1
