byte_2EB084:    dc.b   0,  3,$7F,$5E,$98,$70,$86,$65,$87,$65
                                        ; DATA XREF: ROM:off_1FD8   o
                dc.w sprite_32_24
                dc.w $725D
                dc.w $9500 ! ((grp_131140 / 2) & $00FF)
                dc.w $9600 ! (((grp_131140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_131140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C55
                dc.w $9500 ! ((grp_18BDA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BDA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BDA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9265
                dc.w $9500 ! ((grp_BDFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A69
                dc.w $9500 ! ((grp_EF2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF2C0 / 2) >> 16)
                dc.w 1
