byte_2D1DFC:    dc.b   0,  5,$71,$5A,$90,$8E,$81,$73,$82,$73
                                        ; DATA XREF: ROM:off_E70   o
                dc.w sprite_24_32
                dc.w $7860
                dc.w $9500 ! ((grp_FC940 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC940 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6788
                dc.w $9500 ! ((grp_97880 / 2) & $00FF)
                dc.w $9600 ! (((grp_97880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9058
                dc.w $9500 ! ((grp_A3E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7380
                dc.w $9500 ! ((grp_C99C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C99C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C99C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F58
                dc.w $9500 ! ((grp_C9A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9858
                dc.w $9500 ! ((grp_E3F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3F00 / 2) >> 16)
                dc.w 1
