byte_2ED926:    dc.b   0,  5,$67,$61,$92,$95,$7A,$78,$7B,$78
                                        ; DATA XREF: ROM:off_22DC   o
                dc.w sprite_32_24
                dc.w $6768
                dc.w $9500 ! ((grp_1324C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1324C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1324C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6B80
                dc.w $9500 ! ((grp_52500 / 2) & $00FF)
                dc.w $9600 ! (((grp_52500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52500 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6760
                dc.w $9500 ! ((grp_9DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5F68
                dc.w $9500 ! ((grp_19C960 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C960 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6388
                dc.w $9500 ! ((grp_F0360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B88
                dc.w $9500 ! ((grp_F0380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0380 / 2) >> 16)
                dc.w 1
