byte_2CCD8E:    dc.b   0,  4,$7A,$62,$84,$9D,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_824   o
                dc.w sprite_16_32
                dc.w $7878
                dc.w $9500 ! ((grp_5BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5BB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7860
                dc.w $9500 ! ((grp_C6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7870
                dc.w $9500 ! ((grp_C6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7868
                dc.w $9500 ! ((grp_C6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7898
                dc.w $9500 ! ((grp_C6FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6FC0 / 2) >> 16)
                dc.w 2
