byte_2E4C8E:    dc.b   0,  9,$6E,$67,$8A,$8E,$4A,$98,$7D,$67
                                        ; DATA XREF: ROM:off_1B7C   o
                dc.w sprite_32_16
                dc.w $7171
                dc.w $9500 ! ((grp_4F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6E81
                dc.w $9500 ! ((grp_1606C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1606C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1606C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7069
                dc.w $9500 ! ((grp_189940 / 2) & $00FF)
                dc.w $9600 ! (((grp_189940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6971
                dc.w $9500 ! ((grp_198F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_198F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198F40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7261
                dc.w $9500 ! ((grp_D3500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8689
                dc.w $9500 ! ((grp_D3540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9177
                dc.w $9500 ! ((grp_D3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6176
                dc.w $9500 ! ((grp_EC2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC2A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7859
                dc.w $9500 ! ((grp_EC2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC2C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A7F
                dc.w $9500 ! ((grp_EC2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC2E0 / 2) >> 16)
                dc.w 1
