byte_2D1F38:    dc.b   0,  5,$6F,$61,$89,$8E,$78,$74,$79,$74
                                        ; DATA XREF: ROM:off_E80   o
                dc.w sprite_24_32
                dc.w $726A
                dc.w $9500 ! ((grp_FCC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FCC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FCC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $725A
                dc.w $9500 ! ((grp_76A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8779
                dc.w $9500 ! ((grp_193480 / 2) & $00FF)
                dc.w $9600 ! (((grp_193480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193480 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6A5B
                dc.w $9500 ! ((grp_B2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6260
                dc.w $9500 ! ((grp_E3FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $825A
                dc.w $9500 ! ((grp_E4000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4000 / 2) >> 16)
                dc.w 1
