byte_2FDFA4:    dc.b   0,  8,$72,$47,$95,$8D,$83,$6A,$84,$6A
                                        ; DATA XREF: ROM:off_3360   o
                dc.w sprite_16_16
                dc.w $7278
                dc.w $9500 ! ((grp_95880 / 2) & $00FF)
                dc.w $9600 ! (((grp_95880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A88
                dc.w $9500 ! ((grp_A1400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1400 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7045
                dc.w $9500 ! ((grp_A1380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7E61
                dc.w $9500 ! ((grp_1A0800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0800 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8657
                dc.w $9500 ! ((grp_1A0860 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9044
                dc.w $9500 ! ((grp_1A08C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A08C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A08C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7668
                dc.w $9500 ! ((grp_C5F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E57
                dc.w $9500 ! ((grp_C5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $884D
                dc.w $9500 ! ((grp_F8740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8740 / 2) >> 16)
                dc.w 1
