byte_2D7670:    dc.b   0,  5,$77,$65,$8F,$99,$78,$73,$7F,$68
                                        ; DATA XREF: ROM:off_12F0   o
                dc.w sprite_24_32
                dc.w $766A
                dc.w $9500 ! ((grp_FFAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FFAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FFAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $5E76
                dc.w $9500 ! ((grp_15A480 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8E72
                dc.w $9500 ! ((grp_194AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194AA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7662
                dc.w $9500 ! ((grp_CC100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E6E
                dc.w $9500 ! ((grp_E65A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E65A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E65A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B5A
                dc.w $9500 ! ((grp_E65C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E65C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E65C0 / 2) >> 16)
                dc.w 1
