byte_2E711A:    dc.b   0, $A,$6F,$63,$8E,$8F,$78,$6A,$65,$62
                                        ; DATA XREF: ROM:off_1CBC   o
                dc.w sprite_24_16
                dc.w $635B
                dc.w $9500 ! ((grp_161440 / 2) & $00FF)
                dc.w $9600 ! (((grp_161440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7373
                dc.w $9500 ! ((grp_178600 / 2) & $00FF)
                dc.w $9600 ! (((grp_178600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $636B
                dc.w $9500 ! ((grp_83A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7B63
                dc.w $9500 ! ((grp_83A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B65
                dc.w $9500 ! ((grp_83B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_D4240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B60
                dc.w $9500 ! ((grp_BB080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8380
                dc.w $9500 ! ((grp_BAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $736B
                dc.w $9500 ! ((grp_ECC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECC20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B8B
                dc.w $9500 ! ((grp_ECB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B6C
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
