byte_2DFECC:    dc.b   0,  6,$63,$5A,$9C,$8E,$7F,$74,$8D,$61
                                        ; DATA XREF: ROM:off_1878   o
                dc.w sprite_32_32
                dc.w $7759
                dc.w $9500 ! ((grp_20000 / 2) & $00FF)
                dc.w $9600 ! (((grp_20000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6160
                dc.w $9500 ! ((grp_15FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FA00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7779
                dc.w $9500 ! ((grp_15FAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FAC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6D89
                dc.w $9500 ! ((grp_9A680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9758
                dc.w $9500 ! ((grp_A6F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6F81
                dc.w $9500 ! ((grp_EB840 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D89
                dc.w $9500 ! ((grp_EB860 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB860 / 2) >> 16)
                dc.w 1
