byte_2CD47A:    dc.b   0,  1,$97,$6D,$A7,$7B,$8C,$95,$8D,$95
                                        ; DATA XREF: ROM:off_8BC   o
                dc.w sprite_16_24
                dc.w $9A66
                dc.w $9500 ! ((grp_16FB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FB40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $926B
                dc.w $9500 ! ((grp_B0600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0600 / 2) >> 16)
                dc.w 2
