byte_2E18CE:    dc.b   0,  5,$79,$63,$94,$8E,$86,$75,$76,$63
                                        ; DATA XREF: ROM:off_196C   o
                dc.w sprite_24_32
                dc.w $7662
                dc.w $9500 ! ((grp_1099C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1099C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1099C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7582
                dc.w $9500 ! ((grp_160240 / 2) & $00FF)
                dc.w $9600 ! (((grp_160240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8E62
                dc.w $9500 ! ((grp_81B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_81B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6E5A
                dc.w $9500 ! ((grp_A7900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $765A
                dc.w $9500 ! ((grp_EBE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBE20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E72
                dc.w $9500 ! ((grp_EBE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBE40 / 2) >> 16)
                dc.w 1
