byte_2EB14A:    dc.b   0,  4,$86,$51,$96,$61,$86,$5B,$87,$5B
                                        ; DATA XREF: ROM:off_1FE4   o
                dc.w sprite_24_24
                dc.w $864E
                dc.w $9500 ! ((grp_14A100 / 2) & $00FF)
                dc.w $9600 ! (((grp_14A100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14A100 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7656
                dc.w $9500 ! ((grp_87400 / 2) & $00FF)
                dc.w $9600 ! (((grp_87400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8066
                dc.w $9500 ! ((grp_D7840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E56
                dc.w $9500 ! ((grp_EF360 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9766
                dc.w $9500 ! ((grp_EF380 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF380 / 2) >> 16)
                dc.w 1
