byte_2F1762:    dc.b   0,  3,$6A,$68,$8A,$8B,$7A,$79,$7B,$79
                                        ; DATA XREF: ROM:off_2674   o
                dc.w sprite_24_32
                dc.w $6F66
                dc.w $9500 ! ((grp_114340 / 2) & $00FF)
                dc.w $9600 ! (((grp_114340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114340 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $876D
                dc.w $9500 ! ((grp_C0A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $676B
                dc.w $9500 ! ((grp_F28A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F28A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F28A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7286
                dc.w $9500 ! ((grp_F28C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F28C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F28C0 / 2) >> 16)
                dc.w 1
