byte_2ECEBA:    dc.b   0,  2,$74,$79,$A3,$89,$8B,$81,$8C,$81
                                        ; DATA XREF: ROM:off_223C   o
                dc.w sprite_24_16
                dc.w $727C
                dc.w $9500 ! ((grp_163E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_163E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $8A7F
                dc.w $9500 ! ((grp_9D680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7B77
                dc.w $9500 ! ((grp_18C5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C5E0 / 2) >> 16)
                dc.w 3
