byte_2D0C1E:    dc.b   0, $D,$42,$63,$6D,$8D,$60,$76,$61,$76
                                        ; DATA XREF: ROM:off_DCC   o
                dc.w sprite_24_32
                dc.w $5969
                dc.w $9500 ! ((grp_FBA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FBA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FBA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $715D
                dc.w $9500 ! ((grp_47300 / 2) & $00FF)
                dc.w $9600 ! (((grp_47300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $296E
                dc.w $9500 ! ((grp_170EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_170EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $396F
                dc.w $9500 ! ((grp_170F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_170F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4963
                dc.w $9500 ! ((grp_75E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_75E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $4973
                dc.w $9500 ! ((grp_75F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5961
                dc.w $9500 ! ((grp_184180 / 2) & $00FF)
                dc.w $9600 ! (((grp_184180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184180 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $3967
                dc.w $9500 ! ((grp_C8FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6289
                dc.w $9500 ! ((grp_C8E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $717C
                dc.w $9500 ! ((grp_C8EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $915D
                dc.w $9500 ! ((grp_B19C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B19C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B19C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4983
                dc.w $9500 ! ((grp_E3680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $716D
                dc.w $9500 ! ((grp_E3620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7574
                dc.w $9500 ! ((grp_E3640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3640 / 2) >> 16)
                dc.w 1
