byte_2D5B26:    dc.b   0,  6,$62,$5F,$89,$8A,$79,$74,$7B,$6D
                                        ; DATA XREF: ROM:off_11D4   o
                dc.w sprite_16_32
                dc.w $646A
                dc.w $9500 ! ((grp_5F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $747F
                dc.w $9500 ! ((grp_15A240 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $635A
                dc.w $9500 ! ((grp_78880 / 2) & $00FF)
                dc.w $9600 ! (((grp_78880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5C6D
                dc.w $9500 ! ((grp_1948C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1948C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1948C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $847A
                dc.w $9500 ! ((grp_CBD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7466
                dc.w $9500 ! ((grp_B3B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5E
                dc.w $9500 ! ((grp_B3B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3B80 / 2) >> 16)
                dc.w 2
