byte_2FE872:    dc.b   0,  3,$6A,$82,$97,$8E,$80,$85,$81,$85
                                        ; DATA XREF: ROM:off_343C   o
                dc.w sprite_24_24
                dc.w $8279
                dc.w $9500 ! ((grp_1553E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1553E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1553E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $627A
                dc.w $9500 ! ((grp_59F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_59F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $728A
                dc.w $9500 ! ((grp_E0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9988
                dc.w $9500 ! ((grp_F8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8D80 / 2) >> 16)
                dc.w 1
