byte_2D6774:    dc.b   0,  5,$71,$48,$9B,$80,$86,$64,$87,$64
                                        ; DATA XREF: ROM:off_1258   o
                dc.w sprite_32_32
                dc.w $704E
                dc.w $9500 ! ((grp_24800 / 2) & $00FF)
                dc.w $9600 ! (((grp_24800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $806E
                dc.w $9500 ! ((grp_147520 / 2) & $00FF)
                dc.w $9600 ! (((grp_147520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147520 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7846
                dc.w $9500 ! ((grp_18A060 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A060 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9056
                dc.w $9500 ! ((grp_1994E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1994E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1994E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F6E
                dc.w $9500 ! ((grp_D46C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D46C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D46C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $986A
                dc.w $9500 ! ((grp_BB200 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB200 / 2) >> 16)
                dc.w 2
