byte_2F0968:    dc.b   0,$12,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_2600   o
                dc.w sprite_32_32
                dc.w $6553
                dc.w $9500 ! ((grp_34E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D7B
                dc.w $9500 ! ((grp_34C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5D7B
                dc.w $9500 ! ((grp_112E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_112E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7563
                dc.w $9500 ! ((grp_14D4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D4C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_166600 / 2) & $00FF)
                dc.w $9600 ! (((grp_166600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166600 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D53
                dc.w $9500 ! ((grp_8B980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B980 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D4B
                dc.w $9500 ! ((grp_9E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5D5B
                dc.w $9500 ! ((grp_ABE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9D7B
                dc.w $9500 ! ((grp_ABE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6573
                dc.w $9500 ! ((grp_DA500 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D63
                dc.w $9500 ! ((grp_DA4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8553
                dc.w $9500 ! ((grp_BFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D5B
                dc.w $9500 ! ((grp_BFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D50
                dc.w $9500 ! ((grp_F16C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F16C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F16C0 / 2) >> 16)
                dc.w 1
