byte_2E1D78:    dc.b   0,  2,$78,$76,$97,$88,$87,$7F,$88,$7F
                                        ; DATA XREF: ROM:off_19A8   o
                dc.w sprite_32_16
                dc.w $7679
                dc.w $9500 ! ((grp_4BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4BF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $9575
                dc.w $9500 ! ((grp_B7500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E89
                dc.w $9500 ! ((grp_E9BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9BE0 / 2) >> 16)
                dc.w 1
