byte_2D0A9A:    dc.b   0,  4,$71,$7B,$96,$8D,$83,$84,$84,$84
                                        ; DATA XREF: ROM:off_DBC   o
                dc.w sprite_24_16
                dc.w $7680
                dc.w $9500 ! ((grp_158440 / 2) & $00FF)
                dc.w $9600 ! (((grp_158440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7978
                dc.w $9500 ! ((grp_C9700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E7E
                dc.w $9500 ! ((grp_C9740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E84
                dc.w $9500 ! ((grp_E3C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9186
                dc.w $9500 ! ((grp_E3C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C20 / 2) >> 16)
                dc.w 1
