byte_2D3B04:    dc.b   0,  7,$75,$69,$9A,$8A,$8E,$7A,$8F,$7A
                                        ; DATA XREF: ROM:off_1060   o
                dc.w sprite_16_32
                dc.w $8772
                dc.w $9500 ! ((grp_5E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8062
                dc.w $9500 ! ((grp_77000 / 2) & $00FF)
                dc.w $9600 ! (((grp_77000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9788
                dc.w $9500 ! ((grp_1847E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1847E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1847E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7F72
                dc.w $9500 ! ((grp_193C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_193C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $706B
                dc.w $9500 ! ((grp_CA180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA180 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9780
                dc.w $9500 ! ((grp_CA1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7063
                dc.w $9500 ! ((grp_E4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $777F
                dc.w $9500 ! ((grp_E48A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E48A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E48A0 / 2) >> 16)
                dc.w 1
