byte_2D5C34:    dc.b   0,  7,$78,$5E,$90,$A1,$8C,$83,$82,$6B
                                        ; DATA XREF: ROM:off_11E0   o
                dc.w sprite_24_24
                dc.w $7774
                dc.w $9500 ! ((grp_141580 / 2) & $00FF)
                dc.w $9600 ! (((grp_141580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141580 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $798C
                dc.w $9500 ! ((grp_5F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $7D5D
                dc.w $9500 ! ((grp_194980 / 2) & $00FF)
                dc.w $9600 ! (((grp_194980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194980 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $976D
                dc.w $9500 ! ((grp_B3C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F6A
                dc.w $9500 ! ((grp_B3C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F78
                dc.w $9500 ! ((grp_E6320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7194
                dc.w $9500 ! ((grp_E6340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F76
                dc.w $9500 ! ((grp_E6360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6360 / 2) >> 16)
                dc.w 1
