byte_2EA2A0:    dc.b   0,  5,$69,$63,$97,$8B,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F20   o
                dc.w sprite_32_32
                dc.w $6769
                dc.w $9500 ! ((grp_28A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_28A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8769
                dc.w $9500 ! ((grp_67400 / 2) & $00FF)
                dc.w $9600 ! (((grp_67400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7C61
                dc.w $9500 ! ((grp_18B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B800 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7C89
                dc.w $9500 ! ((grp_18B860 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C89
                dc.w $9500 ! ((grp_EEF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEF20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9771
                dc.w $9500 ! ((grp_EEF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEF40 / 2) >> 16)
                dc.w 1
