byte_2F9A60:    dc.b   0,  3,$5C,$86,$A9,$8F,$82,$8A,$83,$8A
                                        ; DATA XREF: ROM:off_2DB8   o
                dc.w sprite_32_16
                dc.w $7084
                dc.w $9500 ! ((grp_57400 / 2) & $00FF)
                dc.w $9600 ! (((grp_57400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9084
                dc.w $9500 ! ((grp_91380 / 2) & $00FF)
                dc.w $9600 ! (((grp_91380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5889
                dc.w $9500 ! ((grp_190180 / 2) & $00FF)
                dc.w $9600 ! (((grp_190180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190180 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $A08A
                dc.w $9500 ! ((grp_DE700 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE700 / 2) >> 16)
                dc.w 2
