byte_2EC14C:    dc.b   0,  3,$6B,$84,$95,$8E,$80,$89,$81,$89
                                        ; DATA XREF: ROM:off_20B0   o
                dc.w sprite_32_16
                dc.w $7482
                dc.w $9500 ! ((grp_51900 / 2) & $00FF)
                dc.w $9600 ! (((grp_51900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $6C82
                dc.w $9500 ! ((grp_BE3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6487
                dc.w $9500 ! ((grp_EF960 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9487
                dc.w $9500 ! ((grp_EF940 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF940 / 2) >> 16)
                dc.w 1
