byte_2ED044:    dc.b   0,  4,$4E,$84,$AB,$A2,$7C,$93,$7D,$93
                                        ; DATA XREF: ROM:off_2258   o
                dc.w sprite_32_16
                dc.w $4C82
                dc.w $9500 ! ((grp_51E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_51E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $6C82
                dc.w $9500 ! ((grp_51F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_51F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9C8D
                dc.w $9500 ! ((grp_17B3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B3C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9489
                dc.w $9500 ! ((grp_19C3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C3C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8C85
                dc.w $9500 ! ((grp_BE9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE9C0 / 2) >> 16)
                dc.w 2
