byte_2F33B4:    dc.b   0, $A,$5C,$60,$9A,$8D,$7B,$76,$7C,$76
                                        ; DATA XREF: ROM:off_27A8   o
                dc.w sprite_32_24
                dc.w $6F66
                dc.w $9500 ! ((grp_1369C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1369C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1369C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6F7E
                dc.w $9500 ! ((grp_55B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8F66
                dc.w $9500 ! ((grp_8D680 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $745E
                dc.w $9500 ! ((grp_18E860 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6766
                dc.w $9500 ! ((grp_19DFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DFE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8F7B
                dc.w $9500 ! ((grp_C1140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A76
                dc.w $9500 ! ((grp_F33C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F33C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F33C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5F6E
                dc.w $9500 ! ((grp_F33E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F33E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F33E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_F3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $838E
                dc.w $9500 ! ((grp_F3420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9782
                dc.w $9500 ! ((grp_F3440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3440 / 2) >> 16)
                dc.w 1
