byte_2E4090:    dc.b   0, $A,$65,$41,$94,$68,$56,$64,$5E,$6E
                                        ; DATA XREF: ROM:off_1B18   o
                dc.w sprite_32_16
                dc.w $603D
                dc.w $9500 ! ((grp_4AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8045
                dc.w $9500 ! ((grp_1744C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1744C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1744C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5863
                dc.w $9500 ! ((grp_7B880 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $685C
                dc.w $9500 ! ((grp_7B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $786B
                dc.w $9500 ! ((grp_7B980 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6073
                dc.w $9500 ! ((grp_1864C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1864C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1864C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $784D
                dc.w $9500 ! ((grp_196000 / 2) & $00FF)
                dc.w $9600 ! (((grp_196000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $885D
                dc.w $9500 ! ((grp_195FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195FA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9055
                dc.w $9500 ! ((grp_B5D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $555D
                dc.w $9500 ! ((grp_E8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $644D
                dc.w $9500 ! ((grp_E8320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8320 / 2) >> 16)
                dc.w 1
