byte_2EC858:    dc.b   0,  2,$6F,$5B,$8D,$69,$77,$62,$78,$62
                                        ; DATA XREF: ROM:off_2168   o
                dc.w sprite_24_16
                dc.w $785B
                dc.w $9500 ! ((grp_1642C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1642C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1642C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6059
                dc.w $9500 ! ((grp_18C940 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $836B
                dc.w $9500 ! ((grp_EFE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFE20 / 2) >> 16)
                dc.w 1
