byte_2EACDA:    dc.b   0,  7,$6E,$72,$97,$89,$80,$79,$81,$79
                                        ; DATA XREF: ROM:off_1FAC   o
                dc.w sprite_24_16
                dc.w $727A
                dc.w $9500 ! ((grp_163300 / 2) & $00FF)
                dc.w $9600 ! (((grp_163300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $927C
                dc.w $9500 ! ((grp_17AAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AAC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6A
                dc.w $9500 ! ((grp_86E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_86E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A6A
                dc.w $9500 ! ((grp_86F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_D7700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A7C
                dc.w $9500 ! ((grp_BDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $626A
                dc.w $9500 ! ((grp_EF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF1C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A62
                dc.w $9500 ! ((grp_EF1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF1E0 / 2) >> 16)
                dc.w 1
