byte_2E07BE:    dc.b   0,  6,$66,$4C,$95,$7F,$7D,$65,$8C,$50
                                        ; DATA XREF: ROM:off_18DC   o
                dc.w sprite_24_32
                dc.w $794A
                dc.w $9500 ! ((grp_109540 / 2) & $00FF)
                dc.w $9600 ! (((grp_109540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109540 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7A6A
                dc.w $9500 ! ((grp_1467A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1467A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1467A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $6A52
                dc.w $9500 ! ((grp_64300 / 2) & $00FF)
                dc.w $9600 ! (((grp_64300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A72
                dc.w $9500 ! ((grp_81800 / 2) & $00FF)
                dc.w $9600 ! (((grp_81800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9167
                dc.w $9500 ! ((grp_198B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_198B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $626A
                dc.w $9500 ! ((grp_B9A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $914A
                dc.w $9500 ! ((grp_B9A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9A80 / 2) >> 16)
                dc.w 2
