byte_2D5F00:    dc.b   0,  5,$7D,$59,$99,$95,$8E,$7C,$82,$69
                                        ; DATA XREF: ROM:off_1200   o
                dc.w sprite_24_32
                dc.w $7B5A
                dc.w $9500 ! ((grp_FF7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $827A
                dc.w $9500 ! ((grp_1417C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1417C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1417C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7C92
                dc.w $9500 ! ((grp_78D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A7A
                dc.w $9500 ! ((grp_E6520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8452
                dc.w $9500 ! ((grp_E6540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A88
                dc.w $9500 ! ((grp_E6560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6560 / 2) >> 16)
                dc.w 1
