byte_2CEF80:    dc.b   0, $C,$69,$63,$9A,$8E,$80,$77,$81,$77
                                        ; DATA XREF: ROM:off_B38   o
                dc.w sprite_32_24
                dc.w $727F
                dc.w $9500 ! ((grp_11FBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $725F
                dc.w $9500 ! ((grp_1201C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1201C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1201C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $627F
                dc.w $9500 ! ((grp_74780 / 2) & $00FF)
                dc.w $9600 ! (((grp_74780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9267
                dc.w $9500 ! ((grp_74980 / 2) & $00FF)
                dc.w $9600 ! (((grp_74980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9280
                dc.w $9500 ! ((grp_74800 / 2) & $00FF)
                dc.w $9600 ! (((grp_74800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A57
                dc.w $9500 ! ((grp_97100 / 2) & $00FF)
                dc.w $9600 ! (((grp_97100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7A77
                dc.w $9500 ! ((grp_183B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_183B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6277
                dc.w $9500 ! ((grp_C8440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A5F
                dc.w $9500 ! ((grp_B1400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6264
                dc.w $9500 ! ((grp_E2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A6F
                dc.w $9500 ! ((grp_E2A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7277
                dc.w $9500 ! ((grp_E2A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E97
                dc.w $9500 ! ((grp_E2960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2960 / 2) >> 16)
                dc.w 1
