byte_2D42DC:    dc.b   0,  4,$74,$68,$8F,$90,$83,$7B,$84,$7B
                                        ; DATA XREF: ROM:off_10B8   o
                dc.w sprite_24_24
                dc.w $7B74
                dc.w $9500 ! ((grp_140800 / 2) & $00FF)
                dc.w $9600 ! (((grp_140800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140800 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7C64
                dc.w $9500 ! ((grp_77880 / 2) & $00FF)
                dc.w $9600 ! (((grp_77880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $838C
                dc.w $9500 ! ((grp_CAB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7377
                dc.w $9500 ! ((grp_B2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C5F
                dc.w $9500 ! ((grp_B2F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2F40 / 2) >> 16)
                dc.w 2
