byte_2D1C26:    dc.b   0,  9,$71,$61,$97,$8F,$8B,$73,$8C,$73
                                        ; DATA XREF: ROM:off_E5C   o
                dc.w sprite_32_32
                dc.w $7367
                dc.w $9500 ! ((grp_16800 / 2) & $00FF)
                dc.w $9600 ! (((grp_16800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $9359
                dc.w $9500 ! ((grp_158680 / 2) & $00FF)
                dc.w $9600 ! (((grp_158680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $637A
                dc.w $9500 ! ((grp_C9880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9369
                dc.w $9500 ! ((grp_C98C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C98C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C98C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9376
                dc.w $9500 ! ((grp_B2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A5F
                dc.w $9500 ! ((grp_E3D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8487
                dc.w $9500 ! ((grp_E3DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B5F
                dc.w $9500 ! ((grp_E3DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B7E
                dc.w $9500 ! ((grp_E3E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AB61
                dc.w $9500 ! ((grp_E3DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3DE0 / 2) >> 16)
                dc.w 1
