byte_2DC488:    dc.b   0,  6,$74,$5E,$8A,$8D,$7F,$66,$7F,$69
                                        ; DATA XREF: ROM:00001620   o
                dc.w sprite_24_16
                dc.w $7870
                dc.w $9500 ! ((grp_15DE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15DE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15DE40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $685F
                dc.w $9500 ! ((grp_175780 / 2) & $00FF)
                dc.w $9600 ! (((grp_175780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7858
                dc.w $9500 ! ((grp_175840 / 2) & $00FF)
                dc.w $9600 ! (((grp_175840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8858
                dc.w $9500 ! ((grp_175900 / 2) & $00FF)
                dc.w $9600 ! (((grp_175900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175900 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7080
                dc.w $9500 ! ((grp_99580 / 2) & $00FF)
                dc.w $9600 ! (((grp_99580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_CFF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8488
                dc.w $9500 ! ((grp_CFEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFEC0 / 2) >> 16)
                dc.w 2
