byte_2F944C:    dc.b   0,  3,$68,$6F,$90,$94,$7C,$81,$7D,$81
                                        ; DATA XREF: ROM:off_2D38   o
                dc.w sprite_16_32
                dc.w $6B77
                dc.w $9500 ! ((grp_6FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7B6D
                dc.w $9500 ! ((grp_6F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $8B71
                dc.w $9500 ! ((grp_19F660 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F660 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6385
                dc.w $9500 ! ((grp_C4080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4080 / 2) >> 16)
                dc.w 2
