byte_2DF6DC:    dc.b   0,  8,$73,$64,$A4,$92,$8B,$7B,$8C,$7B
                                        ; DATA XREF: ROM:off_1820   o
                dc.w sprite_24_32
                dc.w $7A6A
                dc.w $9500 ! ((grp_107140 / 2) & $00FF)
                dc.w $9600 ! (((grp_107140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $926A
                dc.w $9500 ! ((grp_62F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_62F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $9190
                dc.w $9500 ! ((grp_188980 / 2) & $00FF)
                dc.w $9600 ! (((grp_188980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188980 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $718A
                dc.w $9500 ! ((grp_D1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858A
                dc.w $9500 ! ((grp_D1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9462
                dc.w $9500 ! ((grp_D1DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7273
                dc.w $9500 ! ((grp_EAE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7282
                dc.w $9500 ! ((grp_EAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $968A
                dc.w $9500 ! ((grp_EAE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE80 / 2) >> 16)
                dc.w 1
