byte_2E8C28:    dc.b   0,  5,$78,$67,$84,$8D,$7E,$7A,$81,$6C
                                        ; DATA XREF: ROM:off_1DC0   o
                dc.w sprite_8_32
                dc.w $7A65
                dc.w $9500 ! ((grp_A5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F8B
                dc.w $9500 ! ((grp_CE8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7785
                dc.w $9500 ! ((grp_B6480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8265
                dc.w $9500 ! ((grp_B64C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B64C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B64C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7266
                dc.w $9500 ! ((grp_E89A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E89A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E89A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $827D
                dc.w $9500 ! ((grp_E89C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E89C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E89C0 / 2) >> 16)
                dc.w 1
