byte_2D500A:    dc.b   0,  7,$6E,$64,$8E,$8F,$82,$79,$7D,$6C
                                        ; DATA XREF: ROM:off_115C   o
                dc.w sprite_16_32
                dc.w $7363
                dc.w $9500 ! ((grp_5F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $837B
                dc.w $9500 ! ((grp_159F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_159F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6B83
                dc.w $9500 ! ((grp_78480 / 2) & $00FF)
                dc.w $9600 ! (((grp_78480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $868B
                dc.w $9500 ! ((grp_CB400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B71
                dc.w $9500 ! ((grp_B3800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B63
                dc.w $9500 ! ((grp_E5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B83
                dc.w $9500 ! ((grp_E5EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8373
                dc.w $9500 ! ((grp_E5EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5EC0 / 2) >> 16)
                dc.w 1
