byte_2D1EF2:    dc.b   0,  4,$71,$5F,$8D,$8E,$79,$73,$7A,$73
                                        ; DATA XREF: ROM:off_E7C   o
                dc.w sprite_32_24
                dc.w $716C
                dc.w $9500 ! ((grp_121CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_121CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $685C
                dc.w $9500 ! ((grp_48300 / 2) & $00FF)
                dc.w $9600 ! (((grp_48300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8862
                dc.w $9500 ! ((grp_C9A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8984
                dc.w $9500 ! ((grp_C9AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6064
                dc.w $9500 ! ((grp_B22C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B22C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B22C0 / 2) >> 16)
                dc.w 2
