byte_2F29D2:    dc.b   0, $B,$5D,$71,$A5,$93,$82,$81,$83,$81
                                        ; DATA XREF: ROM:off_2744   o
                dc.w sprite_32_32
                dc.w $836D
                dc.w $9500 ! ((grp_39400 / 2) & $00FF)
                dc.w $9600 ! (((grp_39400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $6373
                dc.w $9500 ! ((grp_6C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7364
                dc.w $9500 ! ((grp_6C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7384
                dc.w $9500 ! ((grp_8CA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A36F
                dc.w $9500 ! ((grp_8CB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $838D
                dc.w $9500 ! ((grp_9EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5B78
                dc.w $9500 ! ((grp_ACB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8F95
                dc.w $9500 ! ((grp_18E260 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E260 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $646B
                dc.w $9500 ! ((grp_DB680 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5389
                dc.w $9500 ! ((grp_C0900 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C6A
                dc.w $9500 ! ((grp_F27E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F27E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F27E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A38D
                dc.w $9500 ! ((grp_F2800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2800 / 2) >> 16)
                dc.w 1
