byte_2E9C34:    dc.b   0,  5,$6A,$53,$A1,$76,$85,$64,$86,$64
                                        ; DATA XREF: ROM:off_1EC0   o
                dc.w sprite_24_32
                dc.w $7B57
                dc.w $9500 ! ((grp_10E940 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6B57
                dc.w $9500 ! ((grp_17A1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $794F
                dc.w $9500 ! ((grp_D6E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6362
                dc.w $9500 ! ((grp_EEC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEC20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8677
                dc.w $9500 ! ((grp_EEC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEC00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9C61
                dc.w $9500 ! ((grp_EEBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEBE0 / 2) >> 16)
                dc.w 1
