byte_2E9FA0:    dc.b   0,  4,$95,$63,$A0,$6F,$A5,$67,$A6,$67
                                        ; DATA XREF: ROM:off_1EF0   o
                dc.w sprite_16_32
                dc.w $9357
                dc.w $9500 ! ((grp_67100 / 2) & $00FF)
                dc.w $9600 ! (((grp_67100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $A359
                dc.w $9500 ! ((grp_67200 / 2) & $00FF)
                dc.w $9600 ! (((grp_67200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67200 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $8B57
                dc.w $9500 ! ((grp_19B160 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $B35F
                dc.w $9500 ! ((grp_BDA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $BB5F
                dc.w $9500 ! ((grp_EEDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEDE0 / 2) >> 16)
                dc.w 1
