byte_2D5812:    dc.b   0,  7,$6F,$5C,$8E,$8F,$71,$6D,$6F,$66
                                        ; DATA XREF: ROM:off_11B4   o
                dc.w sprite_32_32
                dc.w $6258
                dc.w $9500 ! ((grp_1D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1D600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7478
                dc.w $9500 ! ((grp_7DE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8388
                dc.w $9500 ! ((grp_187900 / 2) & $00FF)
                dc.w $9600 ! (((grp_187900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187900 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B88
                dc.w $9500 ! ((grp_D00C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D00C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D00C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6F50
                dc.w $9500 ! ((grp_D0100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A6F
                dc.w $9500 ! ((grp_E99E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E99E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E99E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C78
                dc.w $9500 ! ((grp_E9A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8480
                dc.w $9500 ! ((grp_E9A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9A20 / 2) >> 16)
                dc.w 1
