byte_2ED08A:    dc.b   0,  9,$6E,$4A,$A3,$9A,$88,$72,$89,$72
                                        ; DATA XREF: ROM:off_225C   o
                dc.w sprite_24_16
                dc.w $8A88
                dc.w $9500 ! ((grp_1648C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1648C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1648C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6D48
                dc.w $9500 ! ((grp_17B480 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B480 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7360
                dc.w $9500 ! ((grp_88B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C70
                dc.w $9500 ! ((grp_D86C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D86C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D86C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8178
                dc.w $9500 ! ((grp_D8740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8680
                dc.w $9500 ! ((grp_D8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8368
                dc.w $9500 ! ((grp_EFEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFEC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D98
                dc.w $9500 ! ((grp_EFEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFEE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9C97
                dc.w $9500 ! ((grp_EFF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFF00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A28C
                dc.w $9500 ! ((grp_EFF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFF20 / 2) >> 16)
                dc.w 1
