byte_2E1EBC:    dc.b   0,  2,$71,$80,$8F,$98,$80,$8C,$81,$8C
                                        ; DATA XREF: ROM:off_19C0   o
                dc.w sprite_16_16
                dc.w $777E
                dc.w $9500 ! ((grp_7E480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $808E
                dc.w $9500 ! ((grp_187AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_187AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187AE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6F8B
                dc.w $9500 ! ((grp_B7680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7680 / 2) >> 16)
                dc.w 2
