byte_2F833A:    dc.b   0,  2,$74,$7A,$8F,$94,$81,$87,$82,$87
                                        ; DATA XREF: ROM:off_2C64   o
                dc.w sprite_24_24
                dc.w $7978
                dc.w $9500 ! ((grp_151A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_151A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151A80 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7A90
                dc.w $9500 ! ((grp_18F6A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F6A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F6A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7178
                dc.w $9500 ! ((grp_C3740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3740 / 2) >> 16)
                dc.w 2
