byte_2EF55C:    dc.b   0,  5,$6C,$81,$93,$8D,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_24F0   o
                dc.w sprite_32_16
                dc.w $7281
                dc.w $9500 ! ((grp_53200 / 2) & $00FF)
                dc.w $9600 ! (((grp_53200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7369
                dc.w $9500 ! ((grp_18D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7871
                dc.w $9500 ! ((grp_D9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A79
                dc.w $9500 ! ((grp_D9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A81
                dc.w $9500 ! ((grp_F0E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9286
                dc.w $9500 ! ((grp_F0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0E80 / 2) >> 16)
                dc.w 1
