byte_2D2BF0:    dc.b   0,  6,$73,$6F,$90,$8C,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_F20   o
                dc.w sprite_24_16
                dc.w $7A6F
                dc.w $9500 ! ((grp_159280 / 2) & $00FF)
                dc.w $9600 ! (((grp_159280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159280 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7A7F
                dc.w $9500 ! ((grp_1591C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1591C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1591C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6C
                dc.w $9500 ! ((grp_77300 / 2) & $00FF)
                dc.w $9600 ! (((grp_77300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6464
                dc.w $9500 ! ((grp_CA400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $727C
                dc.w $9500 ! ((grp_E4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A8F
                dc.w $9500 ! ((grp_E4C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $927F
                dc.w $9500 ! ((grp_E4BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4BA0 / 2) >> 16)
                dc.w 1
