byte_2F96A0:    dc.b   0,  1,$81,$7D,$8D,$84,$87,$80,$88,$80
                                        ; DATA XREF: ROM:off_2D70   o
                dc.w sprite_16_16
                dc.w $817B
                dc.w $9500 ! ((grp_91100 / 2) & $00FF)
                dc.w $9600 ! (((grp_91100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $797B
                dc.w $9500 ! ((grp_F6960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6960 / 2) >> 16)
                dc.w 1
