byte_2DB2BC:    dc.b   0,  9,$66,$64,$9F,$8E,$82,$79,$83,$79
                                        ; DATA XREF: ROM:off_1540   o
                dc.w sprite_32_24
                dc.w $6C67
                dc.w $9500 ! ((grp_12DB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12DB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12DB40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C5F
                dc.w $9500 ! ((grp_18A5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A5A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7E7F
                dc.w $9500 ! ((grp_18A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A600 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6464
                dc.w $9500 ! ((grp_19A140 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A140 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_D56C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D56C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D56C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7284
                dc.w $9500 ! ((grp_D5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A87
                dc.w $9500 ! ((grp_D5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C61
                dc.w $9500 ! ((grp_BC180 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9462
                dc.w $9500 ! ((grp_EDCE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDCE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDCE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B61
                dc.w $9500 ! ((grp_EDD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDD00 / 2) >> 16)
                dc.w 1
