byte_2F2DDC:    dc.b   0,  5,$77,$54,$97,$87,$86,$6E,$87,$6E
                                        ; DATA XREF: ROM:off_2770   o
                dc.w sprite_32_24
                dc.w $806E
                dc.w $9500 ! ((grp_136840 / 2) & $00FF)
                dc.w $9600 ! (((grp_136840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8256
                dc.w $9500 ! ((grp_14FC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_14FC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14FC20 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $725D
                dc.w $9500 ! ((grp_6D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $7881
                dc.w $9500 ! ((grp_C1040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8089
                dc.w $9500 ! ((grp_F3260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F4E
                dc.w $9500 ! ((grp_F3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3280 / 2) >> 16)
                dc.w 1
