byte_2F52F0:    dc.b   0,  2,$5D,$9A,$6A,$A6,$63,$A0,$64,$A0
                                        ; DATA XREF: ROM:off_2A58   o
                dc.w sprite_8_24
                dc.w $5B91
                dc.w $9500 ! ((grp_19E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E880 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6395
                dc.w $9500 ! ((grp_C1DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B9C
                dc.w $9500 ! ((grp_F45E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F45E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F45E0 / 2) >> 16)
                dc.w 1
