byte_2E6F74:    dc.b   0,  3,$74,$53,$92,$78,$7D,$64,$6B,$63
                                        ; DATA XREF: ROM:off_1CA8   o
                dc.w sprite_32_32
                dc.w $7655
                dc.w $9500 ! ((grp_1C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1C000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $665D
                dc.w $9500 ! ((grp_174B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_174B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9655
                dc.w $9500 ! ((grp_196900 / 2) & $00FF)
                dc.w $9600 ! (((grp_196900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196900 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8075
                dc.w $9500 ! ((grp_CEAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEAC0 / 2) >> 16)
                dc.w 2
