byte_2D5C9E:    dc.b   0,  6,$73,$5E,$8C,$90,$7E,$79,$80,$6F
                                        ; DATA XREF: ROM:off_11E4   o
                dc.w sprite_32_32
                dc.w $6E6D
                dc.w $9500 ! ((grp_1C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1C800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_8
                dc.w $778D
                dc.w $9500 ! ((grp_CF600 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7765
                dc.w $9500 ! ((grp_CF640 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $667B
                dc.w $9500 ! ((grp_B6DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F95
                dc.w $9500 ! ((grp_E9220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F5D
                dc.w $9500 ! ((grp_E9240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E7F
                dc.w $9500 ! ((grp_E9260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9260 / 2) >> 16)
                dc.w 1
