byte_2DD7C0:    dc.b   0, $A,$54,$44,$A1,$8C,$7A,$68,$93,$4D
                                        ; DATA XREF: ROM:off_16E0   o
                dc.w sprite_32_32
                dc.w $6E62
                dc.w $9500 ! ((grp_1DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1DE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7A42
                dc.w $9500 ! ((grp_145120 / 2) & $00FF)
                dc.w $9600 ! (((grp_145120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145120 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6A46
                dc.w $9500 ! ((grp_7EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7EF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9242
                dc.w $9500 ! ((grp_7EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6E82
                dc.w $9500 ! ((grp_99900 / 2) & $00FF)
                dc.w $9600 ! (((grp_99900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $524A
                dc.w $9500 ! ((grp_187FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_187FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $725A
                dc.w $9500 ! ((grp_188020 / 2) & $00FF)
                dc.w $9600 ! (((grp_188020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188020 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $768A
                dc.w $9500 ! ((grp_188080 / 2) & $00FF)
                dc.w $9600 ! (((grp_188080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188080 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8E6B
                dc.w $9500 ! ((grp_B7C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A87
                dc.w $9500 ! ((grp_E9F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A242
                dc.w $9500 ! ((grp_E9FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9FA0 / 2) >> 16)
                dc.w 1
