byte_2ED598:    dc.b   0,  2,$78,$64,$88,$93,$80,$79,$81,$79
                                        ; DATA XREF: ROM:off_22A8   o
                dc.w sprite_24_24
                dc.w $7468
                dc.w $9500 ! ((grp_14C1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C1A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7980
                dc.w $9500 ! ((grp_89100 / 2) & $00FF)
                dc.w $9600 ! (((grp_89100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7560
                dc.w $9500 ! ((grp_D8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8B00 / 2) >> 16)
                dc.w 2
