byte_2E1B8E:    dc.b   0,  5,$70,$5C,$9A,$88,$85,$72,$74,$62
                                        ; DATA XREF: ROM:off_198C   o
                dc.w sprite_32_32
                dc.w $6E62
                dc.w $9500 ! ((grp_1DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $8D6A
                dc.w $9500 ! ((grp_7E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6E82
                dc.w $9500 ! ((grp_D0440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0440 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E5A
                dc.w $9500 ! ((grp_D0480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $748A
                dc.w $9500 ! ((grp_E5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8582
                dc.w $9500 ! ((grp_E9C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9C20 / 2) >> 16)
                dc.w 1
