byte_2FF5F0:    dc.b   0, $A,$3F,$6F,$90,$C2,$67,$98,$68,$98
                                        ; DATA XREF: ROM:off_3590   o
                dc.w sprite_8_24
                dc.w $44AD
                dc.w $9500 ! ((grp_1A1040 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1040 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $549D
                dc.w $9500 ! ((grp_1A0FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5C95
                dc.w $9500 ! ((grp_1A0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $648D
                dc.w $9500 ! ((grp_1A0F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6C84
                dc.w $9500 ! ((grp_1A0EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $747B
                dc.w $9500 ! ((grp_1A0E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C73
                dc.w $9500 ! ((grp_1A0E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $846D
                dc.w $9500 ! ((grp_1A0DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $3CB5
                dc.w $9500 ! ((grp_C6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4CA8
                dc.w $9500 ! ((grp_C64C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C64C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C64C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C6D
                dc.w $9500 ! ((grp_C6480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6480 / 2) >> 16)
                dc.w 2
