byte_2F91EC:    dc.b   0,  4,$73,$6F,$94,$95,$83,$82,$84,$82
                                        ; DATA XREF: ROM:off_2D18   o
                dc.w sprite_32_24
                dc.w $7075
                dc.w $9500 ! ((grp_139CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_139CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $708D
                dc.w $9500 ! ((grp_9FE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9073
                dc.w $9500 ! ((grp_AE600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $766D
                dc.w $9500 ! ((grp_18FDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FDC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D95
                dc.w $9500 ! ((grp_DE380 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE380 / 2) >> 16)
                dc.w 2
