byte_2FA598:    dc.b   0,  8,$78,$71,$BF,$7E,$9B,$72,$9C,$72
                                        ; DATA XREF: ROM:off_2E10   o
                dc.w sprite_32_32
                dc.w $7173
                dc.w $9500 ! ((grp_42200 / 2) & $00FF)
                dc.w $9600 ! (((grp_42200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $9963
                dc.w $9500 ! ((grp_42400 / 2) & $00FF)
                dc.w $9600 ! (((grp_42400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $895B
                dc.w $9500 ! ((grp_180940 / 2) & $00FF)
                dc.w $9600 ! (((grp_180940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180940 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $995B
                dc.w $9500 ! ((grp_A0680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $715B
                dc.w $9500 ! ((grp_190720 / 2) & $00FF)
                dc.w $9600 ! (((grp_190720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190720 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $9653
                dc.w $9500 ! ((grp_190780 / 2) & $00FF)
                dc.w $9600 ! (((grp_190780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190780 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9173
                dc.w $9500 ! ((grp_19FA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FA80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $B96B
                dc.w $9500 ! ((grp_19FAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FAE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $C169
                dc.w $9500 ! ((grp_C49C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C49C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C49C0 / 2) >> 16)
                dc.w 2
