byte_2FEC3A:    dc.b   0,  1,$7B,$7E,$85,$8D,$83,$7E,$84,$7E
                                        ; DATA XREF: ROM:off_34BC   o
                dc.w sprite_16_24
                dc.w $797E
                dc.w $9500 ! ((grp_182B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_182B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $846E
                dc.w $9500 ! ((grp_96400 / 2) & $00FF)
                dc.w $9600 ! (((grp_96400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96400 / 2) >> 16)
                dc.w 4
