byte_2FDA5C:    dc.b   0,  8,$60,$5E,$8E,$8D,$77,$75,$78,$75
                                        ; DATA XREF: ROM:off_3328   o
                dc.w sprite_24_16
                dc.w $636A
                dc.w $9500 ! ((grp_16D440 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7B60
                dc.w $9500 ! ((grp_182080 / 2) & $00FF)
                dc.w $9600 ! (((grp_182080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7578
                dc.w $9500 ! ((grp_95500 / 2) & $00FF)
                dc.w $9600 ! (((grp_95500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95500 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6888
                dc.w $9500 ! ((grp_A1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6E5C
                dc.w $9500 ! ((grp_DFF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8578
                dc.w $9500 ! ((grp_DFFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E60
                dc.w $9500 ! ((grp_C5BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $665D
                dc.w $9500 ! ((grp_F8560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E58
                dc.w $9500 ! ((grp_F8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8580 / 2) >> 16)
                dc.w 1
