byte_2F4DC0:    dc.b   0, $B,$6D,$62,$94,$8B,$8E,$74,$8F,$74
                                        ; DATA XREF: ROM:off_2A20   o
                dc.w sprite_24_32
                dc.w $795F
                dc.w $9500 ! ((grp_1165C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1165C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1165C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $996E
                dc.w $9500 ! ((grp_150760 / 2) & $00FF)
                dc.w $9600 ! (((grp_150760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150760 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6A75
                dc.w $9500 ! ((grp_17E780 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E780 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7A7F
                dc.w $9500 ! ((grp_8E680 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $808D
                dc.w $9500 ! ((grp_DC700 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9D60
                dc.w $9500 ! ((grp_DC740 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9F86
                dc.w $9500 ! ((grp_DC780 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7165
                dc.w $9500 ! ((grp_C1A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9170
                dc.w $9500 ! ((grp_C1A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A7F
                dc.w $9500 ! ((grp_F42A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F42A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F42A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9456
                dc.w $9500 ! ((grp_F42C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F42C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F42C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B173
                dc.w $9500 ! ((grp_F42E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F42E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F42E0 / 2) >> 16)
                dc.w 1
