byte_2E3CAC:    dc.b   0, $A,$5A,$6C,$98,$7D,$C4,$47,$C4,$41
                                        ; DATA XREF: ROM:off_1B00   o
                dc.w sprite_32_16
                dc.w $656E
                dc.w $9500 ! ((grp_4A700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5D5E
                dc.w $9500 ! ((grp_15C4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C4C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $856E
                dc.w $9500 ! ((grp_15C580 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $B93E
                dc.w $9500 ! ((grp_7B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $787E
                dc.w $9500 ! ((grp_CD900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $996A
                dc.w $9500 ! ((grp_CD940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A062
                dc.w $9500 ! ((grp_CD9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B54E
                dc.w $9500 ! ((grp_CD980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5563
                dc.w $9500 ! ((grp_E80E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E80E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E80E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A85A
                dc.w $9500 ! ((grp_E80C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E80C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E80C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B055
                dc.w $9500 ! ((grp_E80A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E80A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E80A0 / 2) >> 16)
                dc.w 1
