byte_2FF25E:    dc.b   0,  8,$1A,$72,$B8,$90,$67,$7E,$68,$7E
                                        ; DATA XREF: ROM:off_3564   o
                dc.w sprite_32_16
                dc.w $5074
                dc.w $9500 ! ((grp_5A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A400 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8874
                dc.w $9500 ! ((grp_5A500 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $1874
                dc.w $9500 ! ((grp_96480 / 2) & $00FF)
                dc.w $9600 ! (((grp_96480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7074
                dc.w $9500 ! ((grp_96500 / 2) & $00FF)
                dc.w $9600 ! (((grp_96500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A874
                dc.w $9500 ! ((grp_96580 / 2) & $00FF)
                dc.w $9600 ! (((grp_96580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96580 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $307A
                dc.w $9500 ! ((grp_A1B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8074
                dc.w $9500 ! ((grp_C6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $2084
                dc.w $9500 ! ((grp_F9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $287C
                dc.w $9500 ! ((grp_F9160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9160 / 2) >> 16)
                dc.w 1
