byte_2F4BD0:    dc.b   0,  8,$6B,$65,$92,$8E,$81,$79,$82,$79
                                        ; DATA XREF: ROM:off_2A10   o
                dc.w sprite_16_32
                dc.w $7168
                dc.w $9500 ! ((grp_6DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $815F
                dc.w $9500 ! ((grp_6DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6DB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $817F
                dc.w $9500 ! ((grp_8E580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $696F
                dc.w $9500 ! ((grp_ACE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $917D
                dc.w $9500 ! ((grp_19E4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E4C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9985
                dc.w $9500 ! ((grp_C18C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C18C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C18C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6186
                dc.w $9500 ! ((grp_F41A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F41A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F41A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7988
                dc.w $9500 ! ((grp_F41C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F41C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F41C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $898F
                dc.w $9500 ! ((grp_F41E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F41E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F41E0 / 2) >> 16)
                dc.w 1
