byte_2E4FC8:    dc.b   0, $B,$6F,$62,$88,$8E,$48,$8C,$78,$62
                                        ; DATA XREF: ROM:off_1B98   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82180 / 2) & $00FF)
                dc.w $9600 ! (((grp_82180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8260
                dc.w $9500 ! ((grp_D3600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8268
                dc.w $9500 ! ((grp_D3640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9138
                dc.w $9500 ! ((grp_D3680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_BA300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8258
                dc.w $9500 ! ((grp_EC3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC3A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8270
                dc.w $9500 ! ((grp_EC3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC3C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9440
                dc.w $9500 ! ((grp_EC3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC3E0 / 2) >> 16)
                dc.w 1
