byte_2D0112:    dc.b   0,  1,$79,$7F,$86,$8F,$7F,$87,$80,$87
                                        ; DATA XREF: ROM:off_CD4   o
                dc.w sprite_24_24
                dc.w $777F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7877
                dc.w $9500 ! ((grp_C8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B00 / 2) >> 16)
                dc.w 2
