byte_2E4F46:    dc.b   0,  9,$6F,$62,$88,$8E,$4A,$8B,$78,$62
                                        ; DATA XREF: ROM:off_1B94   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82180 / 2) & $00FF)
                dc.w $9600 ! (((grp_82180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $825D
                dc.w $9500 ! ((grp_82580 / 2) & $00FF)
                dc.w $9600 ! (((grp_82580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_BA240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $826D
                dc.w $9500 ! ((grp_BA280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9239
                dc.w $9500 ! ((grp_BA2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A3D
                dc.w $9500 ! ((grp_EC380 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC380 / 2) >> 16)
                dc.w 1
