byte_2CE6B4:    dc.b   0,  1,$78,$79,$87,$88,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_AD0   o
                dc.w sprite_24_16
                dc.w $7677
                dc.w $9500 ! ((grp_156400 / 2) & $00FF)
                dc.w $9600 ! (((grp_156400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7987
                dc.w $9500 ! ((grp_C7640 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7640 / 2) >> 16)
                dc.w 2
