byte_2D18B6:    dc.b   0,  7,$74,$66,$97,$89,$97,$75,$98,$75
                                        ; DATA XREF: ROM:off_E34   o
                dc.w sprite_32_32
                dc.w $7162
                dc.w $9500 ! ((grp_16000 / 2) & $00FF)
                dc.w $9600 ! (((grp_16000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9162
                dc.w $9500 ! ((grp_FC7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7182
                dc.w $9500 ! ((grp_158500 / 2) & $00FF)
                dc.w $9600 ! (((grp_158500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158500 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $A95A
                dc.w $9500 ! ((grp_1585C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1585C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1585C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9982
                dc.w $9500 ! ((grp_76680 / 2) & $00FF)
                dc.w $9600 ! (((grp_76680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A96A
                dc.w $9500 ! ((grp_76600 / 2) & $00FF)
                dc.w $9600 ! (((grp_76600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $A15A
                dc.w $9500 ! ((grp_E3C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A97A
                dc.w $9500 ! ((grp_E3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3C80 / 2) >> 16)
                dc.w 1
