byte_2F98A8:    dc.b   0,  8,$66,$67,$A0,$9E,$83,$82,$84,$82
                                        ; DATA XREF: ROM:off_2D98   o
                dc.w sprite_16_16
                dc.w $877C
                dc.w $9500 ! ((grp_91200 / 2) & $00FF)
                dc.w $9600 ! (((grp_91200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7D71
                dc.w $9500 ! ((grp_DE6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $727A
                dc.w $9500 ! ((grp_C4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A61
                dc.w $9500 ! ((grp_C4340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $688C
                dc.w $9500 ! ((grp_F6B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C9C
                dc.w $9500 ! ((grp_F6BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7194
                dc.w $9500 ! ((grp_F6BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7986
                dc.w $9500 ! ((grp_F6B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A8D
                dc.w $9500 ! ((grp_F6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6B80 / 2) >> 16)
                dc.w 1
