byte_2F2008:    dc.b   0,  5,$78,$65,$A4,$8B,$8E,$73,$8F,$73
                                        ; DATA XREF: ROM:off_26E0   o
                dc.w sprite_24_32
                dc.w $7568
                dc.w $9500 ! ((grp_113740 / 2) & $00FF)
                dc.w $9600 ! (((grp_113740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113740 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $8D68
                dc.w $9500 ! ((grp_134140 / 2) & $00FF)
                dc.w $9600 ! (((grp_134140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134140 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $9258
                dc.w $9500 ! ((grp_54600 / 2) & $00FF)
                dc.w $9600 ! (((grp_54600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7388
                dc.w $9500 ! ((grp_9E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8D80
                dc.w $9500 ! ((grp_18DD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DD20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6D7C
                dc.w $9500 ! ((grp_F1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1D00 / 2) >> 16)
                dc.w 1
