byte_2EE1B8:    dc.b   0,  6,$69,$6D,$97,$95,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_2370   o
                dc.w sprite_32_32
                dc.w $716B
                dc.w $9500 ! ((grp_31600 / 2) & $00FF)
                dc.w $9600 ! (((grp_31600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $9082
                dc.w $9500 ! ((grp_89B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $738B
                dc.w $9500 ! ((grp_18D0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D0C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6974
                dc.w $9500 ! ((grp_19CD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CD80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7793
                dc.w $9500 ! ((grp_D9200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $617F
                dc.w $9500 ! ((grp_BF280 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9172
                dc.w $9500 ! ((grp_BF2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF2C0 / 2) >> 16)
                dc.w 2
