byte_2FEFD6:    dc.b   0,  2,$6F,$6E,$8B,$90,$7D,$7F,$7E,$7F
                                        ; DATA XREF: ROM:off_351C   o
                dc.w sprite_24_32
                dc.w $6E6C
                dc.w $9500 ! ((grp_11D940 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D940 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $708C
                dc.w $9500 ! ((grp_1919E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1919E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1919E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8674
                dc.w $9500 ! ((grp_1A16A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A16A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A16A0 / 2) >> 16)
                dc.w 3
