byte_2FEC18:    dc.b   0,  1,$7B,$7F,$85,$8D,$83,$7F,$84,$7F
                                        ; DATA XREF: ROM:off_34B8   o
                dc.w sprite_16_32
                dc.w $7970
                dc.w $9500 ! ((grp_71B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_71B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $876F
                dc.w $9500 ! ((grp_F9060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9060 / 2) >> 16)
                dc.w 1
