byte_2E1B54:    dc.b   0,  3,$6E,$6D,$91,$8D,$7F,$77,$7E,$79
                                        ; DATA XREF: ROM:off_1988   o
                dc.w sprite_24_32
                dc.w $746A
                dc.w $9500 ! ((grp_104BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_104BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $8C6D
                dc.w $9500 ! ((grp_A6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C6E
                dc.w $9500 ! ((grp_197140 / 2) & $00FF)
                dc.w $9600 ! (((grp_197140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197140 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7C8A
                dc.w $9500 ! ((grp_E9AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9AA0 / 2) >> 16)
                dc.w 1
