byte_2E79F2:    dc.b   0,  3,$6F,$7A,$8E,$8F,$8A,$82,$87,$87
                                        ; DATA XREF: ROM:off_1D0C   o
                dc.w sprite_32_24
                dc.w $7179
                dc.w $9500 ! ((grp_128EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_128EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $9180
                dc.w $9500 ! ((grp_B8280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6989
                dc.w $9500 ! ((grp_EA380 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $697F
                dc.w $9500 ! ((grp_EA3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA3A0 / 2) >> 16)
                dc.w 1
