byte_2FBB82:    dc.b   0,  4,$6A,$6E,$94,$92,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_2FCC   o
                dc.w sprite_32_24
                dc.w $786C
                dc.w $9500 ! ((grp_13B040 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $686C
                dc.w $9500 ! ((grp_91F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_91F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8884
                dc.w $9500 ! ((grp_DF300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $687D
                dc.w $9500 ! ((grp_C4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $788D
                dc.w $9500 ! ((grp_F79E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F79E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F79E0 / 2) >> 16)
                dc.w 1
