byte_2DFF2A:    dc.b   0,  5,$63,$5C,$9C,$8E,$7F,$75,$86,$63
                                        ; DATA XREF: ROM:off_187C   o
                dc.w sprite_32_32
                dc.w $7F5A
                dc.w $9500 ! ((grp_20200 / 2) & $00FF)
                dc.w $9600 ! (((grp_20200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $5F5B
                dc.w $9500 ! ((grp_15FB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FB80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $737A
                dc.w $9500 ! ((grp_15FC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FC40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_9A700 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $775A
                dc.w $9500 ! ((grp_A6F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8E8A
                dc.w $9500 ! ((grp_EB880 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB880 / 2) >> 16)
                dc.w 1
