byte_2D360C:    dc.b   0,  4,$75,$5B,$88,$95,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_1018   o
                dc.w sprite_16_32
                dc.w $785B
                dc.w $9500 ! ((grp_5EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5EA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7A7B
                dc.w $9500 ! ((grp_5EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5EB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $705B
                dc.w $9500 ! ((grp_193FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A7A
                dc.w $9500 ! ((grp_CA6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8676
                dc.w $9500 ! ((grp_CA700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA700 / 2) >> 16)
                dc.w 2
