byte_2ED70C:    dc.b   0,  3,$5A,$6C,$88,$93,$6F,$7B,$70,$7B
                                        ; DATA XREF: ROM:off_22C0   o
                dc.w sprite_32_24
                dc.w $596F
                dc.w $9500 ! ((grp_1321C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1321C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1321C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7770
                dc.w $9500 ! ((grp_69100 / 2) & $00FF)
                dc.w $9600 ! (((grp_69100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_69100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $5A67
                dc.w $9500 ! ((grp_18CE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CE80 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $5F87
                dc.w $9500 ! ((grp_18CEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CEE0 / 2) >> 16)
                dc.w 3
