byte_2EF90E:    dc.b   0,  5,$62,$1B,$91,$37,$79,$29,$7A,$29
                                        ; DATA XREF: ROM:off_253C   o
                dc.w sprite_32_16
                dc.w $6019
                dc.w $9500 ! ((grp_53400 / 2) & $00FF)
                dc.w $9600 ! (((grp_53400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8019
                dc.w $9500 ! ((grp_8A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6431
                dc.w $9500 ! ((grp_18D8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D8A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8431
                dc.w $9500 ! ((grp_D9E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C32
                dc.w $9500 ! ((grp_F11C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F11C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F11C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $901E
                dc.w $9500 ! ((grp_F11E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F11E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F11E0 / 2) >> 16)
                dc.w 1
