byte_2EED0E:    dc.b   0,  2,$76,$83,$8A,$8C,$80,$87,$81,$87
                                        ; DATA XREF: ROM:off_241C   o
                dc.w sprite_32_24
                dc.w $737C
                dc.w $9500 ! ((grp_1330C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1330C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1330C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_F0A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9389
                dc.w $9500 ! ((grp_F0A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0A60 / 2) >> 16)
                dc.w 1
