byte_2E00FE:    dc.b   0,  4,$6D,$62,$94,$8D,$80,$77,$82,$6A
                                        ; DATA XREF: ROM:off_1894   o
                dc.w sprite_32_32
                dc.w $7660
                dc.w $9500 ! ((grp_20A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_20A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6D80
                dc.w $9500 ! ((grp_15FDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15FDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15FDC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6668
                dc.w $9500 ! ((grp_177040 / 2) & $00FF)
                dc.w $9600 ! (((grp_177040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177040 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8588
                dc.w $9500 ! ((grp_D2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $966D
                dc.w $9500 ! ((grp_B9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9680 / 2) >> 16)
                dc.w 2
