byte_2EF792:    dc.b   0,  1,$7E,$4F,$93,$67,$88,$5B,$89,$5B
                                        ; DATA XREF: ROM:off_251C   o
                dc.w sprite_16_16
                dc.w $864D
                dc.w $9500 ! ((grp_8A700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7C62
                dc.w $9500 ! ((grp_F10C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F10C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F10C0 / 2) >> 16)
                dc.w 1
