byte_2D253A:    dc.b   0,  2,$5D,$4A,$A3,$73,$69,$65,$6A,$65
                                        ; DATA XREF: ROM:off_EDC   o
                dc.w sprite_16_8
                dc.w $645C
                dc.w $9500 ! ((grp_C9E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D6C
                dc.w $9500 ! ((grp_E4320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5F64
                dc.w $9500 ! ((grp_E4340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4340 / 2) >> 16)
                dc.w 1
