byte_2DAE7E:    dc.b   0,  3,$5C,$8A,$AE,$8F,$85,$8C,$A5,$8A
                                        ; DATA XREF: ROM:off_151C   o
                dc.w sprite_32_8
                dc.w $5A88
                dc.w $9500 ! ((grp_99680 / 2) & $00FF)
                dc.w $9600 ! (((grp_99680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99680 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7A88
                dc.w $9500 ! ((grp_99700 / 2) & $00FF)
                dc.w $9600 ! (((grp_99700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9A88
                dc.w $9500 ! ((grp_187960 / 2) & $00FF)
                dc.w $9600 ! (((grp_187960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9F90
                dc.w $9500 ! ((grp_D01C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D01C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D01C0 / 2) >> 16)
                dc.w 2
