byte_2F164E:    dc.b   0,  1,$77,$6F,$9A,$8C,$88,$82,$89,$82
                                        ; DATA XREF: ROM:off_265C   o
                dc.w sprite_32_24
                dc.w $7576
                dc.w $9500 ! ((grp_134740 / 2) & $00FF)
                dc.w $9600 ! (((grp_134740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134740 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_8
                dc.w $957E
                dc.w $9500 ! ((grp_F1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1F00 / 2) >> 16)
                dc.w 1
