byte_2CC602:    dc.b   0,  1,$77,$84,$8F,$8D,$82,$88,$83,$88
                                        ; DATA XREF: ROM:off_794   o
                dc.w sprite_24_16
                dc.w $7582
                dc.w $9500 ! ((grp_156100 / 2) & $00FF)
                dc.w $9600 ! (((grp_156100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156100 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8D83
                dc.w $9500 ! ((grp_E1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1500 / 2) >> 16)
                dc.w 1
