byte_2F169E:    dc.b   0,  1,$75,$7E,$90,$8F,$82,$8A,$83,$8A
                                        ; DATA XREF: ROM:off_2664   o
                dc.w sprite_32_8
                dc.w $738A
                dc.w $9500 ! ((grp_9EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7A82
                dc.w $9500 ! ((grp_18DE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DE40 / 2) >> 16)
                dc.w 3
