byte_2F2706:    dc.b   0,  4,$71,$5A,$8E,$8E,$7F,$79,$80,$79
                                        ; DATA XREF: ROM:off_2724   o
                dc.w sprite_24_24
                dc.w $7771
                dc.w $9500 ! ((grp_14DEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14DEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14DEE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7861
                dc.w $9500 ! ((grp_8BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7789
                dc.w $9500 ! ((grp_DA800 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F79
                dc.w $9500 ! ((grp_F1A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F7C
                dc.w $9500 ! ((grp_F1A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1A20 / 2) >> 16)
                dc.w 1
