byte_2E03C8:    dc.b   0,  9,$5A,$40,$91,$85,$75,$62,$85,$5E
                                        ; DATA XREF: ROM:off_18B8   o
                dc.w sprite_24_32
                dc.w $784C
                dc.w $9500 ! ((grp_108F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_108F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $696C
                dc.w $9500 ! ((grp_12B440 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B440 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $613E
                dc.w $9500 ! ((grp_4E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $896C
                dc.w $9500 ! ((grp_177100 / 2) & $00FF)
                dc.w $9600 ! (((grp_177100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177100 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7084
                dc.w $9500 ! ((grp_9A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $694E
                dc.w $9500 ! ((grp_D2BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5945
                dc.w $9500 ! ((grp_B9840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6151
                dc.w $9500 ! ((grp_B9880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $514C
                dc.w $9500 ! ((grp_EBA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBA00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7056
                dc.w $9500 ! ((grp_EBA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBA20 / 2) >> 16)
                dc.w 1
