byte_2E6E96:    dc.b   0,  3,$74,$53,$92,$78,$7D,$64,$8A,$65
                                        ; DATA XREF: ROM:off_1C9C   o
                dc.w sprite_24_32
                dc.w $7A56
                dc.w $9500 ! ((grp_1036C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1036C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1036C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6A53
                dc.w $9500 ! ((grp_174AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_174AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7A76
                dc.w $9500 ! ((grp_CEA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C4E
                dc.w $9500 ! ((grp_CEA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEA40 / 2) >> 16)
                dc.w 2
