byte_2F25FC:    dc.b   0,  1,$77,$6A,$89,$8E,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_2710   o
                dc.w sprite_24_24
                dc.w $7571
                dc.w $9500 ! ((grp_14DB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_14DB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14DB80 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7789
                dc.w $9500 ! ((grp_DA740 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA740 / 2) >> 16)
                dc.w 2
