byte_2E83C2:    dc.b   0,  7,$6F,$69,$8E,$8F,$75,$81,$58,$74
                                        ; DATA XREF: ROM:off_1D64   o
                dc.w sprite_24_32
                dc.w $6F64
                dc.w $9500 ! ((grp_1033C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1033C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1033C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6F84
                dc.w $9500 ! ((grp_49500 / 2) & $00FF)
                dc.w $9600 ! (((grp_49500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5768
                dc.w $9500 ! ((grp_15C7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C7C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $876C
                dc.w $9500 ! ((grp_159A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_159A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $577D
                dc.w $9500 ! ((grp_186820 / 2) & $00FF)
                dc.w $9600 ! (((grp_186820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186820 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5675
                dc.w $9500 ! ((grp_E86C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E86C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E86C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8C
                dc.w $9500 ! ((grp_E5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9564
                dc.w $9500 ! ((grp_E5A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A20 / 2) >> 16)
                dc.w 1
