byte_2E72DA:    dc.b   0,  9,$6F,$66,$8E,$8F,$D3,$77,$A1,$63
                                        ; DATA XREF: ROM:off_1CCC   o
                dc.w sprite_24_32
                dc.w $756E
                dc.w $9500 ! ((grp_10B340 / 2) & $00FF)
                dc.w $9600 ! (((grp_10B340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10B340 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7D66
                dc.w $9500 ! ((grp_9B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B300 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $BB75
                dc.w $9500 ! ((grp_9B380 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $835E
                dc.w $9500 ! ((grp_189DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189DC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C88
                dc.w $9500 ! ((grp_D4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8588
                dc.w $9500 ! ((grp_D4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9B5F
                dc.w $9500 ! ((grp_D44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D44C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A865
                dc.w $9500 ! ((grp_D4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B26D
                dc.w $9500 ! ((grp_D4540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D77
                dc.w $9500 ! ((grp_ECC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECC80 / 2) >> 16)
                dc.w 1
