byte_2D68EC:    dc.b   0,  5,$73,$55,$92,$7A,$82,$4F,$8B,$59
                                        ; DATA XREF: ROM:off_1268   o
                dc.w sprite_32_32
                dc.w $6E49
                dc.w $9500 ! ((grp_26E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_26E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8E51
                dc.w $9500 ! ((grp_179E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_179E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6C69
                dc.w $9500 ! ((grp_9BD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5E61
                dc.w $9500 ! ((grp_D63C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D63C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D63C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $664C
                dc.w $9500 ! ((grp_EE2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE2E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E5F
                dc.w $9500 ! ((grp_EE300 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE300 / 2) >> 16)
                dc.w 1
