byte_2CF754:    dc.b   0,  1,$73,$7A,$8C,$8C,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_B80   o
                dc.w sprite_24_16
                dc.w $7180
                dc.w $9500 ! ((grp_157240 / 2) & $00FF)
                dc.w $9600 ! (((grp_157240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157240 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7978
                dc.w $9500 ! ((grp_183DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_183DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183DC0 / 2) >> 16)
                dc.w 3
