byte_2CC3D0:    dc.b   0,  1,$82,$82,$90,$8F,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_748   o
                dc.w sprite_24_16
                dc.w $8080
                dc.w $9500 ! ((grp_155BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_155BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8090
                dc.w $9500 ! ((grp_C6880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6880 / 2) >> 16)
                dc.w 2
