byte_2D37B0:    dc.b   0,  4,$87,$70,$D1,$8D,$AC,$7E,$AD,$7E
                                        ; DATA XREF: ROM:off_1030   o
                dc.w sprite_24_16
                dc.w $8D6E
                dc.w $9500 ! ((grp_1594C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1594C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1594C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $A576
                dc.w $9500 ! ((grp_159580 / 2) & $00FF)
                dc.w $9600 ! (((grp_159580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159580 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $C579
                dc.w $9500 ! ((grp_172240 / 2) & $00FF)
                dc.w $9600 ! (((grp_172240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172240 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $857E
                dc.w $9500 ! ((grp_97F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $BD7B
                dc.w $9500 ! ((grp_B2CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2CC0 / 2) >> 16)
                dc.w 2
