byte_2CCF6C:    dc.b   0,  3,$67,$6F,$98,$8D,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_858   o
                dc.w sprite_32_32
                dc.w $6D6F
                dc.w $9500 ! ((grp_10800 / 2) & $00FF)
                dc.w $9600 ! (((grp_10800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10800 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $8D78
                dc.w $9500 ! ((grp_191D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_191D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9570
                dc.w $9500 ! ((grp_191DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_191DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6575
                dc.w $9500 ! ((grp_B0A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0A40 / 2) >> 16)
                dc.w 2
