byte_2DA47A:    dc.b   0, $A,$56,$51,$7A,$90,$68,$70,$6B,$5B
                                        ; DATA XREF: ROM:off_149C   o
                dc.w sprite_24_32
                dc.w $5F70
                dc.w $9500 ! ((grp_100CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_100CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6750
                dc.w $9500 ! ((grp_5FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5FD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $5F90
                dc.w $9500 ! ((grp_185620 / 2) & $00FF)
                dc.w $9600 ! (((grp_185620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4F50
                dc.w $9500 ! ((grp_194380 / 2) & $00FF)
                dc.w $9600 ! (((grp_194380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5F58
                dc.w $9500 ! ((grp_195100 / 2) & $00FF)
                dc.w $9600 ! (((grp_195100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195100 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7750
                dc.w $9500 ! ((grp_195160 / 2) & $00FF)
                dc.w $9600 ! (((grp_195160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195160 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5750
                dc.w $9500 ! ((grp_CAFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7788
                dc.w $9500 ! ((grp_B3500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $556C
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5788
                dc.w $9500 ! ((grp_E58A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5F48
                dc.w $9500 ! ((grp_E59A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E59A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E59A0 / 2) >> 16)
                dc.w 1
