byte_2F7A86:    dc.b   0, $F,$64,$42,$9E,$83,$96,$6E,$97,$6E
                                        ; DATA XREF: ROM:off_2BB4   o
                dc.w sprite_24_32
                dc.w $675C
                dc.w $9500 ! ((grp_119440 / 2) & $00FF)
                dc.w $9600 ! (((grp_119440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7F54
                dc.w $9500 ! ((grp_1195C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1195C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1195C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $B756
                dc.w $9500 ! ((grp_151720 / 2) & $00FF)
                dc.w $9600 ! (((grp_151720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151720 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $975C
                dc.w $9500 ! ((grp_6EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6EE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7F74
                dc.w $9500 ! ((grp_169C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_169C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $977C
                dc.w $9500 ! ((grp_90700 / 2) & $00FF)
                dc.w $9600 ! (((grp_90700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5F64
                dc.w $9500 ! ((grp_AE100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $677C
                dc.w $9500 ! ((grp_AE180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A754
                dc.w $9500 ! ((grp_AE200 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $AF5C
                dc.w $9500 ! ((grp_19F2A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F2A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F2A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F7C
                dc.w $9500 ! ((grp_DDA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7784
                dc.w $9500 ! ((grp_DDAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F8C
                dc.w $9500 ! ((grp_C33C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C33C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C33C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AE44
                dc.w $9500 ! ((grp_C3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F84
                dc.w $9500 ! ((grp_F5DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $998C
                dc.w $9500 ! ((grp_F5DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5DC0 / 2) >> 16)
                dc.w 1
