byte_2F38FE:    dc.b   0,  7,$6C,$5D,$98,$8D,$77,$75,$78,$75
                                        ; DATA XREF: ROM:off_27DC   o
                dc.w sprite_24_32
                dc.w $786B
                dc.w $9500 ! ((grp_1144C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1144C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1144C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $685B
                dc.w $9500 ! ((grp_55300 / 2) & $00FF)
                dc.w $9600 ! (((grp_55300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5066
                dc.w $9500 ! ((grp_167440 / 2) & $00FF)
                dc.w $9600 ! (((grp_167440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167440 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9073
                dc.w $9500 ! ((grp_8CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $686B
                dc.w $9500 ! ((grp_DB800 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $758B
                dc.w $9500 ! ((grp_F2AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $898B
                dc.w $9500 ! ((grp_F2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9083
                dc.w $9500 ! ((grp_F2B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2B20 / 2) >> 16)
                dc.w 1
