byte_2EAA26:    dc.b   0,  4,$71,$6C,$91,$88,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_1F74   o
                dc.w sprite_24_24
                dc.w $7671
                dc.w $9500 ! ((grp_149FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_149FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149FE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $6E72
                dc.w $9500 ! ((grp_19B820 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B820 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8E72
                dc.w $9500 ! ((grp_19B880 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B880 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7969
                dc.w $9500 ! ((grp_D73C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D73C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D73C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E89
                dc.w $9500 ! ((grp_D7340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7340 / 2) >> 16)
                dc.w 2
