byte_2EFC92:    dc.b   0,  2,$73,$7B,$89,$8D,$7E,$84,$7F,$84
                                        ; DATA XREF: ROM:off_2584   o
                dc.w sprite_24_16
                dc.w $7481
                dc.w $9500 ! ((grp_165B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_165B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7C79
                dc.w $9500 ! ((grp_DA080 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C85
                dc.w $9500 ! ((grp_F1340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1340 / 2) >> 16)
                dc.w 1
