byte_2D8298:    dc.b   0,  4,$75,$68,$89,$84,$7E,$60,$8C,$66
                                        ; DATA XREF: ROM:off_1378   o
                dc.w sprite_32_16
                dc.w $786C
                dc.w $9500 ! ((grp_49E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $795C
                dc.w $9500 ! ((grp_15A6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A6C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $787C
                dc.w $9500 ! ((grp_79480 / 2) & $00FF)
                dc.w $9600 ! (((grp_79480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7070
                dc.w $9500 ! ((grp_194EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $887C
                dc.w $9500 ! ((grp_E6B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6B60 / 2) >> 16)
                dc.w 1
