byte_2EC43E:    dc.b   0,  2,$6E,$6C,$91,$8D,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_20E4   o
                dc.w sprite_32_32
                dc.w $6C6A
                dc.w $9500 ! ((grp_30200 / 2) & $00FF)
                dc.w $9600 ! (((grp_30200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30200 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $8C71
                dc.w $9500 ! ((grp_19C060 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C060 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $768A
                dc.w $9500 ! ((grp_D7FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7FC0 / 2) >> 16)
                dc.w 2
