byte_2DED96:    dc.b   0,  7,$70,$64,$91,$8E,$80,$73,$6C,$6D
                                        ; DATA XREF: ROM:off_17BC   o
                dc.w sprite_32_32
                dc.w $7167
                dc.w $9500 ! ((grp_26A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_26A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7387
                dc.w $9500 ! ((grp_50500 / 2) & $00FF)
                dc.w $9600 ! (((grp_50500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $616F
                dc.w $9500 ! ((grp_85C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9174
                dc.w $9500 ! ((grp_85C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7157
                dc.w $9500 ! ((grp_9B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6167
                dc.w $9500 ! ((grp_D6280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D5F
                dc.w $9500 ! ((grp_EE0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE0C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A5F
                dc.w $9500 ! ((grp_EE0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE0E0 / 2) >> 16)
                dc.w 1
