byte_2D1106:    dc.b   0,  9,$59,$62,$84,$8E,$69,$78,$6A,$78
                                        ; DATA XREF: ROM:off_DEC   o
                dc.w sprite_32_24
                dc.w $7361
                dc.w $9500 ! ((grp_1213C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1213C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1213C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6379
                dc.w $9500 ! ((grp_47900 / 2) & $00FF)
                dc.w $9600 ! (((grp_47900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8C53
                dc.w $9500 ! ((grp_157D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_157D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $9B6A
                dc.w $9500 ! ((grp_157E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_157E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157E40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6489
                dc.w $9500 ! ((grp_97600 / 2) & $00FF)
                dc.w $9600 ! (((grp_97600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7459
                dc.w $9500 ! ((grp_1842A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1842A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1842A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8379
                dc.w $9500 ! ((grp_C9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B69
                dc.w $9500 ! ((grp_B1BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $936D
                dc.w $9500 ! ((grp_B1C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C4B
                dc.w $9500 ! ((grp_E3860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3860 / 2) >> 16)
                dc.w 1
