byte_2E8720:    dc.b   0,  8,$6F,$6C,$8E,$8F,$98,$59,$75,$6B
                                        ; DATA XREF: ROM:off_1D80   o
                dc.w sprite_24_32
                dc.w $746C
                dc.w $9500 ! ((grp_103540 / 2) & $00FF)
                dc.w $9600 ! (((grp_103540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $735C
                dc.w $9500 ! ((grp_7C080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $805B
                dc.w $9500 ! ((grp_186A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_186A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6C6C
                dc.w $9500 ! ((grp_196600 / 2) & $00FF)
                dc.w $9600 ! (((grp_196600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_CE6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838C
                dc.w $9500 ! ((grp_CE640 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9254
                dc.w $9500 ! ((grp_CE680 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $646E
                dc.w $9500 ! ((grp_B6200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C70
                dc.w $9500 ! ((grp_B61C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B61C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B61C0 / 2) >> 16)
                dc.w 2
