byte_2D95F8:    dc.b   0,  4,$67,$6F,$94,$8E,$7D,$7E,$7E,$7E
                                        ; DATA XREF: ROM:off_1430   o
                dc.w sprite_32_24
                dc.w $7478
                dc.w $9500 ! ((grp_127540 / 2) & $00FF)
                dc.w $9600 ! (((grp_127540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127540 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6C78
                dc.w $9500 ! ((grp_196B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_196B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8774
                dc.w $9500 ! ((grp_CF200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6475
                dc.w $9500 ! ((grp_B6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F6C
                dc.w $9500 ! ((grp_E9060 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9060 / 2) >> 16)
                dc.w 1
