byte_2F9756:    dc.b   0,  1,$99,$7F,$AE,$88,$A3,$83,$A4,$83
                                        ; DATA XREF: ROM:off_2D84   o
                dc.w sprite_24_8
                dc.w $9A7D
                dc.w $9500 ! ((grp_190120 / 2) & $00FF)
                dc.w $9600 ! (((grp_190120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190120 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9E85
                dc.w $9500 ! ((grp_DE600 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE600 / 2) >> 16)
                dc.w 2
