byte_2F32BC:    dc.b   0, $A,$6F,$5F,$92,$91,$7C,$78,$7D,$78
                                        ; DATA XREF: ROM:off_27A0   o
                dc.w sprite_32_16
                dc.w $707D
                dc.w $9500 ! ((grp_55800 / 2) & $00FF)
                dc.w $9600 ! (((grp_55800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6D5D
                dc.w $9500 ! ((grp_6D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7D5D
                dc.w $9500 ! ((grp_17DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DD00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7D75
                dc.w $9500 ! ((grp_18E5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E5C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D70
                dc.w $9500 ! ((grp_DBB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D65
                dc.w $9500 ! ((grp_DBAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $907D
                dc.w $9500 ! ((grp_C0E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6563
                dc.w $9500 ! ((grp_F2E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $778D
                dc.w $9500 ! ((grp_F2E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $878D
                dc.w $9500 ! ((grp_F2E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $945D
                dc.w $9500 ! ((grp_F2EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2EA0 / 2) >> 16)
                dc.w 1
