byte_2EDDB8:    dc.b   0,  2,$76,$7C,$88,$91,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_2318   o
                dc.w sprite_16_24
                dc.w $797C
                dc.w $9500 ! ((grp_17BB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BB40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $8779
                dc.w $9500 ! ((grp_BF000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7189
                dc.w $9500 ! ((grp_F04C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F04C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F04C0 / 2) >> 16)
                dc.w 1
