byte_2D446A:    dc.b   0,  5,$6F,$68,$92,$90,$80,$79,$81,$79
                                        ; DATA XREF: ROM:off_10CC   o
                dc.w sprite_32_32
                dc.w $7171
                dc.w $9500 ! ((grp_17800 / 2) & $00FF)
                dc.w $9600 ! (((grp_17800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7469
                dc.w $9500 ! ((grp_184DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184DE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A61
                dc.w $9500 ! ((grp_CAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $917B
                dc.w $9500 ! ((grp_B3040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697C
                dc.w $9500 ! ((grp_E54A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E54A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E54A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C67
                dc.w $9500 ! ((grp_E54C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E54C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E54C0 / 2) >> 16)
                dc.w 1
