byte_2E71A8:    dc.b   0,  5,$6F,$66,$8E,$8F,$68,$61,$72,$66
                                        ; DATA XREF: ROM:off_1CC0   o
                dc.w sprite_24_32
                dc.w $6C5D
                dc.w $9500 ! ((grp_10AD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10AD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10AD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $5C5D
                dc.w $9500 ! ((grp_1786C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1786C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1786C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6E85
                dc.w $9500 ! ((grp_83B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_83B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8483
                dc.w $9500 ! ((grp_83C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_83C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $767D
                dc.w $9500 ! ((grp_D4040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8468
                dc.w $9500 ! ((grp_ECB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB60 / 2) >> 16)
                dc.w 1
