byte_2E2F36:    dc.b   0,  9,$6F,$43,$8E,$8F,$7A,$41,$7A,$41
                                        ; DATA XREF: ROM:off_1A74   o
                dc.w sprite_24_32
                dc.w $663E
                dc.w $9500 ! ((grp_106540 / 2) & $00FF)
                dc.w $9600 ! (((grp_106540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $705E
                dc.w $9500 ! ((grp_7FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $786E
                dc.w $9500 ! ((grp_A6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $805E
                dc.w $9500 ! ((grp_A6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7E56
                dc.w $9500 ! ((grp_D1580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $884E
                dc.w $9500 ! ((grp_D15C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D15C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D15C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8946
                dc.w $9500 ! ((grp_D1600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $886B
                dc.w $9500 ! ((grp_B8940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F87
                dc.w $9500 ! ((grp_EAC20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAC20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAC20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7689
                dc.w $9500 ! ((grp_EAC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAC40 / 2) >> 16)
                dc.w 1
