byte_2D21BC:    dc.b   0,  6,$6A,$42,$98,$7B,$7F,$6D,$80,$6D
                                        ; DATA XREF: ROM:off_EA0   o
                dc.w sprite_32_16
                dc.w $7086
                dc.w $9500 ! ((grp_48700 / 2) & $00FF)
                dc.w $9600 ! (((grp_48700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_48700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7556
                dc.w $9500 ! ((grp_158A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_158A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7566
                dc.w $9500 ! ((grp_1588C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1588C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1588C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $707E
                dc.w $9500 ! ((grp_97A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_97A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7976
                dc.w $9500 ! ((grp_C9BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $704A
                dc.w $9500 ! ((grp_B2440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $784E
                dc.w $9500 ! ((grp_E4140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4140 / 2) >> 16)
                dc.w 1
