byte_2CD78C:    dc.b   0,  1,$64,$50,$7C,$5C,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_910   o
                dc.w sprite_32_24
                dc.w $614B
                dc.w $9500 ! ((grp_11F2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11F2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11F2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7965
                dc.w $9500 ! ((grp_73E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_73E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73E00 / 2) >> 16)
                dc.w 4
