byte_2F0126:    dc.b   0, $C,$3D, $A,$B3,$4D,$78,$65,$79,$65
                                        ; DATA XREF: ROM:000025BC   o
                dc.w sprite_24_32
                dc.w $7E53
                dc.w $9500 ! ((grp_1129C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1129C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1129C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7E33
                dc.w $9500 ! ((grp_112B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_112B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $3E3B
                dc.w $9500 ! ((grp_53C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8673
                dc.w $9500 ! ((grp_6B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $9E2B
                dc.w $9500 ! ((grp_166240 / 2) & $00FF)
                dc.w $9600 ! (((grp_166240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166240 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6E35
                dc.w $9500 ! ((grp_17C5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C5C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5E36
                dc.w $9500 ! ((grp_8B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $862B
                dc.w $9500 ! ((grp_DA280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C93
                dc.w $9500 ! ((grp_BFA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9630
                dc.w $9500 ! ((grp_BFAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3641
                dc.w $9500 ! ((grp_F1580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7656
                dc.w $9500 ! ((grp_F15A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F15A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F15A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B62B
                dc.w $9500 ! ((grp_F15C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F15C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F15C0 / 2) >> 16)
                dc.w 1
