byte_2D1188:    dc.b   0,  9,$73,$5C,$92,$8E,$8D,$72,$8E,$72
                                        ; DATA XREF: ROM:off_DF0   o
                dc.w sprite_32_32
                dc.w $7461
                dc.w $9500 ! ((grp_15000 / 2) & $00FF)
                dc.w $9600 ! (((grp_15000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6481
                dc.w $9500 ! ((grp_47A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9459
                dc.w $9500 ! ((grp_5D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $6C69
                dc.w $9500 ! ((grp_193060 / 2) & $00FF)
                dc.w $9600 ! (((grp_193060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193060 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $A459
                dc.w $9500 ! ((grp_1930C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1930C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1930C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5879
                dc.w $9500 ! ((grp_C91C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C91C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C91C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5881
                dc.w $9500 ! ((grp_E3880 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8059
                dc.w $9500 ! ((grp_E38A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E38A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E38A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C59
                dc.w $9500 ! ((grp_E38C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E38C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E38C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9751
                dc.w $9500 ! ((grp_E38E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E38E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E38E0 / 2) >> 16)
                dc.w 1
