byte_2E880C:    dc.b   0,  7,$6F,$69,$8E,$8F,$79,$68,$5D,$6F
                                        ; DATA XREF: ROM:off_1D88   o
                dc.w sprite_32_16
                dc.w $7084
                dc.w $9500 ! ((grp_49500 / 2) & $00FF)
                dc.w $9600 ! (((grp_49500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7864
                dc.w $9500 ! ((grp_61000 / 2) & $00FF)
                dc.w $9600 ! (((grp_61000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $886C
                dc.w $9500 ! ((grp_159A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_159A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6069
                dc.w $9500 ! ((grp_7C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7065
                dc.w $9500 ! ((grp_196660 / 2) & $00FF)
                dc.w $9600 ! (((grp_196660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196660 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $586C
                dc.w $9500 ! ((grp_B62C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B62C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B62C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $908C
                dc.w $9500 ! ((grp_E5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9664
                dc.w $9500 ! ((grp_E5A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A20 / 2) >> 16)
                dc.w 1
