byte_2F374A:    dc.b   0,  9,$69,$5F,$96,$89,$7F,$77,$80,$77
                                        ; DATA XREF: ROM:off_27CC   o
                dc.w sprite_16_32
                dc.w $7D5E
                dc.w $9500 ! ((grp_6D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6D5D
                dc.w $9500 ! ((grp_17DF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DF40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7D7E
                dc.w $9500 ! ((grp_17DE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DE80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6D7D
                dc.w $9500 ! ((grp_8D180 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9280
                dc.w $9500 ! ((grp_8D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8D66
                dc.w $9500 ! ((grp_ACD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $5D64
                dc.w $9500 ! ((grp_C0FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $556A
                dc.w $9500 ! ((grp_F3100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6564
                dc.w $9500 ! ((grp_F30C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F30C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F30C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9574
                dc.w $9500 ! ((grp_F30E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F30E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F30E0 / 2) >> 16)
                dc.w 1
