byte_2DC918:    dc.b   0,  5,$76,$5A,$91,$98,$89,$77,$82,$6D
                                        ; DATA XREF: ROM:off_1648   o
                dc.w sprite_32_24
                dc.w $7470
                dc.w $9500 ! ((grp_124E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_124E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_124E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7E88
                dc.w $9500 ! ((grp_15B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8350
                dc.w $9500 ! ((grp_173980 / 2) & $00FF)
                dc.w $9600 ! (((grp_173980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7668
                dc.w $9500 ! ((grp_185920 / 2) & $00FF)
                dc.w $9600 ! (((grp_185920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $968D
                dc.w $9500 ! ((grp_CCDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8298
                dc.w $9500 ! ((grp_E7260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7260 / 2) >> 16)
                dc.w 1
