byte_2D6D12:    dc.b   0,  6,$74,$55,$92,$A0,$81,$3C,$82,$5F
                                        ; DATA XREF: ROM:off_128C   o
                dc.w sprite_32_32
                dc.w $738A
                dc.w $9500 ! ((grp_27200 / 2) & $00FF)
                dc.w $9600 ! (((grp_27200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $79AA
                dc.w $9500 ! ((grp_66500 / 2) & $00FF)
                dc.w $9600 ! (((grp_66500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66500 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7E3A
                dc.w $9500 ! ((grp_A9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7982
                dc.w $9500 ! ((grp_18B0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B0E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7E5A
                dc.w $9500 ! ((grp_19A740 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8172
                dc.w $9500 ! ((grp_BCD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $71A7
                dc.w $9500 ! ((grp_EE4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE4C0 / 2) >> 16)
                dc.w 1
