byte_2FAAC6:    dc.b   0, $A,$78,$5F,$99,$8A,$8F,$6E,$90,$6E
                                        ; DATA XREF: ROM:off_2E34   o
                dc.w sprite_32_32
                dc.w $7855
                dc.w $9500 ! ((grp_42800 / 2) & $00FF)
                dc.w $9600 ! (((grp_42800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $6F75
                dc.w $9500 ! ((grp_11B6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $9855
                dc.w $9500 ! ((grp_180AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_180AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $937D
                dc.w $9500 ! ((grp_91800 / 2) & $00FF)
                dc.w $9600 ! (((grp_91800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E4D
                dc.w $9500 ! ((grp_190840 / 2) & $00FF)
                dc.w $9600 ! (((grp_190840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190840 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8775
                dc.w $9500 ! ((grp_1908A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1908A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1908A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $705D
                dc.w $9500 ! ((grp_19FB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FB40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $877D
                dc.w $9500 ! ((grp_C4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A380
                dc.w $9500 ! ((grp_F7120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A86A
                dc.w $9500 ! ((grp_F7140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A858
                dc.w $9500 ! ((grp_F7160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7160 / 2) >> 16)
                dc.w 1
