byte_2DAD3A:    dc.b   0,  6,$6E,$78,$8D,$8B,$9D,$7F,$73,$7C
                                        ; DATA XREF: ROM:off_1504   o
                dc.w sprite_24_24
                dc.w $6B76
                dc.w $9500 ! ((grp_144CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_144CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144CA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $8378
                dc.w $9500 ! ((grp_62200 / 2) & $00FF)
                dc.w $9600 ! (((grp_62200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $6D6E
                dc.w $9500 ! ((grp_CFD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $738E
                dc.w $9500 ! ((grp_CFD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $937A
                dc.w $9500 ! ((grp_B7280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8398
                dc.w $9500 ! ((grp_E98E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E98E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E98E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B7C
                dc.w $9500 ! ((grp_E9900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9900 / 2) >> 16)
                dc.w 1
