byte_2D523E:    dc.b   0,  5,$6F,$59,$8E,$8F,$7A,$73,$73,$5E
                                        ; DATA XREF: ROM:off_1174   o
                dc.w sprite_24_32
                dc.w $6B71
                dc.w $9500 ! ((grp_FE5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6A59
                dc.w $9500 ! ((grp_140EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_140EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140EC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $6F51
                dc.w $9500 ! ((grp_CB680 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8389
                dc.w $9500 ! ((grp_CB6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $625F
                dc.w $9500 ! ((grp_B3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8375
                dc.w $9500 ! ((grp_B3940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3940 / 2) >> 16)
                dc.w 2
