byte_2FBA8C:    dc.b   0,  5,$6F,$6E,$96,$98,$82,$83,$83,$83
                                        ; DATA XREF: ROM:off_2FC0   o
                dc.w sprite_32_32
                dc.w $7970
                dc.w $9500 ! ((grp_44000 / 2) & $00FF)
                dc.w $9600 ! (((grp_44000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $728F
                dc.w $9500 ! ((grp_16B340 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A67
                dc.w $9500 ! ((grp_91E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_91E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8368
                dc.w $9500 ! ((grp_DF280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A8F
                dc.w $9500 ! ((grp_F7920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A90
                dc.w $9500 ! ((grp_F7940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7940 / 2) >> 16)
                dc.w 1
