byte_2E0BA4:    dc.b   0, $A,$7F,$4A,$F7,$8B,$BB,$6A,$AA,$6B
                                        ; DATA XREF: ROM:off_1908   o
                dc.w sprite_32_32
                dc.w $9A60
                dc.w $9500 ! ((grp_22E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_22E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $BA68
                dc.w $9500 ! ((grp_23000 / 2) & $00FF)
                dc.w $9600 ! (((grp_23000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $D248
                dc.w $9500 ! ((grp_23200 / 2) & $00FF)
                dc.w $9600 ! (((grp_23200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $DA68
                dc.w $9500 ! ((grp_1468C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1468C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1468C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7A66
                dc.w $9500 ! ((grp_4EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4EB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $BA58
                dc.w $9500 ! ((grp_160180 / 2) & $00FF)
                dc.w $9600 ! (((grp_160180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160180 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $F256
                dc.w $9500 ! ((grp_A7880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7880 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $C888
                dc.w $9500 ! ((grp_189280 / 2) & $00FF)
                dc.w $9600 ! (((grp_189280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189280 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $AA80
                dc.w $9500 ! ((grp_D2DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $C250
                dc.w $9500 ! ((grp_D2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $DA80
                dc.w $9500 ! ((grp_EBDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBDE0 / 2) >> 16)
                dc.w 1
