byte_2CFBD0:    dc.b   0,  1,$71,$7D,$8E,$86,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_C18   o
                dc.w sprite_24_16
                dc.w $6F7B
                dc.w $9500 ! ((grp_157480 / 2) & $00FF)
                dc.w $9600 ! (((grp_157480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157480 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8783
                dc.w $9500 ! ((grp_C89C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C89C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C89C0 / 2) >> 16)
                dc.w 2
