byte_2CE692:    dc.b   0,  1,$78,$79,$87,$87,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_ACC   o
                dc.w sprite_24_16
                dc.w $7677
                dc.w $9500 ! ((grp_156340 / 2) & $00FF)
                dc.w $9600 ! (((grp_156340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7B87
                dc.w $9500 ! ((grp_C7600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7600 / 2) >> 16)
                dc.w 2
