byte_2F0DBA:    dc.b   0, $C,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_2614   o
                dc.w sprite_32_32
                dc.w $5D4D
                dc.w $9500 ! ((grp_36200 / 2) & $00FF)
                dc.w $9600 ! (((grp_36200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D4D
                dc.w $9500 ! ((grp_36400 / 2) & $00FF)
                dc.w $9600 ! (((grp_36400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $846B
                dc.w $9500 ! ((grp_36600 / 2) & $00FF)
                dc.w $9600 ! (((grp_36600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $5D6D
                dc.w $9500 ! ((grp_14D820 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D820 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $5D83
                dc.w $9500 ! ((grp_14D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D700 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8D8B
                dc.w $9500 ! ((grp_166300 / 2) & $00FF)
                dc.w $9600 ! (((grp_166300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $756B
                dc.w $9500 ! ((grp_ABF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7D6D
                dc.w $9500 ! ((grp_AC000 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9D5B
                dc.w $9500 ! ((grp_BFF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
