byte_2D6830:    dc.b   0,  7,$6B,$4A,$9C,$81,$83,$65,$84,$65
                                        ; DATA XREF: ROM:off_1260   o
                dc.w sprite_32_32
                dc.w $7148
                dc.w $9500 ! ((grp_24A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_24A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7A68
                dc.w $9500 ! ((grp_147640 / 2) & $00FF)
                dc.w $9600 ! (((grp_147640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147640 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $6958
                dc.w $9500 ! ((grp_199600 / 2) & $00FF)
                dc.w $9600 ! (((grp_199600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199600 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9156
                dc.w $9500 ! ((grp_199660 / 2) & $00FF)
                dc.w $9600 ! (((grp_199660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199660 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $975A
                dc.w $9500 ! ((grp_1996C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1996C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1996C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A80
                dc.w $9500 ! ((grp_D4740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7168
                dc.w $9500 ! ((grp_ECE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECE00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9275
                dc.w $9500 ! ((grp_ECDE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECDE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECDE0 / 2) >> 16)
                dc.w 1
