byte_2FF9AA:    dc.b   0,  4,$74,$18,$89,$85,$80,$52,$81,$52
                                        ; DATA XREF: ROM:off_35B4   o
                dc.w sprite_16_32
                dc.w $771D
                dc.w $9500 ! ((grp_71F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_71F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $793D
                dc.w $9500 ! ((grp_72000 / 2) & $00FF)
                dc.w $9600 ! (((grp_72000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $7C5D
                dc.w $9500 ! ((grp_AFA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $767D
                dc.w $9500 ! ((grp_1918C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1918C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1918C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7B85
                dc.w $9500 ! ((grp_F95C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F95C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F95C0 / 2) >> 16)
                dc.w 1
