byte_2F7EBE:    dc.b   0,  7,$7B,$7C,$A1,$B5,$8E,$98,$8F,$98
                                        ; DATA XREF: ROM:off_2BE4   o
                dc.w sprite_8_24
                dc.w $8288
                dc.w $9500 ! ((grp_19F120 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F120 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A7D
                dc.w $9500 ! ((grp_C3080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A7D
                dc.w $9500 ! ((grp_C3040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $827C
                dc.w $9500 ! ((grp_F5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A94
                dc.w $9500 ! ((grp_F5960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8BA6
                dc.w $9500 ! ((grp_F5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9284
                dc.w $9500 ! ((grp_F5940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A1AE
                dc.w $9500 ! ((grp_F5920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5920 / 2) >> 16)
                dc.w 1
