byte_2F6BE8:    dc.b   0,$16,$7D,$4E,$A2,$80,$82,$7E,$83,$7E
                                        ; DATA XREF: ROM:off_2B68   o
                dc.w sprite_24_32
                dc.w $8659
                dc.w $9500 ! ((grp_117340 / 2) & $00FF)
                dc.w $9600 ! (((grp_117340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7649
                dc.w $9500 ! ((grp_6E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $B634
                dc.w $9500 ! ((grp_6E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_1696C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1696C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1696C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7B86
                dc.w $9500 ! ((grp_169780 / 2) & $00FF)
                dc.w $9600 ! (((grp_169780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169780 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8649
                dc.w $9500 ! ((grp_1690C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1690C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1690C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $427E
                dc.w $9500 ! ((grp_8F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $927F
                dc.w $9500 ! ((grp_8F980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9E50
                dc.w $9500 ! ((grp_8EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A866
                dc.w $9500 ! ((grp_8FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B754
                dc.w $9500 ! ((grp_8FA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5888
                dc.w $9500 ! ((grp_9F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $C638
                dc.w $9500 ! ((grp_19EE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EE20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9F76
                dc.w $9500 ! ((grp_DD380 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AE45
                dc.w $9500 ! ((grp_C2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6280
                dc.w $9500 ! ((grp_F53A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F53A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F53A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C79
                dc.w $9500 ! ((grp_F4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F41
                dc.w $9500 ! ((grp_F4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E60
                dc.w $9500 ! ((grp_F4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A648
                dc.w $9500 ! ((grp_F4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A660
                dc.w $9500 ! ((grp_F4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AD7B
                dc.w $9500 ! ((grp_F53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F53C0 / 2) >> 16)
                dc.w 1
