byte_2CCDD4:    dc.b   0,  5,$7A,$62,$84,$9D,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_828   o
                dc.w sprite_16_16
                dc.w $7890
                dc.w $9500 ! ((grp_73100 / 2) & $00FF)
                dc.w $9600 ! (((grp_73100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7860
                dc.w $9500 ! ((grp_73080 / 2) & $00FF)
                dc.w $9600 ! (((grp_73080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7870
                dc.w $9500 ! ((grp_C6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7878
                dc.w $9500 ! ((grp_C6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7880
                dc.w $9500 ! ((grp_C6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7888
                dc.w $9500 ! ((grp_C6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6F40 / 2) >> 16)
                dc.w 2
