byte_2EB2B6:    dc.b   0,  3,$70,$75,$89,$8C,$7D,$74,$7E,$74
                                        ; DATA XREF: ROM:off_1FF4   o
                dc.w sprite_24_24
                dc.w $766B
                dc.w $9500 ! ((grp_14A220 / 2) & $00FF)
                dc.w $9600 ! (((grp_14A220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14A220 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6F83
                dc.w $9500 ! ((grp_1636C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1636C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1636C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6E5B
                dc.w $9500 ! ((grp_18BE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BE60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A63
                dc.w $9500 ! ((grp_D7980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7980 / 2) >> 16)
                dc.w 2
