byte_2ED616:    dc.b   0,  4,$72,$64,$8E,$95,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_22B4   o
                dc.w sprite_16_32
                dc.w $7871
                dc.w $9500 ! ((grp_69000 / 2) & $00FF)
                dc.w $9600 ! (((grp_69000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_69000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7861
                dc.w $9500 ! ((grp_89280 / 2) & $00FF)
                dc.w $9600 ! (((grp_89280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $706A
                dc.w $9500 ! ((grp_AAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8866
                dc.w $9500 ! ((grp_19C840 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C840 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $906A
                dc.w $9500 ! ((grp_BED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BED80 / 2) >> 16)
                dc.w 2
