byte_2EF9A6:    dc.b   0,  8,$5F,$16,$97,$33,$7B,$24,$7C,$24
                                        ; DATA XREF: ROM:off_2544   o
                dc.w sprite_16_16
                dc.w $6313
                dc.w $9500 ! ((grp_8A980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8A980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8A980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7318
                dc.w $9500 ! ((grp_8AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8AA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8314
                dc.w $9500 ! ((grp_8AA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8AA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8AA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B2E
                dc.w $9500 ! ((grp_D9EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9317
                dc.w $9500 ! ((grp_BF880 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B19
                dc.w $9500 ! ((grp_F1220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $632C
                dc.w $9500 ! ((grp_F1240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B31
                dc.w $9500 ! ((grp_F1260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B2C
                dc.w $9500 ! ((grp_F1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1280 / 2) >> 16)
                dc.w 1
