byte_2D3BC0:    dc.b   0,  5,$6D,$68,$90,$82,$7F,$71,$80,$71
                                        ; DATA XREF: ROM:off_1068   o
                dc.w sprite_24_24
                dc.w $6969
                dc.w $9500 ! ((grp_140380 / 2) & $00FF)
                dc.w $9600 ! (((grp_140380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140380 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $815D
                dc.w $9500 ! ((grp_5E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E600 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $6C81
                dc.w $9500 ! ((grp_E4940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7981
                dc.w $9500 ! ((grp_E4920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $817D
                dc.w $9500 ! ((grp_E48E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E48E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E48E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $915D
                dc.w $9500 ! ((grp_E4900 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4900 / 2) >> 16)
                dc.w 1
