byte_2D93F0:    dc.b   0,  7,$67,$2B,$94,$5B,$7D,$43,$7E,$43
                                        ; DATA XREF: ROM:off_1420   o
                dc.w sprite_32_24
                dc.w $6D40
                dc.w $9500 ! ((grp_127240 / 2) & $00FF)
                dc.w $9600 ! (((grp_127240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_127240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6F38
                dc.w $9500 ! ((grp_186FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_186FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186FA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8828
                dc.w $9500 ! ((grp_CF180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6541
                dc.w $9500 ! ((grp_B6AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D42
                dc.w $9500 ! ((grp_B6B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7358
                dc.w $9500 ! ((grp_E8F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8558
                dc.w $9500 ! ((grp_E8F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F30
                dc.w $9500 ! ((grp_E8F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8F60 / 2) >> 16)
                dc.w 1
