byte_2D2A9E:    dc.b   0,  5,$70,$5F,$99,$78,$82,$6D,$83,$6D
                                        ; DATA XREF: ROM:off_F0C   o
                dc.w sprite_16_24
                dc.w $6E61
                dc.w $9500 ! ((grp_171E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_171E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $865D
                dc.w $9500 ! ((grp_171F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_171F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7E5F
                dc.w $9500 ! ((grp_A4B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $965D
                dc.w $9500 ! ((grp_B2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6775
                dc.w $9500 ! ((grp_E4AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8675
                dc.w $9500 ! ((grp_E4AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4AE0 / 2) >> 16)
                dc.w 1
