byte_2DC130:    dc.b   0,  5,$78,$5B,$A7,$90,$8C,$64,$8D,$64
                                        ; DATA XREF: ROM:off_15F8   o
                dc.w sprite_24_32
                dc.w $8755
                dc.w $9500 ! ((grp_10DEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10DEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10DEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $7F5C
                dc.w $9500 ! ((grp_19AB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AB60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9F6A
                dc.w $9500 ! ((grp_D6740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F55
                dc.w $9500 ! ((grp_BD140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $775C
                dc.w $9500 ! ((grp_BD180 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F55
                dc.w $9500 ! ((grp_BD1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD1C0 / 2) >> 16)
                dc.w 2
