byte_2E916A:    dc.b   0,  4,$64,$46,$72,$8E,$6D,$5D,$6C,$4F
                                        ; DATA XREF: ROM:off_1E1C   o
                dc.w sprite_16_16
                dc.w $6245
                dc.w $9500 ! ((grp_7ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7ED00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $726D
                dc.w $9500 ! ((grp_197440 / 2) & $00FF)
                dc.w $9600 ! (((grp_197440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D5D
                dc.w $9500 ! ((grp_B7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $623D
                dc.w $9500 ! ((grp_E9D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A55
                dc.w $9500 ! ((grp_E9DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9DA0 / 2) >> 16)
                dc.w 1
