byte_2E2462:    dc.b   0,  2,$6F,$70,$8E,$8F,$7C,$7B,$85,$72
                                        ; DATA XREF: ROM:off_1A14   o
                dc.w sprite_32_32
                dc.w $6870
                dc.w $9500 ! ((grp_1B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1B600 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $886D
                dc.w $9500 ! ((grp_195D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_195D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7868
                dc.w $9500 ! ((grp_CD800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD800 / 2) >> 16)
                dc.w 2
