byte_2D492E:    dc.b   0,  9,$6B,$5F,$91,$95,$83,$7B,$7B,$6F
                                        ; DATA XREF: ROM:off_1104   o
                dc.w sprite_16_32
                dc.w $7075
                dc.w $9500 ! ((grp_5F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8076
                dc.w $9500 ! ((grp_5F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_5F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5F100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $587A
                dc.w $9500 ! ((grp_159DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_159DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7365
                dc.w $9500 ! ((grp_78380 / 2) & $00FF)
                dc.w $9600 ! (((grp_78380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $908B
                dc.w $9500 ! ((grp_CB1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9874
                dc.w $9500 ! ((grp_CB200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9072
                dc.w $9500 ! ((grp_B3680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B6C
                dc.w $9500 ! ((grp_E5D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5D40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7395
                dc.w $9500 ! ((grp_E5D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_E5D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5D80 / 2) >> 16)
                dc.w 1
