byte_2FF8C2:    dc.b   0,  6,$42,$2F,$D0,$BF,$89,$77,$8A,$77
                                        ; DATA XREF: ROM:off_35A4   o
                dc.w sprite_24_24
                dc.w $B82D
                dc.w $9500 ! ((grp_155740 / 2) & $00FF)
                dc.w $9600 ! (((grp_155740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155740 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $A83D
                dc.w $9500 ! ((grp_1A13A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A13A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A13A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $B037
                dc.w $9500 ! ((grp_1A1340 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $B845
                dc.w $9500 ! ((grp_E0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $D02D
                dc.w $9500 ! ((grp_C6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $40BD
                dc.w $9500 ! ((grp_F9520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A045
                dc.w $9500 ! ((grp_F9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9500 / 2) >> 16)
                dc.w 1
