byte_2E8ED6:    dc.b   0,  2,$7C,$58,$85,$8D,$83,$71,$80,$64
                                        ; DATA XREF: ROM:off_1DEC   o
                dc.w sprite_16_24
                dc.w $7C78
                dc.w $9500 ! ((grp_176500 / 2) & $00FF)
                dc.w $9600 ! (((grp_176500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176500 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $7852
                dc.w $9500 ! ((grp_197A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_197A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C60
                dc.w $9500 ! ((grp_1979E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1979E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1979E0 / 2) >> 16)
                dc.w 3
