byte_2EF642:    dc.b   0,  3,$7A,$5D,$98,$6F,$89,$66,$8A,$66
                                        ; DATA XREF: ROM:off_2504   o
                dc.w sprite_16_8
                dc.w $7863
                dc.w $9500 ! ((grp_D9D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D5B
                dc.w $9500 ! ((grp_F0F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $885B
                dc.w $9500 ! ((grp_F0F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $936B
                dc.w $9500 ! ((grp_F0FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0FA0 / 2) >> 16)
                dc.w 1
