byte_2E0FC4:    dc.b   0,  3,$72,$5A,$8E,$8E,$7A,$3B,$76,$2C
                                        ; DATA XREF: ROM:off_1920   o
                dc.w sprite_24_16
                dc.w $7741
                dc.w $9500 ! ((grp_15C040 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C040 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6F2E
                dc.w $9500 ! ((grp_CD6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7726
                dc.w $9500 ! ((grp_CD700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $672C
                dc.w $9500 ! ((grp_E7C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7C00 / 2) >> 16)
                dc.w 1
