byte_2EF376:    dc.b   0,  4,$65,$68,$95,$9E,$7D,$7F,$7E,$7F
                                        ; DATA XREF: ROM:off_24CC   o
                dc.w sprite_32_8
                dc.w $637E
                dc.w $9500 ! ((grp_9E300 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $837F
                dc.w $9500 ! ((grp_18D660 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D660 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6376
                dc.w $9500 ! ((grp_D9880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9880 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7877
                dc.w $9500 ! ((grp_D98C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D98C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D98C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9177
                dc.w $9500 ! ((grp_F0DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0DE0 / 2) >> 16)
                dc.w 1
