byte_2E38FC:    dc.b   0,  5,$79,$66,$9A,$92,$89,$7C,$8A,$7C
                                        ; DATA XREF: ROM:off_1AE0   o
                dc.w sprite_24_24
                dc.w $7867
                dc.w $9500 ! ((grp_1495C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1495C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1495C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7885
                dc.w $9500 ! ((grp_18B3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $728D
                dc.w $9500 ! ((grp_D6B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C7D
                dc.w $9500 ! ((grp_D6B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9064
                dc.w $9500 ! ((grp_D6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $906C
                dc.w $9500 ! ((grp_EEA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEA20 / 2) >> 16)
                dc.w 1
