byte_2D58DA:    dc.b   0,  6,$6E,$63,$8E,$8F,$7E,$74,$74,$68
                                        ; DATA XREF: ROM:off_11BC   o
                dc.w sprite_24_32
                dc.w $6F61
                dc.w $9500 ! ((grp_FEEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FEEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FEEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7381
                dc.w $9500 ! ((grp_185320 / 2) & $00FF)
                dc.w $9600 ! (((grp_185320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185320 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6764
                dc.w $9500 ! ((grp_194860 / 2) & $00FF)
                dc.w $9600 ! (((grp_194860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194860 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A89
                dc.w $9500 ! ((grp_CBB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D59
                dc.w $9500 ! ((grp_CBB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8789
                dc.w $9500 ! ((grp_CBB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8761
                dc.w $9500 ! ((grp_E61C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E61C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E61C0 / 2) >> 16)
                dc.w 1
