byte_2F5B84:    dc.b   0,  5,$71,$44,$92,$83,$53,$85,$54,$85
                                        ; DATA XREF: ROM:off_2B18   o
                dc.w sprite_32_32
                dc.w $6E47
                dc.w $9500 ! ((grp_3D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3D600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7667
                dc.w $9500 ! ((grp_116D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_116D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $8E57
                dc.w $9500 ! ((grp_C22C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C22C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C22C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E7A
                dc.w $9500 ! ((grp_F4A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $743F
                dc.w $9500 ! ((grp_F4A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $853F
                dc.w $9500 ! ((grp_F4A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A60 / 2) >> 16)
                dc.w 1
