byte_2CCFEC:    dc.b   0,  5,$66,$65,$9B,$7A,$80,$6F,$81,$6F
                                        ; DATA XREF: ROM:off_860   o
                dc.w sprite_16_16
                dc.w $7E63
                dc.w $9500 ! ((grp_74200 / 2) & $00FF)
                dc.w $9600 ! (((grp_74200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7663
                dc.w $9500 ! ((grp_191E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_191E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8D72
                dc.w $9500 ! ((grp_C7F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6E6D
                dc.w $9500 ! ((grp_B0A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $646D
                dc.w $9500 ! ((grp_E2160 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E62
                dc.w $9500 ! ((grp_E2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2180 / 2) >> 16)
                dc.w 1
