byte_2E2636:    dc.b   0,  7,$64,$70,$9F,$8D,$81,$7E,$82,$7E
                                        ; DATA XREF: ROM:off_1A2C   o
                dc.w sprite_16_32
                dc.w $7A70
                dc.w $9500 ! ((grp_64900 / 2) & $00FF)
                dc.w $9600 ! (((grp_64900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9270
                dc.w $9500 ! ((grp_81C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_81C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8A80
                dc.w $9500 ! ((grp_D3080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $727D
                dc.w $9500 ! ((grp_B9CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A70
                dc.w $9500 ! ((grp_B9C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6289
                dc.w $9500 ! ((grp_EBF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBF80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A83
                dc.w $9500 ! ((grp_EBFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBFA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9568
                dc.w $9500 ! ((grp_EBFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBFC0 / 2) >> 16)
                dc.w 1
