byte_2CC6A2:    dc.b   0,  1,$78,$58,$8A,$6A,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_7A4   o
                dc.w sprite_24_16
                dc.w $765E
                dc.w $9500 ! ((grp_155EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_155EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7A56
                dc.w $9500 ! ((grp_C6C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6C40 / 2) >> 16)
                dc.w 2
