byte_2FE59A:    dc.b   0,  1,$7B,$80,$83,$8D,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_33EC   o
                dc.w sprite_16_16
                dc.w $7880
                dc.w $9500 ! ((grp_96780 / 2) & $00FF)
                dc.w $9600 ! (((grp_96780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7878
                dc.w $9500 ! ((grp_F9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9680 / 2) >> 16)
                dc.w 1
