byte_2E497C:    dc.b   0,  4,$6E,$72,$8C,$98,$7D,$85,$7E,$85
                                        ; DATA XREF: ROM:off_1B58   o
                dc.w sprite_24_24
                dc.w $7278
                dc.w $9500 ! ((grp_146C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_146C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146C20 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7990
                dc.w $9500 ! ((grp_82080 / 2) & $00FF)
                dc.w $9600 ! (((grp_82080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7270
                dc.w $9500 ! ((grp_D3440 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A7A
                dc.w $9500 ! ((grp_B9F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8987
                dc.w $9500 ! ((grp_B9F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9F00 / 2) >> 16)
                dc.w 2
