byte_2FCE8C:    dc.b   0,  1,$82,$65,$96,$72,$8C,$6B,$8D,$6B
                                        ; DATA XREF: ROM:off_3250   o
                dc.w sprite_32_16
                dc.w $8063
                dc.w $9500 ! ((grp_59000 / 2) & $00FF)
                dc.w $9600 ! (((grp_59000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $8673
                dc.w $9500 ! ((grp_DF940 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF940 / 2) >> 16)
                dc.w 2
