byte_2FF70C:    dc.b   0, $A,$40,$6F,$90,$C4,$68,$99,$69,$99
                                        ; DATA XREF: ROM:off_3598   o
                dc.w sprite_24_16
                dc.w $7C6D
                dc.w $9500 ! ((grp_16E1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $549D
                dc.w $9500 ! ((grp_1A1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5C95
                dc.w $9500 ! ((grp_1A1220 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $648D
                dc.w $9500 ! ((grp_1A11C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A11C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A11C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6C85
                dc.w $9500 ! ((grp_1A1160 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $747C
                dc.w $9500 ! ((grp_1A1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1100 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C7D
                dc.w $9500 ! ((grp_E0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $44BD
                dc.w $9500 ! ((grp_C6540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3CBB
                dc.w $9500 ! ((grp_F93C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F93C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F93C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4CA8
                dc.w $9500 ! ((grp_F93A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F93A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F93A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C85
                dc.w $9500 ! ((grp_F9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9380 / 2) >> 16)
                dc.w 1
