byte_2F38AC:    dc.b   0,  5,$6B,$5D,$94,$8C,$76,$77,$77,$77
                                        ; DATA XREF: ROM:off_27D8   o
                dc.w sprite_24_32
                dc.w $7273
                dc.w $9500 ! ((grp_1147C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1147C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1147C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6A5B
                dc.w $9500 ! ((grp_136240 / 2) & $00FF)
                dc.w $9600 ! (((grp_136240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8A6D
                dc.w $9500 ! ((grp_6D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6D100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5265
                dc.w $9500 ! ((grp_8CD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5375
                dc.w $9500 ! ((grp_F2C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6263
                dc.w $9500 ! ((grp_F2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2C40 / 2) >> 16)
                dc.w 1
