byte_2E14AC:    dc.b   0,  6,$71,$58,$93,$8F,$83,$73,$84,$73
                                        ; DATA XREF: ROM:off_1940   o
                dc.w sprite_32_16
                dc.w $695A
                dc.w $9500 ! ((grp_50600 / 2) & $00FF)
                dc.w $9600 ! (((grp_50600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7969
                dc.w $9500 ! ((grp_66200 / 2) & $00FF)
                dc.w $9600 ! (((grp_66200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $895D
                dc.w $9500 ! ((grp_179740 / 2) & $00FF)
                dc.w $9600 ! (((grp_179740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179740 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7089
                dc.w $9500 ! ((grp_9B880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9961
                dc.w $9500 ! ((grp_D62C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D62C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D62C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6559
                dc.w $9500 ! ((grp_EE100 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9959
                dc.w $9500 ! ((grp_EE120 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE120 / 2) >> 16)
                dc.w 1
