byte_2E7506:    dc.b   0,  8,$6F,$63,$8E,$8F,$82,$77,$82,$6A
                                        ; DATA XREF: ROM:off_1CDC   o
                dc.w sprite_24_16
                dc.w $6E60
                dc.w $9500 ! ((grp_1615C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1615C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1615C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $6E70
                dc.w $9500 ! ((grp_161680 / 2) & $00FF)
                dc.w $9600 ! (((grp_161680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161680 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_189E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_189E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189E80 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7D88
                dc.w $9500 ! ((grp_189EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189EE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8668
                dc.w $9500 ! ((grp_199480 / 2) & $00FF)
                dc.w $9600 ! (((grp_199480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199480 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_D4640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E6D
                dc.w $9500 ! ((grp_BB140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7558
                dc.w $9500 ! ((grp_ECCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECCC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9669
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
