byte_2E8174:    dc.b   0,  9,$6F,$5D,$8E,$8F,$89,$49,$96,$60
                                        ; DATA XREF: ROM:off_1D50   o
                dc.w sprite_16_32
                dc.w $7A58
                dc.w $9500 ! ((grp_60F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7378
                dc.w $9500 ! ((grp_98E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9258
                dc.w $9500 ! ((grp_A5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7380
                dc.w $9500 ! ((grp_1866A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1866A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1866A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7260
                dc.w $9500 ! ((grp_196240 / 2) & $00FF)
                dc.w $9600 ! (((grp_196240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196240 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C88
                dc.w $9500 ! ((grp_CDF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CDF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8753
                dc.w $9500 ! ((grp_CDFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A70
                dc.w $9500 ! ((grp_E85C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E85C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E85C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A5B
                dc.w $9500 ! ((grp_E85E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E85E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E85E0 / 2) >> 16)
                dc.w 1
