byte_2F2640:    dc.b   0,  4,$75,$5A,$8D,$87,$81,$76,$82,$76
                                        ; DATA XREF: ROM:off_2718   o
                dc.w sprite_16_32
                dc.w $7963
                dc.w $9500 ! ((grp_6B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $716B
                dc.w $9500 ! ((grp_19D560 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8965
                dc.w $9500 ! ((grp_C0000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1920 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $897B
                dc.w $9500 ! ((grp_F1940 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1940 / 2) >> 16)
                dc.w 1
