byte_2EA344:    dc.b   0,  6,$69,$66,$97,$90,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F28   o
                dc.w sprite_32_32
                dc.w $7674
                dc.w $9500 ! ((grp_28C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_28C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6E64
                dc.w $9500 ! ((grp_9C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C400 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $766C
                dc.w $9500 ! ((grp_9C380 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6E6C
                dc.w $9500 ! ((grp_A9A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6668
                dc.w $9500 ! ((grp_19B340 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B340 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9674
                dc.w $9500 ! ((grp_BDD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9264
                dc.w $9500 ! ((grp_EEFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEFA0 / 2) >> 16)
                dc.w 1
