byte_2D5600:    dc.b   0,  7,$6F,$64,$8E,$8F,$81,$78,$7E,$6A
                                        ; DATA XREF: ROM:off_11A0   o
                dc.w sprite_24_24
                dc.w $7E61
                dc.w $9500 ! ((grp_141220 / 2) & $00FF)
                dc.w $9600 ! (((grp_141220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141220 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7479
                dc.w $9500 ! ((grp_15A180 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6E61
                dc.w $9500 ! ((grp_172900 / 2) & $00FF)
                dc.w $9600 ! (((grp_172900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6A88
                dc.w $9500 ! ((grp_CBA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8888
                dc.w $9500 ! ((grp_CBAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9664
                dc.w $9500 ! ((grp_B3AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6665
                dc.w $9500 ! ((grp_E6180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C79
                dc.w $9500 ! ((grp_E61A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E61A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E61A0 / 2) >> 16)
                dc.w 1
