byte_2F0EE2:    dc.b   0, $A,$64,$56,$AD,$84,$8C,$6D,$8D,$6D
                                        ; DATA XREF: ROM:off_261C   o
                dc.w sprite_32_32
                dc.w $7350
                dc.w $9500 ! ((grp_37400 / 2) & $00FF)
                dc.w $9600 ! (((grp_37400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7370
                dc.w $9500 ! ((grp_134A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_134A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $9352
                dc.w $9500 ! ((grp_134BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_134BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $5B60
                dc.w $9500 ! ((grp_14E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E900 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $936A
                dc.w $9500 ! ((grp_8C180 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AE60
                dc.w $9500 ! ((grp_8C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7388
                dc.w $9500 ! ((grp_DAFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $937A
                dc.w $9500 ! ((grp_C0540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B80
                dc.w $9500 ! ((grp_F2320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B58
                dc.w $9500 ! ((grp_F2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B358
                dc.w $9500 ! ((grp_F2360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2360 / 2) >> 16)
                dc.w 1
