byte_2FB2E2:    dc.b   0,  2,$67,$71,$8D,$8B,$7A,$7E,$7B,$7E
                                        ; DATA XREF: ROM:off_2F54   o
                dc.w sprite_32_32
                dc.w $6D6F
                dc.w $9500 ! ((grp_42E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_42E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_16
                dc.w $6574
                dc.w $9500 ! ((grp_C4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D83
                dc.w $9500 ! ((grp_F7860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7860 / 2) >> 16)
                dc.w 1
