byte_2D3698:    dc.b   0,  6,$75,$5B,$88,$95,$81,$78,$82,$78
                                        ; DATA XREF: ROM:off_1020   o
                dc.w sprite_16_32
                dc.w $7971
                dc.w $9500 ! ((grp_5EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5EC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7759
                dc.w $9500 ! ((grp_1720C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1720C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1720C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $697C
                dc.w $9500 ! ((grp_CA740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA740 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E91
                dc.w $9500 ! ((grp_CA780 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8976
                dc.w $9500 ! ((grp_CA7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F5C
                dc.w $9500 ! ((grp_B2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $897E
                dc.w $9500 ! ((grp_E4F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4F80 / 2) >> 16)
                dc.w 1
