byte_2E80A0:    dc.b   0,  8,$6F,$72,$8E,$8F,$71,$5E,$62,$7D
                                        ; DATA XREF: ROM:off_1D48   o
                dc.w sprite_32_32
                dc.w $6E70
                dc.w $9500 ! ((grp_1B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1B800 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_24
                dc.w $5C63
                dc.w $9500 ! ((grp_1961E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1961E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1961E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5E7B
                dc.w $9500 ! ((grp_CDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $635E
                dc.w $9500 ! ((grp_CDE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E70
                dc.w $9500 ! ((grp_B5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6683
                dc.w $9500 ! ((grp_E8560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E57
                dc.w $9500 ! ((grp_E8520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D68
                dc.w $9500 ! ((grp_E8540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E88
                dc.w $9500 ! ((grp_E8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8580 / 2) >> 16)
                dc.w 1
