byte_2FE3CA:    dc.b   0,  4,$75,$78,$8B,$89,$85,$79,$86,$79
                                        ; DATA XREF: ROM:off_33CC   o
                dc.w sprite_24_16
                dc.w $7577
                dc.w $9500 ! ((grp_16DA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_16DA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16DA40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7587
                dc.w $9500 ! ((grp_E0380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D7D
                dc.w $9500 ! ((grp_F8A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7568
                dc.w $9500 ! ((grp_F8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $977A
                dc.w $9500 ! ((grp_F8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8980 / 2) >> 16)
                dc.w 1
