byte_2F4AFC:    dc.b   0,  8,$65,$68,$91,$8C,$83,$7A,$84,$7A
                                        ; DATA XREF: ROM:off_2A08   o
                dc.w sprite_24_32
                dc.w $6972
                dc.w $9500 ! ((grp_115FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_115FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5976
                dc.w $9500 ! ((grp_8E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9174
                dc.w $9500 ! ((grp_8E480 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A17C
                dc.w $9500 ! ((grp_8E500 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8165
                dc.w $9500 ! ((grp_ACE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8964
                dc.w $9500 ! ((grp_19E3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E3A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $716A
                dc.w $9500 ! ((grp_DC540 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9164
                dc.w $9500 ! ((grp_C1880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $616E
                dc.w $9500 ! ((grp_F4160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4160 / 2) >> 16)
                dc.w 1
