byte_2DED2C:    dc.b   0,  7,$6F,$60,$8E,$8F,$82,$70,$82,$64
                                        ; DATA XREF: ROM:off_17B8   o
                dc.w sprite_32_24
                dc.w $6F65
                dc.w $9500 ! ((grp_12A540 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $785D
                dc.w $9500 ! ((grp_D27C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D27C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D27C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $787D
                dc.w $9500 ! ((grp_D2800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7580
                dc.w $9500 ! ((grp_B9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8480
                dc.w $9500 ! ((grp_B93C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B93C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B93C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F65
                dc.w $9500 ! ((grp_B9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D88
                dc.w $9500 ! ((grp_EB4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB4C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
