byte_2E49C2:    dc.b   0,  4,$65,$69,$8B,$8D,$78,$7B,$68,$6F
                                        ; DATA XREF: ROM:off_1B5C   o
                dc.w sprite_32_24
                dc.w $6367
                dc.w $9500 ! ((grp_12D3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6B7F
                dc.w $9500 ! ((grp_1624C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1624C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1624C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $836D
                dc.w $9500 ! ((grp_A8200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8B6F
                dc.w $9500 ! ((grp_BBA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $828D
                dc.w $9500 ! ((grp_ED780 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED780 / 2) >> 16)
                dc.w 1
