byte_2EED82:    dc.b   0,  3,$75,$7F,$8D,$8B,$81,$85,$82,$85
                                        ; DATA XREF: ROM:off_2424   o
                dc.w sprite_32_24
                dc.w $7A7A
                dc.w $9500 ! ((grp_133240 / 2) & $00FF)
                dc.w $9600 ! (((grp_133240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_133240 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6A7A
                dc.w $9500 ! ((grp_17C140 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C140 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $8172
                dc.w $9500 ! ((grp_18D4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D4E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7472
                dc.w $9500 ! ((grp_F0AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0AE0 / 2) >> 16)
                dc.w 1
