byte_2DDCF0:    dc.b   0,  6,$75,$67,$8F,$90,$82,$7B,$80,$6D
                                        ; DATA XREF: ROM:off_1718   o
                dc.w sprite_24_32
                dc.w $766F
                dc.w $9500 ! ((grp_1078C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1078C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1078C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $666F
                dc.w $9500 ! ((grp_80900 / 2) & $00FF)
                dc.w $9600 ! (((grp_80900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E67
                dc.w $9500 ! ((grp_188B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_188B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188B00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A8F
                dc.w $9500 ! ((grp_D22C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D22C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D22C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E71
                dc.w $9500 ! ((grp_EB140 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B67
                dc.w $9500 ! ((grp_EB160 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E7F
                dc.w $9500 ! ((grp_EB180 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB180 / 2) >> 16)
                dc.w 1
