byte_2F936E:    dc.b   0,  4,$64,$73,$90,$93,$7A,$83,$7B,$83
                                        ; DATA XREF: ROM:off_2D2C   o
                dc.w sprite_24_32
                dc.w $7471
                dc.w $9500 ! ((grp_11A4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6C7D
                dc.w $9500 ! ((grp_19F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7491
                dc.w $9500 ! ((grp_DE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6285
                dc.w $9500 ! ((grp_F66C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F66C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F66C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C76
                dc.w $9500 ! ((grp_F66E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F66E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F66E0 / 2) >> 16)
                dc.w 1
