byte_2DB6E2:    dc.b   0,  6,$6D,$62,$8E,$91,$7D,$79,$7E,$79
                                        ; DATA XREF: ROM:off_1564   o
                dc.w sprite_32_24
                dc.w $6B68
                dc.w $9500 ! ((grp_12DE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12DE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12DE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7160
                dc.w $9500 ! ((grp_18A720 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A720 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $818C
                dc.w $9500 ! ((grp_D5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7380
                dc.w $9500 ! ((grp_BC340 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7E80
                dc.w $9500 ! ((grp_BBE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B6D
                dc.w $9500 ! ((grp_BC380 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $708C
                dc.w $9500 ! ((grp_EDB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDB00 / 2) >> 16)
                dc.w 1
