byte_2E3068:    dc.b   0,  4,$70,$64,$80,$6D,$78,$7B,$7B,$75
                                        ; DATA XREF: ROM:off_1A80   o
                dc.w sprite_32_32
                dc.w $7471
                dc.w $9500 ! ((grp_1DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1DC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $5D67
                dc.w $9500 ! ((grp_4C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7D69
                dc.w $9500 ! ((grp_187C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_187C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C77
                dc.w $9500 ! ((grp_E9CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $708C
                dc.w $9500 ! ((grp_E9D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9D00 / 2) >> 16)
                dc.w 1
