byte_2FAA44:    dc.b   0,  9,$76,$6A,$AB,$81,$97,$76,$98,$76
                                        ; DATA XREF: ROM:off_2E30   o
                dc.w sprite_32_32
                dc.w $805A
                dc.w $9500 ! ((grp_42600 / 2) & $00FF)
                dc.w $9600 ! (((grp_42600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_42600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $A05B
                dc.w $9500 ! ((grp_11B540 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B540 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $707A
                dc.w $9500 ! ((grp_153A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_153A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_153A00 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $887A
                dc.w $9500 ! ((grp_1907E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1907E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1907E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7072
                dc.w $9500 ! ((grp_DEE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A37B
                dc.w $9500 ! ((grp_DEE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $786A
                dc.w $9500 ! ((grp_F70A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F70A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F70A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8882
                dc.w $9500 ! ((grp_F70E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F70E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F70E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9482
                dc.w $9500 ! ((grp_F7100 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B86B
                dc.w $9500 ! ((grp_F70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F70C0 / 2) >> 16)
                dc.w 1
