byte_2E5BB0:    dc.b   0,  6,$6C,$60,$86,$8E,$3F,$9A,$75,$64
                                        ; DATA XREF: ROM:off_1BF8   o
                dc.w sprite_32_24
                dc.w $636A
                dc.w $9500 ! ((grp_12C340 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7082
                dc.w $9500 ! ((grp_160B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_160B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $715A
                dc.w $9500 ! ((grp_82D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_82D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $815E
                dc.w $9500 ! ((grp_189A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_189A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189A60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8369
                dc.w $9500 ! ((grp_D3900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $916E
                dc.w $9500 ! ((grp_D3940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9576
                dc.w $9500 ! ((grp_EC660 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC660 / 2) >> 16)
                dc.w 1
