byte_2EEE0E:    dc.b   0,  7,$6A,$7A,$97,$8C,$80,$83,$81,$83
                                        ; DATA XREF: ROM:off_242C   o
                dc.w sprite_32_16
                dc.w $6081
                dc.w $9500 ! ((grp_52C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_52C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9078
                dc.w $9500 ! ((grp_17C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C200 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8075
                dc.w $9500 ! ((grp_ABC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6879
                dc.w $9500 ! ((grp_18D540 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D540 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $887E
                dc.w $9500 ! ((grp_19D2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D2C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $786D
                dc.w $9500 ! ((grp_D9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A07B
                dc.w $9500 ! ((grp_BF7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A77
                dc.w $9500 ! ((grp_F0B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0B20 / 2) >> 16)
                dc.w 1
