byte_2EE4BE:    dc.b   0,  2,$7C,$53,$83,$7E,$7F,$68,$80,$68
                                        ; DATA XREF: ROM:off_2394   o
                dc.w sprite_8_24
                dc.w $7C69
                dc.w $9500 ! ((grp_19CB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CB40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7E51
                dc.w $9500 ! ((grp_19CBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CBA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7471
                dc.w $9500 ! ((grp_BF180 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF180 / 2) >> 16)
                dc.w 2
