byte_2DF80E:    dc.b   0,  7,$5B,$58,$90,$8D,$75,$72,$7B,$65
                                        ; DATA XREF: ROM:off_182C   o
                dc.w sprite_16_32
                dc.w $7569
                dc.w $9500 ! ((grp_63200 / 2) & $00FF)
                dc.w $9600 ! (((grp_63200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6D5A
                dc.w $9500 ! ((grp_15F4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F4C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $656A
                dc.w $9500 ! ((grp_80C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8456
                dc.w $9500 ! ((grp_80C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D89
                dc.w $9500 ! ((grp_9A480 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5572
                dc.w $9500 ! ((grp_D2840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8581
                dc.w $9500 ! ((grp_EB520 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D89
                dc.w $9500 ! ((grp_EB540 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB540 / 2) >> 16)
                dc.w 1
