byte_2D7898:    dc.b   0,  7,$77,$65,$8F,$99,$7C,$7B,$90,$7B
                                        ; DATA XREF: ROM:off_1308   o
                dc.w sprite_24_32
                dc.w $6E6E
                dc.w $9500 ! ((grp_100240 / 2) & $00FF)
                dc.w $9600 ! (((grp_100240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $618E
                dc.w $9500 ! ((grp_98500 / 2) & $00FF)
                dc.w $9600 ! (((grp_98500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $866E
                dc.w $9500 ! ((grp_194BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_194BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194BC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A96
                dc.w $9500 ! ((grp_CC300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $745E
                dc.w $9500 ! ((grp_CC280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C66
                dc.w $9500 ! ((grp_CC2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E76
                dc.w $9500 ! ((grp_B3FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $667B
                dc.w $9500 ! ((grp_E6740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6740 / 2) >> 16)
                dc.w 1
