byte_2ED56A:    dc.b   0,  2,$75,$62,$8C,$93,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_22A4   o
                dc.w sprite_24_32
                dc.w $7862
                dc.w $9500 ! ((grp_111C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_111C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7982
                dc.w $9500 ! ((grp_89080 / 2) & $00FF)
                dc.w $9600 ! (((grp_89080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7068
                dc.w $9500 ! ((grp_19C7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C7E0 / 2) >> 16)
                dc.w 3
