byte_2D27E6:    dc.b   0, $B,$5D,$4A,$A3,$73,$79,$7A,$7A,$7A
                                        ; DATA XREF: ROM:off_EF4   o
                dc.w sprite_32_24
                dc.w $7959
                dc.w $9500 ! ((grp_122140 / 2) & $00FF)
                dc.w $9600 ! (((grp_122140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6959
                dc.w $9500 ! ((grp_5E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $5978
                dc.w $9500 ! ((grp_A4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $615F
                dc.w $9500 ! ((grp_A4600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $617F
                dc.w $9500 ! ((grp_A4680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6979
                dc.w $9500 ! ((grp_A4700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7179
                dc.w $9500 ! ((grp_193960 / 2) & $00FF)
                dc.w $9600 ! (((grp_193960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193960 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7971
                dc.w $9500 ! ((grp_1939C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1939C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1939C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5968
                dc.w $9500 ! ((grp_B28C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B28C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B28C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8171
                dc.w $9500 ! ((grp_B2880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8971
                dc.w $9500 ! ((grp_E4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9961
                dc.w $9500 ! ((grp_E44A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E44A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E44A0 / 2) >> 16)
                dc.w 1
