byte_2EDEE8:    dc.b   0,  5,$76,$78,$C3,$8E,$9C,$85,$9D,$85
                                        ; DATA XREF: ROM:off_2328   o
                dc.w sprite_16_32
                dc.w $7E75
                dc.w $9500 ! ((grp_69200 / 2) & $00FF)
                dc.w $9600 ! (((grp_69200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_69200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $A678
                dc.w $9500 ! ((grp_9DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $767D
                dc.w $9500 ! ((grp_19CAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CAE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8E80
                dc.w $9500 ! ((grp_D8F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E7A
                dc.w $9500 ! ((grp_BEFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E8B
                dc.w $9500 ! ((grp_F0420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0420 / 2) >> 16)
                dc.w 1
