byte_2F2C70:    dc.b   0,  7,$70,$67,$8E,$9D,$7D,$81,$7E,$81
                                        ; DATA XREF: ROM:off_2760   o
                dc.w sprite_32_32
                dc.w $7069
                dc.w $9500 ! ((grp_3AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3AA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $6F89
                dc.w $9500 ! ((grp_1502E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1502E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1502E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $6D61
                dc.w $9500 ! ((grp_DBFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B93
                dc.w $9500 ! ((grp_C10C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C10C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C10C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8789
                dc.w $9500 ! ((grp_C1100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6969
                dc.w $9500 ! ((grp_F3360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8861
                dc.w $9500 ! ((grp_F3380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906C
                dc.w $9500 ! ((grp_F33A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F33A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F33A0 / 2) >> 16)
                dc.w 1
