byte_2EBEAA:    dc.b   0,  8,$84,$5B,$A1,$80,$82,$7C,$83,$7C
                                        ; DATA XREF: ROM:off_2084   o
                dc.w sprite_32_32
                dc.w $5468
                dc.w $9500 ! ((grp_2E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2E600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $746A
                dc.w $9500 ! ((grp_2E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_2E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2E800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $946B
                dc.w $9500 ! ((grp_110D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_110D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $5488
                dc.w $9500 ! ((grp_9D180 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $748A
                dc.w $9500 ! ((grp_9D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $948B
                dc.w $9500 ! ((grp_18C2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C2E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $AC70
                dc.w $9500 ! ((grp_19BE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BE80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4C73
                dc.w $9500 ! ((grp_BE300 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $B47A
                dc.w $9500 ! ((grp_EF7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF7E0 / 2) >> 16)
                dc.w 1
