byte_2DF0E6:    dc.b   0, $B,$67,$60,$94,$8E,$7B,$72,$60,$6D
                                        ; DATA XREF: ROM:off_17DC   o
                dc.w sprite_16_32
                dc.w $7064
                dc.w $9500 ! ((grp_66000 / 2) & $00FF)
                dc.w $9600 ! (((grp_66000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $805C
                dc.w $9500 ! ((grp_66100 / 2) & $00FF)
                dc.w $9600 ! (((grp_66100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $807C
                dc.w $9500 ! ((grp_179680 / 2) & $00FF)
                dc.w $9600 ! (((grp_179680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7084
                dc.w $9500 ! ((grp_85B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_85B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5854
                dc.w $9500 ! ((grp_9B780 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $585C
                dc.w $9500 ! ((grp_19A320 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A320 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $606A
                dc.w $9500 ! ((grp_19A380 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9064
                dc.w $9500 ! ((grp_19A3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7854
                dc.w $9500 ! ((grp_D6240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6874
                dc.w $9500 ! ((grp_BC680 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $986C
                dc.w $9500 ! ((grp_BC6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $908A
                dc.w $9500 ! ((grp_EE0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE0A0 / 2) >> 16)
                dc.w 1
