byte_2DD55C:    dc.b   0,  6,$80,$5B,$94,$98,$8B,$90,$83,$67
                                        ; DATA XREF: ROM:off_16C8   o
                dc.w sprite_24_32
                dc.w $7C5C
                dc.w $9500 ! ((grp_101BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_101BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $8484
                dc.w $9500 ! ((grp_15B8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7C7C
                dc.w $9500 ! ((grp_185BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185BC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7463
                dc.w $9500 ! ((grp_195700 / 2) & $00FF)
                dc.w $9600 ! (((grp_195700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195700 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8454
                dc.w $9500 ! ((grp_CD180 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD180 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C94
                dc.w $9500 ! ((grp_CD1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $945C
                dc.w $9500 ! ((grp_E7720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7720 / 2) >> 16)
                dc.w 1
