byte_2D2926:    dc.b   0, $C,$5D,$4A,$A3,$73,$79,$7A,$7A,$7A
                                        ; DATA XREF: ROM:off_EFC   o
                dc.w sprite_32_32
                dc.w $695A
                dc.w $9500 ! ((grp_16E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $5981
                dc.w $9500 ! ((grp_171A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_171A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171A00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $717A
                dc.w $9500 ! ((grp_76D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6162
                dc.w $9500 ! ((grp_A4980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $697A
                dc.w $9500 ! ((grp_A4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5969
                dc.w $9500 ! ((grp_193B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_193B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $895A
                dc.w $9500 ! ((grp_193AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193AE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $915F
                dc.w $9500 ! ((grp_B2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6199
                dc.w $9500 ! ((grp_E4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718A
                dc.w $9500 ! ((grp_E4520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $817A
                dc.w $9500 ! ((grp_E4520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8972
                dc.w $9500 ! ((grp_E4520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9962
                dc.w $9500 ! ((grp_E4540 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4540 / 2) >> 16)
                dc.w 1
