byte_2DCEB6:    dc.b   0,  4,$6F,$6C,$8E,$8F,$80,$7E,$82,$72
                                        ; DATA XREF: ROM:off_167C   o
                dc.w sprite_32_24
                dc.w $6F72
                dc.w $9500 ! ((grp_12D6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $736A
                dc.w $9500 ! ((grp_18A540 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_D55C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D55C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D55C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838A
                dc.w $9500 ! ((grp_D5600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F7A
                dc.w $9500 ! ((grp_EDA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDA20 / 2) >> 16)
                dc.w 1
