byte_2E88C8:    dc.b   0,  5,$7B,$65,$89,$8D,$80,$79,$88,$6C
                                        ; DATA XREF: ROM:off_1D90   o
                dc.w sprite_16_16
                dc.w $7D63
                dc.w $9500 ! ((grp_7C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B7B
                dc.w $9500 ! ((grp_1966C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1966C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1966C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7383
                dc.w $9500 ! ((grp_B6300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7563
                dc.w $9500 ! ((grp_B3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8373
                dc.w $9500 ! ((grp_B6340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8388
                dc.w $9500 ! ((grp_E8800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8800 / 2) >> 16)
                dc.w 1
