byte_2D0F74:    dc.b   0,  8,$45,$60,$6D,$92,$63,$78,$64,$78
                                        ; DATA XREF: ROM:off_DE0   o
                dc.w sprite_32_32
                dc.w $5260
                dc.w $9500 ! ((grp_14800 / 2) & $00FF)
                dc.w $9600 ! (((grp_14800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7260
                dc.w $9500 ! ((grp_14A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $5780
                dc.w $9500 ! ((grp_47800 / 2) & $00FF)
                dc.w $9600 ! (((grp_47800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $3A68
                dc.w $9500 ! ((grp_157C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_157C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7780
                dc.w $9500 ! ((grp_76100 / 2) & $00FF)
                dc.w $9600 ! (((grp_76100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9260
                dc.w $9500 ! ((grp_193000 / 2) & $00FF)
                dc.w $9600 ! (((grp_193000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9A60
                dc.w $9500 ! ((grp_B1B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3270
                dc.w $9500 ! ((grp_E37A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E37A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E37A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $4A60
                dc.w $9500 ! ((grp_E37C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E37C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E37C0 / 2) >> 16)
                dc.w 1
