byte_2DA63C:    dc.b   0, $C,$56,$52,$85,$8E,$6D,$70,$80,$5E
                                        ; DATA XREF: ROM:off_14A8   o
                dc.w sprite_24_24
                dc.w $687C
                dc.w $9500 ! ((grp_142300 / 2) & $00FF)
                dc.w $9600 ! (((grp_142300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142300 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $604C
                dc.w $9500 ! ((grp_77B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_77B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $686C
                dc.w $9500 ! ((grp_79900 / 2) & $00FF)
                dc.w $9600 ! (((grp_79900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $504C
                dc.w $9500 ! ((grp_A4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $586C
                dc.w $9500 ! ((grp_CB000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $685C
                dc.w $9500 ! ((grp_CCB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7054
                dc.w $9500 ! ((grp_CCAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $704C
                dc.w $9500 ! ((grp_CB040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $785C
                dc.w $9500 ! ((grp_CAF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $605C
                dc.w $9500 ! ((grp_B34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B34C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $584C
                dc.w $9500 ! ((grp_E5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6084
                dc.w $9500 ! ((grp_E58E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E58E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E58E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6864
                dc.w $9500 ! ((grp_E6FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6FC0 / 2) >> 16)
                dc.w 1
