byte_2FC89E:    dc.b   0,  1,$7D,$70,$8B,$8D,$84,$7E,$85,$7E
                                        ; DATA XREF: ROM:off_3154   o
                dc.w sprite_16_24
                dc.w $826E
                dc.w $9500 ! ((grp_1816C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1816C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1816C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7A6F
                dc.w $9500 ! ((grp_C5700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5700 / 2) >> 16)
                dc.w 2
