byte_2F2BC0:    dc.b   0,  5,$72,$6B,$8E,$82,$80,$76,$81,$76
                                        ; DATA XREF: ROM:off_2758   o
                dc.w sprite_16_16
                dc.w $8070
                dc.w $9500 ! ((grp_8BB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7868
                dc.w $9500 ! ((grp_19D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7880
                dc.w $9500 ! ((grp_DA5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $706D
                dc.w $9500 ! ((grp_BFF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8069
                dc.w $9500 ! ((grp_F17C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F17C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F17C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $896B
                dc.w $9500 ! ((grp_F1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1800 / 2) >> 16)
                dc.w 1
