byte_2EC02A:    dc.b   0,  2,$77,$5D,$92,$89,$84,$73,$85,$73
                                        ; DATA XREF: ROM:0000209C   o
                dc.w sprite_32_32
                dc.w $756B
                dc.w $9500 ! ((grp_2EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2EE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $845B
                dc.w $9500 ! ((grp_87C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_87C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $828B
                dc.w $9500 ! ((grp_EF860 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF860 / 2) >> 16)
                dc.w 1
