byte_2F36E0:    dc.b   0,  7,$69,$5F,$96,$89,$78,$77,$79,$77
                                        ; DATA XREF: ROM:off_27C8   o
                dc.w sprite_32_32
                dc.w $725D
                dc.w $9500 ! ((grp_3A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3A600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $5A61
                dc.w $9500 ! ((grp_8D100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D100 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $727D
                dc.w $9500 ! ((grp_9F180 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A85
                dc.w $9500 ! ((grp_DBE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C8D
                dc.w $9500 ! ((grp_DBE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A64
                dc.w $9500 ! ((grp_F30A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F30A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F30A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A74
                dc.w $9500 ! ((grp_F3060 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3060 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $926D
                dc.w $9500 ! ((grp_F3080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3080 / 2) >> 16)
                dc.w 1
