byte_2E2362:    dc.b   0,  5,$74,$63,$88,$87,$81,$73,$88,$5D
                                        ; DATA XREF: ROM:off_1A04   o
                dc.w sprite_32_32
                dc.w $6E5F
                dc.w $9500 ! ((grp_1B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1B400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $767F
                dc.w $9500 ! ((grp_7B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E57
                dc.w $9500 ! ((grp_186280 / 2) & $00FF)
                dc.w $9600 ! (((grp_186280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $798F
                dc.w $9500 ! ((grp_E7F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8687
                dc.w $9500 ! ((grp_E7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E76
                dc.w $9500 ! ((grp_E7F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7F20 / 2) >> 16)
                dc.w 1
