byte_2DFF7C:    dc.b   0,  6,$64,$58,$9B,$8E,$7F,$73,$80,$69
                                        ; DATA XREF: ROM:off_1880   o
                dc.w sprite_32_32
                dc.w $6E5B
                dc.w $9500 ! ((grp_20400 / 2) & $00FF)
                dc.w $9600 ! (((grp_20400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_20400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6E7B
                dc.w $9500 ! ((grp_12ACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12ACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12ACC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8E65
                dc.w $9500 ! ((grp_176F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_176F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5E56
                dc.w $9500 ! ((grp_81400 / 2) & $00FF)
                dc.w $9600 ! (((grp_81400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $668B
                dc.w $9500 ! ((grp_EB8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB8A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E7D
                dc.w $9500 ! ((grp_EB8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB8C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E8B
                dc.w $9500 ! ((grp_EB8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB8E0 / 2) >> 16)
                dc.w 1
