byte_2FE390:    dc.b   0,  3,$78,$77,$89,$86,$86,$78,$87,$78
                                        ; DATA XREF: ROM:off_33C8   o
                dc.w sprite_24_16
                dc.w $7676
                dc.w $9500 ! ((grp_16D980 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7986
                dc.w $9500 ! ((grp_E0340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7669
                dc.w $9500 ! ((grp_F8A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9071
                dc.w $9500 ! ((grp_F8A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8A60 / 2) >> 16)
                dc.w 1
