byte_2FDC7A:    dc.b   0,  4,$6F,$63,$9A,$8D,$84,$78,$85,$78
                                        ; DATA XREF: ROM:off_333C   o
                dc.w sprite_32_24
                dc.w $6D61
                dc.w $9500 ! ((grp_13B640 / 2) & $00FF)
                dc.w $9600 ! (((grp_13B640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13B640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8D60
                dc.w $9500 ! ((grp_1822C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1822C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1822C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7C78
                dc.w $9500 ! ((grp_A1200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_1913E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1913E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1913E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8080
                dc.w $9500 ! ((grp_E00C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E00C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E00C0 / 2) >> 16)
                dc.w 2
