byte_2F5AF8:    dc.b   0,  4,$71,$54,$98,$8E,$84,$71,$85,$71
                                        ; DATA XREF: ROM:off_2B10   o
                dc.w sprite_32_32
                dc.w $7761
                dc.w $9500 ! ((grp_3CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3CC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6F51
                dc.w $9500 ! ((grp_168DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_168DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7A81
                dc.w $9500 ! ((grp_168E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_168E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6F61
                dc.w $9500 ! ((grp_C2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $976D
                dc.w $9500 ! ((grp_F48C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F48C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F48C0 / 2) >> 16)
                dc.w 1
