byte_2E6166:    dc.b   0,  9,$6E,$61,$83,$8E,$7C,$64,$75,$62
                                        ; DATA XREF: ROM:off_1C2C   o
                dc.w sprite_24_24
                dc.w $6E61
                dc.w $9500 ! ((grp_146F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_146F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146F80 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5E72
                dc.w $9500 ! ((grp_83080 / 2) & $00FF)
                dc.w $9600 ! (((grp_83080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7679
                dc.w $9500 ! ((grp_83100 / 2) & $00FF)
                dc.w $9600 ! (((grp_83100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83100 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7089
                dc.w $9500 ! ((grp_9AE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D38
                dc.w $9500 ! ((grp_D3680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8663
                dc.w $9500 ! ((grp_BAB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $666A
                dc.w $9500 ! ((grp_EC7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC7E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7159
                dc.w $9500 ! ((grp_EC800 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E30
                dc.w $9500 ! ((grp_EC820 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9040
                dc.w $9500 ! ((grp_EC3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC3E0 / 2) >> 16)
                dc.w 1
