byte_2F1734:    dc.b   0,  2,$6E,$66,$87,$7A,$7A,$70,$7B,$70
                                        ; DATA XREF: ROM:off_2670   o
                dc.w sprite_32_16
                dc.w $6C64
                dc.w $9500 ! ((grp_55100 / 2) & $00FF)
                dc.w $9600 ! (((grp_55100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55100 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7274
                dc.w $9500 ! ((grp_18E2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E2C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7B7C
                dc.w $9500 ! ((grp_F2880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2880 / 2) >> 16)
                dc.w 1
