byte_2FC186:    dc.b   0,  1,$73,$8D,$7A,$9D,$76,$95,$77,$95
                                        ; DATA XREF: ROM:off_30B4   o
                dc.w sprite_16_16
                dc.w $718B
                dc.w $9500 ! ((grp_92B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_92B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $719B
                dc.w $9500 ! ((grp_F7D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7D80 / 2) >> 16)
                dc.w 1
