byte_2DA908:    dc.b   0,  6,$6F,$68,$8E,$8F,$81,$7A,$82,$6B
                                        ; DATA XREF: ROM:off_14C8   o
                dc.w sprite_32_16
                dc.w $6F70
                dc.w $9500 ! ((grp_4B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $6F68
                dc.w $9500 ! ((grp_1874E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1874E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1874E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7780
                dc.w $9500 ! ((grp_187540 / 2) & $00FF)
                dc.w $9600 ! (((grp_187540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187540 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8F6B
                dc.w $9500 ! ((grp_196F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_196F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7088
                dc.w $9500 ! ((grp_CFAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8588
                dc.w $9500 ! ((grp_CFA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B60
                dc.w $9500 ! ((grp_E9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9680 / 2) >> 16)
                dc.w 1
