byte_2FE688:    dc.b   0,  1,$73,$76,$8C,$89,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_3408   o
                dc.w sprite_32_16
                dc.w $6F7C
                dc.w $9500 ! ((grp_59D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_59D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7574
                dc.w $9500 ! ((grp_1917A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1917A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1917A0 / 2) >> 16)
                dc.w 3
