byte_2F3682:    dc.b   0,  6,$69,$5F,$96,$89,$7A,$76,$7B,$76
                                        ; DATA XREF: ROM:off_27C4   o
                dc.w sprite_32_32
                dc.w $725D
                dc.w $9500 ! ((grp_3A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3A400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $787D
                dc.w $9500 ! ((grp_167C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_167C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $5A63
                dc.w $9500 ! ((grp_18E6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E6E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7A8D
                dc.w $9500 ! ((grp_18E740 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E740 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6578
                dc.w $9500 ! ((grp_DBDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $616B
                dc.w $9500 ! ((grp_F3020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9081
                dc.w $9500 ! ((grp_F3040 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3040 / 2) >> 16)
                dc.w 1
