byte_2DABB6:    dc.b   0,  4,$71,$73,$8E,$89,$9E,$7F,$81,$89
                                        ; DATA XREF: ROM:off_14F4   o
                dc.w sprite_24_32
                dc.w $6D72
                dc.w $9500 ! ((grp_104740 / 2) & $00FF)
                dc.w $9600 ! (((grp_104740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104740 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7162
                dc.w $9500 ! ((grp_15D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D900 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8577
                dc.w $9500 ! ((grp_15D840 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D840 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $896B
                dc.w $9500 ! ((grp_E97E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E97E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E97E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D7A
                dc.w $9500 ! ((grp_E97C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E97C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E97C0 / 2) >> 16)
                dc.w 1
