byte_2E38B6:    dc.b   0,  4,$70,$68,$A0,$90,$88,$7C,$89,$7C
                                        ; DATA XREF: ROM:off_1ADC   o
                dc.w sprite_24_24
                dc.w $796B
                dc.w $9500 ! ((grp_1494A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1494A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1494A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_9C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7583
                dc.w $9500 ! ((grp_18B320 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B320 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8B66
                dc.w $9500 ! ((grp_18B380 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B380 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8263
                dc.w $9500 ! ((grp_EEA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEA00 / 2) >> 16)
                dc.w 1
