byte_2E48C0:    dc.b   0,  7,$70,$60,$8D,$97,$7E,$7B,$7F,$7B
                                        ; DATA XREF: ROM:off_1B50   o
                dc.w sprite_24_32
                dc.w $7376
                dc.w $9500 ! ((grp_109E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_109E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6B76
                dc.w $9500 ! ((grp_198E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_198E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198E80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8B7C
                dc.w $9500 ! ((grp_198EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198EE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7166
                dc.w $9500 ! ((grp_D3340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A6E
                dc.w $9500 ! ((grp_D3380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B96
                dc.w $9500 ! ((grp_D33C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D33C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D33C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $815E
                dc.w $9500 ! ((grp_B9E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $725E
                dc.w $9500 ! ((grp_EC220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC220 / 2) >> 16)
                dc.w 1
