byte_2F261E:    dc.b   0,  1,$78,$68,$8A,$8E,$81,$82,$82,$82
                                        ; DATA XREF: ROM:off_2714   o
                dc.w sprite_24_24
                dc.w $7674
                dc.w $9500 ! ((grp_14DCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14DCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14DCA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $768C
                dc.w $9500 ! ((grp_DA780 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA780 / 2) >> 16)
                dc.w 2
