byte_2DE566:    dc.b   0,  4,$73,$5F,$8B,$8E,$7E,$74,$81,$60
                                        ; DATA XREF: ROM:off_176C   o
                dc.w sprite_32_32
                dc.w $6D68
                dc.w $9500 ! ((grp_25C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_25C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7658
                dc.w $9500 ! ((grp_84A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D88
                dc.w $9500 ! ((grp_9B480 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8D80
                dc.w $9500 ! ((grp_BB800 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6E58
                dc.w $9500 ! ((grp_ED540 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED540 / 2) >> 16)
                dc.w 1
