byte_2EA236:    dc.b   0,  7,$67,$63,$95,$8B,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F1C   o
                dc.w sprite_32_32
                dc.w $6F68
                dc.w $9500 ! ((grp_28800 / 2) & $00FF)
                dc.w $9600 ! (((grp_28800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_28800 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $676A
                dc.w $9500 ! ((grp_A9980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8F68
                dc.w $9500 ! ((grp_A9A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $976D
                dc.w $9500 ! ((grp_19B2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B2E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7588
                dc.w $9500 ! ((grp_D71C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D71C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D71C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C60
                dc.w $9500 ! ((grp_D7180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F71
                dc.w $9500 ! ((grp_EEEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEEE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8788
                dc.w $9500 ! ((grp_EEF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEF00 / 2) >> 16)
                dc.w 1
