byte_2E7FD8:    dc.b   0,  7,$77,$64,$8C,$87,$77,$56,$84,$56
                                        ; DATA XREF: ROM:off_1D40   o
                dc.w sprite_24_32
                dc.w $7155
                dc.w $9500 ! ((grp_105DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_105DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_105DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7B75
                dc.w $9500 ! ((grp_15EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EE00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8085
                dc.w $9500 ! ((grp_D1240 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8764
                dc.w $9500 ! ((grp_D1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D5C
                dc.w $9500 ! ((grp_D1200 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7375
                dc.w $9500 ! ((grp_EA820 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A46
                dc.w $9500 ! ((grp_EA840 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F4D
                dc.w $9500 ! ((grp_EA860 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA860 / 2) >> 16)
                dc.w 1
