byte_2FC62E:    dc.b   0,  3,$3F,$5A,$BD,$9F,$7E,$94,$7F,$94
                                        ; DATA XREF: ROM:off_3124   o
                dc.w sprite_32_16
                dc.w $4094
                dc.w $9500 ! ((grp_58700 / 2) & $00FF)
                dc.w $9600 ! (((grp_58700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58700 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $5D90
                dc.w $9500 ! ((grp_58600 / 2) & $00FF)
                dc.w $9600 ! (((grp_58600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7D8D
                dc.w $9500 ! ((grp_58500 / 2) & $00FF)
                dc.w $9600 ! (((grp_58500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58500 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9D8A
                dc.w $9500 ! ((grp_58400 / 2) & $00FF)
                dc.w $9600 ! (((grp_58400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_58400 / 2) >> 16)
                dc.w 8
