byte_2E8D28:    dc.b   0,  3,$75,$7B,$89,$8E,$81,$82,$7D,$83
                                        ; DATA XREF: ROM:off_1DD0   o
                dc.w sprite_24_24
                dc.w $7279
                dc.w $9500 ! ((grp_143F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_143F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143F20 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $6A82
                dc.w $9500 ! ((grp_E8AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A71
                dc.w $9500 ! ((grp_E8AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A88
                dc.w $9500 ! ((grp_E8A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8A80 / 2) >> 16)
                dc.w 1
