byte_2D4C90:    dc.b   0,  4,$71,$76,$9D,$88,$87,$7F,$88,$7F
                                        ; DATA XREF: ROM:off_1130   o
                dc.w sprite_32_16
                dc.w $7174
                dc.w $9500 ! ((grp_4D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9174
                dc.w $9500 ! ((grp_80780 / 2) & $00FF)
                dc.w $9600 ! (((grp_80780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80780 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6F84
                dc.w $9500 ! ((grp_9A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7A6C
                dc.w $9500 ! ((grp_EB0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB0C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F84
                dc.w $9500 ! ((grp_EB0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB0A0 / 2) >> 16)
                dc.w 1
