byte_2E01D0:    dc.b   0,  5,$6B,$5C,$94,$8E,$7F,$75,$72,$60
                                        ; DATA XREF: ROM:off_18A0   o
                dc.w sprite_32_32
                dc.w $655A
                dc.w $9500 ! ((grp_21000 / 2) & $00FF)
                dc.w $9600 ! (((grp_21000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $657A
                dc.w $9500 ! ((grp_4E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $856A
                dc.w $9500 ! ((grp_63600 / 2) & $00FF)
                dc.w $9600 ! (((grp_63600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6D8A
                dc.w $9500 ! ((grp_9A880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9578
                dc.w $9500 ! ((grp_B9700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D8A
                dc.w $9500 ! ((grp_EB960 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB960 / 2) >> 16)
                dc.w 1
