byte_2F5BD6:    dc.b   0,  7,$73,$4C,$94,$83,$6D,$85,$6E,$85
                                        ; DATA XREF: ROM:off_2B1C   o
                dc.w sprite_32_32
                dc.w $6B48
                dc.w $9500 ! ((grp_3DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7468
                dc.w $9500 ! ((grp_1177C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1177C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1177C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $934F
                dc.w $9500 ! ((grp_17ED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17ED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17ED80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6350
                dc.w $9500 ! ((grp_AD300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B45
                dc.w $9500 ! ((grp_AD380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8B65
                dc.w $9500 ! ((grp_19EBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EBE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7240
                dc.w $9500 ! ((grp_F4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A353
                dc.w $9500 ! ((grp_F4D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4D20 / 2) >> 16)
                dc.w 1
