byte_2E765A:    dc.b   0,  7,$6F,$66,$8E,$8F,$84,$62,$73,$6A
                                        ; DATA XREF: ROM:off_1CEC   o
                dc.w sprite_24_24
                dc.w $7671
                dc.w $9500 ! ((grp_145240 / 2) & $00FF)
                dc.w $9600 ! (((grp_145240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145240 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7261
                dc.w $9500 ! ((grp_15EA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EA40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7889
                dc.w $9500 ! ((grp_99A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6A67
                dc.w $9500 ! ((grp_B7EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $626D
                dc.w $9500 ! ((grp_EA180 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7089
                dc.w $9500 ! ((grp_EA160 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E81
                dc.w $9500 ! ((grp_EA1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA1A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E76
                dc.w $9500 ! ((grp_EA1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA1C0 / 2) >> 16)
                dc.w 1
