byte_2D77DC:    dc.b   0,  7,$77,$65,$8F,$99,$78,$78,$7C,$65
                                        ; DATA XREF: ROM:off_1300   o
                dc.w sprite_24_32
                dc.w $6B63
                dc.w $9500 ! ((grp_1000C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1000C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1000C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5B7C
                dc.w $9500 ! ((grp_79000 / 2) & $00FF)
                dc.w $9600 ! (((grp_79000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8363
                dc.w $9500 ! ((grp_194B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_194B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194B00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B83
                dc.w $9500 ! ((grp_CC240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8B5E
                dc.w $9500 ! ((grp_CC200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $638C
                dc.w $9500 ! ((grp_E66A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E66A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E66A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $636E
                dc.w $9500 ! ((grp_E66C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E66C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E66C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B66
                dc.w $9500 ! ((grp_E66E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E66E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E66E0 / 2) >> 16)
                dc.w 1
