byte_2F0470:    dc.b   0, $F,$5F,$57,$9A,$96,$7F,$75,$80,$75
                                        ; DATA XREF: ROM:000025E8   o
                dc.w sprite_32_32
                dc.w $6D53
                dc.w $9500 ! ((grp_33E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_33E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $5D73
                dc.w $9500 ! ((grp_54300 / 2) & $00FF)
                dc.w $9600 ! (((grp_54300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7D73
                dc.w $9500 ! ((grp_54400 / 2) & $00FF)
                dc.w $9600 ! (((grp_54400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5D8B
                dc.w $9500 ! ((grp_1663C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1663C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1663C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8D8B
                dc.w $9500 ! ((grp_166300 / 2) & $00FF)
                dc.w $9600 ! (((grp_166300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8D5B
                dc.w $9500 ! ((grp_17C680 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5D63
                dc.w $9500 ! ((grp_8B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B700 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A83
                dc.w $9500 ! ((grp_9E680 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E680 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8A83
                dc.w $9500 ! ((grp_9E700 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5A83
                dc.w $9500 ! ((grp_DA300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $556B
                dc.w $9500 ! ((grp_BFBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D63
                dc.w $9500 ! ((grp_BFC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D73
                dc.w $9500 ! ((grp_BFC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
