byte_2CD5C0:    dc.b   0,  2,$76,$6C,$89,$89,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8E8   o
                dc.w sprite_24_32
                dc.w $746D
                dc.w $9500 ! ((grp_F9C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7465
                dc.w $9500 ! ((grp_C71C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C71C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C71C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C8D
                dc.w $9500 ! ((grp_E1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1800 / 2) >> 16)
                dc.w 1
