byte_2F1D5A:    dc.b   0, $B,$76,$70,$99,$8E,$97,$70,$98,$70
                                        ; DATA XREF: ROM:off_26CC   o
                dc.w sprite_16_32
                dc.w $7C71
                dc.w $9500 ! ((grp_6BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $9C58
                dc.w $9500 ! ((grp_1669C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1669C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1669C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7473
                dc.w $9500 ! ((grp_AC080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $AC63
                dc.w $9500 ! ((grp_18DCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DCC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8269
                dc.w $9500 ! ((grp_DA980 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C5A
                dc.w $9500 ! ((grp_DA9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AB50
                dc.w $9500 ! ((grp_DAA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C71
                dc.w $9500 ! ((grp_C0040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $946A
                dc.w $9500 ! ((grp_C0080 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C81
                dc.w $9500 ! ((grp_F1C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C52
                dc.w $9500 ! ((grp_F1C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A67
                dc.w $9500 ! ((grp_F1C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1C60 / 2) >> 16)
                dc.w 1
