byte_2EEC78:    dc.b   0,  6,$6E,$4E,$89,$8E,$80,$7B,$81,$7B
                                        ; DATA XREF: ROM:off_2410   o
                dc.w sprite_24_32
                dc.w $6A63
                dc.w $9500 ! ((grp_1126C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1126C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1126C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6181
                dc.w $9500 ! ((grp_52B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_52B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8183
                dc.w $9500 ! ((grp_165280 / 2) & $00FF)
                dc.w $9600 ! (((grp_165280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $826B
                dc.w $9500 ! ((grp_17C080 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C080 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6279
                dc.w $9500 ! ((grp_F09E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F09E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F09E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8263
                dc.w $9500 ! ((grp_F0A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9986
                dc.w $9500 ! ((grp_F0A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0A00 / 2) >> 16)
                dc.w 1
