byte_2E4222:    dc.b   0,  8,$6D,$3D,$99,$63,$9B,$27,$90,$2D
                                        ; DATA XREF: ROM:off_1B24   o
                dc.w sprite_24_24
                dc.w $6B3E
                dc.w $9500 ! ((grp_143980 / 2) & $00FF)
                dc.w $9600 ! (((grp_143980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143980 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7256
                dc.w $9500 ! ((grp_7BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $833E
                dc.w $9500 ! ((grp_7BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E47
                dc.w $9500 ! ((grp_7BA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7136
                dc.w $9500 ! ((grp_186580 / 2) & $00FF)
                dc.w $9600 ! (((grp_186580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186580 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8B26
                dc.w $9500 ! ((grp_1865E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1865E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1865E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $842E
                dc.w $9500 ! ((grp_CDCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A56
                dc.w $9500 ! ((grp_E8400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9257
                dc.w $9500 ! ((grp_E83E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E83E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E83E0 / 2) >> 16)
                dc.w 1
