byte_2ED746:    dc.b   0,  4,$65,$5D,$8D,$94,$78,$76,$79,$76
                                        ; DATA XREF: ROM:off_22C4   o
                dc.w sprite_24_32
                dc.w $6764
                dc.w $9500 ! ((grp_112240 / 2) & $00FF)
                dc.w $9600 ! (((grp_112240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6F81
                dc.w $9500 ! ((grp_52600 / 2) & $00FF)
                dc.w $9600 ! (((grp_52600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $675C
                dc.w $9500 ! ((grp_D8E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F61
                dc.w $9500 ! ((grp_BEF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F6A
                dc.w $9500 ! ((grp_BEF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEF40 / 2) >> 16)
                dc.w 2
