byte_2D120A:    dc.b   0,  7,$61,$5D,$9F,$8E,$85,$75,$86,$75
                                        ; DATA XREF: ROM:off_DF4   o
                dc.w sprite_32_32
                dc.w $735C
                dc.w $9500 ! ((grp_15E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5B65
                dc.w $9500 ! ((grp_FC640 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC640 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $737C
                dc.w $9500 ! ((grp_158380 / 2) & $00FF)
                dc.w $9600 ! (((grp_158380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9B6A
                dc.w $9500 ! ((grp_171280 / 2) & $00FF)
                dc.w $9600 ! (((grp_171280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171280 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9362
                dc.w $9500 ! ((grp_1932A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1932A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1932A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $AB6E
                dc.w $9500 ! ((grp_B1E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $708A
                dc.w $9500 ! ((grp_E3A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8954
                dc.w $9500 ! ((grp_E3AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3AA0 / 2) >> 16)
                dc.w 1
