byte_2EBBB6:    dc.b   0, $C,$84,$5B,$A1,$80,$84,$7B,$85,$7B
                                        ; DATA XREF: ROM:off_206C   o
                dc.w sprite_32_32
                dc.w $6568
                dc.w $9500 ! ((grp_2C200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2C200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2C200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8568
                dc.w $9500 ! ((grp_2CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2CE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $5570
                dc.w $9500 ! ((grp_68000 / 2) & $00FF)
                dc.w $9600 ! (((grp_68000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $A568
                dc.w $9500 ! ((grp_68400 / 2) & $00FF)
                dc.w $9600 ! (((grp_68400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68400 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6588
                dc.w $9500 ! ((grp_9CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8588
                dc.w $9500 ! ((grp_9CD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6260
                dc.w $9500 ! ((grp_18C0A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C0A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C0A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4D70
                dc.w $9500 ! ((grp_19BCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BCA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5568
                dc.w $9500 ! ((grp_D7D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8490
                dc.w $9500 ! ((grp_D7E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A588
                dc.w $9500 ! ((grp_D7E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B570
                dc.w $9500 ! ((grp_BE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6590
                dc.w $9500 ! ((grp_EF6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF6E0 / 2) >> 16)
                dc.w 1
