byte_2CE016:    dc.b   0,  7,$65,$53,$94,$7B,$7C,$67,$7D,$67
                                        ; DATA XREF: ROM:off_9E4   o
                dc.w sprite_8_16
                dc.w $7971
                dc.w $9500 ! ((grp_B0D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A51
                dc.w $9500 ! ((grp_B0DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $615A
                dc.w $9500 ! ((grp_E24A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E24A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E24A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7359
                dc.w $9500 ! ((grp_E24C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E24C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E24C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C51
                dc.w $9500 ! ((grp_E24E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E24E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E24E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8467
                dc.w $9500 ! ((grp_E2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F6B
                dc.w $9500 ! ((grp_E2520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9460
                dc.w $9500 ! ((grp_E2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2500 / 2) >> 16)
                dc.w 1
