byte_2EC8C0:    dc.b   0,  3,$77,$79,$90,$8E,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_2170   o
                dc.w sprite_16_16
                dc.w $8180
                dc.w $9500 ! ((grp_88A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7978
                dc.w $9500 ! ((grp_19C360 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C360 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7163
                dc.w $9500 ! ((grp_BE940 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7472
                dc.w $9500 ! ((grp_EFE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFE60 / 2) >> 16)
                dc.w 1
