byte_2CF660:    dc.b   0, $B,$65,$72,$92,$97,$8D,$79,$8E,$79
                                        ; DATA XREF: ROM:off_B70   o
                dc.w sprite_32_24
                dc.w $6B81
                dc.w $9500 ! ((grp_120AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_120AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $665A
                dc.w $9500 ! ((grp_46900 / 2) & $00FF)
                dc.w $9600 ! (((grp_46900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $8661
                dc.w $9500 ! ((grp_1705C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1705C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1705C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6679
                dc.w $9500 ! ((grp_97300 / 2) & $00FF)
                dc.w $9600 ! (((grp_97300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E71
                dc.w $9500 ! ((grp_183D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_183D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8B81
                dc.w $9500 ! ((grp_192A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_192A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192A60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8679
                dc.w $9500 ! ((grp_C8740 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6381
                dc.w $9500 ! ((grp_B1640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8659
                dc.w $9500 ! ((grp_E2CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $938C
                dc.w $9500 ! ((grp_E2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A17A
                dc.w $9500 ! ((grp_E2D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2D20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AD61
                dc.w $9500 ! ((grp_E2D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2D40 / 2) >> 16)
                dc.w 1
