byte_2DF992:    dc.b   0,  5,$5D,$5E,$8F,$8D,$76,$75,$7B,$64
                                        ; DATA XREF: ROM:off_183C   o
                dc.w sprite_32_32
                dc.w $6A65
                dc.w $9500 ! ((grp_1F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1F000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6A85
                dc.w $9500 ! ((grp_4DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $6A5D
                dc.w $9500 ! ((grp_188EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_188EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6271
                dc.w $9500 ! ((grp_1984C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1984C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1984C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5A7C
                dc.w $9500 ! ((grp_EB5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB5C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A88
                dc.w $9500 ! ((grp_EB5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB5E0 / 2) >> 16)
                dc.w 1
