byte_2E6AC4:    dc.b   0,  7,$70,$63,$8C,$8C,$80,$71,$7A,$63
                                        ; DATA XREF: ROM:off_1C78   o
                dc.w sprite_24_24
                dc.w $7363
                dc.w $9500 ! ((grp_1472E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1472E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1472E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7283
                dc.w $9500 ! ((grp_1612C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1612C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1612C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8B63
                dc.w $9500 ! ((grp_161380 / 2) & $00FF)
                dc.w $9600 ! (((grp_161380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6363
                dc.w $9500 ! ((grp_178480 / 2) & $00FF)
                dc.w $9600 ! (((grp_178480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178480 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $745B
                dc.w $9500 ! ((grp_189C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_189C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189C40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $777B
                dc.w $9500 ! ((grp_D3E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F53
                dc.w $9500 ! ((grp_D3EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A8B
                dc.w $9500 ! ((grp_ECA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECA20 / 2) >> 16)
                dc.w 1
