byte_2E1FF4:    dc.b   0,  3,$76,$54,$8C,$8A,$81,$6F,$82,$6F
                                        ; DATA XREF: ROM:off_19D8   o
                dc.w sprite_32_32
                dc.w $745D
                dc.w $9500 ! ((grp_1B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1B000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $747D
                dc.w $9500 ! ((grp_4A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $744D
                dc.w $9500 ! ((grp_B5540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $854D
                dc.w $9500 ! ((grp_B5580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5580 / 2) >> 16)
                dc.w 2
