byte_2D355C:    dc.b   0,  6,$75,$5B,$88,$95,$81,$78,$82,$78
                                        ; DATA XREF: ROM:off_1010   o
                dc.w sprite_24_16
                dc.w $7159
                dc.w $9500 ! ((grp_159400 / 2) & $00FF)
                dc.w $9600 ! (((grp_159400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7970
                dc.w $9500 ! ((grp_172180 / 2) & $00FF)
                dc.w $9600 ! (((grp_172180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7B88
                dc.w $9500 ! ((grp_77780 / 2) & $00FF)
                dc.w $9600 ! (((grp_77780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $697C
                dc.w $9500 ! ((grp_CA800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7569
                dc.w $9500 ! ((grp_CA840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8979
                dc.w $9500 ! ((grp_E4FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E77
                dc.w $9500 ! ((grp_E4FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4FC0 / 2) >> 16)
                dc.w 1
