byte_2CCA86:    dc.b   0,  7,$45,$7D,$AE,$90,$79,$86,$7A,$86
                                        ; DATA XREF: ROM:off_7EC   o
                dc.w sprite_32_16
                dc.w $6C83
                dc.w $9500 ! ((grp_46200 / 2) & $00FF)
                dc.w $9600 ! (((grp_46200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46200 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8C81
                dc.w $9500 ! ((grp_46300 / 2) & $00FF)
                dc.w $9600 ! (((grp_46300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46300 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $4C8B
                dc.w $9500 ! ((grp_96C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $487D
                dc.w $9500 ! ((grp_C6D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6483
                dc.w $9500 ! ((grp_E16C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E16C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E16C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $877B
                dc.w $9500 ! ((grp_E16E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E16E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E16E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A579
                dc.w $9500 ! ((grp_E1700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AC83
                dc.w $9500 ! ((grp_E1720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1720 / 2) >> 16)
                dc.w 1
