byte_2F7C0E:    dc.b   0, $C,$64,$42,$9E,$83,$98,$75,$99,$75
                                        ; DATA XREF: ROM:off_2BBC   o
                dc.w sprite_32_32
                dc.w $6463
                dc.w $9500 ! ((grp_40400 / 2) & $00FF)
                dc.w $9600 ! (((grp_40400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8463
                dc.w $9500 ! ((grp_40600 / 2) & $00FF)
                dc.w $9600 ! (((grp_40600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $6483
                dc.w $9500 ! ((grp_90880 / 2) & $00FF)
                dc.w $9600 ! (((grp_90880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $695B
                dc.w $9500 ! ((grp_DDBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6A93
                dc.w $9500 ! ((grp_DDC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C83
                dc.w $9500 ! ((grp_DDC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $895B
                dc.w $9500 ! ((grp_DDB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9483
                dc.w $9500 ! ((grp_DDC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C6B
                dc.w $9500 ! ((grp_C34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C34C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9353
                dc.w $9500 ! ((grp_F5E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948B
                dc.w $9500 ! ((grp_F5E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A473
                dc.w $9500 ! ((grp_F5E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5E20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AF72
                dc.w $9500 ! ((grp_F5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5E80 / 2) >> 16)
                dc.w 1
