byte_2FF0FA:    dc.b   0,  1,$7B,$78,$90,$8B,$85,$82,$86,$82
                                        ; DATA XREF: ROM:off_3544   o
                dc.w sprite_32_24
                dc.w $746E
                dc.w $9500 ! ((grp_13C9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7486
                dc.w $9500 ! ((grp_E0F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0F40 / 2) >> 16)
                dc.w 2
