byte_2F8230:    dc.b   0,  2,$71,$6A,$90,$A0,$7F,$8E,$80,$8E
                                        ; DATA XREF: ROM:off_2C50   o
                dc.w sprite_32_24
                dc.w $6E7F
                dc.w $9500 ! ((grp_138040 / 2) & $00FF)
                dc.w $9600 ! (((grp_138040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_138040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7997
                dc.w $9500 ! ((grp_DDD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E81
                dc.w $9500 ! ((grp_F5F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5F20 / 2) >> 16)
                dc.w 1
