byte_2CEC00:    dc.b   0,  4,$7B,$47,$87,$7F,$81,$63,$82,$63
                                        ; DATA XREF: ROM:off_B18   o
                dc.w sprite_8_24
                dc.w $816D
                dc.w $9500 ! ((grp_1923A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1923A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1923A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8145
                dc.w $9500 ! ((grp_192400 / 2) & $00FF)
                dc.w $9600 ! (((grp_192400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192400 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $825D
                dc.w $9500 ! ((grp_B0FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7945
                dc.w $9500 ! ((grp_E2660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $797D
                dc.w $9500 ! ((grp_E2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2680 / 2) >> 16)
                dc.w 1
