byte_2FC550:    dc.b   0,  7,$44,$5A,$BF,$AA,$81,$94,$82,$94
                                        ; DATA XREF: ROM:off_3118   o
                dc.w sprite_32_16
                dc.w $8E97
                dc.w $9500 ! ((grp_57B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_57B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $467F
                dc.w $9500 ! ((grp_16C540 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C540 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $5E86
                dc.w $9500 ! ((grp_16C480 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C480 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $768D
                dc.w $9500 ! ((grp_16C3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C3C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $AE9E
                dc.w $9500 ! ((grp_93400 / 2) & $00FF)
                dc.w $9600 ! (((grp_93400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $3E7F
                dc.w $9500 ! ((grp_F7F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E8F
                dc.w $9500 ! ((grp_F7F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BE9F
                dc.w $9500 ! ((grp_F7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7F00 / 2) >> 16)
                dc.w 1
