byte_2E655E:    dc.b   0,  8,$6C,$60,$89,$8E,$75,$74,$74,$63
                                        ; DATA XREF: ROM:off_1C4C   o
                dc.w sprite_24_16
                dc.w $6B59
                dc.w $9500 ! ((grp_160F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_160F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7F79
                dc.w $9500 ! ((grp_178300 / 2) & $00FF)
                dc.w $9600 ! (((grp_178300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B6C
                dc.w $9500 ! ((grp_83180 / 2) & $00FF)
                dc.w $9600 ! (((grp_83180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6B69
                dc.w $9500 ! ((grp_83200 / 2) & $00FF)
                dc.w $9600 ! (((grp_83200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6F89
                dc.w $9500 ! ((grp_D3C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8371
                dc.w $9500 ! ((grp_D3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B69
                dc.w $9500 ! ((grp_BAC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8361
                dc.w $9500 ! ((grp_BAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7781
                dc.w $9500 ! ((grp_EC8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC8C0 / 2) >> 16)
                dc.w 1
