byte_2DB33E:    dc.b   0,  7,$65,$60,$9E,$8F,$81,$77,$82,$77
                                        ; DATA XREF: ROM:off_1544   o
                dc.w sprite_24_32
                dc.w $735E
                dc.w $9500 ! ((grp_10CB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_10CB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10CB40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $635E
                dc.w $9500 ! ((grp_179200 / 2) & $00FF)
                dc.w $9600 ! (((grp_179200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7B7E
                dc.w $9500 ! ((grp_85580 / 2) & $00FF)
                dc.w $9600 ! (((grp_85580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8B5E
                dc.w $9500 ! ((grp_18A660 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A660 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B88
                dc.w $9500 ! ((grp_D5780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $868B
                dc.w $9500 ! ((grp_D57C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D57C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D57C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7380
                dc.w $9500 ! ((grp_EDA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDA60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B66
                dc.w $9500 ! ((grp_EDA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDA80 / 2) >> 16)
                dc.w 1
