byte_2EC81E:    dc.b   0,  3,$66,$54,$8C,$61,$79,$5B,$7A,$5B
                                        ; DATA XREF: ROM:off_2164   o
                dc.w sprite_16_16
                dc.w $7754
                dc.w $9500 ! ((grp_88A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_88A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6858
                dc.w $9500 ! ((grp_D8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8754
                dc.w $9500 ! ((grp_BE900 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $645B
                dc.w $9500 ! ((grp_EFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFE00 / 2) >> 16)
                dc.w 1
