byte_2E866E:    dc.b   0, $D,$6F,$67,$8E,$8F,$D0,$39,$86,$5E
                                        ; DATA XREF: ROM:off_1D7C   o
                dc.w sprite_24_24
                dc.w $7460
                dc.w $9500 ! ((grp_143BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_143BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143BC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7378
                dc.w $9500 ! ((grp_186940 / 2) & $00FF)
                dc.w $9600 ! (((grp_186940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186940 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7680
                dc.w $9500 ! ((grp_1869A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1869A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1869A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6F88
                dc.w $9500 ! ((grp_CE540 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8158
                dc.w $9500 ! ((grp_CE500 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8488
                dc.w $9500 ! ((grp_CE580 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE580 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A14D
                dc.w $9500 ! ((grp_CE5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AD46
                dc.w $9500 ! ((grp_CE600 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $CC34
                dc.w $9500 ! ((grp_B6180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C68
                dc.w $9500 ! ((grp_E87E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E87E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E87E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9153
                dc.w $9500 ! ((grp_E8780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9952
                dc.w $9500 ! ((grp_E87A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E87A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E87A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $BD42
                dc.w $9500 ! ((grp_E87C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E87C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E87C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C43D
                dc.w $9500 ! ((grp_E8760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8760 / 2) >> 16)
                dc.w 1
