byte_2D5AC8:    dc.b   0,  6,$77,$5F,$8E,$95,$8C,$7C,$81,$6B
                                        ; DATA XREF: ROM:off_11D0   o
                dc.w sprite_24_32
                dc.w $766E
                dc.w $9500 ! ((grp_FF4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8E6E
                dc.w $9500 ! ((grp_78A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $898B
                dc.w $9500 ! ((grp_CBDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $946B
                dc.w $9500 ! ((grp_CBE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $778E
                dc.w $9500 ! ((grp_B3C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B5E
                dc.w $9500 ! ((grp_B3CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8365
                dc.w $9500 ! ((grp_E6380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6380 / 2) >> 16)
                dc.w 1
