byte_2EE280:    dc.b   0,  4,$6B,$6A,$96,$93,$81,$7F,$82,$7F
                                        ; DATA XREF: ROM:off_2378   o
                dc.w sprite_32_32
                dc.w $6F70
                dc.w $9500 ! ((grp_31800 / 2) & $00FF)
                dc.w $9600 ! (((grp_31800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8F72
                dc.w $9500 ! ((grp_17BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BC00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6774
                dc.w $9500 ! ((grp_19CEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CEA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7868
                dc.w $9500 ! ((grp_D9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9280 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7990
                dc.w $9500 ! ((grp_D92C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D92C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D92C0 / 2) >> 16)
                dc.w 2
