byte_2F830C:    dc.b   0,  2,$71,$6A,$90,$A0,$81,$8E,$82,$8E
                                        ; DATA XREF: ROM:off_2C60   o
                dc.w sprite_32_24
                dc.w $747E
                dc.w $9500 ! ((grp_138340 / 2) & $00FF)
                dc.w $9600 ! (((grp_138340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_138340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7A96
                dc.w $9500 ! ((grp_DDE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C80
                dc.w $9500 ! ((grp_F5F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5F80 / 2) >> 16)
                dc.w 1
