byte_2FE5DE:    dc.b   0,  1,$74,$7D,$83,$83,$7B,$80,$7C,$80
                                        ; DATA XREF: ROM:off_33F4   o
                dc.w sprite_24_8
                dc.w $727B
                dc.w $9500 ! ((grp_191920 / 2) & $00FF)
                dc.w $9600 ! (((grp_191920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7283
                dc.w $9500 ! ((grp_E0E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0E40 / 2) >> 16)
                dc.w 2
