byte_2E8BA8:    dc.b   0,  3,$77,$67,$83,$8C,$7E,$79,$7E,$6C
                                        ; DATA XREF: ROM:off_1DB8   o
                dc.w sprite_24_16
                dc.w $747F
                dc.w $9500 ! ((grp_15CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15CA00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7367
                dc.w $9500 ! ((grp_7C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B77
                dc.w $9500 ! ((grp_CE840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $745F
                dc.w $9500 ! ((grp_E8940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8940 / 2) >> 16)
                dc.w 1
