byte_2D860A:    dc.b   0,  7,$76,$5E,$8F,$9C,$7F,$7E,$83,$6C
                                        ; DATA XREF: ROM:off_139C   o
                dc.w sprite_16_32
                dc.w $777E
                dc.w $9500 ! ((grp_61B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $876F
                dc.w $9500 ! ((grp_15D180 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7866
                dc.w $9500 ! ((grp_174F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_174F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174F40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6280
                dc.w $9500 ! ((grp_7D180 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6872
                dc.w $9500 ! ((grp_7D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8297
                dc.w $9500 ! ((grp_CF7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $877F
                dc.w $9500 ! ((grp_CF800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D5E
                dc.w $9500 ! ((grp_E9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9400 / 2) >> 16)
                dc.w 1
