byte_2FDD9E:    dc.b   0,  5,$74,$4C,$92,$8D,$83,$6C,$84,$6C
                                        ; DATA XREF: ROM:off_334C   o
                dc.w sprite_16_32
                dc.w $7A68
                dc.w $9500 ! ((grp_71200 / 2) & $00FF)
                dc.w $9600 ! (((grp_71200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7A48
                dc.w $9500 ! ((grp_71300 / 2) & $00FF)
                dc.w $9600 ! (((grp_71300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $725E
                dc.w $9500 ! ((grp_AEE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A5C
                dc.w $9500 ! ((grp_AEF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_191500 / 2) & $00FF)
                dc.w $9600 ! (((grp_191500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191500 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9265
                dc.w $9500 ! ((grp_C5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5E00 / 2) >> 16)
                dc.w 2
