byte_2CF7FE:    dc.b   0,  1,$7A,$73,$84,$93,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_B94   o
                dc.w sprite_16_32
                dc.w $7871
                dc.w $9500 ! ((grp_5CB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5CB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5CB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7891
                dc.w $9500 ! ((grp_C8840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8840 / 2) >> 16)
                dc.w 2
