byte_2CD078:    dc.b   0,  2,$7B,$79,$8F,$8D,$85,$83,$86,$83
                                        ; DATA XREF: ROM:off_868   o
                dc.w sprite_16_16
                dc.w $8577
                dc.w $9500 ! ((grp_73A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_73A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $798A
                dc.w $9500 ! ((grp_C70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C70C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D7A
                dc.w $9500 ! ((grp_B05C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B05C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B05C0 / 2) >> 16)
                dc.w 2
