byte_2F18E2:    dc.b   0,  3,$7B,$69,$8F,$87,$85,$78,$86,$78
                                        ; DATA XREF: ROM:off_268C   o
                dc.w sprite_16_32
                dc.w $7967
                dc.w $9500 ! ((grp_6CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6CE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $8967
                dc.w $9500 ! ((grp_C0B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C87
                dc.w $9500 ! ((grp_F2A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2A20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9173
                dc.w $9500 ! ((grp_F2A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2A40 / 2) >> 16)
                dc.w 1
