byte_2D25F4:    dc.b   0, $C,$5D,$4A,$A3,$73,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_EE8   o
                dc.w sprite_24_24
                dc.w $8763
                dc.w $9500 ! ((grp_140260 / 2) & $00FF)
                dc.w $9600 ! (((grp_140260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140260 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $5F7E
                dc.w $9500 ! ((grp_5E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_5E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5E000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5F66
                dc.w $9500 ! ((grp_171880 / 2) & $00FF)
                dc.w $9600 ! (((grp_171880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171880 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7763
                dc.w $9500 ! ((grp_1717C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1717C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1717C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $775B
                dc.w $9500 ! ((grp_97C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $576C
                dc.w $9500 ! ((grp_A4100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6F75
                dc.w $9500 ! ((grp_193780 / 2) & $00FF)
                dc.w $9600 ! (((grp_193780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193780 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6F5D
                dc.w $9500 ! ((grp_1937E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1937E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1937E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9F6A
                dc.w $9500 ! ((grp_193840 / 2) & $00FF)
                dc.w $9600 ! (((grp_193840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193840 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $679E
                dc.w $9500 ! ((grp_C9EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $578C
                dc.w $9500 ! ((grp_E43C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E43C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E43C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $675E
                dc.w $9500 ! ((grp_E4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $777B
                dc.w $9500 ! ((grp_E43A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E43A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E43A0 / 2) >> 16)
                dc.w 1
