byte_2FE236:    dc.b   0,  1,$74,$72,$8D,$8D,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_33AC   o
                dc.w sprite_24_32
                dc.w $7A70
                dc.w $9500 ! ((grp_11D340 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D340 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $7270
                dc.w $9500 ! ((grp_1A0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0980 / 2) >> 16)
                dc.w 3
