byte_2F1CFE:    dc.b   0,  3,$79,$76,$8E,$8E,$83,$82,$84,$82
                                        ; DATA XREF: ROM:off_26C4   o
                dc.w sprite_24_16
                dc.w $7A74
                dc.w $9500 ! ((grp_166900 / 2) & $00FF)
                dc.w $9600 ! (((grp_166900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7B84
                dc.w $9500 ! ((grp_8BE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7276
                dc.w $9500 ! ((grp_F1BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $738A
                dc.w $9500 ! ((grp_F1BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1BC0 / 2) >> 16)
                dc.w 1
