byte_2FC668:    dc.b   0,  6,$3F,$5A,$BB,$AA,$7D,$94,$7E,$94
                                        ; DATA XREF: ROM:00003128   o
                dc.w sprite_24_16
                dc.w $4F97
                dc.w $9500 ! ((grp_16C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C600 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $6F8E
                dc.w $9500 ! ((grp_16C6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C6C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8787
                dc.w $9500 ! ((grp_16C780 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C780 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $A77F
                dc.w $9500 ! ((grp_16C840 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $3F9E
                dc.w $9500 ! ((grp_93480 / 2) & $00FF)
                dc.w $9600 ! (((grp_93480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6795
                dc.w $9500 ! ((grp_C5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F84
                dc.w $9500 ! ((grp_C5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5380 / 2) >> 16)
                dc.w 2
