byte_2E0698:    dc.b   0,  9,$68,$5D,$9A,$94,$81,$78,$8C,$6D
                                        ; DATA XREF: ROM:off_18D0   o
                dc.w sprite_16_32
                dc.w $6A72
                dc.w $9500 ! ((grp_64100 / 2) & $00FF)
                dc.w $9600 ! (((grp_64100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8257
                dc.w $9500 ! ((grp_A7400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8277
                dc.w $9500 ! ((grp_A7480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A63
                dc.w $9500 ! ((grp_A7500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9270
                dc.w $9500 ! ((grp_A7580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7A6F
                dc.w $9500 ! ((grp_198B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_198B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198B20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $627F
                dc.w $9500 ! ((grp_B9940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A87
                dc.w $9500 ! ((grp_B9980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A83
                dc.w $9500 ! ((grp_B99C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B99C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B99C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A7B
                dc.w $9500 ! ((grp_B9A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9A00 / 2) >> 16)
                dc.w 2
