byte_2F20C4:    dc.b   0, $A,$6E,$66,$AB,$92,$8A,$76,$8B,$76
                                        ; DATA XREF: ROM:off_26E8   o
                dc.w sprite_32_32
                dc.w $7160
                dc.w $9500 ! ((grp_36C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_36C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $916A
                dc.w $9500 ! ((grp_36E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_36E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $7980
                dc.w $9500 ! ((grp_166A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_166A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6168
                dc.w $9500 ! ((grp_17CEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7D58
                dc.w $9500 ! ((grp_DABC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DABC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DABC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B16E
                dc.w $9500 ! ((grp_C0240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7A90
                dc.w $9500 ! ((grp_F1DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1DC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A90
                dc.w $9500 ! ((grp_F1DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $918A
                dc.w $9500 ! ((grp_F1D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1D40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9162
                dc.w $9500 ! ((grp_F1D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A962
                dc.w $9500 ! ((grp_F1D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1D80 / 2) >> 16)
                dc.w 1
