byte_2E9FE6:    dc.b   0,  6,$81,$76,$94,$86,$90,$76,$91,$76
                                        ; DATA XREF: ROM:off_1EF4   o
                dc.w sprite_32_16
                dc.w $8A66
                dc.w $9500 ! ((grp_50E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7278
                dc.w $9500 ! ((grp_86E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $826F
                dc.w $9500 ! ((grp_A9900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8A76
                dc.w $9500 ! ((grp_18B7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B7A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8A7E
                dc.w $9500 ! ((grp_D70C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D70C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D70C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9F5E
                dc.w $9500 ! ((grp_D7100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A86
                dc.w $9500 ! ((grp_EEE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEE00 / 2) >> 16)
                dc.w 1
