byte_2DDDFC:    dc.b   0,  3,$77,$6A,$8D,$90,$82,$7D,$83,$7D
                                        ; DATA XREF: ROM:00001728   o
                dc.w sprite_24_32
                dc.w $7570
                dc.w $9500 ! ((grp_1075C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1075C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1075C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7568
                dc.w $9500 ! ((grp_188AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_188AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188AA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7690
                dc.w $9500 ! ((grp_D2180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D70
                dc.w $9500 ! ((grp_B8FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8FC0 / 2) >> 16)
                dc.w 2
