byte_2EFABC:    dc.b   0,  3,$79,$7B,$8B,$8C,$82,$83,$83,$83
                                        ; DATA XREF: ROM:off_2558   o
                dc.w sprite_16_8
                dc.w $7785
                dc.w $9500 ! ((grp_D9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A7E
                dc.w $9500 ! ((grp_DA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F8D
                dc.w $9500 ! ((grp_F0D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0D00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8679
                dc.w $9500 ! ((grp_F12A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F12A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F12A0 / 2) >> 16)
                dc.w 1
