byte_2CDAF6:    dc.b   0,  9,$68,$4C,$9A,$8D,$81,$6C,$82,$6C
                                        ; DATA XREF: ROM:off_974   o
                dc.w sprite_32_32
                dc.w $6D52
                dc.w $9500 ! ((grp_10A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_10A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6572
                dc.w $9500 ! ((grp_11F8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11F8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11F8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $857A
                dc.w $9500 ! ((grp_156C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_156C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8D53
                dc.w $9500 ! ((grp_16FD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FD80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $694A
                dc.w $9500 ! ((grp_C7FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8572
                dc.w $9500 ! ((grp_C8000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6552
                dc.w $9500 ! ((grp_E21A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E21A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E21A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $656A
                dc.w $9500 ! ((grp_E21C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E21C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E21C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D8A
                dc.w $9500 ! ((grp_E21E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E21E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E21E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D8A
                dc.w $9500 ! ((grp_E2200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2200 / 2) >> 16)
                dc.w 1
