byte_2E184E:    dc.b   0,  5,$75,$70,$96,$8D,$84,$7E,$94,$80
                                        ; DATA XREF: ROM:off_1964   o
                dc.w sprite_24_32
                dc.w $7B70
                dc.w $9500 ! ((grp_109840 / 2) & $00FF)
                dc.w $9600 ! (((grp_109840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109840 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $7378
                dc.w $9500 ! ((grp_198D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_198D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8068
                dc.w $9500 ! ((grp_D2E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B7A
                dc.w $9500 ! ((grp_B9B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9376
                dc.w $9500 ! ((grp_B9B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9B7D
                dc.w $9500 ! ((grp_EBE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBE00 / 2) >> 16)
                dc.w 1
