byte_2EBD54:    dc.b   0,  9,$84,$5B,$A1,$80,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_2078   o
                dc.w sprite_32_32
                dc.w $6C66
                dc.w $9500 ! ((grp_2D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_2D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2D800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8C69
                dc.w $9500 ! ((grp_2DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2DA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $5C66
                dc.w $9500 ! ((grp_68500 / 2) & $00FF)
                dc.w $9600 ! (((grp_68500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7486
                dc.w $9500 ! ((grp_163A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_163A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163A80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $546E
                dc.w $9500 ! ((grp_AA800 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5C86
                dc.w $9500 ! ((grp_18C160 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C160 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8C89
                dc.w $9500 ! ((grp_18C1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C1C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $AC6F
                dc.w $9500 ! ((grp_19BE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BE20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4C82
                dc.w $9500 ! ((grp_BE240 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $548E
                dc.w $9500 ! ((grp_EF780 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF780 / 2) >> 16)
                dc.w 1
