byte_2D7846:    dc.b   0,  5,$77,$65,$8F,$99,$70,$72,$87,$7E
                                        ; DATA XREF: ROM:off_1304   o
                dc.w sprite_32_24
                dc.w $626B
                dc.w $9500 ! ((grp_1240C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1240C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1240C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5277
                dc.w $9500 ! ((grp_79080 / 2) & $00FF)
                dc.w $9600 ! (((grp_79080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8273
                dc.w $9500 ! ((grp_79100 / 2) & $00FF)
                dc.w $9600 ! (((grp_79100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $825B
                dc.w $9500 ! ((grp_194B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_194B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194B60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $536F
                dc.w $9500 ! ((grp_E6720 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A5E
                dc.w $9500 ! ((grp_E6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6700 / 2) >> 16)
                dc.w 1
