byte_2F7B50:    dc.b   0, $E,$64,$42,$9E,$83,$97,$71,$98,$71
                                        ; DATA XREF: ROM:off_2BB8   o
                dc.w sprite_24_32
                dc.w $635B
                dc.w $9500 ! ((grp_119740 / 2) & $00FF)
                dc.w $9600 ! (((grp_119740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7B63
                dc.w $9500 ! ((grp_6EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6EF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8B53
                dc.w $9500 ! ((grp_6F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $637B
                dc.w $9500 ! ((grp_169CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_169CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $A361
                dc.w $9500 ! ((grp_17FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $BC5C
                dc.w $9500 ! ((grp_17FBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $688B
                dc.w $9500 ! ((grp_90800 / 2) & $00FF)
                dc.w $9600 ! (((grp_90800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B73
                dc.w $9500 ! ((grp_90780 / 2) & $00FF)
                dc.w $9600 ! (((grp_90780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9B63
                dc.w $9500 ! ((grp_AE280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B83
                dc.w $9500 ! ((grp_DDB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9383
                dc.w $9500 ! ((grp_DDB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B6B
                dc.w $9500 ! ((grp_C3440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B363
                dc.w $9500 ! ((grp_C3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $938B
                dc.w $9500 ! ((grp_F5DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AF4B
                dc.w $9500 ! ((grp_F5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5E00 / 2) >> 16)
                dc.w 1
