byte_2F96E4:    dc.b   0,  1,$91,$7B,$A3,$87,$9A,$81,$9B,$81
                                        ; DATA XREF: ROM:off_2D78   o
                dc.w sprite_16_16
                dc.w $967A
                dc.w $9500 ! ((grp_91180 / 2) & $00FF)
                dc.w $9600 ! (((grp_91180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8E79
                dc.w $9500 ! ((grp_C41C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C41C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C41C0 / 2) >> 16)
                dc.w 2
