byte_2E9E4E:    dc.b   0,  1,$6E,$84,$91,$8E,$7F,$88,$80,$88
                                        ; DATA XREF: ROM:off_1EDC   o
                dc.w sprite_32_16
                dc.w $7481
                dc.w $9500 ! ((grp_50F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $6C82
                dc.w $9500 ! ((grp_BDA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDA80 / 2) >> 16)
                dc.w 2
