byte_2EC1B4:    dc.b   0,  3,$72,$6D,$93,$8F,$82,$7E,$83,$7E
                                        ; DATA XREF: ROM:off_20B8   o
                dc.w sprite_32_24
                dc.w $6E72
                dc.w $9500 ! ((grp_131740 / 2) & $00FF)
                dc.w $9600 ! (((grp_131740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_131740 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $728A
                dc.w $9500 ! ((grp_9D380 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8E6A
                dc.w $9500 ! ((grp_AAA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $766A
                dc.w $9500 ! ((grp_18C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C400 / 2) >> 16)
                dc.w 3
