byte_2E1162:    dc.b   0, $F,$72,$5A,$8E,$8E,$7B,$3F,$79,$28
                                        ; DATA XREF: ROM:off_192C   o
                dc.w sprite_16_32
                dc.w $8B36
                dc.w $9500 ! ((grp_60B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6336
                dc.w $9500 ! ((grp_15BA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BA40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8B26
                dc.w $9500 ! ((grp_15BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7350
                dc.w $9500 ! ((grp_7B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $831E
                dc.w $9500 ! ((grp_A5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6326
                dc.w $9500 ! ((grp_185F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_185F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185F80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5B34
                dc.w $9500 ! ((grp_195A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_195A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7B1E
                dc.w $9500 ! ((grp_195A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_195A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195A60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $833E
                dc.w $9500 ! ((grp_1959A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1959A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1959A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9B43
                dc.w $9500 ! ((grp_195880 / 2) & $00FF)
                dc.w $9600 ! (((grp_195880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195880 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $632E
                dc.w $9500 ! ((grp_CD500 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $931E
                dc.w $9500 ! ((grp_CD400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5338
                dc.w $9500 ! ((grp_B5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B4E
                dc.w $9500 ! ((grp_B5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B40
                dc.w $9500 ! ((grp_B5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $732E
                dc.w $9500 ! ((grp_E7B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B40 / 2) >> 16)
                dc.w 1
