byte_2FB310:    dc.b   0,  4,$61,$6E,$8F,$90,$78,$7F,$79,$7F
                                        ; DATA XREF: ROM:off_2F58   o
                dc.w sprite_32_32
                dc.w $676C
                dc.w $9500 ! ((grp_43000 / 2) & $00FF)
                dc.w $9600 ! (((grp_43000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $8784
                dc.w $9500 ! ((grp_91D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_91D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5F6C
                dc.w $9500 ! ((grp_19FCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FCC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $778C
                dc.w $9500 ! ((grp_DF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8774
                dc.w $9500 ! ((grp_C4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4C40 / 2) >> 16)
                dc.w 2
