byte_2FEFA8:    dc.b   0,  2,$6F,$72,$91,$8D,$80,$7F,$81,$7F
                                        ; DATA XREF: ROM:off_3518   o
                dc.w sprite_24_32
                dc.w $7470
                dc.w $9500 ! ((grp_11D7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6C71
                dc.w $9500 ! ((grp_1A1640 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1640 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8C78
                dc.w $9500 ! ((grp_1A15E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A15E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A15E0 / 2) >> 16)
                dc.w 3
