byte_2D83A6:    dc.b   0,  6,$72,$5D,$87,$7C,$7C,$70,$7C,$60
                                        ; DATA XREF: ROM:off_1384   o
                dc.w sprite_24_32
                dc.w $6F5F
                dc.w $9500 ! ((grp_1006C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1006C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1006C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $754F
                dc.w $9500 ! ((grp_15A840 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A840 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7D8B
                dc.w $9500 ! ((grp_CC7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $675F
                dc.w $9500 ! ((grp_B4300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B7F
                dc.w $9500 ! ((grp_B4340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8573
                dc.w $9500 ! ((grp_B4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D79
                dc.w $9500 ! ((grp_E6BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6BC0 / 2) >> 16)
                dc.w 1
