byte_2D6FD4:    dc.b   0,  6,$74,$55,$92,$7A,$7F,$4E,$8D,$50
                                        ; DATA XREF: ROM:off_12A8   o
                dc.w sprite_32_24
                dc.w $754A
                dc.w $9500 ! ((grp_12EBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12EBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12EBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7B72
                dc.w $9500 ! ((grp_162E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_162E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $955A
                dc.w $9500 ! ((grp_17A100 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7962
                dc.w $9500 ! ((grp_86380 / 2) & $00FF)
                dc.w $9600 ! (((grp_86380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D52
                dc.w $9500 ! ((grp_19AA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AA40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $655B
                dc.w $9500 ! ((grp_BCF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E82
                dc.w $9500 ! ((grp_EE600 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE600 / 2) >> 16)
                dc.w 1
