byte_2EB5B0:    dc.b   0,  5,$71,$55,$8F,$8D,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_2030   o
                dc.w sprite_32_32
                dc.w $6F6D
                dc.w $9500 ! ((grp_2AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2AE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8F75
                dc.w $9500 ! ((grp_17AD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_17AD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17AD00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6E8D
                dc.w $9500 ! ((grp_9C880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6775
                dc.w $9500 ! ((grp_19BB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BB20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8E8D
                dc.w $9500 ! ((grp_EF520 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F6D
                dc.w $9500 ! ((grp_EF540 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF540 / 2) >> 16)
                dc.w 1
