byte_2DC80A:    dc.b   0,  5,$70,$64,$88,$8D,$80,$78,$81,$68
                                        ; DATA XREF: ROM:0000163C   o
                dc.w sprite_24_24
                dc.w $6E6A
                dc.w $9500 ! ((grp_144EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_144EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144EE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $8668
                dc.w $9500 ! ((grp_7DB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7382
                dc.w $9500 ! ((grp_187780 / 2) & $00FF)
                dc.w $9600 ! (((grp_187780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187780 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_CFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7662
                dc.w $9500 ! ((grp_CFE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838A
                dc.w $9500 ! ((grp_CFE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFE80 / 2) >> 16)
                dc.w 2
