byte_2EA1AA:    dc.b   0,  4,$56,$7A,$9B,$8D,$80,$84,$47,$80
                                        ; DATA XREF: ROM:off_1F14   o
                dc.w sprite_32_24
                dc.w $6678
                dc.w $9500 ! ((grp_12FC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12FC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12FC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8E78
                dc.w $9500 ! ((grp_17A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_17A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17A400 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8678
                dc.w $9500 ! ((grp_19B220 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $547E
                dc.w $9500 ! ((grp_BDC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E7D
                dc.w $9500 ! ((grp_BDC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDC80 / 2) >> 16)
                dc.w 2
