byte_2EEB80:    dc.b   0,  7,$6E,$4E,$89,$8E,$82,$69,$83,$69
                                        ; DATA XREF: ROM:off_2408   o
                dc.w sprite_32_32
                dc.w $6C65
                dc.w $9500 ! ((grp_33200 / 2) & $00FF)
                dc.w $9600 ! (((grp_33200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7245
                dc.w $9500 ! ((grp_33400 / 2) & $00FF)
                dc.w $9600 ! (((grp_33400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_33400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6785
                dc.w $9500 ! ((grp_9E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C65
                dc.w $9500 ! ((grp_AB980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9261
                dc.w $9500 ! ((grp_ABA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8785
                dc.w $9500 ! ((grp_18D480 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D480 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9251
                dc.w $9500 ! ((grp_BF640 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A5D
                dc.w $9500 ! ((grp_F09C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F09C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F09C0 / 2) >> 16)
                dc.w 1
