byte_2CD998:    dc.b   0,  1,$84,$87,$94,$8C,$83,$8E,$84,$9F
                                        ; DATA XREF: ROM:off_948   o
                dc.w sprite_24_8
                dc.w $8087
                dc.w $9500 ! ((grp_183520 / 2) & $00FF)
                dc.w $9600 ! (((grp_183520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $907F
                dc.w $9500 ! ((grp_E1EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1EA0 / 2) >> 16)
                dc.w 1
