byte_2E909A:    dc.b   0,  2,$74,$64,$86,$8E,$81,$78,$80,$72
                                        ; DATA XREF: ROM:off_1E0C   o
                dc.w sprite_24_32
                dc.w $7262
                dc.w $9500 ! ((grp_104EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_104EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7282
                dc.w $9500 ! ((grp_7EC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7EC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7EC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8A72
                dc.w $9500 ! ((grp_B7A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7A00 / 2) >> 16)
                dc.w 2
