byte_2D7D3C:    dc.b   0,  6,$75,$5D,$8B,$A2,$82,$81,$81,$6A
                                        ; DATA XREF: ROM:off_1338   o
                dc.w sprite_16_32
                dc.w $7786
                dc.w $9500 ! ((grp_5FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5FB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8473
                dc.w $9500 ! ((grp_15A540 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A540 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $746E
                dc.w $9500 ! ((grp_172F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_172F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6C74
                dc.w $9500 ! ((grp_194D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_194D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C66
                dc.w $9500 ! ((grp_CC600 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C5E
                dc.w $9500 ! ((grp_E6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906B
                dc.w $9500 ! ((grp_E68A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E68A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E68A0 / 2) >> 16)
                dc.w 1
