byte_2D6402:    dc.b   0,  7,$6F,$5B,$8E,$8F,$7F,$70,$81,$5E
                                        ; DATA XREF: ROM:off_1234   o
                dc.w sprite_24_32
                dc.w $7855
                dc.w $9500 ! ((grp_106FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_106FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_106FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $747D
                dc.w $9500 ! ((grp_15F340 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6860
                dc.w $9500 ! ((grp_176A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_176A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $905A
                dc.w $9500 ! ((grp_197EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B75
                dc.w $9500 ! ((grp_D1C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8588
                dc.w $9500 ! ((grp_D1C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7183
                dc.w $9500 ! ((grp_B8DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $784D
                dc.w $9500 ! ((grp_EAE20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE20 / 2) >> 16)
                dc.w 1
