byte_2D64FA:    dc.b   0, $A,$6F,$5C,$8E,$8F,$7F,$71,$80,$60
                                        ; DATA XREF: ROM:off_123C   o
                dc.w sprite_32_32
                dc.w $7263
                dc.w $9500 ! ((grp_1EE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1EE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1EE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $6261
                dc.w $9500 ! ((grp_176740 / 2) & $00FF)
                dc.w $9600 ! (((grp_176740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8A53
                dc.w $9500 ! ((grp_80200 / 2) & $00FF)
                dc.w $9600 ! (((grp_80200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80200 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7283
                dc.w $9500 ! ((grp_99F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_99F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $725B
                dc.w $9500 ! ((grp_1888C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1888C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1888C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $708B
                dc.w $9500 ! ((grp_D1B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7753
                dc.w $9500 ! ((grp_D1B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858B
                dc.w $9500 ! ((grp_D1BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9263
                dc.w $9500 ! ((grp_D1C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $926B
                dc.w $9500 ! ((grp_EADE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EADE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EADE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A5B
                dc.w $9500 ! ((grp_EAE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE00 / 2) >> 16)
                dc.w 1
