byte_2CEEE6:    dc.b   0, $B,$69,$63,$97,$95,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_B34   o
                dc.w sprite_32_24
                dc.w $7280
                dc.w $9500 ! ((grp_11FBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7260
                dc.w $9500 ! ((grp_120040 / 2) & $00FF)
                dc.w $9600 ! (((grp_120040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_120040 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6280
                dc.w $9500 ! ((grp_74780 / 2) & $00FF)
                dc.w $9600 ! (((grp_74780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9268
                dc.w $9500 ! ((grp_74900 / 2) & $00FF)
                dc.w $9600 ! (((grp_74900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9281
                dc.w $9500 ! ((grp_74800 / 2) & $00FF)
                dc.w $9600 ! (((grp_74800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A58
                dc.w $9500 ! ((grp_97100 / 2) & $00FF)
                dc.w $9600 ! (((grp_97100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97100 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7A78
                dc.w $9500 ! ((grp_183B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_183B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6A60
                dc.w $9500 ! ((grp_192820 / 2) & $00FF)
                dc.w $9600 ! (((grp_192820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192820 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6278
                dc.w $9500 ! ((grp_C8400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6268
                dc.w $9500 ! ((grp_B13C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B13C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B13C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7278
                dc.w $9500 ! ((grp_E29E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E29E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E29E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E98
                dc.w $9500 ! ((grp_E2960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2960 / 2) >> 16)
                dc.w 1
