byte_2E8530:    dc.b   0,  4,$6F,$6F,$8E,$8F,$90,$6F,$66,$7A
                                        ; DATA XREF: ROM:off_1D70   o
                dc.w sprite_32_32
                dc.w $6E70
                dc.w $9500 ! ((grp_1BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1BC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $5E75
                dc.w $9500 ! ((grp_7BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7BF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5867
                dc.w $9500 ! ((grp_1964E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1964E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1964E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B68
                dc.w $9500 ! ((grp_CE300 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E88
                dc.w $9500 ! ((grp_E8740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8740 / 2) >> 16)
                dc.w 1
