byte_2CE9E4:    dc.b   0,  7,$7E,  2,$8F,$AB,$86,$56,$87,$56
                                        ; DATA XREF: ROM:off_B00   o
                dc.w sprite_24_32
                dc.w $7B8E
                dc.w $9500 ! ((grp_FA840 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA840 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $834E
                dc.w $9500 ! ((grp_A2900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $856E
                dc.w $9500 ! ((grp_A2980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C1B
                dc.w $9500 ! ((grp_A2A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8436
                dc.w $9500 ! ((grp_192520 / 2) & $00FF)
                dc.w $9600 ! (((grp_192520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8C03
                dc.w $9500 ! ((grp_192580 / 2) & $00FF)
                dc.w $9600 ! (((grp_192580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192580 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7B7E
                dc.w $9500 ! ((grp_B1180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8400
                dc.w $9500 ! ((grp_E2700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2700 / 2) >> 16)
                dc.w 1
