byte_2D3C64:    dc.b   0,  5,$6C,$69,$8C,$85,$7D,$72,$7E,$72
                                        ; DATA XREF: ROM:off_1070   o
                dc.w sprite_32_24
                dc.w $696A
                dc.w $9500 ! ((grp_122740 / 2) & $00FF)
                dc.w $9600 ! (((grp_122740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122740 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $875D
                dc.w $9500 ! ((grp_A4A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7982
                dc.w $9500 ! ((grp_CA280 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D82
                dc.w $9500 ! ((grp_E49C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E49C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E49C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F62
                dc.w $9500 ! ((grp_E49E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E49E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E49E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F73
                dc.w $9500 ! ((grp_E4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4A00 / 2) >> 16)
                dc.w 1
