byte_2F903E:    dc.b   0,  2,$75,$84,$8C,$8E,$80,$A0,$81,$A0
                                        ; DATA XREF: ROM:off_2CFC   o
                dc.w sprite_32_24
                dc.w $7189
                dc.w $9500 ! ((grp_139840 / 2) & $00FF)
                dc.w $9600 ! (((grp_139840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $79A1
                dc.w $9500 ! ((grp_6F800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6F800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6F800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $7A81
                dc.w $9500 ! ((grp_18FCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FCA0 / 2) >> 16)
                dc.w 3
