byte_2DF570:    dc.b   0,  5,$73,$5F,$8B,$8B,$80,$74,$87,$68
                                        ; DATA XREF: ROM:off_1810   o
                dc.w sprite_32_24
                dc.w $706E
                dc.w $9500 ! ((grp_125A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_125A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6C83
                dc.w $9500 ! ((grp_7AC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7C60
                dc.w $9500 ! ((grp_7AD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C86
                dc.w $9500 ! ((grp_CD3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $906F
                dc.w $9500 ! ((grp_B52C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B52C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B52C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C58
                dc.w $9500 ! ((grp_E7A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A00 / 2) >> 16)
                dc.w 1
