byte_2FEDB0:    dc.b   0,  1,$77,$73,$86,$86,$7E,$7C,$7F,$7C
                                        ; DATA XREF: ROM:off_34E8   o
                dc.w sprite_16_16
                dc.w $7979
                dc.w $9500 ! ((grp_96A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_96A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7571
                dc.w $9500 ! ((grp_F9760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9760 / 2) >> 16)
                dc.w 1
