byte_2ED5C6:    dc.b   0,  2,$76,$63,$89,$93,$7F,$79,$80,$79
                                        ; DATA XREF: ROM:off_22AC   o
                dc.w sprite_24_24
                dc.w $7469
                dc.w $9500 ! ((grp_14C2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C2C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7981
                dc.w $9500 ! ((grp_89180 / 2) & $00FF)
                dc.w $9600 ! (((grp_89180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7561
                dc.w $9500 ! ((grp_D8B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8B40 / 2) >> 16)
                dc.w 2
