byte_2F8D54:    dc.b   0,  4,$6F,$71,$90,$85,$7F,$6C,$80,$6C
                                        ; DATA XREF: ROM:off_2CD0   o
                dc.w sprite_32_24
                dc.w $6E68
                dc.w $9500 ! ((grp_138DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_138DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_138DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7160
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $666F
                dc.w $9500 ! ((grp_C3B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E6E
                dc.w $9500 ! ((grp_C3B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7558
                dc.w $9500 ! ((grp_F63E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F63E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F63E0 / 2) >> 16)
                dc.w 1
