byte_2DB3A8:    dc.b   0,  9,$62,$5C,$9D,$8F,$7F,$75,$80,$75
                                        ; DATA XREF: ROM:off_1548   o
                dc.w sprite_32_24
                dc.w $685C
                dc.w $9500 ! ((grp_12D840 / 2) & $00FF)
                dc.w $9600 ! (((grp_12D840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12D840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $885A
                dc.w $9500 ! ((grp_18A6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A6C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8174
                dc.w $9500 ! ((grp_19A020 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A020 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C88
                dc.w $9500 ! ((grp_D5800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $818C
                dc.w $9500 ! ((grp_D5840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6061
                dc.w $9500 ! ((grp_BBDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7974
                dc.w $9500 ! ((grp_BBE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7174
                dc.w $9500 ! ((grp_EDAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDAA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7480
                dc.w $9500 ! ((grp_EDAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDAC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8862
                dc.w $9500 ! ((grp_EDAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDAE0 / 2) >> 16)
                dc.w 1
