byte_2DCA6C:    dc.b   0,  7,$6F,$53,$8E,$8F,$80,$6E,$7F,$52
                                        ; DATA XREF: ROM:off_1658   o
                dc.w sprite_16_32
                dc.w $714E
                dc.w $9500 ! ((grp_65B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $726E
                dc.w $9500 ! ((grp_84D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8150
                dc.w $9500 ! ((grp_A8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8270
                dc.w $9500 ! ((grp_A8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A5C
                dc.w $9500 ! ((grp_199CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199CC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8955
                dc.w $9500 ! ((grp_199D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_199D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D57
                dc.w $9500 ! ((grp_199D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_199D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199D80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $757E
                dc.w $9500 ! ((grp_BBA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBA80 / 2) >> 16)
                dc.w 2
