byte_2DCDA6:    dc.b   0, $A,$6F,$51,$8E,$8F,$7C,$6B,$81,$56
                                        ; DATA XREF: ROM:off_1674   o
                dc.w sprite_16_24
                dc.w $8367
                dc.w $9500 ! ((grp_179140 / 2) & $00FF)
                dc.w $9600 ! (((grp_179140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179140 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6B44
                dc.w $9500 ! ((grp_A8580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7354
                dc.w $9500 ! ((grp_A8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7B5C
                dc.w $9500 ! ((grp_A8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8247
                dc.w $9500 ! ((grp_A8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $777C
                dc.w $9500 ! ((grp_199F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_199F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199F00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7A44
                dc.w $9500 ! ((grp_199F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_199F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8A47
                dc.w $9500 ! ((grp_199FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6344
                dc.w $9500 ! ((grp_BBB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F82
                dc.w $9500 ! ((grp_BBBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9244
                dc.w $9500 ! ((grp_BBC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBC00 / 2) >> 16)
                dc.w 2
