byte_2D847A:    dc.b   0,  6,$75,$60,$8D,$77,$80,$6C,$83,$63
                                        ; DATA XREF: ROM:off_138C   o
                dc.w sprite_24_32
                dc.w $7259
                dc.w $9500 ! ((grp_100840 / 2) & $00FF)
                dc.w $9600 ! (((grp_100840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7C79
                dc.w $9500 ! ((grp_15A9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A9C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6A5E
                dc.w $9500 ! ((grp_B4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A57
                dc.w $9500 ! ((grp_B4440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7479
                dc.w $9500 ! ((grp_E6C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7851
                dc.w $9500 ! ((grp_E6C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9056
                dc.w $9500 ! ((grp_E6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6C80 / 2) >> 16)
                dc.w 1
