byte_2DFDBE:    dc.b   0,  5,$68,$59,$94,$8E,$7E,$73,$88,$62
                                        ; DATA XREF: ROM:off_186C   o
                dc.w sprite_32_32
                dc.w $7071
                dc.w $9500 ! ((grp_1FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1FA00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7859
                dc.w $9500 ! ((grp_12A840 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A840 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $6871
                dc.w $9500 ! ((grp_A6D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7A51
                dc.w $9500 ! ((grp_D29C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D29C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D29C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7061
                dc.w $9500 ! ((grp_B9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $607F
                dc.w $9500 ! ((grp_EB7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB7C0 / 2) >> 16)
                dc.w 1
