byte_2D56D4:    dc.b   0,  7,$6F,$5C,$8E,$8F,$73,$6F,$6E,$67
                                        ; DATA XREF: ROM:off_11A8   o
                dc.w sprite_16_32
                dc.w $7261
                dc.w $9500 ! ((grp_62300 / 2) & $00FF)
                dc.w $9600 ! (((grp_62300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6F51
                dc.w $9500 ! ((grp_7DD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A5E
                dc.w $9500 ! ((grp_A5E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7481
                dc.w $9500 ! ((grp_1877E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1877E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1877E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_D0000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8889
                dc.w $9500 ! ((grp_D0040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6265
                dc.w $9500 ! ((grp_B7340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8279
                dc.w $9500 ! ((grp_E9940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9940 / 2) >> 16)
                dc.w 1
