byte_2EFC4E:    dc.b   0,  1,$77,$7E,$8C,$8D,$81,$85,$82,$85
                                        ; DATA XREF: ROM:off_257C   o
                dc.w sprite_24_16
                dc.w $757C
                dc.w $9500 ! ((grp_165C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_165C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $758C
                dc.w $9500 ! ((grp_DA0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA0C0 / 2) >> 16)
                dc.w 2
