byte_2CD2B8:    dc.b   0,  7,$6C,$6F,$94,$91,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_898   o
                dc.w sprite_8_24
                dc.w $907D
                dc.w $9500 ! ((grp_191FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_191FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191FE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_E22A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E22A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E22A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B73
                dc.w $9500 ! ((grp_E22C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E22C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E22C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7889
                dc.w $9500 ! ((grp_E2360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B6D
                dc.w $9500 ! ((grp_E22E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E22E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E22E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8372
                dc.w $9500 ! ((grp_E2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B6D
                dc.w $9500 ! ((grp_E2320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9375
                dc.w $9500 ! ((grp_E2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2340 / 2) >> 16)
                dc.w 1
