byte_2F0C26:    dc.b   0,$11,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_260C   o
                dc.w sprite_32_32
                dc.w $6553
                dc.w $9500 ! ((grp_35800 / 2) & $00FF)
                dc.w $9600 ! (((grp_35800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $6573
                dc.w $9500 ! ((grp_133FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_133FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_133FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $5D8B
                dc.w $9500 ! ((grp_1663C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1663C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1663C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8D8B
                dc.w $9500 ! ((grp_166300 / 2) & $00FF)
                dc.w $9600 ! (((grp_166300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8563
                dc.w $9500 ! ((grp_17C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8D4B
                dc.w $9500 ! ((grp_17C8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9573
                dc.w $9500 ! ((grp_17C980 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C980 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $955B
                dc.w $9500 ! ((grp_17C740 / 2) & $00FF)
                dc.w $9600 ! (((grp_17C740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17C740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $857B
                dc.w $9500 ! ((grp_8BA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6D4B
                dc.w $9500 ! ((grp_9E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5D5B
                dc.w $9500 ! ((grp_ABF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8553
                dc.w $9500 ! ((grp_BFE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D83
                dc.w $9500 ! ((grp_F1740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5D7B
                dc.w $9500 ! ((grp_F1760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1760 / 2) >> 16)
                dc.w 1
