byte_2E1EEA:    dc.b   0,  3,$73,$5D,$8E,$8C,$80,$74,$82,$64
                                        ; DATA XREF: ROM:off_19C4   o
                dc.w sprite_24_24
                dc.w $7167
                dc.w $9500 ! ((grp_143500 / 2) & $00FF)
                dc.w $9600 ! (((grp_143500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143500 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $717F
                dc.w $9500 ! ((grp_4A500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7957
                dc.w $9500 ! ((grp_7B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8963
                dc.w $9500 ! ((grp_195C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_195C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195C40 / 2) >> 16)
                dc.w 3
