byte_2E7ADC:    dc.b   0, $B,$6C,$68,$8B,$87,$81,$66,$6B,$5A
                                        ; DATA XREF: ROM:off_1D18   o
                dc.w sprite_24_24
                dc.w $686C
                dc.w $9500 ! ((grp_1455A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1455A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1455A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7F7A
                dc.w $9500 ! ((grp_7F500 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F500 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5F64
                dc.w $9500 ! ((grp_99C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_99C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5F5C
                dc.w $9500 ! ((grp_D0D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6754
                dc.w $9500 ! ((grp_D0DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7754
                dc.w $9500 ! ((grp_D0E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8766
                dc.w $9500 ! ((grp_D0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8F6C
                dc.w $9500 ! ((grp_D0E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F64
                dc.w $9500 ! ((grp_B8340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6984
                dc.w $9500 ! ((grp_EA480 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $724C
                dc.w $9500 ! ((grp_EA4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA4A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C5C
                dc.w $9500 ! ((grp_EA4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA4C0 / 2) >> 16)
                dc.w 1
