byte_2E169A:    dc.b   0,  9,$71,$58,$93,$8F,$86,$6F,$87,$6F
                                        ; DATA XREF: ROM:off_1954   o
                dc.w sprite_16_24
                dc.w $7E5B
                dc.w $9500 ! ((grp_179A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_179A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7771
                dc.w $9500 ! ((grp_85F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7651
                dc.w $9500 ! ((grp_A9000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6E4F
                dc.w $9500 ! ((grp_19A560 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A560 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7881
                dc.w $9500 ! ((grp_D6340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E5E
                dc.w $9500 ! ((grp_BC7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9659
                dc.w $9500 ! ((grp_BC800 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E53
                dc.w $9500 ! ((grp_EE1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE1E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E5A
                dc.w $9500 ! ((grp_EE200 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE200 / 2) >> 16)
                dc.w 1
