byte_2FC6C6:    dc.b   0,  8,$41,$5A,$B8,$AF,$7C,$93,$7D,$93
                                        ; DATA XREF: ROM:off_312C   o
                dc.w sprite_24_16
                dc.w $A679
                dc.w $9500 ! ((grp_16C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $46A0
                dc.w $9500 ! ((grp_93500 / 2) & $00FF)
                dc.w $9600 ! (((grp_93500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $5699
                dc.w $9500 ! ((grp_93580 / 2) & $00FF)
                dc.w $9600 ! (((grp_93580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6E90
                dc.w $9500 ! ((grp_93600 / 2) & $00FF)
                dc.w $9600 ! (((grp_93600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7E89
                dc.w $9500 ! ((grp_93680 / 2) & $00FF)
                dc.w $9600 ! (((grp_93680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9680
                dc.w $9500 ! ((grp_93700 / 2) & $00FF)
                dc.w $9600 ! (((grp_93700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_93700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6696
                dc.w $9500 ! ((grp_C53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C53C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E86
                dc.w $9500 ! ((grp_C5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $3EA6
                dc.w $9500 ! ((grp_F7F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7F60 / 2) >> 16)
                dc.w 1
