byte_2DDCAA:    dc.b   0,  4,$77,$66,$8F,$90,$83,$7B,$7F,$6D
                                        ; DATA XREF: ROM:off_1714   o
                dc.w sprite_24_24
                dc.w $7679
                dc.w $9500 ! ((grp_145C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_145C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145C60 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7861
                dc.w $9500 ! ((grp_145D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_145D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145D80 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $7062
                dc.w $9500 ! ((grp_B9000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E91
                dc.w $9500 ! ((grp_EB1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB1A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E79
                dc.w $9500 ! ((grp_EB1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB1C0 / 2) >> 16)
                dc.w 1
