byte_2DECCE:    dc.b   0,  6,$6F,$60,$8E,$8F,$82,$70,$83,$67
                                        ; DATA XREF: ROM:off_17B4   o
                dc.w sprite_24_32
                dc.w $7368
                dc.w $9500 ! ((grp_1084C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1084C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1084C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7460
                dc.w $9500 ! ((grp_188DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_188DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B68
                dc.w $9500 ! ((grp_1983A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1983A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1983A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8B66
                dc.w $9500 ! ((grp_198400 / 2) & $00FF)
                dc.w $9600 ! (((grp_198400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198400 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D88
                dc.w $9500 ! ((grp_D2780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8488
                dc.w $9500 ! ((grp_EB4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB4A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
