byte_2F9D38:    dc.b   0,$10,$7C,$5C,$8F,$8E,$7E,$70,$7F,$70
                                        ; DATA XREF: ROM:off_2DD8   o
                dc.w sprite_24_32
                dc.w $6B67
                dc.w $9500 ! ((grp_11A7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A7C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8367
                dc.w $9500 ! ((grp_6FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $615F
                dc.w $9500 ! ((grp_A0480 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0480 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6157
                dc.w $9500 ! ((grp_190480 / 2) & $00FF)
                dc.w $9600 ! (((grp_190480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190480 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6B87
                dc.w $9500 ! ((grp_1901E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1901E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1901E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $738F
                dc.w $9500 ! ((grp_190240 / 2) & $00FF)
                dc.w $9600 ! (((grp_190240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190240 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $815F
                dc.w $9500 ! ((grp_1902A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1902A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1902A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C4F
                dc.w $9500 ! ((grp_DE7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE7C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8257
                dc.w $9500 ! ((grp_DE800 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8387
                dc.w $9500 ! ((grp_DE840 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $636C
                dc.w $9500 ! ((grp_C44C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C44C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C44C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9369
                dc.w $9500 ! ((grp_C4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B74
                dc.w $9500 ! ((grp_F6D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $614F
                dc.w $9500 ! ((grp_F6EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $795E
                dc.w $9500 ! ((grp_F6EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A57
                dc.w $9500 ! ((grp_F6F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $995F
                dc.w $9500 ! ((grp_F6D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6D80 / 2) >> 16)
                dc.w 1
