byte_2EBC5C:    dc.b   0,  8,$84,$5B,$A1,$80,$80,$7C,$81,$7C
                                        ; DATA XREF: ROM:off_2070   o
                dc.w sprite_32_32
                dc.w $5468
                dc.w $9500 ! ((grp_2D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_2D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2D000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7469
                dc.w $9500 ! ((grp_2D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_2D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2D200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $9469
                dc.w $9500 ! ((grp_110A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_110A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $AC70
                dc.w $9500 ! ((grp_87A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_87A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5488
                dc.w $9500 ! ((grp_9CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7489
                dc.w $9500 ! ((grp_9CE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9489
                dc.w $9500 ! ((grp_18C100 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C100 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $4C70
                dc.w $9500 ! ((grp_19BD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BD60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $AC80
                dc.w $9500 ! ((grp_EF740 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF740 / 2) >> 16)
                dc.w 1
