byte_2E0542:    dc.b   0,  7,$4C,$4D,$92,$86,$6F,$69,$82,$55
                                        ; DATA XREF: ROM:off_18C4   o
                dc.w sprite_32_32
                dc.w $6153
                dc.w $9500 ! ((grp_22000 / 2) & $00FF)
                dc.w $9600 ! (((grp_22000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7D6A
                dc.w $9500 ! ((grp_1090C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1090C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1090C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6573
                dc.w $9500 ! ((grp_146680 / 2) & $00FF)
                dc.w $9600 ! (((grp_146680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146680 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $4963
                dc.w $9500 ! ((grp_81580 / 2) & $00FF)
                dc.w $9600 ! (((grp_81580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $814B
                dc.w $9500 ! ((grp_81600 / 2) & $00FF)
                dc.w $9600 ! (((grp_81600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $815B
                dc.w $9500 ! ((grp_B98C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B98C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B98C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5962
                dc.w $9500 ! ((grp_EBB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBB40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $794B
                dc.w $9500 ! ((grp_EBB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBB60 / 2) >> 16)
                dc.w 1
