byte_2E0DAE:    dc.b   0, $E,$72,$5A,$8E,$8E,$77,$42,$74,$2B
                                        ; DATA XREF: ROM:off_1914   o
                dc.w sprite_16_32
                dc.w $8739
                dc.w $9500 ! ((grp_60B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_60B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5F39
                dc.w $9500 ! ((grp_15BA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BA40 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8729
                dc.w $9500 ! ((grp_15BB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BB00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6F53
                dc.w $9500 ! ((grp_7B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7F21
                dc.w $9500 ! ((grp_A5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5180 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5F31
                dc.w $9500 ! ((grp_186040 / 2) & $00FF)
                dc.w $9600 ! (((grp_186040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186040 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5737
                dc.w $9500 ! ((grp_195A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_195A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7721
                dc.w $9500 ! ((grp_195B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_195B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7F41
                dc.w $9500 ! ((grp_1959A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1959A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1959A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9746
                dc.w $9500 ! ((grp_195880 / 2) & $00FF)
                dc.w $9600 ! (((grp_195880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195880 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6029
                dc.w $9500 ! ((grp_CD640 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8F21
                dc.w $9500 ! ((grp_CD400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4F3B
                dc.w $9500 ! ((grp_B5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6751
                dc.w $9500 ! ((grp_B5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7743
                dc.w $9500 ! ((grp_B5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5400 / 2) >> 16)
                dc.w 2
