byte_2EA0CE:    dc.b   0,  2,$6E,$73,$90,$8E,$7F,$80,$80,$80
                                        ; DATA XREF: ROM:off_1F04   o
                dc.w sprite_24_32
                dc.w $7471
                dc.w $9500 ! ((grp_10F0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10F0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10F0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $8C79
                dc.w $9500 ! ((grp_19B1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B1C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6C81
                dc.w $9500 ! ((grp_BDB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BDB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BDB00 / 2) >> 16)
                dc.w 2
