byte_2DEE00:    dc.b   0,  9,$70,$64,$91,$8E,$7F,$72,$6B,$76
                                        ; DATA XREF: ROM:off_17C0   o
                dc.w sprite_32_32
                dc.w $6F74
                dc.w $9500 ! ((grp_26200 / 2) & $00FF)
                dc.w $9600 ! (((grp_26200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6F6C
                dc.w $9500 ! ((grp_9B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $676C
                dc.w $9500 ! ((grp_A8A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8F74
                dc.w $9500 ! ((grp_A8A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F54
                dc.w $9500 ! ((grp_18ABA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18ABA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18ABA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8F5C
                dc.w $9500 ! ((grp_19A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9770
                dc.w $9500 ! ((grp_19A260 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A260 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6C5C
                dc.w $9500 ! ((grp_BC4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8754
                dc.w $9500 ! ((grp_BC500 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F73
                dc.w $9500 ! ((grp_EDF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDF80 / 2) >> 16)
                dc.w 1
