byte_2D24A4:    dc.b   0,  5,$75,$8F,$8B,$B4,$89,$A0,$8A,$A0
                                        ; DATA XREF: ROM:off_ED0   o
                dc.w sprite_16_24
                dc.w $7993
                dc.w $9500 ! ((grp_171640 / 2) & $00FF)
                dc.w $9600 ! (((grp_171640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171640 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6FB0
                dc.w $9500 ! ((grp_E4280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $75AB
                dc.w $9500 ! ((grp_E4260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B8B
                dc.w $9500 ! ((grp_E42A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E42A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E42A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $85AB
                dc.w $9500 ! ((grp_E42C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E42C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E42C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8CB3
                dc.w $9500 ! ((grp_E42E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E42E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E42E0 / 2) >> 16)
                dc.w 1
