byte_2CF7BA:    dc.b   0,  1,$78,$75,$87,$8E,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_B8C   o
                dc.w sprite_16_32
                dc.w $7673
                dc.w $9500 ! ((grp_5C900 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C900 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $867C
                dc.w $9500 ! ((grp_E2D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2D80 / 2) >> 16)
                dc.w 1
