byte_2FD464:    dc.b   0,  8,$67,$45,$87,$8D,$77,$69,$78,$69
                                        ; DATA XREF: ROM:off_32E8   o
                dc.w sprite_16_24
                dc.w $7A70
                dc.w $9500 ! ((grp_181CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_181CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6B43
                dc.w $9500 ! ((grp_A0C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6548
                dc.w $9500 ! ((grp_1A04A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A04A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A04A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6860
                dc.w $9500 ! ((grp_DFC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E68
                dc.w $9500 ! ((grp_DFC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C4B
                dc.w $9500 ! ((grp_DFC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DFC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DFC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7270
                dc.w $9500 ! ((grp_C5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D58
                dc.w $9500 ! ((grp_F8380 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8380 / 2) >> 16)
                dc.w 1
