byte_2E663E:    dc.b   0,  7,$6F,$61,$8A,$8E,$7E,$76,$77,$62
                                        ; DATA XREF: ROM:off_1C54   o
                dc.w sprite_24_24
                dc.w $7264
                dc.w $9500 ! ((grp_1471C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1471C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1471C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $767C
                dc.w $9500 ! ((grp_83400 / 2) & $00FF)
                dc.w $9600 ! (((grp_83400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8A6A
                dc.w $9500 ! ((grp_83480 / 2) & $00FF)
                dc.w $9600 ! (((grp_83480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83480 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7289
                dc.w $9500 ! ((grp_9AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A6B
                dc.w $9500 ! ((grp_1991E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1991E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1991E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B5C
                dc.w $9500 ! ((grp_D3D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $627B
                dc.w $9500 ! ((grp_EC900 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC900 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $867C
                dc.w $9500 ! ((grp_EC920 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC920 / 2) >> 16)
                dc.w 1
