byte_2D8168:    dc.b   0,  5,$71,$60,$85,$7C,$86,$60,$7F,$60
                                        ; DATA XREF: ROM:off_1368   o
                dc.w sprite_24_32
                dc.w $6F57
                dc.w $9500 ! ((grp_1003C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1003C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1003C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7577
                dc.w $9500 ! ((grp_173380 / 2) & $00FF)
                dc.w $9600 ! (((grp_173380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173380 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8573
                dc.w $9500 ! ((grp_CC700 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6760
                dc.w $9500 ! ((grp_B4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $875F
                dc.w $9500 ! ((grp_B4240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D8F
                dc.w $9500 ! ((grp_E6A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6A60 / 2) >> 16)
                dc.w 1
