byte_2FF326:    dc.b   0,  2,$98,$70,$F2,$90,$C3,$7D,$C4,$7D
                                        ; DATA XREF: ROM:off_356C   o
                dc.w sprite_32_24
                dc.w $B273
                dc.w $9500 ! ((grp_13BC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_13BC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13BC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $D272
                dc.w $9500 ! ((grp_13BAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13BAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13BAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $9675
                dc.w $9500 ! ((grp_5A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A800 / 2) >> 16)
                dc.w 8
