byte_2CEE58:    dc.b   0, $A,$69,$6B,$93,$96,$80,$7A,$81,$7A
                                        ; DATA XREF: ROM:off_B30   o
                dc.w sprite_32_24
                dc.w $7282
                dc.w $9500 ! ((grp_11FBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7262
                dc.w $9500 ! ((grp_11FD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11FD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11FD40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6282
                dc.w $9500 ! ((grp_74780 / 2) & $00FF)
                dc.w $9600 ! (((grp_74780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74780 / 2) >> 16)
word_2CEE84:    dc.w 4                  ; DATA XREF: ROM:001AD390   o
                dc.w sprite_16_16
                dc.w $926A
                dc.w $9500 ! ((grp_74880 / 2) & $00FF)
                dc.w $9600 ! (((grp_74880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9283
                dc.w $9500 ! ((grp_74800 / 2) & $00FF)
                dc.w $9600 ! (((grp_74800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A5A
                dc.w $9500 ! ((grp_97180 / 2) & $00FF)
                dc.w $9600 ! (((grp_97180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6A62
                dc.w $9500 ! ((grp_A3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7A7A
                dc.w $9500 ! ((grp_183B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_183B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183B80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $627A
                dc.w $9500 ! ((grp_E29A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E29A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E29A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $727A
                dc.w $9500 ! ((grp_E29C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E29C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E29C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E9A
                dc.w $9500 ! ((grp_E2960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2960 / 2) >> 16)
                dc.w 1
