byte_2D23EA:    dc.b   0,  4,$72,$A8,$8E,$B8,$88,$B1,$89,$B1
                                        ; DATA XREF: ROM:off_EC4   o
                dc.w sprite_32_8
                dc.w $6AA8
                dc.w $9500 ! ((grp_97B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8AA8
                dc.w $9500 ! ((grp_193540 / 2) & $00FF)
                dc.w $9600 ! (((grp_193540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193540 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $66AD
                dc.w $9500 ! ((grp_B2640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6EB0
                dc.w $9500 ! ((grp_B2600 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $92AD
                dc.w $9500 ! ((grp_B2680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2680 / 2) >> 16)
                dc.w 2
