byte_2F0E60:    dc.b   0,  9,$64,$5B,$B5,$7A,$8D,$6E,$8E,$6E
                                        ; DATA XREF: ROM:off_2618   o
                dc.w sprite_32_32
                dc.w $8357
                dc.w $9500 ! ((grp_37200 / 2) & $00FF)
                dc.w $9600 ! (((grp_37200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7357
                dc.w $9500 ! ((grp_6BD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5B5C
                dc.w $9500 ! ((grp_17D280 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D280 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $A35E
                dc.w $9500 ! ((grp_17D340 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $B35A
                dc.w $9500 ! ((grp_17D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D400 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $8377
                dc.w $9500 ! ((grp_9EB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6B77
                dc.w $9500 ! ((grp_18DF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DF60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6B5F
                dc.w $9500 ! ((grp_19D6E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D6E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D6E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $797F
                dc.w $9500 ! ((grp_F22E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F22E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F22E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937F
                dc.w $9500 ! ((grp_F2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2300 / 2) >> 16)
                dc.w 1
