byte_2E85E0:    dc.b   0, $A,$6F,$66,$8E,$8F,$BB,$44,$AA,$4D
                                        ; DATA XREF: ROM:off_1D78   o
                dc.w sprite_32_16
                dc.w $7068
                dc.w $9500 ! ((grp_4AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7278
                dc.w $9500 ! ((grp_15C940 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9E4F
                dc.w $9500 ! ((grp_7C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $B23F
                dc.w $9500 ! ((grp_99000 / 2) & $00FF)
                dc.w $9600 ! (((grp_99000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8F5A
                dc.w $9500 ! ((grp_1965A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1965A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1965A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_CE4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F60
                dc.w $9500 ! ((grp_CE3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8388
                dc.w $9500 ! ((grp_CE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A847
                dc.w $9500 ! ((grp_CE400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $C237
                dc.w $9500 ! ((grp_CE440 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9756
                dc.w $9500 ! ((grp_B6140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6140 / 2) >> 16)
                dc.w 2
