byte_2D41B6:    dc.b   0,  9,$6D,$68,$90,$90,$7E,$7B,$7F,$7B
                                        ; DATA XREF: ROM:off_10AC   o
                dc.w sprite_24_16
                dc.w $776E
                dc.w $9500 ! ((grp_159700 / 2) & $00FF)
                dc.w $9600 ! (((grp_159700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7F7E
                dc.w $9500 ! ((grp_77800 / 2) & $00FF)
                dc.w $9600 ! (((grp_77800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $676E
                dc.w $9500 ! ((grp_CAA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7566
                dc.w $9500 ! ((grp_CAAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6979
                dc.w $9500 ! ((grp_B2E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7785
                dc.w $9500 ! ((grp_B2E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F75
                dc.w $9500 ! ((grp_B2E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6179
                dc.w $9500 ! ((grp_E5260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F83
                dc.w $9500 ! ((grp_E5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $858E
                dc.w $9500 ! ((grp_E52A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E52A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E52A0 / 2) >> 16)
                dc.w 1
