byte_2E10B0:    dc.b   0, $D,$72,$5A,$8E,$8E,$76,$3D,$74,$28
                                        ; DATA XREF: ROM:off_1928   o
                dc.w sprite_24_16
                dc.w $7136
                dc.w $9500 ! ((grp_15BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5037
                dc.w $9500 ! ((grp_7B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7F26
                dc.w $9500 ! ((grp_7AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8F23
                dc.w $9500 ! ((grp_7B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5F26
                dc.w $9500 ! ((grp_98A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5F2E
                dc.w $9500 ! ((grp_185EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $6555
                dc.w $9500 ! ((grp_185F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_185F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7746
                dc.w $9500 ! ((grp_185E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_185E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6138
                dc.w $9500 ! ((grp_CD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8E4C
                dc.w $9500 ! ((grp_CD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $754E
                dc.w $9500 ! ((grp_E7B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $772E
                dc.w $9500 ! ((grp_E7AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C1E
                dc.w $9500 ! ((grp_E7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9644
                dc.w $9500 ! ((grp_E7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B00 / 2) >> 16)
                dc.w 1
