byte_2D6990:    dc.b   0,  7,$74,$55,$92,$7A,$83,$4F,$8A,$59
                                        ; DATA XREF: ROM:off_1270   o
                dc.w sprite_24_32
                dc.w $7951
                dc.w $9500 ! ((grp_10D440 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6162
                dc.w $9500 ! ((grp_162B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_162B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $714A
                dc.w $9500 ! ((grp_19A680 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A680 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $694A
                dc.w $9500 ! ((grp_BC940 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9155
                dc.w $9500 ! ((grp_BC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9952
                dc.w $9500 ! ((grp_BC9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5966
                dc.w $9500 ! ((grp_EE320 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $804A
                dc.w $9500 ! ((grp_EE340 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE340 / 2) >> 16)
                dc.w 1
