byte_2EE0FC:    dc.b   0,  6,$69,$6D,$96,$94,$7D,$80,$7E,$80
                                        ; DATA XREF: ROM:off_2368   o
                dc.w sprite_32_32
                dc.w $746A
                dc.w $9500 ! ((grp_31200 / 2) & $00FF)
                dc.w $9600 ! (((grp_31200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_31200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $748A
                dc.w $9500 ! ((grp_9DD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6C6D
                dc.w $9500 ! ((grp_AB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9473
                dc.w $9500 ! ((grp_AB680 / 2) & $00FF)
                dc.w $9600 ! (((grp_AB680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AB680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6475
                dc.w $9500 ! ((grp_19CCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19CCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19CCC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7792
                dc.w $9500 ! ((grp_D9180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5C85
                dc.w $9500 ! ((grp_F0780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0780 / 2) >> 16)
                dc.w 1
