byte_2F3522:    dc.b   0,  6,$69,$5F,$96,$89,$7A,$78,$7B,$78
                                        ; DATA XREF: ROM:off_27B4   o
                dc.w sprite_32_32
                dc.w $735D
                dc.w $9500 ! ((grp_3A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_3A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3A000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $5B63
                dc.w $9500 ! ((grp_167A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_167A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7C85
                dc.w $9500 ! ((grp_8D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $737D
                dc.w $9500 ! ((grp_9F100 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $605B
                dc.w $9500 ! ((grp_F2FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2FA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B79
                dc.w $9500 ! ((grp_F2F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937C
                dc.w $9500 ! ((grp_F2F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2F60 / 2) >> 16)
                dc.w 1
