byte_2D09E0:    dc.b   0,  2,$6F,$7A,$92,$8E,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_DB0   o
                dc.w sprite_32_24
                dc.w $757A
                dc.w $9500 ! ((grp_121540 / 2) & $00FF)
                dc.w $9600 ! (((grp_121540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_121540 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $6D82
                dc.w $9500 ! ((grp_B1F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8672
                dc.w $9500 ! ((grp_E3BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3BA0 / 2) >> 16)
                dc.w 1
