byte_2EE8CC:    dc.b   0,  6,$6C,$69,$96,$92,$81,$7B,$82,$7B
                                        ; DATA XREF: ROM:off_23E8   o
                dc.w sprite_32_32
                dc.w $7061
                dc.w $9500 ! ((grp_32400 / 2) & $00FF)
                dc.w $9600 ! (((grp_32400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7081
                dc.w $9500 ! ((grp_52A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_52A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9074
                dc.w $9500 ! ((grp_17BE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BE40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6878
                dc.w $9500 ! ((grp_19D0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D0E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7791
                dc.w $9500 ! ((grp_D9400 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $607C
                dc.w $9500 ! ((grp_F0840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $908C
                dc.w $9500 ! ((grp_F0860 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0860 / 2) >> 16)
                dc.w 1
