byte_2DEF3E:    dc.b   0,  8,$6F,$55,$90,$8E,$80,$72,$6B,$7F
                                        ; DATA XREF: ROM:off_17CC   o
                dc.w sprite_24_32
                dc.w $6973
                dc.w $9500 ! ((grp_10D140 / 2) & $00FF)
                dc.w $9600 ! (((grp_10D140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10D140 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $695B
                dc.w $9500 ! ((grp_12E2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $906B
                dc.w $9500 ! ((grp_A8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E53
                dc.w $9500 ! ((grp_18ACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18ACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18ACC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $818B
                dc.w $9500 ! ((grp_18AD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AD20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8173
                dc.w $9500 ! ((grp_BC5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8962
                dc.w $9500 ! ((grp_BC600 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $987B
                dc.w $9500 ! ((grp_BC640 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $617B
                dc.w $9500 ! ((grp_EDFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDFE0 / 2) >> 16)
                dc.w 1
