byte_2D7AE4:    dc.b   0,  5,$75,$5D,$8B,$A2,$83,$81,$80,$6A
                                        ; DATA XREF: ROM:off_1320   o
                dc.w sprite_32_24
                dc.w $6C6E
                dc.w $9500 ! ((grp_1243C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1243C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1243C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7986
                dc.w $9500 ! ((grp_172C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_172C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8C6D
                dc.w $9500 ! ((grp_172CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_172CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7866
                dc.w $9500 ! ((grp_CC5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D5E
                dc.w $9500 ! ((grp_E6920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6920 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $809E
                dc.w $9500 ! ((grp_E67C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E67C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E67C0 / 2) >> 16)
                dc.w 1
