byte_2D4C1C:    dc.b   0,  3,$58,$77,$88,$89,$70,$80,$71,$80
                                        ; DATA XREF: ROM:off_1128   o
                dc.w sprite_32_16
                dc.w $5675
                dc.w $9500 ! ((grp_4D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7677
                dc.w $9500 ! ((grp_80680 / 2) & $00FF)
                dc.w $9600 ! (((grp_80680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5E85
                dc.w $9500 ! ((grp_188A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_188A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $867B
                dc.w $9500 ! ((grp_EB020 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB020 / 2) >> 16)
                dc.w 1
