byte_2E39F2:    dc.b   0,  6,$71,$66,$9E,$94,$87,$7D,$88,$7D
                                        ; DATA XREF: ROM:off_1AEC   o
                dc.w sprite_24_32
                dc.w $7F6B
                dc.w $9500 ! ((grp_10E640 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E640 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7F8B
                dc.w $9500 ! ((grp_D6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9263
                dc.w $9500 ! ((grp_D6C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F87
                dc.w $9500 ! ((grp_BD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7779
                dc.w $9500 ! ((grp_BD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7384
                dc.w $9500 ! ((grp_EEAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEAA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $976B
                dc.w $9500 ! ((grp_EEAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEAC0 / 2) >> 16)
                dc.w 1
