byte_2D463C:    dc.b   0,  6,$59,$62,$AB,$8C,$8E,$7D,$8F,$7D
                                        ; DATA XREF: ROM:off_10E8   o
                dc.w sprite_32_16
                dc.w $7F7C
                dc.w $9500 ! ((grp_49400 / 2) & $00FF)
                dc.w $9600 ! (((grp_49400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $6F78
                dc.w $9500 ! ((grp_CAE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $918C
                dc.w $9500 ! ((grp_CAEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9374
                dc.w $9500 ! ((grp_CAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F7C
                dc.w $9500 ! ((grp_B3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7480
                dc.w $9500 ! ((grp_E5820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8174
                dc.w $9500 ! ((grp_E5800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5800 / 2) >> 16)
                dc.w 1
