byte_2F906C:    dc.b   0,  3,$6D,$74,$8E,$92,$7D,$83,$7E,$83
                                        ; DATA XREF: ROM:off_2D00   o
                dc.w sprite_32_24
                dc.w $7179
                dc.w $9500 ! ((grp_1399C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1399C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1399C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $6F8E
                dc.w $9500 ! ((grp_DE300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7A71
                dc.w $9500 ! ((grp_DE340 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6985
                dc.w $9500 ! ((grp_F64E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F64E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F64E0 / 2) >> 16)
                dc.w 1
