byte_2F7590:    dc.b   0, $C,$65,$47,$8E,$83,$6F,$86,$70,$86
                                        ; DATA XREF: ROM:off_2B98   o
                dc.w sprite_32_32
                dc.w $684D
                dc.w $9500 ! ((grp_3EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3EC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $904D
                dc.w $9500 ! ((grp_1186C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1186C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1186C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $786D
                dc.w $9500 ! ((grp_1514E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1514E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1514E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_24
                dc.w $6055
                dc.w $9500 ! ((grp_19EF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EF40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $706D
                dc.w $9500 ! ((grp_19EFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EFA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9845
                dc.w $9500 ! ((grp_DD5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $885D
                dc.w $9500 ! ((grp_C2F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6845
                dc.w $9500 ! ((grp_F57A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F57A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F57A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $686D
                dc.w $9500 ! ((grp_F57C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F57C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F57C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A85
                dc.w $9500 ! ((grp_F5820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A45
                dc.w $9500 ! ((grp_F57E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F57E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F57E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8585
                dc.w $9500 ! ((grp_F5820 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906D
                dc.w $9500 ! ((grp_F5800 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5800 / 2) >> 16)
                dc.w 1
