byte_2F5B3E:    dc.b   0,  4,$74,$45,$8C,$85,$54,$85,$55,$85
                                        ; DATA XREF: ROM:off_2B14   o
                dc.w sprite_24_32
                dc.w $764B
                dc.w $9500 ! ((grp_116A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_116A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $776B
                dc.w $9500 ! ((grp_116BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_116BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_116BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6E4B
                dc.w $9500 ! ((grp_19EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EA00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7643
                dc.w $9500 ! ((grp_DCE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DCE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DCE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F75
                dc.w $9500 ! ((grp_C2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2280 / 2) >> 16)
                dc.w 2
