byte_2E8116:    dc.b   0,  6,$6F,$68,$8E,$8F,$62,$7C,$8D,$7C
                                        ; DATA XREF: ROM:off_1D4C   o
                dc.w sprite_32_24
                dc.w $7768
                dc.w $9500 ! ((grp_126640 / 2) & $00FF)
                dc.w $9600 ! (((grp_126640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $6F80
                dc.w $9500 ! ((grp_4AD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4AD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4AD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $5F7F
                dc.w $9500 ! ((grp_CDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7760
                dc.w $9500 ! ((grp_CDF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F6B
                dc.w $9500 ! ((grp_B5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F77
                dc.w $9500 ! ((grp_E85A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E85A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E85A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_E5A60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A60 / 2) >> 16)
                dc.w 1
