byte_2FCF82:    dc.b   0,  2,$69,$65,$9B,$6B,$82,$68,$83,$68
                                        ; DATA XREF: ROM:off_3274   o
                dc.w sprite_16_16
                dc.w $8F63
                dc.w $9500 ! ((grp_94B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_94B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_94B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6763
                dc.w $9500 ! ((grp_A0980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8763
                dc.w $9500 ! ((grp_F80C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F80C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F80C0 / 2) >> 16)
                dc.w 1
