byte_2CE17A:    dc.b   0,  1,$92,$7A,$A5,$8D,$9B,$83,$9C,$83
                                        ; DATA XREF: ROM:off_A04   o
                dc.w sprite_24_16
                dc.w $9081
                dc.w $9500 ! ((grp_156B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_156B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $9578
                dc.w $9500 ! ((grp_C7F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7F00 / 2) >> 16)
                dc.w 2
