byte_2E08EE:    dc.b   0,  6,$4F,$59,$8E,$7D,$6E,$6B,$82,$61
                                        ; DATA XREF: ROM:off_18EC   o
                dc.w sprite_24_32
                dc.w $5D60
                dc.w $9500 ! ((grp_1096C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1096C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1096C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $4D5E
                dc.w $9500 ! ((grp_64600 / 2) & $00FF)
                dc.w $9600 ! (((grp_64600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $5D58
                dc.w $9500 ! ((grp_9AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_1891C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1891C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1891C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7560
                dc.w $9500 ! ((grp_198BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198BE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7D55
                dc.w $9500 ! ((grp_EBC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBC80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B55
                dc.w $9500 ! ((grp_EBCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBCA0 / 2) >> 16)
                dc.w 1
