byte_2D8C40:    dc.b   0,  9,$74,$55,$92,$7A,$7F,$4E,$8F,$59
                                        ; DATA XREF: ROM:off_13D8   o
                dc.w sprite_16_32
                dc.w $705D
                dc.w $9500 ! ((grp_61600 / 2) & $00FF)
                dc.w $9600 ! (((grp_61600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61600 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $784D
                dc.w $9500 ! ((grp_15D540 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D540 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $805D
                dc.w $9500 ! ((grp_196960 / 2) & $00FF)
                dc.w $9600 ! (((grp_196960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $757D
                dc.w $9500 ! ((grp_CEB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CEB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CEB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6074
                dc.w $9500 ! ((grp_B6800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $704D
                dc.w $9500 ! ((grp_B6840 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $885D
                dc.w $9500 ! ((grp_B6880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9055
                dc.w $9500 ! ((grp_B68C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B68C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B68C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6873
                dc.w $9500 ! ((grp_E8CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $684F
                dc.w $9500 ! ((grp_E8CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8CE0 / 2) >> 16)
                dc.w 1
