byte_2DD1D6:    dc.b   0,  3,$76,$62,$8C,$7F,$7F,$6F,$7F,$62
                                        ; DATA XREF: ROM:off_169C   o
                dc.w sprite_32_32
                dc.w $6F55
                dc.w $9500 ! ((grp_1A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $787D
                dc.w $9500 ! ((grp_15B440 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B440 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7175
                dc.w $9500 ! ((grp_185B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_185B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185B60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6755
                dc.w $9500 ! ((grp_E74E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E74E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E74E0 / 2) >> 16)
                dc.w 1
