byte_2F13A4:    dc.b   0, $E,$65,$63,$A6,$9D,$86,$7C,$87,$7C
                                        ; DATA XREF: ROM:off_2640   o
                dc.w sprite_32_24
                dc.w $7982
                dc.w $9500 ! ((grp_135940 / 2) & $00FF)
                dc.w $9600 ! (((grp_135940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_135940 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $585A
                dc.w $9500 ! ((grp_54A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7969
                dc.w $9500 ! ((grp_54B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9962
                dc.w $9500 ! ((grp_6C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A8D
                dc.w $9500 ! ((grp_8C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9982
                dc.w $9500 ! ((grp_8C580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $616A
                dc.w $9500 ! ((grp_18E020 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E020 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7862
                dc.w $9500 ! ((grp_18E080 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E080 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $797A
                dc.w $9500 ! ((grp_18E0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E0E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $759A
                dc.w $9500 ! ((grp_DB400 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A86A
                dc.w $9500 ! ((grp_DB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $628F
                dc.w $9500 ! ((grp_C0780 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7172
                dc.w $9500 ! ((grp_F25E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F25E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F25E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A5A
                dc.w $9500 ! ((grp_F2600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2600 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A972
                dc.w $9500 ! ((grp_F2620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2620 / 2) >> 16)
                dc.w 1
