byte_2F978E:    dc.b   0,  4,$70,$70,$8E,$8D,$7F,$7E,$80,$7E
                                        ; DATA XREF: ROM:off_2D8C   o
                dc.w sprite_24_24
                dc.w $7776
                dc.w $9500 ! ((grp_1526E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1526E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1526E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7A6E
                dc.w $9500 ! ((grp_DE640 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F7A
                dc.w $9500 ! ((grp_C4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $848E
                dc.w $9500 ! ((grp_F69C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F69C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F69C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F83
                dc.w $9500 ! ((grp_F69E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F69E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F69E0 / 2) >> 16)
                dc.w 1
