byte_2D2318:    dc.b   0,  5,$72,$A5,$8E,$B4,$89,$AE,$8A,$AE
                                        ; DATA XREF: ROM:off_EB8   o
                dc.w sprite_16_16
                dc.w $6BAC
                dc.w $9500 ! ((grp_76B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6CA4
                dc.w $9500 ! ((grp_184540 / 2) & $00FF)
                dc.w $9600 ! (((grp_184540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $84A4
                dc.w $9500 ! ((grp_C9C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $86AC
                dc.w $9500 ! ((grp_C9D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8CB4
                dc.w $9500 ! ((grp_C9CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8BBC
                dc.w $9500 ! ((grp_E4200 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4200 / 2) >> 16)
                dc.w 1
