byte_2CD954:    dc.b   0,  1,$83,$86,$92,$8C,$84,$8E,$82,$9F
                                        ; DATA XREF: ROM:off_940   o
                dc.w sprite_24_8
                dc.w $8187
                dc.w $9500 ! ((grp_183220 / 2) & $00FF)
                dc.w $9600 ! (((grp_183220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8D7F
                dc.w $9500 ! ((grp_E1820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1820 / 2) >> 16)
                dc.w 1
