byte_2DFC18:    dc.b   0,  4,$56,$6A,$8C,$8D,$71,$7B,$66,$71
                                        ; DATA XREF: ROM:off_1858   o
                dc.w sprite_32_32
                dc.w $6268
                dc.w $9500 ! ((grp_1F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_1F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1F600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6A88
                dc.w $9500 ! ((grp_9A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9A600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5A70
                dc.w $9500 ! ((grp_1987C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1987C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1987C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $527C
                dc.w $9500 ! ((grp_EB720 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A88
                dc.w $9500 ! ((grp_EB740 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB740 / 2) >> 16)
                dc.w 1
