byte_2DC44E:    dc.b   0,  3,$76,$5A,$A2,$90,$8D,$63,$8E,$63
                                        ; DATA XREF: ROM:off_161C   o
                dc.w sprite_32_24
                dc.w $7C58
                dc.w $9500 ! ((grp_12F340 / 2) & $00FF)
                dc.w $9600 ! (((grp_12F340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12F340 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $9C58
                dc.w $9500 ! ((grp_19AD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AD40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $745A
                dc.w $9500 ! ((grp_BD3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BD3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BD3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A467
                dc.w $9500 ! ((grp_EE8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE8C0 / 2) >> 16)
                dc.w 1
