byte_2D40EE:    dc.b   0,  8,$69,$68,$8F,$90,$7A,$7B,$7B,$7B
                                        ; DATA XREF: ROM:off_10A4   o
                dc.w sprite_24_16
                dc.w $7475
                dc.w $9500 ! ((grp_159640 / 2) & $00FF)
                dc.w $9600 ! (((grp_159640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159640 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $686D
                dc.w $9500 ! ((grp_98000 / 2) & $00FF)
                dc.w $9600 ! (((grp_98000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7085
                dc.w $9500 ! ((grp_98080 / 2) & $00FF)
                dc.w $9600 ! (((grp_98080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7665
                dc.w $9500 ! ((grp_CAA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $687A
                dc.w $9500 ! ((grp_B2DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6178
                dc.w $9500 ! ((grp_E5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $768D
                dc.w $9500 ! ((grp_E51A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E51A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E51A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $858D
                dc.w $9500 ! ((grp_E51C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E51C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E51C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C7C
                dc.w $9500 ! ((grp_E51E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E51E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E51E0 / 2) >> 16)
                dc.w 1
