byte_2D0812:    dc.b   0,  1,$76,$75,$8E,$82,$80,$81,$29,$36
                                        ; DATA XREF: ROM:off_D8C   o
                dc.w sprite_32_16
                dc.w $7175
                dc.w $9500 ! ((grp_47000 / 2) & $00FF)
                dc.w $9600 ! (((grp_47000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47000 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $776D
                dc.w $9500 ! ((grp_E3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3580 / 2) >> 16)
                dc.w 1
