byte_2F8E3E:    dc.b   0,  5,$6F,$71,$90,$85,$81,$6B,$82,$6B
                                        ; DATA XREF: ROM:off_2CDC   o
                dc.w sprite_24_32
                dc.w $7A65
                dc.w $9500 ! ((grp_119EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_119EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $784D
                dc.w $9500 ! ((grp_90D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $726D
                dc.w $9500 ! ((grp_19F4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F4E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $785D
                dc.w $9500 ! ((grp_DE1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A6E
                dc.w $9500 ! ((grp_C3CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9174
                dc.w $9500 ! ((grp_C3D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3D00 / 2) >> 16)
                dc.w 2
