byte_2ECF72:    dc.b   0,  3,$6E,$72,$96,$96,$82,$84,$83,$84
                                        ; DATA XREF: ROM:off_224C   o
                dc.w sprite_32_32
                dc.w $7170
                dc.w $9500 ! ((grp_30400 / 2) & $00FF)
                dc.w $9600 ! (((grp_30400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $7190
                dc.w $9500 ! ((grp_9D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9174
                dc.w $9500 ! ((grp_AAD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $697C
                dc.w $9500 ! ((grp_19C120 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C120 / 2) >> 16)
                dc.w 3
