byte_2CC146:    dc.b   0,  1,$82,$82,$95,$93,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_6EC   o
                dc.w sprite_24_16
                dc.w $8086
                dc.w $9500 ! ((grp_155C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_155C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $857E
                dc.w $9500 ! ((grp_C6980 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6980 / 2) >> 16)
                dc.w 2
