byte_2F5A54:    dc.b   0,  5,$70,$54,$99,$8E,$84,$71,$85,$71
                                        ; DATA XREF: ROM:off_2B08   o
                dc.w sprite_32_32
                dc.w $7662
                dc.w $9500 ! ((grp_3C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3C800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6E52
                dc.w $9500 ! ((grp_168AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_168AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168AC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7682
                dc.w $9500 ! ((grp_168B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_168B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6E62
                dc.w $9500 ! ((grp_C2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $966B
                dc.w $9500 ! ((grp_C2040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E82
                dc.w $9500 ! ((grp_F4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4880 / 2) >> 16)
                dc.w 1
