byte_2E1920:    dc.b   0,  6,$77,$5D,$94,$8D,$81,$74,$80,$5E
                                        ; DATA XREF: ROM:off_1970   o
                dc.w sprite_32_32
                dc.w $765A
                dc.w $9500 ! ((grp_23600 / 2) & $00FF)
                dc.w $9600 ! (((grp_23600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_23600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $748A
                dc.w $9500 ! ((grp_1892E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1892E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1892E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6E6D
                dc.w $9500 ! ((grp_198D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_198D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198D60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7982
                dc.w $9500 ! ((grp_D2E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F7A
                dc.w $9500 ! ((grp_D2EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $965E
                dc.w $9500 ! ((grp_B9BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6679
                dc.w $9500 ! ((grp_EBE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBE60 / 2) >> 16)
                dc.w 1
