byte_2D982C:    dc.b   0,  8,$6E,$58,$8F,$8E,$7E,$73,$7D,$61
                                        ; DATA XREF: ROM:off_1448   o
                dc.w sprite_24_32
                dc.w $7470
                dc.w $9500 ! ((grp_103840 / 2) & $00FF)
                dc.w $9600 ! (((grp_103840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103840 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $748F
                dc.w $9500 ! ((grp_99200 / 2) & $00FF)
                dc.w $9600 ! (((grp_99200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C70
                dc.w $9500 ! ((grp_1969C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1969C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1969C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7750
                dc.w $9500 ! ((grp_196BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_196BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196BA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7468
                dc.w $9500 ! ((grp_CF240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C7F
                dc.w $9500 ! ((grp_B6940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C68
                dc.w $9500 ! ((grp_E8D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F5E
                dc.w $9500 ! ((grp_E9080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8468
                dc.w $9500 ! ((grp_E8D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8D20 / 2) >> 16)
                dc.w 1
