byte_2F84F4:    dc.b   0, $A,$75,$5C,$97,$8B,$80,$6A,$81,$6A
                                        ; DATA XREF: ROM:off_2C80   o
                dc.w sprite_24_24
                dc.w $785F
                dc.w $9500 ! ((grp_151DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_151DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151DE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $707B
                dc.w $9500 ! ((grp_169F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_169F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9057
                dc.w $9500 ! ((grp_90A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_90A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7673
                dc.w $9500 ! ((grp_DDFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8057
                dc.w $9500 ! ((grp_DDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9067
                dc.w $9500 ! ((grp_DDE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $687A
                dc.w $9500 ! ((grp_C38C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C38C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C38C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $758B
                dc.w $9500 ! ((grp_F5FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $818B
                dc.w $9500 ! ((grp_F5FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $906F
                dc.w $9500 ! ((grp_F6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A055
                dc.w $9500 ! ((grp_F60A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F60A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F60A0 / 2) >> 16)
                dc.w 1
