byte_2F01EE:    dc.b   0,  2,$79,$57,$86,$87,$82,$67,$83,$67
                                        ; DATA XREF: ROM:off_25C4   o
                dc.w sprite_32_16
                dc.w $755C
                dc.w $9500 ! ((grp_54100 / 2) & $00FF)
                dc.w $9600 ! (((grp_54100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $766B
                dc.w $9500 ! ((grp_8B580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7554
                dc.w $9500 ! ((grp_DA2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA2C0 / 2) >> 16)
                dc.w 2
