byte_2DF2E0:    dc.b   0,  5,$76,$5C,$89,$8D,$81,$74,$7D,$68
                                        ; DATA XREF: ROM:off_17F0   o
                dc.w sprite_24_24
                dc.w $6E6E
                dc.w $9500 ! ((grp_143080 / 2) & $00FF)
                dc.w $9600 ! (((grp_143080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143080 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7486
                dc.w $9500 ! ((grp_7A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $866E
                dc.w $9500 ! ((grp_7A980 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $795E
                dc.w $9500 ! ((grp_B5180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B57
                dc.w $9500 ! ((grp_E7860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7860 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E66
                dc.w $9500 ! ((grp_E7840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7840 / 2) >> 16)
                dc.w 1
