byte_2E26FE:    dc.b   0,  7,$66,$49,$A6,$8D,$86,$6B,$87,$6B
                                        ; DATA XREF: ROM:off_1A34   o
                dc.w sprite_16_32
                dc.w $8A48
                dc.w $9500 ! ((grp_64A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_64A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8568
                dc.w $9500 ! ((grp_1603C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1603C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1603C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9B6B
                dc.w $9500 ! ((grp_81C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_81C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6488
                dc.w $9500 ! ((grp_9AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_189640 / 2) & $00FF)
                dc.w $9600 ! (((grp_189640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189640 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7E78
                dc.w $9500 ! ((grp_D3140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9A5B
                dc.w $9500 ! ((grp_B9D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $824A
                dc.w $9500 ! ((grp_EBFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBFE0 / 2) >> 16)
                dc.w 1
