byte_2ECE98:    dc.b   0,  1,$76,$77,$8C,$89,$81,$80,$82,$80
                                        ; DATA XREF: ROM:off_2238   o
                dc.w sprite_24_16
                dc.w $747D
                dc.w $9500 ! ((grp_163D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_163D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163D80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7875
                dc.w $9500 ! ((grp_18C580 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C580 / 2) >> 16)
                dc.w 3
