byte_2DE862:    dc.b   0,  9,$7A,$4C,$B5,$8B,$97,$6B,$98,$6B
                                        ; DATA XREF: ROM:off_178C   o
                dc.w sprite_32_24
                dc.w $876B
                dc.w $9500 ! ((grp_12A240 / 2) & $00FF)
                dc.w $9600 ! (((grp_12A240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12A240 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $864A
                dc.w $9500 ! ((grp_4DB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4DB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4DB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7770
                dc.w $9500 ! ((grp_80A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $A76B
                dc.w $9500 ! ((grp_80A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $865A
                dc.w $9500 ! ((grp_D24C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D24C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D24C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9A83
                dc.w $9500 ! ((grp_D2500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8783
                dc.w $9500 ! ((grp_B9080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9863
                dc.w $9500 ! ((grp_EB240 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A64B
                dc.w $9500 ! ((grp_EB260 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AE7B
                dc.w $9500 ! ((grp_EB280 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB280 / 2) >> 16)
                dc.w 1
