byte_2D1E4E:    dc.b   0,  6,$70,$5D,$8E,$8E,$84,$6C,$85,$6C
                                        ; DATA XREF: ROM:off_E74   o
                dc.w sprite_24_32
                dc.w $725B
                dc.w $9500 ! ((grp_FCAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FCAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FCAC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $8A5B
                dc.w $9500 ! ((grp_A3E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6A5C
                dc.w $9500 ! ((grp_B2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A6F
                dc.w $9500 ! ((grp_E3F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3F40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $847B
                dc.w $9500 ! ((grp_E3F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3F80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9265
                dc.w $9500 ! ((grp_E3F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9760
                dc.w $9500 ! ((grp_E3F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3F60 / 2) >> 16)
                dc.w 1
