byte_2F8414:    dc.b   0,  4,$74,$7A,$A5,$A8,$8C,$91,$8D,$91
                                        ; DATA XREF: ROM:off_2C78   o
                dc.w sprite_16_24
                dc.w $7A78
                dc.w $9500 ! ((grp_17FC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17FC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17FC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8A7D
                dc.w $9500 ! ((grp_AE400 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9293
                dc.w $9500 ! ((grp_19F360 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F360 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9A97
                dc.w $9500 ! ((grp_DDE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7278
                dc.w $9500 ! ((grp_C3800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3800 / 2) >> 16)
                dc.w 2
