byte_2F7F62:    dc.b   0,  2,$7B,$7C,$97,$92,$89,$87,$8A,$87
                                        ; DATA XREF: ROM:off_2BEC   o
                dc.w sprite_16_16
                dc.w $8984
                dc.w $9500 ! ((grp_90180 / 2) & $00FF)
                dc.w $9600 ! (((grp_90180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7A7C
                dc.w $9500 ! ((grp_19F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $827C
                dc.w $9500 ! ((grp_F5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5880 / 2) >> 16)
                dc.w 1
