byte_2D6C90:    dc.b   0,  9,$74,$55,$92,$A0,$81,$3C,$81,$5B
                                        ; DATA XREF: ROM:off_1288   o
                dc.w sprite_32_32
                dc.w $708A
                dc.w $9500 ! ((grp_27000 / 2) & $00FF)
                dc.w $9600 ! (((grp_27000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $70AA
                dc.w $9500 ! ((grp_148BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_148BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148BA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $7D4A
                dc.w $9500 ! ((grp_A9300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $806A
                dc.w $9500 ! ((grp_A9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $609B
                dc.w $9500 ! ((grp_D65C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D65C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D65C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $73C2
                dc.w $9500 ! ((grp_D6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $803A
                dc.w $9500 ! ((grp_BCCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $909A
                dc.w $9500 ! ((grp_BCD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7882
                dc.w $9500 ! ((grp_EE480 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8882
                dc.w $9500 ! ((grp_EE4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE4A0 / 2) >> 16)
                dc.w 1
