byte_2F7CB4:    dc.b   0, $A,$64,$42,$9E,$83,$82,$75,$83,$75
                                        ; DATA XREF: ROM:off_2BC0   o
                dc.w sprite_32_32
                dc.w $6463
                dc.w $9500 ! ((grp_40800 / 2) & $00FF)
                dc.w $9600 ! (((grp_40800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8463
                dc.w $9500 ! ((grp_40A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_40A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $8B53
                dc.w $9500 ! ((grp_90900 / 2) & $00FF)
                dc.w $9600 ! (((grp_90900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F83
                dc.w $9500 ! ((grp_18F640 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F640 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $695B
                dc.w $9500 ! ((grp_DDCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDCC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5C6B
                dc.w $9500 ! ((grp_C3540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6783
                dc.w $9500 ! ((grp_C3500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A90
                dc.w $9500 ! ((grp_F5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $835B
                dc.w $9500 ! ((grp_F5EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A83
                dc.w $9500 ! ((grp_F5EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B8B
                dc.w $9500 ! ((grp_F5EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5EE0 / 2) >> 16)
                dc.w 1
