byte_2ED37E:    dc.b   0,  4,$95,$75,$A1,$85,$86,$81,$87,$81
                                        ; DATA XREF: ROM:off_228C   o
                dc.w sprite_24_24
                dc.w $8E72
                dc.w $9500 ! ((grp_14BF60 / 2) & $00FF)
                dc.w $9600 ! (((grp_14BF60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14BF60 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7081
                dc.w $9500 ! ((grp_52200 / 2) & $00FF)
                dc.w $9600 ! (((grp_52200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_52200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7E71
                dc.w $9500 ! ((grp_88F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_88F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6889
                dc.w $9500 ! ((grp_F01C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F01C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F01C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7679
                dc.w $9500 ! ((grp_F01E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F01E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F01E0 / 2) >> 16)
                dc.w 1
