byte_2E8F04:    dc.b   0,  3,$7C,$59,$84,$8F,$82,$72,$80,$65
                                        ; DATA XREF: ROM:off_1DF0   o
                dc.w sprite_16_16
                dc.w $7C7C
                dc.w $9500 ! ((grp_7F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7A5C
                dc.w $9500 ! ((grp_A6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7E54
                dc.w $9500 ! ((grp_197AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197AA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7E8C
                dc.w $9500 ! ((grp_EA900 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA900 / 2) >> 16)
                dc.w 1
