byte_2E21B2:    dc.b   0,  7,$76,$37,$8C,$B9,$81,$78,$82,$78
                                        ; DATA XREF: ROM:off_19EC   o
                dc.w sprite_16_24
                dc.w $7492
                dc.w $9500 ! ((grp_173EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_173EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $85A5
                dc.w $9500 ! ((grp_195CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_195CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7435
                dc.w $9500 ! ((grp_B5740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8785
                dc.w $9500 ! ((grp_B5780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $74AD
                dc.w $9500 ! ((grp_E7E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7E80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $745D
                dc.w $9500 ! ((grp_E7E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C45
                dc.w $9500 ! ((grp_E7E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7E40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C72
                dc.w $9500 ! ((grp_E7EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7EA0 / 2) >> 16)
                dc.w 1
