byte_2F90A6:    dc.b   0,  4,$6D,$72,$8E,$90,$7D,$81,$7E,$81
                                        ; DATA XREF: ROM:off_2D04   o
                dc.w sprite_32_24
                dc.w $6F78
                dc.w $9500 ! ((grp_139B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_139B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7670
                dc.w $9500 ! ((grp_18FD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FD00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $677F
                dc.w $9500 ! ((grp_F6520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7290
                dc.w $9500 ! ((grp_F6540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E77
                dc.w $9500 ! ((grp_F6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6500 / 2) >> 16)
                dc.w 1
