byte_2D147A:    dc.b   0,  9,$6B,$5C,$97,$8E,$85,$75,$86,$75
                                        ; DATA XREF: ROM:off_E0C   o
                dc.w sprite_24_32
                dc.w $756B
                dc.w $9500 ! ((grp_FBEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FBEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FBEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $755B
                dc.w $9500 ! ((grp_47C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_47C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $5D65
                dc.w $9500 ! ((grp_5D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_158140 / 2) & $00FF)
                dc.w $9600 ! (((grp_158140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158140 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6D7A
                dc.w $9500 ! ((grp_193180 / 2) & $00FF)
                dc.w $9600 ! (((grp_193180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193180 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6D62
                dc.w $9500 ! ((grp_1931E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1931E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1931E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5573
                dc.w $9500 ! ((grp_B1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A56C
                dc.w $9500 ! ((grp_B1D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9563
                dc.w $9500 ! ((grp_E39A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E39A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E39A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AD6E
                dc.w $9500 ! ((grp_E39C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E39C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E39C0 / 2) >> 16)
                dc.w 1
