byte_2E4A66:    dc.b   0,  7,$5A,$5F,$95,$92,$77,$78,$69,$78
                                        ; DATA XREF: ROM:off_1B64   o
                dc.w sprite_16_32
                dc.w $7375
                dc.w $9500 ! ((grp_65900 / 2) & $00FF)
                dc.w $9600 ! (((grp_65900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $585D
                dc.w $9500 ! ((grp_162280 / 2) & $00FF)
                dc.w $9600 ! (((grp_162280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162280 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $837F
                dc.w $9500 ! ((grp_162340 / 2) & $00FF)
                dc.w $9600 ! (((grp_162340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162340 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $636D
                dc.w $9500 ! ((grp_84C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $637D
                dc.w $9500 ! ((grp_D52C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D52C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D52C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $888F
                dc.w $9500 ! ((grp_D5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B70
                dc.w $9500 ! ((grp_BB980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B85
                dc.w $9500 ! ((grp_ED720 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED720 / 2) >> 16)
                dc.w 1
