byte_2D373C:    dc.b   0,  2,$93,$69,$B4,$88,$A3,$78,$A4,$78
                                        ; DATA XREF: ROM:off_1028   o
                dc.w sprite_32_32
                dc.w $9767
                dc.w $9500 ! ((grp_17400 / 2) & $00FF)
                dc.w $9600 ! (((grp_17400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $9A87
                dc.w $9500 ! ((grp_184B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_184B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8F7B
                dc.w $9500 ! ((grp_E4FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4FE0 / 2) >> 16)
                dc.w 1
