byte_2D3E68:    dc.b   0,  5,$73,$65,$92,$8F,$7C,$77,$7D,$77
                                        ; DATA XREF: ROM:off_1088   o
                dc.w sprite_24_24
                dc.w $7578
                dc.w $9500 ! ((grp_140920 / 2) & $00FF)
                dc.w $9600 ! (((grp_140920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140920 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7C60
                dc.w $9500 ! ((grp_172480 / 2) & $00FF)
                dc.w $9600 ! (((grp_172480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172480 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $657D
                dc.w $9500 ! ((grp_B30C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B30C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B30C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6D80
                dc.w $9500 ! ((grp_B3100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C63
                dc.w $9500 ! ((grp_B3140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D78
                dc.w $9500 ! ((grp_B3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3180 / 2) >> 16)
                dc.w 2
