byte_2D54FE:    dc.b   0,  6,$6F,$64,$8E,$8F,$7D,$76,$6B,$6C
                                        ; DATA XREF: ROM:off_1194   o
                dc.w sprite_24_24
                dc.w $6B5E
                dc.w $9500 ! ((grp_140FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_140FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140FE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $6B76
                dc.w $9500 ! ((grp_141100 / 2) & $00FF)
                dc.w $9600 ! (((grp_141100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141100 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $835F
                dc.w $9500 ! ((grp_78600 / 2) & $00FF)
                dc.w $9600 ! (((grp_78600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6366
                dc.w $9500 ! ((grp_194800 / 2) & $00FF)
                dc.w $9600 ! (((grp_194800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194800 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6B8E
                dc.w $9500 ! ((grp_CB8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8788
                dc.w $9500 ! ((grp_CB900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8283
                dc.w $9500 ! ((grp_E6140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6140 / 2) >> 16)
                dc.w 1
