byte_2FDBBE:    dc.b   0,  6,$6B,$5D,$9B,$8D,$83,$75,$84,$75
                                        ; DATA XREF: ROM:off_3334   o
                dc.w sprite_24_24
                dc.w $7E59
                dc.w $9500 ! ((grp_154AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_154AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_154AE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $665B
                dc.w $9500 ! ((grp_16D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D500 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7C78
                dc.w $9500 ! ((grp_16D5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D5C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7088
                dc.w $9500 ! ((grp_1912C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1912C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1912C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8270
                dc.w $9500 ! ((grp_E0080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $965E
                dc.w $9500 ! ((grp_C5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $766B
                dc.w $9500 ! ((grp_F8600 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8600 / 2) >> 16)
                dc.w 1
