byte_2CE0B8:    dc.b   0,  1,$85,$85,$9A,$8E,$8F,$89,$90,$89
                                        ; DATA XREF: ROM:off_9F0   o
                dc.w sprite_24_8
                dc.w $838B
                dc.w $9500 ! ((grp_183640 / 2) & $00FF)
                dc.w $9600 ! (((grp_183640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183640 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8583
                dc.w $9500 ! ((grp_1836A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1836A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1836A0 / 2) >> 16)
                dc.w 3
