byte_2F991E:    dc.b   0,  7,$65,$69,$A2,$99,$83,$81,$84,$81
                                        ; DATA XREF: ROM:off_2D9C   o
                dc.w sprite_8_16
                dc.w $6D77
                dc.w $9500 ! ((grp_C4380 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C67
                dc.w $9500 ! ((grp_C43C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C43C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C43C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C94
                dc.w $9500 ! ((grp_F6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B86
                dc.w $9500 ! ((grp_F6BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8770
                dc.w $9500 ! ((grp_F6C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A85
                dc.w $9500 ! ((grp_F6C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $907C
                dc.w $9500 ! ((grp_F6C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E91
                dc.w $9500 ! ((grp_F6C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6C60 / 2) >> 16)
                dc.w 1
