byte_2F501A:    dc.b   0,  7,$76,$61,$97,$8D,$87,$75,$88,$75
                                        ; DATA XREF: ROM:off_2A34   o
                dc.w sprite_32_24
                dc.w $7661
                dc.w $9500 ! ((grp_137140 / 2) & $00FF)
                dc.w $9600 ! (((grp_137140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_137140 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7679
                dc.w $9500 ! ((grp_1372C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1372C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1372C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $9671
                dc.w $9500 ! ((grp_AD000 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7B59
                dc.w $9500 ! ((grp_18EB60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EB60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EB60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6E6A
                dc.w $9500 ! ((grp_C1B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6671
                dc.w $9500 ! ((grp_F43E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F43E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F43E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E83
                dc.w $9500 ! ((grp_F4400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A07B
                dc.w $9500 ! ((grp_F4420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4420 / 2) >> 16)
                dc.w 1
