byte_2EEF9A:    dc.b   0,  1,$79,$6B,$85,$8E,$7F,$84,$80,$84
                                        ; DATA XREF: ROM:off_2444   o
                dc.w sprite_16_32
                dc.w $7876
                dc.w $9500 ! ((grp_6AD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AD00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8877
                dc.w $9500 ! ((grp_F0CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0CA0 / 2) >> 16)
                dc.w 1
