byte_2F1A4A:    dc.b   0,  5,$74,$48,$98,$70,$86,$5E,$87,$5E
                                        ; DATA XREF: ROM:off_26A4   o
                dc.w sprite_24_24
                dc.w $8258
                dc.w $9500 ! ((grp_14E6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E6C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $7251
                dc.w $9500 ! ((grp_8C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7949
                dc.w $9500 ! ((grp_F20E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F20E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F20E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8150
                dc.w $9500 ! ((grp_F2080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2080 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8570
                dc.w $9500 ! ((grp_F20A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F20A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F20A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A68
                dc.w $9500 ! ((grp_F20C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F20C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F20C0 / 2) >> 16)
                dc.w 1
