byte_2F69A0:    dc.b   0,$17,$77,$52,$B0,$82,$7E,$88,$7F,$88
                                        ; DATA XREF: ROM:off_2B60   o
                dc.w sprite_24_32
                dc.w $7860
                dc.w $9500 ! ((grp_1171C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1171C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1171C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $B049
                dc.w $9500 ! ((grp_151060 / 2) & $00FF)
                dc.w $9600 ! (((grp_151060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151060 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $407E
                dc.w $9500 ! ((grp_56900 / 2) & $00FF)
                dc.w $9600 ! (((grp_56900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7850
                dc.w $9500 ! ((grp_56500 / 2) & $00FF)
                dc.w $9600 ! (((grp_56500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56500 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7880
                dc.w $9500 ! ((grp_56800 / 2) & $00FF)
                dc.w $9600 ! (((grp_56800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $987A
                dc.w $9500 ! ((grp_17F2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $B061
                dc.w $9500 ! ((grp_8F880 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7051
                dc.w $9500 ! ((grp_AD180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9852
                dc.w $9500 ! ((grp_AD280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AD280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AD280 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E48
                dc.w $9500 ! ((grp_18EEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EEC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9060
                dc.w $9500 ! ((grp_19EB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EB80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $307A
                dc.w $9500 ! ((grp_DD2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6887
                dc.w $9500 ! ((grp_DD240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD240 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A871
                dc.w $9500 ! ((grp_DD280 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A05A
                dc.w $9500 ! ((grp_C2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A06A
                dc.w $9500 ! ((grp_C2B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A853
                dc.w $9500 ! ((grp_C2440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6089
                dc.w $9500 ! ((grp_F52E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F52E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F52E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7078
                dc.w $9500 ! ((grp_F4BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9078
                dc.w $9500 ! ((grp_F5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9872
                dc.w $9500 ! ((grp_F4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A869
                dc.w $9500 ! ((grp_F5320 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A879
                dc.w $9500 ! ((grp_F5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C84E
                dc.w $9500 ! ((grp_F5360 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5360 / 2) >> 16)
                dc.w 1
