byte_2D0642:    dc.b   0,  1,$62,$6D,$70,$8B,$69,$7C,$6A,$7C
                                        ; DATA XREF: ROM:off_D54   o
                dc.w sprite_16_16
                dc.w $636B
                dc.w $9500 ! ((grp_75C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $607B
                dc.w $9500 ! ((grp_192D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_192D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192D60 / 2) >> 16)
                dc.w 3
