byte_2F7DBE:    dc.b   0,  2,$7B,$7C,$92,$92,$86,$86,$87,$86
                                        ; DATA XREF: ROM:off_2BD4   o
                dc.w sprite_8_24
                dc.w $827C
                dc.w $9500 ! ((grp_19F060 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F060 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7A7C
                dc.w $9500 ! ((grp_C2F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A83
                dc.w $9500 ! ((grp_C2FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2FC0 / 2) >> 16)
                dc.w 2
