byte_2DF036:    dc.b   0,  6,$67,$55,$8F,$8E,$74,$6C,$5C,$6F
                                        ; DATA XREF: ROM:off_17D4   o
                dc.w sprite_32_32
                dc.w $6A53
                dc.w $9500 ! ((grp_26600 / 2) & $00FF)
                dc.w $9600 ! (((grp_26600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_26600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7273
                dc.w $9500 ! ((grp_50400 / 2) & $00FF)
                dc.w $9600 ! (((grp_50400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $526B
                dc.w $9500 ! ((grp_1795C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1795C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1795C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8A63
                dc.w $9500 ! ((grp_85B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_85B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $627B
                dc.w $9500 ! ((grp_D61C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D61C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D61C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6269
                dc.w $9500 ! ((grp_EE040 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7983
                dc.w $9500 ! ((grp_EE060 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE060 / 2) >> 16)
                dc.w 1
