byte_2FDF22:    dc.b   0,  9,$60,$4F,$94,$8D,$7A,$6E,$7B,$6E
                                        ; DATA XREF: ROM:off_335C   o
                dc.w sprite_16_16
                dc.w $804D
                dc.w $9500 ! ((grp_95800 / 2) & $00FF)
                dc.w $9600 ! (((grp_95800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95800 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $604D
                dc.w $9500 ! ((grp_A1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1280 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6988
                dc.w $9500 ! ((grp_A1300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $885D
                dc.w $9500 ! ((grp_AF100 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9054
                dc.w $9500 ! ((grp_AF180 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7970
                dc.w $9500 ! ((grp_1A0740 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0740 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $806B
                dc.w $9500 ! ((grp_1A07A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A07A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A07A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5E55
                dc.w $9500 ! ((grp_E0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7178
                dc.w $9500 ! ((grp_C5F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D5D
                dc.w $9500 ! ((grp_F8720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8720 / 2) >> 16)
                dc.w 1
