byte_2F9706:    dc.b   0,  1,$95,$7C,$A6,$88,$9D,$82,$9E,$82
                                        ; DATA XREF: ROM:off_2D7C   o
                dc.w sprite_24_8
                dc.w $937A
                dc.w $9500 ! ((grp_190060 / 2) & $00FF)
                dc.w $9600 ! (((grp_190060 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190060 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9682
                dc.w $9500 ! ((grp_DE580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE580 / 2) >> 16)
                dc.w 2
