byte_2CD3DA:    dc.b   0,  2,$8E,$73,$A1,$85,$88,$98,$89,$98
                                        ; DATA XREF: ROM:off_8AC   o
                dc.w sprite_24_16
                dc.w $8978
                dc.w $9500 ! ((grp_156940 / 2) & $00FF)
                dc.w $9600 ! (((grp_156940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8088
                dc.w $9500 ! ((grp_C79C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C79C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C79C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9470
                dc.w $9500 ! ((grp_C7A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7A00 / 2) >> 16)
                dc.w 2
