byte_2CC624:    dc.b   0,  1,$78,$7D,$8F,$8A,$84,$83,$85,$83
                                        ; DATA XREF: ROM:off_798   o
                dc.w sprite_24_16
                dc.w $7A7D
                dc.w $9500 ! ((grp_155D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_155D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $767A
                dc.w $9500 ! ((grp_AFF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFF80 / 2) >> 16)
                dc.w 2
