byte_2F1462:    dc.b   0, $C,$68,$66,$A2,$9C,$84,$7C,$85,$7C
                                        ; DATA XREF: ROM:off_2644   o
                dc.w sprite_24_32
                dc.w $8F6A
                dc.w $9500 ! ((grp_1141C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1141C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1141C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6059
                dc.w $9500 ! ((grp_14EEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14EEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14EEA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $878A
                dc.w $9500 ! ((grp_54C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_54C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7F61
                dc.w $9500 ! ((grp_6C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5F90
                dc.w $9500 ! ((grp_8C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6F8E
                dc.w $9500 ! ((grp_8C680 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A772
                dc.w $9500 ! ((grp_AC900 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7761
                dc.w $9500 ! ((grp_19D8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D8C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7F87
                dc.w $9500 ! ((grp_19D920 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D920 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7381
                dc.w $9500 ! ((grp_DB480 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $585E
                dc.w $9500 ! ((grp_C07C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C07C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C07C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F71
                dc.w $9500 ! ((grp_F2640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AF81
                dc.w $9500 ! ((grp_F2660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2660 / 2) >> 16)
                dc.w 1
