byte_2F825E:    dc.b   0,  2,$71,$6A,$90,$A0,$7F,$8E,$80,$8E
                                        ; DATA XREF: ROM:off_2C54   o
                dc.w sprite_24_32
                dc.w $747F
                dc.w $9500 ! ((grp_1198C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1198C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1198C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $6C80
                dc.w $9500 ! ((grp_C3600 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3600 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C80
                dc.w $9500 ! ((grp_F5F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5F40 / 2) >> 16)
                dc.w 1
