byte_2D6EF4:    dc.b   0,  8,$74,$55,$92,$7A,$7F,$4E,$8A,$55
                                        ; DATA XREF: ROM:off_12A0   o
                dc.w sprite_16_32
                dc.w $796E
                dc.w $9500 ! ((grp_66700 / 2) & $00FF)
                dc.w $9600 ! (((grp_66700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $794E
                dc.w $9500 ! ((grp_66800 / 2) & $00FF)
                dc.w $9600 ! (((grp_66800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $695E
                dc.w $9500 ! ((grp_179F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_179F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8951
                dc.w $9500 ! ((grp_19A980 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A980 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9061
                dc.w $9500 ! ((grp_BCE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9568
                dc.w $9500 ! ((grp_BCE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6976
                dc.w $9500 ! ((grp_EE560 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B46
                dc.w $9500 ! ((grp_EE580 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $897E
                dc.w $9500 ! ((grp_EE5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE5A0 / 2) >> 16)
                dc.w 1
