byte_2DF428:    dc.b   0,  4,$72,$58,$90,$80,$81,$6C,$88,$5F
                                        ; DATA XREF: ROM:off_1800   o
                dc.w sprite_32_24
                dc.w $7C5C
                dc.w $9500 ! ((grp_1258C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1258C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1258C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6C61
                dc.w $9500 ! ((grp_60900 / 2) & $00FF)
                dc.w $9600 ! (((grp_60900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_60900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7C74
                dc.w $9500 ! ((grp_15B980 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7D54
                dc.w $9500 ! ((grp_185D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_185D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185D40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6475
                dc.w $9500 ! ((grp_E7920 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7920 / 2) >> 16)
                dc.w 1
