byte_2D4D32:    dc.b   0,  3,$79,$5F,$8A,$99,$87,$7E,$80,$69
                                        ; DATA XREF: ROM:off_113C   o
                dc.w sprite_32_24
                dc.w $775D
                dc.w $9500 ! ((grp_1276C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1276C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1276C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7984
                dc.w $9500 ! ((grp_4B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7774
                dc.w $9500 ! ((grp_15D000 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D000 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $7894
                dc.w $9500 ! ((grp_B6C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6C40 / 2) >> 16)
                dc.w 2
