byte_2FA222:    dc.b   0,  6,$7C,$4B,$8F,$8E,$89,$68,$8A,$68
                                        ; DATA XREF: ROM:off_2DF4   o
                dc.w sprite_32_32
                dc.w $7271
                dc.w $9500 ! ((grp_41A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_41A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8351
                dc.w $9500 ! ((grp_11AF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11AF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11AF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7041
                dc.w $9500 ! ((grp_16A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A800 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7351
                dc.w $9500 ! ((grp_1807C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1807C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1807C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9B5E
                dc.w $9500 ! ((grp_180880 / 2) & $00FF)
                dc.w $9600 ! (((grp_180880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180880 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $6369
                dc.w $9500 ! ((grp_A0580 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8849
                dc.w $9500 ! ((grp_DEC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEC00 / 2) >> 16)
                dc.w 2
