byte_2F7392:    dc.b   0, $D,$67,$31,$92,$84,$6E,$7B,$6F,$7B
                                        ; DATA XREF: ROM:off_2B8C   o
                dc.w sprite_32_32
                dc.w $632F
                dc.w $9500 ! ((grp_3E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_3E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3E600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $6B4F
                dc.w $9500 ! ((grp_1512A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1512A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1512A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $7367
                dc.w $9500 ! ((grp_6E900 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9347
                dc.w $9500 ! ((grp_17F680 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9737
                dc.w $9500 ! ((grp_8FF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $835B
                dc.w $9500 ! ((grp_ADA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $833B
                dc.w $9500 ! ((grp_ADA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B3F
                dc.w $9500 ! ((grp_ADB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5B57
                dc.w $9500 ! ((grp_DD580 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $837B
                dc.w $9500 ! ((grp_C2DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B3B
                dc.w $9500 ! ((grp_F5640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $635F
                dc.w $9500 ! ((grp_F5660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B65
                dc.w $9500 ! ((grp_F5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $975F
                dc.w $9500 ! ((grp_F5620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5620 / 2) >> 16)
                dc.w 1
