byte_2E2EB4:    dc.b   0,  9,$6F,$3E,$8E,$8F,$81,$54,$79,$39
                                        ; DATA XREF: ROM:off_1A70   o
                dc.w sprite_24_32
                dc.w $6F45
                dc.w $9500 ! ((grp_1063C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1063C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1063C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7075
                dc.w $9500 ! ((grp_7FD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8F4F
                dc.w $9500 ! ((grp_197CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_197CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197CE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $703D
                dc.w $9500 ! ((grp_D1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8465
                dc.w $9500 ! ((grp_D1540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6747
                dc.w $9500 ! ((grp_B8880 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C65
                dc.w $9500 ! ((grp_B88C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B88C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B88C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9752
                dc.w $9500 ! ((grp_B8900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $874D
                dc.w $9500 ! ((grp_EABE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EABE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EABE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $875D
                dc.w $9500 ! ((grp_EAC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAC00 / 2) >> 16)
                dc.w 1
