byte_2FDEB8:    dc.b   0,  7,$78,$48,$92,$8D,$85,$6A,$86,$6A
                                        ; DATA XREF: ROM:off_3358   o
                dc.w sprite_16_32
                dc.w $7F48
                dc.w $9500 ! ((grp_71700 / 2) & $00FF)
                dc.w $9600 ! (((grp_71700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7F68
                dc.w $9500 ! ((grp_16D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D800 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $7750
                dc.w $9500 ! ((grp_AF080 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF080 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7588
                dc.w $9500 ! ((grp_191620 / 2) & $00FF)
                dc.w $9600 ! (((grp_191620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7770
                dc.w $9500 ! ((grp_1A06E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A06E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A06E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7F78
                dc.w $9500 ! ((grp_C5EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F64
                dc.w $9500 ! ((grp_F86E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F86E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F86E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8640
                dc.w $9500 ! ((grp_F8700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8700 / 2) >> 16)
                dc.w 1
