byte_2D4A02:    dc.b   0,  5,$28,$84,$69,$92,$48,$8B,$49,$8B
                                        ; DATA XREF: ROM:off_110C   o
                dc.w sprite_32_16
                dc.w $2E85
                dc.w $9500 ! ((grp_4C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C400 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $5685
                dc.w $9500 ! ((grp_D0780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4E83
                dc.w $9500 ! ((grp_B7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $268D
                dc.w $9500 ! ((grp_E9DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9DE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $2E7D
                dc.w $9500 ! ((grp_E9E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $668A
                dc.w $9500 ! ((grp_E9E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9E20 / 2) >> 16)
                dc.w 1
