byte_2D2248:    dc.b   0,  2,$75,$A8,$8B,$B3,$89,$AD,$8A,$AD
                                        ; DATA XREF: ROM:off_EA8   o
                dc.w sprite_32_8
                dc.w $72A9
                dc.w $9500 ! ((grp_97A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $72B1
                dc.w $9500 ! ((grp_E4180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4180 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8AB1
                dc.w $9500 ! ((grp_E41A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E41A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E41A0 / 2) >> 16)
                dc.w 1
