byte_2EDB42:    dc.b   0,  5,$6C,$68,$9A,$96,$85,$7C,$86,$7C
                                        ; DATA XREF: ROM:off_22F4   o
                dc.w sprite_24_16
                dc.w $6D80
                dc.w $9500 ! ((grp_164B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_164B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $857E
                dc.w $9500 ! ((grp_88E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_88E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7778
                dc.w $9500 ! ((grp_18CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CA00 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7E70
                dc.w $9500 ! ((grp_18CA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CA60 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8468
                dc.w $9500 ! ((grp_18CAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CAC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7490
                dc.w $9500 ! ((grp_D8800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8800 / 2) >> 16)
                dc.w 2
