byte_2D57B4:    dc.b   0,  6,$6F,$67,$8E,$8F,$71,$76,$6B,$71
                                        ; DATA XREF: ROM:off_11B0   o
                dc.w sprite_32_16
                dc.w $5D6C
                dc.w $9500 ! ((grp_4B800 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B800 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $667C
                dc.w $9500 ! ((grp_4B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B900 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $6664
                dc.w $9500 ! ((grp_187840 / 2) & $00FF)
                dc.w $9600 ! (((grp_187840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187840 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $668C
                dc.w $9500 ! ((grp_1878A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1878A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1878A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8989
                dc.w $9500 ! ((grp_D0080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D6C
                dc.w $9500 ! ((grp_B73C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B73C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B73C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8681
                dc.w $9500 ! ((grp_E99C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E99C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E99C0 / 2) >> 16)
                dc.w 1
