byte_2CFA68:    dc.b   0,  1,$7B,$79,$84,$89,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_BE8   o
                dc.w sprite_16_16
                dc.w $7977
                dc.w $9500 ! ((grp_74F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_74F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8187
                dc.w $9500 ! ((grp_E2F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2F40 / 2) >> 16)
                dc.w 1
