byte_2E896C:    dc.b   0,  3,$77,$65,$85,$8D,$7F,$78,$7D,$6C
                                        ; DATA XREF: ROM:off_1D98   o
                dc.w sprite_16_24
                dc.w $7662
                dc.w $9500 ! ((grp_174940 / 2) & $00FF)
                dc.w $9600 ! (((grp_174940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7582
                dc.w $9500 ! ((grp_7C300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7C300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7C300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7D7A
                dc.w $9500 ! ((grp_E8820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8589
                dc.w $9500 ! ((grp_E8840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8840 / 2) >> 16)
                dc.w 1
