byte_2F2FBE:    dc.b   0,  8,$6B,$5F,$8B,$8E,$70,$76,$71,$76
                                        ; DATA XREF: ROM:off_2784   o
                dc.w sprite_24_24
                dc.w $766A
                dc.w $9500 ! ((grp_14F320 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F320 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $566A
                dc.w $9500 ! ((grp_9EE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A62
                dc.w $9500 ! ((grp_9EF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6A82
                dc.w $9500 ! ((grp_9EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $718A
                dc.w $9500 ! ((grp_18E380 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E380 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B5A
                dc.w $9500 ! ((grp_DB900 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5268
                dc.w $9500 ! ((grp_C0C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A5A
                dc.w $9500 ! ((grp_F2C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E7A
                dc.w $9500 ! ((grp_F2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2C80 / 2) >> 16)
                dc.w 1
