byte_2EBFC4:    dc.b   0,  1,$82,$5F,$93,$88,$8A,$73,$8B,$73
                                        ; DATA XREF: ROM:off_2090   o
                dc.w sprite_24_32
                dc.w $7F6D
                dc.w $9500 ! ((grp_110EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_110EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_110EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $815D
                dc.w $9500 ! ((grp_87B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_87B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87B00 / 2) >> 16)
                dc.w 4
