byte_2E4AD0:    dc.b   0,  6,$59,$5E,$86,$90,$6F,$77,$6D,$7A
                                        ; DATA XREF: ROM:off_1B68   o
                dc.w sprite_24_32
                dc.w $696C
                dc.w $9500 ! ((grp_10C3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C3C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6164
                dc.w $9500 ! ((grp_18A480 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A480 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $817B
                dc.w $9500 ! ((grp_199C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_199C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199C00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5165
                dc.w $9500 ! ((grp_D5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $718C
                dc.w $9500 ! ((grp_D5380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6174
                dc.w $9500 ! ((grp_BB9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $695C
                dc.w $9500 ! ((grp_ED740 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED740 / 2) >> 16)
                dc.w 1
