byte_2E533E:    dc.b   0,  9,$6F,$64,$88,$8E,$3F,$97,$72,$63
                                        ; DATA XREF: ROM:off_1BB4   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $9A60
                dc.w $9500 ! ((grp_1609C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1609C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1609C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82880 / 2) & $00FF)
                dc.w $9600 ! (((grp_82880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7A69
                dc.w $9500 ! ((grp_9AD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5A5E
                dc.w $9500 ! ((grp_D3780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7457
                dc.w $9500 ! ((grp_D37C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D37C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D37C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA540 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8271
                dc.w $9500 ! ((grp_EC4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC4C0 / 2) >> 16)
                dc.w 1
