byte_2E1E54:    dc.b   0,  3,$64,$73,$86,$87,$75,$7D,$76,$7D
                                        ; DATA XREF: ROM:off_19B8   o
                dc.w sprite_24_16
                dc.w $6C75
                dc.w $9500 ! ((grp_15E2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15E2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15E2C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $5C7A
                dc.w $9500 ! ((grp_D0340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7470
                dc.w $9500 ! ((grp_D0380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C82
                dc.w $9500 ! ((grp_D03C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D03C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D03C0 / 2) >> 16)
                dc.w 2
