byte_2F93FA:    dc.b   0,  5,$67,$70,$90,$95,$7B,$82,$7C,$82
                                        ; DATA XREF: ROM:off_2D34   o
                dc.w sprite_32_24
                dc.w $6B76
                dc.w $9500 ! ((grp_139E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_139E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_139E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $678E
                dc.w $9500 ! ((grp_18FEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FEE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7B6E
                dc.w $9500 ! ((grp_DE500 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B74
                dc.w $9500 ! ((grp_C4040 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6386
                dc.w $9500 ! ((grp_F6720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6720 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D96
                dc.w $9500 ! ((grp_F6740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6740 / 2) >> 16)
                dc.w 1
