byte_2D5B84:    dc.b   0,  5,$63,$5E,$89,$8A,$72,$75,$76,$6D
                                        ; DATA XREF: ROM:off_11D8   o
                dc.w sprite_24_32
                dc.w $636F
                dc.w $9500 ! ((grp_FF340 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $635F
                dc.w $9500 ! ((grp_15A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_15A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15A300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7B84
                dc.w $9500 ! ((grp_CBD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B67
                dc.w $9500 ! ((grp_B3BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B7F
                dc.w $9500 ! ((grp_E62C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E62C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E62C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B5D
                dc.w $9500 ! ((grp_E62E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E62E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E62E0 / 2) >> 16)
                dc.w 1
