byte_2DEC58:    dc.b   0,  8,$6F,$60,$8E,$8F,$82,$70,$84,$6A
                                        ; DATA XREF: ROM:off_17B0   o
                dc.w sprite_16_32
                dc.w $7C68
                dc.w $9500 ! ((grp_63100 / 2) & $00FF)
                dc.w $9600 ! (((grp_63100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $746E
                dc.w $9500 ! ((grp_A6A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6C66
                dc.w $9500 ! ((grp_1982E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1982E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1982E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8C65
                dc.w $9500 ! ((grp_198340 / 2) & $00FF)
                dc.w $9600 ! (((grp_198340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6D89
                dc.w $9500 ! ((grp_D2700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7C60
                dc.w $9500 ! ((grp_D2740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $745E
                dc.w $9500 ! ((grp_B9340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8488
                dc.w $9500 ! ((grp_EB480 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
