byte_2E24D6:    dc.b   0,  3,$6F,$66,$8E,$8F,$7C,$77,$87,$68
                                        ; DATA XREF: ROM:off_1A1C   o
                dc.w sprite_32_24
                dc.w $7068
                dc.w $9500 ! ((grp_1264C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1264C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1264C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6980
                dc.w $9500 ! ((grp_77B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_77B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7660
                dc.w $9500 ! ((grp_186340 / 2) & $00FF)
                dc.w $9600 ! (((grp_186340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186340 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7980
                dc.w $9500 ! ((grp_CAF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAF00 / 2) >> 16)
                dc.w 2
