byte_2F1C5A:    dc.b   0,  6,$79,$64,$8F,$8B,$84,$77,$85,$77
                                        ; DATA XREF: ROM:000026BC   o
                dc.w sprite_16_32
                dc.w $7C62
                dc.w $9500 ! ((grp_6BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6BA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7782
                dc.w $9500 ! ((grp_8BD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7465
                dc.w $9500 ! ((grp_F1AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7473
                dc.w $9500 ! ((grp_F1AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8786
                dc.w $9500 ! ((grp_F1B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1B00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C65
                dc.w $9500 ! ((grp_F1B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C73
                dc.w $9500 ! ((grp_F1B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1B40 / 2) >> 16)
                dc.w 1
