byte_2E2D76:    dc.b   0,  9,$6F,$3A,$8E,$8F,$7B,$47,$7C,$4F
                                        ; DATA XREF: ROM:off_1A64   o
                dc.w sprite_24_24
                dc.w $743D
                dc.w $9500 ! ((grp_145A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_145A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145A20 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7755
                dc.w $9500 ! ((grp_1765C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1765C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1765C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5642
                dc.w $9500 ! ((grp_7FA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6965
                dc.w $9500 ! ((grp_7FA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8831
                dc.w $9500 ! ((grp_7FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8761
                dc.w $9500 ! ((grp_188620 / 2) & $00FF)
                dc.w $9600 ! (((grp_188620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188620 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $654B
                dc.w $9500 ! ((grp_D1380 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F57
                dc.w $9500 ! ((grp_EAA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAA00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8759
                dc.w $9500 ! ((grp_EAA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAA20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9659
                dc.w $9500 ! ((grp_EAA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAA40 / 2) >> 16)
                dc.w 1
