byte_2CBE7C:    dc.b   0,  5,$71,$72,$8D,$8E,$89,$76,$8A,$76
                                        ; DATA XREF: ROM:off_6B0   o
                dc.w sprite_32_24
                dc.w $7261
                dc.w $9500 ! ((grp_11DDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11DDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11DDC0 / 2) >> 16)
                dc.w    $C
                dc.w sprite_32_24
                dc.w $7279
                dc.w $9500 ! ((grp_11DC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11DC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11DC40 / 2) >> 16)
                dc.w    $C
                dc.w sprite_16_24
                dc.w $9261
                dc.w $9500 ! ((grp_16F0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16F0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16F0C0 / 2) >> 16)
                dc.w     6
                dc.w sprite_16_16
                dc.w $9279
                dc.w $9500 ! ((grp_72A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_72A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72A80 / 2) >> 16)
                dc.w     4
                dc.w sprite_8_24
                dc.w $6A72
                dc.w $9500 ! ((grp_191B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_191B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191B00 / 2) >> 16)
                dc.w     3
                dc.w sprite_8_8
                dc.w $9289
                dc.w $9500 ! ((grp_E1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1280 / 2) >> 16)
                dc.w     1
