byte_2EE08A:    dc.b   0,  2,$79,$72,$87,$7E,$80,$78,$81,$78
                                        ; DATA XREF: ROM:off_235C   o
                dc.w sprite_16_16
                dc.w $7A70
                dc.w $9500 ! ((grp_89A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7270
                dc.w $9500 ! ((grp_F0640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C80
                dc.w $9500 ! ((grp_F0660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0660 / 2) >> 16)
                dc.w 1
