byte_2CBECE:    dc.b   0,  6,$6D,$81,$97,$8F,$84,$7C,$85,$7C
                                        ; DATA XREF: ROM:off_6B4   o
                dc.w sprite_32_24
                dc.w $6778
                dc.w $9500 ! ((grp_11DF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_11DF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11DF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8778
                dc.w $9500 ! ((grp_13D9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D9E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7C70
                dc.w $9500 ! ((grp_182F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_182F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5F7D
                dc.w $9500 ! ((grp_AFE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6F68
                dc.w $9500 ! ((grp_AFE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9F7B
                dc.w $9500 ! ((grp_AFEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8968
                dc.w $9500 ! ((grp_E12A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E12A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E12A0 / 2) >> 16)
                dc.w 1
