byte_2EB37C:    dc.b   0,  4,$75,$6D,$8C,$8A,$7E,$73,$7F,$73
                                        ; DATA XREF: ROM:off_2000   o
                dc.w sprite_32_32
                dc.w $706A
                dc.w $9500 ! ((grp_2A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2A600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $755A
                dc.w $9500 ! ((grp_87580 / 2) & $00FF)
                dc.w $9600 ! (((grp_87580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87580 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6D5A
                dc.w $9500 ! ((grp_EF4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF4A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F8A
                dc.w $9500 ! ((grp_EF460 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $878A
                dc.w $9500 ! ((grp_EF480 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF480 / 2) >> 16)
                dc.w 1
