byte_2D0772:    dc.b   0,  2,$6F,$78,$8F,$86,$80,$81,$2A,$33
                                        ; DATA XREF: ROM:off_D7C   o
                dc.w sprite_16_16
                dc.w $7276
                dc.w $9500 ! ((grp_75D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_75D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8279
                dc.w $9500 ! ((grp_75E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_75E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6A77
                dc.w $9500 ! ((grp_E35A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E35A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E35A0 / 2) >> 16)
                dc.w 1
