byte_2CC6F2:    dc.b   0,  2,$70,$71,$8A,$80,$7F,$76,$80,$76
                                        ; DATA XREF: ROM:off_7AC   o
                dc.w sprite_24_16
                dc.w $756F
                dc.w $9500 ! ((grp_155F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_155F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_155F80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6D75
                dc.w $9500 ! ((grp_E1400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $807F
                dc.w $9500 ! ((grp_E1420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1420 / 2) >> 16)
                dc.w 1
