byte_2EB258:    dc.b   0,  6,$74,$73,$8E,$8C,$80,$77,$81,$77
                                        ; DATA XREF: ROM:off_1FF0   o
                dc.w sprite_16_16
                dc.w $8173
                dc.w $9500 ! ((grp_87500 / 2) & $00FF)
                dc.w $9600 ! (((grp_87500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7973
                dc.w $9500 ! ((grp_AA380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AA380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AA380 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $705B
                dc.w $9500 ! ((grp_18BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18BE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D63
                dc.w $9500 ! ((grp_D7900 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7900 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F6B
                dc.w $9500 ! ((grp_D7940 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7184
                dc.w $9500 ! ((grp_BE0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8183
                dc.w $9500 ! ((grp_EF420 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF420 / 2) >> 16)
                dc.w 1
