byte_2DCD24:    dc.b   0,  9,$6F,$52,$8E,$8F,$7E,$6B,$82,$57
                                        ; DATA XREF: ROM:off_1670   o
                dc.w sprite_24_32
                dc.w $764F
                dc.w $9500 ! ((grp_10C840 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C840 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6445
                dc.w $9500 ! ((grp_85300 / 2) & $00FF)
                dc.w $9600 ! (((grp_85300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6F84
                dc.w $9500 ! ((grp_85380 / 2) & $00FF)
                dc.w $9600 ! (((grp_85380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $806F
                dc.w $9500 ! ((grp_85400 / 2) & $00FF)
                dc.w $9600 ! (((grp_85400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $786F
                dc.w $9500 ! ((grp_A8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8E47
                dc.w $9500 ! ((grp_199EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_199EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199EA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6E55
                dc.w $9500 ! ((grp_BBB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C47
                dc.w $9500 ! ((grp_ED980 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E6C
                dc.w $9500 ! ((grp_ED7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED7A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $964A
                dc.w $9500 ! ((grp_ED9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED9A0 / 2) >> 16)
                dc.w 1
