byte_2CE8E0:    dc.b   0,  9,$7D,  2,$90,$A0,$86,$51,$87,$51
                                        ; DATA XREF: ROM:off_AF8   o
                dc.w sprite_16_16
                dc.w $7B94
                dc.w $9500 ! ((grp_74480 / 2) & $00FF)
                dc.w $9600 ! (((grp_74480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8338
                dc.w $9500 ! ((grp_A2B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A6D
                dc.w $9500 ! ((grp_A2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8B10
                dc.w $9500 ! ((grp_A2C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B7C
                dc.w $9500 ! ((grp_1926A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1926A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1926A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8458
                dc.w $9500 ! ((grp_192700 / 2) & $00FF)
                dc.w $9600 ! (((grp_192700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192700 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8A00
                dc.w $9500 ! ((grp_B1280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8B8D
                dc.w $9500 ! ((grp_B12C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B12C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B12C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8200
                dc.w $9500 ! ((grp_E2760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8730
                dc.w $9500 ! ((grp_E2780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2780 / 2) >> 16)
                dc.w 1
