byte_2FF2D4:    dc.b   0,  5,$1D,$75,$9B,$90,$5A,$7E,$5B,$7E
                                        ; DATA XREF: ROM:off_3568   o
                dc.w sprite_32_16
                dc.w $5C76
                dc.w $9500 ! ((grp_5A700 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A700 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7C76
                dc.w $9500 ! ((grp_5A600 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A600 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $3C7A
                dc.w $9500 ! ((grp_A1C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $247C
                dc.w $9500 ! ((grp_191860 / 2) & $00FF)
                dc.w $9600 ! (((grp_191860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $1C77
                dc.w $9500 ! ((grp_C63C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C63C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C63C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $147E
                dc.w $9500 ! ((grp_F91A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F91A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F91A0 / 2) >> 16)
                dc.w 1
