byte_2D106C:    dc.b   0, $B,$49,$62,$7E,$8D,$5E,$75,$5F,$75
                                        ; DATA XREF: ROM:off_DE8   o
                dc.w sprite_32_32
                dc.w $7061
                dc.w $9500 ! ((grp_14C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $9058
                dc.w $9500 ! ((grp_14E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $6E81
                dc.w $9500 ! ((grp_157CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_157CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157CC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5F78
                dc.w $9500 ! ((grp_76280 / 2) & $00FF)
                dc.w $9600 ! (((grp_76280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76280 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9F80
                dc.w $9500 ! ((grp_76300 / 2) & $00FF)
                dc.w $9600 ! (((grp_76300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $B06A
                dc.w $9500 ! ((grp_76380 / 2) & $00FF)
                dc.w $9600 ! (((grp_76380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76380 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $9078
                dc.w $9500 ! ((grp_97580 / 2) & $00FF)
                dc.w $9600 ! (((grp_97580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97580 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9750
                dc.w $9500 ! ((grp_184240 / 2) & $00FF)
                dc.w $9600 ! (((grp_184240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184240 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8059
                dc.w $9500 ! ((grp_C9140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6689
                dc.w $9500 ! ((grp_E3800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A290
                dc.w $9500 ! ((grp_E3820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A448
                dc.w $9500 ! ((grp_E3840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3840 / 2) >> 16)
                dc.w 1
