byte_2CF464:    dc.b   0,  7,$5F,$6E,$94,$95,$7F,$78,$80,$78
                                        ; DATA XREF: ROM:off_B60   o
                dc.w sprite_32_32
                dc.w $657A
                dc.w $9500 ! ((grp_13A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_13A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $655A
                dc.w $9500 ! ((grp_13C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $855C
                dc.w $9500 ! ((grp_5C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_5C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5C600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $857C
                dc.w $9500 ! ((grp_170500 / 2) & $00FF)
                dc.w $9600 ! (((grp_170500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_170500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9580
                dc.w $9500 ! ((grp_74C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_74C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_74C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5D74
                dc.w $9500 ! ((grp_A3400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9568
                dc.w $9500 ! ((grp_1929A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1929A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1929A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $5D67
                dc.w $9500 ! ((grp_E2BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2BE0 / 2) >> 16)
                dc.w 1
