byte_2DE5E6:    dc.b   0,  8,$6C,$67,$8E,$8E,$7F,$76,$83,$67
                                        ; DATA XREF: ROM:off_1774   o
                dc.w sprite_24_24
                dc.w $6F7A
                dc.w $9500 ! ((grp_147E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_147E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_147E20 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6F6A
                dc.w $9500 ! ((grp_4FC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $795A
                dc.w $9500 ! ((grp_84A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8F6A
                dc.w $9500 ! ((grp_A8000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8000 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $676F
                dc.w $9500 ! ((grp_199B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_199B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8782
                dc.w $9500 ! ((grp_BB840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $715A
                dc.w $9500 ! ((grp_ED580 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8A
                dc.w $9500 ! ((grp_ED5A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED5A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED5A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9780
                dc.w $9500 ! ((grp_ED5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED5C0 / 2) >> 16)
                dc.w 1
