byte_2E0862:    dc.b   0,  4,$6B,$55,$94,$87,$7F,$6E,$8F,$60
                                        ; DATA XREF: ROM:off_18E4   o
                dc.w sprite_32_32
                dc.w $776A
                dc.w $9500 ! ((grp_22800 / 2) & $00FF)
                dc.w $9600 ! (((grp_22800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $6769
                dc.w $9500 ! ((grp_64500 / 2) & $00FF)
                dc.w $9600 ! (((grp_64500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7B5A
                dc.w $9500 ! ((grp_1600C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1600C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1600C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $8352
                dc.w $9500 ! ((grp_D2CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7362
                dc.w $9500 ! ((grp_EBC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBC40 / 2) >> 16)
                dc.w 1
