byte_2FD39C:    dc.b   0,  6,$6E,$50,$8E,$8D,$7E,$6E,$7F,$6E
                                        ; DATA XREF: ROM:off_32E0   o
                dc.w sprite_16_32
                dc.w $6C50
                dc.w $9500 ! ((grp_70A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_70A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_70A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $6E70
                dc.w $9500 ! ((grp_181B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_181B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8456
                dc.w $9500 ! ((grp_181C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_181C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_181C00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7288
                dc.w $9500 ! ((grp_190FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_190FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7A4E
                dc.w $9500 ! ((grp_190F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_190F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7E80
                dc.w $9500 ! ((grp_F82E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F82E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F82E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $856E
                dc.w $9500 ! ((grp_F8300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8300 / 2) >> 16)
                dc.w 1
