byte_2E4B68:    dc.b   0,  4,$70,$6B,$93,$8F,$81,$7D,$76,$73
                                        ; DATA XREF: ROM:off_1B70   o
                dc.w sprite_16_32
                dc.w $7569
                dc.w $9500 ! ((grp_65A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_65A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8572
                dc.w $9500 ! ((grp_A8180 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6D71
                dc.w $9500 ! ((grp_199C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_199C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199C60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7589
                dc.w $9500 ! ((grp_D53C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D53C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D53C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D81
                dc.w $9500 ! ((grp_BBA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBA00 / 2) >> 16)
                dc.w 2
