byte_2F468A:    dc.b   0,  1,$7C,$76,$86,$8A,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_29A4   o
                dc.w sprite_8_24
                dc.w $7975
                dc.w $9500 ! ((grp_19E160 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8174
                dc.w $9500 ! ((grp_19E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E100 / 2) >> 16)
                dc.w 3
