byte_2FC296:    dc.b   0,  1,$69,$8A,$75,$96,$6F,$90,$70,$90
                                        ; DATA XREF: ROM:off_30D4   o
                dc.w sprite_16_16
                dc.w $6A88
                dc.w $9500 ! ((grp_92D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_92D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6291
                dc.w $9500 ! ((grp_F7DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7DC0 / 2) >> 16)
                dc.w 1
