byte_2D008A:    dc.b   0,  1,$7A,$7C,$87,$8C,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_CC4   o
                dc.w sprite_24_24
                dc.w $787C
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7974
                dc.w $9500 ! ((grp_C8B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B00 / 2) >> 16)
                dc.w 2
