byte_2D76C2:    dc.b   0,  5,$77,$65,$8F,$99,$85,$77,$7D,$67
                                        ; DATA XREF: ROM:off_12F4   o
                dc.w sprite_24_32
                dc.w $796E
                dc.w $9500 ! ((grp_FFC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FFC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FFC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $745E
                dc.w $9500 ! ((grp_78F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7181
                dc.w $9500 ! ((grp_B3E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $917A
                dc.w $9500 ! ((grp_B3E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $798E
                dc.w $9500 ! ((grp_E65E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E65E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E65E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $997E
                dc.w $9500 ! ((grp_E6600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6600 / 2) >> 16)
                dc.w 1
