byte_2EABC6:    dc.b   0,  1,$77,$6E,$88,$91,$7E,$7F,$7F,$7F
                                        ; DATA XREF: ROM:off_1F94   o
                dc.w sprite_24_32
                dc.w $7374
                dc.w $9500 ! ((grp_10FCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10FCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10FCC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $7B6C
                dc.w $9500 ! ((grp_D75C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D75C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D75C0 / 2) >> 16)
                dc.w 2
