byte_2CD4BE:    dc.b   0,  1,$9B,$69,$A9,$77,$8E,$92,$8F,$92
                                        ; DATA XREF: ROM:off_8C4   o
                dc.w sprite_24_16
                dc.w $9968
                dc.w $9500 ! ((grp_1567C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1567C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1567C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $A178
                dc.w $9500 ! ((grp_E1CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1CE0 / 2) >> 16)
                dc.w 1
