byte_2FA12A:    dc.b   0,  9,$6D,$6E,$89,$8E,$7D,$74,$7E,$74
                                        ; DATA XREF: ROM:off_2DEC   o
                dc.w sprite_32_32
                dc.w $6E61
                dc.w $9500 ! ((grp_41800 / 2) & $00FF)
                dc.w $9600 ! (((grp_41800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41800 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6981
                dc.w $9500 ! ((grp_57900 / 2) & $00FF)
                dc.w $9600 ! (((grp_57900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5E69
                dc.w $9500 ! ((grp_180700 / 2) & $00FF)
                dc.w $9600 ! (((grp_180700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8980
                dc.w $9500 ! ((grp_91600 / 2) & $00FF)
                dc.w $9600 ! (((grp_91600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9669
                dc.w $9500 ! ((grp_19FA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FA20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6759
                dc.w $9500 ! ((grp_DEB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F59
                dc.w $9500 ! ((grp_DEBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEBC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $566E
                dc.w $9500 ! ((grp_C4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E65
                dc.w $9500 ! ((grp_C47C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C47C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C47C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E6E
                dc.w $9500 ! ((grp_C4840 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4840 / 2) >> 16)
                dc.w 2
