byte_2F7136:    dc.b   0, $F,$7B,$4D,$A6,$82,$87,$74,$88,$74
                                        ; DATA XREF: ROM:off_2B7C   o
                dc.w sprite_32_32
                dc.w $A721
                dc.w $9500 ! ((grp_3E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3E400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $764B
                dc.w $9500 ! ((grp_1174C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1174C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1174C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $A741
                dc.w $9500 ! ((grp_56C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8E4B
                dc.w $9500 ! ((grp_6E300 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $C724
                dc.w $9500 ! ((grp_6E800 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $866B
                dc.w $9500 ! ((grp_17EB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EB40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $9E51
                dc.w $9500 ! ((grp_17EA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17EA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17EA80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7776
                dc.w $9500 ! ((grp_8F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $C744
                dc.w $9500 ! ((grp_8FE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $AE51
                dc.w $9500 ! ((grp_DD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $B361
                dc.w $9500 ! ((grp_DD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $966B
                dc.w $9500 ! ((grp_C24C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C24C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C24C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F7B
                dc.w $9500 ! ((grp_F4CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F43
                dc.w $9500 ! ((grp_F4C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C356
                dc.w $9500 ! ((grp_F55E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F55E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F55E0 / 2) >> 16)
                dc.w 1
