byte_2FCF34:    dc.b   0,  1,$7D,$65,$9A,$6F,$8B,$6A,$8C,$6A
                                        ; DATA XREF: ROM:off_3268   o
                dc.w sprite_32_16
                dc.w $7B63
                dc.w $9500 ! ((grp_59300 / 2) & $00FF)
                dc.w $9600 ! (((grp_59300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59300 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $9B63
                dc.w $9500 ! ((grp_F80A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F80A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F80A0 / 2) >> 16)
                dc.w 1
