byte_2DCEFC:    dc.b   0,  6,$6F,$61,$8E,$8F,$78,$74,$74,$62
                                        ; DATA XREF: ROM:off_1680   o
                dc.w sprite_24_32
                dc.w $6661
                dc.w $9500 ! ((grp_1045C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1045C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1045C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7E61
                dc.w $9500 ! ((grp_175000 / 2) & $00FF)
                dc.w $9600 ! (((grp_175000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175000 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $7E79
                dc.w $9500 ! ((grp_1750C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1750C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1750C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6E81
                dc.w $9500 ! ((grp_7D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6459
                dc.w $9500 ! ((grp_187300 / 2) & $00FF)
                dc.w $9600 ! (((grp_187300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187300 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5E70
                dc.w $9500 ! ((grp_B7000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8159
                dc.w $9500 ! ((grp_E9520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9520 / 2) >> 16)
                dc.w 1
