byte_2D047A:    dc.b   0,  1,$76,$79,$8F,$88,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_D24   o
                dc.w sprite_24_24
                dc.w $7577
                dc.w $9500 ! ((grp_13EBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13EBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13EBE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $8D81
                dc.w $9500 ! ((grp_E33A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E33A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E33A0 / 2) >> 16)
                dc.w 1
