byte_2EFD8C:    dc.b   0, $C,$44,$15,$BC,$5A,$80,$71,$81,$71
                                        ; DATA XREF: ROM:off_25A0   o
                dc.w sprite_32_24
                dc.w $794B
                dc.w $9500 ! ((grp_1336C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1336C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1336C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $4143
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9943
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $856B
                dc.w $9500 ! ((grp_6B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6143
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8A8B
                dc.w $9500 ! ((grp_8B180 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7943
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7863
                dc.w $9500 ! ((grp_18DB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DB40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7143
                dc.w $9500 ! ((grp_BF9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $B943
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7153
                dc.w $9500 ! ((grp_F14A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F14A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F14A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D71
                dc.w $9500 ! ((grp_F14C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F14C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F14C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B9B
                dc.w $9500 ! ((grp_F14E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F14E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F14E0 / 2) >> 16)
                dc.w 1
