byte_2D4526:    dc.b   0,  2,$59,$62,$AB,$8C,$8C,$78,$8D,$78
                                        ; DATA XREF: ROM:off_10D4   o
                dc.w sprite_32_24
                dc.w $8170
                dc.w $9500 ! ((grp_1234C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1234C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1234C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_16
                dc.w $7671
                dc.w $9500 ! ((grp_B3440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A176
                dc.w $9500 ! ((grp_E5840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5840 / 2) >> 16)
                dc.w 1
