byte_2F1178:    dc.b   0,  6,$6C,$54,$9F,$81,$82,$6A,$83,$6A
                                        ; DATA XREF: ROM:off_2630   o
                dc.w sprite_32_32
                dc.w $7B4F
                dc.w $9500 ! ((grp_38600 / 2) & $00FF)
                dc.w $9600 ! (((grp_38600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7B6F
                dc.w $9500 ! ((grp_134EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_134EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6367
                dc.w $9500 ! ((grp_14EA20 / 2) & $00FF)
                dc.w $9600 ! (((grp_14EA20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14EA20 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $9B4F
                dc.w $9500 ! ((grp_AC380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9B6F
                dc.w $9500 ! ((grp_19D7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D7A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $637F
                dc.w $9500 ! ((grp_DB1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6B5F
                dc.w $9500 ! ((grp_DB200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB200 / 2) >> 16)
                dc.w 2
