byte_2F83AC:    dc.b   0,  4,$74,$7A,$92,$96,$83,$88,$84,$88
                                        ; DATA XREF: ROM:off_2C70   o
                dc.w sprite_8_32
                dc.w $7F78
                dc.w $9500 ! ((grp_AE300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $877A
                dc.w $9500 ! ((grp_AE380 / 2) & $00FF)
                dc.w $9600 ! (((grp_AE380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AE380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7778
                dc.w $9500 ! ((grp_19F300 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F300 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6F79
                dc.w $9500 ! ((grp_C3780 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F8A
                dc.w $9500 ! ((grp_C37C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C37C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C37C0 / 2) >> 16)
                dc.w 2
