byte_2E6B2E:    dc.b   0, $B,$6F,$63,$89,$8D,$7C,$71,$79,$63
                                        ; DATA XREF: ROM:off_1C7C   o
                dc.w sprite_24_32
                dc.w $7161
                dc.w $9500 ! ((grp_10A440 / 2) & $00FF)
                dc.w $9600 ! (((grp_10A440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10A440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7481
                dc.w $9500 ! ((grp_83780 / 2) & $00FF)
                dc.w $9600 ! (((grp_83780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8965
                dc.w $9500 ! ((grp_83800 / 2) & $00FF)
                dc.w $9600 ! (((grp_83800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83800 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5963
                dc.w $9500 ! ((grp_189CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $615B
                dc.w $9500 ! ((grp_D3F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8489
                dc.w $9500 ! ((grp_D3F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8556
                dc.w $9500 ! ((grp_D3F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9162
                dc.w $9500 ! ((grp_D3FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $696B
                dc.w $9500 ! ((grp_ECA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECA40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C87
                dc.w $9500 ! ((grp_ECA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECA60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7559
                dc.w $9500 ! ((grp_ECA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECA80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $874E
                dc.w $9500 ! ((grp_ECAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECAA0 / 2) >> 16)
                dc.w 1
