byte_2CE73A:    dc.b   0,  7,$76,  2,$85,$7F,$7D,$40,$7E,$40
                                        ; DATA XREF: ROM:off_AE4   o
                dc.w sprite_8_32
                dc.w $7400
                dc.w $9500 ! ((grp_A2700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $803A
                dc.w $9500 ! ((grp_A2780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7C5A
                dc.w $9500 ! ((grp_192460 / 2) & $00FF)
                dc.w $9600 ! (((grp_192460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192460 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7520
                dc.w $9500 ! ((grp_B1000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7C72
                dc.w $9500 ! ((grp_B1040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D2A
                dc.w $9500 ! ((grp_B1080 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C00
                dc.w $9500 ! ((grp_E26A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E26A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E26A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $845A
                dc.w $9500 ! ((grp_E26C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E26C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E26C0 / 2) >> 16)
                dc.w 1
