byte_2F78CE:    dc.b   0,$10,$64,$42,$9E,$83,$86,$5F,$87,$5F
                                        ; DATA XREF: ROM:off_2BAC   o
                dc.w sprite_32_32
                dc.w $815A
                dc.w $9500 ! ((grp_3FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3FE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $813A
                dc.w $9500 ! ((grp_40000 / 2) & $00FF)
                dc.w $9600 ! (((grp_40000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_40000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $695A
                dc.w $9500 ! ((grp_118FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_118FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $693A
                dc.w $9500 ! ((grp_119140 / 2) & $00FF)
                dc.w $9600 ! (((grp_119140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_119140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $5942
                dc.w $9500 ! ((grp_6EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6EB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $A952
                dc.w $9500 ! ((grp_6EC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6EC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6EC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5962
                dc.w $9500 ! ((grp_17F980 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F980 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $707A
                dc.w $9500 ! ((grp_9F880 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F880 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $A942
                dc.w $9500 ! ((grp_9F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_9F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9F900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $494A
                dc.w $9500 ! ((grp_ADE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $A142
                dc.w $9500 ! ((grp_ADE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $A94A
                dc.w $9500 ! ((grp_18F520 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5156
                dc.w $9500 ! ((grp_19F1E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F1E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F1E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7682
                dc.w $9500 ! ((grp_DDA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $BB3A
                dc.w $9500 ! ((grp_DDA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DDA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DDA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $4149
                dc.w $9500 ! ((grp_C3300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A162
                dc.w $9500 ! ((grp_C3340 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3340 / 2) >> 16)
                dc.w 2
