byte_2E3306:    dc.b   0,  6,$70,$64,$80,$6D,$79,$74,$7B,$75
                                        ; DATA XREF: ROM:off_1A9C   o
                dc.w sprite_24_32
                dc.w $7368
                dc.w $9500 ! ((grp_104D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_104D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_104D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7088
                dc.w $9500 ! ((grp_7E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8B6F
                dc.w $9500 ! ((grp_7E780 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8088
                dc.w $9500 ! ((grp_187B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_187B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187B40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5C55
                dc.w $9500 ! ((grp_B7740 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $645A
                dc.w $9500 ! ((grp_B7780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B61
                dc.w $9500 ! ((grp_B77C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B77C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B77C0 / 2) >> 16)
                dc.w 2
