byte_2D59AE:    dc.b   0,  5,$6E,$65,$8E,$8F,$79,$76,$6F,$69
                                        ; DATA XREF: ROM:off_11C4   o
                dc.w sprite_24_32
                dc.w $6A60
                dc.w $9500 ! ((grp_FF1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $5A60
                dc.w $9500 ! ((grp_78780 / 2) & $00FF)
                dc.w $9600 ! (((grp_78780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A88
                dc.w $9500 ! ((grp_185380 / 2) & $00FF)
                dc.w $9600 ! (((grp_185380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185380 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7480
                dc.w $9500 ! ((grp_1853E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1853E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1853E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8788
                dc.w $9500 ! ((grp_CBC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7458
                dc.w $9500 ! ((grp_E6260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6260 / 2) >> 16)
                dc.w 1
