byte_2D07A0:    dc.b   0,  2,$72,$7A,$8E,$89,$80,$81,$28,$33
                                        ; DATA XREF: ROM:off_D80   o
                dc.w sprite_32_8
                dc.w $7180
                dc.w $9500 ! ((grp_97480 / 2) & $00FF)
                dc.w $9600 ! (((grp_97480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7678
                dc.w $9500 ! ((grp_C8DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8388
                dc.w $9500 ! ((grp_E3520 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3520 / 2) >> 16)
                dc.w 1
