byte_2E3DEC:    dc.b   0, $B,$6B,$82,$9E,$A5,$AD,$47,$AD,$42
                                        ; DATA XREF: ROM:off_1B08   o
                dc.w sprite_24_24
                dc.w $6394
                dc.w $9500 ! ((grp_143740 / 2) & $00FF)
                dc.w $9600 ! (((grp_143740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143740 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7B92
                dc.w $9500 ! ((grp_15C640 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $927C
                dc.w $9500 ! ((grp_174280 / 2) & $00FF)
                dc.w $9600 ! (((grp_174280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174280 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $508D
                dc.w $9500 ! ((grp_186400 / 2) & $00FF)
                dc.w $9600 ! (((grp_186400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186400 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9274
                dc.w $9500 ! ((grp_CDA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDA00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A23D
                dc.w $9500 ! ((grp_CDA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A345
                dc.w $9500 ! ((grp_CDA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CDA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CDA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8A82
                dc.w $9500 ! ((grp_B5980 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E64
                dc.w $9500 ! ((grp_B5900 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A64D
                dc.w $9500 ! ((grp_B5940 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5940 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9394
                dc.w $9500 ! ((grp_E81C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E81C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E81C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A25C
                dc.w $9500 ! ((grp_E81E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E81E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E81E0 / 2) >> 16)
                dc.w 1
