byte_2D566A:    dc.b   0,  7,$6F,$5C,$8E,$8F,$73,$6F,$6E,$67
                                        ; DATA XREF: ROM:off_11A4   o
                dc.w sprite_16_32
                dc.w $7269
                dc.w $9500 ! ((grp_62500 / 2) & $00FF)
                dc.w $9600 ! (((grp_62500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7151
                dc.w $9500 ! ((grp_1759C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1759C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1759C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6A61
                dc.w $9500 ! ((grp_A6000 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B89
                dc.w $9500 ! ((grp_D0140 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8889
                dc.w $9500 ! ((grp_D0180 / 2) & $00FF)
                dc.w $9600 ! (((grp_D0180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D0180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6264
                dc.w $9500 ! ((grp_B7400 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8279
                dc.w $9500 ! ((grp_B7440 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A81
                dc.w $9500 ! ((grp_E9A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9A40 / 2) >> 16)
                dc.w 1
