byte_2DAFA4:    dc.b   0,  9,$63,$60,$A1,$8E,$82,$77,$83,$77
                                        ; DATA XREF: ROM:off_1528   o
                dc.w sprite_24_24
                dc.w $7163
                dc.w $9500 ! ((grp_148720 / 2) & $00FF)
                dc.w $9600 ! (((grp_148720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148720 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6163
                dc.w $9500 ! ((grp_85600 / 2) & $00FF)
                dc.w $9600 ! (((grp_85600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85600 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7382
                dc.w $9500 ! ((grp_9B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $9160
                dc.w $9500 ! ((grp_18A780 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A780 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8A
                dc.w $9500 ! ((grp_D59C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D59C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D59C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B7A
                dc.w $9500 ! ((grp_D5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $878A
                dc.w $9500 ! ((grp_D5A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $895F
                dc.w $9500 ! ((grp_BBF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6373
                dc.w $9500 ! ((grp_EDB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDB80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9658
                dc.w $9500 ! ((grp_EDBA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDBA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDBA0 / 2) >> 16)
                dc.w 1
