byte_2F070A:    dc.b   0, $D,$5F,$59,$9A,$96,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_25F4   o
                dc.w sprite_32_32
                dc.w $6D4B
                dc.w $9500 ! ((grp_34A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D7B
                dc.w $9500 ! ((grp_34C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5D5B
                dc.w $9500 ! ((grp_112CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_112CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $5D7B
                dc.w $9500 ! ((grp_112E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_112E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $8D4B
                dc.w $9500 ! ((grp_112FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_112FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_166480 / 2) & $00FF)
                dc.w $9600 ! (((grp_166480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166480 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9D7B
                dc.w $9500 ! ((grp_ABE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7D6B
                dc.w $9500 ! ((grp_BFD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6553
                dc.w $9500 ! ((grp_F1660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1680 / 2) >> 16)
                dc.w 1
submarine:      dc.b   0, $F,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_25F8   o
                dc.w sprite_32_32
                dc.w $6D4B
                dc.w $9500 ! ((grp_34A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D7B
                dc.w $9500 ! ((grp_34C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_34C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_34C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5D7B
                dc.w $9500 ! ((grp_112E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_112E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_112E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6563
                dc.w $9500 ! ((grp_14D280 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D280 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_32
                dc.w $8D4B
                dc.w $9500 ! ((grp_6B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B600 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $8D6B
                dc.w $9500 ! ((grp_166480 / 2) & $00FF)
                dc.w $9600 ! (((grp_166480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166480 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5D5B
                dc.w $9500 ! ((grp_ABE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9D7B
                dc.w $9500 ! ((grp_ABE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6553
                dc.w $9500 ! ((grp_BFD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D6B
                dc.w $9500 ! ((grp_BFD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D5B
                dc.w $9500 ! ((grp_BFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFDC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1680 / 2) >> 16)
                dc.w 1
