byte_2D5E50:    dc.b   0,  6,$73,$5E,$8C,$9E,$87,$7F,$80,$6F
                                        ; DATA XREF: ROM:off_11F8   o
                dc.w sprite_24_32
                dc.w $7085
                dc.w $9500 ! ((grp_FF640 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF640 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7175
                dc.w $9500 ! ((grp_49B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_49B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $9175
                dc.w $9500 ! ((grp_78C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_78C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7C5D
                dc.w $9500 ! ((grp_1949E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1949E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1949E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $846A
                dc.w $9500 ! ((grp_E6460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $889B
                dc.w $9500 ! ((grp_E6480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $946D
                dc.w $9500 ! ((grp_E64A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E64A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E64A0 / 2) >> 16)
                dc.w 1
