byte_2F2914:    dc.b   0, $E,$52,$6A,$A3,$9A,$7B,$7F,$7C,$7F
                                        ; DATA XREF: ROM:off_2740   o
                dc.w sprite_32_32
                dc.w $7F71
                dc.w $9500 ! ((grp_39200 / 2) & $00FF)
                dc.w $9600 ! (((grp_39200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6267
                dc.w $9500 ! ((grp_55000 / 2) & $00FF)
                dc.w $9600 ! (((grp_55000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55000 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $477A
                dc.w $9500 ! ((grp_1672C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1672C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1672C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6F77
                dc.w $9500 ! ((grp_17D7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17D7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17D7C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9C99
                dc.w $9500 ! ((grp_8C980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9F6A
                dc.w $9500 ! ((grp_8CA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8C91
                dc.w $9500 ! ((grp_18E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E200 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5272
                dc.w $9500 ! ((grp_DB5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $5F82
                dc.w $9500 ! ((grp_DB600 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7659
                dc.w $9500 ! ((grp_DB640 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A5A
                dc.w $9500 ! ((grp_F2760 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $625F
                dc.w $9500 ! ((grp_F2740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $765F
                dc.w $9500 ! ((grp_F2780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F7A
                dc.w $9500 ! ((grp_F27A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F27A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F27A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AA6A
                dc.w $9500 ! ((grp_F27C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F27C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F27C0 / 2) >> 16)
                dc.w 1
