byte_2D22DE:    dc.b   0,  3,$72,$A7,$8E,$B5,$8B,$AD,$8C,$AD
                                        ; DATA XREF: ROM:off_EB4   o
                dc.w sprite_24_8
                dc.w $73A6
                dc.w $9500 ! ((grp_1844E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1844E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1844E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6FAB
                dc.w $9500 ! ((grp_B2580 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8BAA
                dc.w $9500 ! ((grp_B2540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $93B0
                dc.w $9500 ! ((grp_E41E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E41E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E41E0 / 2) >> 16)
                dc.w 1
