byte_2DCC08:    dc.b   0,  9,$6F,$58,$8E,$8F,$7F,$6D,$85,$5B
                                        ; DATA XREF: ROM:off_1668   o
                dc.w sprite_24_24
                dc.w $7A51
                dc.w $9500 ! ((grp_148180 / 2) & $00FF)
                dc.w $9600 ! (((grp_148180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_148180 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $6F74
                dc.w $9500 ! ((grp_179080 / 2) & $00FF)
                dc.w $9600 ! (((grp_179080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6253
                dc.w $9500 ! ((grp_85100 / 2) & $00FF)
                dc.w $9600 ! (((grp_85100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A69
                dc.w $9500 ! ((grp_85180 / 2) & $00FF)
                dc.w $9600 ! (((grp_85180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_85180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7253
                dc.w $9500 ! ((grp_A8400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A8400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A8400 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8579
                dc.w $9500 ! ((grp_D5500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9252
                dc.w $9500 ! ((grp_D5540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5A55
                dc.w $9500 ! ((grp_ED8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED8A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B71
                dc.w $9500 ! ((grp_ED8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED8C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $925A
                dc.w $9500 ! ((grp_ED8E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED8E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED8E0 / 2) >> 16)
                dc.w 1
