byte_2E0C32:    dc.b   0, $F,$72,$5A,$8E,$8E,$79,$48,$76,$32
                                        ; DATA XREF: ROM:off_190C   o
                dc.w sprite_24_16
                dc.w $8D4E
                dc.w $9500 ! ((grp_15BBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5342
                dc.w $9500 ! ((grp_7AF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6D59
                dc.w $9500 ! ((grp_7AE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7540
                dc.w $9500 ! ((grp_7AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $952E
                dc.w $9500 ! ((grp_7AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8538
                dc.w $9500 ! ((grp_A5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6531
                dc.w $9500 ! ((grp_195940 / 2) & $00FF)
                dc.w $9600 ! (((grp_195940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195940 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $6D31
                dc.w $9500 ! ((grp_1958E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1958E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1958E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7D50
                dc.w $9500 ! ((grp_B5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8D30
                dc.w $9500 ! ((grp_B5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $655F
                dc.w $9500 ! ((grp_E7AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7538
                dc.w $9500 ! ((grp_E7BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D38
                dc.w $9500 ! ((grp_E7BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D30
                dc.w $9500 ! ((grp_E7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D28
                dc.w $9500 ! ((grp_E7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A5E
                dc.w $9500 ! ((grp_E5860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5860 / 2) >> 16)
                dc.w 1
