byte_2DDE94:    dc.b   0,  5,$76,$5F,$8B,$8E,$80,$73,$82,$60
                                        ; DATA XREF: ROM:off_1730   o
                dc.w sprite_32_32
                dc.w $7256
                dc.w $9500 ! ((grp_25A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_25A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_25A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $7782
                dc.w $9500 ! ((grp_4F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7B76
                dc.w $9500 ! ((grp_84680 / 2) & $00FF)
                dc.w $9600 ! (((grp_84680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6A5E
                dc.w $9500 ! ((grp_197E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_197E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_197E00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8A
                dc.w $9500 ! ((grp_D4E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $925D
                dc.w $9500 ! ((grp_B8C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8C00 / 2) >> 16)
                dc.w 2
