byte_2EC1EE:    dc.b   0,  2,$71,$6D,$93,$8F,$82,$7E,$83,$7E
                                        ; DATA XREF: ROM:off_20BC   o
                dc.w sprite_32_32
                dc.w $6F6B
                dc.w $9500 ! ((grp_2F600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2F600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2F600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $718B
                dc.w $9500 ! ((grp_9D400 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8F6B
                dc.w $9500 ! ((grp_AAB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AAB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AAB00 / 2) >> 16)
                dc.w 4
