byte_2E00B8:    dc.b   0,  4,$6C,$61,$98,$8D,$82,$77,$7E,$67
                                        ; DATA XREF: ROM:off_1890   o
                dc.w sprite_24_32
                dc.w $8570
                dc.w $9500 ! ((grp_108DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_108DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_108DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $6D60
                dc.w $9500 ! ((grp_146440 / 2) & $00FF)
                dc.w $9600 ! (((grp_146440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146440 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $6D78
                dc.w $9500 ! ((grp_146560 / 2) & $00FF)
                dc.w $9600 ! (((grp_146560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146560 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $656D
                dc.w $9500 ! ((grp_B9640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7558
                dc.w $9500 ! ((grp_EB900 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB900 / 2) >> 16)
                dc.w 1
