byte_2D9BDA:    dc.b   0,  6,$86,$67,$8F,$77,$80,$6D,$88,$60
                                        ; DATA XREF: ROM:off_146C   o
                dc.w sprite_24_32
                dc.w $7976
                dc.w $9500 ! ((grp_1009C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1009C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1009C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $7953
                dc.w $9500 ! ((grp_100B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_100B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_100B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $6A51
                dc.w $9500 ! ((grp_1735C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1735C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1735C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6D6E
                dc.w $9500 ! ((grp_E6E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6E60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718D
                dc.w $9500 ! ((grp_E6EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F8D
                dc.w $9500 ! ((grp_E6F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6F00 / 2) >> 16)
                dc.w 1
