byte_2DAA3E:    dc.b   0,  7,$6D,$76,$8A,$8D,$9E,$7D,$83,$7F
                                        ; DATA XREF: ROM:off_14E4   o
                dc.w sprite_24_16
                dc.w $6B77
                dc.w $9500 ! ((grp_15D6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D6C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $695F
                dc.w $9500 ! ((grp_175540 / 2) & $00FF)
                dc.w $9600 ! (((grp_175540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175540 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6E87
                dc.w $9500 ! ((grp_7D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $837D
                dc.w $9500 ! ((grp_1875A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1875A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1875A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9278
                dc.w $9500 ! ((grp_CFB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $836D
                dc.w $9500 ! ((grp_B7140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $668F
                dc.w $9500 ! ((grp_E9700 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9700 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E8C
                dc.w $9500 ! ((grp_E96E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E96E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E96E0 / 2) >> 16)
                dc.w 1
