byte_2F40C2:    dc.b   0,  3,$77,$74,$8B,$8D,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28D4   o
                dc.w sprite_24_16
                dc.w $757A
                dc.w $9500 ! ((grp_167E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_167E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $758A
                dc.w $9500 ! ((grp_DC100 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D72
                dc.w $9500 ! ((grp_DC140 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D7A
                dc.w $9500 ! ((grp_F3540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3540 / 2) >> 16)
                dc.w 1
