byte_2DF180:    dc.b   0,  6,$75,$5F,$8F,$88,$7F,$75,$8A,$64
                                        ; DATA XREF: ROM:off_17E0   o
                dc.w sprite_32_32
                dc.w $7163
                dc.w $9500 ! ((grp_1A400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $765B
                dc.w $9500 ! ((grp_185C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_185C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185C80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6680
                dc.w $9500 ! ((grp_CD200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9167
                dc.w $9500 ! ((grp_B5040 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6688
                dc.w $9500 ! ((grp_E7760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7760 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $917B
                dc.w $9500 ! ((grp_E7740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7740 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9968
                dc.w $9500 ! ((grp_E7780 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7780 / 2) >> 16)
                dc.w 1
