byte_2D45C8:    dc.b   0,  3,$59,$62,$AB,$8C,$75,$75,$76,$75
                                        ; DATA XREF: ROM:off_10E0   o
                dc.w sprite_24_24
                dc.w $676B
                dc.w $9500 ! ((grp_140C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_140C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_140C80 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $5F6B
                dc.w $9500 ! ((grp_B3380 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3380 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7F6C
                dc.w $9500 ! ((grp_B33C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B33C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B33C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7783
                dc.w $9500 ! ((grp_E57C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E57C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E57C0 / 2) >> 16)
                dc.w 1
