byte_2D0178:    dc.b   0,  1,$7D,$7D,$87,$8F,$82,$86,$83,$86
                                        ; DATA XREF: ROM:off_CE0   o
                dc.w sprite_16_16
                dc.w $7B83
                dc.w $9500 ! ((grp_75980 / 2) & $00FF)
                dc.w $9600 ! (((grp_75980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B7B
                dc.w $9500 ! ((grp_C8B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8B40 / 2) >> 16)
                dc.w 2
