byte_2D0366:    dc.b   0,  2,$70,$6E,$8B,$8D,$7D,$7D,$7E,$7D
                                        ; DATA XREF: ROM:off_D0C   o
                dc.w sprite_24_24
                dc.w $777D
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6D
                dc.w $9500 ! ((grp_46F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $7A65
                dc.w $9500 ! ((grp_E31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E31C0 / 2) >> 16)
                dc.w 1
