byte_2D2F04:    dc.b   0,  4,$68,$70,$94,$91,$77,$80,$78,$80
                                        ; DATA XREF: ROM:off_F40   o
                dc.w sprite_32_32
                dc.w $7068
                dc.w $9500 ! ((grp_17200 / 2) & $00FF)
                dc.w $9600 ! (((grp_17200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7888
                dc.w $9500 ! ((grp_184A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_184A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9064
                dc.w $9500 ! ((grp_193EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_193EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193EA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8160
                dc.w $9500 ! ((grp_E4E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4E00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9084
                dc.w $9500 ! ((grp_E4E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4E20 / 2) >> 16)
                dc.w 1
