byte_2ECFFE:    dc.b   0,  4,$4F,$7C,$B4,$90,$81,$86,$82,$86
                                        ; DATA XREF: ROM:off_2254   o
                dc.w sprite_32_16
                dc.w $4D83
                dc.w $9500 ! ((grp_51D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_51D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_51D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6D83
                dc.w $9500 ! ((grp_164680 / 2) & $00FF)
                dc.w $9600 ! (((grp_164680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164680 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $857F
                dc.w $9500 ! ((grp_164800 / 2) & $00FF)
                dc.w $9600 ! (((grp_164800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164800 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $9D7D
                dc.w $9500 ! ((grp_164740 / 2) & $00FF)
                dc.w $9600 ! (((grp_164740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164740 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $A275
                dc.w $9500 ! ((grp_D8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8680 / 2) >> 16)
                dc.w 2
