byte_2F2152:    dc.b   0, $C,$67,$5F,$B2,$93,$87,$75,$88,$75
                                        ; DATA XREF: ROM:off_26EC   o
                dc.w sprite_32_32
                dc.w $9A6B
                dc.w $9500 ! ((grp_37000 / 2) & $00FF)
                dc.w $9600 ! (((grp_37000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_37000 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5A65
                dc.w $9500 ! ((grp_134440 / 2) & $00FF)
                dc.w $9600 ! (((grp_134440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_134440 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7A5C
                dc.w $9500 ! ((grp_1342C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1342C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1342C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $7A74
                dc.w $9500 ! ((grp_1345C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1345C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1345C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8A8C
                dc.w $9500 ! ((grp_8BF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8BF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8BF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6A5D
                dc.w $9500 ! ((grp_DAC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $718C
                dc.w $9500 ! ((grp_DAC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7D54
                dc.w $9500 ! ((grp_DACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DACC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9A63
                dc.w $9500 ! ((grp_DAC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DAC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DAC00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $526C
                dc.w $9500 ! ((grp_C0300 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $727D
                dc.w $9500 ! ((grp_C0280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $BA74
                dc.w $9500 ! ((grp_C02C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C02C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C02C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A5B
                dc.w $9500 ! ((grp_F1DE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1DE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1DE0 / 2) >> 16)
                dc.w 1
