byte_2FEF1C:    dc.b   0,  4,$6D,$6D,$98,$8A,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:off_3510   o
                dc.w sprite_24_32
                dc.w $786B
                dc.w $9500 ! ((grp_11D640 / 2) & $00FF)
                dc.w $9600 ! (((grp_11D640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11D640 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $7075
                dc.w $9500 ! ((grp_1A1520 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A1520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A1520 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $906B
                dc.w $9500 ! ((grp_1A14C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A14C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A14C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $687D
                dc.w $9500 ! ((grp_C6700 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9873
                dc.w $9500 ! ((grp_F9720 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9720 / 2) >> 16)
                dc.w 1
