byte_2D86EA:    dc.b   0,  5,$63,$5F,$8E,$7A,$81,$71,$83,$6D
                                        ; DATA XREF: ROM:off_13A4   o
                dc.w sprite_32_32
                dc.w $665C
                dc.w $9500 ! ((grp_19800 / 2) & $00FF)
                dc.w $9600 ! (((grp_19800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $8E6F
                dc.w $9500 ! ((grp_185560 / 2) & $00FF)
                dc.w $9600 ! (((grp_185560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185560 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $627C
                dc.w $9500 ! ((grp_CC900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E6D
                dc.w $9500 ! ((grp_B4700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8668
                dc.w $9500 ! ((grp_B46C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B46C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B46C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6584
                dc.w $9500 ! ((grp_E6DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6DC0 / 2) >> 16)
                dc.w 1
