byte_2CD372:    dc.b   0,  3,$86,$7A,$97,$8B,$86,$99,$87,$99
                                        ; DATA XREF: ROM:off_8A4   o
                dc.w sprite_8_16
                dc.w $8880
                dc.w $9500 ! ((grp_B0640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F7B
                dc.w $9500 ! ((grp_B0680 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9472
                dc.w $9500 ! ((grp_B06C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B06C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B06C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8088
                dc.w $9500 ! ((grp_E1D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1D60 / 2) >> 16)
                dc.w 1
