byte_2EBFA2:    dc.b   0,  1,$7B,$5F,$8E,$88,$84,$73,$85,$73
                                        ; DATA XREF: ROM:off_208C   o
                dc.w sprite_24_32
                dc.w $796D
                dc.w $9500 ! ((grp_111340 / 2) & $00FF)
                dc.w $9600 ! (((grp_111340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111340 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $835D
                dc.w $9500 ! ((grp_87D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_87D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87D80 / 2) >> 16)
                dc.w 4
