byte_2EC61C:    dc.b   0,  1,$73,$7D,$8E,$90,$80,$86,$81,$86
                                        ; DATA XREF: ROM:off_2130   o
                dc.w sprite_24_24
                dc.w $717B
                dc.w $9500 ! ((grp_14BAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14BAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14BAE0 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $897C
                dc.w $9500 ! ((grp_BE640 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE640 / 2) >> 16)
                dc.w 2
