byte_2DB684:    dc.b   0,  6,$6F,$5D,$89,$91,$7C,$77,$7D,$77
                                        ; DATA XREF: ROM:off_1560   o
                dc.w sprite_32_24
                dc.w $6C6B
                dc.w $9500 ! ((grp_12DCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12DCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12DCC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_8
                dc.w $6E8A
                dc.w $9500 ! ((grp_D6040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7663
                dc.w $9500 ! ((grp_D6080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7E8B
                dc.w $9500 ! ((grp_D60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D60C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7183
                dc.w $9500 ! ((grp_EDEA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDEA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDEA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $785B
                dc.w $9500 ! ((grp_EDEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDEC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8083
                dc.w $9500 ! ((grp_EDEE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDEE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDEE0 / 2) >> 16)
                dc.w 1
