byte_2EDB94:    dc.b   0,  6,$70,$65,$9E,$95,$87,$7A,$88,$7A
                                        ; DATA XREF: ROM:off_22F8   o
                dc.w sprite_16_32
                dc.w $7070
                dc.w $9500 ! ((grp_68900 / 2) & $00FF)
                dc.w $9600 ! (((grp_68900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $806D
                dc.w $9500 ! ((grp_68A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $9076
                dc.w $9500 ! ((grp_19C540 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C540 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8065
                dc.w $9500 ! ((grp_D8840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9065
                dc.w $9500 ! ((grp_BEA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEA80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $987D
                dc.w $9500 ! ((grp_BEAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7868
                dc.w $9500 ! ((grp_F0020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0020 / 2) >> 16)
                dc.w 1
