byte_2F0D08:    dc.b   0, $D,$5F,$59,$9A,$96,$7F,$6A,$80,$6A
                                        ; DATA XREF: ROM:off_2610   o
                dc.w sprite_32_32
                dc.w $5D63
                dc.w $9500 ! ((grp_35A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_35A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $604D
                dc.w $9500 ! ((grp_35C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_35C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $7D6B
                dc.w $9500 ! ((grp_35E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_35E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_35E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $804D
                dc.w $9500 ! ((grp_36000 / 2) & $00FF)
                dc.w $9600 ! (((grp_36000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_36000 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $5D83
                dc.w $9500 ! ((grp_14D700 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D700 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $758B
                dc.w $9500 ! ((grp_14D160 / 2) & $00FF)
                dc.w $9600 ! (((grp_14D160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14D160 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8D8B
                dc.w $9500 ! ((grp_166300 / 2) & $00FF)
                dc.w $9600 ! (((grp_166300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_166300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $4D6B
                dc.w $9500 ! ((grp_8B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5588
                dc.w $9500 ! ((grp_19D3E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D3E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D3E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9D63
                dc.w $9500 ! ((grp_BFE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9D7B
                dc.w $9500 ! ((grp_BFEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A593
                dc.w $9500 ! ((grp_BFB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7583
                dc.w $9500 ! ((grp_F1780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1780 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D73
                dc.w $9500 ! ((grp_F17A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F17A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F17A0 / 2) >> 16)
                dc.w 1
