byte_2DEA46:    dc.b   0,  9,$7B,$4C,$9E,$8D,$8C,$6C,$8D,$6C
                                        ; DATA XREF: ROM:off_179C   o
                dc.w sprite_16_24
                dc.w $8D44
                dc.w $9500 ! ((grp_176C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_176C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $8167
                dc.w $9500 ! ((grp_A6880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $896B
                dc.w $9500 ! ((grp_A6900 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9966
                dc.w $9500 ! ((grp_A6980 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6980 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7969
                dc.w $9500 ! ((grp_1980A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1980A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1980A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $917D
                dc.w $9500 ! ((grp_198160 / 2) & $00FF)
                dc.w $9600 ! (((grp_198160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9165
                dc.w $9500 ! ((grp_198100 / 2) & $00FF)
                dc.w $9600 ! (((grp_198100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198100 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $854C
                dc.w $9500 ! ((grp_B9140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D51
                dc.w $9500 ! ((grp_EB3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB3C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8587
                dc.w $9500 ! ((grp_EB3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB3A0 / 2) >> 16)
                dc.w 1
