byte_2F96C2:    dc.b   0,  1,$87,$7D,$99,$85,$90,$81,$91,$81
                                        ; DATA XREF: ROM:off_2D74   o
                dc.w sprite_24_8
                dc.w $847B
                dc.w $9500 ! ((grp_190000 / 2) & $00FF)
                dc.w $9600 ! (((grp_190000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190000 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $9083
                dc.w $9500 ! ((grp_F6980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6980 / 2) >> 16)
                dc.w 1
