byte_2E47E2:    dc.b   0,  4,$71,$69,$97,$95,$84,$7F,$85,$7F
                                        ; DATA XREF: ROM:off_1B44   o
                dc.w sprite_24_32
                dc.w $7667
                dc.w $9500 ! ((grp_109FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_109FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_109FC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7687
                dc.w $9500 ! ((grp_160600 / 2) & $00FF)
                dc.w $9600 ! (((grp_160600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160600 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $6E6F
                dc.w $9500 ! ((grp_A7B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7B80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8E6F
                dc.w $9500 ! ((grp_A7C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9677
                dc.w $9500 ! ((grp_B9F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9F80 / 2) >> 16)
                dc.w 2
