byte_2ECFAC:    dc.b   0,  5,$6E,$71,$97,$97,$82,$84,$83,$84
                                        ; DATA XREF: ROM:off_2250   o
                dc.w sprite_16_16
                dc.w $6C70
                dc.w $9500 ! ((grp_88780 / 2) & $00FF)
                dc.w $9600 ! (((grp_88780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7C6F
                dc.w $9500 ! ((grp_18C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C700 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7593
                dc.w $9500 ! ((grp_D8340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8340 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C87
                dc.w $9500 ! ((grp_BE700 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9283
                dc.w $9500 ! ((grp_BE740 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $917B
                dc.w $9500 ! ((grp_EFCA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFCA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFCA0 / 2) >> 16)
                dc.w 1
