byte_2D2B36:    dc.b   0,  3,$6F,$71,$96,$8C,$82,$7C,$83,$7C
                                        ; DATA XREF: ROM:off_F14   o
                dc.w sprite_32_24
                dc.w $7177
                dc.w $9500 ! ((grp_122A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_122A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $6C71
                dc.w $9500 ! ((grp_1848A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1848A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1848A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7069
                dc.w $9500 ! ((grp_CA3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9180
                dc.w $9500 ! ((grp_E4B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4B20 / 2) >> 16)
                dc.w 1
