byte_2FA280:    dc.b   0, $A,$77,$4A,$87,$8E,$8C,$6A,$8D,$6A
                                        ; DATA XREF: ROM:off_2DF8   o
                dc.w sprite_32_32
                dc.w $7271
                dc.w $9500 ! ((grp_41C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_41C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $6F51
                dc.w $9500 ! ((grp_11B0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11B0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11B0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8751
                dc.w $9500 ! ((grp_6FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6FF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6A43
                dc.w $9500 ! ((grp_16A8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $9754
                dc.w $9500 ! ((grp_190600 / 2) & $00FF)
                dc.w $9600 ! (((grp_190600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_190600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8249
                dc.w $9500 ! ((grp_DEC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A05C
                dc.w $9500 ! ((grp_DEC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DEC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DEC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9763
                dc.w $9500 ! ((grp_C4880 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6768
                dc.w $9500 ! ((grp_F6FE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6FE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6FE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $675C
                dc.w $9500 ! ((grp_F7000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7000 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9271
                dc.w $9500 ! ((grp_F7020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7020 / 2) >> 16)
                dc.w 1
