byte_2DAB7C:    dc.b   0,  3,$71,$79,$90,$8D,$9D,$80,$73,$8D
                                        ; DATA XREF: ROM:off_14F0   o
                dc.w sprite_32_16
                dc.w $7876
                dc.w $9500 ! ((grp_4B700 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $687A
                dc.w $9500 ! ((grp_1756C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1756C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1756C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7886
                dc.w $9500 ! ((grp_187600 / 2) & $00FF)
                dc.w $9600 ! (((grp_187600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187600 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $987E
                dc.w $9500 ! ((grp_E97A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E97A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E97A0 / 2) >> 16)
                dc.w 1
