byte_2DD05E:    dc.b   0,  5,$6E,$63,$86,$83,$74,$76,$6B,$69
                                        ; DATA XREF: ROM:off_168C   o
                dc.w sprite_24_24
                dc.w $7066
                dc.w $9500 ! ((grp_1429C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1429C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1429C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $8086
                dc.w $9500 ! ((grp_7A300 / 2) & $00FF)
                dc.w $9600 ! (((grp_7A300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7A300 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $5B5E
                dc.w $9500 ! ((grp_98A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5866
                dc.w $9500 ! ((grp_185A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_185A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $707E
                dc.w $9500 ! ((grp_185AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185AA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8871
                dc.w $9500 ! ((grp_E7360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7360 / 2) >> 16)
                dc.w 1
