byte_2EE86E:    dc.b   0,  6,$6C,$69,$93,$96,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_23E4   o
                dc.w sprite_32_24
                dc.w $6B6E
                dc.w $9500 ! ((grp_132AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_132AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_132AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6A86
                dc.w $9500 ! ((grp_165040 / 2) & $00FF)
                dc.w $9600 ! (((grp_165040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165040 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8286
                dc.w $9500 ! ((grp_165100 / 2) & $00FF)
                dc.w $9600 ! (((grp_165100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_165100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8B6E
                dc.w $9500 ! ((grp_17BD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_17BD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17BD80 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7066
                dc.w $9500 ! ((grp_9DE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DE80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7C96
                dc.w $9500 ! ((grp_18D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D300 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6376
                dc.w $9500 ! ((grp_BF540 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF540 / 2) >> 16)
                dc.w 2
