byte_2F11D6:    dc.b   0, $D,$64,$61,$9E,$99,$7F,$79,$80,$79
                                        ; DATA XREF: ROM:off_2634   o
                dc.w sprite_32_32
                dc.w $6D57
                dc.w $9500 ! ((grp_38E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_38E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_38E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $7D77
                dc.w $9500 ! ((grp_6C600 / 2) & $00FF)
                dc.w $9600 ! (((grp_6C600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6C600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6D87
                dc.w $9500 ! ((grp_8C780 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9589
                dc.w $9500 ! ((grp_8C800 / 2) & $00FF)
                dc.w $9600 ! (((grp_8C800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8C800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8D79
                dc.w $9500 ! ((grp_AC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_AC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AC980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $558D
                dc.w $9500 ! ((grp_18E140 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E140 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $655D
                dc.w $9500 ! ((grp_19D980 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D980 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D61
                dc.w $9500 ! ((grp_19D9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D9E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9567
                dc.w $9500 ! ((grp_19DA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DA40 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7997
                dc.w $9500 ! ((grp_DB4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5F95
                dc.w $9500 ! ((grp_F26A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F26A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F26A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7577
                dc.w $9500 ! ((grp_F26C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F26C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F26C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9499
                dc.w $9500 ! ((grp_F26E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F26E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F26E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D70
                dc.w $9500 ! ((grp_F2700 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2700 / 2) >> 16)
                dc.w 1
