byte_2F838A:    dc.b   0,  1,$74,$7A,$8C,$99,$80,$89,$81,$89
                                        ; DATA XREF: ROM:off_2C6C   o
                dc.w sprite_24_24
                dc.w $7988
                dc.w $9500 ! ((grp_151CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_151CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151CC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7178
                dc.w $9500 ! ((grp_57100 / 2) & $00FF)
                dc.w $9600 ! (((grp_57100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_57100 / 2) >> 16)
                dc.w 8
