byte_2F4868:    dc.b   0, $C,$60,$5E,$AE,$9A,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_29F0   o
                dc.w sprite_24_32
                dc.w $716C
                dc.w $9500 ! ((grp_115E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_115E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $798C
                dc.w $9500 ! ((grp_55F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_55F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $996F
                dc.w $9500 ! ((grp_168100 / 2) & $00FF)
                dc.w $9600 ! (((grp_168100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_168100 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6184
                dc.w $9500 ! ((grp_17E540 / 2) & $00FF)
                dc.w $9600 ! (((grp_17E540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17E540 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6164
                dc.w $9500 ! ((grp_8E000 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $815C
                dc.w $9500 ! ((grp_8E080 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $896C
                dc.w $9500 ! ((grp_19E2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E2E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9988
                dc.w $9500 ! ((grp_C1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697C
                dc.w $9500 ! ((grp_F3B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $718C
                dc.w $9500 ! ((grp_F3B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7164
                dc.w $9500 ! ((grp_F3B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9174
                dc.w $9500 ! ((grp_F3BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9184
                dc.w $9500 ! ((grp_F3BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3BC0 / 2) >> 16)
                dc.w 1
