byte_2D3F0C:    dc.b   0,  6,$75,$65,$9D,$8F,$86,$7C,$87,$7C
                                        ; DATA XREF: ROM:off_1090   o
                dc.w sprite_32_24
                dc.w $7D68
                dc.w $9500 ! ((grp_1231C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1231C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1231C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_98180 / 2) & $00FF)
                dc.w $9600 ! (((grp_98180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98180 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7980
                dc.w $9500 ! ((grp_98200 / 2) & $00FF)
                dc.w $9600 ! (((grp_98200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6980
                dc.w $9500 ! ((grp_CAC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $756B
                dc.w $9500 ! ((grp_B3200 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $637B
                dc.w $9500 ! ((grp_E55C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E55C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E55C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D6F
                dc.w $9500 ! ((grp_E55A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E55A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E55A0 / 2) >> 16)
                dc.w 1
