byte_2EF804:    dc.b   0,  2,$71,$21,$83,$34,$7A,$2A,$7B,$2A
                                        ; DATA XREF: ROM:off_2528   o
                dc.w sprite_16_8
                dc.w $742F
                dc.w $9500 ! ((grp_D9DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $771F
                dc.w $9500 ! ((grp_D9E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F21
                dc.w $9500 ! ((grp_F1120 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1120 / 2) >> 16)
                dc.w 1
