byte_2D6BF6:    dc.b   0, $B,$73,$55,$92,$A0,$81,$3C,$81,$58
                                        ; DATA XREF: ROM:off_1284   o
                dc.w sprite_32_24
                dc.w $7078
                dc.w $9500 ! ((grp_12EA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12EA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12EA40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6898
                dc.w $9500 ! ((grp_162DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_162DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162DC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6082
                dc.w $9500 ! ((grp_86200 / 2) & $00FF)
                dc.w $9600 ! (((grp_86200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7E4A
                dc.w $9500 ! ((grp_A9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9280 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $66A8
                dc.w $9500 ! ((grp_18B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B080 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $67B0
                dc.w $9500 ! ((grp_D6500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7090
                dc.w $9500 ! ((grp_D6540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6540 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $908B
                dc.w $9500 ! ((grp_D6580 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7D6A
                dc.w $9500 ! ((grp_BCC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCC40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $803A
                dc.w $9500 ! ((grp_BCC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BCC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BCC80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5885
                dc.w $9500 ! ((grp_EE440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8890
                dc.w $9500 ! ((grp_EE460 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE460 / 2) >> 16)
                dc.w 1
