byte_2E8042:    dc.b   0,  6,$78,$67,$8E,$85,$80,$72,$86,$64
                                        ; DATA XREF: ROM:off_1D44   o
                dc.w sprite_32_16
                dc.w $746F
                dc.w $9500 ! ((grp_4D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_4D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4D300 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7F5F
                dc.w $9500 ! ((grp_15EEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15EEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15EEC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $675F
                dc.w $9500 ! ((grp_7F780 / 2) & $00FF)
                dc.w $9600 ! (((grp_7F780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7F780 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7E7F
                dc.w $9500 ! ((grp_D12C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D12C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D12C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A57
                dc.w $9500 ! ((grp_D1300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1300 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7767
                dc.w $9500 ! ((grp_EA880 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA880 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8487
                dc.w $9500 ! ((grp_EA8A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EA8A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EA8A0 / 2) >> 16)
                dc.w 1
