byte_2CC1D8:    dc.b   0,  1,$82,$82,$96,$98,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_700   o
                dc.w sprite_24_24
                dc.w $8083
                dc.w $9500 ! ((grp_13D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_13D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13D200 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $877B
                dc.w $9500 ! ((grp_C69C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C69C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C69C0 / 2) >> 16)
                dc.w 2
