byte_2EF044:    dc.b   0,  1,$73,$7D,$8E,$8C,$80,$84,$81,$84
                                        ; DATA XREF: ROM:off_2458   o
                dc.w sprite_32_16
                dc.w $717B
                dc.w $9500 ! ((grp_53700 / 2) & $00FF)
                dc.w $9600 ! (((grp_53700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53700 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $748B
                dc.w $9500 ! ((grp_18D9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D9C0 / 2) >> 16)
                dc.w 3
