byte_2EF4B8:    dc.b   0,  5,$6C,$81,$93,$8D,$80,$7B,$81,$7B
                                        ; DATA XREF: ROM:off_24E8   o
                dc.w sprite_24_16
                dc.w $7581
                dc.w $9500 ! ((grp_1657C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1657C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1657C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7369
                dc.w $9500 ! ((grp_18D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D600 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6586
                dc.w $9500 ! ((grp_D9B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7871
                dc.w $9500 ! ((grp_D9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9780 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7879
                dc.w $9500 ! ((grp_D9B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D81
                dc.w $9500 ! ((grp_D9B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9B80 / 2) >> 16)
                dc.w 2
