byte_2DC9BC:    dc.b   0,  7,$6F,$4A,$8E,$8F,$7F,$6D,$7D,$50
                                        ; DATA XREF: ROM:off_1650   o
                dc.w sprite_24_32
                dc.w $745A
                dc.w $9500 ! ((grp_10C9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $744A
                dc.w $9500 ! ((grp_162640 / 2) & $00FF)
                dc.w $9600 ! (((grp_162640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_162640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6E88
                dc.w $9500 ! ((grp_D5640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5640 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8589
                dc.w $9500 ! ((grp_D5680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7778
                dc.w $9500 ! ((grp_BBD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8479
                dc.w $9500 ! ((grp_BBD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C6B
                dc.w $9500 ! ((grp_BBD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C71
                dc.w $9500 ! ((grp_EDA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDA40 / 2) >> 16)
                dc.w 1
