byte_2D3FC8:    dc.b   0,  6,$72,$65,$9B,$8F,$8B,$7B,$8C,$7B
                                        ; DATA XREF: ROM:off_1098   o
                dc.w sprite_24_32
                dc.w $7270
                dc.w $9500 ! ((grp_FDE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_FDE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FDE40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7268
                dc.w $9500 ! ((grp_184E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_184E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184E40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8A6A
                dc.w $9500 ! ((grp_1942C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1942C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1942C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $926F
                dc.w $9500 ! ((grp_CACC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CACC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CACC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $A272
                dc.w $9500 ! ((grp_CAD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAD00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6A77
                dc.w $9500 ! ((grp_B3240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9267
                dc.w $9500 ! ((grp_E5660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5660 / 2) >> 16)
                dc.w 1
