byte_2E1F24:    dc.b   0,  3,$73,$5F,$8E,$8A,$80,$74,$7E,$66
                                        ; DATA XREF: ROM:off_19C8   o
                dc.w sprite_32_24
                dc.w $7165
                dc.w $9500 ! ((grp_125D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_125D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125D40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7185
                dc.w $9500 ! ((grp_98C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_98C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $747D
                dc.w $9500 ! ((grp_186100 / 2) & $00FF)
                dc.w $9600 ! (((grp_186100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_186100 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $795D
                dc.w $9500 ! ((grp_CD740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD740 / 2) >> 16)
                dc.w 2
