byte_2EB7B2:    dc.b   0,  4,$71,$55,$8F,$8D,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_204C   o
                dc.w sprite_32_32
                dc.w $6A6D
                dc.w $9500 ! ((grp_2BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2BC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8A6D
                dc.w $9500 ! ((grp_67C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67C00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6A8D
                dc.w $9500 ! ((grp_9CB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8A8D
                dc.w $9500 ! ((grp_D7CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9A7D
                dc.w $9500 ! ((grp_EF640 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF640 / 2) >> 16)
                dc.w 1
