byte_2EB4B0:    dc.b   0,  3,$71,$55,$8F,$8D,$82,$7F,$83,$7F
                                        ; DATA XREF: ROM:off_2020   o
                dc.w sprite_32_32
                dc.w $6A6C
                dc.w $9500 ! ((grp_2BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_2BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2BE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8A74
                dc.w $9500 ! ((grp_67D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_67D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $6A8C
                dc.w $9500 ! ((grp_9CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9CC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $8A6C
                dc.w $9500 ! ((grp_EF660 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF660 / 2) >> 16)
                dc.w 1
