byte_2D1FC4:    dc.b   0,  4,$6A,$70,$93,$8E,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_E88   o
                dc.w sprite_32_32
                dc.w $6B71
                dc.w $9500 ! ((grp_16C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_16C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8B70
                dc.w $9500 ! ((grp_A3F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E69
                dc.w $9500 ! ((grp_184480 / 2) & $00FF)
                dc.w $9600 ! (((grp_184480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184480 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6386
                dc.w $9500 ! ((grp_E40C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E40C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E40C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $937D
                dc.w $9500 ! ((grp_E40E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E40E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E40E0 / 2) >> 16)
                dc.w 1
