byte_2D6E08:    dc.b   0,  6,$74,$55,$92,$A0,$81,$44,$82,$62
                                        ; DATA XREF: ROM:off_1298   o
                dc.w sprite_32_32
                dc.w $6F82
                dc.w $9500 ! ((grp_27400 / 2) & $00FF)
                dc.w $9600 ! (((grp_27400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $78A2
                dc.w $9500 ! ((grp_10DBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10DBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10DBC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_32
                dc.w $7F42
                dc.w $9500 ! ((grp_A9600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9600 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8062
                dc.w $9500 ! ((grp_A9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9680 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7858
                dc.w $9500 ! ((grp_19A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A800 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8F8C
                dc.w $9500 ! ((grp_19A860 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $70A2
                dc.w $9500 ! ((grp_EE500 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE500 / 2) >> 16)
                dc.w 1
