byte_2CBF72:    dc.b   0,  7,$63,$7B,$92,$87,$7F,$7C,$80,$7C
                                        ; DATA XREF: ROM:off_6BC   o
                dc.w sprite_32_16
                dc.w $6A7A
                dc.w $9500 ! ((grp_45E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_45E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_45E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $947B
                dc.w $9500 ! ((grp_C6B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5D75
                dc.w $9500 ! ((grp_E1380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5D81
                dc.w $9500 ! ((grp_E1300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A6F
                dc.w $9500 ! ((grp_E1320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7672
                dc.w $9500 ! ((grp_E1360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1360 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8871
                dc.w $9500 ! ((grp_E1340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D83
                dc.w $9500 ! ((grp_E12E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E12E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E12E0 / 2) >> 16)
                dc.w 1
