byte_2E5C0E:    dc.b   0,  7,$6A,$61,$84,$8E,$47,$96,$70,$63
                                        ; DATA XREF: ROM:off_1BFC   o
                dc.w sprite_24_32
                dc.w $6C69
                dc.w $9500 ! ((grp_10A140 / 2) & $00FF)
                dc.w $9600 ! (((grp_10A140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10A140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8F6F
                dc.w $9500 ! ((grp_82D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_82D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6E89
                dc.w $9500 ! ((grp_189AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_189AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189AC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $646D
                dc.w $9500 ! ((grp_199000 / 2) & $00FF)
                dc.w $9600 ! (((grp_199000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199000 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $745E
                dc.w $9500 ! ((grp_D3980 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3980 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8369
                dc.w $9500 ! ((grp_D39C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D39C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D39C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $875F
                dc.w $9500 ! ((grp_D3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3A00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6C59
                dc.w $9500 ! ((grp_BA700 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA700 / 2) >> 16)
                dc.w 2
