byte_2F9AE0:    dc.b   0,  5,$7A,$71,$92,$8F,$82,$80,$83,$80
                                        ; DATA XREF: ROM:off_2DC0   o
                dc.w sprite_32_32
                dc.w $7672
                dc.w $9500 ! ((grp_41000 / 2) & $00FF)
                dc.w $9600 ! (((grp_41000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_41000 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $6679
                dc.w $9500 ! ((grp_180400 / 2) & $00FF)
                dc.w $9600 ! (((grp_180400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180400 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $967A
                dc.w $9500 ! ((grp_19F720 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F720 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $806A
                dc.w $9500 ! ((grp_DE780 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5E81
                dc.w $9500 ! ((grp_C4440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9E82
                dc.w $9500 ! ((grp_C4480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4480 / 2) >> 16)
                dc.w 2
