byte_2E9AA4:    dc.b   0,  8,$60,$3B,$A5,$80,$7F,$4D,$80,$4D
                                        ; DATA XREF: ROM:off_1E98   o
                dc.w sprite_32_32
                dc.w $583C
                dc.w $9500 ! ((grp_27A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $783B
                dc.w $9500 ! ((grp_66E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $983D
                dc.w $9500 ! ((grp_66F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $585C
                dc.w $9500 ! ((grp_9C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9042
                dc.w $9500 ! ((grp_A9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5E34
                dc.w $9500 ! ((grp_18B560 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8845
                dc.w $9500 ! ((grp_19AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $785B
                dc.w $9500 ! ((grp_D6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $985D
                dc.w $9500 ! ((grp_EEB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB20 / 2) >> 16)
                dc.w 1
