byte_2D9AB4:    dc.b   0,  5,$89,$67,$91,$77,$7E,$5B,$7F,$5B
                                        ; DATA XREF: ROM:off_1460   o
                dc.w sprite_32_8
                dc.w $7153
                dc.w $9500 ! ((grp_99400 / 2) & $00FF)
                dc.w $9600 ! (((grp_99400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $695B
                dc.w $9500 ! ((grp_196D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_196D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196D80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $885B
                dc.w $9500 ! ((grp_B6F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6F40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6953
                dc.w $9500 ! ((grp_E9420 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $876B
                dc.w $9500 ! ((grp_E9440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9440 / 2) >> 16)
                dc.w 1
