byte_2DD210:    dc.b   0,  4,$76,$62,$8E,$81,$83,$6E,$80,$63
                                        ; DATA XREF: ROM:off_16A0   o
                dc.w sprite_32_24
                dc.w $7363
                dc.w $9500 ! ((grp_125140 / 2) & $00FF)
                dc.w $9600 ! (((grp_125140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_125140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7A7B
                dc.w $9500 ! ((grp_15B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B500 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7453
                dc.w $9500 ! ((grp_CD000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $755B
                dc.w $9500 ! ((grp_CD040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A5B
                dc.w $9500 ! ((grp_E7500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7500 / 2) >> 16)
                dc.w 1
