byte_2DDC2A:    dc.b   0,  4,$66,$69,$8D,$91,$79,$7D,$83,$6D
                                        ; DATA XREF: ROM:off_170C   o
                dc.w sprite_24_32
                dc.w $7567
                dc.w $9500 ! ((grp_107BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_107BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7587
                dc.w $9500 ! ((grp_188B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_188B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_188B60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D6A
                dc.w $9500 ! ((grp_198040 / 2) & $00FF)
                dc.w $9600 ! (((grp_198040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198040 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7060
                dc.w $9500 ! ((grp_D2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2300 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $768F
                dc.w $9500 ! ((grp_D2340 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2340 / 2) >> 16)
                dc.w 2
