byte_2D098E:    dc.b   0,  5,$9C,$67,$A8,$81,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_DAC   o
                dc.w sprite_32_32
                dc.w $6562
                dc.w $9500 ! ((grp_14200 / 2) & $00FF)
                dc.w $9600 ! (((grp_14200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $8565
                dc.w $9500 ! ((grp_14400 / 2) & $00FF)
                dc.w $9600 ! (((grp_14400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $6582
                dc.w $9500 ! ((grp_47100 / 2) & $00FF)
                dc.w $9600 ! (((grp_47100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47100 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $A562
                dc.w $9500 ! ((grp_A3880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $5D6D
                dc.w $9500 ! ((grp_192E20 / 2) & $00FF)
                dc.w $9600 ! (((grp_192E20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192E20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $945D
                dc.w $9500 ! ((grp_C8E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8E00 / 2) >> 16)
                dc.w 2
