byte_2EDE2C:    dc.b   0,  6,$76,$6D,$B7,$8D,$96,$7D,$97,$7D
                                        ; DATA XREF: ROM:off_2320   o
                dc.w sprite_24_24
                dc.w $797C
                dc.w $9500 ! ((grp_14CAA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14CAA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14CAA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $997D
                dc.w $9500 ! ((grp_D8F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8F80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $AD68
                dc.w $9500 ! ((grp_D8FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8FC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A970
                dc.w $9500 ! ((grp_BF080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7188
                dc.w $9500 ! ((grp_F0520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E74
                dc.w $9500 ! ((grp_F0540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9180
                dc.w $9500 ! ((grp_F0560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0560 / 2) >> 16)
                dc.w 1
