byte_2E202E:    dc.b   0,  5,$77,$4E,$8A,$9B,$80,$74,$81,$74
                                        ; DATA XREF: ROM:off_19DC   o
                dc.w sprite_24_32
                dc.w $7569
                dc.w $9500 ! ((grp_102040 / 2) & $00FF)
                dc.w $9600 ! (((grp_102040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7551
                dc.w $9500 ! ((grp_1432C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1432C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1432C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7589
                dc.w $9500 ! ((grp_15C1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C1C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7549
                dc.w $9500 ! ((grp_E7CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7599
                dc.w $9500 ! ((grp_E7C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8549
                dc.w $9500 ! ((grp_E7C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7C60 / 2) >> 16)
                dc.w 1
