byte_2F024A:    dc.b   0,  1,$79,$57,$86,$87,$86,$68,$87,$68
                                        ; DATA XREF: ROM:off_25CC   o
                dc.w sprite_16_32
                dc.w $795B
                dc.w $9500 ! ((grp_6B300 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B300 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8763
                dc.w $9500 ! ((grp_8B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B600 / 2) >> 16)
                dc.w 4
