byte_2E4D10:    dc.b   0,  5,$6E,$65,$8A,$8E,$4D,$98,$7B,$65
                                        ; DATA XREF: ROM:off_1B80   o
                dc.w sprite_32_24
                dc.w $686B
                dc.w $9500 ! ((grp_12C1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12C1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12C1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7183
                dc.w $9500 ! ((grp_4F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $725B
                dc.w $9500 ! ((grp_82380 / 2) & $00FF)
                dc.w $9600 ! (((grp_82380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82380 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $886D
                dc.w $9500 ! ((grp_82400 / 2) & $00FF)
                dc.w $9600 ! (((grp_82400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9870
                dc.w $9500 ! ((grp_BA080 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8263
                dc.w $9500 ! ((grp_EC300 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC300 / 2) >> 16)
                dc.w 1
