byte_2D2B92:    dc.b   0,  6,$74,$6E,$90,$8C,$82,$7B,$83,$7B
                                        ; DATA XREF: ROM:off_F1C   o
                dc.w sprite_24_16
                dc.w $7A6F
                dc.w $9500 ! ((grp_159100 / 2) & $00FF)
                dc.w $9600 ! (((grp_159100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159100 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7A7F
                dc.w $9500 ! ((grp_1591C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1591C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1591C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A6C
                dc.w $9500 ! ((grp_77280 / 2) & $00FF)
                dc.w $9600 ! (((grp_77280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $6B64
                dc.w $9500 ! ((grp_E4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $727C
                dc.w $9500 ! ((grp_E4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A8F
                dc.w $9500 ! ((grp_E4C60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4C60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4C60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $927F
                dc.w $9500 ! ((grp_E4BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4BA0 / 2) >> 16)
                dc.w 1
