byte_2EE92A:    dc.b   0,  4,$69,$6A,$9A,$8C,$81,$7A,$82,$7A
                                        ; DATA XREF: ROM:off_23EC   o
                dc.w sprite_32_32
                dc.w $686F
                dc.w $9500 ! ((grp_32600 / 2) & $00FF)
                dc.w $9600 ! (((grp_32600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_32600 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $886F
                dc.w $9500 ! ((grp_1123C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1123C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1123C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7060
                dc.w $9500 ! ((grp_9DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7E8F
                dc.w $9500 ! ((grp_18D360 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D360 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6077
                dc.w $9500 ! ((grp_BF580 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF580 / 2) >> 16)
                dc.w 2
