byte_2D89F2:    dc.b   0,  9,$6F,$5A,$8E,$90,$76,$72,$86,$65
                                        ; DATA XREF: ROM:off_13C4   o
                dc.w sprite_24_24
                dc.w $6A65
                dc.w $9500 ! ((grp_1479A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1479A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1479A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $617D
                dc.w $9500 ! ((grp_18A240 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A240 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8265
                dc.w $9500 ! ((grp_199A20 / 2) & $00FF)
                dc.w $9600 ! (((grp_199A20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_199A20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5A64
                dc.w $9500 ! ((grp_D4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7385
                dc.w $9500 ! ((grp_D4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B7D
                dc.w $9500 ! ((grp_D4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $805D
                dc.w $9500 ! ((grp_D4C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6185
                dc.w $9500 ! ((grp_ED200 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED200 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $768D
                dc.w $9500 ! ((grp_ED220 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8755
                dc.w $9500 ! ((grp_ED240 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED240 / 2) >> 16)
                dc.w 1
