byte_2F9148:    dc.b   0,  4,$76,$57,$94,$8D,$85,$72,$86,$72
                                        ; DATA XREF: ROM:off_2D10   o
                dc.w sprite_24_32
                dc.w $746D
                dc.w $9500 ! ((grp_11A1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7A55
                dc.w $9500 ! ((grp_152140 / 2) & $00FF)
                dc.w $9600 ! (((grp_152140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_152140 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $778A
                dc.w $9500 ! ((grp_18FD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18FD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18FD60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8C79
                dc.w $9500 ! ((grp_C3F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9259
                dc.w $9500 ! ((grp_C3F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3F40 / 2) >> 16)
                dc.w 2
