byte_2D5D5A:    dc.b   0,  5,$73,$50,$89,$89,$81,$6E,$79,$5A
                                        ; DATA XREF: ROM:off_11EC   o
                dc.w sprite_32_24
                dc.w $6C4E
                dc.w $9500 ! ((grp_123C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_123C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_123C40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7466
                dc.w $9500 ! ((grp_1416A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1416A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1416A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6D7E
                dc.w $9500 ! ((grp_78B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $847E
                dc.w $9500 ! ((grp_CBEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CBEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CBEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9476
                dc.w $9500 ! ((grp_B3D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6582
                dc.w $9500 ! ((grp_E6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6400 / 2) >> 16)
                dc.w 1
