byte_2CCAF0:    dc.b   0,  4,$45,$88,$B3,$90,$7C,$8C,$7D,$8C
                                        ; DATA XREF: ROM:off_7F0   o
                dc.w sprite_32_16
                dc.w $7284
                dc.w $9500 ! ((grp_46400 / 2) & $00FF)
                dc.w $9600 ! (((grp_46400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46400 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $9288
                dc.w $9500 ! ((grp_96D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_96D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $4287
                dc.w $9500 ! ((grp_183160 / 2) & $00FF)
                dc.w $9600 ! (((grp_183160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_183160 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $5A8A
                dc.w $9500 ! ((grp_1831C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1831C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1831C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $B286
                dc.w $9500 ! ((grp_E1740 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1740 / 2) >> 16)
                dc.w 1
