byte_2F50E2:    dc.b   0, $C,$6C,$5E,$96,$95,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_2A3C   o
                dc.w sprite_24_24
                dc.w $716C
                dc.w $9500 ! ((grp_1509A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1509A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1509A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6384
                dc.w $9500 ! ((grp_56100 / 2) & $00FF)
                dc.w $9600 ! (((grp_56100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6164
                dc.w $9500 ! ((grp_8EA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7A5C
                dc.w $9500 ! ((grp_8EA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9384
                dc.w $9500 ! ((grp_8EB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $996E
                dc.w $9500 ! ((grp_8EB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8974
                dc.w $9500 ! ((grp_DC8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8384
                dc.w $9500 ! ((grp_C1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $697C
                dc.w $9500 ! ((grp_F4500 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4500 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6994
                dc.w $9500 ! ((grp_F4520 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4520 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4520 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7164
                dc.w $9500 ! ((grp_F4540 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4540 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8B8C
                dc.w $9500 ! ((grp_F4560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E94
                dc.w $9500 ! ((grp_F4580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4580 / 2) >> 16)
                dc.w 1
