byte_2E6BC8:    dc.b   0,  9,$72,$64,$85,$8E,$82,$72,$7A,$64
                                        ; DATA XREF: ROM:off_1C80   o
                dc.w sprite_32_16
                dc.w $6E69
                dc.w $9500 ! ((grp_4F500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F500 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6851
                dc.w $9500 ! ((grp_83880 / 2) & $00FF)
                dc.w $9600 ! (((grp_83880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83880 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7479
                dc.w $9500 ! ((grp_83900 / 2) & $00FF)
                dc.w $9600 ! (((grp_83900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83900 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8E60
                dc.w $9500 ! ((grp_83980 / 2) & $00FF)
                dc.w $9600 ! (((grp_83980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83980 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7089
                dc.w $9500 ! ((grp_9B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6F61
                dc.w $9500 ! ((grp_D4000 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7859
                dc.w $9500 ! ((grp_ECAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECAC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8481
                dc.w $9500 ! ((grp_ECAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECAE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E70
                dc.w $9500 ! ((grp_ECB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9089
                dc.w $9500 ! ((grp_ECB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECB20 / 2) >> 16)
                dc.w 1
