byte_2CD5EE:    dc.b   0,  4,$73,$6A,$85,$85,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8EC   o
                dc.w sprite_24_24
                dc.w $716A
                dc.w $9500 ! ((grp_13E1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E1C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_8
                dc.w $7182
                dc.w $9500 ! ((grp_1832E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1832E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1832E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7462
                dc.w $9500 ! ((grp_C7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7C8A
                dc.w $9500 ! ((grp_E1D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1D80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8977
                dc.w $9500 ! ((grp_E1DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1DA0 / 2) >> 16)
                dc.w 1
