byte_2F01CC:    dc.b   0,  1,$79,$57,$86,$87,$82,$68,$83,$68
                                        ; DATA XREF: ROM:off_25C0   o
                dc.w sprite_32_16
                dc.w $755B
                dc.w $9500 ! ((grp_54200 / 2) & $00FF)
                dc.w $9600 ! (((grp_54200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_54200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $766B
                dc.w $9500 ! ((grp_8B580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B580 / 2) >> 16)
                dc.w 4
