byte_2CD4E0:    dc.b   0,  1,$9E,$68,$AB,$6F,$8E,$92,$8F,$92
                                        ; DATA XREF: ROM:off_8C8   o
                dc.w sprite_16_16
                dc.w $9C66
                dc.w $9500 ! ((grp_73B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_73B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $AC69
                dc.w $9500 ! ((grp_E1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1D00 / 2) >> 16)
                dc.w 1
