byte_2D8A74:    dc.b   0,  6,$6F,$5A,$8E,$90,$83,$74,$92,$64
                                        ; DATA XREF: ROM:off_13C8   o
                dc.w sprite_32_24
                dc.w $7C69
                dc.w $9500 ! ((grp_12CF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12CF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12CF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7481
                dc.w $9500 ! ((grp_84580 / 2) & $00FF)
                dc.w $9600 ! (((grp_84580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6482
                dc.w $9500 ! ((grp_D4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6C6D
                dc.w $9500 ! ((grp_D4CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8E59
                dc.w $9500 ! ((grp_BB580 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB580 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9C69
                dc.w $9500 ! ((grp_BB5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8488
                dc.w $9500 ! ((grp_ED260 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED260 / 2) >> 16)
                dc.w 1
