byte_2E2310:    dc.b   0,  5,$72,$64,$89,$84,$82,$73,$8F,$5D
                                        ; DATA XREF: ROM:off_1A00   o
                dc.w sprite_24_32
                dc.w $7557
                dc.w $9500 ! ((grp_102AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_102AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_102AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7477
                dc.w $9500 ! ((grp_143620 / 2) & $00FF)
                dc.w $9600 ! (((grp_143620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_143620 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_32
                dc.w $6D5F
                dc.w $9500 ! ((grp_A5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8C75
                dc.w $9500 ! ((grp_195D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_195D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195D00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $828F
                dc.w $9500 ! ((grp_E7EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D57
                dc.w $9500 ! ((grp_E7EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7EC0 / 2) >> 16)
                dc.w 1
