byte_2FEDD2:    dc.b   0,  1,$77,$75,$87,$85,$7F,$7D,$80,$7D
                                        ; DATA XREF: ROM:off_34EC   o
                dc.w sprite_16_16
                dc.w $7A78
                dc.w $9500 ! ((grp_96880 / 2) & $00FF)
                dc.w $9600 ! (((grp_96880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7573
                dc.w $9500 ! ((grp_F9740 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9740 / 2) >> 16)
                dc.w 1
