byte_2CD272:    dc.b   0,  4,$69,$6E,$96,$92,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_894   o
                dc.w sprite_32_16
                dc.w $6784
                dc.w $9500 ! ((grp_46700 / 2) & $00FF)
                dc.w $9600 ! (((grp_46700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $886D
                dc.w $9500 ! ((grp_5BE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5BE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5BE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $776C
                dc.w $9500 ! ((grp_C8140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8140 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $878D
                dc.w $9500 ! ((grp_C8180 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8180 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6B73
                dc.w $9500 ! ((grp_B0B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0B40 / 2) >> 16)
                dc.w 2
