byte_2F2E2E:    dc.b   0,  8,$73,$54,$97,$82,$86,$6D,$87,$6D
                                        ; DATA XREF: ROM:off_2774   o
                dc.w sprite_24_24
                dc.w $776D
                dc.w $9500 ! ((grp_14FD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_14FD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14FD40 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_24
                dc.w $7755
                dc.w $9500 ! ((grp_14FE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_14FE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14FE60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $694F
                dc.w $9500 ! ((grp_8D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D500 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8F6D
                dc.w $9500 ! ((grp_8D580 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D580 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7885
                dc.w $9500 ! ((grp_DBF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBF80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F79
                dc.w $9500 ! ((grp_F32A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F32A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F32A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $874D
                dc.w $9500 ! ((grp_F32C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F32C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F32C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F65
                dc.w $9500 ! ((grp_F32E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F32E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F32E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F75
                dc.w $9500 ! ((grp_F3300 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3300 / 2) >> 16)
                dc.w 1
