byte_2FB356:    dc.b   0,  4,$5F,$6D,$8F,$96,$77,$81,$78,$81
                                        ; DATA XREF: ROM:off_2F5C   o
                dc.w sprite_32_32
                dc.w $5D6B
                dc.w $9500 ! ((grp_43200 / 2) & $00FF)
                dc.w $9600 ! (((grp_43200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43200 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $7D7B
                dc.w $9500 ! ((grp_11BFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_11BFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11BFC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7D6B
                dc.w $9500 ! ((grp_91D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_91D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6D8B
                dc.w $9500 ! ((grp_DF200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7593
                dc.w $9500 ! ((grp_F7880 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7880 / 2) >> 16)
                dc.w 1
