byte_2D02A2:    dc.b   0,  4,$70,$63,$87,$84,$7B,$73,$7C,$73
                                        ; DATA XREF: ROM:off_CFC   o
                dc.w sprite_24_24
                dc.w $7774
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $7064
                dc.w $9500 ! ((grp_157600 / 2) & $00FF)
                dc.w $9600 ! (((grp_157600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157600 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6866
                dc.w $9500 ! ((grp_E3220 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C5C
                dc.w $9500 ! ((grp_E3240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8868
                dc.w $9500 ! ((grp_E3260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3260 / 2) >> 16)
                dc.w 1
