byte_2F4014:    dc.b   0,  4,$71,$6E,$91,$94,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28C8   o
                dc.w sprite_24_32
                dc.w $7474
                dc.w $9500 ! ((grp_115840 / 2) & $00FF)
                dc.w $9600 ! (((grp_115840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115840 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $7D6C
                dc.w $9500 ! ((grp_18E920 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E920 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E920 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8C74
                dc.w $9500 ! ((grp_C1240 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6C82
                dc.w $9500 ! ((grp_F34C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F34C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F34C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7694
                dc.w $9500 ! ((grp_F34E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F34E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F34E0 / 2) >> 16)
                dc.w 1
