byte_2F2CDA:    dc.b   0,  6,$70,$67,$8F,$9E,$82,$81,$83,$81
                                        ; DATA XREF: ROM:off_2764   o
                dc.w sprite_32_32
                dc.w $6E82
                dc.w $9500 ! ((grp_3A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_3A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3A800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_24
                dc.w $7C6A
                dc.w $9500 ! ((grp_14F9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F9E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6C65
                dc.w $9500 ! ((grp_8D380 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9462
                dc.w $9500 ! ((grp_19DF20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DF20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DF20 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8462
                dc.w $9500 ! ((grp_DBF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7475
                dc.w $9500 ! ((grp_F31A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F31A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F31A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E88
                dc.w $9500 ! ((grp_F31C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F31C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F31C0 / 2) >> 16)
                dc.w 1
