byte_2D2568:    dc.b   0,  3,$5D,$4A,$A3,$73,$6F,$6C,$70,$6C
                                        ; DATA XREF: ROM:off_EE0   o
                dc.w sprite_24_16
                dc.w $5E5A
                dc.w $9500 ! ((grp_158B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_158B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $5A6A
                dc.w $9500 ! ((grp_1936C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1936C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1936C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $765A
                dc.w $9500 ! ((grp_C9E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $626A
                dc.w $9500 ! ((grp_E4360 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4360 / 2) >> 16)
                dc.w 1
