byte_2F1614:    dc.b   0,  3,$70,$61,$91,$89,$80,$79,$81,$79
                                        ; DATA XREF: ROM:off_2658   o
                dc.w sprite_24_32
                dc.w $7668
                dc.w $9500 ! ((grp_113A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_113A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_113A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $6E74
                dc.w $9500 ! ((grp_19D620 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7D88
                dc.w $9500 ! ((grp_F1EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1EC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E79
                dc.w $9500 ! ((grp_F1EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1EE0 / 2) >> 16)
                dc.w 1
