byte_2D428A:    dc.b   0,  5,$7E,$68,$9D,$90,$87,$79,$88,$79
                                        ; DATA XREF: ROM:off_10B4   o
                dc.w sprite_24_32
                dc.w $8070
                dc.w $9500 ! ((grp_FD9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FD9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FD9C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_8
                dc.w $8668
                dc.w $9500 ! ((grp_184CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184CC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8960
                dc.w $9500 ! ((grp_184D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_184D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7086
                dc.w $9500 ! ((grp_E5300 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $787B
                dc.w $9500 ! ((grp_E5320 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5320 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7888
                dc.w $9500 ! ((grp_E5340 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5340 / 2) >> 16)
                dc.w 1
