byte_2DFAF2:    dc.b   0,  6,$68,$67,$9B,$8D,$81,$7A,$78,$78
                                        ; DATA XREF: ROM:off_184C   o
                dc.w sprite_24_24
                dc.w $656D
                dc.w $9500 ! ((grp_146320 / 2) & $00FF)
                dc.w $9600 ! (((grp_146320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_146320 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6D85
                dc.w $9500 ! ((grp_15F940 / 2) & $00FF)
                dc.w $9600 ! (((grp_15F940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15F940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8580
                dc.w $9500 ! ((grp_80F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_80F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8570
                dc.w $9500 ! ((grp_80F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_80F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7D65
                dc.w $9500 ! ((grp_A6C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A6C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A6C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $956C
                dc.w $9500 ! ((grp_B9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9500 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D68
                dc.w $9500 ! ((grp_EB680 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB680 / 2) >> 16)
                dc.w 1
