byte_2D4A54:    dc.b   0,  3,$27,$84,$68,$91,$47,$8A,$48,$8A
                                        ; DATA XREF: ROM:off_1110   o
                dc.w sprite_32_16
                dc.w $3581
                dc.w $9500 ! ((grp_4C500 / 2) & $00FF)
                dc.w $9600 ! (((grp_4C500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4C500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $5587
                dc.w $9500 ! ((grp_187D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_187D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187D20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $2D84
                dc.w $9500 ! ((grp_B7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $258C
                dc.w $9500 ! ((grp_E9E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9E40 / 2) >> 16)
                dc.w 1
