byte_2D25A2:    dc.b   0,  5,$5D,$4A,$A3,$73,$79,$77,$7A,$77
                                        ; DATA XREF: ROM:off_EE4   o
                dc.w sprite_16_32
                dc.w $615D
                dc.w $9500 ! ((grp_5DF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5DF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5DF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $815A
                dc.w $9500 ! ((grp_158BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_158BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $715A
                dc.w $9500 ! ((grp_171700 / 2) & $00FF)
                dc.w $9600 ! (((grp_171700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171700 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $5967
                dc.w $9500 ! ((grp_A4080 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $617D
                dc.w $9500 ! ((grp_193720 / 2) & $00FF)
                dc.w $9600 ! (((grp_193720 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193720 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $5987
                dc.w $9500 ! ((grp_B2780 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2780 / 2) >> 16)
                dc.w 2
