byte_2EF742:    dc.b   0,  3,$73,$59,$8F,$69,$81,$61,$82,$61
                                        ; DATA XREF: ROM:off_2514   o
                dc.w sprite_8_16
                dc.w $8A5F
                dc.w $9500 ! ((grp_BF840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $715F
                dc.w $9500 ! ((grp_F1020 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B65
                dc.w $9500 ! ((grp_F10A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F10A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F10A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8457
                dc.w $9500 ! ((grp_F1080 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1080 / 2) >> 16)
                dc.w 1
