byte_2D761E:    dc.b   0,  5,$77,$65,$8F,$99,$7B,$73,$84,$67
                                        ; DATA XREF: ROM:off_12EC   o
                dc.w sprite_24_32
                dc.w $7166
                dc.w $9500 ! ((grp_FF940 / 2) & $00FF)
                dc.w $9600 ! (((grp_FF940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FF940 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $896E
                dc.w $9500 ! ((grp_172B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_172B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_172B40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5F63
                dc.w $9500 ! ((grp_78F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_78F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7F5E
                dc.w $9500 ! ((grp_CC080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8386
                dc.w $9500 ! ((grp_CC0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $696D
                dc.w $9500 ! ((grp_B3E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3E00 / 2) >> 16)
                dc.w 2
