byte_2D38A4:    dc.b   0,  4,$7C,$5D,$93,$82,$8A,$6F,$8B,$6F
                                        ; DATA XREF: ROM:off_1040   o
                dc.w sprite_24_16
                dc.w $755D
                dc.w $9500 ! ((grp_158EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_158EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158EC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7B75
                dc.w $9500 ! ((grp_76F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_76F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8D5B
                dc.w $9500 ! ((grp_76F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_76F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C6D
                dc.w $9500 ! ((grp_CA100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B55
                dc.w $9500 ! ((grp_E4660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4660 / 2) >> 16)
                dc.w 1
