byte_2FBADE:    dc.b   0,  5,$6D,$6E,$96,$94,$81,$81,$82,$81
                                        ; DATA XREF: ROM:off_2FC4   o
                dc.w sprite_24_24
                dc.w $836F
                dc.w $9500 ! ((grp_153D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_153D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_153D60 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $8287
                dc.w $9500 ! ((grp_16B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_16B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16B400 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $737C
                dc.w $9500 ! ((grp_91E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_91E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $6B6C
                dc.w $9500 ! ((grp_19FE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FE40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $786C
                dc.w $9500 ! ((grp_F7960 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8767
                dc.w $9500 ! ((grp_F7980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7980 / 2) >> 16)
                dc.w 1
