byte_2F459A:    dc.b   0,  2,$76,$6B,$8E,$94,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_298C   o
                dc.w sprite_32_32
                dc.w $7171
                dc.w $9500 ! ((grp_3AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3AE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_8
                dc.w $7791
                dc.w $9500 ! ((grp_18E980 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E980 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7C69
                dc.w $9500 ! ((grp_DC200 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC200 / 2) >> 16)
                dc.w 2
