byte_2E035E:    dc.b   0,  7,$57,$47,$91,$82,$74,$64,$85,$5A
                                        ; DATA XREF: ROM:off_18B4   o
                dc.w sprite_32_32
                dc.w $6865
                dc.w $9500 ! ((grp_21A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_21A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_21A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $5945
                dc.w $9500 ! ((grp_12B2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12B2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12B2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7945
                dc.w $9500 ! ((grp_63B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_63B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_63B00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_32
                dc.w $8865
                dc.w $9500 ! ((grp_A7200 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7200 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $906B
                dc.w $9500 ! ((grp_198A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_198A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198A00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $514D
                dc.w $9500 ! ((grp_B97C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B97C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B97C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $894E
                dc.w $9500 ! ((grp_B9800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $645D
                dc.w $9500 ! ((grp_EB9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB9E0 / 2) >> 16)
                dc.w 1
