byte_2EDAE4:    dc.b   0,  6,$6A,$69,$99,$96,$7F,$7D,$80,$7D
                                        ; DATA XREF: ROM:off_22F0   o
                dc.w sprite_24_16
                dc.w $7381
                dc.w $9500 ! ((grp_164980 / 2) & $00FF)
                dc.w $9600 ! (((grp_164980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164980 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7571
                dc.w $9500 ! ((grp_164A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_164A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_164A40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6573
                dc.w $9500 ! ((grp_88D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8D71
                dc.w $9500 ! ((grp_19C4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C4E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8669
                dc.w $9500 ! ((grp_D87C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D87C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D87C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $957E
                dc.w $9500 ! ((grp_EFFE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EFFE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EFFE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $956D
                dc.w $9500 ! ((grp_F0000 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0000 / 2) >> 16)
                dc.w 1
