byte_2E2BAA:    dc.b   0,  8,$6F,$72,$8E,$8F,$7B,$78,$85,$66
                                        ; DATA XREF: ROM:off_1A54   o
                dc.w sprite_16_32
                dc.w $8168
                dc.w $9500 ! ((grp_62A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_62A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7180
                dc.w $9500 ! ((grp_7FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7FF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6178
                dc.w $9500 ! ((grp_99E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_99E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99E80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6070
                dc.w $9500 ! ((grp_D1680 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6B8B
                dc.w $9500 ! ((grp_D16C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D16C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D16C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8060
                dc.w $9500 ! ((grp_D1700 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1700 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8188
                dc.w $9500 ! ((grp_D1740 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9170
                dc.w $9500 ! ((grp_B8A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B8A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B8A40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9188
                dc.w $9500 ! ((grp_EAC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAC80 / 2) >> 16)
                dc.w 1
