byte_2F2C12:    dc.b   0,  6,$72,$6B,$91,$82,$81,$76,$82,$76
                                        ; DATA XREF: ROM:off_275C   o
                dc.w sprite_8_24
                dc.w $7868
                dc.w $9500 ! ((grp_19D500 / 2) & $00FF)
                dc.w $9600 ! (((grp_19D500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19D500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7880
                dc.w $9500 ! ((grp_DA5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA5C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8874
                dc.w $9500 ! ((grp_DA640 / 2) & $00FF)
                dc.w $9600 ! (((grp_DA640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DA640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $706D
                dc.w $9500 ! ((grp_BFF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFF40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8070
                dc.w $9500 ! ((grp_BFFC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFFC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFFC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8069
                dc.w $9500 ! ((grp_F17C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F17C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F17C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D6C
                dc.w $9500 ! ((grp_F1840 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1840 / 2) >> 16)
                dc.w 1
