byte_2CD49C:    dc.b   0,  1,$98,$6C,$A8,$7A,$8D,$94,$8E,$94
                                        ; DATA XREF: ROM:off_8C0   o
                dc.w sprite_24_16
                dc.w $966A
                dc.w $9500 ! ((grp_156700 / 2) & $00FF)
                dc.w $9600 ! (((grp_156700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156700 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $9E7A
                dc.w $9500 ! ((grp_C7800 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7800 / 2) >> 16)
                dc.w 2
