byte_2FF3B2:    dc.b   0,  3,$1D,$6F,$F2,$90,$86,$7B,$87,$7B
                                        ; DATA XREF: ROM:off_3574   o
                dc.w sprite_32_24
                dc.w $9270
                dc.w $9500 ! ((grp_13BDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13BDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13BDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $B270
                dc.w $9500 ! ((grp_13BF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_13BF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13BF40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $D270
                dc.w $9500 ! ((grp_13C0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C0C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $1878
                dc.w $9500 ! ((grp_96600 / 2) & $00FF)
                dc.w $9600 ! (((grp_96600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96600 / 2) >> 16)
                dc.w 4
