byte_2DEB90:    dc.b   0,  6,$6F,$60,$8E,$8F,$82,$70,$83,$68
                                        ; DATA XREF: ROM:off_17A8   o
                dc.w sprite_24_24
                dc.w $6C68
                dc.w $9500 ! ((grp_145EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_145EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_145EA0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $8364
                dc.w $9500 ! ((grp_176E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_176E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176E00 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6C88
                dc.w $9500 ! ((grp_D2600 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7480
                dc.w $9500 ! ((grp_D2640 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B58
                dc.w $9500 ! ((grp_B9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B9280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8480
                dc.w $9500 ! ((grp_B92C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B92C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B92C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8C88
                dc.w $9500 ! ((grp_EB440 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB440 / 2) >> 16)
                dc.w 1
