byte_2FF354:    dc.b   0,  6,$1D,$74,$9B,$90,$5A,$7D,$5B,$7D
                                        ; DATA XREF: ROM:off_3570   o
                dc.w sprite_32_16
                dc.w $3475
                dc.w $9500 ! ((grp_5A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_5A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5A900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $5475
                dc.w $9500 ! ((grp_5AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5AA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $7475
                dc.w $9500 ! ((grp_5AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5AB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $1B7D
                dc.w $9500 ! ((grp_E0B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9475
                dc.w $9500 ! ((grp_C6400 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6400 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $1685
                dc.w $9500 ! ((grp_F91E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F91E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F91E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $1E75
                dc.w $9500 ! ((grp_F91C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F91C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F91C0 / 2) >> 16)
                dc.w 1
