byte_2DD4A0:    dc.b   0,  5,$73,$5B,$8B,$7F,$89,$90,$80,$62
                                        ; DATA XREF: ROM:off_16C0   o
                dc.w sprite_16_32
                dc.w $856F
                dc.w $9500 ! ((grp_61D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $664F
                dc.w $9500 ! ((grp_15D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D300 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $6E5F
                dc.w $9500 ! ((grp_175180 / 2) & $00FF)
                dc.w $9600 ! (((grp_175180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_175180 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7677
                dc.w $9500 ! ((grp_7D480 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7E57
                dc.w $9500 ! ((grp_A5C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $864F
                dc.w $9500 ! ((grp_A5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5C80 / 2) >> 16)
                dc.w 4
