byte_2D14FC:    dc.b   0,  6,$66,$5E,$96,$8E,$84,$76,$85,$76
                                        ; DATA XREF: ROM:off_E10   o
                dc.w sprite_32_32
                dc.w $745D
                dc.w $9500 ! ((grp_15800 / 2) & $00FF)
                dc.w $9600 ! (((grp_15800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15800 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $5C65
                dc.w $9500 ! ((grp_FC040 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC040 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $717D
                dc.w $9500 ! ((grp_13F4E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F4E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F4E0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $946D
                dc.w $9500 ! ((grp_76480 / 2) & $00FF)
                dc.w $9600 ! (((grp_76480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_76480 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D7D
                dc.w $9500 ! ((grp_C9440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6985
                dc.w $9500 ! ((grp_B1D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A46C
                dc.w $9500 ! ((grp_B1DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1DC0 / 2) >> 16)
                dc.w 2
