byte_2E9EC2:    dc.b   0,  5,$91,$63,$A2,$71,$95,$72,$96,$72
                                        ; DATA XREF: ROM:off_1EE4   o
                dc.w sprite_24_24
                dc.w $955B
                dc.w $9500 ! ((grp_149800 / 2) & $00FF)
                dc.w $9600 ! (((grp_149800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149800 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7D73
                dc.w $9500 ! ((grp_50D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7D83
                dc.w $9500 ! ((grp_D7040 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $856B
                dc.w $9500 ! ((grp_D7080 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D63
                dc.w $9500 ! ((grp_EED60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EED60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EED60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9D73
                dc.w $9500 ! ((grp_EED80 / 2) & $00FF)
                dc.w $9600 ! (((grp_EED80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EED80 / 2) >> 16)
                dc.w 1
