byte_2D0890:    dc.b   0,  2,$55,$52,$AC,$8E,$79,$84,$7A,$84
                                        ; DATA XREF: ROM:off_D98   o
                dc.w sprite_24_24
                dc.w $6E79
                dc.w $9500 ! ((grp_13F840 / 2) & $00FF)
                dc.w $9600 ! (((grp_13F840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13F840 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_8
                dc.w $6688
                dc.w $9500 ! ((grp_E3AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8689
                dc.w $9500 ! ((grp_E3B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3B00 / 2) >> 16)
                dc.w 1
