byte_2EFFB8:    dc.b   0,  9,$44,$39,$BD,$86,$80,$8A,$81,$8A
                                        ; DATA XREF: ROM:off_25B0   o
                dc.w sprite_32_16
                dc.w $4175
                dc.w $9500 ! ((grp_53900 / 2) & $00FF)
                dc.w $9600 ! (((grp_53900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $9975
                dc.w $9500 ! ((grp_53A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $897D
                dc.w $9500 ! ((grp_6B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6175
                dc.w $9500 ! ((grp_8B100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7985
                dc.w $9500 ! ((grp_8B380 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B380 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7975
                dc.w $9500 ! ((grp_9E600 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $717D
                dc.w $9500 ! ((grp_18DAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18DAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18DAE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $B975
                dc.w $9500 ! ((grp_BF980 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7175
                dc.w $9500 ! ((grp_F1480 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1480 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D9D
                dc.w $9500 ! ((grp_F1560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1560 / 2) >> 16)
                dc.w 1
