byte_2CD458:    dc.b   0,  1,$95,$6E,$A7,$7C,$8C,$95,$8D,$95
                                        ; DATA XREF: ROM:off_8B8   o
                dc.w sprite_24_16
                dc.w $926F
                dc.w $9500 ! ((grp_156640 / 2) & $00FF)
                dc.w $9600 ! (((grp_156640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_156640 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $9667
                dc.w $9500 ! ((grp_C77C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C77C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C77C0 / 2) >> 16)
                dc.w 2
