byte_2FB738:    dc.b   0,  3,$72,$62,$89,$8E,$7D,$78,$7E,$78
                                        ; DATA XREF: ROM:off_2F90   o
                dc.w sprite_16_16
                dc.w $6C84
                dc.w $9500 ! ((grp_92A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_92A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7C78
                dc.w $9500 ! ((grp_AEB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7A60
                dc.w $9500 ! ((grp_1A0200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8486
                dc.w $9500 ! ((grp_C50C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C50C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C50C0 / 2) >> 16)
                dc.w 2
