byte_2D03F0:    dc.b   0,  2,$70,$71,$8C,$8F,$7E,$80,$7F,$80
                                        ; DATA XREF: ROM:off_D18   o
                dc.w sprite_24_24
                dc.w $777F
                dc.w $9500 ! ((grp_13E9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E9A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6E6F
                dc.w $9500 ! ((grp_46D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_46D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_46D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $8E6F
                dc.w $9500 ! ((grp_E3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3180 / 2) >> 16)
                dc.w 1
