byte_2E8BE2:    dc.b   0,  4,$76,$69,$81,$8D,$7E,$7B,$7D,$6E
                                        ; DATA XREF: ROM:off_1DBC   o
                dc.w sprite_8_32
                dc.w $776F
                dc.w $9500 ! ((grp_A5880 / 2) & $00FF)
                dc.w $9600 ! (((grp_A5880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A5880 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7F78
                dc.w $9500 ! ((grp_1967E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1967E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1967E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7067
                dc.w $9500 ! ((grp_CE880 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $778F
                dc.w $9500 ! ((grp_E8960 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8960 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8788
                dc.w $9500 ! ((grp_E8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8980 / 2) >> 16)
                dc.w 1
