byte_2F46EE:    dc.b   0,  1,$7E,$7A,$84,$86,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_29B4   o
                dc.w sprite_8_24
                dc.w $8078
                dc.w $9500 ! ((grp_19E1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19E1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19E1C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $787B
                dc.w $9500 ! ((grp_C1540 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1540 / 2) >> 16)
                dc.w 2
