byte_2DC690:    dc.b   0, $A,$71,$5E,$8A,$8D,$7E,$72,$7F,$60
                                        ; DATA XREF: ROM:00001630   o
                dc.w sprite_16_16
                dc.w $6966
                dc.w $9500 ! ((grp_77C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_77C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77C00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6D86
                dc.w $9500 ! ((grp_7DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $795E
                dc.w $9500 ! ((grp_7DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8486
                dc.w $9500 ! ((grp_7DA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7DA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7DA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8956
                dc.w $9500 ! ((grp_A4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7156
                dc.w $9500 ! ((grp_184F60 / 2) & $00FF)
                dc.w $9600 ! (((grp_184F60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184F60 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $747E
                dc.w $9500 ! ((grp_184FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_184FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $695E
                dc.w $9500 ! ((grp_CB100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $796E
                dc.w $9500 ! ((grp_CB0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7976
                dc.w $9500 ! ((grp_CB080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB080 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $915E
                dc.w $9500 ! ((grp_B3540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3540 / 2) >> 16)
                dc.w 2
