byte_2CEA4E:    dc.b   0,  9,$7A,  2,$90,$A8,$85,$55,$86,$55
                                        ; DATA XREF: ROM:off_B04   o
                dc.w sprite_8_32
                dc.w $7883
                dc.w $9500 ! ((grp_A2280 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8510
                dc.w $9500 ! ((grp_A2300 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8673
                dc.w $9500 ! ((grp_A2380 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8C2B
                dc.w $9500 ! ((grp_A2400 / 2) & $00FF)
                dc.w $9600 ! (((grp_A2400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A2400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7AA3
                dc.w $9500 ! ((grp_1839A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1839A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1839A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $875B
                dc.w $9500 ! ((grp_192280 / 2) & $00FF)
                dc.w $9600 ! (((grp_192280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192280 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8700
                dc.w $9500 ! ((grp_B0E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8793
                dc.w $9500 ! ((grp_B0E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8C4B
                dc.w $9500 ! ((grp_B0E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $787B
                dc.w $9500 ! ((grp_E2560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2560 / 2) >> 16)
                dc.w 1
