byte_2F7776:    dc.b   0, $D,$64,$42,$9E,$83,$85,$5C,$86,$5C
                                        ; DATA XREF: ROM:off_2BA4   o
                dc.w sprite_32_32
                dc.w $6F55
                dc.w $9500 ! ((grp_3F200 / 2) & $00FF)
                dc.w $9600 ! (((grp_3F200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3F200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_32
                dc.w $6F35
                dc.w $9500 ! ((grp_3F400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3F400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3F400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8F3D
                dc.w $9500 ! ((grp_118CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_118CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_118CC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8F5D
                dc.w $9500 ! ((grp_151600 / 2) & $00FF)
                dc.w $9600 ! (((grp_151600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_151600 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $6F75
                dc.w $9500 ! ((grp_56E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_56E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $A73D
                dc.w $9500 ! ((grp_90480 / 2) & $00FF)
                dc.w $9600 ! (((grp_90480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_90480 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $5F45
                dc.w $9500 ! ((grp_ADC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $675D
                dc.w $9500 ! ((grp_ADC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $673D
                dc.w $9500 ! ((grp_ADD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ADD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ADD00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $5751
                dc.w $9500 ! ((grp_C3280 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F65
                dc.w $9500 ! ((grp_C32C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C32C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C32C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4F57
                dc.w $9500 ! ((grp_F5CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5CC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F75
                dc.w $9500 ! ((grp_F5CE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5CE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5CE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F75
                dc.w $9500 ! ((grp_F5D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5D00 / 2) >> 16)
                dc.w 1
