word_2E9430:    dc.w 8                  ; DATA XREF: ROM:off_1E60   o
                dc.b $55 ; U
                dc.w sprite_24_16
                dc.w $8079
                dc.w $4E7A
                dc.b $4E
                dc.w sprite_32_32
                dc.w $523D
                dc.w $9500 ! ((grp_27A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_27A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_27A00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $723C
                dc.w $9500 ! ((grp_66E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $923E
                dc.w $9500 ! ((grp_66F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_66F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_66F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $525D
                dc.w $9500 ! ((grp_9C280 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8A43
                dc.w $9500 ! ((grp_A9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A9780 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $5835
                dc.w $9500 ! ((grp_18B560 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B560 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8246
                dc.w $9500 ! ((grp_19AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19AE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $725C
                dc.w $9500 ! ((grp_D6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $925E
                dc.w $9500 ! ((grp_EEB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EEB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EEB20 / 2) >> 16)
                dc.w 1
