byte_2D9282:    dc.b   0,  5,$61,$50,$9D,$7C,$7F,$66,$80,$66
                                        ; DATA XREF: ROM:off_1414   o
                dc.w sprite_24_32
                dc.w $6F56
                dc.w $9500 ! ((grp_1039C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1039C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1039C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8756
                dc.w $9500 ! ((grp_61700 / 2) & $00FF)
                dc.w $9600 ! (((grp_61700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $5F58
                dc.w $9500 ! ((grp_174C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_174C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174C40 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7276
                dc.w $9500 ! ((grp_99300 / 2) & $00FF)
                dc.w $9600 ! (((grp_99300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $975A
                dc.w $9500 ! ((grp_196A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_196A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196A80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $774E
                dc.w $9500 ! ((grp_CF000 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF000 / 2) >> 16)
                dc.w 2
