byte_2D091A:    dc.b   0,  3,$55,$52,$AC,$8E,$80,$7D,$81,$7D
                                        ; DATA XREF: ROM:off_DA4   o
                dc.w sprite_16_24
                dc.w $797B
                dc.w $9500 ! ((grp_171340 / 2) & $00FF)
                dc.w $9600 ! (((grp_171340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171340 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $896B
                dc.w $9500 ! ((grp_A3D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A3D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A3D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $816B
                dc.w $9500 ! ((grp_B1F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1F00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7188
                dc.w $9500 ! ((grp_E3B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3B40 / 2) >> 16)
                dc.w 1
