byte_2D4602:    dc.b   0,  3,$59,$62,$AB,$8C,$7C,$79,$7D,$79
                                        ; DATA XREF: ROM:off_10E4   o
                dc.w sprite_24_16
                dc.w $7B7B
                dc.w $9500 ! ((grp_159940 / 2) & $00FF)
                dc.w $9600 ! (((grp_159940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159940 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6A73
                dc.w $9500 ! ((grp_77A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_77A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77A80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8073
                dc.w $9500 ! ((grp_CAE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CAE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CAE00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686F
                dc.w $9500 ! ((grp_E57E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E57E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E57E0 / 2) >> 16)
                dc.w 1
