byte_2E8340:    dc.b   0,  9,$6F,$6E,$8E,$8F,$83,$63,$6E,$83
                                        ; DATA XREF: ROM:off_1D60   o
                dc.w sprite_24_32
                dc.w $6F6C
                dc.w $9500 ! ((grp_103240 / 2) & $00FF)
                dc.w $9600 ! (((grp_103240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103240 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $876C
                dc.w $9500 ! ((grp_15C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_15C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15C700 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6772
                dc.w $9500 ! ((grp_196480 / 2) & $00FF)
                dc.w $9600 ! (((grp_196480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196480 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6C8C
                dc.w $9500 ! ((grp_CE100 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $828C
                dc.w $9500 ! ((grp_CE140 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5F7A
                dc.w $9500 ! ((grp_B60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B60C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F5C
                dc.w $9500 ! ((grp_E8660 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8064
                dc.w $9500 ! ((grp_E8680 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8784
                dc.w $9500 ! ((grp_E86A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E86A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E86A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9F6D
                dc.w $9500 ! ((grp_E8500 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8500 / 2) >> 16)
                dc.w 1
