byte_2FF4D4:    dc.b   0,  7,$3A,$8E,$74,$CC,$57,$AD,$58,$AD
                                        ; DATA XREF: ROM:off_3588   o
                dc.w sprite_8_32
                dc.w $3FB4
                dc.w $9500 ! ((grp_AF300 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4FA4
                dc.w $9500 ! ((grp_AF280 / 2) & $00FF)
                dc.w $9600 ! (((grp_AF280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AF280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $47AC
                dc.w $9500 ! ((grp_1A0B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0B00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $579C
                dc.w $9500 ! ((grp_1A0AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0AA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $5F94
                dc.w $9500 ! ((grp_1A0A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A0A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A0A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $678C
                dc.w $9500 ! ((grp_1A09E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A09E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A09E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6F8C
                dc.w $9500 ! ((grp_C6440 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $37BC
                dc.w $9500 ! ((grp_F92C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F92C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F92C0 / 2) >> 16)
                dc.w 1
