byte_2D9C38:    dc.b   0, $E,$86,$67,$8F,$77,$7F,$6D,$86,$61
                                        ; DATA XREF: ROM:off_1470   o
                dc.w sprite_24_32
                dc.w $706D
                dc.w $9500 ! ((grp_101140 / 2) & $00FF)
                dc.w $9600 ! (((grp_101140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101140 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $785D
                dc.w $9500 ! ((grp_15AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15AD80 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $704D
                dc.w $9500 ! ((grp_98680 / 2) & $00FF)
                dc.w $9600 ! (((grp_98680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98680 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $788D
                dc.w $9500 ! ((grp_98900 / 2) & $00FF)
                dc.w $9600 ! (((grp_98900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98900 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7446
                dc.w $9500 ! ((grp_1855C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1855C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1855C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $886D
                dc.w $9500 ! ((grp_195280 / 2) & $00FF)
                dc.w $9600 ! (((grp_195280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_195280 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $688D
                dc.w $9500 ! ((grp_CC940 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC940 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7855
                dc.w $9500 ! ((grp_CCB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8885
                dc.w $9500 ! ((grp_CC980 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC980 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6852
                dc.w $9500 ! ((grp_B4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7055
                dc.w $9500 ! ((grp_B3480 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $686E
                dc.w $9500 ! ((grp_E7020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7020 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7065
                dc.w $9500 ! ((grp_E7040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7040 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8855
                dc.w $9500 ! ((grp_E6EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6EA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9053
                dc.w $9500 ! ((grp_E5A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A00 / 2) >> 16)
                dc.w 1
