byte_2D3B6E:    dc.b   0,  5,$6E,$65,$A8,$83,$8D,$72,$8E,$72
                                        ; DATA XREF: ROM:off_1064   o
                dc.w sprite_32_24
                dc.w $8167
                dc.w $9500 ! ((grp_122440 / 2) & $00FF)
                dc.w $9600 ! (((grp_122440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122440 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $6967
                dc.w $9500 ! ((grp_159040 / 2) & $00FF)
                dc.w $9600 ! (((grp_159040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_159040 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $A16A
                dc.w $9500 ! ((grp_77080 / 2) & $00FF)
                dc.w $9600 ! (((grp_77080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_77080 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7A7F
                dc.w $9500 ! ((grp_97D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_97D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $925F
                dc.w $9500 ! ((grp_CA200 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA200 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D5F
                dc.w $9500 ! ((grp_E48C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E48C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E48C0 / 2) >> 16)
                dc.w 1
