byte_2F67DC:    dc.b   0,$11,$69,$51,$A0,$8C,$6E,$7B,$6F,$7B
                                        ; DATA XREF: ROM:off_2B58   o
                dc.w sprite_32_32
                dc.w $7D59
                dc.w $9500 ! ((grp_3DC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_3DC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3DC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $7579
                dc.w $9500 ! ((grp_1375C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1375C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1375C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $3068
                dc.w $9500 ! ((grp_150F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_150F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150F40 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $3D7E
                dc.w $9500 ! ((grp_56600 / 2) & $00FF)
                dc.w $9600 ! (((grp_56600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_56600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $655F
                dc.w $9500 ! ((grp_6E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E100 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $A563
                dc.w $9500 ! ((grp_17F140 / 2) & $00FF)
                dc.w $9600 ! (((grp_17F140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17F140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $2E56
                dc.w $9500 ! ((grp_8F680 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $5D7F
                dc.w $9500 ! ((grp_8F700 / 2) & $00FF)
                dc.w $9600 ! (((grp_8F700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8F700 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8251
                dc.w $9500 ! ((grp_18EE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18EE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18EE60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7561
                dc.w $9500 ! ((grp_19EAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EAC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9D6F
                dc.w $9500 ! ((grp_19ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19ED00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9D57
                dc.w $9500 ! ((grp_19EB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_19EB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19EB20 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7551
                dc.w $9500 ! ((grp_C23C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C23C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C23C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9579
                dc.w $9500 ! ((grp_C2AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $2875
                dc.w $9500 ! ((grp_F5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5280 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $5D67
                dc.w $9500 ! ((grp_F4B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D87
                dc.w $9500 ! ((grp_F52A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F52A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F52A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8449
                dc.w $9500 ! ((grp_F4B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4B60 / 2) >> 16)
                dc.w 1
