byte_2DE2C4:    dc.b   0,  9,$72,$5B,$8F,$8E,$7F,$6F,$91,$5C
                                        ; DATA XREF: ROM:off_1758   o
                dc.w sprite_24_32
                dc.w $7262
                dc.w $9500 ! ((grp_10BDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10BDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10BDC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7282
                dc.w $9500 ! ((grp_4F900 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $9252
                dc.w $9500 ! ((grp_65200 / 2) & $00FF)
                dc.w $9600 ! (((grp_65200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_65200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $5A62
                dc.w $9500 ! ((grp_161D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_161D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $8252
                dc.w $9500 ! ((grp_84800 / 2) & $00FF)
                dc.w $9600 ! (((grp_84800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8A62
                dc.w $9500 ! ((grp_BB6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB6C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_ED300 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $844A
                dc.w $9500 ! ((grp_ED380 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $928A
                dc.w $9500 ! ((grp_ED340 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED340 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A26A
                dc.w $9500 ! ((grp_ED360 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED360 / 2) >> 16)
                dc.w 1
