byte_2F95EA:    dc.b   0,  1,$75,$5E,$8C,$72,$80,$68,$81,$68
                                        ; DATA XREF: ROM:off_2D5C   o
                dc.w sprite_24_16
                dc.w $725C
                dc.w $9500 ! ((grp_16A380 / 2) & $00FF)
                dc.w $9600 ! (((grp_16A380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16A380 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7B6D
                dc.w $9500 ! ((grp_F68A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F68A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F68A0 / 2) >> 16)
                dc.w 1
