byte_2FB916:    dc.b   0,  2,$6F,$6F,$91,$91,$80,$80,$81,$80
                                        ; DATA XREF: ROM:off_2FAC   o
                dc.w sprite_32_32
                dc.w $6D6D
                dc.w $9500 ! ((grp_44200 / 2) & $00FF)
                dc.w $9600 ! (((grp_44200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_44200 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $728D
                dc.w $9500 ! ((grp_A0780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $8D6D
                dc.w $9500 ! ((grp_AEA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_AEA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AEA00 / 2) >> 16)
                dc.w 4
