byte_2E26A0:    dc.b   0,  6,$64,$4E,$A1,$8E,$82,$6E,$83,$6E
                                        ; DATA XREF: ROM:off_1A30   o
                dc.w sprite_32_24
                dc.w $7C6B
                dc.w $9500 ! ((grp_12BEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12BEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12BEC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $874B
                dc.w $9500 ! ((grp_177880 / 2) & $00FF)
                dc.w $9600 ! (((grp_177880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_177880 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $648B
                dc.w $9500 ! ((grp_9AB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9AB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9AB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8463
                dc.w $9500 ! ((grp_1895E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1895E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1895E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9C64
                dc.w $9500 ! ((grp_198DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198DC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7283
                dc.w $9500 ! ((grp_D3100 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3100 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8C83
                dc.w $9500 ! ((grp_D30C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D30C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D30C0 / 2) >> 16)
                dc.w 2
