byte_2D155A:    dc.b   0,  6,$6D,$65,$97,$8E,$82,$79,$83,$79
                                        ; DATA XREF: ROM:off_E14   o
                dc.w sprite_24_32
                dc.w $7F74
                dc.w $9500 ! ((grp_FC1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FC1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FC1C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6F69
                dc.w $9500 ! ((grp_5D800 / 2) & $00FF)
                dc.w $9600 ! (((grp_5D800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5D800 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7F64
                dc.w $9500 ! ((grp_158200 / 2) & $00FF)
                dc.w $9600 ! (((grp_158200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_158200 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6789
                dc.w $9500 ! ((grp_184300 / 2) & $00FF)
                dc.w $9600 ! (((grp_184300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184300 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $977B
                dc.w $9500 ! ((grp_B1E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B1E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B1E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $636E
                dc.w $9500 ! ((grp_E3A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3A00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6769
                dc.w $9500 ! ((grp_E39E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E39E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E39E0 / 2) >> 16)
                dc.w 1
