byte_2DD408:    dc.b   0,  4,$76,$67,$8F,$83,$7D,$73,$88,$66
                                        ; DATA XREF: ROM:off_16B8   o
                dc.w sprite_24_32
                dc.w $7858
                dc.w $9500 ! ((grp_101A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_101A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_101A40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7878
                dc.w $9500 ! ((grp_142E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_142E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_142E40 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $6062
                dc.w $9500 ! ((grp_15B740 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B740 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $905C
                dc.w $9500 ! ((grp_1956A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1956A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1956A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7078
                dc.w $9500 ! ((grp_E7620 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7620 / 2) >> 16)
                dc.w 1
