byte_2ED47E:    dc.b   0,  8,$69,$56,$92,$91,$7F,$6E,$80,$6E
                                        ; DATA XREF: ROM:off_229C   o
                dc.w sprite_24_32
                dc.w $6E59
                dc.w $9500 ! ((grp_111AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_111AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_111AC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8660
                dc.w $9500 ! ((grp_17B900 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B900 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5E5B
                dc.w $9500 ! ((grp_89000 / 2) & $00FF)
                dc.w $9600 ! (((grp_89000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89000 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7F81
                dc.w $9500 ! ((grp_88F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_88F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_88F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6951
                dc.w $9500 ! ((grp_18CD60 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CD60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CD60 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7179
                dc.w $9500 ! ((grp_18CDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CDC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6979
                dc.w $9500 ! ((grp_BECC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BECC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BECC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9659
                dc.w $9500 ! ((grp_BED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BED00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F82
                dc.w $9500 ! ((grp_F0220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0220 / 2) >> 16)
                dc.w 1
