byte_2CCFA6:    dc.b   0,  4,$65,$67,$9A,$86,$7F,$76,$80,$76
                                        ; DATA XREF: ROM:off_85C   o
                dc.w sprite_32_24
                dc.w $6A6D
                dc.w $9500 ! ((grp_11F740 / 2) & $00FF)
                dc.w $9600 ! (((grp_11F740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11F740 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8A71
                dc.w $9500 ! ((grp_16FCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16FCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16FCC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $636F
                dc.w $9500 ! ((grp_E2100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F65
                dc.w $9500 ! ((grp_E2120 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2120 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2120 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C66
                dc.w $9500 ! ((grp_E2140 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2140 / 2) >> 16)
                dc.w 1
