byte_2F39C6:    dc.b   0,  8,$6B,$5D,$96,$8A,$77,$77,$78,$77
                                        ; DATA XREF: ROM:off_27E4   o
                dc.w sprite_32_32
                dc.w $7C6B
                dc.w $9500 ! ((grp_39600 / 2) & $00FF)
                dc.w $9600 ! (((grp_39600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_39600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_16
                dc.w $675B
                dc.w $9500 ! ((grp_55400 / 2) & $00FF)
                dc.w $9600 ! (((grp_55400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55400 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $4F63
                dc.w $9500 ! ((grp_1675C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1675C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1675C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6C6B
                dc.w $9500 ! ((grp_DB840 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB840 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7F8B
                dc.w $9500 ! ((grp_DB880 / 2) & $00FF)
                dc.w $9600 ! (((grp_DB880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DB880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7473
                dc.w $9500 ! ((grp_F2BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8763
                dc.w $9500 ! ((grp_F2B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2B80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8793
                dc.w $9500 ! ((grp_F2BA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2BA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2BA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9C72
                dc.w $9500 ! ((grp_F2BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2BC0 / 2) >> 16)
                dc.w 1
