byte_2F45F6:    dc.b   0,  2,$77,$6E,$8B,$92,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_2994   o
                dc.w sprite_24_32
                dc.w $766C
                dc.w $9500 ! ((grp_115B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_115B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_115B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $788C
                dc.w $9500 ! ((grp_8DC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8DC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8DC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7083
                dc.w $9500 ! ((grp_C1500 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1500 / 2) >> 16)
                dc.w 2
