byte_2FED8E:    dc.b   0,  1,$76,$74,$86,$84,$7E,$7C,$7F,$7C
                                        ; DATA XREF: ROM:off_34E4   o
                dc.w sprite_16_16
                dc.w $7977
                dc.w $9500 ! ((grp_96B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_96B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_96B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7472
                dc.w $9500 ! ((grp_F9780 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9780 / 2) >> 16)
                dc.w 1
