byte_2ED3C4:    dc.b   0,  2,$96,$79,$9E,$8A,$87,$83,$88,$83
                                        ; DATA XREF: ROM:off_2290   o
                dc.w sprite_32_24
                dc.w $7479
                dc.w $9500 ! ((grp_131EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_131EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_131EC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $9477
                dc.w $9500 ! ((grp_17B6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B6C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_16
                dc.w $6C81
                dc.w $9500 ! ((grp_BEC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEC00 / 2) >> 16)
                dc.w 2
