byte_2DA9E0:    dc.b   0,  6,$6C,$76,$8A,$8D,$9E,$7F,$85,$81
                                        ; DATA XREF: ROM:off_14E0   o
                dc.w sprite_32_16
                dc.w $5B87
                dc.w $9500 ! ((grp_4B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_4B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4B600 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6B67
                dc.w $9500 ! ((grp_61E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_61E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $837E
                dc.w $9500 ! ((grp_99500 / 2) & $00FF)
                dc.w $9600 ! (((grp_99500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_99500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $7B71
                dc.w $9500 ! ((grp_196FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_196FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_196FC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $695F
                dc.w $9500 ! ((grp_CFB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8376
                dc.w $9500 ! ((grp_E96A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E96A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E96A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9376
                dc.w $9500 ! ((grp_E96C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E96C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E96C0 / 2) >> 16)
                dc.w 1
