byte_2FFA7C:    dc.b   0,  2,$77,$1C,$85,$80,$7E,$4F,$7F,$4F
                                        ; DATA XREF: ROM:off_35C0   o
                dc.w sprite_16_32
                dc.w $791D
                dc.w $9500 ! ((grp_72400 / 2) & $00FF)
                dc.w $9600 ! (((grp_72400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_72400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_8
                dc.w $7A3D
                dc.w $9500 ! ((grp_F9620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9620 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B7D
                dc.w $9500 ! ((grp_F9640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9640 / 2) >> 16)
                dc.w 1
