byte_2D8AD2:    dc.b   0,  7,$74,$55,$92,$7A,$7F,$4E,$8B,$58
                                        ; DATA XREF: ROM:off_13CC   o
                dc.w sprite_32_32
                dc.w $724D
                dc.w $9500 ! ((grp_1CC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1CC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1CC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_16
                dc.w $616D
                dc.w $9500 ! ((grp_15D600 / 2) & $00FF)
                dc.w $9600 ! (((grp_15D600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15D600 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $6945
                dc.w $9500 ! ((grp_187360 / 2) & $00FF)
                dc.w $9600 ! (((grp_187360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_187360 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $876D
                dc.w $9500 ! ((grp_CF8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF8C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6665
                dc.w $9500 ! ((grp_E9560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9560 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6A4D
                dc.w $9500 ! ((grp_E9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $717D
                dc.w $9500 ! ((grp_E95A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E95A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E95A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9265
                dc.w $9500 ! ((grp_E95C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E95C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E95C0 / 2) >> 16)
                dc.w 1
