byte_2D7266:    dc.b   0,  5,$79,$62,$8B,$7A,$84,$6C,$87,$5D
                                        ; DATA XREF: ROM:off_12C4   o
                dc.w sprite_32_32
                dc.w $7957
                dc.w $9500 ! ((grp_24C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_24C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_24C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7187
                dc.w $9500 ! ((grp_84000 / 2) & $00FF)
                dc.w $9600 ! (((grp_84000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7D77
                dc.w $9500 ! ((grp_18A0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A0C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $794F
                dc.w $9500 ! ((grp_D4780 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4780 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7157
                dc.w $9500 ! ((grp_BB2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BB2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BB2C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $797F
                dc.w $9500 ! ((grp_ECE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECE40 / 2) >> 16)
                dc.w 1
