byte_2D74CA:    dc.b   0,  5,$78,$5D,$8D,$74,$82,$6C,$85,$58
                                        ; DATA XREF: ROM:off_12DC   o
                dc.w sprite_32_24
                dc.w $6D54
                dc.w $9500 ! ((grp_12CC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_12CC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12CC40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7374
                dc.w $9500 ! ((grp_84300 / 2) & $00FF)
                dc.w $9600 ! (((grp_84300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84300 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $5D5A
                dc.w $9500 ! ((grp_D4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4800 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $796C
                dc.w $9500 ! ((grp_D4840 / 2) & $00FF)
                dc.w $9600 ! (((grp_D4840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D4840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7384
                dc.w $9500 ! ((grp_ECF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECF80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D62
                dc.w $9500 ! ((grp_ECFA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ECFA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ECFA0 / 2) >> 16)
                dc.w 1
