byte_2D92D4:    dc.b   0,  8,$5F,$30,$A6,$6E,$82,$4F,$83,$4F
                                        ; DATA XREF: ROM:off_1418   o
                dc.w sprite_32_32
                dc.w $6D3A
                dc.w $9500 ! ((grp_1C400 / 2) & $00FF)
                dc.w $9600 ! (((grp_1C400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1C400 / 2) >> 16)
                dc.w $10
                dc.w sprite_24_32
                dc.w $8D45
                dc.w $9500 ! ((grp_103B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_103B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_103B40 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6D5A
                dc.w $9500 ! ((grp_126DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_126DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $5D3F
                dc.w $9500 ! ((grp_61800 / 2) & $00FF)
                dc.w $9600 ! (((grp_61800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_61800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $5D5F
                dc.w $9500 ! ((grp_7CB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7CB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7CB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8D3D
                dc.w $9500 ! ((grp_CF040 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF040 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8D65
                dc.w $9500 ! ((grp_CF080 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF080 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $992E
                dc.w $9500 ! ((grp_CF0C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF0C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF0C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $A555
                dc.w $9500 ! ((grp_E8EA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8EA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8EA0 / 2) >> 16)
                dc.w 1
