byte_2CF710:    dc.b   0,  1,$75,$77,$8A,$8F,$7F,$83,$80,$83
                                        ; DATA XREF: ROM:off_B78   o
                dc.w sprite_24_24
                dc.w $7475
                dc.w $9500 ! ((grp_13E880 / 2) & $00FF)
                dc.w $9600 ! (((grp_13E880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13E880 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7B8D
                dc.w $9500 ! ((grp_C8AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8AC0 / 2) >> 16)
                dc.w 2
