byte_2EEBEA:    dc.b   0, $A,$6E,$4E,$89,$8E,$84,$65,$85,$65
                                        ; DATA XREF: ROM:off_240C   o
                dc.w sprite_16_32
                dc.w $7B46
                dc.w $9500 ! ((grp_6AA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AA00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7B66
                dc.w $9500 ! ((grp_6AB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AB00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $8B56
                dc.w $9500 ! ((grp_6AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_6AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6AC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $8B46
                dc.w $9500 ! ((grp_89F80 / 2) & $00FF)
                dc.w $9600 ! (((grp_89F80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89F80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7286
                dc.w $9500 ! ((grp_9E180 / 2) & $00FF)
                dc.w $9600 ! (((grp_9E180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9E180 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6B4F
                dc.w $9500 ! ((grp_ABA80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABA80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABA80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7357
                dc.w $9500 ! ((grp_ABB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $9B51
                dc.w $9500 ! ((grp_ABB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ABB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ABB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B3E
                dc.w $9500 ! ((grp_D9540 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9540 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6358
                dc.w $9500 ! ((grp_BF680 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF680 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7347
                dc.w $9500 ! ((grp_BF6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF6C0 / 2) >> 16)
                dc.w 2
