byte_2D4820:    dc.b   0,  6,$6E,$5F,$91,$8F,$83,$7B,$81,$6B
                                        ; DATA XREF: ROM:off_10F8   o
                dc.w sprite_32_32
                dc.w $7675
                dc.w $9500 ! ((grp_18200 / 2) & $00FF)
                dc.w $9600 ! (((grp_18200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $606D
                dc.w $9500 ! ((grp_78180 / 2) & $00FF)
                dc.w $9600 ! (((grp_78180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7865
                dc.w $9500 ! ((grp_78100 / 2) & $00FF)
                dc.w $9600 ! (((grp_78100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_78100 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $6E74
                dc.w $9500 ! ((grp_A4D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $9675
                dc.w $9500 ! ((grp_B3640 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3640 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7B5D
                dc.w $9500 ! ((grp_E5CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5CA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E75
                dc.w $9500 ! ((grp_E5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5C80 / 2) >> 16)
                dc.w 1
