byte_2EB190:    dc.b   0,  6,$87,$52,$95,$62,$86,$5D,$87,$5D
                                        ; DATA XREF: ROM:off_1FE8   o
                dc.w sprite_24_16
                dc.w $7B59
                dc.w $9500 ! ((grp_163600 / 2) & $00FF)
                dc.w $9600 ! (((grp_163600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_163600 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $9351
                dc.w $9500 ! ((grp_19BA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19BA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19BA00 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7D69
                dc.w $9500 ! ((grp_D78C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D78C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D78C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8351
                dc.w $9500 ! ((grp_D7880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7357
                dc.w $9500 ! ((grp_BE040 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6B57
                dc.w $9500 ! ((grp_EF3A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF3A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF3A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9B61
                dc.w $9500 ! ((grp_EF3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF3C0 / 2) >> 16)
                dc.w 1
