byte_2DCAD6:    dc.b   0,  6,$6F,$56,$8E,$8F,$7F,$6D,$81,$55
                                        ; DATA XREF: ROM:off_165C   o
                dc.w sprite_24_32
                dc.w $7152
                dc.w $9500 ! ((grp_10C6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10C6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10C6C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $615D
                dc.w $9500 ! ((grp_84E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_84E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84E00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $8957
                dc.w $9500 ! ((grp_84D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_84D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_84D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $6B72
                dc.w $9500 ! ((grp_9B500 / 2) & $00FF)
                dc.w $9600 ! (((grp_9B500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9B500 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $7F7A
                dc.w $9500 ! ((grp_BBAC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BBAC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BBAC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6955
                dc.w $9500 ! ((grp_ED7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED7E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6D7A
                dc.w $9500 ! ((grp_ED800 / 2) & $00FF)
                dc.w $9600 ! (((grp_ED800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ED800 / 2) >> 16)
                dc.w 1
