byte_2E094C:    dc.b   0,  8,$45,$4C,$86,$71,$65,$5E,$77,$58
                                        ; DATA XREF: ROM:off_18F0   o
                dc.w sprite_16_32
                dc.w $5153
                dc.w $9500 ! ((grp_64700 / 2) & $00FF)
                dc.w $9600 ! (((grp_64700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6152
                dc.w $9500 ! ((grp_64800 / 2) & $00FF)
                dc.w $9600 ! (((grp_64800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7950
                dc.w $9500 ! ((grp_81900 / 2) & $00FF)
                dc.w $9600 ! (((grp_81900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_81900 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $4951
                dc.w $9500 ! ((grp_A7780 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7780 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $4152
                dc.w $9500 ! ((grp_198C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_198C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198C40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $714D
                dc.w $9500 ! ((grp_198CA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198CA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198CA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $514B
                dc.w $9500 ! ((grp_D2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $614A
                dc.w $9500 ! ((grp_D2D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D2D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D2D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $4949
                dc.w $9500 ! ((grp_EBCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBCC0 / 2) >> 16)
                dc.w 1
