byte_2D0A54:    dc.b   0,  4,$72,$77,$98,$8D,$85,$82,$86,$82
                                        ; DATA XREF: ROM:off_DB8   o
                dc.w sprite_24_24
                dc.w $7878
                dc.w $9500 ! ((grp_13FCC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13FCC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13FCC0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7D70
                dc.w $9500 ! ((grp_C9680 / 2) & $00FF)
                dc.w $9600 ! (((grp_C9680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C9680 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $907C
                dc.w $9500 ! ((grp_C96C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C96C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C96C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $707B
                dc.w $9500 ! ((grp_B2000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $9374
                dc.w $9500 ! ((grp_E3BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3BE0 / 2) >> 16)
                dc.w 1
