byte_2D1BD4:    dc.b   0,  5,$70,$6B,$92,$8F,$81,$7D,$82,$7D
                                        ; DATA XREF: ROM:off_E58   o
                dc.w sprite_32_32
                dc.w $6E69
                dc.w $9500 ! ((grp_16600 / 2) & $00FF)
                dc.w $9600 ! (((grp_16600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16600 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $6E89
                dc.w $9500 ! ((grp_97800 / 2) & $00FF)
                dc.w $9600 ! (((grp_97800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_97800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $8E70
                dc.w $9500 ! ((grp_193360 / 2) & $00FF)
                dc.w $9600 ! (((grp_193360 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_193360 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6671
                dc.w $9500 ! ((grp_B20C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B20C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B20C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8E89
                dc.w $9500 ! ((grp_E3D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3D60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $967B
                dc.w $9500 ! ((grp_E3D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3D40 / 2) >> 16)
                dc.w 1
