byte_2DF230:    dc.b   0,  5,$74,$56,$8E,$83,$7D,$6C,$83,$61
                                        ; DATA XREF: ROM:off_17E8   o
                dc.w sprite_32_32
                dc.w $6664
                dc.w $9500 ! ((grp_1A800 / 2) & $00FF)
                dc.w $9600 ! (((grp_1A800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1A800 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $865C
                dc.w $9500 ! ((grp_173C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_173C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173C80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7E54
                dc.w $9500 ! ((grp_CD240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8674
                dc.w $9500 ! ((grp_B5140 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8978
                dc.w $9500 ! ((grp_B5100 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7E5C
                dc.w $9500 ! ((grp_E77C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E77C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E77C0 / 2) >> 16)
                dc.w 1
