byte_2E394E:    dc.b   0,  3,$72,$64,$98,$93,$85,$7B,$86,$7B
                                        ; DATA XREF: ROM:off_1AE4   o
                dc.w sprite_24_32
                dc.w $7567
                dc.w $9500 ! ((grp_10E4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10E4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10E4C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $8D61
                dc.w $9500 ! ((grp_86B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_86B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_86B00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $718F
                dc.w $9500 ! ((grp_18B440 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B440 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7487
                dc.w $9500 ! ((grp_18B4A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B4A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B4A0 / 2) >> 16)
                dc.w 3
