byte_2FB9E8:    dc.b   0,  4,$6A,$6E,$96,$95,$80,$81,$81,$81
                                        ; DATA XREF: ROM:off_2FB8   o
                dc.w sprite_32_32
                dc.w $6874
                dc.w $9500 ! ((grp_43E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_43E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_43E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_8
                dc.w $706C
                dc.w $9500 ! ((grp_A0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_A0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A0700 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $9176
                dc.w $9500 ! ((grp_19FD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_19FD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19FD80 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7494
                dc.w $9500 ! ((grp_DF240 / 2) & $00FF)
                dc.w $9600 ! (((grp_DF240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DF240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $897C
                dc.w $9500 ! ((grp_C4C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4C80 / 2) >> 16)
                dc.w 2
