byte_2FF426:    dc.b   0,  5,$1E,$70,$F3,$90,$86,$7B,$87,$7B
                                        ; DATA XREF: ROM:off_357C   o
                dc.w sprite_32_24
                dc.w $D671
                dc.w $9500 ! ((grp_13C540 / 2) & $00FF)
                dc.w $9600 ! (((grp_13C540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13C540 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $BE71
                dc.w $9500 ! ((grp_16E040 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E040 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $1C79
                dc.w $9500 ! ((grp_F9220 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9220 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $1E81
                dc.w $9500 ! ((grp_F9260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B679
                dc.w $9500 ! ((grp_F9240 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9240 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $C681
                dc.w $9500 ! ((grp_F9280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9280 / 2) >> 16)
                dc.w 1
