byte_2EF960:    dc.b   0,  4,$62,$19,$95,$35,$7B,$27,$7C,$27
                                        ; DATA XREF: ROM:off_2540   o
                dc.w sprite_32_16
                dc.w $7217
                dc.w $9500 ! ((grp_53500 / 2) & $00FF)
                dc.w $9600 ! (((grp_53500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53500 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $5A1B
                dc.w $9500 ! ((grp_18D900 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D900 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $782F
                dc.w $9500 ! ((grp_18D960 / 2) & $00FF)
                dc.w $9600 ! (((grp_18D960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18D960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $642F
                dc.w $9500 ! ((grp_D9E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $921B
                dc.w $9500 ! ((grp_F1200 / 2) & $00FF)
                dc.w $9600 ! (((grp_F1200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F1200 / 2) >> 16)
                dc.w 1
