byte_2DF614:    dc.b   0,  7,$73,$61,$9F,$8F,$89,$78,$8A,$78
                                        ; DATA XREF: ROM:off_1818   o
                dc.w sprite_24_32
                dc.w $7A6A
                dc.w $9500 ! ((grp_107140 / 2) & $00FF)
                dc.w $9600 ! (((grp_107140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_107140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $9262
                dc.w $9500 ! ((grp_62D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_62D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $718A
                dc.w $9500 ! ((grp_D1CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $858A
                dc.w $9500 ! ((grp_D1D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8A5E
                dc.w $9500 ! ((grp_D1D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1D40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9282
                dc.w $9500 ! ((grp_D1D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_D1D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D1D80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7282
                dc.w $9500 ! ((grp_EAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7273
                dc.w $9500 ! ((grp_EAE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAE60 / 2) >> 16)
                dc.w 1
