byte_2E8DE2:    dc.b   0,  3,$77,$5C,$84,$7E,$7C,$68,$84,$60
                                        ; DATA XREF: ROM:off_1DDC   o
                dc.w sprite_24_24
                dc.w $7160
                dc.w $9500 ! ((grp_144040 / 2) & $00FF)
                dc.w $9600 ! (((grp_144040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_144040 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_8
                dc.w $7958
                dc.w $9500 ! ((grp_CE9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CE9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CE9C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7778
                dc.w $9500 ! ((grp_E8B60 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8B60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8B60 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E50
                dc.w $9500 ! ((grp_E8B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E8B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E8B80 / 2) >> 16)
                dc.w 1
