byte_2F315A:    dc.b   0,  9,$67,$5F,$88,$8C,$73,$75,$74,$75
                                        ; DATA XREF: ROM:off_2794   o
                dc.w sprite_32_16
                dc.w $565F
                dc.w $9500 ! ((grp_55700 / 2) & $00FF)
                dc.w $9600 ! (((grp_55700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_55700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $666F
                dc.w $9500 ! ((grp_17DC40 / 2) & $00FF)
                dc.w $9600 ! (((grp_17DC40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17DC40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $765E
                dc.w $9500 ! ((grp_ACC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_32
                dc.w $7E68
                dc.w $9500 ! ((grp_ACC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_ACC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_ACC80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $865E
                dc.w $9500 ! ((grp_19DD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DD40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6E87
                dc.w $9500 ! ((grp_C0DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $767E
                dc.w $9500 ! ((grp_C0E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5E7D
                dc.w $9500 ! ((grp_F2D20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2D20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2D20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E88
                dc.w $9500 ! ((grp_F2D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2D40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $867F
                dc.w $9500 ! ((grp_F2D60 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2D60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2D60 / 2) >> 16)
                dc.w 1
