byte_2DA894:    dc.b   0,  4,$6F,$72,$8E,$8F,$88,$7F,$95,$78
                                        ; DATA XREF: ROM:off_14C0   o
                dc.w sprite_32_32
                dc.w $7A71
                dc.w $9500 ! ((grp_1D200 / 2) & $00FF)
                dc.w $9600 ! (((grp_1D200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1D200 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $6A79
                dc.w $9500 ! ((grp_1753C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1753C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1753C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $9A78
                dc.w $9500 ! ((grp_7D680 / 2) & $00FF)
                dc.w $9600 ! (((grp_7D680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7D680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8669
                dc.w $9500 ! ((grp_CFA40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CFA40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CFA40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7271
                dc.w $9500 ! ((grp_E9640 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9640 / 2) >> 16)
                dc.w 1
