byte_2CD1F2:    dc.b   0,  4,$6A,$6E,$95,$90,$80,$80,$7F,$80
                                        ; DATA XREF: ROM:off_88C   o
                dc.w sprite_24_32
                dc.w $6D73
                dc.w $9500 ! ((grp_FA540 / 2) & $00FF)
                dc.w $9600 ! (((grp_FA540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FA540 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $8573
                dc.w $9500 ! ((grp_5BC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5BC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5BC00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $796B
                dc.w $9500 ! ((grp_1837C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1837C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1837C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $957A
                dc.w $9500 ! ((grp_B0B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0B00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6587
                dc.w $9500 ! ((grp_E2260 / 2) & $00FF)
                dc.w $9600 ! (((grp_E2260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E2260 / 2) >> 16)
                dc.w 1
