byte_2F92BE:    dc.b   0,  6,$66,$72,$90,$8F,$7B,$80,$7C,$80
                                        ; DATA XREF: ROM:off_2D24   o
                dc.w sprite_24_24
                dc.w $7772
                dc.w $9500 ! ((grp_1524A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1524A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1524A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6A8A
                dc.w $9500 ! ((grp_9FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FF00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6782
                dc.w $9500 ! ((grp_DE440 / 2) & $00FF)
                dc.w $9600 ! (((grp_DE440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DE440 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6185
                dc.w $9500 ! ((grp_F6680 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6680 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6F7A
                dc.w $9500 ! ((grp_F6660 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6660 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6660 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B6A
                dc.w $9500 ! ((grp_F6640 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6640 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F76
                dc.w $9500 ! ((grp_F6620 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6620 / 2) >> 16)
                dc.w 1
