byte_2D3A78:    dc.b   0,  6,$71,$5E,$87,$84,$7C,$6F,$7D,$6F
                                        ; DATA XREF: ROM:off_1058   o
                dc.w sprite_16_24
                dc.w $7568
                dc.w $9500 ! ((grp_171B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_171B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_171B80 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7360
                dc.w $9500 ! ((grp_184780 / 2) & $00FF)
                dc.w $9600 ! (((grp_184780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_184780 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7A7F
                dc.w $9500 ! ((grp_CA140 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D70
                dc.w $9500 ! ((grp_E4800 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4800 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7058
                dc.w $9500 ! ((grp_E4820 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4820 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4820 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8058
                dc.w $9500 ! ((grp_E4840 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4840 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $856C
                dc.w $9500 ! ((grp_E4860 / 2) & $00FF)
                dc.w $9600 ! (((grp_E4860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E4860 / 2) >> 16)
                dc.w 1
