byte_2FE2CC:    dc.b   0,  4,$73,$77,$89,$87,$77,$83,$78,$83
                                        ; DATA XREF: ROM:off_33B8   o
                dc.w sprite_24_16
                dc.w $7A79
                dc.w $9500 ! ((grp_16D8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_16D8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16D8C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7671
                dc.w $9500 ! ((grp_191680 / 2) & $00FF)
                dc.w $9600 ! (((grp_191680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191680 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7279
                dc.w $9500 ! ((grp_C6140 / 2) & $00FF)
                dc.w $9600 ! (((grp_C6140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C6140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6383
                dc.w $9500 ! ((grp_F8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8980 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $888E
                dc.w $9500 ! ((grp_F89E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F89E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F89E0 / 2) >> 16)
                dc.w 1
