byte_2D4CD6:    dc.b   0,  2,$6B,$78,$93,$8C,$7F,$82,$80,$82
                                        ; DATA XREF: ROM:off_1134   o
                dc.w sprite_32_24
                dc.w $6976
                dc.w $9500 ! ((grp_129F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_129F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_129F40 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $897E
                dc.w $9500 ! ((grp_80800 / 2) & $00FF)
                dc.w $9600 ! (((grp_80800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_80800 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $778E
                dc.w $9500 ! ((grp_EB0E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EB0E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EB0E0 / 2) >> 16)
                dc.w 1
