byte_2EB6E0:    dc.b   0,  4,$71,$55,$8F,$8D,$81,$82,$82,$82
                                        ; DATA XREF: ROM:off_2040   o
                dc.w sprite_32_32
                dc.w $6A6E
                dc.w $9500 ! ((grp_2B600 / 2) & $00FF)
                dc.w $9600 ! (((grp_2B600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_2B600 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8A6E
                dc.w $9500 ! ((grp_67900 / 2) & $00FF)
                dc.w $9600 ! (((grp_67900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7A8E
                dc.w $9500 ! ((grp_87680 / 2) & $00FF)
                dc.w $9600 ! (((grp_87680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87680 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6A8E
                dc.w $9500 ! ((grp_D7C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7C00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A8E
                dc.w $9500 ! ((grp_EF5E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF5E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF5E0 / 2) >> 16)
                dc.w 1
