byte_2E1DE0:    dc.b   0,  2,$73,$6A,$91,$88,$82,$79,$83,$79
                                        ; DATA XREF: ROM:off_19B0   o
                dc.w sprite_32_24
                dc.w $7468
                dc.w $9500 ! ((grp_128140 / 2) & $00FF)
                dc.w $9600 ! (((grp_128140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_128140 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7880
                dc.w $9500 ! ((grp_7E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_7E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7E400 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $6C67
                dc.w $9500 ! ((grp_B7540 / 2) & $00FF)
                dc.w $9600 ! (((grp_B7540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B7540 / 2) >> 16)
                dc.w 2
