byte_2E3870:    dc.b   0,  4,$6E,$66,$9F,$8F,$86,$7A,$87,$7A
                                        ; DATA XREF: ROM:off_1AD8   o
                dc.w sprite_24_24
                dc.w $7972
                dc.w $9500 ! ((grp_149380 / 2) & $00FF)
                dc.w $9600 ! (((grp_149380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_149380 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_9C000 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C000 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7E6A
                dc.w $9500 ! ((grp_9C080 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $9362
                dc.w $9500 ! ((grp_D6AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6AC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7182
                dc.w $9500 ! ((grp_EE9E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE9E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE9E0 / 2) >> 16)
                dc.w 1
