byte_2D4DA6:    dc.b   0,  6,$66,$5F,$8E,$8D,$7B,$79,$7C,$70
                                        ; DATA XREF: ROM:off_1144   o
                dc.w sprite_24_32
                dc.w $636E
                dc.w $9500 ! ((grp_FE2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FE2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FE2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_16
                dc.w $7B86
                dc.w $9500 ! ((grp_49800 / 2) & $00FF)
                dc.w $9600 ! (((grp_49800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_49800 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $7861
                dc.w $9500 ! ((grp_194500 / 2) & $00FF)
                dc.w $9600 ! (((grp_194500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194500 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8D7E
                dc.w $9500 ! ((grp_CB240 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $5B67
                dc.w $9500 ! ((grp_B3700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $738E
                dc.w $9500 ! ((grp_E5DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5DA0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7B5E
                dc.w $9500 ! ((grp_E5DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5DC0 / 2) >> 16)
                dc.w 1
