byte_2EB436:    dc.b   0,  1,$82,$4C,$91,$56,$81,$51,$82,$51
                                        ; DATA XREF: ROM:off_200C   o
                dc.w sprite_32_8
                dc.w $6F4B
                dc.w $9500 ! ((grp_9C700 / 2) & $00FF)
                dc.w $9600 ! (((grp_9C700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9C700 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8353
                dc.w $9500 ! ((grp_D7AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D7AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D7AC0 / 2) >> 16)
                dc.w 2
