byte_2E171C:    dc.b   0,  6,$71,$58,$93,$8F,$87,$6E,$88,$6E
                                        ; DATA XREF: ROM:off_1958   o
                dc.w sprite_32_24
                dc.w $7059
                dc.w $9500 ! ((grp_12E5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_12E5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_12E5C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7871
                dc.w $9500 ! ((grp_179B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_179B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179B00 / 2) >> 16)
                dc.w 6
                dc.w sprite_32_8
                dc.w $7189
                dc.w $9500 ! ((grp_9BB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9BB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9BB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F51
                dc.w $9500 ! ((grp_18AD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_18AD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18AD80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9053
                dc.w $9500 ! ((grp_19A5C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19A5C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19A5C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9854
                dc.w $9500 ! ((grp_BC840 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7349
                dc.w $9500 ! ((grp_EE220 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE220 / 2) >> 16)
                dc.w 1
