byte_2F34AC:    dc.b   0,  8,$69,$5F,$96,$89,$7A,$77,$7B,$77
                                        ; DATA XREF: ROM:off_27B0   o
                dc.w sprite_24_32
                dc.w $7B5D
                dc.w $9500 ! ((grp_114DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_114DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_114DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7D7D
                dc.w $9500 ! ((grp_14F560 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F560 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $5C63
                dc.w $9500 ! ((grp_8CF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8CF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8CF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6579
                dc.w $9500 ! ((grp_18E620 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E620 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E620 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $735D
                dc.w $9500 ! ((grp_19DE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DE00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $6C64
                dc.w $9500 ! ((grp_F2EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2EE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9369
                dc.w $9500 ! ((grp_F2F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2F00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $957E
                dc.w $9500 ! ((grp_F2F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2F20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9589
                dc.w $9500 ! ((grp_F2F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_F2F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F2F40 / 2) >> 16)
                dc.w 1
