byte_2D8218:    dc.b   0,  4,$6F,$65,$82,$82,$82,$60,$82,$63
                                        ; DATA XREF: ROM:off_1370   o
                dc.w sprite_32_24
                dc.w $6A62
                dc.w $9500 ! ((grp_1246C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1246C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1246C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $6E7A
                dc.w $9500 ! ((grp_79400 / 2) & $00FF)
                dc.w $9600 ! (((grp_79400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79400 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F5A
                dc.w $9500 ! ((grp_185440 / 2) & $00FF)
                dc.w $9600 ! (((grp_185440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185440 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7988
                dc.w $9500 ! ((grp_E6AE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6AE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6AE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8A72
                dc.w $9500 ! ((grp_E6B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6B00 / 2) >> 16)
                dc.w 1
