byte_2F026C:    dc.b   0,  2,$79,$57,$86,$87,$87,$69,$88,$69
                                        ; DATA XREF: ROM:off_25D0   o
                dc.w sprite_16_32
                dc.w $7F5C
                dc.w $9500 ! ((grp_6B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_6B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6B400 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_16
                dc.w $776B
                dc.w $9500 ! ((grp_BFB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8F6A
                dc.w $9500 ! ((grp_BFB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BFB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BFB40 / 2) >> 16)
                dc.w 2
