byte_2FC3E6:    dc.b   0,  1,$5F,$81,$70,$88,$67,$84,$68,$84
                                        ; DATA XREF: ROM:off_3104   o
                dc.w sprite_16_16
                dc.w $637F
                dc.w $9500 ! ((grp_92F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_92F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_92F00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $5B83
                dc.w $9500 ! ((grp_F7E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F7E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F7E00 / 2) >> 16)
                dc.w 1
