byte_2CC070:    dc.b   0,  1,$82,$82,$8C,$93,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_6D0   o
                dc.w sprite_8_24
                dc.w $867D
                dc.w $9500 ! ((grp_191A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_191A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191A40 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $7E85
                dc.w $9500 ! ((grp_AFDC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_AFDC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_AFDC0 / 2) >> 16)
                dc.w 2
