byte_2DBC38:    dc.b   0,  3,$6C,$69,$86,$8C,$79,$7A,$70,$6A
                                        ; DATA XREF: ROM:off_15B0   o
                dc.w sprite_32_16
                dc.w $6E7B
                dc.w $9500 ! ((grp_4A000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6E6B
                dc.w $9500 ! ((grp_79C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_79C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_79C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $758B
                dc.w $9500 ! ((grp_185860 / 2) & $00FF)
                dc.w $9600 ! (((grp_185860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185860 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $7E73
                dc.w $9500 ! ((grp_E71C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E71C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E71C0 / 2) >> 16)
                dc.w 1
