byte_2F49CA:    dc.b   0,  4,$69,$67,$A2,$93,$83,$7D,$83,$7D
                                        ; DATA XREF: ROM:off_29FC   o
                dc.w sprite_32_32
                dc.w $6675
                dc.w $9500 ! ((grp_3B400 / 2) & $00FF)
                dc.w $9600 ! (((grp_3B400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_3B400 / 2) >> 16)
                dc.w $10
                dc.w sprite_32_24
                dc.w $826D
                dc.w $9500 ! ((grp_136E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_136E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_136E40 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $8685
                dc.w $9500 ! ((grp_150640 / 2) & $00FF)
                dc.w $9600 ! (((grp_150640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_150640 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_16
                dc.w $6E65
                dc.w $9500 ! ((grp_8E100 / 2) & $00FF)
                dc.w $9600 ! (((grp_8E100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8E100 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $8265
                dc.w $9500 ! ((grp_DC300 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC300 / 2) >> 16)
                dc.w 2
