byte_2D0B0E:    dc.b   0,  9,$6F,$65,$90,$8F,$8E,$78,$8F,$78
                                        ; DATA XREF: ROM:off_DC4   o
                dc.w sprite_24_32
                dc.w $7571
                dc.w $9500 ! ((grp_FB8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_FB8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_FB8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $9567
                dc.w $9500 ! ((grp_13ED00 / 2) & $00FF)
                dc.w $9600 ! (((grp_13ED00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13ED00 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_16
                dc.w $7561
                dc.w $9500 ! ((grp_47200 / 2) & $00FF)
                dc.w $9600 ! (((grp_47200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_47200 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $6572
                dc.w $9500 ! ((grp_5CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_5CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_5CE00 / 2) >> 16)
                dc.w 8
                dc.w sprite_8_24
                dc.w $8D71
                dc.w $9500 ! ((grp_192E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_192E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192E80 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $AD66
                dc.w $9500 ! ((grp_192EE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_192EE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_192EE0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $656A
                dc.w $9500 ! ((grp_C8E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C8E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C8E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6D62
                dc.w $9500 ! ((grp_E35C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E35C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E35C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8159
                dc.w $9500 ! ((grp_E35E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E35E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E35E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $B570
                dc.w $9500 ! ((grp_E3600 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3600 / 2) >> 16)
                dc.w 1
