byte_2F414C:    dc.b   0,  2,$7A,$78,$88,$89,$7C,$80,$7C,$7E
                                        ; DATA XREF: ROM:off_28E0   o
                dc.w sprite_16_16
                dc.w $787E
                dc.w $9500 ! ((grp_8D980 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D980 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7B76
                dc.w $9500 ! ((grp_DC1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_DC1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DC1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $887E
                dc.w $9500 ! ((grp_F3580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3580 / 2) >> 16)
                dc.w 1
