byte_2DB42A:    dc.b   0,  7,$5F,$5C,$9F,$8F,$7F,$75,$80,$75
                                        ; DATA XREF: ROM:off_154C   o
                dc.w sprite_32_16
                dc.w $6D5B
                dc.w $9500 ! ((grp_4FF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_4FF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4FF00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $7973
                dc.w $9500 ! ((grp_179440 / 2) & $00FF)
                dc.w $9600 ! (((grp_179440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_179440 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $726B
                dc.w $9500 ! ((grp_18A900 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A900 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $8D5A
                dc.w $9500 ! ((grp_18A960 / 2) & $00FF)
                dc.w $9600 ! (((grp_18A960 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18A960 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $5D5E
                dc.w $9500 ! ((grp_D5E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $838B
                dc.w $9500 ! ((grp_D5E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D5E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D5E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7183
                dc.w $9500 ! ((grp_BC1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BC1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BC1C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6566
                dc.w $9500 ! ((grp_EDD20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EDD20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EDD20 / 2) >> 16)
                dc.w 1
