byte_2D07F0:    dc.b   0,  1,$71,$78,$89,$84,$80,$81,$2A,$35
                                        ; DATA XREF: ROM:off_D88   o
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_157900 / 2) & $00FF)
                dc.w $9600 ! (((grp_157900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_157900 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6C76
                dc.w $9500 ! ((grp_E3560 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3560 / 2) >> 16)
                dc.w 1
