byte_2CD634:    dc.b   0,  3,$74,$64,$83,$86,$82,$8F,$81,$8F
                                        ; DATA XREF: ROM:off_8F0   o
                dc.w sprite_24_32
                dc.w $6D67
                dc.w $9500 ! ((grp_F9DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9DC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_16
                dc.w $7883
                dc.w $9500 ! ((grp_73C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_73C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_73C80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $735F
                dc.w $9500 ! ((grp_C7A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C7A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C7A80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8573
                dc.w $9500 ! ((grp_B0700 / 2) & $00FF)
                dc.w $9600 ! (((grp_B0700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B0700 / 2) >> 16)
                dc.w 2
