byte_2F2542:    dc.b   0,  3,$75,$4B,$8C,$7F,$80,$69,$81,$69
                                        ; DATA XREF: ROM:off_2704   o
                dc.w sprite_24_24
                dc.w $7652
                dc.w $9500 ! ((grp_14DA60 / 2) & $00FF)
                dc.w $9600 ! (((grp_14DA60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14DA60 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7C6A
                dc.w $9500 ! ((grp_17CBC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17CBC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17CBC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $6E5C
                dc.w $9500 ! ((grp_F18C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F18C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F18C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C6B
                dc.w $9500 ! ((grp_F18A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F18A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F18A0 / 2) >> 16)
                dc.w 1
