byte_2F9102:    dc.b   0,  4,$71,$5F,$91,$8B,$81,$75,$82,$75
                                        ; DATA XREF: ROM:off_2D0C   o
                dc.w sprite_24_32
                dc.w $726E
                dc.w $9500 ! ((grp_11A040 / 2) & $00FF)
                dc.w $9600 ! (((grp_11A040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_11A040 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $7366
                dc.w $9500 ! ((grp_9FD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FD80 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $795E
                dc.w $9500 ! ((grp_9FE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9FE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9FE00 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8A7C
                dc.w $9500 ! ((grp_C3EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C3EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C3EC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6A79
                dc.w $9500 ! ((grp_F6560 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6560 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6560 / 2) >> 16)
                dc.w 1
