byte_2F9BEE:    dc.b   0,  5,$7B,$5B,$8F,$8F,$83,$75,$84,$75
                                        ; DATA XREF: ROM:off_2DCC   o
                dc.w sprite_32_24
                dc.w $6A7A
                dc.w $9500 ! ((grp_13A2C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_13A2C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13A2C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_24
                dc.w $6D62
                dc.w $9500 ! ((grp_13A440 / 2) & $00FF)
                dc.w $9600 ! (((grp_13A440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_13A440 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $8A7A
                dc.w $9500 ! ((grp_180640 / 2) & $00FF)
                dc.w $9600 ! (((grp_180640 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_180640 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_8
                dc.w $7A5A
                dc.w $9500 ! ((grp_1905A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1905A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1905A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8D62
                dc.w $9500 ! ((grp_19F9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19F9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19F9C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $956A
                dc.w $9500 ! ((grp_C4780 / 2) & $00FF)
                dc.w $9600 ! (((grp_C4780 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C4780 / 2) >> 16)
                dc.w 2
