byte_2DF46E:    dc.b   0,  5,$71,$57,$8C,$83,$7F,$6C,$86,$60
                                        ; DATA XREF: ROM:off_1804   o
                dc.w sprite_32_32
                dc.w $6D63
                dc.w $9500 ! ((grp_1AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1AC00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_24
                dc.w $8A5C
                dc.w $9500 ! ((grp_173D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_173D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_173D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7C53
                dc.w $9500 ! ((grp_7AB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_16
                dc.w $8778
                dc.w $9500 ! ((grp_B5240 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5240 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6675
                dc.w $9500 ! ((grp_E7940 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7940 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7940 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7F83
                dc.w $9500 ! ((grp_E5A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5A80 / 2) >> 16)
                dc.w 1
