byte_2ED236:    dc.b   0,  5,$86,$63,$92,$86,$84,$79,$85,$79
                                        ; DATA XREF: ROM:off_227C   o
                dc.w sprite_32_32
                dc.w $6671
                dc.w $9500 ! ((grp_30E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_30E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_30E00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8671
                dc.w $9500 ! ((grp_68E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_68E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_68E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_8
                dc.w $7D69
                dc.w $9500 ! ((grp_9D980 / 2) & $00FF)
                dc.w $9600 ! (((grp_9D980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9D980 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $8061
                dc.w $9500 ! ((grp_18CD00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18CD00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18CD00 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $9671
                dc.w $9500 ! ((grp_19C6C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19C6C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19C6C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9E72
                dc.w $9500 ! ((grp_BEC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BEC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BEC80 / 2) >> 16)
                dc.w 2
