byte_2E0CFC:    dc.b   0, $D,$72,$5A,$8E,$8E,$7A,$45,$78,$30
                                        ; DATA XREF: ROM:off_1910   o
                dc.w sprite_24_16
                dc.w $753E
                dc.w $9500 ! ((grp_15BC80 / 2) & $00FF)
                dc.w $9600 ! (((grp_15BC80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15BC80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $543F
                dc.w $9500 ! ((grp_7B080 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B080 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $832E
                dc.w $9500 ! ((grp_7AF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $932B
                dc.w $9500 ! ((grp_7B000 / 2) & $00FF)
                dc.w $9600 ! (((grp_7B000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7B000 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6336
                dc.w $9500 ! ((grp_185EC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185EC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185EC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $695D
                dc.w $9500 ! ((grp_185F20 / 2) & $00FF)
                dc.w $9600 ! (((grp_185F20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185F20 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $7B4E
                dc.w $9500 ! ((grp_185E60 / 2) & $00FF)
                dc.w $9600 ! (((grp_185E60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185E60 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $632E
                dc.w $9500 ! ((grp_CD600 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD600 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6540
                dc.w $9500 ! ((grp_CD4C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD4C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD4C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9254
                dc.w $9500 ! ((grp_CD480 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B2E
                dc.w $9500 ! ((grp_B54C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B54C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B54C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7956
                dc.w $9500 ! ((grp_E7B20 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8026
                dc.w $9500 ! ((grp_E7A40 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7A40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7A40 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A4C
                dc.w $9500 ! ((grp_E7B00 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7B00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7B00 / 2) >> 16)
                dc.w 1
