byte_2D4400:    dc.b   0,  7,$6E,$65,$94,$90,$7D,$77,$7E,$77
                                        ; DATA XREF: ROM:off_10C8   o
                dc.w sprite_24_16
                dc.w $767E
                dc.w $9500 ! ((grp_1597C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1597C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1597C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_24
                dc.w $8466
                dc.w $9500 ! ((grp_1723C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1723C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1723C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $6E73
                dc.w $9500 ! ((grp_1941A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1941A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1941A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $7C61
                dc.w $9500 ! ((grp_194200 / 2) & $00FF)
                dc.w $9600 ! (((grp_194200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194200 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $8E7A
                dc.w $9500 ! ((grp_B3000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B3000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B3000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6672
                dc.w $9500 ! ((grp_E5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6C62
                dc.w $9500 ! ((grp_E5460 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5460 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5460 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7468
                dc.w $9500 ! ((grp_E5480 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5480 / 2) >> 16)
                dc.w 1
