byte_2EE73E:    dc.b   0,  4,$7A,$62,$84,$9D,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_23D4   o
                dc.w sprite_16_16
                dc.w $7870
                dc.w $9500 ! ((grp_89D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7860
                dc.w $9500 ! ((grp_89D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_89D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $7880
                dc.w $9500 ! ((grp_89D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_89D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89D00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7898
                dc.w $9500 ! ((grp_D9500 / 2) & $00FF)
                dc.w $9600 ! (((grp_D9500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D9500 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7890
                dc.w $9500 ! ((grp_D94C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D94C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D94C0 / 2) >> 16)
                dc.w 2
