byte_2F35DE:    dc.b   0,  5,$69,$5F,$96,$89,$7B,$77,$7C,$77
                                        ; DATA XREF: ROM:off_27BC   o
                dc.w sprite_24_32
                dc.w $7B75
                dc.w $9500 ! ((grp_1150C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1150C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1150C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_24
                dc.w $7B5D
                dc.w $9500 ! ((grp_14F7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_14F7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14F7A0 / 2) >> 16)
                dc.w 9
                dc.w sprite_24_16
                dc.w $5B61
                dc.w $9500 ! ((grp_167BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_167BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167BC0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $6B7C
                dc.w $9500 ! ((grp_8D080 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D080 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $735D
                dc.w $9500 ! ((grp_19DE60 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DE60 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DE60 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $937E
                dc.w $9500 ! ((grp_C0F40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C0F40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C0F40 / 2) >> 16)
                dc.w 2
