byte_2EB0BE:    dc.b   0,  6,$81,$5B,$9E,$73,$89,$68,$8A,$68
                                        ; DATA XREF: ROM:off_1FDC   o
                dc.w sprite_16_32
                dc.w $8A5A
                dc.w $9500 ! ((grp_67700 / 2) & $00FF)
                dc.w $9600 ! (((grp_67700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_67700 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $725D
                dc.w $9500 ! ((grp_87380 / 2) & $00FF)
                dc.w $9600 ! (((grp_87380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_87380 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_24
                dc.w $825C
                dc.w $9500 ! ((grp_19B9A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19B9A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19B9A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $9A67
                dc.w $9500 ! ((grp_BE000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BE000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BE000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6F57
                dc.w $9500 ! ((grp_EF2E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF2E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF2E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7A6D
                dc.w $9500 ! ((grp_EF300 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF300 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A267
                dc.w $9500 ! ((grp_EF320 / 2) & $00FF)
                dc.w $9600 ! (((grp_EF320 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EF320 / 2) >> 16)
                dc.w 1
