byte_2F6D06:    dc.b   0,$15,$7B,$4F,$A4,$7F,$83,$7D,$84,$7D
                                        ; DATA XREF: ROM:off_2B6C   o
                dc.w sprite_24_32
                dc.w $8659
                dc.w $9500 ! ((grp_117340 / 2) & $00FF)
                dc.w $9600 ! (((grp_117340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_117340 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_32
                dc.w $B63B
                dc.w $9500 ! ((grp_1183C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1183C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1183C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $7649
                dc.w $9500 ! ((grp_6E200 / 2) & $00FF)
                dc.w $9600 ! (((grp_6E200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_6E200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7476
                dc.w $9500 ! ((grp_169180 / 2) & $00FF)
                dc.w $9600 ! (((grp_169180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_169180 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $8649
                dc.w $9500 ! ((grp_1690C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1690C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1690C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $917E
                dc.w $9500 ! ((grp_8FB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FB00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $9E50
                dc.w $9500 ! ((grp_8EF80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8EF80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8EF80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $AE64
                dc.w $9500 ! ((grp_8FB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_8FB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8FB80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6287
                dc.w $9500 ! ((grp_18F1C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F1C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F1C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_24_8
                dc.w $B633
                dc.w $9500 ! ((grp_18F220 / 2) & $00FF)
                dc.w $9600 ! (((grp_18F220 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18F220 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $4681
                dc.w $9500 ! ((grp_C2C40 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2C40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2C40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $A66C
                dc.w $9500 ! ((grp_C2C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $AE45
                dc.w $9500 ! ((grp_C2480 / 2) & $00FF)
                dc.w $9600 ! (((grp_C2480 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C2480 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7891
                dc.w $9500 ! ((grp_F53E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F53E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F53E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7E6E
                dc.w $9500 ! ((grp_F4BE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8C79
                dc.w $9500 ! ((grp_F4C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8D86
                dc.w $9500 ! ((grp_F5400 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5400 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8E93
                dc.w $9500 ! ((grp_F5420 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5420 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5420 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F41
                dc.w $9500 ! ((grp_F4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4BC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9E60
                dc.w $9500 ! ((grp_F4C20 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4C20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4C20 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A660
                dc.w $9500 ! ((grp_F5440 / 2) & $00FF)
                dc.w $9600 ! (((grp_F5440 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F5440 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $A648
                dc.w $9500 ! ((grp_F4A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_F4A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F4A00 / 2) >> 16)
                dc.w 1
