byte_2D53E4:    dc.b   0,  6,$6F,$78,$8E,$8F,$80,$83,$81,$7C
                                        ; DATA XREF: ROM:off_1188   o
                dc.w sprite_32_32
                dc.w $6C73
                dc.w $9500 ! ((grp_18C00 / 2) & $00FF)
                dc.w $9600 ! (((grp_18C00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18C00 / 2) >> 16)
                dc.w $10
                dc.w sprite_8_32
                dc.w $8C70
                dc.w $9500 ! ((grp_A4D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_A4D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A4D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7C93
                dc.w $9500 ! ((grp_CB800 / 2) & $00FF)
                dc.w $9600 ! (((grp_CB800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CB800 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $647F
                dc.w $9500 ! ((grp_E60A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E60A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E60A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $756B
                dc.w $9500 ! ((grp_E6100 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6100 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $886B
                dc.w $9500 ! ((grp_E60C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E60C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E60C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $948D
                dc.w $9500 ! ((grp_E60E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E60E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E60E0 / 2) >> 16)
                dc.w 1
