byte_2FF964:    dc.b   0,  4,$72,$32,$8A,$89,$81,$5F,$82,$5F
                                        ; DATA XREF: ROM:off_35B0   o
                dc.w sprite_16_32
                dc.w $7734
                dc.w $9500 ! ((grp_71D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_71D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71D00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_32
                dc.w $7854
                dc.w $9500 ! ((grp_71E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_71E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71E00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $7574
                dc.w $9500 ! ((grp_16E400 / 2) & $00FF)
                dc.w $9600 ! (((grp_16E400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16E400 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $7384
                dc.w $9500 ! ((grp_F9580 / 2) & $00FF)
                dc.w $9600 ! (((grp_F9580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F9580 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8384
                dc.w $9500 ! ((grp_F95A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F95A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F95A0 / 2) >> 16)
                dc.w 1
