byte_2CFCA4:    dc.b   0,  1,$7B,$7B,$83,$88,$7F,$81,$80,$81
                                        ; DATA XREF: ROM:off_C38   o
                dc.w sprite_16_16
                dc.w $7979
                dc.w $9500 ! ((grp_75280 / 2) & $00FF)
                dc.w $9600 ! (((grp_75280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_75280 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $7C89
                dc.w $9500 ! ((grp_E3020 / 2) & $00FF)
                dc.w $9600 ! (((grp_E3020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E3020 / 2) >> 16)
                dc.w 1
