byte_2D810A:    dc.b   0,  6,$7A,$5C,$89,$84,$88,$60,$79,$5D
                                        ; DATA XREF: ROM:off_1364   o
                dc.w sprite_32_24
                dc.w $715A
                dc.w $9500 ! ((grp_1279C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1279C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1279C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $7972
                dc.w $9500 ! ((grp_174E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_174E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_174E80 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $7D52
                dc.w $9500 ! ((grp_CF740 / 2) & $00FF)
                dc.w $9600 ! (((grp_CF740 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CF740 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $695D
                dc.w $9500 ! ((grp_B6E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6E40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8972
                dc.w $9500 ! ((grp_B6E80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B6E80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B6E80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7F8A
                dc.w $9500 ! ((grp_E9380 / 2) & $00FF)
                dc.w $9600 ! (((grp_E9380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E9380 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9177
                dc.w $9500 ! ((grp_E93A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E93A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E93A0 / 2) >> 16)
                dc.w 1
