byte_2F9988:    dc.b   0,  1,$77,$7A,$87,$84,$7F,$7F,$80,$7F
                                        ; DATA XREF: ROM:off_2DA0   o
                dc.w sprite_16_16
                dc.w $7B78
                dc.w $9500 ! ((grp_91300 / 2) & $00FF)
                dc.w $9600 ! (((grp_91300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_91300 / 2) >> 16)
                dc.w 4
                dc.w sprite_8_8
                dc.w $737E
                dc.w $9500 ! ((grp_F6CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F6CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F6CC0 / 2) >> 16)
                dc.w 1
