byte_2EED3C:    dc.b   0,  4,$74,$81,$8B,$8C,$7F,$86,$80,$86
                                        ; DATA XREF: ROM:off_2420   o
                dc.w sprite_24_24
                dc.w $777B
                dc.w $9500 ! ((grp_14CE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_14CE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14CE00 / 2) >> 16)
                dc.w 9
                dc.w sprite_8_16
                dc.w $6F83
                dc.w $9500 ! ((grp_BF700 / 2) & $00FF)
                dc.w $9600 ! (((grp_BF700 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BF700 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6789
                dc.w $9500 ! ((grp_F0A80 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0A80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0A80 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D73
                dc.w $9500 ! ((grp_F0AC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0AC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0AC0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8F88
                dc.w $9500 ! ((grp_F0AA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F0AA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F0AA0 / 2) >> 16)
                dc.w 1
