byte_2DCF5A:    dc.b   0, $A,$6D,$63,$8A,$82,$7C,$75,$78,$5F
                                        ; DATA XREF: ROM:off_1684   o
                dc.w sprite_32_16
                dc.w $636B
                dc.w $9500 ! ((grp_4A200 / 2) & $00FF)
                dc.w $9600 ! (((grp_4A200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4A200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $645B
                dc.w $9500 ! ((grp_15B200 / 2) & $00FF)
                dc.w $9600 ! (((grp_15B200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_15B200 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $737B
                dc.w $9500 ! ((grp_CCE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $836B
                dc.w $9500 ! ((grp_CCE80 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCE80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCE80 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8863
                dc.w $9500 ! ((grp_CCEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCEC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $897E
                dc.w $9500 ! ((grp_CCF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_CCF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CCF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $6883
                dc.w $9500 ! ((grp_B4BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8373
                dc.w $9500 ! ((grp_B4B80 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4B80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4B80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $5B70
                dc.w $9500 ! ((grp_E72C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E72C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E72C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6E80
                dc.w $9500 ! ((grp_E72E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E72E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E72E0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C63
                dc.w $9500 ! ((grp_E72A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E72A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E72A0 / 2) >> 16)
                dc.w 1
