byte_2D3848:    dc.b   0,  4,$91,$71,$C0,$87,$A8,$7C,$A9,$7C
                                        ; DATA XREF: ROM:off_1038   o
                dc.w sprite_32_24
                dc.w $9572
                dc.w $9500 ! ((grp_122BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_122BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_122BC0 / 2) >> 16)
                dc.w $C
                dc.w sprite_8_24
                dc.w $B572
                dc.w $9500 ! ((grp_194020 / 2) & $00FF)
                dc.w $9600 ! (((grp_194020 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_194020 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $9C6A
                dc.w $9500 ! ((grp_CA900 / 2) & $00FF)
                dc.w $9600 ! (((grp_CA900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CA900 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $BD75
                dc.w $9500 ! ((grp_B2D00 / 2) & $00FF)
                dc.w $9600 ! (((grp_B2D00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B2D00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8D7C
                dc.w $9500 ! ((grp_E5080 / 2) & $00FF)
                dc.w $9600 ! (((grp_E5080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E5080 / 2) >> 16)
                dc.w 1
