byte_2CC44C:    dc.b   0,  1,$82,$82,$8E,$97,$8B,$8A,$88,$89
                                        ; DATA XREF: ROM:off_758   o
                dc.w sprite_16_24
                dc.w $8080
                dc.w $9500 ! ((grp_16EF40 / 2) & $00FF)
                dc.w $9600 ! (((grp_16EF40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_16EF40 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_8
                dc.w $8498
                dc.w $9500 ! ((grp_E1240 / 2) & $00FF)
                dc.w $9600 ! (((grp_E1240 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E1240 / 2) >> 16)
                dc.w 1
