byte_2E4DD8:    dc.b   0,  9,$6F,$62,$88,$8E,$4B,$94,$78,$62
                                        ; DATA XREF: ROM:off_1B88   o
                dc.w sprite_32_16
                dc.w $7185
                dc.w $9500 ! ((grp_4F000 / 2) & $00FF)
                dc.w $9600 ! (((grp_4F000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_4F000 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $6A5D
                dc.w $9500 ! ((grp_82180 / 2) & $00FF)
                dc.w $9600 ! (((grp_82180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6A6D
                dc.w $9500 ! ((grp_82200 / 2) & $00FF)
                dc.w $9600 ! (((grp_82200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_82200 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6A7D
                dc.w $9500 ! ((grp_1898E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1898E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1898E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $8263
                dc.w $9500 ! ((grp_198FA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_198FA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_198FA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8A63
                dc.w $9500 ! ((grp_D35C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D35C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D35C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A5D
                dc.w $9500 ! ((grp_BA100 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA100 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA100 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7A6D
                dc.w $9500 ! ((grp_BA000 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9767
                dc.w $9500 ! ((grp_BA140 / 2) & $00FF)
                dc.w $9600 ! (((grp_BA140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BA140 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8F6B
                dc.w $9500 ! ((grp_EC340 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC340 / 2) >> 16)
                dc.w 1
