byte_2DC24A:    dc.b   0,  5,$71,$5B,$A7,$90,$8B,$64,$8C,$64
                                        ; DATA XREF: ROM:off_1604   o
                dc.w sprite_32_16
                dc.w $6A56
                dc.w $9500 ! ((grp_50900 / 2) & $00FF)
                dc.w $9600 ! (((grp_50900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50900 / 2) >> 16)
                dc.w 8
                dc.w sprite_32_16
                dc.w $8A5C
                dc.w $9500 ! ((grp_50A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_50A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_50A00 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_8
                dc.w $8A54
                dc.w $9500 ! ((grp_18B1A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18B1A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18B1A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $8A6C
                dc.w $9500 ! ((grp_D6880 / 2) & $00FF)
                dc.w $9600 ! (((grp_D6880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D6880 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6866
                dc.w $9500 ! ((grp_EE7C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE7C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE7C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $AA66
                dc.w $9500 ! ((grp_EE7E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EE7E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EE7E0 / 2) >> 16)
                dc.w 1
