byte_2FD6B0:    dc.b   0,  7,$5F,$46,$8B,$8D,$81,$69,$82,$69
                                        ; DATA XREF: ROM:off_3300   o
                dc.w sprite_16_32
                dc.w $7E60
                dc.w $9500 ! ((grp_71800 / 2) & $00FF)
                dc.w $9600 ! (((grp_71800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_71800 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7546
                dc.w $9500 ! ((grp_95A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_95A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95A00 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $7288
                dc.w $9500 ! ((grp_A1800 / 2) & $00FF)
                dc.w $9600 ! (((grp_A1800 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A1800 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $7E80
                dc.w $9500 ! ((grp_E02C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E02C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E02C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7956
                dc.w $9500 ! ((grp_F87A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F87A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F87A0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7C3E
                dc.w $9500 ! ((grp_F8260 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8260 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7D58
                dc.w $9500 ! ((grp_F87C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F87C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F87C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $8546
                dc.w $9500 ! ((grp_F8280 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8280 / 2) >> 16)
                dc.w 1
