byte_2E6D06:    dc.b   0,  6,$71,$64,$86,$8D,$81,$77,$7E,$67
                                        ; DATA XREF: ROM:off_1C8C   o
                dc.w sprite_24_32
                dc.w $6E5E
                dc.w $9500 ! ((grp_10A8C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_10A8C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_10A8C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_24
                dc.w $717E
                dc.w $9500 ! ((grp_178540 / 2) & $00FF)
                dc.w $9600 ! (((grp_178540 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_178540 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_24
                dc.w $8E66
                dc.w $9500 ! ((grp_1993C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1993C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1993C0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $665F
                dc.w $9500 ! ((grp_BAE40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAE40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAE40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8185
                dc.w $9500 ! ((grp_BAD40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAD40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAD40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $866C
                dc.w $9500 ! ((grp_BAD80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAD80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAD80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9667
                dc.w $9500 ! ((grp_BADC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_BADC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BADC0 / 2) >> 16)
                dc.w 2
