byte_2E2490:    dc.b   0,  4,$6F,$6B,$8E,$8F,$7D,$7A,$86,$6B
                                        ; DATA XREF: ROM:off_1A18   o
                dc.w sprite_32_24
                dc.w $6E68
                dc.w $9500 ! ((grp_126340 / 2) & $00FF)
                dc.w $9600 ! (((grp_126340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_126340 / 2) >> 16)
                dc.w $C
                dc.w sprite_32_8
                dc.w $6E88
                dc.w $9500 ! ((grp_98D80 / 2) & $00FF)
                dc.w $9600 ! (((grp_98D80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98D80 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7780
                dc.w $9500 ! ((grp_1862E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1862E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1862E0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $7460
                dc.w $9500 ! ((grp_CD840 / 2) & $00FF)
                dc.w $9600 ! (((grp_CD840 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CD840 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6677
                dc.w $9500 ! ((grp_E7FC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E7FC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E7FC0 / 2) >> 16)
                dc.w 1
