byte_2FDB3C:    dc.b   0,  9,$67,$56,$9D,$8D,$82,$71,$83,$71
                                        ; DATA XREF: ROM:off_3330   o
                dc.w sprite_24_24
                dc.w $8055
                dc.w $9500 ! ((grp_1549C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1549C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1549C0 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $7051
                dc.w $9500 ! ((grp_182140 / 2) & $00FF)
                dc.w $9600 ! (((grp_182140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_182140 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7378
                dc.w $9500 ! ((grp_95680 / 2) & $00FF)
                dc.w $9600 ! (((grp_95680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_95680 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $6F88
                dc.w $9500 ! ((grp_191260 / 2) & $00FF)
                dc.w $9600 ! (((grp_191260 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_191260 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $6A68
                dc.w $9500 ! ((grp_E0000 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0000 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $6E70
                dc.w $9500 ! ((grp_E0040 / 2) & $00FF)
                dc.w $9600 ! (((grp_E0040 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E0040 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $685D
                dc.w $9500 ! ((grp_C5C80 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5C80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5C80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $985D
                dc.w $9500 ! ((grp_C5CC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_C5CC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C5CC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6061
                dc.w $9500 ! ((grp_F85C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F85C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F85C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6854
                dc.w $9500 ! ((grp_F85E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_F85E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F85E0 / 2) >> 16)
                dc.w 1
