byte_2ED876:    dc.b   0,  6,$73,$63,$AD,$94,$8B,$79,$8C,$79
                                        ; DATA XREF: ROM:off_22D4   o
                dc.w sprite_24_24
                dc.w $866A
                dc.w $9500 ! ((grp_14C860 / 2) & $00FF)
                dc.w $9600 ! (((grp_14C860 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_14C860 / 2) >> 16)
                dc.w 9
                dc.w sprite_16_24
                dc.w $9E6B
                dc.w $9500 ! ((grp_17B9C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_17B9C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_17B9C0 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $7681
                dc.w $9500 ! ((grp_89500 / 2) & $00FF)
                dc.w $9600 ! (((grp_89500 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_89500 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $8682
                dc.w $9500 ! ((grp_9DA00 / 2) & $00FF)
                dc.w $9600 ! (((grp_9DA00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_9DA00 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6688
                dc.w $9500 ! ((grp_D8DC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8DC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8DC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $868A
                dc.w $9500 ! ((grp_D8E00 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8E00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8E00 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $9E63
                dc.w $9500 ! ((grp_D8E40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D8E40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D8E40 / 2) >> 16)
                dc.w 2
