byte_2DF51E:    dc.b   0,  5,$6F,$5A,$8C,$8E,$81,$72,$85,$67
                                        ; DATA XREF: ROM:off_180C   o
                dc.w sprite_32_32
                dc.w $7565
                dc.w $9500 ! ((grp_1AE00 / 2) & $00FF)
                dc.w $9600 ! (((grp_1AE00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1AE00 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_16
                dc.w $7385
                dc.w $9500 ! ((grp_7AC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_7AC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_7AC00 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $7D5D
                dc.w $9500 ! ((grp_185DA0 / 2) & $00FF)
                dc.w $9600 ! (((grp_185DA0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_185DA0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_16
                dc.w $6D6A
                dc.w $9500 ! ((grp_B5280 / 2) & $00FF)
                dc.w $9600 ! (((grp_B5280 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B5280 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7D55
                dc.w $9500 ! ((grp_E79C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E79C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E79C0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $956D
                dc.w $9500 ! ((grp_E79E0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E79E0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E79E0 / 2) >> 16)
                dc.w 1
