byte_2E0760:    dc.b   0,  6,$64,$56,$99,$81,$7E,$6B,$8E,$64
                                        ; DATA XREF: ROM:off_18D8   o
                dc.w sprite_32_32
                dc.w $6A54
                dc.w $9500 ! ((grp_22400 / 2) & $00FF)
                dc.w $9600 ! (((grp_22400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_22400 / 2) >> 16)
                dc.w $10
                dc.w sprite_16_32
                dc.w $8A5A
                dc.w $9500 ! ((grp_64200 / 2) & $00FF)
                dc.w $9600 ! (((grp_64200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_64200 / 2) >> 16)
                dc.w 8
                dc.w sprite_24_16
                dc.w $6A74
                dc.w $9500 ! ((grp_160000 / 2) & $00FF)
                dc.w $9600 ! (((grp_160000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160000 / 2) >> 16)
                dc.w 6
                dc.w sprite_8_32
                dc.w $625D
                dc.w $9500 ! ((grp_A7600 / 2) & $00FF)
                dc.w $9600 ! (((grp_A7600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_A7600 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $827A
                dc.w $9500 ! ((grp_189160 / 2) & $00FF)
                dc.w $9600 ! (((grp_189160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_189160 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_8
                dc.w $8274
                dc.w $9500 ! ((grp_EBBE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBBE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBBE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9A5F
                dc.w $9500 ! ((grp_EBC00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EBC00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EBC00 / 2) >> 16)
                dc.w 1
