byte_2E6472:    dc.b   0,  8,$6C,$60,$89,$8E,$76,$74,$74,$63
                                        ; DATA XREF: ROM:off_1C44   o
                dc.w sprite_24_16
                dc.w $6B59
                dc.w $9500 ! ((grp_160F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_160F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_160F00 / 2) >> 16)
                dc.w 6
                dc.w sprite_24_16
                dc.w $7B81
                dc.w $9500 ! ((grp_161080 / 2) & $00FF)
                dc.w $9600 ! (((grp_161080 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_161080 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B6C
                dc.w $9500 ! ((grp_83180 / 2) & $00FF)
                dc.w $9600 ! (((grp_83180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83180 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_16
                dc.w $6B69
                dc.w $9500 ! ((grp_83200 / 2) & $00FF)
                dc.w $9600 ! (((grp_83200 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_83200 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $6B8A
                dc.w $9500 ! ((grp_D3B40 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3B40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3B40 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7B79
                dc.w $9500 ! ((grp_D3BC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D3BC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D3BC0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $7B69
                dc.w $9500 ! ((grp_BAB40 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAB40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAB40 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $8361
                dc.w $9500 ! ((grp_BAB80 / 2) & $00FF)
                dc.w $9600 ! (((grp_BAB80 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_BAB80 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8371
                dc.w $9500 ! ((grp_EC880 / 2) & $00FF)
                dc.w $9600 ! (((grp_EC880 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EC880 / 2) >> 16)
                dc.w 1
