byte_2F382A:    dc.b   0,  9,$69,$5F,$96,$89,$7A,$78,$7B,$78
                                        ; DATA XREF: ROM:off_27D4   o
                dc.w sprite_24_32
                dc.w $7B6E
                dc.w $9500 ! ((grp_1153C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1153C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1153C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_24_16
                dc.w $7B5E
                dc.w $9500 ! ((grp_167D40 / 2) & $00FF)
                dc.w $9600 ! (((grp_167D40 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_167D40 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_16
                dc.w $5B64
                dc.w $9500 ! ((grp_8D300 / 2) & $00FF)
                dc.w $9600 ! (((grp_8D300 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8D300 / 2) >> 16)
                dc.w 4
                dc.w sprite_24_8
                dc.w $637D
                dc.w $9500 ! ((grp_18E7A0 / 2) & $00FF)
                dc.w $9600 ! (((grp_18E7A0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_18E7A0 / 2) >> 16)
                dc.w 3
                dc.w sprite_8_24
                dc.w $735D
                dc.w $9500 ! ((grp_19DEC0 / 2) & $00FF)
                dc.w $9600 ! (((grp_19DEC0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_19DEC0 / 2) >> 16)
                dc.w 3
                dc.w sprite_16_8
                dc.w $798E
                dc.w $9500 ! ((grp_DBF00 / 2) & $00FF)
                dc.w $9600 ! (((grp_DBF00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_DBF00 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9380
                dc.w $9500 ! ((grp_C1000 / 2) & $00FF)
                dc.w $9600 ! (((grp_C1000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_C1000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $6475
                dc.w $9500 ! ((grp_F3160 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3160 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3160 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $6B65
                dc.w $9500 ! ((grp_F3140 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3140 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3140 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $936D
                dc.w $9500 ! ((grp_F3180 / 2) & $00FF)
                dc.w $9600 ! (((grp_F3180 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F3180 / 2) >> 16)
                dc.w 1
