byte_2FE410:    dc.b   0,  2,$73,$79,$8B,$88,$7F,$7B,$80,$7B
                                        ; DATA XREF: ROM:off_33D0   o
                dc.w sprite_32_16
                dc.w $6E77
                dc.w $9500 ! ((grp_59900 / 2) & $00FF)
                dc.w $9600 ! (((grp_59900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_59900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_8
                dc.w $7487
                dc.w $9500 ! ((grp_E03C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_E03C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E03C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $7468
                dc.w $9500 ! ((grp_F8980 / 2) & $00FF)
                dc.w $9600 ! (((grp_F8980 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_F8980 / 2) >> 16)
                dc.w 1
