byte_2D7902:    dc.b   0,  8,$77,$65,$8F,$99,$8E,$7D,$96,$71
                                        ; DATA XREF: ROM:off_130C   o
                dc.w sprite_24_24
                dc.w $796E
                dc.w $9500 ! ((grp_141A00 / 2) & $00FF)
                dc.w $9600 ! (((grp_141A00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_141A00 / 2) >> 16)
                dc.w 9
                dc.w sprite_32_8
                dc.w $8A67
                dc.w $9500 ! ((grp_98580 / 2) & $00FF)
                dc.w $9600 ! (((grp_98580 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98580 / 2) >> 16)
                dc.w 4
                dc.w sprite_32_8
                dc.w $916F
                dc.w $9500 ! ((grp_98600 / 2) & $00FF)
                dc.w $9600 ! (((grp_98600 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_98600 / 2) >> 16)
                dc.w 4
                dc.w sprite_16_8
                dc.w $725E
                dc.w $9500 ! ((grp_CC340 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC340 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC340 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $7666
                dc.w $9500 ! ((grp_CC400 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC400 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC400 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8396
                dc.w $9500 ! ((grp_CC380 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC380 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC380 / 2) >> 16)
                dc.w 2
                dc.w sprite_16_8
                dc.w $8386
                dc.w $9500 ! ((grp_CC3C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_CC3C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_CC3C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_16
                dc.w $9177
                dc.w $9500 ! ((grp_B4000 / 2) & $00FF)
                dc.w $9600 ! (((grp_B4000 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_B4000 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $8A8E
                dc.w $9500 ! ((grp_E6760 / 2) & $00FF)
                dc.w $9600 ! (((grp_E6760 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_E6760 / 2) >> 16)
                dc.w 1
