byte_2F029A:    dc.b   0,  1,$79,$57,$86,$87,$7F,$69,$80,$69
                                        ; DATA XREF: ROM:off_25D4   o
                dc.w sprite_32_16
                dc.w $6E5D
                dc.w $9500 ! ((grp_53F00 / 2) & $00FF)
                dc.w $9600 ! (((grp_53F00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_53F00 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_16
                dc.w $7A6C
                dc.w $9500 ! ((grp_8B680 / 2) & $00FF)
                dc.w $9600 ! (((grp_8B680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_8B680 / 2) >> 16)
                dc.w 4
