byte_2E2C96:    dc.b   0,  6,$6F,$4D,$8E,$8F,$81,$53,$79,$49
                                        ; DATA XREF: ROM:off_1A5C   o
                dc.w sprite_24_32
                dc.w $7B52
                dc.w $9500 ! ((grp_1060C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_1060C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_1060C0 / 2) >> 16)
                dc.w $C
                dc.w sprite_16_32
                dc.w $6B56
                dc.w $9500 ! ((grp_62900 / 2) & $00FF)
                dc.w $9600 ! (((grp_62900 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_62900 / 2) >> 16)
                dc.w 8
                dc.w sprite_16_24
                dc.w $9359
                dc.w $9500 ! ((grp_176680 / 2) & $00FF)
                dc.w $9600 ! (((grp_176680 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_176680 / 2) >> 16)
                dc.w 6
                dc.w sprite_16_8
                dc.w $6B4E
                dc.w $9500 ! ((grp_D13C0 / 2) & $00FF)
                dc.w $9600 ! (((grp_D13C0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_D13C0 / 2) >> 16)
                dc.w 2
                dc.w sprite_8_8
                dc.w $636C
                dc.w $9500 ! ((grp_EAAE0 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAAE0 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAAE0 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $7246
                dc.w $9500 ! ((grp_EAB00 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAB00 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAB00 / 2) >> 16)
                dc.w 1
                dc.w sprite_8_8
                dc.w $9171
                dc.w $9500 ! ((grp_EAB20 / 2) & $00FF)
                dc.w $9600 ! (((grp_EAB20 / 2) >> 8) & $00FF)
                dc.w $9700 ! ((grp_EAB20 / 2) >> 16)
                dc.w 1
